### PR TITLE
Broken Keymap docs link

### PR DESCRIPTION
**Pull request by fabienheureux**

### CODE REVIEW

**Comment by jackhumbert** [comment]
Thanks!

**Comment by fabienheureux** [comment]
You're welcome, I will check links as I go through the doc and submit PR if needed 👍 
Thanks for the doc though, very clear and complete.

**Comment by jackhumbert** [comment]
Awesome :) if the file exists in the same directory, you can link to it like `/Keymap.md` instead of using the whole url and it'll appear on the website, as long as it's also linked in the `SUMMARY.md` (this weirdness is due to gitbook).

**Comment by fredizzimo** [comment]
@jackhumbert, does the Gitbook require absolute paths, starting with `/`? Because the absolute paths breaks the links when viewed through Github. If we could use relative paths, then both Gitbook and Github would work.

**Comment by jackhumbert** [comment]
Good call! `Keymap.md` works as well :)

**Pull request merged**
