### PR TITLE
Add a reactive RGB underglow animation

### PR DESCRIPTION
**Pull request by 20015jjw**
## Description

I've implemented a reactive RGB underglow animation for my iris v4. This animation is adapted from the twinkle animation and it works by lighting up the corresponding LED when the keys above it is pressed. When all the keys above a certain LED are released, the LED starts to fade until the time runs out or any key above it is pressed again.

## Demos

* Normal, Static color (for some reason embedding this one is just broken)
https://giphy.com/gifs/H42P5SZzzHGKDxuSul

* Hue Change

* Random Color

* Tokyo60 Typing Test with Random Color
https://photos.app.goo.gl/qQ22jT6VE63CpkYb7

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by 20015jjw** [comment]
Document is on the way. This is the first time I PR here so I want to get the code in shape before anything else. I'll add them before the PR is merged, if we do manage to get that far ;)

I've tested the feature fully on my Iris v4 and will test on a non-split board as soon as my diffuser for the tokyo60 arrives.

**Comment by drashna** [comment]
Welcome.  And yeah, the rgb matrix code is ... designed for this sort of usage, as well as ... more animation types. 

As for the hook, there is also the post_process_record_* hook, that runs after the fact

**Comment by 20015jjw** [comment]
@drashna 
I briefly looked into the rib matrix documentation. It doesn't look like it's doing anything to the underglow. I'm quite confused at this moment. 
I know the matrix system already has reactive effects but I believe it's for individual key's RGB backlight? If that's the case, I'm actually quite happy with my approach as I'm adding my animation as a part of the underglow animations. I'm worried that if I extend the matrix system to support tapping into the underglow, things can get a bit entwined.

As for the existing hook you mentioned, I'm fairly certain I cannot use it as it happens after the record is processed, which is after the dual role key's threshold, de-syncing the lighting with the key's actuation.

Please correct me if I'm wrong on both points. Thanks in advance!

**Comment by drashna** [comment]
Hmmm, that may be because of how the animation is programmed.  

The actual code is here: 
https://github.com/qmk/qmk_firmware/blob/master/quantum/rgb_matrix_animations/typing_heatmap_anim.h

**Comment by 20015jjw** [comment]
@drashna can you elaborate? Thanks... the .h file you cited is about per key lighting, right...?

**Comment by 20015jjw** [comment]
Can I get more help on this PR to get it merged? Thanks in advance. I'm lost with the matrix implementation.

**Review by mrsendyyk — APPROVED** [review]

**Comment by 20015jjw** [comment]
@noroadsleft hmm why is this closed? I haven't gotten a chance to resolve the merge conflicts and write the doc so I can update and merge this. When I do, do I reopen this or do I make another PR?

**Comment by tzarc** [comment]
We were in the process of merging the `develop` beach, which was accidentally deleted. We're in the process of reopening all closed PRs -- hours was one of about 80 accidentally closed.

**Comment by tzarc** [comment]
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

**Comment by tzarc** [comment]
Going through old PRs. Sorry it took this long to get to it.

At this stage, it's been pointed out by @drashna that RGB Matrix is where the preferred location of reactive effects needs to be. The rgblight system is intentionally "dumb" and the added complexity of it for reactive effects seems like a step in the wrong direction as far as where QMK wants to be.

I'd suggest taking @drashna's advice and porting to RGB Matrix instead.

**Pull request closed without merging**
