### PR TITLE
Add LFKeyboard offerings

### PR DESCRIPTION
**Pull request by scott-t-wilson**
This would add support for the LFK78, LFK87 and the SMK65.

### CODE REVIEW

**Comment by jackhumbert** [comment]
We're currently considering a rework of some of the make system to make things like this easier - if you'd like to check it out, it's on this branch: https://github.com/qmk/qmk_firmware/tree/make_args_redo :)

**Comment by scott-t-wilson** [comment]
Thanks- I'll submit a new request for that branch. Is there a way to duplicate the travis-ci failure locally?

**Comment by jackhumbert** [comment]
We added support for organising keyboards like you had here - is that support something you're still interested in adding? Some details on the changes can be seen [here](http://qmk.fm/changes/2017-10-14-make-arguments-redo-subprojects-eliminated).

**Comment by scott-t-wilson** [comment]
Yes - thanks for the update. I'll do another pull request soon.

**Pull request closed without merging**
