### PR TITLE
Added more mousekey acceleration keys

### PR DESCRIPTION
**Pull request by BrentBrightling**
I added more mousekey acceleration keys, one so that the speed can be doubled, and 2 keys to permanently change the speed both up and down. I found these keys to be necessary as the current mouse speed is quite slow especially when going across several monitors. This makes it so you can choose a faster speed, or if you want to stick with the slower base speed, you at least have an option to go faster.

Also, to do these changes I removed 3 FN keys to be able to handle the 3 new keymaps. I'm not sure if this is the best method to go about this, or if starting a new store would be better. I was looking into seeing who uses the FN keys removed, and it seems like there are about 5 keymaps that all use FN29-31. I believe that all these layouts were for the planck. Also, these keys were used to do some chained commands, I believe that if we wanted to permanently remove these keys we could just change the planck layouts to use something like KC_LCTL(cmd(cmd)) etc.. 

@ezuk

### CODE REVIEW

**Comment by ezuk** [comment]
@jackhumbert are you able to suggest a path forward that won't mess up existing keymaps? Can this be done?

**Comment by fredizzimo** [comment]
I can see a few options.

1. The codes `0xBD`, `0xBE` and `0xBF`, at the end of the media keys range appears to be unused, so they could probably be used instead of deleting `FN29-FN31`.
2. Actually remove the `FNx` macros, since we have `F(x)` as a replacement
3. Don't use codes for the `FNx`, macros but define them in terms of `F(x)`, probably using the high end range of them so `#define F1 F(223)`. This would mean that if you use both the `FNx` and `F(x)` macros you would not be able to use as many, but that would probably be very rare, and I doubt we have any keymaps using `F(223)` and higher at the moment
4. Move all mouse key keycodes to the 16-bit QMK range.

Option 4. is probably the best, but it would also probably mean the most refactoring.

**Comment by jackhumbert** [comment]
3 sounds good I think - I'm alright with `FNx` and `F(x)` still pointing to the same function, as they do now. 4 would need to be done eventually - I'd like to get everything that's not standardised (a separate topic to discuss) moved out of the 0x00-0xFF range.

**Comment by BrentBrightling** [comment]
Just to ensure I understand before going ahed, if we go with 3 that means that we are removing the FN keys from the keymap file? Also where would be the best place to define the new function mappings? Also there was a few things I wasn't sure about from @fredizzimo's comment, `#define F1 F(223)` is this meant to say `#define FN1 F(223)`? Also it was mentioned we would have to start at 223, are there already defined `F(x)` functions? If so where would they exist?

**Comment by fredizzimo** [comment]
@BrentBrightling,

Yes, the `FN` keys should be removed from the keymap and the defines should go inside `quantum_keycodes.h`, that's were a lot of similar stuff is already defined.

And yes there's a typo, it should be `FN1`. The reason for starting at 223 is that users are already using  the `F(x)` macros in the kemaps, and we don't want to cause problems for them. Because they are most likely using the start of the range, leaving the end of the range at 223-255 unused, it should be much safer to use that.

**Comment by jackhumbert** [comment]
I think we'll need to start at `#define FN0 F(0)`, right? If we define `FN0` to be `F(223)`, their actions will need to occupy the 223 value in that definition. `FNx` and `F(x)` are already interchangable, and this change wouldn't affect that, it'd just reroute the `FNx` to outside of the `0xFF` limit they were placed in by TMK.  

To be clear, I think the `KC_MS_ACCEL3` that this PR adds can stay where they are.

**Comment by fredizzimo** [comment]
Ah yes, @jackhumbert is correct. I didn't really think about how it was working and implemented. So yes `FN0` should be an alias of `F(0)` or `FUNC(0)`, if the longer name is preferred. 

Also checking the code it appears that the mask used for the functions is actually  `0xFFF` or 12 bits, so the max value is 4095, and not 255 as the PCB guide says. @BrentBrightling, since you already modify that, could you also please update that information?

**Comment by BrentBrightling** [comment]
Hey sorry for the delay guys, I will take a look into it!

**Comment by ezuk** [comment]
@BrentBrightling hey hey :) Do we want to do anything here or should I close out the PR?

**Comment by BrentBrightling** [comment]
@ezuk I still have to make the updates that were requested. I'm hoping to get to it soon.. I haven't been able to put a whole lot of time into this with schoool starting up again and work but I'll see if I can give it some time over the next few days

**Comment by ezuk** [comment]
Thank you @BrentBrightling  - much appreciated :)

**Comment by jackhumbert** [comment]
Hey @BrentBrightling, I'm gonna close this for now - when you have time to make the changes, feel free to open it back up/make a comment and we'll get things merged :)

**Pull request closed without merging**
