### PR TITLE
Fix typo in uart.c backport and add 32A "support"

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Slight correction to #7628 (`UCSRB` -> `UCSRnB` and `UDR0` -> `UDRn`), and adding the 32A to the defines (untested) The 32A is a bit odd as the high byte of the baud rate register `UBRR` shares the same memory location as the control/status register C (`UCSRC`). The MSB `URSEL` is used to choose between them. I'm doubtful those top three bits are really used so I just switched the define to use the low byte.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
@tzarc coseyfannitutti/mysterium doesnt build `tmk_core/common/uart.c`? Or is there a scenario I have missed?

**Comment by fauxpark** [comment]
Only the iWRAP and V-USB makefiles reference uart.c - but if you try setting `NO_UART = no` in the rules.mk (+ remove the redundant `NO_UART 1` define in config.h) odDebug.c spits out a warning which fails the build:
> Never compile production devices with debugging enabled

**Comment by zvecr** [comment]
My point was more "if it's not in the list of compiled files, have we really tested it on the 32a in the mysterium"?

**Comment by fauxpark** [comment]
And my point was "no, we have not" 😄

**Comment by tzarc** [comment]
Oh for sure, there's no need for uart on this board.
Really, all we can glean is that it didn't break existing 32A's that don't use uart.c -- I don't have a device that does.

**Pull request merged**
