### PR TITLE
Update Miryoku

### PR DESCRIPTION
**Pull request by manna-harbour**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by manna-harbour** [comment]
This is ready to merge at any time.  Please let me know if you need anything to make it easier to review.  Thanks!

**Review by drashna — COMMENTED** [review]
Could you add a GPL2+ compliant copyright header to the c and h files? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

**Comment by manna-harbour** [comment]
> Could you add a GPL2+ compliant copyright header to the c and h files?
> 
> For instance:
> https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

I've added the header.  It's the same text as in your example but with more compact formatting.  Let me know if that's not acceptable and I'll change it to the usual formatting.  Thanks!

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
I'm not 100% sure about the more compact licensing form, but I think it's okay.  
But thanks!

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Comment by manna-harbour** [comment]
Thanks everyone!

**Pull request merged**
