### PR TITLE
[Keyboard] Update Gergo to use newer Ergodox Matrix code

### PR DESCRIPTION
**Pull request by drashna**
And update layout macros to be correct

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project. (begrudgingly)
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by germ** [comment]
You the man drash

**Comment by drashna** [comment]
@alex-ong Just wanted to double check that this looks correct?  (it's based on the ergodox ez code, with some additions....)

**Comment by noroadsleft** [comment]
Why is the I2C Timeout variable branded (`GERGO_I2C_TIMEOUT` instead of just `I2C_TIMEOUT`)? Is that necessary?

**Comment by alex-ong** [comment]
It looks right (just looking at the matrix.c stuff). Testing it would probably be the easiest way to check if it works :)

**Comment by drashna** [comment]
@noroadsleft because it was called `ERGODOX_EZ_I2C_TIMEOUT`
I suppose I could change it. 

@alex-ong it does work. :) 
But I think it has the sleep issue... again. :D

**Comment by drashna** [comment]
defines changed so they're not hardware specific

**Pull request merged**
