### PR TITLE
Preonic Configurator update

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

Currently, QMK Configurator allows users to create keymap files for layouts not valid for their Preonic revision, like a rev2 with two 2u spacebars. The user has no indication that their setup won't work until they try to compile their firmware, which fails with an error. This PR aims to solve that by exposing only the layouts that are appropriate for the revision selected.

I took some code ideas from the Clueboard 66%, Helix, and Duck Eagle/Viper keyboards to assemble this.

Clueboard 66% and Helix both use a setup where the main keyboard header file (`clueboard/66/66.h` or `helix.h`, respectively) doesn't actually contain any layout macros or matrices, but instead has them in the header files for their revisions, which are included from the main file.

The Helix has `info.json` files in each revision folder, which supersede the `info.json` file in `keyboards/helix`.

The Duck Eagle/Viper's layout macros are in `keyboards/duck/eagle_viper/v2/v2.h` (v2 being the only revision in QMK), but the `info.json` file used by the Configurator is in `keyboards/duck/eagle_viper`.

I took the Clueboard66/Helix header file setup, and paired it with the `info.json` setup used by the Helix and the Duck Eagle/Viper.

@yanfali reviewed my branch and gave it an OK. I've tested these changes as best as I can. Near as I can tell, this doesn't break anything on the CLI side any worse than it's already broken. I ran a local compile for all keymaps as `preonic/rev1`, `rev2` and `rev3`. Revs. 1 and 2 are mostly fine. Most of the existing keymaps fail for rev3, and the rest complete with warnings.

I'm sure Travis CI will complain, but I've done everything I know to do to maintain functionality elsewhere.

## Types of changes

- [ ] Core
- [ ] Bugfix
- [ ] New Feature
- [x] Enhancement/Optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
You broke rev3. :(

**Comment by noroadsleft** [comment]
I'm running a rev3 compile job from current master locally at the moment. Near as I can tell, none of the existing keymaps work from current master, anyway. I actually had a log from one I ran earlier but I accidentally deleted it or something.

**Comment by noroadsleft** [comment]
See log:

[preonic_rev3_test.txt](https://github.com/qmk/qmk_firmware/files/2665766/preonic_rev3_test.txt)

**Comment by drashna** [comment]
yeah, and the default ones do compile, but they have warnings rather than "OK" because they lack a way to check the firmware size.


So really, this looks good.

**Comment by jackhumbert** [comment]
Nice! Thanks :D

**Pull request merged**
