### PR TITLE
Added configurable defaults for RGB backlight indicators.

### PR DESCRIPTION
**Pull request by Wilba6582**
## Description

Added configurable defaults for RGB backlight indicators. They were missing from the set of things people could configure in their keymap's `config.h`

Fixes issue raised by @stanrc85 in #5536

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

### CODE REVIEW

**Comment by drashna** [comment]
Default keymaps compile fine. 

Thanks!

**Comment by stanrc85** [comment]
Based on your structure here, would you mind if I added support for a few more options? Specifically brightness, color1, and color2.

**Comment by drashna** [comment]
Looks like this change broke the RAMA koyu board. :(

**Comment by Wilba6582** [comment]
@stanrc85 I can add the others and amend this branch/PR.

@drashna yes, one of them had to merge first, this branch didn't have KOYU to update.

**Comment by stanrc85** [comment]
> @stanrc85 I can add the others and amend this branch/PR.

Thanks!

**Comment by drashna** [comment]
@Wilba6582 Okay, thanks

**Pull request merged**
