### PR TITLE
Add a temporary comment to quantum/rgblight.h to aid migration.

### PR DESCRIPTION
**Pull request by mtei**
Add a temporary comment. The content is a contrast table of old magic number and new symbol.

### CODE REVIEW

**Comment by drashna** [comment]
I think that it would be better to place this in the document files for the rgb light stuff, rather than tucked away in the code (or probably best, in both places)

**Comment by mtei** [comment]
Whether it should be in rgblight.h, in the document or both. I have no opinion.
If you or anyone decide, please tell me.

**Comment by mtei** [comment]
I tried add some notice to docs/feature_rgblight.md.

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
