### PR TITLE
Use `clock_prescale_set()` from avr-libc

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

According to #395 the `clock_prescale_set()` function was not declared for the 16U2 - this has since been fixed, so we can stop doing the register manipulation manually now.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Do we know which versions of avr-libc were broken/ which one it was fixed in?

**Comment by fauxpark** [comment]
Appears to be this revision: https://svn.savannah.gnu.org/viewvc/avr-libc?view=revision&revision=2245

**Comment by zvecr** [comment]
Hopefully we get no `Firmware fails to build on <insert OS version from yesteryear>` reports.

**Comment by fauxpark** [comment]
"I can't compile QMK on my 386 anymore, help"

**Comment by yanfali** [comment]
> "I can't compile QMK on my 386 anymore, help"

Don't mock my 386 with Co-Pro

**Pull request merged**
