### PR TITLE
Fix usbconfig for unikorn

### PR DESCRIPTION
**Pull request by yanfali**
Restore the usbconfig values so it remains compatible with BMC. Recommended by @mechmerlin 

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Can QMK be used with BMC? That doesn't sound right.

**Comment by yanfali** [comment]
> Can QMK be used with BMC? That doesn't sound right.

According to Merlin, if you don't do this, the board is not revertable to BMC again. By setting the string to this well known value, you can flash BMC back onto board and it will take over.

**Comment by fauxpark** [comment]
I assume you mean from within BMC? Seems like you can just flash PS2AVRGB back onto it manually with the toolbox, using one of the hex files from here: https://github.com/showjean/ps2avrU/releases

**Comment by yanfali** [comment]
@mechmerlin you wanna explain why it has to be this string?

**Comment by yanfali** [comment]
@mechmerlin

**Comment by fauxpark** [comment]
So, as I outlined [here](https://github.com/qmk/qmk_firmware/pull/7488#issuecomment-565524435), zvecr's recent change to the V-USB code renders this PR kinda pointless. If you want to go back to BMC from a recently compiled QMK, your only option now is to flash the hex manually.

**Comment by yanfali** [comment]
OK, sounds good to me.

**Pull request closed without merging**
