### PR TITLE
Fix a bug in the CLI's rules.mk parsing code

### PR DESCRIPTION
**Pull request by Erovia**
DEFAULT_FOLDER could cause unexpected behaviour when the user specified
the full revision of the board.

## Types of Changes

- [ ] Core
- [X] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Does this intersect with #9530 at all?

**Comment by Erovia** [comment]
Big oof, from a quick glance, it fixes the same bug.

**Comment by fauxpark** [comment]
@Erovia is this still needed now that the above PR has gone in?

**Comment by Erovia** [comment]
Nope.

**Pull request closed without merging**
