### PR TITLE
[Core] Add support for Radial Dial HID Reporting

### PR DESCRIPTION
**Pull request by drashna**
## Description

This is 100% @sigprof's fault. 

https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/radial-controller-protocol-implementation

## Types of Changes

- [x] Core
- [x] New feature
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by sigprof — CHANGES_REQUESTED** [review]
Well, I did not request anyone to implement this :smile:

**Comment by drashna** [comment]
> Well, I did not request anyone to implement this 😄

Yeah, but you can't post info about cool stuff and not expect somebody to want to implement it... 😄 

On the plus side, I'm a lot more familiar with the USB stack, and need to rework the gamepad draft.

**Comment by DeeHants** [comment]
I know this has been closed for a while, but is there any appetite for reopening or carrying on this work?
I have a keyboard with an encoder, and a separate arduino based encoder emulating a surface dial, and would be great to combine them.
Thanks!

**Comment by drashna** [comment]
The main stopping point was how to implement the interface.  Eg, keycodes, functions, etc.

**Comment by drashna** [comment]
the issue is how to handle the rotational control.  A good example of what I mean is mousekeys and pointing devices.  There is a big difference in how the two are handled, and with varying effectiveness. 

That said, I have updated the branch to be mergeable with current develop branch.

**Comment by DeeHants** [comment]
> the issue is how to handle the rotational control. A good example of what I mean is mousekeys and pointing devices.

Ahh, I was assuming a single dial step per encoder step, but that's based on my sample of 2 encoders that have about 12 steps with detents per full rotation.

**Pull request closed without merging**
