### PR TITLE
Making KC_NO not be a key

### PR DESCRIPTION
**Pull request by IsaacElenbaas**
**Backstory paragraph, skip if you'd like:**
I have a key to activate an AHK script to turn off my monitors and lock everything. On my new Planck, I thought I would set everything to KC_NO to not wake them if something is accidentally pressed. To my dismay, it still woke them (monitors, not my PC, I understand that is different [and a windows setting]). Digging deeper I found that QMK handles updates by the matrix, assigning and interpreting keycodes later. I made a workaround for my mapping, but on testing further I found further issues this could cause.

**End backstory paragraph**

KC_NO is counted as a key in all the ways that matter. It triggers host_keyboard_send, which was my original issue, but when I tested further, I found out it triggered default: as it ran the following in my macros:
`default:
      if(keycode <= KC_Z)`
Now, obviously those have workarounds - add a != KC_NO in default, and after a bit of searching I found out how to stop the keyboard from sending updates.
However, preventing updates can't be done per-key, and so I can't have certain keys be macros even when my screen is off without letting any KC_NOs wake monitors too. Also, KC_NO cancels oneshots, and there is no way I can find to get around it.

In my opinion, KC_NO should act as though I hit a key not connected to my board. This will need to be made a setting, so that anyone who uses KC_NO to cancel oneshots or something won't have their keymap broken.

## Description
A simple check where matrix changes are logged to block KC_NO. This runs layer_switch_get_layer, however (to get actual keycode), and as such the keycode should probably be passed along so that it doesn't need to be called again [here.](https://github.com/qmk/qmk_firmware/blob/e1203a222bb12ab9733916164a000ef3ac48da93/quantum/quantum.c#L226)

## Types of Changes

- [X] Core
- [X] Bugfix (IMO)
- [X] New feature
- [ ] Enhancement/optimization (technically? One less thing sent to the OS)
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation
## Checklist

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage). One layer in my keymap broken, no clue what the cause could be as it's near identical to another. Investigating.

I get that this is a very small issue that requires comparatively drastic changes, but I don't believe the key acts how it should. I'll be (slowly, takes me a while to understand this code and the bugs make no sense) working on it.

### CODE REVIEW

**Comment by drashna** [comment]
One shot keys are cleared here: https://github.com/qmk/qmk_firmware/blob/47051f506fd4888bbb55fa7981cb7b24827f3d1b/tmk_core/common/action_util.c#L154-L168

**Comment by IsaacElenbaas** [comment]
I haven't had time to look at it, but thinking the past day non-USB HID macros (tapdance, LSFT(KC_A), KC_NO) might all return KC_NO and then be interpreted by later functions to see if they should trigger a tapdance function or send a complex keycode. I don't see why else LSFT(KC_A) would return KC_NO, but I'm hoping that's not it. If it is, too much might have to be changed for this to be worth it.

**Comment by IsaacElenbaas** [comment]
Above comment was in reference to this:

> Also, for some reason oneshots aren't working. When pressing them nothing happens (but the oneshot closes) and that key won't work again until another is pressed. My guess is they're triggering that function, and set as the last keycode, so don't work until they aren't the last one. (All mine are complex (eg. LSFT(KC_A), that might have something to do with it?)

Upon repulling this in another directory so I can work on it separately, none of this is happening. Everything is working as intended, except for one of my layers that appears to do nothing. Anywho, removed from OP.

**Comment by IsaacElenbaas** [comment]
Further testing. . . this is bizarre. Tapdance is working correctly for everything, but certain keys don't work on certain layers. At all. And while pressing my layer MO works, pressing my one to take me to my arrow keys layer freezes up the whole keyboard. Layers around it work fine.

**Comment by IsaacElenbaas** [comment]
Month later update; KC_NO being in the keymap screws up mostly random keys (they seem to group by column.) Anything with no KC_NOs in the keymap works as expected, as does KC_NO aside from causing issues elsewhere. The method I am using to get the key pressed is the same as is used in get_event_keycode, and isn't triggered until the matrix coord is selected, so I don't see why anything but the currently pressed key or having KC_NOs in the keymap would matter.

**Comment by IsaacElenbaas** [comment]
Also, I've deleted original post info about oneshots not triggering, as I'm not sure whether it's due to the current error. Will need to be tested once that's fixed.

**Comment by jackhumbert** [comment]
+1 to making this a flag - something like "SILENT_KC_NO"?

**Comment by IsaacElenbaas** [comment]
Breaking change that I no longer need and I doubt anyone else will. Closing.

**Pull request closed without merging**
