### PR TITLE
S60-X refactor and Configurator support

### PR DESCRIPTION
**Pull request by noroadsleft**
- matrix refactor
  - added matrices for:
    - `LAYOUT_60_ansi`
    - `LAYOUT_60_ansi_split_bs_rshift`
    - `LAYOUT_60_iso`
  - `LAYOUT_legacy` renamed to `LAYOUT_kc`
- keymap refactor
  - matrix rename
  - keymap `default` refactored to use `LAYOUT_60_ansi` matrix
  - readability
- Configurator update
  - added supported layouts:
    - `LAYOUT_60_ansi`
    - `LAYOUT_60_ansi_split_bs_rshift`
    - `LAYOUT_60_iso`
- Added community layouts `60_ansi`, `60_ansi_split_bs_rshift` and `60_iso` to `rules.mk`

### CODE REVIEW

**Comment by noroadsleft** [comment]
Travis errors are with @Talljoe's community keymaps `talljoe` and `talljoe-ansi`, but only for the `s60_x/default` variant, `s60_x/rgb` compiles without issues. Something about tap dance (a feature with which I have no experience).

https://travis-ci.org/qmk/qmk_firmware/builds/400118553#L956
https://travis-ci.org/qmk/qmk_firmware/builds/400118553#L997

**Comment by Talljoe** [comment]
Looks like tapdance expects oneshot, which s60_x doesn't have by default for some reason?  Anyway, I think this change will fix it: https://github.com/qmk/qmk_firmware/compare/master...Talljoe:tapdance-oneshot-fix?expand=1

**Comment by noroadsleft** [comment]
@Talljoe,

1. That fixes it.
2. Is this a change that should be applied to the whole of QMK? (Does it break things elsewhere?)
3. How do you seemingly always know exactly how to fix an issue? Teach me your ways, O Tall One.

**Comment by drashna** [comment]
@noroadsleft because the error message tells you. :D
https://github.com/drashna/qmk_firmware/blob/8dd12a28ecb19a5d192b8c7cdc8ef72bd496e366/quantum/process_keycode/process_tap_dance.c#L149
That's the file and line that it's erroring on.

And I'm guessing that @Talljoe or the keyboard designer disabled One Shot functionality, so it causes this. 

And yeah, ideally, this should be a separate PR, as it is a global issue.  And I don't think it should break anything.

**Comment by Talljoe** [comment]
Here's a PR for the issue: #3311 

3. I've been doing this a long time...

**Comment by drashna** [comment]
lol, yeah, that would be a good reason too.

**Comment by drashna** [comment]
Thanks!

**Comment by noroadsleft** [comment]
@drashna,

> because the error message tells you. :D

The error message telling you where the problem is is not the same as telling you *how* to fix the problem. :grinning:

**Comment by Talljoe** [comment]
```
process_tap_dance.c:149: undefined reference to `get_oneshot_mods'
```
That told me the general place to look. First thing I did was to see where `get_oneshot_mods` [was defined](https://github.com/qmk/qmk_firmware/blob/master/tmk_core/common/action_util.c#L268). It appeared that the file was being built, so the other explanation was it was being [`#ifdef`'d out](https://github.com/qmk/qmk_firmware/blob/master/tmk_core/common/action_util.c#L241). There were a couple ways of fixing it, I chose the one that had little impact to other code (i.e. setting oneshot mods to `0` instead of removing all references to it) and made it clear that the define would impact things (as opposed to defining an alternate `get_oneshot_mods` to return `0`). Made sure it didn't break anything else (specifically `gh60:talljoe`) but didn't test it on your branch because I was busy. :)

**Comment by noroadsleft** [comment]
Appreciate the answer, @Talljoe.

**Pull request merged**
