### PR TITLE
macOS Mission Control and Launchpad keys

### PR DESCRIPTION
**Pull request by gtg465x**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* [[Feature Request] [PR Planning] macOS Mission Control and Launchpad keys](https://github.com/qmk/qmk_firmware/issues/10111)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by gtg465x** [comment]
The Fn keys on Apple keyboards provide media functions by default. All media functions provided by Apple keyboards are supported by QMK except for Mission Control and Launchpad, which are usually mapped to the F3 and F4 keys respectively. [Apple has added codes for these functions to the official HID spec](https://www.usb.org/sites/default/files/hutrr77_-_desktop_controls_0.pdf), so it would be nice for macOS users to not have to write custom user code to get their keyboard to function as expected. I updated my personal user keymap for my keyboard as an example to show what was required before vs with this change.

**Comment by fauxpark** [comment]
Please see my first comment on the issue you linked. Also, this PR will need to target `develop`.

**Comment by gtg465x** [comment]
> Please see my first comment on the issue you linked. Also, this PR will need to target `develop`.

Shoot, not sure how I missed that. Should I just close the PR then? What's the blocker on "we are waiting to be able to remove the KC_FN* keycodes"? I'll do it. It seems people have been submitting PRs like this for years now... let's do something about it or it will never get fixed and people will keep on making these requests and PRs.

**Comment by fauxpark** [comment]
It's been on my list, and I've been chipping away at it as and when I can. The removal of the `KC_FN*` keycodes itself will have to go through `develop`, as although that whole system is deprecated it is still technically a breaking change.

**Comment by RobSjaras** [comment]
@gtg465x Is the code on this PR actual working code? I'm currently looking into getting those 2 keys to work as expected on my Keychron Q1. Thanks.

**Comment by gtg465x** [comment]
@RobSjaras Yeah, it’s working, but it would be easier to just build from my custom Q1 keymap that’s already in master.

**Comment by RobSjaras** [comment]
@gtg465x Yeah I noticed a few minutes after my comment! And then I saw someone had been building on top of that, which I then built on top of.  I needed to mirror Mac behavior as much as possible, so I've added caps lock with tap-protection, right ctrl->right alt, and fn+backspace=delete. But yeah, thanks for your work, it works wonders!

**Comment by mmshivesh** [comment]
@RobSjaras Im curious on how you implemented Caps Lock with tap protection. You have any pointers?

**Comment by RobSjaras** [comment]
> @RobSjaras Im curious on how you implemented Caps Lock with tap protection. You have any pointers?

Sorry for the very late reply, December was very hectic for me... Is this still something you're looking to get help for?

**Comment by chrismanderson** [comment]
> > @RobSjaras Im curious on how you implemented Caps Lock with tap protection. You have any pointers?
> 
> Sorry for the very late reply, December was very hectic for me... Is this still something you're looking to get help for?

I'd love to see the the caps lock/fn backspace for sure if you have a fork or some such uploaded!

**Comment by RobSjaras** [comment]
> > > @RobSjaras Im curious on how you implemented Caps Lock with tap protection. You have any pointers?
> > 
> > 
> > Sorry for the very late reply, December was very hectic for me... Is this still something you're looking to get help for?
> 
> I'd love to see the the caps lock/fn backspace for sure if you have a fork or some such uploaded!

So I finally got around to doing it! Have yet to document anything, but my goal was changing one of the previous setups and make the keyboard act more like a _true_ macOS keyboard.

https://github.com/RobSjaras/qmk_firmware/commit/4071b3326b9f27a1a936fe5bad8683da081590ff

**Review by fauxpark — CHANGES_REQUESTED** [review]
Please rebase - the FN keys are now gone and there is space to add these keycodes contiguously.

**Pull request closed without merging**
