### PR TITLE
Edit the 'Ignore Mod Tap Interrupt' doc

### PR DESCRIPTION
**Pull request by xster**
## Description

A tentative edit to solve my misunderstanding of https://github.com/qmk/qmk_firmware/issues/6953 from reading the current docs. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Honestly, I'm not sure about the wording here.  It feels to me, like it's making things less clear.   But I fully admit that is a) because I wrote a lot of that, and b) I'm familiar with the features

**Comment by xster** [comment]
Sure, I'm not attached to the PR's wording at all. I mainly just wrote things down to double check whether it's right that the actual behavior is more or less the reverse of what's documented. 

I'll re-tweak the wording.

**Comment by xster** [comment]
I reworded the doc edit a bit. Please take another look. 

Also a cleanup of trailing whitespaces. Feel free to turn on GitHub review's 'ignore whitespace' option. Or I can revert if you prefer to leave them in.

**Comment by precondition** [comment]
You should use another word than combos, I don't know why you're bringing up combos when they have nothing to do with this. Do you mean holding down a key and then tapping another one while holding down the first? That's not a combo in the way the QMK docs use the word. "Chords" is perhaps better.

**Comment by manna-harbour** [comment]
> "Chords" is perhaps better.

For holding a mod or mods and tapping another key I'd say "modifier combination", so instead of "rolling combo" it'd be "rolling modifier combination".

**Comment by tzarc** [comment]
Removed the label preventing stalebot from kicking in.
If it's critical that this gets merged, I'd suggest appropriate follow-up.

Stalebot will close this otherwise.

**Comment by zvecr** [comment]
Thank you for your contribution!

This pull request has been automatically closed because it has not had activity in the last 30 days.
Please feel free to give a status update now, ping for review, or re-open when it's ready.﻿

**Pull request closed without merging**
