### PR TITLE
relocating boards by flehrad to flehrad/ folder

### PR DESCRIPTION
**Pull request by flehrad**
## Description
Requesting relocation of a number of pcbs/boards I have created to be moved into a folder to easier manage and track which boards have qmk completions in configurator.
This also improves identification of pcb maker.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
This PR should target the `develop` branch instead of master as it is considered a breaking change.

**Comment by flehrad** [comment]
> This PR should target the `develop` branch instead of master as it is considered a breaking change.

:( Sorry, I'm very novice to a lot of this still, is there something I need to do to make this workable, or should I not look to move these, and just only request to add newer boards into a folder going forwards?

**Comment by flehrad** [comment]
Closing to raise new PR to develop.

**Comment by fauxpark** [comment]
You can retarget this PR by clicking the edit button, and then rebasing.

**Comment by flehrad** [comment]
Changed to Develop. Thank you Ryan.

**Pull request merged**
