### PR TITLE
Clean up duped filenames om qmk.fm. Solves https://github.com/qmk/qmk.fm/issues/43

### PR DESCRIPTION
**Pull request by Duckle29**
## Description
The addition to the build script should find any files that have the exact same name, except for capitalization. And remove the oldest one.

Such duplicated files will cause issues on windows, and are usually the result of a name change, and as such deprecated.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* fixes qmk/qmk.fm#43

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Duckle29** [comment]
I removed some code I had left over from previous versions of it. No need to build an array of files to remove with how it is now.

**Comment by drashna** [comment]
Just to clarify, it's not just dupped names that are the issue, but also the files for keyboards that have been moved or their name's changed.  Eg, `iris` to `keebio/iris`.

**Comment by Duckle29** [comment]
This snippit would only clean up duped names

**Comment by drashna** [comment]
Okay. Well, it would clean up part of the issue, at least then. 

If it helps, the build script does generate a list of the current keyboards. It should be possible to compare the files to that. I just don't know enough to do so.

**Comment by noroadsleft** [comment]
This might be better solved on qmk/qmk.fm. My understanding is that the bot only generates new firmware when this repo is updated, but doesn't clean up the old files. So removing them from qmk/qmk.fm directly should mean they don't get generated again.

**Comment by Duckle29** [comment]
The issue with that would be what would trigger it on qmk.fm? 
This is the script that pushes new files to qmk.fm, and as such, this is the script making the dupes. Only makes sense to deal with them here.

**Comment by drashna** [comment]
@noroadsleft No, this is the best point to hand this. This script is what uploads the files to the qmk.fm repo.   Also, the list of current keyboards is generated here.  It would be the best place to clean this up, I believe. 

I may be wrong, but my understanding of how the Travis CI scripts work, this is the best point.

**Comment by noroadsleft** [comment]
@drashna When the script runs, do the old files still exist on this repo?

**Comment by Duckle29** [comment]
with the keyboard file, it's actually easier I think. I'd just remove any files that don't match a keyboard in that list.

**Comment by drashna** [comment]
yes.  Specifically, 
it clones the repo:
https://github.com/qmk/qmk_firmware/blob/f6f955de3f6292acfe00202d7ab2ccc1ec778326/util/travis_compiled_push.sh#L46

Moves the newly generated keyboard list over:
https://github.com/qmk/qmk_firmware/blob/f6f955de3f6292acfe00202d7ab2ccc1ec778326/util/travis_compiled_push.sh#L49

Moves the newly generated default firmware images:
https://github.com/qmk/qmk_firmware/blob/f6f955de3f6292acfe00202d7ab2ccc1ec778326/util/travis_compiled_push.sh#L59

Regenerates the page for qmk.fm/keyboards:
https://github.com/qmk/qmk_firmware/blob/f6f955de3f6292acfe00202d7ab2ccc1ec778326/util/travis_compiled_push.sh#L73

And then adds the new files and pushes to the qmk.fm repo:
https://github.com/qmk/qmk_firmware/blob/f6f955de3f6292acfe00202d7ab2ccc1ec778326/util/travis_compiled_push.sh#L74-L76

So, it has access to the new list of keyboards, and all of the images on the qmk.fm repo.  So, it very well could remove any outdated images. 

I'm just not familiar with bash enough to know how to compare the file contents to the file list, and prune accordingly.

**Comment by Duckle29** [comment]
That should do it

**Comment by drashna** [comment]
I'm mostly waiting on @jackhumbert and/or @skullydazed to approve this PR.  

Otherwise, awesome, and thanks!!

**Pull request merged**
