### PR TITLE
Support PS/2 mouse 9-bit output with MOUSE_EXTENDED_REPORT

### PR DESCRIPTION
**Pull request by dkao**
## Description

Support the 8-bit + sign-bit output from PS/2 using `MOUSE_EXTENDED_REPORT`.
Also gives user code more range to scale mouse movement.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Honestly, it may be better to move the ps2 stuff over to the pointing device code, in general.  It would simplify/solve a lot of this, I think.

**Comment by dkao** [comment]
Right, I was wondering why PS/2 mouse is a special case.
Does QMK still support only one pointing device? There are use cases that have a PS/2 mouse and some other pointing device.

**Comment by drashna** [comment]
It's mostly that way because they were added at different points, and I didn't have a ps2 device to test with. 

That said, yeah, it's mostly just a single device only, at this point, but dasky has been working on making adding multiple devices a lot more seamless:
<https://github.com/qmk/qmk_firmware/pull/20374>

**Comment by freznel10** [comment]
> It's mostly that way because they were added at different points, and I didn't have a ps2 device to test with.
> 
> That said, yeah, it's mostly just a single device only, at this point, but dasky has been working on making adding multiple devices a lot more seamless: #20374

been rocking #20374 and tried porting ps2 trackpoint to it but I've been getting weird results as I can't the RP2040 PIO driver to play nice. :( I will chuck this to my ignorance

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Pull request merged**
