### PR TITLE
small corrections to the total number of leds to space65 (#5001)

### PR DESCRIPTION
**Pull request by mnpqraven**
The space65 uses 6 LEDs(3 top and 3 side) instead of 5. Just a small correction :)
## Types of changes

- [ ] Core
- [ ] Bugfix
- [ ] New Feature
- [x] Enhancement/Optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* 

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mnpqraven** [comment]
idk why but git is putting the whole file as one big diff instead of just the line that should be endited (L62)

**Comment by mechmerlin** [comment]
I have a fix for this coming in this weekend along with other optimizations.

**Comment by noroadsleft** [comment]
@mnpqraven 

`keyboards/gray_studio/space65/config.h` doesn't exist in the parent commit of 45ff725 on your source branch. You need to grab the changes from qmk/qmk_firmware and rebase.

```sh
git fetch upstream  
git rebase upstream/master
```

Assuming upstream points to qmk/qmk_firmware, `git fetch` grabs the current state of qmk/qmk_firmware, and then `git rebase` takes 45ff725, reverses it, updates your branch to match qmk/qmk_firmware's `master` branch , and then attempts to apply the same changes that 45ff725 did originally.

At this point, you'll have a merge conflict, but it will only be the line you edited. Open the file, fix the conflict, save, `git add`, `git commit`, `git push --force-with-lease`.

That should update your PR with only the one line you changed.

Extended instructions here: https://docs.qmk.fm/#/newbs_best_practices?id=resolving-merge-conflicts

----

Since @mechmerlin already has a fix, I'll let you two talk about who should do/will be doing what.

**Comment by mnpqraven** [comment]
@noroadsleft you are correct, it was an oversight from me because i squashed my random commits from previous work and just added the config.h as a new commit, i'll look into it and improve my rebase/squash practice. Many thanks for the explanation !

**Pull request merged**
