### PR TITLE
LFK78 refactor

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Attempting to bring the lfkeyboards directory more in line with current standards, starting with the LFK78 as someone on Discord was having trouble with it recently (they needed to set the correct `LFK_REV` in rules.mk - lucky they were not using Configurator!).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
I like this PR in concept. Just a couple issues that I'm not okay with.

- `default` keymap doesn't compile on `revb`, due to firmware size. It's like 3kB over. Even if I do it locally in avr-gcc 8.3.0, it's 2.5kB oversize. `AUDIO_ENABLE = yes` for me is nearly 9kB. I'm not sure how (or if) we solve this.
- I have a strong dislike for when revision folders are "hyphenated". I'd rather have `revc_h` be `revc`, and then note in a readme it supports revisions C through H.

**Comment by fauxpark** [comment]
@noroadsleft good point on the revision folders. Changed to `revc` and added some stuff in the readme.
On the revB, it already compiles too large on master (Travis doesn't pick it up because `LFK_REV = J`). Turning off Music mode still result in 710 bytes over :/

@drashna I'll leave pulling out all the custom code for another PR, but yeah, I suspect all of it could be converted to their respective core features instead. That might help with the size...

**Comment by drashna** [comment]
it looks like ca178858 is looking for `LAYOUT_split_rshift`, and iso is looking for .... `LAYOUT_iso` for the lfk78 keyboard.

**Comment by fauxpark** [comment]
Yep, neither of which are supported on the revB.

@scott-t-wilson you originally PR'ed this board, thoughts? (not sure if you are also LFKeyboards)

**Comment by drashna** [comment]
Rebase needed

**Comment by fauxpark** [comment]
All done

**Pull request merged**
