### PR TITLE
Update msiu's xd75 keymap README to be accurate

### PR DESCRIPTION
**Pull request by markstos**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
The current QMK stance is to not change user keymaps without prior knowledge.

Can get sign off from @martinmksiu before making this change?

**Comment by markstos** [comment]
@martinmksiu Are you OK with this update to your README file? 

As someone reading through several of these, it's helpful if the README files are present and accurate.

Thanks.

**Comment by martinmksiu** [comment]
yep that's fine. Thanks for updating this!

**Comment by noroadsleft** [comment]
Thanks for responding, @martinmksiu.

**Pull request merged**
