### PR TITLE
[Core] Userspace keymaps & layouts

### PR DESCRIPTION
**Pull request by Curry**
## Description

Allowing for storage of user defined keymaps and layouts to be stored inside userspace.

Rules are defined in issue #7414 

## Types of Changes

- [x] Core
- [x] New feature
- [x] Enhancement/optimization
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* #7414 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

## Additional Comments
- The order of checking for keymaps is now `userspace` > `keyboard` > `layouts`
- The order in which the rules.mk are applied is the same: `keyboard` > `userspace` > `keymap`
- Would be ideal in the future to have a makefile specifically for setting up userspace.
- Majority of changed files are just movin keymaps to my userspace.

## Bugs found
- Some layouts set `USER_NAME`, was not updating user path and caused it to crash (Fixed) 
- Included userspace layout after finding the proper community layout (Fixed) https://github.com/qmk/qmk_firmware/pull/7955/commits/61015648e423dc4c06587af00271fbef7802f3c1
- Erroneously included the wrong layout file (Fixed) https://github.com/qmk/qmk_firmware/pull/7955/commits/61015648e423dc4c06587af00271fbef7802f3c1
- Only detecting the first user (Fixed) https://github.com/qmk/qmk_firmware/pull/7955/commits/90e223ac8753ba21f1206fa49e23871ac9a0bdaf

### CODE REVIEW

**Comment by tominabox1** [comment]
It seems to only work when the keymap is consistent with the username. In some cases, I have multiple layouts for the same board which would appear in a keyboard keymap folder as tominabox1 and tominabox1_40 for instance. Putting them in userspace makes no distinction between these two. Granted, this pr does not prevent you from still doing that and keeping the one in the keyboard folder but would like to see this allowed

**Comment by drashna** [comment]
I think that ideally, you'd only want to use "community layouts" for this, @tominabox1.  And at some point we may want/need to convert all of the keyboards into "community layouts", even if that is something like `LAYOUT_(keyboard)`.

**Comment by drashna** [comment]
The only issu eI have with this, is that it doesn't parse things like the keyboards folder. 

Eg, `crkbd/` doesn't work, but `crkbd/rev1/` does.  But I think you'd need to expand the logic significantly to support that.

**Comment by Curry** [comment]
t could be possible to ignore the revision folder name and pull directly from `crkbd`. Currently, both `make crkbd:curry` and `make crkbd/rev1:curry` both work and pull in `users/curry/keymaps/crkbd/rev1/keymap.c`, since the default folder is `rev1/`. I could make it pull from just `users/curry/keymaps/crkbd/keymap.c`, however, if you wanted a certain keymap for a certain revision, changing this would prevent that from happening (ex: planck).

**Comment by drashna** [comment]
Sorry for not getting back to you sooner!

> I could make it pull from just `users/curry/keymaps/crkbd/keymap.c`, however, if you wanted a certain keymap for a certain revision, changing this would prevent that from happening (ex: planck).

Ideally, both should work, much the way that the existing keyboard format works.

It may work best to reuse the parsing for the keymap folders, and somehow generalize that, too.

**Pull request closed without merging**
