### PR TITLE
QMK DFU bootloader generation

### PR DESCRIPTION
**Pull request by jackhumbert**
This exposes the `:bootloader` and `:production` targets for generating the `$(TARGET)_bootloader.hex` (just the bootloader) and `$(TARGET)_production.hex` (application and the bootloader combined) files.

If you define these variables in your `config.h` you'll be able to overwrite the defaults in the QMK fork of the LUFA DFU bootloader. The `ESC` key is whatever key you'd like to use to exit the bootloader. `LED` and `SPEAKER` work the same - either can be LEDs. Both just toggle on/off when things are happening in the bootloader.

    #define QMK_ESC_OUTPUT F1 // usually COL
    #define QMK_ESC_INPUT D5 // usually ROW
    #define QMK_ESC_LED E6
    #define QMK_ESC_SPEAKER C6

It will also automatically load the manufacturer and product strings (with ` Bootloader` added to the product) from your `config.h`. Only `atmega32u4` chip at 16Mhz are supported with this PR - more options will come down the road.

### CODE REVIEW

**Comment by Maartenwut** [comment]
This should be added to the documentation.

**Comment by jackhumbert** [comment]
Definitely! Working on polishing it up a bit :)

**Comment by colemarkham** [comment]
Does this work for ProMicros? That is, could I reflash one with this bootloader? Because that would make life so much easier for end users. Would that require an ISP or could it be done using avrdude?

**Comment by jackhumbert** [comment]
Totally! You’d need to ISP flash it (which is done via avrdude but not
avr109) - not the easiest thing to do unfortunately, but we have a guide:
https://docs.qmk.fm/isp_flashing_guide.html

**Comment by drashna** [comment]
But the keyboard config would have go be updated to support this, correct? 

Also, you could use the SparkFun stuff: https://learn.sparkfun.com/tutorials/installing-an-arduino-bootloader
(which is what I've done to reload bricked boards, with their AVR Pocket Programmer)

**Comment by jackhumbert** [comment]
Yeah, you'd need to compile your own bootloader using the targets and settings above, but we're also working on modifying how the select the bootloader for a keyboard a little bit - it's not currently overridable via revisions/keymaps.

**Comment by colemarkham** [comment]
Thanks for all the info. I will give it a try sometime.

**Comment by drashna** [comment]
@jackhumbert  Glad to hear it!  
Though, aside from "all in house", is there a distinct advantage to using the "QMK DFU" bootloader? 
Such as smaller size, or the like?

**Comment by jackhumbert** [comment]
It's 0x0F3E in size, but that doesn't really matter unless you can get it under 0x0800 or 0x0400, because the bootloader has to start at certain points in the memory - this start point is changed with the fuses.

I'm not aware of any benefits the LUFA DFU one has over Atmel's besides being open source and less buggy in general, but I added the simple matrix scan and exposed the LEDs/Speaker pulsing that you see above to the QMK fork we have.

There's a couple different bootloaders in LUFA - the HID one is pretty interesting, and is compatible with the command line version of PJRC's flasher, and therefore the QMK Toolbox. It doesn't require any drivers to get flashed, which is a nice benefit, but I'm not sure how advantageous that is for people using QMK.

I think the thing I'm most interested in right now is a bootloader being exposed to Chrome's USB API - it's working with dfu-util and ARM boards, and it would be nice to have an alternative for AVR chips.

**Comment by colemarkham** [comment]
Just to clarify, the bootloader in this PR is not the LUFA HID one that you mentioned? I assume it's still compatible with QMK Toolbox, but does it require drivers to be installed?

**Comment by jackhumbert** [comment]
That's correct - this target is for the QMK fork of the LUFA DFU bootloader :) it's compatible with QMK Toolbox, Atmel's Flip, and dfu-programmer - sometimes it requires drivers to be installed on Windows, but I'm not 100% clear on that because most people have a development environment setup by the time they get to flashing.

**Pull request merged**
