### PR TITLE
Add `redox` layout

### PR DESCRIPTION
**Pull request by dunk2k**
## Description

- add 'redox' to `layouts/default`
- add LAYOUT_redox to `layouts/default/readme.md` 
- changed LAYOUT macro in all keymaps for matching keyboards:
    - redox
    - redox_w 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* n/a

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — COMMENTED** [review]
If anything, it may be more worthwhile to move the redox_w folder into the redox folder, as a revision.

**Comment by dunk2k** [comment]
> If anything, it may be more worthwhile to move the redox_w folder into the redox folder, as a revision.

@mattdibi - yay/nay?

**Comment by mattdibi** [comment]
> > If anything, it may be more worthwhile to move the redox_w folder into the redox folder, as a revision.
> 
> @mattdibi - yay/nay?

I think it’s a great idea.

**Comment by dunk2k** [comment]
diverting effort to moving `redox_w` into `redox` dir

**Pull request closed without merging**
