### PR TITLE
Update OLED driver to support some new displays

### PR DESCRIPTION
**Pull request by sigprof**
## Description

Update the OLED driver to make it work with more display variants:
* [64×32 SSD1306](https://www.aliexpress.com/item/33047471191.html)
* [64×48 SSD1306](https://www.aliexpress.com/item/32847587362.html)
* [64×128 SH1107](https://www.aliexpress.com/item/4000465625534.html)

Changes which needed to be made in the driver code:
1. All of those displays need `#define OLED_COLUMN_OFFSET 32`, however, the existing driver code supported `OLED_COLUMN_OFFSET` only for `OLED_IC_SH1106`; the code for `OLED_IC_SSD1306` needed to be updated to use the offset too.
2. Address calculations in `calc_bounds_90()` were wrong, but they gave correct values for previously supported displays. The errors were uncovered when trying to configure the driver for the 64×48 display size — in this case the display width is no longer an integer multiple of the display height, and therefore blocks no longer occupy the whole height when using 90°/270° rotation, and the top and bottom page numbers in addressing commands must be calculated properly.
3. While fixing the code, I also implemented the 90°/270° rotation support for `OLED_IC_SH1106` — it gives a 20% to 50% performance penalty when testing on the 128×32 SSD1306 display (which actually supports both command sets), but this is still better than no rotation support at all.

Fixes from #10377 are also needed to make these displays work properly.

### TODO before removing the draft status

- [ ] Document `OLED_COLUMN_OFFSET` support for `OLED_IC_SSD1306`
- [ ] Document rotation support for `OLED_IC_SH1106`
- [ ] Figure out the appropriate location for example display configs and add configs for these displays there

### Configuration for the 64×32 SSD1306 display

```c
#define OLED_DISPLAY_CUSTOM
#define OLED_DISPLAY_WIDTH 64
#define OLED_DISPLAY_HEIGHT 32
#define OLED_COLUMN_OFFSET 32
#define OLED_MATRIX_SIZE (OLED_DISPLAY_HEIGHT / 8 * OLED_DISPLAY_WIDTH)
#define OLED_BLOCK_TYPE uint8_t
#define OLED_BLOCK_COUNT (sizeof(OLED_BLOCK_TYPE) * 8)
#define OLED_BLOCK_SIZE (OLED_MATRIX_SIZE / OLED_BLOCK_COUNT)
#define OLED_COM_PINS COM_PINS_ALT
#define OLED_SOURCE_MAP { 0, 8, 16, 24 }
#define OLED_TARGET_MAP { 24, 16, 8, 0 }
```

### Configuration for the 64×48 SSD1306 display

```c
#define OLED_DISPLAY_CUSTOM
#define OLED_DISPLAY_WIDTH 64
#define OLED_DISPLAY_HEIGHT 48
#define OLED_COLUMN_OFFSET 32
#define OLED_MATRIX_SIZE (OLED_DISPLAY_HEIGHT / 8 * OLED_DISPLAY_WIDTH)
#define OLED_BLOCK_TYPE uint32_t
#define OLED_BLOCK_COUNT 24
#define OLED_BLOCK_SIZE (OLED_MATRIX_SIZE / OLED_BLOCK_COUNT)
#define OLED_COM_PINS COM_PINS_ALT
#define OLED_SOURCE_MAP { 0, 8 }
#define OLED_TARGET_MAP { 8, 0 }
```

### Configuration for the 64×128 SH1107 display

```c
#define OLED_DISPLAY_CUSTOM
#define OLED_DISPLAY_WIDTH 64
#define OLED_DISPLAY_HEIGHT 128
#define OLED_COLUMN_OFFSET 32
#define OLED_MATRIX_SIZE (OLED_DISPLAY_HEIGHT / 8 * OLED_DISPLAY_WIDTH)
#define OLED_BLOCK_TYPE uint16_t
#define OLED_SOURCE_MAP { 0, 8, 16, 24, 32, 40, 48, 56 }
#define OLED_TARGET_MAP { 56, 48, 40, 32, 24, 16, 8, 0 }
#define OLED_BLOCK_COUNT (sizeof(OLED_BLOCK_TYPE) * 8)
#define OLED_BLOCK_SIZE (OLED_MATRIX_SIZE / OLED_BLOCK_COUNT)
#define OLED_COM_PINS COM_PINS_ALT
#define OLED_IC OLED_IC_SH1106
```

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by sigprof** [comment]
After some more testing it seems that the configuration for the 64×128 SH1107 display that I found is in fact wrong — I noticed that the right column was showing some garbage with low brightness; seems that the proper configuration involves changing the `MULTIPLEX_RATIO` and `DISPLAY_OFFSET` I2C command arguments, and the current driver does not offer a way to set these values from config.h.

**Comment by zvecr** [comment]
Just FYI (also tagging @fauxpark),  a quick test with a `64×128 SH1107 display` no longer gives a clean black/white output with the default settings since the recent OLED brightness changes.

Kinda difficult to get an image, but


Setting `OLED_BRIGHTNESS` less than 30, or reverting the 0x40 -> 0x20 change is enough to give a more pleasing output.

**Comment by sigprof** [comment]
@zvecr Yes, the code for the 64×128 display (which actually uses the SH1107 chip, not SH1106) was wrong. Look at https://github.com/qmk/qmk_firmware/compare/master...sigprof:oled-driver-new-hardware-support-v2 for now (I'm still rearranging those commits though).

The configuration for that 64×128 screen with the new code would be:

```c
#define OLED_DISPLAY_CUSTOM
#define OLED_DISPLAY_WIDTH 64
#define OLED_DISPLAY_HEIGHT 128
#define OLED_COM_PIN_OFFSET 32
#define OLED_MATRIX_SIZE (OLED_DISPLAY_HEIGHT / 8 * OLED_DISPLAY_WIDTH)
#define OLED_BLOCK_TYPE uint16_t
#define OLED_SOURCE_MAP { 0, 8, 16, 24, 32, 40, 48, 56 }
#define OLED_TARGET_MAP { 56, 48, 40, 32, 24, 16, 8, 0 }
#define OLED_BLOCK_COUNT (sizeof(OLED_BLOCK_TYPE) * 8)
#define OLED_BLOCK_SIZE (OLED_MATRIX_SIZE / OLED_BLOCK_COUNT)
#define OLED_COM_PINS COM_PINS_ALT
#define OLED_IC OLED_IC_SH1107
```

**Comment by fauxpark** [comment]
The VCOMH deselect value might need to be chip-specific, then, or at least configurable.

**Comment by tzarc** [comment]
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

**Comment by KarlK90** [comment]
I've been using your implementation from the v2 branch since a couple of days without any problems, thank you! 

The SH1107 Displays (link no longer works but I think it is [this one](https://www.aliexpress.com/item/4000547865501.html)) have very noticeable high pitched coil whine when lighting up large parts of the screen, setting `PRE_CHARGE_PERIOD` to `0x22` instead of `0xF1` fixes that problem to basically. This value is hard coded for all displays maybe this should be configurable as well?

**Comment by mrninhvn** [comment]
Hi, is there any update on this?

**Comment by shawe** [comment]
I'm trying the SSD1107 OLED from this link https://es.aliexpress.com/item/4000547865501.html?spm=a2g0o.9042311.0.0.a99263c0nuLi91 on a Lily58L, and seems to work fine but only with OLED_ROTATION_270 (at least works).

Can I help with any way to try to add better support?

**Comment by mrninhvn** [comment]
> I'm trying the SSD1107 OLED from this link https://es.aliexpress.com/item/4000547865501.html?spm=a2g0o.9042311.0.0.a99263c0nuLi91 on a Lily58L, and seems to work fine but only with OLED_ROTATION_270 (at least works).
> 
> Can I help with any way to try to add better support?

https://github.com/qmk/qmk_firmware/pull/15238
Take a look.

**Comment by drashna** [comment]
Has some merge conflicts.

(Also, the sh1107 has a 128x128 display too)

**Comment by joh** [comment]
Hi, is there any progress on this? Would love to see this merged :) FWIW the v2 branch seems to work fine on top of latest develop (after resolving some conflicts). Tested on these [GME64128-02](https://www.aliexpress.com/item/1005004383312299.html) modules.

**Comment by drashna** [comment]
> drashna marked this pull request as ready for review [8 hours ago]

Not intentionally, at least. 

Also, can also confirm that the v2 branch works well with the 128x128 SH1107 screens.

would like to get this or similar merged, partially because it's a pain to maintain a separate file

**Comment by drashna** [comment]
Closing this since #20331 covers this, and some of the added suggestions

**Pull request closed without merging**
