### PR TITLE
add 'KEYBOARD_LOCAL_FEATURES_MK' into build_keyboard.mk

### PR DESCRIPTION
**Pull request by mtei**
## Description

KEYBOARD_LOCAL_FEATURES_MK has the file name of the file that contains
the keyboard post-processing rules.

Post-processing rules convert keyboard-specific shortcuts that represent
combinations of standard options into QMK standard options.

Usage:
```c
// file: keyboards/helix/rev2/rules.mk
KEYBOARD_LOCAL_FEATURES_MK := $(dir $(lastword $(MAKEFILE_LIST)))local_features.mk

HELIX_ROWS = 5              # Helix Rows is 4 or 5
LED_BACK_ENABLE = no        # LED as backlight (Enable WS2812 RGB backlight.)
LED_UNDERGLOW_ENABLE = no   # LED as underglow (Enable WS2812 RGB underlight.)
IOS_DEVICE_ENABLE = no      # connect to IOS device (iPad,iPhone)

```
```c
// file: keyboards/helix/rev2/keymaps/a_keymap/rules.mk
LED_BACK_ENABLE = yes        # LED as backlight (Enable WS2812 RGB backlight.)
```
```c
// file: keyboards/helix/rev2/local_features.mk
ifneq ($(strip $(HELIX_ROWS)), 4)
  ifneq ($(strip $(HELIX_ROWS)), 5)
    $(error HELIX_ROWS = $(strip $(HELIX_ROWS)) is unexpected value)
  endif
endif
OPT_DEFS += -DHELIX_ROWS=$(strip $(HELIX_ROWS))

ifeq ($(strip $(LED_BACK_ENABLE)), yes)
  RGBLIGHT_ENABLE = yes
  OPT_DEFS += -DRGBLED_BACK
else ifeq ($(strip $(LED_UNDERGLOW_ENABLE)), yes)
  RGBLIGHT_ENABLE = yes
endif

ifeq ($(strip $(IOS_DEVICE_ENABLE)), yes)
    OPT_DEFS += -DIOS_DEVICE_ENABLE
endif
```

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
This looks like it's a re-implementation of:
https://github.com/qmk/qmk_firmware/pull/2046

**Comment by mtei** [comment]
I previously found #2046, but I forgot it and created this PR. I don't mind either implementation.

**Comment by drashna** [comment]
Yeah, it was on my minds, since I just went through all of our open PRs....

**Comment by drashna** [comment]
Double checking this PR, I think that seeb's may be the better implementation, and the one that we should go with, long term.   It supports every layer of the makefile stuff, which also allows for some pretty cool stuff (well, the same stuff as here, but at all levels, from what I've seen.

**Comment by mtei** [comment]
Choose a more appropriate one. :-)

**Comment by drashna** [comment]
Mostly, I'm adding the "On Hold" label, since there is discussion around this topic (eg, the best way to handle this). And so the Stale bot doesn't close the PR

**Comment by mtei** [comment]
This is closed because I have opened a more general PR. #8422

**Pull request closed without merging**
