### PR TITLE
Include lib8tion.c into RGB matrix build list

### PR DESCRIPTION
**Pull request by filterpaper**
## Description

Random functions in lib8tion's `random8.h` requires the variable `rand16seed` that is externally initialised in `lib8tion.c`. Included that as part of source files to be built with `RGB_MATRIX_ENABLE`.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — CHANGES_REQUESTED** [review]
My preference is something like
```diff
diff --git a/common_features.mk b/common_features.mk
index 8c9d0a90c..917469ced 100644
--- a/common_features.mk
+++ b/common_features.mk
@@ -255,6 +255,7 @@ endif
     SRC += $(QUANTUM_DIR)/color.c
     SRC += $(QUANTUM_DIR)/rgb_matrix.c
     SRC += $(QUANTUM_DIR)/rgb_matrix_drivers.c
+    SRC += $(LIB_PATH)/lib8tion/lib8tion.c
     CIE1931_CURVE := yes
     RGB_KEYCODES_ENABLE := yes
 
```

As this,
* avoids the known issues on gcc10 and fcommon
* adds fewer modifications to the library

**Comment by filterpaper** [comment]
> My preference is something like

This will probably increase firmware size across the board, but does sound like a better idea. If this suggestion is preferred by everyone, I can make the change.

**Review by drashna — APPROVED** [review]

**Comment by filterpaper** [comment]
Bumping this @drashna and @zvecr. It's a dependency of #12670.

**Review by fauxpark — CHANGES_REQUESTED** [review]
This PR should target develop and be applied for LED Matrix too.

**Comment by filterpaper** [comment]
> This PR should target develop and be applied for LED Matrix too.

Added for `LED_MATRIX_ENABLE`.

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
You have a couple of merge conflicts that need to be resolved.

**Comment by filterpaper** [comment]
> You have a couple of merge conflicts that need to be resolved.

Sorry I missed those. Conflicts are resolved.

**Pull request merged**
