### PR TITLE
Added support for Wb32fq95

### PR DESCRIPTION
**Pull request by wb-Joy**
## Description

The Chibios-Contrib repository needs to be updated.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Please supply datasheets and reference manuals for this new chip family -- no documentation exists on your site.

**Comment by wb-Joy** [comment]
[EN_RM2905025_WB32FQ95xx_V01.pdf](https://github.com/qmk/qmk_firmware/files/8506450/EN_RM2905025_WB32FQ95xx_V01.pdf)
[EN_DS1104041_WB32FQ95xC_V01.pdf](https://github.com/qmk/qmk_firmware/files/8506467/EN_DS1104041_WB32FQ95xC_V01.pdf)
@tzarc

**Comment by wb-Joy** [comment]
Is there any progress?

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
> http://www.westberrytech.com/down/20220419/EN_DS1104041_WB32FQ95xC_V01.pdf http://www.westberrytech.com/down/20220419/EN_RM2905025_WB32FQ95xx_V01.pdf @tzarc

@itarze do you still have copies of these documents available somewhere? The links are broken.

**Comment by itarze** [comment]
[EN_RM2905025_WB32FQ95xx_V01.pdf](https://github.com/qmk/qmk_firmware/files/10778546/EN_RM2905025_WB32FQ95xx_V01.pdf)
[EN_DS1905020_WB32FQ95xC_V01.pdf](https://github.com/qmk/qmk_firmware/files/10778548/EN_DS1905020_WB32FQ95xC_V01.pdf)

@tzarc

**Comment by itarze** [comment]
Download links from the official website :
[EN_DS1905020_WB32FQ95xC_V01.pdf](http://westberrytech.com/uploads/file/WB32FQ95xx/EN_DS1905020_WB32FQ95xC_V01.pdf)  
[EN_RM2905025_WB32FQ95xx_V01.pdf](http://westberrytech.com/uploads/file/WB32FQ95xx/EN_RM2905025_WB32FQ95xx_V01.pdf)

**Comment by tzarc** [comment]
Thanks!

**Pull request merged**
