### PR TITLE
Far better VSCode intellisense support using clangd.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

`clangd` seems to be a lot better at dealing with detection of paths and the like automatically.

Draft PR for now while we work out dependencies -- macOS should be fine, Linux and Windows may need separate installations. Documentation to match, once figured out.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
IIRC, I have used the clang version and had more weird issues with it. But that's ... been a while so it may be improved, now.

**Comment by elpekenin** [comment]
Been using this for a few days and im liking it better. 

However, it has messed code up a few times because it includes headers when auto-completing, causing issues with the order in which things are declared.

Have just found out I can add to `settings.json` this config, which will hopefully prevent those, will update with another comment if it doesnt fix
```
    "clangd.arguments": [
        "--header-insertion=never"
      ],
```

**Comment by tzarc** [comment]
@elpekenin added.

**Review by drashna — APPROVED** [review]

**Comment by daskygit** [comment]
Worth updating the docs to go with this?
https://github.com/qmk/qmk_firmware/blob/master/docs/other_vscode.md#configure-vs-code-for-qmk

**Comment by tzarc** [comment]
> Worth updating the docs to go with this? [`master`/docs/other_vscode.md#configure-vs-code-for-qmk](https://github.com/qmk/qmk_firmware/blob/master/docs/other_vscode.md?rgh-link-date=2023-05-10T22%3A05%3A09Z#configure-vs-code-for-qmk)

Yep, was part of the intended plan as per the PR description, just hadn't gotten to it yet.
Main holdup was me not having a QMK WSL install to test with -- QMK MSYS has `clang` so it should be fine to rely on there, just haven't gone through the motions on WSL yet.

**Review by drashna — APPROVED** [review]

**Pull request merged**
