### PR TITLE
fixed build break (size overflow) HelixPico with Backlight or Underglow

### PR DESCRIPTION
**Pull request by mtei**

### CODE REVIEW

**Comment by drashna** [comment]
It may help to make sure that console and command are disabled in the rules.mk (for the main keyboard, actually).

And it may be a good idea to add this block to the config.h: 

```c
#if !defined(NO_DEBUG) && !defined(CONSOLE_ENABLE)
#define NO_DEBUG // if console isn't enabled, why are we debugging? 
#endif // !NO_DEBUG
#if !defined(NO_PRINT) && !defined(CONSOLE_ENABLE)
#define NO_PRINT // if console is disabled, there is nowhere to print to
#endif // !NO_PRINT
// LTO has issues with macros (action_get_macro) and "functions" (fn_actions), so just disable them
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#define DISABLE_LEADER
```

I use this, along with `EXTRAFLAGS        += -flto` in the rules.mk file to reduce the file size. And it really does help.

**Comment by mtei** [comment]
this block
```
#if !defined(NO_DEBUG) && !defined(CONSOLE_ENABLE)
#define NO_DEBUG // if console isn't enabled, why are we debugging? 
#endif // !NO_DEBUG
#if !defined(NO_PRINT) && !defined(CONSOLE_ENABLE)
#define NO_PRINT // if console is disabled, there is nowhere to print to
#endif // !NO_PRINT
```
more simply as follows?
```
#if !defined(CONSOLE_ENABLE)
  #define NO_DEBUG
  #define NO_PRINT
#endif
```

**Comment by drashna** [comment]
Sorry, yeah, it probably would.

I have it set that way, as some boards have those defined already, and if you redefine them with undefining them... it causes the compiler to error out.   Bet if this in the keyboard itself, then that would be better

**Comment by mtei** [comment]
I tried '#define NO_DEBUG' and '#define NO_PRINT' in config.h, but it occured error.

because tmk_core/common.mk include this block.

```
ifeq ($(strip $(CONSOLE_ENABLE)), yes)
    TMK_COMMON_DEFS += -DCONSOLE_ENABLE
else
    TMK_COMMON_DEFS += -DNO_PRINT
    TMK_COMMON_DEFS += -DNO_DEBUG
endif
```

**Comment by drashna** [comment]
Ah, good to know!  

However, the other stuff would still help (the no action function and no macros)

**Comment by drashna** [comment]
Thanks!

**Comment by mtei** [comment]
Thank you !

**Pull request merged**
