### PR TITLE
Think6.5 LED range control at keyboard level

### PR DESCRIPTION
**Pull request by rys**
Having implemented static control of the Think6.5 LED ranges in my personal map in qmk/qmk_firmware#7603, I've now separated it out and applied it at the keyboard level for both hotswap and solder versions of the Think6.5 PCB.

I’ve also added support for individual colour control for each of the 3 LED ranges, storing that configuration in upper EEPROM space away from the `eeconfig` code, similarly to how VIA and its `DYNAMIC_KEYMAP` support is implemented.

## Description

Separates out the LED range control into `led_control.[h|c]` at the keyboard level, plugs that into `rules.mk`, and wires it into the default maps on layer 1. The documentation for both default maps is updated to track the new functionality, which I've wired into unused keys so it doesn't change existing functionality that users are used to.

I've also updated my own personal map for the solder version to use the new keyboard-level LED controls, along with wiring in caps lock indication to the badge LEDs to show users how that can be done. I didn't add that to the default map just in case the behaviour bothered people.

If I make a breaking change to what's stored in user EEPROM in future versions of the code I'll remember to update the magic value to invalidate the existing EEPROM contents so the firmware doesn't try and load them.

It also includes a workaround for when `keyboard_post_init_user()` is called, which I discussed with maintainers on QMK Discord recently. I run a 250ms wait before calling into further code that needs to run "late".

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by rys** [comment]
One thing I didn't mention in the PR: I disabled mouse keys support in order to free up more firmware space taken up by the LED control code. A build with it on is under the size limit (`28032/28672 (97%, 640 bytes free)`), so I can reenable mouse keys by default if you think it's not a good idea to have it off like that.

**Comment by rys** [comment]
> One thing I didn't mention in the PR: I disabled mouse keys support in order to free up more firmware space taken up by the LED control code. A build with it on is under the size limit (`28032/28672 (97%, 640 bytes free)`), so I can reenable mouse keys by default if you think it's not a good idea to have it off like that.

Tested whether an almost full firmware was a problem and it's not, so I've turned it back on in 9d7b724.

**Comment by rys** [comment]
I don't use mouse keys, so I've turned it off in my personal map to make CI pass, in 2203d60. It complains the firmware is too big, yet when I build locally I get `28250/28672 (98%, 422 bytes free)`. I guess my toolchain is different to the one that runs on Travis.

**Comment by rys** [comment]
Is there anything I can do to help expedite the review? I've got future changes that build on top of this code, so I'd like to see it get to master if possible.

**Comment by DitwanP** [comment]
Hey what happened to this? I tried the test firmware that included your zone control functionality but it  wasn't recognized by VIA and I'm new to this and dont know how to add my own keybinds on top of it. Could you maybe point me in the right direction?

**Pull request closed without merging**
