### PR TITLE
.vscode/ added to .gitignore because it is IDE specific

### PR DESCRIPTION
**Pull request by droseger**
Apparently, the folder .vscode/ accidentally got added in a recent pull request. I propose adding the folder to .gitignore

### CODE REVIEW

**Comment by fredizzimo** [comment]
I disagree with these changes. Some of the settings there are very important for having a pleasant Visual Code experience. For example, the file exclude part, without that, searching would take forever because it would try to search in output and hex files, unless you restrict it in other ways. 

As can be seen here, the intent has always been for the settings.json file to be team specific and shared between the team https://github.com/Microsoft/vscode/issues/37519. 

That said, the file commonly gets modified automatically, because we don't have enough rules for files.associations for example, so more rules should be added to them. You might also want to have some personal settings. But that's no longer an issue, with the multi-root workspaces it's possible to get the best of the two worlds, you just need to create your own workspace, see this https://github.com/Microsoft/vscode/issues/37519 for example.

**Comment by droseger** [comment]
Well, the folder was added as a byproduct of _Xton's first keymap! (#2941)_, it clearly wasn't added because Visual Code users thought it best to do so. Besides, the same is true for .idea/: A lot of useful settings can be set there. .idea/ is already in .gitignore.
I think it has advantages not to pollute a repo with IDE files. Every one of them adds a bit of noise.

**Comment by fredizzimo** [comment]
No I added the settings in this commit https://github.com/qmk/qmk_firmware/commit/448b91689fc774aded9e646b66256a5c35c3ccf7#diff-5b46cfda0ddaed371f52aa24ea2b0b2a, almost a year ago

**Comment by droseger** [comment]
Ok, it seems i misread the git log. It still seems weird to have this folder, though.

**Comment by slang800** [comment]
@fredizzimo Do people _need_ to use VSCode to be able to work on QMK, or is it just something that you recommend?

**Comment by drashna** [comment]
@slang800 it's not required. You could use any text editor, too.  But VSCode works VERY well, as it is able to process the includes, and well, include folders for code ("intellisense", I believe). 

And the files included in the `.vscode` folder make it easier to get started, and it tells vscode how to handle some folders and files. 

So, it's not necessary, but it's very helpful.  And I personally don't think it's a good idea to remove then.

**Comment by drashna** [comment]
As there has been no update on this, and it sounds like we want to keep the .vscode files, I think we should close this PR.

If you disagree, then please re-open it!

**Pull request closed without merging**
