### PR TITLE
Update docker util script and travis to use new base container

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Now that <https://github.com/qmk/qmk_base_container> exists, we can update the travis build to use the new "slim" image, that does not bundle the qmk_firmware repo, and not build the image for every build. Should save a small amount of time (~100 seconds), and more importantly, increase the repeatability between builds.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by yanfali** [comment]
I thought we did this already?

**Comment by drashna** [comment]
I think we did, after this. But yeah.

**Comment by yanfali** [comment]
@zvecr ok to close this?

**Comment by zvecr** [comment]
@yanfali @drashna This is still required. We swapped travis to use docker, then pulled some common bits to a central image. This PR finished that tidy up, and is similar to the work behind <https://github.com/qmk/qmk_compiler/pull/45>.

**Pull request merged**
