### PR TITLE
Fix midi after recent refactoring

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Seems to compile now, no idea if its the "best" fix.

Used to live in:
https://github.com/qmk/qmk_firmware/blob/e296d671463f38a78c75ee0727016939634ef985/tmk_core/protocol/midi.mk#L9

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by tzarc — APPROVED** [review]

**Comment by fauxpark** [comment]
I tested this before and it seemed to compile fine without it, on both AVR and ChibiOS?

**Comment by zvecr** [comment]
You might want to recheck AVR, as its currently failing.

```console
$ make clean bandominedoni:default
QMK Firmware 0.19.11
Deleting .build/ ... done.
Making bandominedoni with keymap default
...
Linking: .build/bandominedoni_default.elf                                                           [ERRORS]
 | 
 | /usr/bin/avr-ld: /tmp/ccRJP1QQ.ltrans0.ltrans.o: in function `.Loc.3848':
 | /home/zvecr/qmk_firmware/tmk_core/protocol/lufa/lufa.c:714: undefined reference to `MIDI_Device_SendEventPacket'
 | /usr/bin/avr-ld: /tmp/ccRJP1QQ.ltrans0.ltrans.o: in function `.Loc.3861':
 | /home/zvecr/qmk_firmware/tmk_core/protocol/lufa/lufa.c:718: undefined reference to `MIDI_Device_ReceiveEventPacket'
 | /usr/bin/avr-ld: /tmp/ccRJP1QQ.ltrans0.ltrans.o: in function `.Loc.4558':
 | /home/zvecr/qmk_firmware/tmk_core/protocol/lufa/lufa.c:886: undefined reference to `MIDI_Device_USBTask'
 | collect2: error: ld returned 1 exit status
 ```

**Comment by fauxpark** [comment]
I don't get it, CI didn't complain: https://github.com/qmk/qmk_firmware/runs/10947261782

**Comment by zvecr** [comment]
Except it is failing, and is holding up verification of other scenarios. We can work out how it slipped through at a later date.

**Comment by fauxpark** [comment]
Better solution, add this to lufa.mk next to the virtser one:
```
ifeq ($(strip $(MIDI_ENABLE)), yes)
	LUFA_SRC += $(LUFA_ROOT_PATH)/Drivers/USB/Class/Device/MIDIClassDevice.c
endif
```

**Review by fauxpark — APPROVED** [review]

**Comment by zvecr** [comment]
Cheers!

**Pull request merged**
