### PR TITLE
Add `SGUI()` and `SGUI_T()` for consistency with `KC_GUI`

### PR DESCRIPTION
**Pull request by skullydazed**

### CODE REVIEW

**Comment by fauxpark** [comment]
Perhaps SWIN and SCMD should actually be aliases of SGUI? Considering that is the key's "real" name.

**Comment by skullydazed** [comment]
You make a good point. Initially I had the mindset of making a minimal change, but this is minimal enough too.

**Comment by fauxpark** [comment]
SCMD now seems to be aliased to itself, I think you forgot something! :)

**Comment by skullydazed** [comment]
Whoops, it sure is. e5c331e7 fixes it, thanks for the note!

**Pull request merged**
