### PR TITLE
Custom user keymap for Think6.5 with LED range control

### PR DESCRIPTION
**Pull request by rys**
Adds an ISO layout to the solderable version of the Think6.5, and user cycling of the RGB ranges on the board which get saved and restored to user EEPROM so they persist when the board resets.

## Description

The Think6.5 has a bunch of RGB LEDs grouped into three main ranges. This keymap allows the user to cycle through all combinations of those ranges, and toggle them on and off individually, saving and restoring the chosen state in user EEPROM.

I've also added an ISO layout to the solderable version of the PCB, which it supports.

If the general LED control idea is good I'd be happy to add it to the top level default maps for both Think6.5 PCB types and maintain it. I've no idea if the way I manage, cycle and toggle the LED state map for the ranges is a good idea or not. Please suggest a better way to do it if there is one!

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by rys** [comment]
> You will need to update the info.json otherwise configurator will break.

Sorry about that, I'll add the new layout type as soon as I figure out how info.json works.

**Comment by yanfali** [comment]
> > You will need to update the info.json otherwise configurator will break.
> 
> Sorry about that, I'll add the new layout type as soon as I figure out how info.json works.

@noroadsleft can help you out. Easiest thing is get a KLE of your new layout and pass it through qmk.fm/converter take that output and add it to the layouts in the info.json

**Comment by MudkipMao** [comment]
Nice! @rys

**Comment by rys** [comment]
Thanks @noroadsleft! I've applied those suggestions and the layout for `info.json` to my tree.

**Pull request merged**
