### PR TITLE
Rename scotto userspace to scottokeebs

### PR DESCRIPTION
**Pull request by joe-scotto**
The `scotto` userspace should be called `scottokeebs`.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by waffle87 — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]
I feel like userspace names should really match the GitHub username, but that's not in the docs right now AFAICT.

**Comment by zvecr** [comment]
Keymaps are still called `scotto` so this wont actually work?

**Comment by dunk2k** [comment]
> Keymaps are still called `scotto` so this wont actually work? Which would also imply this hasn't been tested at all?

@joe-scotto I think what zvecr is trying to say is:
1. `scotto` keymaps in `/layouts/community/`* need amending also
2. amended keymaps in 1. tested locally to ensure they compile successfully
😉

**Comment by joe-scotto** [comment]
@zvecr

1. I spoke with @fauxpark yesterday on Discord about the root of this issue, it had to do with TD functions being shared between keymaps in a keyboard named `scotto` and the userspace being named `scotto`. If both are named the same, they're both compiled into your board.
2. The keymaps do not **need** to be renamed, the one within a keyboard directory will take precedence over the one stored in the community layouts.
3. I tested this locally, multiple times. 

Renaming the userspace from `scotto` to `scottokeebs` fixes the issue entirely and all the work @dunk2k did on the community layout is still functional without the need to change 20+ boards with new PRs. That said, I do think for consistency's sake it makes sense to rename the community layout to `scottokeebs` that way there isn't confusion on which is being used.

**Comment by fauxpark** [comment]
That is not what I was saying at all. Your problem is that you have tap dances defined in your keymap, but you do not need to do that because they're already in your userspace.

**Comment by joe-scotto** [comment]
@fauxpark Thats what I meant, its early here...

Regardless this should fix the issue without needing to change 20 boards keymaps. The`scottokeeebs` userspace/community layout becomes the "public" one and then on each board there is the `scotto` keymap that is my personal one for that board.

**Comment by fauxpark** [comment]
But now you need to manually set the username for each of your keymaps, instead of having it automatically picked up because the names match.

**Comment by joe-scotto** [comment]
That is fine, none of them are actually using the userspace anyway... yet. 

The goal is to eventually remove the `scotto` maps all together from each board where it has a community layout and then the keymap just become `scottokeebs`. Part of this will also be updating the boards without a community layout to use the userspace, but the userspace needs to be sorted for that to happen.

**Comment by zvecr** [comment]
> The keymaps do not need to be renamed, the one within a keyboard directory will take precedence over the one stored in the community layouts.

You did, because they wouldn't have compiled, due to the `scotto.h` file no longer existing.

> But now you need to manually set the username for each of your keymaps, instead of having it automatically picked up because the names match.

Because neither of these things had been done. And why my suggestion that it hadnt actually been tested.

**Comment by joe-scotto** [comment]
@zvecr Please read up in the comments. 

None of the keyboards actually use the userspace nor reference `scotto.h`. The issue was that `scotto` keymaps had TD code that was also defined in the userspace, this was leading to compilation errors when they share the same name: `scotto`

Instead of having to change 20 boards, changing the userspace to just `scottokeebs` solves everything. Eventually the `scotto` keymaps will be phased out in favor of the community layout `scottokeebs`

**Comment by joe-scotto** [comment]
@zvecr That is the community layout, I'm referring to keymaps in `keyboards/handwired/scottokeebs`. 

Only reason I changed the community layout is to keep a clear distinction between keymaps within the keyboard folder and the actual community layout as they differ.

**Comment by zvecr** [comment]
At the point of where I initially commented, [1277c6d](https://github.com/qmk/qmk_firmware/pull/21753/commits/1277c6d51d871dce2730101d5cb46420cd076aba), keymaps would not have compiled due to the previously mentioned mis-match.

```
gh pr checkout 21753
make git-submodule
git checkout 1277c6d

make clean cradio:scotto
QMK Firmware 0.21.6
Deleting .build/ ... done.
Making cradio with keymap scotto

Generating: .build/obj_cradio_scotto/src/info_deps.d                                                [OK]
avr-gcc (GCC) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Generating: .build/obj_cradio/src/info_config.h                                                    Generating: .build/obj_cradio/src/default_keyboard.c                                               Generating: .build/obj_cradio/src/default_keyboard.h                                                [OK]
 [OK]
 [OK]
Compiling: quantum/keymap_introspection.c                                                          Compiling: keyboards/cradio/cradio.c                                                               Compiling: quantum/quantum.c                                                                       Compiling: .build/obj_cradio/src/default_keyboard.c                                                Compiling: quantum/led.c                                                                           Compiling: quantum/bitwise.c                                                                       In file included from quantum/keymap_introspection.c:5:
./layouts/community/split_3x5_2/scotto/keymap.c:19:10: fatal error: scotto.h: No such file or directory
   19 | #include "scotto.h"
      |          ^~~~~~~~~~
compilation terminated.
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [builddefs/common_rules.mk:361: .build/obj_cradio_scotto/quantum/keymap_introspection.o] Error 1
make[1]: *** Waiting for unfinished jobs....
 [OK]
 [OK]
 [OK]
 [OK]
 [OK]
Make finished with errors
make: *** [Makefile:392: cradio:scotto] Error 1
```

Community layout keymaps would only replace in the case where the keymap exists in both places, this is not entire use case (as can be shown in the above compile failure). If the intention is that only the keyboard level keymaps are to be used, then the community layouts (and the userspace somewhat too) are not providing any value.

These keymaps not pulling in userspace as intended or zero keymaps pulling in that userspace would have been its own issue, mostly due to the redundancy around "dead" code. Either renaming keymaps (and fixing lingering errors) or reverting the userspace rename would have been a hard requirement.

In the short term, we certainly wouldn't want to be knowingly accepting broken code into the repo. Thus me flagging the issue.

**Comment by joe-scotto** [comment]
@zvecr 

> At the point of where I initially commented, [1277c6d](https://github.com/qmk/qmk_firmware/pull/21753/commits/1277c6d51d871dce2730101d5cb46420cd076aba), keymaps would not have compiled due to the previously mentioned mis-match.

That should be all fixed and as you can see it's passing the checks: https://github.com/qmk/qmk_firmware/pull/21753/commits/e793807875b0bf0ff7483d5f9ae4a55b9acf7d1d



> Community layout keymaps would only replace in the case where the keymap exists in both places, this is not entire use case (as can be shown in the above compile failure). If the intention is that only the keyboard level keymaps are to be used, then the community layouts (and the userspace somewhat too) are not providing any value.

I don't know if you're familiar with my `ScottoKeebs` project... basically, I design **a lot** of boards (20+ at the time of writing). Many of which are 3x5 split layouts that share the same keymap. I've been slowly getting them all merged over the last few months and @dunk2k came to me with the idea to add a userspace/community layout in order to compile those all into a single location. This happened at the same time as merging the boards so the goal is to switch them over to the community layout over time. The community layout is designed to work with 4x10, 3x5_2, and 3x5_3, not just my boards. It's meant to be a "competitor" to something like Miryoku.


> These keymaps not pulling in userspace as intended or zero keymaps pulling in that userspace would have been its own issue, mostly due to the redundancy around "dead" code. Either renaming keymaps (and fixing lingering errors) or reverting the userspace rename would have been a hard requirement.

The community layout uses the userspace so it's not "dead code".

> In the short term, we certainly wouldn't want to be knowingly accepting broken code into the repo. Thus me flagging the issue.
All in all... are you saying this PR won't be merged, I'm confused on exactly what the issue is. From my understanding the use of the community layout is correct and so is the user space. It seems you have a problem with these existing and then me just having `scotto` keymaps? 

I'm just trying to figure out what needs to be done.

**Comment by zvecr** [comment]
> That should be all fixed and as you can see it's passing the checks: https://github.com/qmk/qmk_firmware/commit/e793807875b0bf0ff7483d5f9ae4a55b9acf7d1d

They didnt initially, when i first made the observation, the fixes went in later, which is the core of my whole point.

> The community layout uses the userspace so it's not "dead code".

They also didnt, another part of my point.

> In the short term, we certainly wouldn't want to be knowingly accepting broken code into the repo. Thus me flagging the issue.
> > All in all... are you saying this PR won't be merged

The context here was the broken code you had at [this](https://github.com/qmk/qmk_firmware/pull/21753#issuecomment-1678585292) point in time. Subsequently, most of what I have been trying to get across, have been the errors stated in reasoning for your changes (or position on not changing). There's a lot I would want to say on assumptions made here this PR and the review, but at this point it doesn't seem worth it. Hopefully QMKs near future will provide a way that we no longer have to manage this sort of content.

You could call the broken code that potentially slipped through review process  _fixed_ **now**. Maybe that's all that matters.

**Review by fauxpark — CHANGES_REQUESTED** [review]
Please revert the submodule changes.

**Review by fauxpark — COMMENTED** [review]
Seems like some of this is duplicated in your other PRs.

**Comment by joe-scotto** [comment]
They should all be reverted now if I did it correctly.

**Comment by joe-scotto** [comment]
Closing this as it seems userspaces are no more.

**Pull request closed without merging**
