### PR TITLE
Specify incompatible MCUs in bluetooth docs. Fix #11498

### LINKED ISSUE #11498: [Docs] Bluetooth documentation should specify that only LUFA based MCUs are supported
`docs/feature_bluetooth.md` states:
> Currently Bluetooth support is limited to AVR based chips.

However, since the actual support is implemented as part of the LUFA stack in `tmk_core/protocol/lufa`, non-LUFA AVR devices like atmega32a, atmega328(p) are unsupported.
The page should instead state something like:
> Currently Bluetooth support is limited to AVR based chips with native USB support. Non-AVR based chips and AVR based chips using VUSB are unsupported.

### PR DESCRIPTION
**Pull request by Gigahawk**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* Fixes #11498 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Thanks for your contribution!

I've actually been working on improving the Bluetooth support, and have managed to get the Bluefruit module running on a Proton-C recently, so this will not be necessary soon.

**Comment by Gigahawk** [comment]
That's good to hear!
Are you working on all platforms? Or just ARM/STM microcontrollers?
I have a design right now using an ATmega328p and it would be nice to not have to redo it with a 32u4

**Comment by fauxpark** [comment]
My goal is to implement a Bluetooth API in QMK, which does most of the platform-specific heavy lifting, so that a driver for a module will work for ChibiOS, LUFA and V-USB boards with little to no changes necessary.

**Comment by Gigahawk** [comment]
Has this support been pushed anywhere?
Even if it's not stable or ready for general use I would love to have something to validate that my hardware design was at least correct.

**Comment by drashna** [comment]
other than in fauxpark's fork, no.  It has been talked about, though.

**Comment by Gigahawk** [comment]
Given that it's been nearly 2 months and support is still not present nor seemingly anytime soon, can we at least get this merged for now to avoid misleading anyone who might try to design hardware before support is available?

**Pull request closed without merging**
