### PR TITLE
Shuffle keyboards into thevankeyboards directory

### PR DESCRIPTION
**Pull request by mechmerlin**
- Moved bananasplit, tv44, and roadkit into thevankeyboards directory
- Update readmes with new info and new make instructions

### CODE REVIEW

**Comment by jackhumbert** [comment]
Nice! Would you mind renaming `tv44` to `minivan` as well? Just pinged Evan about this & that, and he's down with it :)

**Comment by mechmerlin** [comment]
Done!

**Comment by drashna** [comment]
Could you update the readme's to reflect the new paths?

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
