### PR TITLE
Initial MBI5042GP 16-bit LED PWM driver release

### PR DESCRIPTION
**Pull request by GitWellBack**
## Description

Macroblock MBI5042GP 16-bit 16 output PWM LED driver for QMK

I had to add a 16-bit CIE1931 curve dataset and extend the driver calling code in quantum, otherwise everything is in its own drivers folder (mbi5042gp)

This is part 1 of the Ducky One2mini integration into QMK (hopefully only 2 other parts for the full integration)

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by GitWellBack** [comment]
Hold off on this one - I think even these few files are using MCU-specific calls for some timers.

<sigh>

**Comment by drashna** [comment]
Any updates here?

**Comment by GitWellBack** [comment]
> Any updates here?

I was waiting on copyright clearance before making any changes - hence the slowness. I'll be pushing a new version today/tomorrow that doesn't reference MCU files and also has a section for standard PWM with an STM32 as an alternative method. Sorry for delays and thanks for keeping in review list!

**Comment by drashna** [comment]
Not a problem, at all.   And copyright clearance is an important thing! 
Though, just a heads up, any licensing would need to be GPL compliant/compatible.

**Comment by drashna** [comment]
I almost hate to do this, but @XScorpion2, since you've become the resident rgb/animation expert here, would you mind giving this a once over, to make sure the recent changes don't conflict with this?

Though, it may be worth holding off, until licensing is clarified.

**Comment by GitWellBack** [comment]
All ready for merge/review - OSS code is also waiting for merge into ChibiOS-Contrib (this can be un-held now, whenever you get a chance)

**Comment by drashna** [comment]
Is waiting on:
https://github.com/qmk/ChibiOS-Contrib/pull/10

**Comment by drashna** [comment]
Is this ready to go?

**Comment by bgulla** [comment]
+1

**Comment by drashna** [comment]
Re-reviewing this, could you add information to the appropriate documents pages? 

Eg, the feature_rgb_matrix page?

**Comment by drashna** [comment]
There are a number of merge conflicts here now. 


If you could, update PR to address this?

**Comment by ShaakhaBrahma** [comment]
Where to find the issue rised area of code?

**Comment by drashna** [comment]
There are some merge conflicts here now, and some changes to the rgb matrix stuff.

**Comment by fishman** [comment]
@drashna i'm updating these patched, can you explain what i would need to add in the feature_matrix?

also how can i set the keyboard to have reactive typing rgb enabled by default? I can't quite wrap my head around the RGB documentation

**Comment by drashna** [comment]
@fishman https://docs.qmk.fm/#/feature_rgb_matrix?id=additional-configh-options

It's the `RGB_MATRIX_STARTUP_MODE` value in that list.  Or you can use matrix init to do so at every start.

**Comment by drashna** [comment]
@GitWellBack was this dependent on the chibiOS-contrib update?   Or can this be merged without it?

**Comment by tzarc** [comment]
People can use this for inspiration if they want to pick up the Ducky One2Mini RGB LED -- at this stage this PR looks dead and can be reopened if the original submitter resurfaces and wishes to pursue the implementation.

**Comment by fishman** [comment]
i'm traveling and have no means to test any PWM changes until early next year

**Pull request closed without merging**
