### PR TITLE
Move Ixora and Vinta to proper vendor folder

### PR DESCRIPTION
**Pull request by coarse**
## Description

Rebranding my PCB services and will be updating these two keyboards in the near future. I will also be adding another keyboard in the same folder in the near future so I might as well start moving previous projects first. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* n/a

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Retargeted to `develop`, as it is a breaking change.

Also, a merge conflict exists here.

**Comment by drashna** [comment]
Looks like there are some merge conflicts here. Needs a rebase.

**Comment by tzarc** [comment]
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

**Comment by drashna** [comment]
There are a bunch of merge conflicts here.

**Comment by tzarc** [comment]
Closing in favour of #13898 -- conflicts were easier to resolve with a different PR.

**Pull request closed without merging**
