### PR TITLE
Fix all warnings and turn on warnings as errors

### PR DESCRIPTION
**Pull request by fredizzimo**
As discussed in #667, this pull request actually does what was agreed there.

I saw the huge amount of warnings especially from the ChibiOS keyboards, so I decided to take things into my own hands and fix everything and make sure it stays that way.

By default this pull request enables all warnings as errors, but it's possible to override this by providing the `ALLOW_WARNINGS=yes` option to make. This also adds another unrelated makefile option `BREAK_ON_ERRORS`, which stops building on errors instead of continuing with the next keymap/keyboard. And because everything comes in threes, there's a third makefile option added `SKIP_VERSION`, which speeds up the compilation by skipping the version file generation, so that less has to be recompiled if you run make again.

@lucwastiaux and nrrkeene. I changed some of you macros in your keymaps to use unshifted characters, as only 8-bit keycodes are allowed for them. The compiler should automatically have done the same thing so everything should work the same way. But it's of course possible that I have made a mistake so please report that to me if it's the case.

@fitzsim, I changed your special keymap macro to be compatible with both the EZ and Infinity. Again, I didn't test that it works, so please report any issues you have to me.

@milestogo, I had to rename `MS-sculpt-mobile` to `MS_sculpt_mobile` Our build system generates defines based on the project name, and `-` is not a valid character in C defines.

@ickerwx, I changed the  `MOUSEKEY_WHEEL_TIME_TO_MAX` setting from 1000 to 255. 255 is the maximum value supported. This might be a behavior change though, so please test it, 1000 % 255 = 235, so I think 235 is the value that it was actually using.

@deepshitgoeshere, I changed a couple of `register_code` calls to use unshifted characters, as only 8-bit codes are supported. There's also a register_code16 that could have been used, but since you are already manually registering shift, this was a smaller change.

@CommandLineDesign, I changed your startup_tone to use `MUSICAL_NOTE`, as `pow` is not allowed inside constant expressions in standard C. GCC allows it but generates a warning. As always I might have made a mistake during the conversion.

I think the rest are general warnings that concerns the firmware code itself.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Perfect :) thanks!

**Comment by fredizzimo** [comment]
@lucwastiaux, I forgot to mention that I also changed the wait from 500 to 255. 255 is the maximum supported value, and should actually be a bit longer than the previous 500, which is interpreted as 244.

@lucwastiaux, I'm mentioning you here again, because I forgot the `@` character in the original message, and I'm not sure if you will get a notification if I just edit that.

**Comment by fredizzimo** [comment]
🤣 The second mention in the message above should have been @nrrkeene. I guess everything really comes in threes, but this time I hope the third time is a charm.

**Comment by r2d2rogers** [comment]
This fixed 2 out of the three warnings I was seeing, but compiling for the right half of the infinity ergodox as master still has an implicit declaration error, but I'm not familiar enough with what order the files are compiled to sort it out:

`Compiling: keyboards/ergodox/infinity/matrix.c                                                     keyboards/ergodox/infinity/matrix.c: In function 'matrix_scan':
keyboards/ergodox/infinity/matrix.c:121:5: error: implicit declaration of function 'is_serial_link_master' [-Werror=implicit-function-declaration]
     if (is_serial_link_master()) {
`

**Comment by fredizzimo** [comment]
Ah, yes, I didn't try the right hand version. I will check that out now. 

I don't think the warning have anything to do with the disconnection bug though. But I will switch over to that configuration now to see if I can reproduce that one as well.

I will most likely also change how the handness is defined, I think the Infinity uses a different configuration variable than the Ez, so I will switch the Infinity to use the same one.

**Comment by r2d2rogers** [comment]
I don't think the EZ or the classic use handedness, there's only one Teensy or controller in them, if I recall correctly.

**Comment by fredizzimo** [comment]
It might be some other keyboard supported by QMK then. I'm pretty sure that I have seen some kind of mirror option somewhere.

**Comment by fredizzimo** [comment]
Let's Split has the defines MASTER_LEFT, and MASTER_RIGHT and EE_HANDS, but nothing in the makefiles. Vision Division has a KEYMAP_MASTER macro. So I think the makefile approach for the Infinity is good. 

Ideally I would like to store the information in EEPROM. So that you permanently write the correct value to each half. The half connected with the USB to the computer would then read its value, and behave accordingly. There are quite a few special cases when doing that, so support for it has to wait, at least from my part.

**Comment by fredizzimo** [comment]
https://github.com/qmk/qmk_firmware/pull/1226 fixes the warning when compiling as a right hand master.

**Pull request merged**
