### PR TITLE
Fix westfoxtrot/aanzee Configurator config

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Spotted within the output of http://compile.qmk.fm/v1/keyboards/error_log.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mechmerlin** [comment]
@westfoxtrot I knew you said you were gonna work on this so I thought it would be a good idea to have you on this PR too.

**Comment by westfoxtrot** [comment]
@zvecr thanks! I am still learning all this stuff so appreciate you taking the time to fix my mistake

**Comment by zvecr** [comment]
Seems this is still producing errors, however now
```json
{
	"message": "Error: westfoxtrot/aanzee: LAYOUT_iso: Number of elements in info.json does not match! info.json:68 != LAYOUT_iso:69",
	"severity": "error"
}, {
	"message": "Error: westfoxtrot/aanzee: LAYOUT_ansi: Number of elements in info.json does not match! info.json:68 != LAYOUT_ansi:69",
	"severity": "error"
}
```

Tracking this down, the info.json seems correct against all images of the board(assuming this is correct), and instead the LAYOUT macros have an extra key. It currently looks like the bottom row is configured for `space, X, Y, Z, arrows` while it should be `space, X, Y, arrows`, however i would only be able to guess which matrix position to edit.

Something like this for both the LAYOUT macros.
```diff
-  {K40, K41, K42, ___, ___, ___, K46, ___, ___, K49, K4A, K4B, K4C, K4D, K4E, ___}  \
+  {K40, K41, K42, ___, ___, ___, K46, ___, ___, K49, K4A, ___, K4C, K4D, K4E, ___}  \
```

@westfoxtrot Any ideas to what the layout/matrix should be?

**Comment by westfoxtrot** [comment]
> 
> 
> Seems this is still producing errors, however now
> 
> ```json
> {
> 	"message": "Error: westfoxtrot/aanzee: LAYOUT_iso: Number of elements in info.json does not match! info.json:68 != LAYOUT_iso:69",
> 	"severity": "error"
> }, {
> 	"message": "Error: westfoxtrot/aanzee: LAYOUT_ansi: Number of elements in info.json does not match! info.json:68 != LAYOUT_ansi:69",
> 	"severity": "error"
> }
> ```
> 
> Tracking this down, the info.json seems correct against all images of the board(assuming this is correct), and instead the LAYOUT macros have an extra key. It currently looks like the bottom row is configured for `space, X, Y, Z, arrows` while it should be `space, X, Y, arrows`, however i would only be able to guess which matrix position to edit.
> 
> Something like this for both the LAYOUT macros.
> 
> ```diff
> -  {K40, K41, K42, ___, ___, ___, K46, ___, ___, K49, K4A, K4B, K4C, K4D, K4E, ___}  \
> +  {K40, K41, K42, ___, ___, ___, K46, ___, ___, K49, K4A, ___, K4C, K4D, K4E, ___}  \
> ```
> 
> @westfoxtrot Any ideas to what the layout/matrix should be?

finally had a chance to go over this, as far as I can tell the issue is that indeed the layouts both have 69 keys rather than the matrix being wrong (additional ISO key & split backspace are in the configurator) I've submitted a fix for it, thanks so much for pointing it out!
@zvecr

**Pull request merged**
