### PR TITLE
drivers: Implemented i2c bitbang driver ALTERNATE

### PR DESCRIPTION
**Pull request by purdeaandrei**
## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by purdeaandrei** [comment]
Rebased to resolve conflicts

**Comment by daskygit** [comment]
This made someone very happy, they wanted to use a oled (128x32) on a trailmix (atmega32u4) and the hardware i2c peripheral pins are in use by the matrix. Compiled a keymap using this PR and worked flawlessly, docs were clear as well. So I'll thank you on there behalf.

**Comment by tzarc** [comment]
See my comment on #12616 -- same question applies.

**Comment by purdeaandrei** [comment]
Rebased to resolve conflicts
@tzarc I responded to your question on 12616

**Pull request closed without merging**
