### PR TITLE
`qmk fileformat`: only print complaints, and fix some of them

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

This should cut down on the noise in the logs. The remaining complaints are image files in keymaps, that probably should not be in the repo in the first place, a couple symlinks, and the submodules.

The Lily58 keymaps have an `0x08` just before the F4, for some reason, and the markdown file is using the actual ESC character rather than `\e` - @noroadsleft let me know if that's intentional, or whether this change breaks that stuff.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by Erovia — APPROVED** [review]

**Review by skullydazed — APPROVED** [review]

**Review by noroadsleft — COMMENTED** [review]
I'm fine with the change to my Markdown file. I wonder if this file got auto-formatted at some point, because I tested the rendering when I originally submitted it.

@yyc (`chaun`), @kata0510 (keyboard maintainer), and @BenRoe (`lily58l`) should sign off on the keymap changes IMO.

**Review by drashna — APPROVED** [review]

**Review by BenRoe — APPROVED** [review]
With my level of knowledge it looks fine.

**Review by yyc — APPROVED** [review]
Yup, this looks fine. Not sure how those characters got in either.

**Review by noroadsleft — APPROVED** [review]
`__attribute__ ((weak))` :heavy_check_mark: because I'm not knowledgeable in Python.

**Review by zvecr — APPROVED** [review]

**Comment by fauxpark** [comment]
Hm, this doesn't work actually...

**Pull request merged**
