### PR TITLE
Increased minimum breath value so that the effect looks smoother.

### PR DESCRIPTION
**Pull request by guarnacciaa**

### CODE REVIEW

**Comment by drashna** [comment]
@patrickmt Does this look good to you?

**Comment by patrickmt** [comment]
@guarnacciaa Have you tried any other values lower but not near zero that work well also? I tried 25 for minimum just to get slightly darker and it still looks OK. I agree zero minimum can exhibit an abrupt off/on but my suggestion would be for value 25 minimum.

**Comment by guarnacciaa** [comment]
I actually tried a value of 20, but then I noticed that the LEDs of the two halfs of the keyboard do not fade symetrically, one half gets significantly darker than the other one so that half keyboard has the LEDs almost off and the other half is significantly brighter. 
If needed I can test 25 and see how that reflects on my model.

**Comment by patrickmt** [comment]
Please do test at 25 when you have the chance.

**Comment by guarnacciaa** [comment]
I just tested all the values between 20 and 50 stepping up by 5 each time. 50 is the minimum acceptable value , any lower value shows the issue quite clearly.

**Comment by patrickmt** [comment]
Which half of the keyboard is darker? Also, which light pattern are you using for testing? Looking at the brightness curve created for the breathing, minimum values of 0-40 should output 0, 41-51 output 1, and 52-58 output 2. So it makes sense you are not seeing an acceptable change in your testing in these regions. I think the issue will be resolved with a new curve where the minimum output is limited to say 3 (or so). This will also allow for the length of the effect to stay as intended.

**Comment by guarnacciaa** [comment]
The right half is the darker one. I'm using the static color pattern (set to white).

**Comment by patrickmt** [comment]
When you get a chance, in /tmk_core/protocol/arm_atsam/i2c_master.c line 292, replace ISSI3733_CR_SYNC_MASTER with 0 and line 297 replace ISSI3733_CR_SYNC_SLAVE with 0 and see if this fixes the problem, with minimum breath back to 0.

**Comment by guarnacciaa** [comment]
I just tried that, I think we can say it totally fixes the issue, now the right half is as bright as the left one and the breathe effect is completely smooth during the entire loop. I think this can be considered as fixed :)

**Comment by patrickmt** [comment]
Great! Thanks for taking the time to go through this process with me. I've gone through additional testing and study on any visual side effects of taking the drivers out of sync, but all seems well. I will be getting the changes to the I2C setup into a pr later today.

**Comment by patrickmt** [comment]
The PR addressing this issue is included with #3890

**Comment by drashna** [comment]
Just to make sure, this is ready to go? 
@patrickmt ?

**Comment by drashna** [comment]
#3890 fixes this, according to @patrickmt (on discord).  Closing.

**Pull request closed without merging**
