### PR TITLE
Added Split Backspace Support for the Nemui

### PR DESCRIPTION
**Pull request by cBachoo**
## Description
Added split backspace support for the Nemui. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by ridingqwerty — CHANGES_REQUESTED** [review]
The `lib/vusb` updates will have to be removed from this PR.

Looks good otherwise.

**Comment by drashna** [comment]
You have some VUSB changes here.  You may need to run "make gitsubmodule", and add another commit to fix the issue.

**Comment by cBachoo** [comment]
Hopefully that fixed it, weird why it decided to update with me.

**Review by ridingqwerty — APPROVED** [review]
That did it, thanks.

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
