### PR TITLE
Change `led` to `led_matrix` in rgb_matrix_drivers

### PR DESCRIPTION
**Pull request by drashna**
Is a minor change that only affects the driver file. 

However, this will allow somebody to run rgblight along side rgb matrix
using the ws2812 driver, as well.  Specifically, so you can use the
custom driver for rgblight to set a different pin (barring a change to
the `ws2812_setleds` function).  

Courtesy of discord conversion:
https://discordapp.com/channels/440868230475677696/568161140534935572/721555623191248906

Specifically, the issue is that both rgblight and rgb matrix use an array named `led` to hold the LED array before sending it to the hardware. This creates a conflict.  Renaming the led array in rgb matrix allows for coexistence. 

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization

## Checklist

- [x] My code follows the code style of this project.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by skullydazed** [comment]
We already have an led matrix feature, and I fear this could create confusion. Is there a different name that could be used here?

**Comment by drashna** [comment]
> We already have an led matrix feature, and I fear this could create confusion. Is there a different name that could be used here?

Good catch. 

I've updated the name to be ... well, super specific, so that there shouldn't be any issues with name collisions.

**Comment by sigprof** [comment]
The `ws2812_led_array` name does not look “super specific” — it could equally well apply to the usage in the rgblight code (although that part of rgblight code is not really specific to ws2812). Maybe something like `rgbmatrix_ws2812_led` would be better?

**Comment by drashna** [comment]
`ws2812_rgb_matrix_array` sounds better to me.

**Pull request merged**
