### PR TITLE
Signum 3 0 enable kinetic speed

### PR DESCRIPTION
**Pull request by jceb**
## Description

Enable kinetic speed and update keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Could you separate this PR into two separate ones?  One to add the Kinetic speed curve for MouseKeys, and one for enabling it in the Signum 3.0? 

Specifically: 
https://docs.qmk.fm/#/contributing?id=quantumtmk-core
> * Do not lump keyboards or keymaps in with core changes. Submit your core changes first.

**Comment by fauxpark** [comment]
Seems to have already been done in https://github.com/qmk/qmk_firmware/pull/6739

**Comment by jceb** [comment]
I removed the two commits that are part of #6739

**Comment by jceb** [comment]
Any updates on this pull request?

**Pull request merged**
