### PR TITLE
[Keymap] keychron/q1/ansi_encoder Keychron Q1 Special Edition (atmega32u4) with knob keymap 

### PR DESCRIPTION
**Pull request by mkillewald**
## Description

- Retains Keychron factory keycodes for Mission Control, Launchpad, Siri, Cortana, Task View, File Explorer, and others.
- Different RGB settings for Mac base and Win base layers. You can set different RGB animations, colors, brightness and speed for the Mac and Win base layers using the standard RGB keyboard shortcuts.
- Autocorrect is enabled.
    - Uses getreuer's autocorrect dictionary.
    [https://github.com/getreuer/qmk-keymap/blob/main/features/autocorrection_dict.txt](https://github.com/getreuer/qmk-keymap/blob/main/features/autocorrection_dict.txt)
- Caps Word enabled with RGB indicator. 
- Caps Lock RGB indicator. Will light Caps Lock key with options to also light Tab key (useful for some keycap sets), and/or light all alpha keys.
- Dynamic Fn layer RGB indicator. When Fn key is held down, any keys defined on the Fn layer in this firmware or in VIA will be highlighted.   

## This keymap makes the following layout changes over the factory firmware

- Fn+Left Shift toggles Autocorrect on/off
- Fn+Backspace enters DFU mode (but does not reset eeprom)
- Fn+Z (KC_LTTOG) Caps Lock Light Tab Toggle (default: off)
    - toggle lighting the Tab key when Caps Lock is enabled. This is useful with non backlit keycaps/legends.
- Fn+X (KC_LATOG) Caps Lock Light Alpha Toggle (default: on)
    - toggle lighting all the alpha keys when Caps Lock is enabled.
- Fn+C (KC_TKTOG) Fn layer Trasnparent Key Off Toggle (default: RGB on)
    - toggle turning off RGB for keys with no definition
- Fn+V (KC_FCTOG) Fn layer Color Toggle (default: static color on)
    - toggle lighting the defined Fn layer keys with the static color set with FN1_LAYER_COLOR 

- Mac mode only
    - Fn+Esc (KC_LBMAC) will lock and sleep display
    - Fn+< sets my secondary display to 0° rotation
    - Fn+> sets my secondary display to 90° rotation

    Note: display rotation requires additional software and changes made, see this link for more information:
    [https://www.reddit.com/r/Keychron/comments/1254g36/howto_macos_rotate_screen_from_keyboard_shortcut/](https://www.reddit.com/r/Keychron/comments/1254g36/howto_macos_rotate_screen_from_keyboard_shortcut/)

All custom keycodes can be moved to different keys in VIA by using the following:
- CUSTOM(64) = KC_LTTOG (default: Fn+Z) Caps Lock Light Tab Toggle
- CUSTOM(65) = KC_LATOG (default: Fn+X) Caps Lock Light Alpha Toggle
- CUSTOM(66) = KC_TKTOG (default: Fn+C) Fn layer Trasnparent Key Off Toggle
- CUSTOM(67) = KC_FCTOG (default: Fn+V) Fn layer Color Toggle
- CUSTOM(68) = KC_LBMAC (default Mac Only: Fn+Esc) Lock and Blank Mac

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — COMMENTED** [review]
There is a lot of redundancy with your Q2 PR.  You may want to move some of the code into a userspace, as that is shared betweeen keyboards, if using the same keymap folder name.

**Comment by mkillewald** [comment]
Very true, and that is something I have had on my backburner to do. I guess I should take the time to look into what it takes to get a userspace folder set up.

**Comment by mkillewald** [comment]
Added userspace folder on PR #20437 and reduced redundant code in this PR to utilize that userspace folder. Will now be hands off on both PR's until they are either approved or denied for merge.

**Comment by mkillewald** [comment]
Will now be hands off until this is either approved or denied for merge.

**Comment by mkillewald** [comment]
Please do not merge this PR. I have merged branch mkillewald_q1se into branch mkillewald_q2_custom and then deleted mkillewald_q1se. Sorry for any confusion.

**Pull request closed without merging**
