### PR TITLE
shell.nix improvements, and fix problems on Darwin

### PR DESCRIPTION
**Pull request by purcell**
Improvements to shell.nix were made in #8910 by @thorstenweber83, but the result was that the nix shell no longer worked on Darwin.

I have tidied up and improved some of the Nix expression, fixing this issue along the way. If someone would be kind enough to test this on Linux too, that would be appreciated, though I don't expect issues.

## Description

- Removed unnecessary overrides
- Provided a more complete Python environment, adequate for actually running/developing `bin/qmk`
- Unset NIX_TARGET_CFLAGS_COMPILE in the Nix shell, to avoid incompatible host CC flags getting picked up by avr-gcc.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by thorstenweber83** [comment]
LGTM.

`make all:default` successfully built 997 of 1084 keyboards on my NixOS machine.

**Comment by purcell** [comment]
> I think i'm a bit confused about how many keyboards there are and how many i should be able to build.

I guess the key question is whether you get more or fewer failures/successes with or without this PR. I can imagine blanking out `NIX_TARGET_CFLAGS_COMPILE` might have negative effects in some cases, but it was actively necessary for me to do that with `avr-gcc`.

**Comment by thorstenweber83** [comment]
> 
> I guess the key question is whether you get more or fewer failures/successes with or without this PR.

I had failures before, too and it was about the same number.  So it does not look like your PR makes things worse on linux.

**Comment by purcell** [comment]
>  So it does not look like your PR makes things worse on linux.

Cool, thanks for confirming - this should be unproblematic to merge, then.

**Comment by purcell** [comment]
Thanks @Erovia and @fauxpark

**Pull request merged**
