### PR TITLE
Sync suspend_power_down updates to slave half #14851

### PR DESCRIPTION
**Pull request by moroz-slavomir**
## Description

Data transfer for split keyboards occurs after [matrix_scan()](https://github.com/qmk/qmk_firmware/blob/ce8c1ba418f2d102a15112bcdae06c2a2a7e91a9/quantum/matrix.c#L312-L340).

When keyboards on lufa platform are suspended they no longer perform matrix_scan() and[ wait for the remote device to awake](https://github.com/qmk/qmk_firmware/blob/ce8c1ba418f2d102a15112bcdae06c2a2a7e91a9/tmk_core/protocol/lufa/lufa.c#L1102-L1109). 
- Only exception to this is when the remote device is in sleep mode (supports remote awake). Then the matrix_scan() is invoked to detect whether the device should be awoken.
- Wait for the usb device can be disabled by defining NO_USB_STARTUP_CHECK, but this will disable the suspend feature and all connected features e.g. turning off rgb lights on suspend. 

That means, if I turn off my computer, the matrix_scan() isn't invoked and slave half won't receive updates written in suspend_power_down(). E.g. based on the config, the keyboard might turn off rgb lights. This however won't be transferred to slave, so the slave half will keep the rgb ON when the pc shutdowns, while the master will turn them off. 

If I put my computer to sleep, the keyboard still scans the matrix, so both halves will turn off the rgb. 

The fix will execute data transfer from master the slave after [suspend_power_down_quantum()](https://github.com/qmk/qmk_firmware/blob/f79e1ab7481525cfa2b63e6bc062fb7d8250c8db/quantum/quantum.c#L490-L542), that handles suspend for rgb and other features. 

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #14851

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
    - Tested on ATmega32u4 split keyboard

### CODE REVIEW

**Comment by drashna** [comment]
This doesn't really sync the state, at all.  It mostly just clears the matrix and forces a transaction.

**Comment by moroz-slavomir** [comment]
Hi. I'm not sure whether we mean the same thing by 'sync the state'. 

I thought that the transaction is [supposed to copy  various data](https://github.com/qmk/qmk_firmware/blob/0e18f03b79d9bf5274323d7049c25e16d9250a06/quantum/split_common/transactions.c#L617-L633) to the split shared memory and send it to the slave. Thus forcing a transactions was my goal. 

Since transaction needs the matrix, I could have performed a matrix_scan() and that would force the transaction as well, but figured that since we are already in suspend and we clear the keyboard in [suspend_wakeup_init()](https://github.com/qmk/qmk_firmware/blob/0e18f03b79d9bf5274323d7049c25e16d9250a06/platforms/avr/suspend.c#L136), there is no point in preserving matrix data.

**Comment by drashna** [comment]
the suspend power down stuff is putting the controller into a low power state.  That's definitely not happening here.

In fact, it looks like it's zeroing out the matrix. And as an attempt to better detect changes.

**Comment by drashna** [comment]
Also, in theory, this should not be applied to just AVR, but to any/every platform

**Comment by moroz-slavomir** [comment]
> the suspend power down stuff is putting the controller into a low power state. That's definitely not happening here. 
> 
> In fact, it looks like it's zeroing out the matrix. And as an attempt to better detect changes.

 Correct me if I'm wrong but the function is supposed to run before the suspend. It forces the transaction before it powers down. And that cycle runs in a loop since the power down uses interrupts. 
image

As for zeroing the matrix.  As was linked in my previous message, additional data for like rgb config or oled state is copied to slave during the transaction, and every transactions requires matrix data. So it was either empty matrix or full matrix scan and as mentioned the keyboard will undergo a power down afterwards. Would the matrix scan be a better option than forcing a transaction without a matrix?

**Comment by moroz-slavomir** [comment]
> Also, in theory, this should not be applied to just AVR, but to any/every platform

Yes I have thought about this, but wasn't sure enough. The problem with avr and lufa.c specifically is that it won't invoke matrix scan. When compared to code in vusb protocol for instance: 

- [Lufa](https://github.com/qmk/qmk_firmware/blob/0e18f03b79d9bf5274323d7049c25e16d9250a06/tmk_core/protocol/lufa/lufa.c#L1107-L1109) checks whether device supports remote awake and only then executes wakeup condition (matrix scan). Otherwise there is no matrix scan -> no data transfer. 
- [Vusb](https://github.com/qmk/qmk_firmware/blob/0e18f03b79d9bf5274323d7049c25e16d9250a06/tmk_core/protocol/vusb/protocol.c#L142-L145) on the other hand always runs the condition and thus the issue would not occur. 

 So whether the issue appears is connected to the protocol / platform and I was only aware that is was occurring on avr/lufa. But yes, you are right, maybe should be moved outside of AVR specific code.

**Comment by TD22057** [comment]
I tried this branch on my KBO-5000 (ATmega32u4) and it caused problems.  I have both backlight and underglow.  The underglow appears to work ok during power off (turns off and on) but the backlight on the split side that is not directly connected to the computer stays on.  Using this branch, it still stays on and the keyboard wouldn't wake up when power was restored.  I had to unplug and replug it in to get it to wake up.

**Pull request closed without merging**
