### PR TITLE
Add keyboard level encoder function

### PR DESCRIPTION
**Pull request by waffle87**
## Description
Added a keyboard level encoder function as many users have complained about losing encoder functionality when using QMK Configurator. Also removed user functions that performed the same thing. 

## Types of Changes

- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by drashna — CHANGES_REQUESTED** [review]
This either needs to: 
1. Target Develop
2. Get explicit approval from all of the users whose keymaps are touched
3. Revert the keymap changes and just add the kb level callback.

**Review by drashna — CHANGES_REQUESTED** [review]
This either needs to: 
1. Target Develop
2. Get explicit approval from all of the users whose keymaps are touched
3. Revert the keymap changes and just add the kb level callback.

**Comment by waffle87** [comment]
git is not my forte today

**Comment by waffle87** [comment]
git is not my forte today

**Pull request closed without merging**
