### PR TITLE
Bring dactyl/matrix.c in line with quantum/matrix.c

### PR DESCRIPTION
**Pull request by ErinCall**
This is the first big step toward #2065. It updates `keyboards/handwired/dactyl/matrix.c` to look like `quantum/matrix.c`:

* use the updated debounce algorithm
* Rows are called "rows" and columns are called "columns"
* Support for `MATRIX_MASKED`
* Support for `DIODE_DIRECTION`
* The big one: support for `COL_PINS`/`ROW_PINS` arrays. It's currently broken into `ONBOARD_ROW_PINS`/`ONBOARD_COL_PINS` and `EXPANDER_ROW_PINS`/`EXPANDER_COL_PINS`. I don't love that design, but it works and I haven't figured out a better one.

The next step will be to port these changes back into `quantum/matrix.c`. 

cc @drashna

### CODE REVIEW

**Comment by drashna** [comment]
Nice! 

Also, if the matrix is the same as the Ergodox, you should check out the recently added "pretty" layouts for the Ergodox.

**Comment by drashna** [comment]
Was this ready to be merged?

**Comment by ErinCall** [comment]
Yeah, I think it's good to go.

**Comment by jackhumbert** [comment]
Awesome - thanks!

**Pull request merged**
