### PR TITLE
Document the correct path to the split keyboard EEPROM files

### PR DESCRIPTION
**Pull request by zvecr**
## Description

This fixes incorrect paths to the split keyboard EEPROM files within the repo.

Other items for potential review:

- Should all references to eeprom files be updated to the full path `./quantum/split_common/eeprom-lefthand.eep` and `./quantum/split_common/eeprom-righthand.eep`?
- ~~Should this PR update the location within `./keyboards/lets_split/keymaps/bbaserdem/README.md`?~~ Not required
- ~~Should this PR remove the other eeprom files within `minidox` and `deltasplit75` so that the only eeprom files are within the common folder?~~ Not required

## Types of changes

- [ ] Core
- [ ] Bugfix
- [ ] New Feature
- [ ] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [x] Documentation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
Travis CI error is unrelated.

**Comment by drashna** [comment]
Travis CI error is explicitly due to an issue with the avr-gcc compiler that it uses.  I'm using the same version on both MSYS and ubuntu and it compiles under size....

>Should all references to eeprom files be updated to the full path `./quantum/split_common/eeprom-lefthand.eep` and `./quantum/split_common/eeprom-righthand.eep`?

Yes, I think it should, honestly. 

>Should this PR update the location within ./keyboards/lets_split/keymaps/bbaserdem/README.md?

For keymap readme's, no. Just the main readme for the keyboard (and maybe the default keymap's readme".

>Should this PR remove the other eeprom files within minidox and deltasplit75 so that the only eeprom files are within the common folder?

I'd say only if these keyboards have been converted and tested with the split common code.  For now, it should be fine.

**Comment by zvecr** [comment]
@drashna Thanks, i will make those updates shortly.

@bbaserdem Now that the Lets Split uses the split keyboard common code, there are stale reference to the eeprom files within `./keyboards/lets_split/keymaps/bbaserdem/README.md`

**Comment by drashna** [comment]
Awesome, thanks!

**Pull request merged**
