### PR TITLE
Add support for LAZYDESIGNERS/THE60R2

### PR DESCRIPTION
**Pull request by jackytrabbit**
THE60R2

Add support for LAZYDESIGNERS/THE60R2

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by jackytrabbit** [comment]
THE60R2 uses a new design, which is different from Round 1. It has difficulty to put it under the round 1 folder. So I opened a new folder for it. Thank you!

**Comment by drashna** [comment]
Ideally, this is where you'd use a revision subfolder.  Eg, /rev1 and /rev2 (or round1 and round2).  

This way, if the hardware config is different, but the keymaps are the same, they can be shared, easily.  

You can look at the planck as an example of how to do this.

**Comment by jackytrabbit** [comment]
> Ideally, this is where you'd use a revision subfolder. Eg, /rev1 and /rev2 (or round1 and round2).
> 
> This way, if the hardware config is different, but the keymaps are the same, they can be shared, easily.
> 
> You can look at the planck as an example of how to do this.

Thank you! I actually tried that and tested in the local. But they have totally different settings and keymaps so the compile failed.
The R1 version based on one special layout which won't be used again. So the two PCBs use two different configurations and different layouts. Actually this is a single case that the adjustment is not based on the earlier design. I will use the earlier design as much as I can.

**Comment by drashna** [comment]
If that's the case, then don't share the keymap folder.  And that should solve the issue.

**Pull request closed without merging**
