### PR TITLE
[MechBrewery] Update json file to support QMK Configurator correctly

### PR DESCRIPTION
**Pull request by AnthonyNguyen168**
## Description

- Update json file to support Configurator correctly.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

**None**

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
I'm not sure what the point is here.  Adding the labels here doesn't add defaults to the configurator.  That needs to be done in the qmk configurator repo.

**Comment by AnthonyNguyen168** [comment]
Hi @drashna ,
Quoted from [https://docs.qmk.fm/#/reference_configurator_support?id=building-the-json-file](url)

> The label keys are not used; they are only for the user’s reference in identifying specific keys when debugging the info.json file.

The most important change in this pull request is the coordinates for **LAYOUT_65_iso_blocker_split_bs** and **LAYOUT_65_ansi_blocker_tsangan** are changed. Therefore the layout on config.qmk.fm can display correctly.

If you want, I can remove the labels to make it more clear to read the changed coordinates.

**Comment by AnthonyNguyen168** [comment]
Hi @drashna ,
I removed the unnecessary labels.
Now the change is clear to see.
Please check again.

**Comment by AnthonyNguyen168** [comment]
Hi @drashna,
Please check this request again.
Thank you so much.

**Comment by AnthonyNguyen168** [comment]
47925E47-6694-4750-8697-D9DAB3D2252D

**Comment by AnthonyNguyen168** [comment]
Current issue on config.qmk.fm:
Missing Keycode on config.qmk.fm

**Review by drashna — APPROVED** [review]

**Review by zvecr — CHANGES_REQUESTED** [review]
Order of ISO Enter does not match that declared in `mb65s.h`

**Comment by AnthonyNguyen168** [comment]
Dear @zvecr,
I reorder the ISO Enter to match that declared in `mb65s.h`
Please check again.
Thanks.

**Comment by AnthonyNguyen168** [comment]
Hi @noroadsleft,
Can you check this pull request?
I do not want the this json file format to be wrong again.
Thanks.

**Review by drashna — APPROVED** [review]

**Comment by EddieT2011** [comment]
Hi @zvecr pls help us to review and approve these changes. We have followed your suggestions to fix them clearly. Many thanks

**Review by noroadsleft — APPROVED** [review]
All the implementations are correct, though I'm not keen on a couple of the layout macro names, but those can be fixed in another PR.

----

`LAYOUT_65_ansi_blocker_split_bs`:
image

`LAYOUT_65_ansi_blocker_tsangan` (**this should actually be named `LAYOUT_65_ansi_blocker_tsangan_split_bs`**):
image

`LAYOUT_all`:
image

`LAYOUT_65_iso_blocker_split_bs`:
image

`LAYOUT_65_iso_blocker_7u_spc` (**this should actually be named `LAYOUT_65_iso_blocker_tsangan_split_bs`**):
image

**Comment by AnthonyNguyen168** [comment]
Thank you James @noroadsleft, Drashna @drashna and Joel @zver.

**Pull request merged**
