### PR TITLE
tmk_core/protocol/usb_descriptor.h: make RAW usb endpoint size configurable

### PR DESCRIPTION
**Pull request by purdeaandrei**
## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by purdeaandrei** [comment]
One note is that I tested my change for lufa. But "vusb.c" also has a definition of RAW_EPSIZE (who's default value differs from protocol/usb_descriptor.h).

So I'm wondering is it the case that usb_descriptor.h will never be used by vusb, only by lufa/others, so I should probably apply the same ifndef in vusb.c?

**Comment by drashna** [comment]
> So I'm wondering is it the case that usb_descriptor.h will never be used by vusb, only by lufa/others, so I should probably apply the same ifndef in vusb.c?

I believe that the plan was to update v-usb to use it. But incrementally update vusb to get to that point. 

You'd have to talk to @fauxpark and/or @zvecr about that, though. 

But for now, yes, the same ifdef's should be applied to the vusb files.

**Comment by zvecr** [comment]
At the moment, the issue is that RAW_EPSIZE != buffer size for all platforms. vusb **has** to send in chunks of 8., however it still expects 32 in total to be sent.

**Comment by fauxpark** [comment]
So the endpoint size is not the thing we want to be changing here. The maximum differs depending on the USB speed: https://www.beyondlogic.org/usbnutshell/usb4.shtml#Interrupt

For USB 1.1 Low-Speed (ie. V-USB), the maximum endpoint size for interrupt transfers is 8 bytes, hence the stuff zvecr mentions above.
The chips supported by LUFA and ChibiOS (and the ATSAMD51J18A used by the Massdrop boards) are all USB 2.0 compliant, but full speed only, which has a maximum of 64 bytes.

What you're probably after is a configurable report count in the HID report descriptor, but this might mean we need to implement a ring buffer for LUFA/ChibiOS/ATSAM like it is for V-USB.

As for usb_descriptor.[ch], yes, my plan is to use and add to the structs I added to the V-USB code, so we can have a common place for the descriptors and do not have to rely on the stuff LUFA provides (this has the added bonus of not needing to pull the LUFA submodule to build a ChibiOS board, too).

**Pull request closed without merging**
