### PR TITLE
Rename UC_OSX (and related constants) to UC_MAC

### PR DESCRIPTION
**Pull request by vomindoraan**
**As per @skullydazed's [comment](https://github.com/qmk/qmk_firmware/pull/6326#issuecomment-511887937) in #6326, I've rebased the changes onto `master` so they can be merged immediately.**

<hr>

## Description

Apple moved away from calling their operating system OS X in 2016; macOS is now the preferred name. We've been following this naming convention in docs and code for the most part, and I think now is a good time to rename the Unicode constants as well.

This PR renames the following constants:

|Old name          |New name          |Type                |
|------------------|------------------|--------------------|
|`UC_OSX`          |`UC_MAC`          |Input mode name     |
|`UNICODE_MODE_OSX`|`UNICODE_MODE_MAC`|Keycode name        |
|`UC_M_OS`         |`UC_M_MA`         |Keycode alias       |
|`UNICODE_KEY_OSX` |`UNICODE_KEY_MAC` |Overridable constant|
|`UNICODE_SONG_OSX`|`UNICODE_SONG_MAC`|Overridable constant|

References to these constants, except for `UC_OSX`, have been updated to the new values since there weren't that many of them. 3 keymaps, @zunger-humu's (already confirmed okay), @buhearns's and @jotix's are affected.

As for `UC_OSX`, I added it as an alias of `UC_MAC` for backwards compatibility, since 18 keymap/userspace files reference `UC_OSX`. This alias will be removed in a future breaking change (see #6326 for details).

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by vomindoraan** [comment]
All references to the other constants (5 of them in total) have been updated to the new values, so it should be fine. But if it's still not okay, e.g. because of keymaps that exist outside of the repo, there are two ways of going about it:

1. Add aliases for the other constants and merge this into `master`;
2. Treat this as a breaking change in its entirety, remove `UC_OSX` completely and update all references to `UC_MAC`, and merge this into `future` (i.e. #6326).

I'm fine with either, but I'd prefer option 2 since only 18 or so keymaps (half of them default) use `UC_OSX`. I don't think changing them would be a big deal since we've already had several breaking change PRs that affect many more keymaps than that.

**Comment by zvecr** [comment]
I thought I should flag it as there has been a mixed approach to these kinds of changes in the past. As you mention with the 2 solutions, it would be good to see this go one way or the other and not offer partial backwards compatibility. Personally I would be happy with either direction, but favour 2 for the same reasons.

**Comment by skullydazed** [comment]
I apologize, some unexpected delays while traveling have kept me from reviewing `future` related PR's until today. 

I think I'd prefer #1 for now. Having those aliases in the codebase is minor compared to users needing to figure out how to unbreak their keymap.

**Comment by vomindoraan** [comment]
I've added the missing keycode alias and marked it deprecated with a comment.

**Comment by drashna** [comment]
There are a number of merge conflicts here, now,  Sorry.

**Pull request closed without merging**
