### PR TITLE
Pearl Backlight

### PR DESCRIPTION
**Pull request by baldonp1**
Beginning implementation of Pearl backlight. Levels and brightness not working yet.

### CODE REVIEW

**Comment by jetpacktuxedo** [comment]
Looking forward to this!

**Comment by jackhumbert** [comment]
Nice - thanks!

**Comment by jetpacktuxedo** [comment]
This should also work for other PS2AVR boards. At some point once we get all the kinks worked out we should port this to all of those other boards as well.

**Comment by baldonp1** [comment]
Sweet, thanks guys!

**Pull request merged**
