### PR TITLE
[Keyboard] Move all helix boards onto split common

### PR DESCRIPTION
**Pull request by drashna**
## Description

Core is starting to diverge from custom split implementation.  Enough that the pico and rev2 are now erroring out on develop. 

Instead of backporting changes, just convert these boards off of custom split implementation and onto split common. 

## Types of Changes

- [x] Bugfix
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
@MakotoKurauchi Also, if you could test the changes and make sure that nothing is broken?

**Review by fauxpark — APPROVED** [review]

**Comment by mtei** [comment]
The following keymap is ready to be migrated to split_common.
* helix/rev2/default/
* helix/rev2/five_rows/
* helix/rev2/led_test/
* helix/rev2/xulkal/

The keymap below is probably ready to be migrated to split_common. It needs to be tested.
* helix/rev2/edvorakjp/

The following keymaps depend on `local_drivers/ssd1306.c`. The OLED-related code in these keymaps needs to be modified to use `oled_dirver.c`.

* helix/rev2/five_rows_jis/
* helix/rev2/fraanrosi/
* helix/rev2/yshrsmz/

The following keymap is not clear to me; I will discuss it with MakotoKurauchi.
* helix/rev2/froggy/
* helix/rev2/froggy_106/

**Comment by drashna** [comment]
honestly, given the complexity that the helix boards use, that the default keymap compiles ...

**Comment by mtei** [comment]
I've started work on the Helix switch to split_common, and have started a discussion with MakotoKurauchi.

Please let us create a replacement PR for this one.

**Comment by drashna** [comment]
> I've started work on the Helix switch to split_common, and have started a discussion with MakotoKurauchi.
> 
> Please let us create a replacement PR for this one.

Absolutely!  I would rather it be that way, to be honest, as I'm nowhere near as familiar with the helix code as you or makotoKurauchi are.

**Pull request closed without merging**
