### PR TITLE
[Keyboard] Fix compilation issues for creatkeebs thera

### PR DESCRIPTION
**Pull request by drashna**
## Description

Issues with layout macro. 

## Types of Changes

- [x] Bugfix
- [x] Keyboard (addition or update)

## Issues Fixed or Closed by This PR

* Tzarc CI

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
@Timliuzhaolu could you verify that the changes to the layout macro are correct?

**Review by fauxpark — APPROVED** [review]

**Comment by Timliuzhaolu** [comment]
> @Timliuzhaolu could you verify that the changes to the layout macro are correct?

Yes I believe so, is it causing any problems?

**Review by zvecr — APPROVED** [review]

**Comment by zvecr** [comment]
> is it causing any problems

Yeah, the keyboard doesnt compile so is kinda unusable for end users (and we like to have all default keymaps building in the repo).

**Comment by Timliuzhaolu** [comment]
> > is it causing any problems
> 
> Yeah, the keyboard doesnt compile so is kinda unusable for end users (and we like to have all default keymaps building in the repo).

Sorry about that! Can it be compiled now after your latest commit? Just want to make sure that I won't repeat that same mistake. Thanks!

**Comment by drashna** [comment]
> Sorry about that! Can it be compiled now after your latest commit? Just want to make sure that I won't repeat that same mistake. Thanks!

Yup.  I don't submit a fix unless it actually compiles.  

The biggest issue is that I did move a couple of the columns around on the 4th row, basically.  Eg, zxcvb, etc.  I'm not 100% sure it's correct, but looking at how things were set up, I made some educated guesses.

**Pull request merged**
