### PR TITLE
Add description in Bluetooth docs for requiring NKRO to be disabled

### PR DESCRIPTION
**Pull request by pwlandoll**
Expand documentation in Bluetooth rules.mk options for requiring 

## Description

As seen in #10314, the Bluetooth documentation is missing some information about support for NKRO, and how enabling it can be problematic.
This change expands slightly on the Bluetooth feature documentation, and while not nearly comprehensive or sufficient for covering managing Bluetooth in qmk, could likely save some time and troubleshooting.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

None

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by fauxpark — COMMENTED** [review]
[Line 674 in lufa.c](https://github.com/qmk/qmk_firmware/blob/master/tmk_core/protocol/lufa/lufa.c#L674) should perhaps also be changed to:
```c
if ((where == OUTPUT_BLUETOOTH || where == OUTPUT_USB_AND_BT) && !keymap_config.nkro) {
```
just to be sure.

**Comment by drashna** [comment]
Honestly, I think that maybe we should add a message if both bluetooth and NKRO are enabled, so it's obvious at build time.  Not a hard error, but something so users can see it.

**Comment by pwlandoll** [comment]
A warning like that probably would have saved me more time than if it were only in the documentation, I like that. I can try to tackle that, but I don't feel confident in being able to make the change correctly and test it. 

in lufa.c:
```c
    if ((where == OUTPUT_BLUETOOTH || where == OUTPUT_USB_AND_BT) && keymap_config.nkro) {
        print("Both Bluetooth output and NKRO are enabled. This will cause errors in Bluetooth output.\n");
    }
    if ((where == OUTPUT_BLUETOOTH || where == OUTPUT_USB_AND_BT) && !keymap_config.nkro) {
#    ifdef MODULE_ADAFRUIT_BLE
```

Or is there somewhere earlier on in the build process where the rules are checked and the warning could be surfaced there?

**Comment by fauxpark** [comment]
That `print()` will not work unless the Console feature is enabled, and you are looking at the output in QMK Toolbox or hid_listen.
Something like the following in tmk_core/common.mk should do the trick:
```makefile
ifeq ($(strip $(NKRO_ENABLE)), yes)
    ifeq ($(PROTOCOL),VUSB)
        $(info NKRO is not currently supported on V-USB, and has been disabled.)
    else ifeq ($(strip $(BLUETOOTH_ENABLE), yes))
        $(info NKRO is not currently supported with Bluetooth, and has been disabled.)
    else ifneq ($(BLUETOOTH),)
        $(info NKRO is not currently supported with Bluetooth, and has been disabled.)
    else
        TMK_COMMON_DEFS += -DNKRO_ENABLE
        SHARED_EP_ENABLE = yes
    endif
endif
```

**Comment by pwlandoll** [comment]
Updating checklist with changes from [af17d3d](https://github.com/qmk/qmk_firmware/pull/10359/commits/af17d3dc99ced5cb5892480bbfd96766ec2f5c0e)

## Types of Changes

* [ ]  Core
* [ ]  Bugfix
* [ ]  New feature
* [x]  Enhancement/optimization
* [ ]  Keyboard (addition or update)
* [ ]  Keymap/layout/userspace (addition or update)
* [x]  Documentation

## Issues Fixed or Closed by This PR

None
## Checklist

* [x]  My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
* [x]  I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
* [x]  My change requires a change to the documentation.
* [x]  I have updated the documentation accordingly.
* [x]  I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
* [ ]  I have added tests to cover my changes.
* [x]  I have tested the changes and verified that they work and don't break anything (as well as I can manage).

**Comment by pwlandoll** [comment]
Also, thanks for the help @fauxpark and @drashna :)

**Review by fauxpark — APPROVED** [review]

**Comment by fauxpark** [comment]
Just looking around for appearances of `keymap_config.nkro`, it seems like it is actually possible for this to be set to 1 even if NKRO is not compiled in - neither process_magic.c nor bootmagic.c have `#ifdef NKRO_ENABLE` guards around their NKRO-related code.

**Comment by fauxpark** [comment]
On further inspection my above comment is incorrect, as when `NKRO_ENABLE = no` none of the code which checks `keymap_config.nkro` will be compiled in anyway. Maybe it's worth adding ifdefs around the bootmagic/magic NKRO stuff too to save a couple tens of bytes, but for now I'm happy with this. Thanks a lot!

**Comment by pwlandoll** [comment]
Excellent, thanks @fauxpark!

**Comment by maberalc** [comment]
I think NKRO should not be disabled on Build. I mean, I’m using my keyboard wired and on Bluetooth. When I connect it to Bluetooth I boot with bootmagic to disable nkro, and then when I go wired I enable it.

**Comment by pwlandoll** [comment]
@fauxpark , do you think there would be a way to have NKRO enabled for wired mode while disabling it in Bluetooth mode?

**Pull request merged**
