### PR TITLE
The Uni change folder location

### PR DESCRIPTION
**Pull request by petercpark**
## Description

Added a keymap to a keyboard. Then moved the entire keyboard folder into a new "stenokeyboards" folder for organizing future projects by StenoKeyboards.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — COMMENTED** [review]
Keyboard moves must go through develop. You might want to submit the keymap addition as a separate PR.

**Comment by petercpark** [comment]
> Keyboard moves must go through develop. You might want to submit the keymap addition as a separate PR.

Okay. Can I make a new commit just deleting the keymap changes? I'll save those for separate PR.

**Comment by fauxpark** [comment]
There is a merge conflict that needs resolving.

**Comment by petercpark** [comment]
> There is a merge conflict that needs resolving.

Can you help me out with this? All I did was change the location of this file, I don't know what the conflict is.

**Comment by drashna** [comment]
Assuming that you have the qmk repo set as the upstream remote:
```sh
git fetch upstream
git merge upstream/develop
```

Likely, you'll run into merge conflicts when you do this.  When you do, it should tell you how to resolve them, basically.  But `git status` to see which files have conflicts (should be in red).

**Comment by petercpark** [comment]
I believe the conflict is now gone

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
