### PR TITLE
GON NerD codebase refactor

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

The current `gonnerd` codebase supports both the NerD 60 and the NerD TKL PCBs. This PR refactors the codebase into two, one for each PCB, inside a `gon` vendor directory.

### User keymaps affected:

Old Keymap | New Keymap | Owner
:--------- | :--------- | :----
`gonnerd:mauin` | `gon/nerd60:mauin` | @Mauin
`gonnerd:gam3cat` | `gon/nerdtkl:gam3cat` | @Gam3cat

Special care was taken to make sure neither of the user keymaps experienced behaviour changes as best as I could. Each major change was tested by recompiling each keymap and checking the SHA-1 hash of the compiled .hex files, with the following exceptions/caveats:

- The `gon/nerdtkl:gam3cat` keymap (previously `gonnerd:gam3cat`) was *not* checked through this testing, because the `keymap.c` includes `version.h`, which means the hash changes every time you compile it.
- The `gon/nerdtkl:default` keymap (previously `gonnerd:tkl`) was checked with `CONSOLE_ENABLE` set to `no`, for the same reason as above.

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
IMO these should be `gon/nerd/60` and `gon/nerd/tkl`. The Wasdat does something similar as the matrix is the same for both fullsize and TKL. Perhaps they should also be changed to `maartenwut/wasdat/fullsize` and `/tkl`?

**Comment by noroadsleft** [comment]
> IMO these should be `gon/nerd/60` and `gon/nerd/tkl`. The Wasdat does something similar as the matrix is the same for both fullsize and TKL. Perhaps they should also be changed to `maartenwut/wasdat/fullsize` and `/tkl`?

To me, the Wasdat argument isn't really relevant, because it's a converter that works with multiple keyboards. The NerD 60 and NerD TKL are two completely different PCBs (though yes, the 60 uses a subset of the TKL matrix).

I also don't see the point of introducing a `/nerd/` directory tier here. What would be the supposed purpose of doing that?

**Comment by fauxpark** [comment]
Not really, just the WASD V2, which comes in TKL and fullsize flavours (ANSI and ISO), and also share the same common matrix. So to me it seems like a pretty similar situation, just that the MCU happens to be removable.

The 60% portion of the two NerD PCBs look *very* closely related:
http://www.gonskeyboardworks.com/214-thickbox_default/nerd-60-ver20-pcb.jpg
http://www.gonskeyboardworks.com/185-thickbox_default/nerd-tkl-ver20-pcb.jpg
So I feel they should be grouped together under the `nerd` name, as separate logical "revisions".

**Comment by noroadsleft** [comment]
We're debating semantics at this point, as I would still consider the WASD V2 TKL and V2 Fullsize to be separate boards.

I went with `gon/nerd(60|tkl)` as vendor/keyboard. I don't see 60 vs. TKL here as a revision thing at all.

**Comment by fauxpark** [comment]
I see what you mean, the Wasdat itself is the same board, just able to be plugged into two different sized boards that happen to have the same matrix and name. I realise "revision" is not the best term here, which is why I put it in quotes - this is just what QMK mainly uses subfolders for, but I don't see why they couldn't be used for other distinctions.

Either way, ✔️

**Comment by noroadsleft** [comment]
All keymaps compile in Travis CI; error is because I force-pushed after a rebase.

**Pull request merged**
