### PR TITLE
Move some led drivers to common folder

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Not 100% sold on the current "parent folder that only contains 2 files" paradigm. What I would like to see would be something like...

```
drivers/led/apa102.h
drivers/led/aw20216.h
drivers/led/is31fl3731.h
  ...
drivers/led/is31fl3737.c
```

However it does at least have some value for `issi` right now due to the amount of tiles inc. led/rgb variant drivers.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
> Not 100% sold on the current "parent folder that only contains 2 files" paradigm

I have thought (not very hard) about the logistics and worth of moving to a more traditional `include/` and `src/`-style hierarchy. But that's probably a lot of work that can probably only be done once things like `tmk_core/` are assimilated into `quantum/`.

**Review by fauxpark — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
Ideally, I'd like to see the ISSI drivers in there too, but this is great.

**Comment by zvecr** [comment]
> Ideally, I'd like to see the ISSI drivers in there too, but this is great.

I was planning to, as part of this PR but still not sure on the `issi` parent folder.

**Review by fauxpark — COMMENTED** [review]
May be worth putting the ISSI drivers into `drivers/led/issi/`.

**Comment by zvecr** [comment]
> May be worth putting the ISSI drivers into `drivers/led/issi/`.

Thats been on the cards for the lifetime of this PR, and no one spoke up about it so i went with my personal preference.

**Comment by fauxpark** [comment]
The ISSI drivers warrant their own directory due to the sheer number of them, whereas anything directly under `drivers/led/` can be seen as "miscellaneous", until we collect enough like ones to group them together.

**Comment by zvecr** [comment]
I personally dont see the value, but if it helps get this across the line then i will make the change, Just a little disappointed that it was up for grabs and its only after ive made the change that i now have to do more work.

**Comment by fauxpark** [comment]
I don't really see where you mentioned this.

**Comment by zvecr** [comment]
In the PR description. Doesnt matter anyway, ive moved the files keeping the issi folder.

**Comment by fauxpark** [comment]
Wasn't really clear to me what you were saying there, the issi folder isn't a "parent folder that only contains 2 files" but I understand now.

**Review by drashna — APPROVED** [review]
Personally, I'm fine with throwing everything in `/drivers/led`, since the naming helps sort them out.  But either way is absolutely fine, IMO.

**Pull request merged**
