### PR TITLE
Update rev3 to rev4 for clueboard

### PR DESCRIPTION
**Pull request by austinwilcox**
When running the rev3 version on Arco Linux, I get build errors. On rev4 it works every time

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
I'd be more inclined to try to work out why rev3 isn't working, tbh.

**Comment by daskygit** [comment]
I think with rev3 being AVR and rev4 STM32, it's very likely this bug https://github.com/qmk/qmk_firmware/issues/17064#issuecomment-1126739134.

**Comment by zvecr** [comment]
rev3: AVR
rev4: ARM

Going to be #17064 as its an Arch based distro.

**Comment by zvecr** [comment]
Closing as this doesn't really address the root issue.

**Comment by austinwilcox** [comment]
So as another note, in the following page of the docs we are then referencing rev4.

**Pull request closed without merging**
