### PR TITLE
Parse version better in `qmk doctor` GCC version checks

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

To avoid the case where the `version_number.split('.', 2)` fails due to:

> -dumpversion
> Print the compiler version (for example, 3.0, 6.3.0 or 7)—and don’t do anything else. This is the compiler version used in filesystem paths and specs. **Depending on how the compiler has been configured it can be just a single number (major version), two numbers separated by a dot (major and minor version) or three numbers separated by dots (major, minor and patchlevel version).**
>
> -dumpfullversion
> Print the full compiler version—and don’t do anything else. The output is always three numbers separated by dots, major, minor and patchlevel version.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Tested on MSYS with 5.4.0....

5.4.0 does not support `-dumpfullversion`, only `-dumpversion`.  That's ...a problem. 

Is it possible to call the first, and on error call the older?

**Comment by fauxpark** [comment]
Using packaging.version to parse the version. Seems to be failing somewhere else now...I think I broke some of the tests with #9263.

**Comment by fauxpark** [comment]
I could try my hand at doing this in a regex instead, to avoid the additional dependency just for this one thing.

**Comment by Erovia** [comment]
Wouldn't the semver regex be better?
https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

**Comment by fauxpark** [comment]
Explained on Discord but posting here too for posterity:

> i tried it in regex101, it expects all three parts to be present
whereas the version gcc gives us might be only the major part

**Pull request merged**
