### PR TITLE
Reinstate some previous CI formatting processes

### PR DESCRIPTION
**Pull request by zvecr**
## Description

#11476 incorrectly removed dos2unix as part of the formatting process

Also, given that actions currently have to be approved, the `PR to master/develop` part of the workflow has been reinstated. This way a merged PR that didnt have the formatting workflow approved, will still get flagged (be it at a slightly later point in time). 

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by tzarc** [comment]
Is this waiting on anything at this point?

**Review by fauxpark — APPROVED** [review]
Looks good, pending merge conflict resolution.

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Resolved conflicts, but changed the way it works in the sense that it formats the entirety of the repo.

The "Fail when formatting required" step seems like it shouldn't be there if we want it to progress with making the PR?

**Comment by zvecr** [comment]
> changed the way it works in the sense that it formats the entirety of the repo.

You want to remove the files changed action and the git fetch depth in that case, as it's just cycles. 

> The "Fail when formatting required" step seems like it shouldn't be there

It's captured by the if, as we want that behaviour on pulls, and we don't really want to pr to their pr

**Review by drashna — APPROVED** [review]

**Comment by zvecr** [comment]
Replaced by 15156

**Pull request closed without merging**
