### PR TITLE
Clear weak_mods before AS/TD.

### PR DESCRIPTION
**Pull request by IsaacElenbaas**
## Description

`weak_mods` are cleared on key down to ensure the shift state belongs to the last pressed key (#156). This makes keyrepeat work as expected, at least until you release keys. Auto Shift and TapDance could get the event before this happens and return false, causing incorrect characters to be typed.

## Types of Changes

- [X] Core
- [X] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #4072 
* #6214 

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by IsaacElenbaas** [comment]
Please don't, stale-bot.

**Review by tzarc — APPROVED** [review]
Weak approval.

**Comment by IsaacElenbaas** [comment]
Fixed for AS with the keyrepeat and early register pull on develop as I put a `del_weak_mods` in there for it. Still needed for tapdance and to fix the cause.

**Review by Erovia — APPROVED** [review]
`__attribute__ ((weak))` as well.

Additionally, I think this might need go through the breaking change process.

**Review by drashna — APPROVED** [review]
Looks good!

**Review by fauxpark — APPROVED** [review]
`#pragma weak`

**Pull request merged**
