### PR TITLE
Convert zinc to use split_common

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Left some config in which ideally should be removed, like changing the default tapping term. But the target is to maintain backwards compatibility with existing keymaps.

Tagging @monksoffunk as maintainer.

TODO:
- [ ] Swap to `RGBLED_SPLIT` and confirm led behaviour

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by monksoffunk** [comment]
Thanks for your contributions!
I've already prepared the split_common version.
https://github.com/monksoffunk/qmk_firmware/tree/zinc_splitcommon/keyboards/zinc

Also, I've done the RGB Matrix version based on the current zinc codes, cause the RGB Matrix is not fully compatible with split_common.
https://github.com/monksoffunk/qmk_firmware/tree/zinc_RGB_matrix/keyboards/zinc

So I can't decide which version should I PR...

**Comment by drashna** [comment]
@monksoffunk Split common needs something like #5998 to work properly.

**Comment by zvecr** [comment]
A `RGBLED_SPLIT` version can be deployed right now, where a fully working RGB matrix version that isnt using the crkbd method of building 2 different firmwares will be blocked on the PR Drashna mentions.

Given some recent hardware issues, my preference would be to migrate to split_common where possible.

And as a final side note, your "split_common" version would have to go through the breaking changes process, as it changes user keymaps.

**Comment by monksoffunk** [comment]
@zvecr @drashna
Thanks to you, I opened #7114.

**Pull request closed without merging**
