### PR TITLE
[Keyboard] Corne rev4

### PR DESCRIPTION
**Pull request by drashna**
## Description

Finish up and clean up corne rev4.

Taken primarily from #22676, but includes fix from (and closes) #23840
@foostan 

## Types of Changes

- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by luc-vocab** [comment]
Hi, would it be OK if I helped out on this merge request ? Is it just a matter of fixing the remaining compilation issues on the various crkbd keymaps ?

**Comment by waffle87** [comment]
Looks like there's also a Rev 4.1 that [has some changes](https://github.com/foostan/kbd_firmware/blob/main/keyboards/crkbd/qmk/qmk_firmware/rev4_1/config.h#L3-L5) that wouldn't work with regular Rev 4.0 PCBs and vice versa.
```c
#define SERIAL_USART_TX_PIN GP12
#define USB_VBUS_PIN GP13
#define SPLIT_HAND_PIN GP21
```

**Comment by luc-vocab** [comment]
I just got a crkbd 4.1 pre-assembled. The default firmware from https://github.com/foostan/crkbd/blob/main/docs/firmware/rev4/firmware_en.md `[crkbd_rev4_1_standard_via.uf2](https://github.com/foostan/kbd_firmware/raw/main/keyboards/crkbd/qmk/qmk_firmware/.build/crkbd_rev4_1_standard_via.uf2)`  works fine with both halves, however when I try to build the "via" keymap from this pull request, using command `qmk compile -kb crkbd/rev4 -km via`, only one half works at a time, the other half doesn't display any RGB and doesn't respond to key taps.
are there any diagnostics I could provide to help make debugging this easier ?

**Comment by luc-vocab** [comment]
I was able to build a firmware for a crkbd v4.1 using instructions here: https://github.com/foostan/crkbd/issues/257 but the pull request from drashna didn't work for me, only one half worked. Does this pull request need t obe updated to cover v4.1 ?

**Comment by waffle87** [comment]
> Does this pull request need t obe updated to cover v4.1 ?

Yes, the code in the PR is not compatible with v4.1 PCBs, only v4.0. See my comment above.

**Comment by drashna** [comment]
Updated with the 4.1 revision code.

**Comment by luc-vocab** [comment]
Thank you , is there anything else required to get this PR merged ? Or it's just a matter of waiting for a reviewer ?

**Comment by drashna** [comment]
It's waiting on reviews.

**Review by DaneEvans — APPROVED** [review]

**Review by waffle87 — APPROVED** [review]

**Comment by DaneEvans** [comment]
Tested rev 4.1 on adjacent hardware, my new board used it as a base. 
(Testing everything except key mapping and RGB mapping)
Looks fine, seems to work. 
Should not be held up.

**Comment by waffle87** [comment]
Generally, two collaborator reviews are required for a merge.

**Review by tzarc — APPROVED** [review]

**Pull request merged**
