### PR TITLE
Niu keymap WIP

### PR DESCRIPTION
**Pull request by abhixec**
Things to do : 
- [ ] Add extend layer
- [ ] Add numpad layer
- [ ] Update readme

### CODE REVIEW

**Comment by drashna** [comment]
Is this good to go, right now?

**Comment by abhixec** [comment]
I still have the things to do on the layout once those tasks get marked done. I will be done.

**Comment by drashna** [comment]
Okay, it looks good as is, so I wanted to make sure.

**Comment by abhixec** [comment]
@drashna  go ahead and merge this PR I will put up another PR for the updates.

**Comment by drashna** [comment]
Awesome, sounds good. :)

**Pull request merged**
