### PR TITLE
Disable keymap console feature

### PR DESCRIPTION
**Pull request by filterpaper**
## Description

Firmware is too large with console enabled.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

Reported on Discord: caterina bootloader was overwritten by a user.

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
User keymap changes either have to go via develop, or be signed off by the user ( @DaneEvans ).

**Comment by Dane-2pi** [comment]
Lgtm

**Comment by DaneEvans** [comment]
Still LGTM, except the CI failure. 
Looks like I don't have any rights to do an actual review here though. @zvecr, do I need to resubmit the PR myself, or is an approval in the comments ok?

**Comment by zvecr** [comment]
> is an approval in the comments ok?

Thats all thats required, thanks!

**Review by zvecr — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
