### PR TITLE
Add Zeal60 to QMK to prototype WebUSB and raw_hid

### PR DESCRIPTION
**Pull request by JamesHagerman**
Hi there,

I'm sure this should be left to @Wilba6582 but I figured I'd just open the PR and see what happens!

Here's my motivation:

It would be wonderful to get the zeal60 into the QMK master branch as it's usage of the raw USB HID   features of QMK (specifically, overloading `raw_hid_receive()` defined in `raw_hid.h`) open the door to building keyboard configuration tooling entirely online using WebUSB.

If https://github.com/qmk/qmk_configurator can list the zeal60 in it's drop down, I will try my hand at adding WebUSB tooling to that repo that would be able to send keymap updates directly to the zeal60 entirely from the browser.

While obviously, the Zeal keyboards would be the only ones to currently support this, it should be relatively easy to add this functionality to other keyboards where desired... or perhaps it would be better to add a "Keymaps from EEPROM" feature to QMK itself for all keyboards to use?

In the long run, I would like to port this raw HID functionality to the ergodox_ez pretty soon as well, as that is my other main keyboard. Managing the layout on that thing via a browser would be super elegant!

Anyways, I would love to hear thoughts on this!
James

p.s. As this is my first PR on qmk_firmware, please let me know if I'm entirely out of line.. I don't want to step on any toes!

EDIT: It may be helpful to know that I've done some preliminary WebUSB work but it is not nearly complete enough for qmk at this point. That work can be found here: https://github.com/JamesHagerman/webusb-test

Tomorrow afternoon (it's 2:30am) I will be working on a prototype Zeal+WebUSB test to prove this concept and be putting the work in this repo: https://github.com/JamesHagerman/ZealMod

### CODE REVIEW

**Comment by Wilba6582** [comment]
I have no idea why you think you should be the one doing a PR from my fork, without so much as a message to me about what you're doing and why.

I am in the process of refactoring my Zeal60 code and will do a PR when I am ready.

Part of this refactoring is to decouple Zeal60 specifics so they are modular and can be pulled into keyboard implementations. Right now, there is tight coupling between the EEPROM use, the Raw HID use, and the RGB backlight code. I have planned out how to achieve this, as I also want to reuse this same code in the keyboard implementations of other PCBs I've designed.

While I am happy that other people would like to use features that I've developed, some collaboration with me would be appreciated. Perhaps take parts of it and use it in your own fork and discuss it with me before doing a PR from your own fork.

And before the Tone Police come and drag me away in handcuffs, please note I am being civil and polite in my request to not merge what is essentially 100% my own code without my blessing.

**Comment by jackhumbert** [comment]
@JamesHagerman definitely! We'd love to see the Zeal boards here, and use the features developed for them as well. Since this is Wilba's work, I think it'll be more appropriate for him to get things cleaned-up for merging in, as he mentioned, so I'll go ahead and close this, and let him open a PR when it's ready. There's a lot of cool stuff here, and it needs a lot of attention to make sure that it gets integrated well, which is something I'm sure he will be able to do.

The WebUSB stuff is pretty exciting - I think there was recently some [news that Chrome disabled the feature by default](https://www.xda-developers.com/google-disables-chrome-webusb/), but I think we can remain hopefully that it'll be available by default (in some capacity) at some point in the future :)

If you're trying to do anything specific with these features, there might be a way to do it with what we have in qmk:master now. Feel free to ask on Discord or /r/olkb to see if we can help make it work!

@Wilba6582 we care about the tone that people use in the community, especially that of experienced contributors, because people new to the project or development in general can be pretty easily discouraged with what could be perceived as arrogance, hostility, or unfriendliness. We want to create an encouraging, welcoming, and friendly atmosphere in QMK, and part of that is making sure that we say something when we think these things aren't done.

I'm really looking forward to seeing these features integrated - if there's anything we can do to help with the refactoring, or questions you might have, please let us know!

**Comment by JamesHagerman** [comment]
@Wilba6582 I sincerely apologize for opening a PR on your fork. It was wrong of me to do so without collaborating with you before hand. I look forward to seeing your refactor and greatly appreciate all of the work you've done on these keyboards and on QMK. What is the best way to contact you?

@jackhumbert Wilba is entirely courteous and I am in the wrong here. Thank you for understanding and being civil with my ignorance.

I hadn't realized that Chrome disabled WebUSB in 65 without warning. Thank you for the heads up.

I'll bring up my ideas to the QMK Discord.

**Comment by Wilba6582** [comment]
Start a new issue about this so we can discuss it.

**Pull request closed without merging**
