### PR TITLE
Remove CORTEX_ENABLE_WFI_IDLE from keyboards.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

As per the title.
Adds the equivalent to the ChibiOS build scripts.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by hellmind** [comment]
From this 416af0171c6433a7ecb198386dd2c3ac70d4cbd2 
I got my boot times super slow.
kinesis/kint41

**Comment by fauxpark** [comment]
This PR wouldn't have changed anything to do with that.

**Comment by hellmind** [comment]
It seems my teensy 4.1 with that change is discovering using wifi or something like that at boot.

**Comment by fauxpark** [comment]
That's not at all what this does. The Teensy 4.1 has no Wifi. Your issue is elsewhere.

**Pull request merged**
