### PR TITLE
strictly keymap changes

### PR DESCRIPTION
**Pull request by dlaroe**
Updating keymaps including adding a community layout and changing my keymap dirs from dale to dlaroe to match my Github username.

### CODE REVIEW

**Comment by jackhumbert** [comment]
It looks like you might need to rebase on master - these changes remove the Contra folder :/

**Comment by dlaroe** [comment]
Doh, will do!

**Comment by dlaroe** [comment]
I am so ready for layouts/ to be a separate repo. I have no idea how I've broken it this time.

**Comment by dlaroe** [comment]
Well, after taring up my changes "git reset --hard upstream/master", "git pull upstream master" and then a "git push --force" seems to have closed my pull request. I'll make another one once I untar my changes.

**Comment by dlaroe** [comment]
Fixed and reopening...

**Comment by dlaroe** [comment]
Gah! I'm not even touching lib/chibios and lib/chibios-contrib! Do I need to delete and refork?

**Comment by dlaroe** [comment]
deleting and reforking

**Pull request closed without merging**
