### PR TITLE
eeprom driver: call eeprom_driver_init on avr targets too

### PR DESCRIPTION
**Pull request by purdeaandrei**
## Description

This follows what chibios does.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Retargeted to `develop` due to core changes.

**Review by drashna — APPROVED** [review]

**Comment by fauxpark** [comment]
Why not move this call to `keyboard_setup()`? After all, it has nothing to do with LUFA, ChibiOS or V-USB, so it should not really be anywhere near that code.

**Comment by purdeaandrei** [comment]
@fauxpark 
> Why not move this call to `keyboard_setup()`? After all, it has nothing to do with LUFA, ChibiOS or V-USB, so it should not really be anywhere near that code.

Alright. I have also moved the following
`
#ifdef STM32_EEPROM_ENABLE
    EEPROM_Init();
#endif
`
Cause I believe EEPROM_Init() and eeprom_driver_init() should be called from the same place in code.

**Comment by tzarc** [comment]
> Cause I believe EEPROM_Init() and eeprom_driver_init() should be called from the same place in code.

Agreed -- the whole eeprom side of things has a large cleanup on my todo list, this was one of the items. Will end up consolidating this at some point in the future, thanks for simplifying the current stuff as-is.

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
