### PR TITLE
Add Dactyl Manuform 5x8 keyboard

### PR DESCRIPTION
**Pull request by iliorik**
## Description
This pull request add new keyboard to handwired/dactyl_manuform: 5x8.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [*] Keyboard (addition or update)
- [*] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [*] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [*] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [*] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by waffle87 — CHANGES_REQUESTED** [review]
Please not close and open new PRs (#24726). There are numerous suggested changes on your previous PR that have not been addressed even in this new one?

**Comment by iliorik** [comment]
> Please not close and open new PRs (#24726). There are numerous suggested changes on your previous PR that have not been addressed even in this new one?

I rewrote the code in the files taking into account the proposed changes. Can I reopen the old PR?

**Comment by waffle87** [comment]
> Can I reopen the old PR?

Sure, given that half of the requested changes were not made, it would be best to keep the context there.

**Comment by sigprof** [comment]
In order to reopen the old PR, the new PR from the same branch needs to be closed first.

**Pull request closed without merging**
