### PR TITLE
Remove custom matrix from PS2AVRGB boards

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

All of this matrix code is unnecessary, as PS2AVRGB has a single common matrix pinout, and the core matrix.c can handle col2row.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
All but one error seemed to be unrelated.

**Comment by yanfali** [comment]
@coseyfannitutti can you verify the changes on your boards please?

**Comment by fauxpark** [comment]
@sidcarter `DIODE_DIRECTION` was missing from the Finger65 config.h, can you confirm it's `COL2ROW`? (seems to be the case for the rest of them but just to be sure)

**Comment by sidcarter** [comment]
> @sidcarter `DIODE_DIRECTION` was missing from the Finger65 config.h, can you confirm it's `COL2ROW`? (and also how the heck it apparently worked without defining it) Seems to be the case for the rest of them but just to be sure.

whooops, I don't have that keeb no moah. I can ask the one who has the keeb to try it out, but I don't think he's well versed with the QMK code. Suggestions to proceed?

**Comment by fauxpark** [comment]
Just need to know which way the diodes are pointing. Assuming this is the same PCB:

that looks like COL2ROW. The stripe on the diodes are pointed towards the switches, with the other end connected to vertical traces.

**Comment by sidcarter** [comment]
@fauxpark https://txkeyboards.com/images/virtuemart/product/65per.jpg

Unfortunately, I don't have a more detailed pic. It looks as though as it's facing away from the switch?

I could try to get a new pic from the new owner, if that doesn't work.

**Comment by fauxpark** [comment]
I'm fairly confident now - the matrix.c from [here](https://github.com/xauser/tmk_keyboard/blob/xauser/keyboard/l3/matrix.c) is switching row pins and reading column pins, which is what the QMK matrix.c does when configured for COL2ROW. It looks like all the L3 PCBs have the same pinout between them, much like PS2AVRGB. (Finger65 config.h is missing the C2 pin for row 0, probably since it has no F keys)

**Pull request merged**
