### PR TITLE
DC01 refactor and Configurator support

### PR DESCRIPTION
**Pull request by noroadsleft**
- arrow
  - `LAYOUT_ALL` renamed to `LAYOUT_all`
- left
  - `LAYOUT_ANSI` renamed to `LAYOUT_ansi`
- numpad
  - matrix macro correction (keycodes were going to be received out of order)
  - added support for community layouts `numpad_5x4` and `ortho_5x4`
- right
  - `LAYOUT_ANSI` renamed to `LAYOUT_ansi`
  - `LAYOUT_ISO` renamed to `LAYOUT_iso`
  - `LAYOUT_HHKB_ANSI` renamed to `LAYOUT_hhkb_ansi`
  - `LAYOUT_HHKB_ISO` renamed to `LAYOUT_hhkb_iso`
- global readme cleanup (minor grammar corrections)
- added Configurator support for all four parts

### CODE REVIEW

**Comment by noroadsleft** [comment]
Tagging @yiancar because it's his board. (And man, is it a sweet-lookin' board!)

**Comment by drashna** [comment]
@yiancar Do these changes look good to you?

**Comment by yiancar** [comment]
@drashna Looks all good to me. Did not have a look at the jsons as I dont understand them but I have trust.

Thank you @noroadsleft for going into the trouble!

**Comment by noroadsleft** [comment]
@yiancar Thanks for the kind words.

That offer to teach you what I know about the JSON files is a standing offer, redeemable any time.

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
