### PR TITLE
Organizing my keyboards (plaid, tartan, ergoinu)

### PR DESCRIPTION
**Pull request by hsgw**
## Description

Putting Plaid, tartan, and ergoinu in "dm9records" directory.   
Preparing for my own keymap editor.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by hsgw** [comment]
I found a build error due to keymap specific code.
Should I maintain these code?

**Comment by drashna** [comment]
Correct. Build errors are due to community layouts that don't properly support the board.  They are fine, as all the default keymaps appear to pass.

**Comment by mtei** [comment]
`keyboards/dm9records/ergoinu/rules.mk` needs to be changed.

```shell
 % make dm9records/ergoinu:default
QMK Firmware 0.8.71
Makefile:560: keyboards/ergoinu/rules.mk: No such file or directory
 % make dm9records/ergoinu:default_jis
QMK Firmware 0.8.71
Makefile:560: keyboards/ergoinu/rules.mk: No such file or directory
```
```
 % vi keyboards/dm9records/ergoinu/rules.mk
```
```diff
 % git diff | cat
diff --git a/keyboards/dm9records/ergoinu/rules.mk b/keyboards/dm9records/ergoinu/rules.mk
index 6f5debe00..7ccbedf61 100644
--- a/keyboards/dm9records/ergoinu/rules.mk
+++ b/keyboards/dm9records/ergoinu/rules.mk
@@ -35,7 +35,7 @@ SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend
 CUSTOM_MATRIX = yes
 SRC += matrix.c serial.c split_util.c
 
-DEFAULT_FOLDER = ergoinu
+### DEFAULT_FOLDER = ergoinu
 
 # ergoinu configs
 DISABLE_PROMICRO_LEDs = yes
```

```
 % make dm9records/ergoinu:default
.....
 * The firmware size is fine - 18858/28672 (65%, 9814 bytes free)
 % make dm9records/ergoinu:default_jis
....
 * The firmware size is fine - 18858/28672 (65%, 9814 bytes free)
```

**Comment by hsgw** [comment]
I fixed! Thanks.

**Comment by noroadsleft** [comment]
As this touches user keymaps, we'll need clearance from @brickbots and @CaninoDev (`thehalfdeafchef`) before this is merged; otherwise it's a `future` branch change.

**Comment by hsgw** [comment]
OK, I'll be awaiting approval from keymap owners for a while.
But I don't modify keymaps, only move directory.

**Comment by CaninoDev** [comment]
Will I need to make changed to make this go through?

**Comment by hsgw** [comment]
> Will I need to make changed to make this go through?

You don't need to do anything👍
But the build command will be changed as below after this is merged.
```
make dm9records/[keyboard]:[keymap]
```

**Comment by CaninoDev** [comment]
Approved.

**Comment by brickbots** [comment]
Approved!  Thanks for all of your work on these boards @hsgw.  This is still one of my favorite boards to type on 💯

**Comment by hsgw** [comment]
I fixed merge conflict.   
I'm sure that this is ready to merge.

**Comment by hsgw** [comment]
I fixed conflict again.
I think this is ready to merge.

**Comment by mtei** [comment]
Looks Good To Me.

* `make dm9records/ergoinu:all`
   no problem.

* `make dm9records/tartan:all`
   layouts/community/60_iso/unxmaal/config.h problem

* `make dm9records/plaid:all`
  `./layouts/community/planck_mit/guidoism/config.h:24: error: "USB_MAX_POWER_CONSUMPTION" redefined [-Werror]`
  `./layouts/community/ortho_4x12/bakingpy/rules.mk` problem?
  `./layouts/community/ortho_4x12/juno/rules.mk` problem?
  `./layouts/community/ortho_4x12/junonum/rules.mk` problem?
  `./layouts/community/ortho_4x12/xyverz/rules.mk`  problem?

**Comment by hsgw** [comment]
> Looks Good To Me.
> 
> * `make dm9records/ergoinu:all`
>   no problem.
> * `make dm9records/tartan:all`
>   layouts/community/60_iso/unxmaal/config.h problem
> * `make dm9records/plaid:all`
>   `./layouts/community/planck_mit/guidoism/config.h:24: error: "USB_MAX_POWER_CONSUMPTION" redefined [-Werror]`
>   `./layouts/community/ortho_4x12/bakingpy/rules.mk` problem?
>   `./layouts/community/ortho_4x12/juno/rules.mk` problem?
>   `./layouts/community/ortho_4x12/junonum/rules.mk` problem?
>   `./layouts/community/ortho_4x12/xyverz/rules.mk`  problem?

I'm sure these errors are due to community layout for other keyboard.   
same as Travis error.

**Comment by mtei** [comment]
> I'm sure these errors are due to community layout for other keyboard.
> same as Travis error.

I agree with you. That's not your problem.

**Comment by mtei** [comment]
### For your infomation. / ご参考まで。

#### About `make dm9records/plaid:guidoism`

いま、以下のコンパイルはエラーを引き起こします。
Now, the following compilation will cause an error:

```shell
make dm9records/plaid:guidoism
.....
Compiling: keyboards/dm9records/plaid/plaid.c  In file included from <command-line>:
./layouts/community/planck_mit/guidoism/config.h:24: error: "USB_MAX_POWER_CONSUMPTION" redefined [-Werror]
 #define USB_MAX_POWER_CONSUMPTION 50
 
In file included from <command-line>:
./keyboards/dm9records/plaid/config.h:52: note: this is the location of the previous definition
 #define USB_MAX_POWER_CONSUMPTION 100
 
cc1: all warnings being treated as errors
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [.build/obj_dm9records_plaid_guidoism/keyboards/dm9records/plaid/plaid.o] Error 1
```

これは、以下のようにすると容易に避けることができます。
This can be easily avoided by doing the following:

```diff
diff --git a/keyboards/dm9records/plaid/config.h b/keyboards/dm9records/plaid/config.h
index 4d7bedee5..5602f3f7b 100644
--- a/keyboards/dm9records/plaid/config.h
+++ b/keyboards/dm9records/plaid/config.h
@@ -49,7 +49,7 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 /* COL2ROW, ROW2COL*/
 #define DIODE_DIRECTION COL2ROW
 
-#define USB_MAX_POWER_CONSUMPTION 100
+// #define USB_MAX_POWER_CONSUMPTION 100 // move to post_config.h
 
 /*
  * Split Keyboard specific options, make sure you have 'SPLIT_KEYBOARD = yes' in your rules.mk, and define SOFT_SERIAL_PIN.
diff --git a/keyboards/dm9records/plaid/post_config.h b/keyboards/dm9records/plaid/post_config.h
new file mode 100644
index 000000000..879edd3d5
--- /dev/null
+++ b/keyboards/dm9records/plaid/post_config.h
@@ -0,0 +1,5 @@
+#pragma once
+
+#ifndef USB_MAX_POWER_CONSUMPTION
+    #define USB_MAX_POWER_CONSUMPTION 100
+#endif
```

**Comment by fauxpark** [comment]
The usbconfig.h files for these boards can be deleted.

**Comment by hsgw** [comment]
Thanks! I deleted them.

**Comment by noroadsleft** [comment]
Sending this through the `future` branch to take advantage of some QMK-side workflow advantages. These changes will land in mainline May 30.

Thanks!

**Pull request merged**
