### PR TITLE
Move keyboard USB IDs and strings to data driven: 0-9

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Some have been left out due to an issue with the ordering in which `info.json`s at multiple levels are merged together, that will need to be resolved. For now, these can be done.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by zvecr — APPROVED** [review]

**Comment by myst729** [comment]
Is this change involved with the build process? What will happen if _info.json_ doesn't exist (e.g. fast prototyping)?

**Comment by myst729** [comment]
Sometimes just hand craft the minimum of required files: config.h, kb.h, kb.c, rules.mk, and a default keymap.c. Focusing the major idea, and most of other fields may be omitted and fall back to qmk default.

**Comment by fauxpark** [comment]
info.json will eventually become the main config file for QMK keyboards. A lot of things from those files can already be defined there instead.

For the moment you can still specify the manufacturer and product strings in config.h, but after the next breaking changes merge (not this upcoming one), they will need to be actual string literals, eg:
```c
#define MANUFACTURER "blah"
```

The reason for this is that without the quotes, the preprocessor can potentially mangle the strings because a word matches some other defined symbol. Here's an example from the Discord:
```c
#define PRODUCT 3x4 F13 - F24 Function Keyboard
```
This gets preprocessed, baked into the firmware, and shown in Device Manager as:
```
3x4 ((ioline_t)((uint32_t)(GPIOF)) | ((uint32_t)(13))) - F24 Function Keyboard
```
Using string literals will also allow for better Unicode support.

These PRs were aimed at making this transition easier; after all of the strings have been moved to info.json, only the USB descriptor code and the CLI generation for the defines needs to be changed, and that makes for a much smaller and more easily reviewable diff.

**Comment by myst729** [comment]
Got it. Thanks for the details.

**Pull request merged**
