### PR TITLE
Update Swiss French/German keymaps and add sendstring LUTs

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

🇨🇭 (🇫🇷/🇩🇪)

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by vomindoraan** [comment]
It would be nice to see `{keymap,sendstring}_fr_ch.h` renamed to `{keymap,sendstring}_french_ch.h` for consistency.

**Comment by vomindoraan** [comment]
Consider using `CH_*` instead of `FR_*` and `DE_*` since

**Comment by fauxpark** [comment]
I would probably want to rename the whole lot to match `fr_ch`, but that would be quite the breaking change. For the moment, I could rename these to `{keymap,sendstring}_{french,german}_swiss.h` and have the original headers simply include the correct ones, perhaps with a `#pragma message` indicating they are deprecated.

**Comment by vomindoraan** [comment]
That sounds good to me.

In my opinion, the best solution in the long term would be to name the files by locale (as discussed in #8560) and the keycodes by country code (for brevity). So Swiss French would use `keymap_fr_ch.h`, as you suggested, with `CH_*` keycodes; Serbian Latin would use `keymap_sr_latn.h` with `RS_*` keycodes; Brazilian Portuguese would use `keymap_pt_br.h` with `BR_*` keycodes; etc.
We could implement this in the upcoming breaking change, and I'd be glad to assist you.

**Comment by vomindoraan** [comment]
LGTM, just rename the files when you get the chance.

**Pull request merged**
