### PR TITLE
Update MF68 info.json for Configurator

### PR DESCRIPTION
**Pull request by yanfali**
- add a LAYOUT_kc so configurator will load info.json

### CODE REVIEW

**Comment by yanfali** [comment]
I think we either need to fix the compile, or figure out a different way to do this.

**Comment by drashna** [comment]
Honestly, the LAYOUT_kc is mostly for human readability/convenience.   I'm not sure we need to supported here.

@jackhumbert or @skullydazed, what's the policy for these?

**Comment by yanfali** [comment]
It's referenced in the factory keymap, so it should compile right?

**Comment by drashna** [comment]
For the configurator, that depends on how it's passing the keycodes.   If it uses the KC_xx code, then using LAYOUT_kc will cause it to fail to compile, because it's getting `KC_KC_xxxx`, which is not valid. 

IMO, the LAYOUT_kc shouldn't be added here, since it just adds unneeded complexity.  But that's also why I tagged jack.

**Comment by yanfali** [comment]
I see. Maybe we need to filter out kc layouts in the UI or API by convention

**Comment by yanfali** [comment]
_kc's shouldn't be used in UI, they are convenience for _firmware.

**Pull request closed without merging**
