### PR TITLE
Add I2C configuration defines for STM32

### PR DESCRIPTION
**Pull request by daskygit**
## Description

This adds default configurations for the STM32 I2C peripherals.

I've opened this for some eyes on the configurations, I also don't have hardware to test all of them. I'm hoping some kind people might help out. 

After a brief chat with tzarc it seems like the defines might want renaming and/or restructuring with the possibility of adding all alternative pins for a given I2C peripheral. (at the moment it only provides one where available)

The clock configurations should be valid for the default mcuconf clock setup for each platform. I need to triple check but was aiming to do this when writing the documentation. The rise and fall time is set to 0ns in STMCubeMX which is the current setup in i2c_master for f303. (I guess this may be an issue?)

Any help testing any of there configurations would be greatly appreciated, I suspect some might need additional work.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by fauxpark** [comment]
I recall tzarc saying they wanted to change the i2c_master pin config to something more like how the `spi_master` driver does it, ie. with `I2C_SDA_PIN`/`PAL_MODE` etc. rather than individual bank and pin number defines.

**Comment by daskygit** [comment]
Ahh okies, would it need updating if there were higher level defines though? I am intending to rename these defines a little after that discord chat. So `USE_I2C1_SDA_ALT` => `USE_I2C1_SDA_B7` (which is clearer) but if i2c_master is going to change these will need a little bit more of a rework.

The idea was mostly to provide I2Cv2 timing configurations as it seems a sticking point but decided it could also setup the alternative functions and mostly hide the setup completely.

**Comment by tzarc** [comment]
This definitely goes a long way to standardising how people configure I2C.

I also had in mind something like `USE_I2C1_400KHZ` could also set up halconf's `HAL_USE_I2C`, mcuconf's `STM32_I2C_USE_I2C1`, then potentially no override files in the keyboard are required. Probably worth investigating _how_ to do this for at least one scenario -- we can then use the same methodology once we decide to do SPI, PWM, etc.

**Comment by daskygit** [comment]
Happy to redo these defines however they're wanted, the comment about the underlying configuration changing halted any more work for the moment. I had plans of implementing defines for other hardware peripherals but wanted to see how this went.

My main concerns are:
- What should be a reasonable default for rise/fall times? 
0 appears to work fine but it's not a realistic figure and also out of spec as a rise time for fast mode I believe.

- How many different configurations should be provided? 
At the moment I've only really provided 2 different options for pin setup where possible and 2 different speeds per i2c peripheral.

If this expands to include halconf and mcuconf setup maybe it's best to be separate it out into different PRs per platform?

**Pull request closed without merging**
