### PR TITLE
Fixup checkerboards/quark_lp

### PR DESCRIPTION
**Pull request by waffle87**
## Description

- `RGB_MATRIX_DRIVER` was undefined.
- `g_led_config` was incorrect according to `MATRIX_ROWS`/`MATRIX_COLS` definitions. (I assume excess LEDs defined are underglow)
- Other misc. stuff.

@npspears look ok?

## Types of Changes

- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Comment by npspears** [comment]
No, please keep those extra LEDs. There is not underglow on this PCB. The extra LEDs are because of the extra keys on the bottom row (grid, single 2u, 2x2u)

**Comment by waffle87** [comment]
> No, please keep those extra LEDs. There is not underglow on this PCB. The extra LEDs are because of the extra keys on the bottom row (grid, single 2u, 2x2u)

Their functionality will be retained with the positions defined [here](https://github.com/qmk/qmk_firmware/blob/master/keyboards/checkerboards/quark_lp/quark_lp.c#L31), but the first array in `g_led_config` needs to match the matrix row/col number. However, those positional values may want to be changed, given that the LEDs for the other layouts are now 48, 49, & 50. Hope that makes sense.

**Comment by npspears** [comment]
I might understand, but I also don't know what the solution is. Please chat with me on Discord if you can. I'll be on tomorrow morning.

**Comment by npspears** [comment]
Just confirming that I talked to Jack on Discord and I have verified the 3 "extra" LEDs. Thanks for the help!

**Comment by npspears** [comment]
what else do you need from me to in order to see this pushed?

**Pull request closed without merging**
