### PR TITLE
Serial refactor

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

This PR aims to move the serial UART config (which is specifically for the RN42 Bluetooth module) out of `config_common.h`, and into `serial.h`, in preparation for moving the AVR USART implementation to `drivers/`.

I do not really know if these changes actually work, or even if most of the overrides in the keyboard code are necessary, other than perhaps the baud rate. Would be appreciated if anyone who owns one of these boards could test.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Default keymaps for these boards now compile successfully, though I still don't know if functionality is affected.

**Comment by zvecr** [comment]
`serial.h` has already been claimed by split transport, you would have to go with something like `uart.h` instead to avoid conflicts.

**Comment by fauxpark** [comment]
Yeah, I noticed it was picking up the soft serial header so I had to disambiguate it...

`uart.[ch]` is taken too, but I may end up just pinching that one and migrating these boards. It looks much better and will probably be easier to implement the API on the ChibiOS side: https://github.com/qmk/qmk_firmware/blob/master/tmk_core/common/uart.c

Only problem is I don't have anything to test on...

**Comment by fauxpark** [comment]
@filoxo @mattdibi @danielhklein would you be able to check that this PR doesn't break the Honeycomb, Redox Wireless and Uni660? That will give me some confidence that the rest of the affected boards still work.

**Comment by jvbroek** [comment]
FYI: I'm the original developer of the Honeycomb, but it's based (the receiver is almost a direct copy of) off the Mitosis.  Does the Mitosis still work after these changes?

**Comment by fauxpark** [comment]
That's what I'd like to know - though if the Honeycomb still works, the Mitosis probably does too, as the changes are for the most part the same across all these boards. The matrix scanning code is virtually identical.

**Comment by jvbroek** [comment]
I unfortunately don't have a honeycomb to test, but I may be able to pick up my Dichotomy from work (haven't been into the office since COVID hit) and give that a shot.  IIRC the UART config was in the keyboard files, not the core files.

**Review by tzarc — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Pull request merged**
