### PR TITLE
Fix Bug with (RGB|LED)_DISABLE_WHEN_USB_SUSPENDED define 

### PR DESCRIPTION
**Pull request by drashna**
# Description

The check actually errors out if not set to anything (just defined, per docs)

## Types of Changes

- [x] Core
- [x] Bugfix

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Review by fauxpark — COMMENTED** [review]
Should be done for LED Matrix as well?

**Comment by drashna** [comment]
> Should be done for LED Matrix as well?

Yes.  But I was having issues with it on RGB matrix, so didn't want to do that yet.  Will add now.

**Review by fauxpark — COMMENTED** [review]
Out of curiosity, is there a particular reason to use `1` instead of `true`?

Looking at current master, I don't see any usages of this define that set it to anything other than `true` or `false`, except for the docs. So I think they should be updated as well.

Also, IMO the presence of the define itself should be the decider - but that I guess would be a job for `develop`.

**Comment by drashna** [comment]
Well, the point is to have define enable the behavior, without the need to have true or false set.  

However, having it set to true or false causes issues.  And checking if it's equal to true or false causes issues when it's not.  At least in the preprocessor stuff. 

So, right now, if you use `#define RGB_DISABLE_WHEN_USB_SUSPENDED` as per the docs, you get: 
```
Compiling: quantum/rgb_matrix.c                                                                    quantum/rgb_matrix.c:70:36error: operator '!=' has no left operand
 #if RGB_DISABLE_WHEN_USB_SUSPENDED != false
```

Changing it to look for true generates the same issue.  This method is the only way I've seen that actually works, and without having to change every define in the repo.

**Pull request merged**
