### PR TITLE
Start to update all keyboard readmes

### PR DESCRIPTION
**Pull request by ezuk**
We're changing all keyboard readmes over to the new format (after the break here), per standard recommended in #1362.

- [x] alps64
- [x] amj60
- [x] amjpad
- [ ] atomic
- [x] atreus
- [x] atreus62
- [x] bantam44
- [ ] chibios_test
- [x] clueboard
- [x] cluecard
- [x] cluepad
- [ ] converter
- [x] dk60
- [ ] ergodox
- [x] frosty_flake
- [x] gh60
- [x] gherkin
- [x] gonnerd
- [ ] handwired
- [x] hhkb
- [x] infinity60
- [x] jd40
- [x] jd45
- [x] kbd75
- [ ] kc60
- [ ] kinesis
- [x] kitten_paw
- [ ] kmac
- [ ] lets_split
- [ ] m10a
- [ ] maxipad
- [x] mechmini
- [x] mitosis
- [x] miuni32
- [ ] nyquist
- [ ] orthodox
- [x] pegasushoof
- [x] phantom
- [x] planck
- [x] preonic
- [ ] ps2avrGB
- [x] roadkit
- [x] s60_x
- [x] s65_x
- [x] satan
- [x] sixkeyboard
- [ ] subatomic
- [x] tada68
- [x] tiger_lily
- [x] tv44
- [x] vision_division
- [x] whitefox
- [x] xd60

---

```md
Planck
===

![Planck](http://i.imgur.com/q2M3uEU.jpg)

A compact 40% (12x4) ortholinear keyboard kit made and sold by OLKB and Massdrop. [More info on qmk.fm](http://qmk.fm/planck/)

Keyboard Maintainer: [Jack Humbert](https://github.com/jackhumbert)
Hardware Supported: Planck PCB rev1, rev2, rev3, rev4, Teensy 2.0
Hardware Availability: [OLKB.com](https://olkb.com), [Massdrop](https://www.massdrop.com/buy/planck-mechanical-keyboard?mode=guest_open)

Make example for this keyboard (after setting up your build environment):

    make planck-rev4-default

See [build environment setup](https://docs.qmk.fm/build_environment_setup.html) then the [make instructions](https://docs.qmk.fm/make_instructions.html) for more information.
```

### CODE REVIEW

**Comment by fredizzimo** [comment]
I think we need to make sure that the information is available elsewhere before making these changes. For example the special flashing considerations for the Infinity are not at the moment.

Also see my comments on #1439, for the reason for the Travis build failure.

**Comment by jackhumbert** [comment]
Yeah, let's revert 5e36f84 (for reasons in #1439) and make this the PR for changing over all of the readmes. I meant to do this with changing mine over in 1a4a66fd015990942a7248160aa63eb2fa6e59af, but forgot.

All of these readme changes should be made in junction of adding more information to the @qmk/qmk.fm, and fleshing out pages for all of the keyboards that need/want them.

**Comment by skullydazed** [comment]
I just opened #1459 for mine since for now I didn't have any information to move over to qmk.fm. We should enumerate the keyboards that still need their readme updated so people can pick them up to work on as they have time.

**Comment by Dbroqua** [comment]
Hi,

It's ok for the DK60 keyboard (cf #1465).

Regards,
Damien

**Comment by jackhumbert** [comment]
We're gonna go ahead and merge this, and #1588 will keep track of the progress on the rest of these!

**Comment by ryanmaclean** [comment]
Woah @fredizzimo had a good point there... Massive change and the links to qmk.fm are currently not working. 

I can assist with the AMJs, Zeal60 and HHKB controller readmes, just let me know what you want, and where. As it stands, many of the notes about quirks are missing, and the readme template also has some spacing issues that I'd be happy to open a PR for (but again, that would be another big PR).

**Pull request merged**
