### PR TITLE
Submitting my own custom layout for S60X keyboard

### PR DESCRIPTION
**Pull request by antelaurijssen**
Hi everyone,

Hope I'm doing this correctly... This is my first pull request!
I'd like to submit my custom keymap for S60X to the qmk repository. I've put together two MIDI layers, including one that sends chords instead of notes, with my own function. I've also put together a morse code layer, which isn't really useful, but it's nerdy and fun! 

If I'm doing this wrong, let me know...

Thanks!

### CODE REVIEW

**Comment by jackhumbert** [comment]
Awesome! If you could host your images somewhere else, and link to them in your readme, that would be awesome :)

**Comment by antelaurijssen** [comment]
OK, will do that tonight when I'm back home. Will I have to resubmit a pull request? And in the future if I make more changes, do I have to submit a pull request every time, or will it automatically sync with my own branch? Sorry for all these newbie questions... ;-)

**Comment by shieldsd** [comment]
You can keep adding commits to your branch and they'll be included in the pull request. Once your changes are merged in the pull request is closed

**Comment by antelaurijssen** [comment]
@jackhumbert I have modified my readme.md file and put links to keyboard-layout-editor.com instead of the pictures for each of my layers. Hope this works for you.
So if I understand correctly, once this pull request is closed, I will have to open a new one to submit changes that I make? Thanks for your help!

**Comment by jackhumbert** [comment]
All of the changes got made automatically since the PR is coming from your master branch :) thanks!

**Pull request merged**
