### PR TITLE
Fixed WB32 MCU remote wakeup issue

### PR DESCRIPTION
**Pull request by itarze**
## Description

There are some computers that need to add a wait implementation when remote wakeup

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by itarze** [comment]
This PR needs to wait for ChibiOS/ChibiOS-Contrib#367 to be merged before merging

**Comment by itarze** [comment]
Review the PR, please.

**Review by fauxpark — APPROVED** [review]

**Comment by itarze** [comment]
chibios-contrib lib needs to be updated.

**Comment by itarze** [comment]
?

**Review by tzarc — APPROVED** [review]

**Pull request merged**
