### PR TITLE
Adding support for two new The Mad Noodle Keypads (Revised..Again)

### PR DESCRIPTION
**Pull request by jessel92**
Adding new folder for The Mad Noodle
Which moves old ncc1701kb, and includes two new keyboards

## Description

Rebranded the NCC-1701-KB v1 under The Mad Noodle name
Added support for two new macro pads and created a themadnoodle folder

Let me know if anything needs to be fixed!
Everyone stay safe and healthy!

_(This is a revised PR from a new branch, the first two PRs had merge issues so I had to create a new branch and start over! Sorry about that!)_
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by jessel92** [comment]
I'm not sure why Travis keep throwing these errors, I did not modify any of the files in question. 
What can I do to solve this?

**Comment by KGOH** [comment]
You can try this. Close this PR, then:
```
git reset --soft HEAD~1
git checkout HEAD lib
git commit -m "Adding support for two new The Mad Noodle Keypads (Revised..Again)"
git push --force
```
And open a new PR.

**Comment by jessel92** [comment]
@KGOH Thanks! I'll give that a try!

**Comment by jessel92** [comment]
@KGOH Thanks so much! That worked, Should I still need to create a new PR?

**Comment by KGOH** [comment]
Huh, looks like there is no need to create new PR, but you've already created one, so this doesn't matter anymore. Glad it worked

**Comment by jessel92** [comment]
> Huh, looks like there is no need to create new PR, but you've already created one, so this doesn't matter anymore. Glad it worked

@KGOH  Oops, figured it couldn't hurt so I just opened a new one. 
Thanks again for the help!

**Pull request closed without merging**
