### PR TITLE
Add default layouts for 2u spacebar to Clueboard 2x1800 2019

### PR DESCRIPTION
**Pull request by reywood**
Add default ANSI and ISO layouts for 2u spacebar option. @skullydazed may want to review.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by reywood** [comment]
I should have mentioned that I tested this on my 2x1800 that uses a 2u space bar, and everything appears to work.

**Comment by yanfali** [comment]
not sure the config.h files do anything really, so maybe just leave those out.

**Comment by reywood** [comment]
@yanfali I just copied the existing convention for this board. All the other keymaps have them.

**Comment by noroadsleft** [comment]
@yanfali I think @skullydazed had the reasoning that the default keymaps should have no-change `config.h` and `rules.mk` files, so if a user ran the new keymap script, they'd have the files present in their keymap for making changes.

Perhaps a good idea in future would be to only include the files that are actually needed (so only `keymap.c` files on this PR), and then have the new keymap script check the default keymap folder for `config.h` and `rules.mk` files, and copy those if present, or the appropriate file from `quantum/template/` if not.

**Pull request merged**
