### PR TITLE
Fix typo in via.c

### PR DESCRIPTION
**Pull request by Wilba6582**
## Description

Fix typo in via.c

SMH...

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Have some labels to celebrate, ha!

**Comment by hineybush** [comment]
this breaks everything i have in qmk.

**Comment by tzarc** [comment]
> 
> 
> this breaks everything i have in qmk.

yikes, I'll add breaking changes then

**Comment by Wilba6582** [comment]
Congratulations and thanks to everyone who contributes to QMK!

**Comment by tzarc** [comment]
> 
> 
> Congratulations and thanks to everyone who contributes to QMK!

No, thank *you* :) 🥇

**Comment by noroadsleft** [comment]
So I missed Commit No. 13,337 and 13,370... :slightly_frowning_face: Managed to check and get arguably the next best option:

image

Thanks!

**Pull request merged**
