### PR TITLE
Include I2C constants to fix Unicorne build

### PR DESCRIPTION
**Pull request by bcat**
## Description

The Unicorne keyboard that was recently merged (#12993) no longer builds at latest master due to some undefined I2C constants:

```
Compiling: keyboards/yanghu/unicorne/unicorne.c                                                    In file included from ./lib/chibios/os/hal/include/hal_pal.h:174,
                 from ./lib/chibios/os/hal/include/hal.h:139,
                 from tmk_core/common/chibios/platform_deps.h:18,
                 from quantum/quantum.h:18,
                 from keyboards/yanghu/unicorne/unicorne.h:19,
                 from keyboards/yanghu/unicorne/unicorne.c:16:
keyboards/yanghu/unicorne/unicorne.c: In function 'i2c_init':
keyboards/yanghu/unicorne/unicorne.c:26:23: error: 'I2C1_SCL_BANK' undeclared (first use in this function); did you mean 'I2C_CR1_ACK'?
         palSetPadMode(I2C1_SCL_BANK, I2C1_SCL, PAL_MODE_INPUT);
                       ^~~~~~~~~~~~~
```

(And similar errors follow.) Looks like including `i2c_master.h` pulls in the relevant definitions. I've verified that `qmk compile -kb yanghu/unicorne/f411 -km all` builds successfully with this fix.

@yanghu, does this look good to you?

## Types of Changes

- [ ] Core
- [X] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Unicorne keyboard fails to build at latest master.

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Just a heads up, this is fixed in develop, already, which is due to merge in about 2 weeks.

**Review by drashna — APPROVED** [review]

**Comment by bcat** [comment]
> Just a heads up, this is fixed in develop, already, which is due to merge in about 2 weeks.

Ah, I didn't realize that. Should I drop this PR then?

**Comment by drashna** [comment]
Nah, it may still be helpful to get it in sooner rather than later.

**Comment by bcat** [comment]
Looks like 2021Q4 breaking changes are merged now, so I'll go ahead and close this. :)

**Pull request closed without merging**
