### PR TITLE
Dactyl Manuform 4x5_5 Configurator Rendering Update

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

Disambiguates the intended layout of the keyboard/keymaps, and reduces the horizontal space used to render the keymap.

cc @ssedrick (keyboard maintainer)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

|  |  |
| :---- | :--- |
| Before | handwired_dactyl_manuform_4x5_5_default |
| After | image |

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
The render looks a bit off to me.  Th board is supposed to look like this:
image

**Comment by noroadsleft** [comment]
@drashna Where'd you find that photo? I based the render on the block comment in `keymap.c`:

https://github.com/qmk/qmk_firmware/blob/2800cd31ae5312c3057e7fb0aa5480aaaf8e541d/keyboards/handwired/dactyl_manuform/4x5_5/keymaps/default/keymap.c#L25-L41

**Comment by drashna** [comment]
A quick search, actually.  The thumb cluster like that is referred to as the "dactyl manuform mini", usually.

**Comment by ssedrick** [comment]
The image in the keymap is slightly off, I was putting it together a bit
too quickly. I'm working on a pr to update it and add a new keymap.
Drashna's picture is accurate.

**Pull request merged**
