### PR TITLE
Remove LAYOUT_kc macros from edvorakjp keymaps

### PR DESCRIPTION
**Pull request by epaew**
## Description

* Updated edvorakjp userspace
  * Rename enums
  * Refactor macros
* Removed `LAYOUT_kc` macros from `edvorakjp` keymaps of the below keyboards (https://github.com/qmk/qmk_firmware/pull/12160#issuecomment-794443151)
  * crkbd
  * keebio/iris
  * helix
* Run `clang-format`

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

--

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mtei** [comment]
余談ですが、、
もしもお望みなら、Helix キーボードで、ssd1306.c の代わりに QMK 標準の oled_driver.c を使えるようになりました。
キーマップの rules.mk に以下の1行を追加すれば使えます。

As a side note.
If you prefer, you can now use the QMK standard oled_driver.c instead of ssd1306.c on the Helix keyboard.
You can use it by adding the following line to the keymap rules.mk.


```makefile
OLED_SELECT = core
```

helix/rev2/keymaps/default/oled_display.c も参考にしてください。
See also helix/rev2/keymaps/default/oled_display.c.

**Comment by epaew** [comment]
@mtei 
Thank you for your information! I updated my keymaps.

**Review by mtei — APPROVED** [review]
Looks good to me.

**Review by fauxpark — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
