### PR TITLE
Fix the modifier in ssd1306.c of some keyboards

### PR DESCRIPTION
**Pull request by mogira**
## Description
I changed the font variable's modifier from **static** to **extern** in ssd1306.c of claw44, comet46, crkbd, lily58 and yosino58.
These modifiers had caused build error on my environment (avr-gcc 9.1.0).
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Aside from the compiler error, is there a reason for this?

**Comment by mogira** [comment]
There is no reason other than to resolve compile error.

**Comment by drashna** [comment]
Well, given that 9.1.0 is "bleeding edge", and may have a bunch of other issues, I'm hesitant about merging in a fix that deals with it, only.  

But that's my personal opinion.   If others are fine with it, then it should be okay.

**Comment by mogira** [comment]
Thank you for information. I understand that 9.1.0 is "bleeding edge" version.

But fundamentally, a static global variable should be available only in the file it being declared (in this case, lib/glcdfont.c).
So I can not understand why this could be compiled on the previous versions.

**Comment by mtei** [comment]
Looks Good To Me.

'Font[]' in that source must be declared `extern`, not `static`. But with avr-gcc8, it seems to compile with `static` ignored. I think the behavior of avr-gcc8 is obviously strange.

```
{/tmp} % avr-gcc --version
avr-gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

{/tmp} % cat ext.c                                                                            
// $ avr-gcc -mmcu=atmega32u4 -c -O2 ext.c
#include <avr/pgmspace.h>

static const unsigned char font[] PROGMEM;

unsigned char helo(int a)
{
    return font[a];
}

{/tmp} % cat ext2.c
// $ avr-gcc -mmcu=atmega32u4 -c -O2 ext2.c
#include <avr/pgmspace.h>

extern const unsigned char font[] PROGMEM;

unsigned char helo(int a)
{
    return font[a];
}

{/tmp} % avr-gcc -mmcu=atmega32u4 -c -O2 ext.c 
{/tmp} % avr-gcc -mmcu=atmega32u4 -c -O2 ext2.c
{/tmp} %                                                                                      
{/tmp} % avr-readelf -s ext.o | grep font     
    12: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND font
{/tmp} % avr-readelf -s ext2.o | grep font
    12: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND font
{/tmp} % 
```

**Comment by drashna** [comment]
@mtei thanks for the confirmation.   

So basically, it is an issue with the code, and one that the compiler did not catch until 9.x (which would also be a bug). 

If that's the case, I feel much better about the change.

**Comment by drashna** [comment]
Travis CI errors are unrelated to this change.

**Pull request merged**
