### PR TITLE
Small round of rgb matrix optimizations

### PR DESCRIPTION
**Pull request by XScorpion2**
## Description

Small around of changes to the rgb matrix animation code hoisting a few more chunks of calculations out of the loops.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mechmerlin** [comment]
I wish we had some unit tests to test these.

**Comment by drashna** [comment]
@mechmerlin I mean, there is Drashna CI, just need to kick it. :D

**Comment by XScorpion2** [comment]
I wanted to keep this pr small (unlike my other one) for this round. I'm thinking about the changes to make this giant file more modular / testable especially within the context of the animation functions themselves.

Current thinking is move each animation function into a separate code file, and update the function to take pointers to the necessary global values instead of accessing them via extern field. This way the function can be run directly with a set of test values and the results can them be validated without needing anything but just the animation code file itself.

**Comment by XScorpion2** [comment]
Latest version: https://github.com/qmk/qmk_firmware/pull/5304
Works with the test suite being developed for rgb matrix animations.

**Pull request closed without merging**
