### PR TITLE
Speed up Travis CI builds

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Currently a make all:default takes about 20 minutes, applying https://docs.travis-ci.com/user/speeding-up-the-build/ and some logic i have used in previous projects.

Values for j can vary from:
- num_of_cores
- num_of_cores + 1
- num_of_cores * 2

https://docs.travis-ci.com/user/reference/overview/ documents the environment as 2 cores

## Types of changes

- [ ] Core
- [ ] Bugfix
- [ ] New Feature
- [x] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
The problem with using `-j` here is that the rest of the make script isn't designed to use it.  

It breaks a number of things.  Namely, it breaks the file size check, since it runs that too soon (eg, the board isn't done compiling). 

So, we'd need to change the makefile stuff to properly handle that

**Comment by zvecr** [comment]
@drashna happy to dig through and fix those issues too. The main aim at the moment was to see how fast it _could_ go on the current infrastructure.

**Comment by zvecr** [comment]
So some super important stats so far, changing number of jobs:
- -j2 TBD
- -j4 ~21% faster
- -j8 ~20% faster

Not running duplicates saved about 45 seconds.

**Comment by zvecr** [comment]
hmmmm removing NOTPARALLEL from the top level Makefile results in a 4x speedup, however there was no change on travis. I have not encountered any other parallel issues, other than the size check one that ive already fixed.

**Comment by zvecr** [comment]
Cherry picked all the current non MAKEFLAGS fixes from this WIP. Will rebase once those PRs are merged.

**Comment by zvecr** [comment]
Rebased with just `-j3`

**Comment by zvecr** [comment]
@drashna Could the 'in progress' label be removed from this issue?

**Comment by skullydazed** [comment]
Thanks!

**Comment by zvecr** [comment]
Thanks everyone involved in this one!!! As a quick update now its available on master, with the increased amount of supported keyboards, I can see "build all" builds over 20% faster than before. Time to add 20% more keyboards.

**Pull request merged**
