### PR TITLE
Double knight rider for split keyboards

### PR DESCRIPTION
**Pull request by broswen**
This is a new rgb underglow mode inspired from the knight rider mode.
It splits the animation into mirrored halves. This is designed for split keyboards.
It uses the config values for hue/val/sat and uses 3 different speeds from the original knight rider mode.

### CODE REVIEW

**Comment by Lenbok** [comment]
It's worth thinking about how/whether this would interact when the split keyboard uses i2c instead of running RGB data over a separate line.

Currently with split keyboards using i2c, each half-keyboard runs its LEDs independently, (so if enabled, the split animation would already be mirrored?)

**Comment by broswen** [comment]
@Lenbok I only have an iris board connected through serial. Is there any documentation you could link about how LEDs are controlled when using i2c?

Or is it as simple as using a different lighting algorithm when `#define USE_I2C` is defined?

**Comment by Lenbok** [comment]
The i2c RGB support is fairly new (#3120) and currently only supports static modes (fixed, rainbows etc), but people have been experimenting with getting animated modes working (#773).

I think that the current list of RGB light modes is getting pretty long and disorganized and it might be better to allow compile-time customization of the particular set of modes that you wanted. I.e. you could choose to exclude any that were just not wanted, or which weren't appropriate for the type of keyboard, and it would also let you put the modes in the desired order. (Seems worthy of a separate issue though, rather than necessarily affecting this PR)

**Comment by drashna** [comment]
There are some merge conflicts that need to be resolved here.

Also, i2c animation support is being worked on.

**Comment by drashna** [comment]
Any update on this?

**Comment by broswen** [comment]
@drashna Sorry, I've been busy with school lately.
Would it be worth it to port to the new RGB Matrix feature instead?
Do a lot of keyboards have support for that feature?

**Comment by drashna** [comment]
Not a problem.  School always comes first! 

As for the RGB matrix... it's different enough that i don't think that this would fit into this.

**Comment by broswen** [comment]
@drashna , I'm taking a look at those new `RGBLIGHT_SPLIT` and `RGBLED_SPLIT`. Is it as simple as checking for a define and using those variables? I read through the RGB docs but didn't see any specific information about setting RGB LEDs on a split board.

Also, if `RGBLIGHT_SPLIT` is  defined does it  mirror (both 0 position on the outside?) or do they both start from the left (assuming a single row of underglow)?

**Comment by drashna** [comment]
@broswen yup.  It's that simple, now. 

And no, the define doesn't mirror it, it detects which is which, and displays it properly. 

For instance, On my iris, I have rgbled split enabled, and the effect goes between the halves properly, as if I was using the "extra data" pin to transmit the data, rather than having each wired to each half.

**Pull request closed without merging**
