### PR TITLE
Signum 3.0 Fix key order in layout

### PR DESCRIPTION
**Pull request by jceb**
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fix keyboard layout for Signum 3.0

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
@noroadsleft This look good?

**Comment by noroadsleft** [comment]
The ordering is correct, but I'm not keen on how much space this would take up, visually. It's wasting space unnecessarily.

[info.json.txt](https://github.com/qmk/qmk_firmware/files/3110724/info.json.txt)

Same ordering, but more space-efficient.

**Comment by jceb** [comment]
@noroadsleft thanks, I reduced the dimensions according to your suggestion.

**Comment by noroadsleft** [comment]
Fixing the `width` and `height` values doesn't fix the rendering, because the rendering code doesn't use or care about them; it only cares about the `x` and `y` values in your layout object. (`width` and `height` are only used by the API internally.)

The file I posted basically moves all your keys 1.25u to the left and 0.25u up, and separates each half by 1u, which is consistent with most of the ergo/split keyboards we support. I actually started doing this because the Configurator's UI code doesn't understand key rotation – you can include `r` values, which are valid to place (and I've kept them in the file above), but Configurator doesn't do anything with them. The architecture and code just hasn't been written yet.

**Comment by jceb** [comment]
Okay, got it. Thanks for preparing the layout, I added it to the repository.

**Comment by noroadsleft** [comment]
@jceb Thank *you* for your help in supporting this keyboard.

**Pull request merged**
