### PR TITLE
Fix compilation for USB_6KRO_ENABLE = yes

### PR DESCRIPTION
**Pull request by kosorin**
## Description

Compilation failed when `USB_6KRO_ENABLE` was set to `yes`.
I moved code from `action_util.c` to `report.c` which wasn't moved to `report.c` in earlier commits.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
What is the purpose of `USB_6KRO_ENABLE` anyway? By default QMK is already 6KRO, so I'm wondering if this can just be removed altogether.

**Comment by drashna** [comment]
> What is the purpose of `USB_6KRO_ENABLE` anyway? By default QMK is already 6KRO, so I'm wondering if this can just be removed altogether.

It looks like it's handled a bit differently.

**Comment by tzarc** [comment]
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

**Comment by drashna** [comment]
This has a bunch of merge conflicts, and probably needs a rebase.

**Pull request closed without merging**
