### PR TITLE
Update build instructions and docker file to download submodules

### PR DESCRIPTION
**Pull request by metaflow**
Tried to follow instructions to build firmware for Whitefox kb and build failed as it cant find ChibiOS lib.

### CODE REVIEW

**Comment by drashna** [comment]
`make git-submodule` will do this, actually. 

https://github.com/qmk/qmk_firmware/blob/ce3adcd6e19ca2e3b537ab874487e9d022b8e88f/Makefile#L584-L586

**Comment by metaflow** [comment]
good point, @drashna , I will update PR

**Comment by metaflow** [comment]
It looks like docker image has to be updated as well. I will update this PR.

**Comment by drashna** [comment]
@metaflow would you mind updating this so we can get this merged in?

**Comment by metaflow** [comment]
Will do!

**Comment by metaflow** [comment]
Resolved conflicts and updated 'build_docker.sh' as well

**Comment by metaflow** [comment]
@drashna I don't see a button to merge this. Could you please do it?

**Comment by drashna** [comment]
That's normal. Only members/collaborators with write permission on the repo get it. 

And thanks!

**Comment by vomindoraan** [comment]
The changes this PR made to the dockerfile and build script are incorrect. `make clean` and `make git-submodule` should not be executed every time the container is run, as this slows down build times immensely. The submodules should already be in the directory when the image is built. CI enforces this for [official images](https://hub.docker.com/r/qmkfm/qmk_firmware), and you're supposed to clone the submodules ahead of time if you're building a custom image locally.

Furthermore, the change to the docs is unnecessary as well, as the guides instructs the user to use `git clone --recurse-submodules` to clone the repo, as can be seen [here](https://github.com/qmk/qmk_firmware/blob/master/docs/newbs_getting_started.md#set-up-qmk) and [here](https://github.com/qmk/qmk_firmware/blob/master/docs/getting_started_build_tools.md#git), which also clones the submodules.

Therefore, this PR should be reverted.

**Comment by metaflow** [comment]
> The changes this PR made to the dockerfile and build script are not correct. `make clean` and `make git-submodule` should not be executed every time the container is run, as this can slow down keymap build times immensely. Submodules should already be present in the directory when the image is built. CI enforces this for [official images](https://hub.docker.com/r/qmkfm/qmk_firmware), and you're supposed to have the submodules cloned ahead of time if you're building a custom image locally.
I have no issues with running container image multiple times as `make git-submodule` will work on your local directory.
> 
> Furthermore, the change to the docs is unnecessary as well, since the guides instructs the user to use `git clone --recurse-submodules` to clone the repo (as can be seen [here](https://github.com/qmk/qmk_firmware/blob/master/docs/newbs_getting_started.md#set-up-qmk) and [here](https://github.com/qmk/qmk_firmware/blob/master/docs/getting_started_build_tools.md#git)), which also clones the submodules.
That is listed under "windows 10" heading while should be applied on linux as well. I don't see why repeating this harms.

**Comment by vomindoraan** [comment]
> I have no issues with running container image multiple times as make git-submodule will work on your local directory.

As I said, it slows down the build since it runs `make git-submodule` every time you want to compile a keymap. Even worse is that it also runs `make clean` if you're running the image outside the build script. This clears all previous build artifacts from the Docker volume, meaning that everything has to be compiled again, even if you haven't changed anything. So it's hardly ideal.

We had this exact problem up until a couple of months ago, when the build script was added and the dockerfile updated to remove `make clean` from the `CMD`. This resulted in a significant speedup of build times when using Docker.

Keep in mind that `CMD` (or, equivalently, the command in `docker run`) is what's executed when you _run_ the container, not when you're building the image — and updating submodules is definitely something that should happen during the build, or, in our case, before it. Putting build steps into `CMD` is not in line with established Docker best practices (since it's inefficient and often redundant).

> That is listed under "windows 10" heading while should be applied on linux as well. I don't see why repeating this harms.

I have nothing against reiterating or reminding the user that submodules need to be cloned, but for now I'd like to get Docker builds back to a consistent, performant state — and a straight revert of this PR is the fastest/easiest way to do that.

If you have a suggestion on how I can improve the docs change instead of completely reverting it, feel free to add that as a suggestion to the revert PR (#5533).

It's also worth noting that the `--recurse-submodules` command is specified in several other places in the guide (including the very first "getting started" page). Presumably, readers of the guide will get to that first before they read up on build tools, at which point they will have already cloned the submodules. But mentioning it again wouldn't hurt.

**Comment by metaflow** [comment]
@vomindoraan 

> It's also worth noting that the --recurse-submodules command is specified in several other places in the guide (including the very first "getting started" page). Presumably, readers of the guide will get to that first before they read up on build tools, at which point they will have already cloned the submodules. But mentioning it again wouldn't hurt.

And yet I managed to get to the point of compilation without submodules reserved. Maybe documentation had been updated since that time and people don't have this issue anymore.

Ofc, feel free to revert this.

**Comment by vomindoraan** [comment]
I think the build system checks if your submodules are out of date when you run `make` (either directly or through Docker) and displays a message along the lines of "Your submodules are out of date, consider running make git-submodule".

**Pull request merged**
