### PR TITLE
fixed macOS "error writing to teensy" issue #6335

### PR DESCRIPTION
**Pull request by jamessa**
## Types of Changes

- [ ] Core
- [X] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* issue #6335 error writing to Teensy 2.0 on macOS Mojave

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by jamessa** [comment]
This is interesting that I have the same compile errors in master brach by `make ergodox_ez`.

**Comment by jamessa** [comment]
https://gist.github.com/jamessa/8e758422914b8a167d08051fcdf83359 my output here, looks like some ergodox layout is broken on master branch. How can I help on this?

**Comment by fauxpark** [comment]
I'm not sure I understand how enabling LTO fixes an issue with flashing...

**Comment by drashna** [comment]
Honestly, neither can I.

I also cannot reproduce the flash error.  I compiled and flashed the board without this issue, and without LTO.  

I suspect that LTO fixed the issue because it recompiled everything, rather than for anything it did to the image. 

Eg, you should try it without LTO, and run: 
```bash
make clean ergodox_ez:default:teensy
```

And see if that has the same issue.

**Comment by jamessa** [comment]
Just notice that my teensy 2.0 might be counterfeit. I need find other IC to test. Close for now. @fauxpark @drashna thank you for helping me ruling the possibility.

IMG_9273

**Comment by drashna** [comment]
Yup, that's counterfeit, alright. 

image

That's what a genuine looks like. 

But yours looks like one of these:
https://www.pjrc.com/teensy/counterfeit.html
image

RIP.  Sorry. :(

**Pull request closed without merging**
