### PR TITLE
Fix timer skew with a long WS2812 chain using the AVR bitbang driver

### PR DESCRIPTION
**Pull request by sigprof**
## Description

The AVR bitbang driver for WS2812 LEDs needs to disable interrupts when sending out the WS2812 bitstream.  If there are more than 33 LEDs in the chain, sending the bitstream takes more than 1 ms, and this may cause some Timer0 interrupts to be lost, therefore various timings in QMK may get skewed (tapping term will be longer than configured, LED animations will play slower than expected, ...).

Although trying to handle the timer interrupts normally is not possible without disrupting the bitstream, at least for the most common hardware configuration (ATmega32u4 running at 16 MHz) it is possible to squeeze some code to handle Timer0 compare flag bits into the bitbanging loop (at 16 MHz there is a step where 7 nop cycles are inserted for proper timings, and the timer handling code requires 5 cycles).  The added code counts the number of interrupt requests which were generated while interrupts were disabled, and then adds that number to `timer_count`, as if all those interrupts were serviced normally.

Currently the timer fixup code is enabled only for ATmega32u4; it should be possible to use it on other AVR chips after adjusting the `TIFRx` and `OCFxx` defines appropriately.

-----

I tested the code on XD87 HS with `RGBLED_NUM` increased to 105 (imagine a fullsize ISO keyboard with per-key WS2812-style LEDs); with this configuration sending the bitstream would take 3.15 ms.  I also added the following test code to the keymap:

```c
static bool esc_pressed = false;
static uint16_t esc_timer;

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case KC_ESC:
            if (record->event.pressed) {
                esc_pressed = true;
                esc_timer = timer_read();
            } else {
                esc_pressed = false;
            }
            break;
    }
    return true;
}

void matrix_scan_user(void) {
    if (esc_pressed) {
        if (timer_elapsed(esc_timer) >= 1000) {
            esc_pressed = false;
            unregister_code(KC_ESC);
        }
    }
}
```

This code should unregister the Esc key 1000 ms after it was pressed. However, when I also enabled the `RGBLIGHT_MODE_BREATHING + 3` animation without applying the change from this PR, the keyboard tester started showing the keypress duration of 1402…1405 ms, which is definitely wrong; the animation is also significantly slower than with the default number of LEDs. Turning the underglow off resulted in the normal 1000…1004 ms duration.

When the change from this PR is applied, the keyboard tester shows the same Esc keypress duration of 1000…1004 ms both with enabled and disabled animation, and the animation speed seems to be the same as it was with the default number of LEDs.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by sigprof** [comment]
Apparently there is a single keyboard in the repo — `handwired/promethium` — which has ATmega32u4 running at 8 MHz with a chain of 67 WS2812-style LEDs. The code in this PR cannot work with that keyboard, because at 8 MHz the bitbanging code has only 3 nop cycles in one of 3 possible places (and some timings are actually impossible to meet at 8 MHz, which triggers a bug which I tried to fix in a separate PR #9559). This is unfortunate, because that configuration actually needs the timer fixup (even with the ideal 1250 ns/bit sending the bitstream for 67 LEDs would take more than 2 ms, and the actual bit time for that config seems to be even larger).

However, it could be possible to fit the code into those 3 cycles by unrolling the loop and putting the additional instructions into the nop slots at different interations (only the last two subtraction instructions need to be next to each other, because the carry flag needs to be propagated between them). But doing this would complicate the code even further, and I would not be able to test it on that keyboard anyway.

**Comment by mtei** [comment]
To be honest, manipulating timers' registers in ws2812.c is not a good idea.

For example, you can add some APIs to the timer module in the following way:

```diff
diff --git a/tmk_core/common/timer.h b/tmk_core/common/timer.h
index 52bc1cc67..8ba728921 100644
--- a/tmk_core/common/timer.h
+++ b/tmk_core/common/timer.h
@@ -44,6 +44,10 @@ uint32_t timer_read32(void);
 uint16_t timer_elapsed(uint16_t last);
 uint32_t timer_elapsed32(uint32_t last);
 
+void     timer_interrupt_suspend(void);
+void     timer_interrupt_resume(void);
+void     timer_poll_timeup(void);
+
 // Utility functions to check if a future time has expired & autmatically handle time wrapping if checked / reset frequently (half of max value)
 #define timer_expired(current, future) (((uint16_t)current - (uint16_t)future) < 0x8000)
 #define timer_expired32(current, future) (((uint32_t)current - (uint32_t)future) < 0x80000000)
```
```diff
diff --git a/tmk_core/common/avr/timer.c b/tmk_core/common/avr/timer.c
index c2e6c6e08..25ad50373 100644
--- a/tmk_core/common/avr/timer.c
+++ b/tmk_core/common/avr/timer.c
@@ -68,6 +68,39 @@ void timer_init(void) {
 #endif
 }
 
+void timer_interrupt_suspend(void) {
+#if defined(__AVR_ATmega32A__)
+#error not yet
+#elif defined(__AVR_ATtiny85__)
+#error not yet
+#else
+    TIMSK0 &= ~_BV(OCIE0A);
+#endif
+}
+
+void timer_interrupt_resume(void) {
+#if defined(__AVR_ATmega32A__)
+#error not yet
+#elif defined(__AVR_ATtiny85__)
+#error not yet
+#else
+    TIMSK0 |= _BV(OCIE0A);
+#endif
+}
+
+void timer_poll_timeup(void) {
+#if defined(__AVR_ATmega32A__)
+#error not yet
+#elif defined(__AVR_ATtiny85__)
+#error not yet
+#else
+    if ( TIFR0 & _BV(OCF0A) ) {
+        timer_count++;
+        TIFR0 = _BV(OCF0A); // interrupt clear
+    }
+#endif
+}
+
 /** \brief timer clear
  *
  * FIXME: needs doc
```

And it looks good if you use the API in ws2812.c as follows:
```diff
diff --git a/drivers/avr/ws2812.c b/drivers/avr/ws2812.c
index dd2ef8991..4aac2d831 100644
--- a/drivers/avr/ws2812.c
+++ b/drivers/avr/ws2812.c
@@ -20,6 +20,7 @@
  * You should have received a copy of the GNU General Public License
  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
  */
+#include "timer.h"
 #include "ws2812.h"
 #include <avr/interrupt.h>
 #include <avr/io.h>
@@ -42,7 +43,37 @@ void ws2812_setleds(LED_TYPE *ledarray, uint16_t number_of_leds) {
     uint8_t masklo = ~(pinmask(RGB_DI_PIN)) & PORTx_ADDRESS(RGB_DI_PIN);
     uint8_t maskhi = pinmask(RGB_DI_PIN) | PORTx_ADDRESS(RGB_DI_PIN);
 
+#ifndef WS2812_DIVIDED_DRIVING
     ws2812_sendarray_mask((uint8_t *)ledarray, number_of_leds * sizeof(LED_TYPE), masklo, maskhi);
+#else
+    uint8_t sreg_prev;
+
+    sreg_prev = SREG;
+    cli();
+    timer_interrupt_suspend();
+
+#  if WS2812_DIVIDED_DRIVING == 2
+    ws2812_sendarray_mask((uint8_t *)ledarray,
+                          (number_of_leds/2) * sizeof(LED_TYPE), masklo, maskhi);
+    timer_poll_timeup();
+    ws2812_sendarray_mask((uint8_t *)(ledarray + number_of_leds/2),
+                          (number_of_leds - number_of_leds/2) * sizeof(LED_TYPE), masklo, maskhi);
+#  elif WS2812_DIVIDED_DRIVING == 3
+    ws2812_sendarray_mask((uint8_t *)ledarray,
+                          (number_of_leds/3) * sizeof(LED_TYPE), masklo, maskhi);
+    timer_poll_timeup();
+    ws2812_sendarray_mask((uint8_t *)(ledarray + number_of_leds/3),
+                          (number_of_leds/3) * sizeof(LED_TYPE), masklo, maskhi);
+    timer_poll_timeup();
+    ws2812_sendarray_mask((uint8_t *)(ledarray + number_of_leds/3*2),
+                          (number_of_leds - number_of_leds/3*2) * sizeof(LED_TYPE), masklo, maskhi);
+#  else
+    #error invalid WS2812_DIVIDED_DRIVING value
+#  endif
+    timer_interrupt_resume();
+    SREG = sreg_prev;
+
+#endif
 
     _delay_us(WS2812_TRST_US);
 }
```

**Comment by sigprof** [comment]
Yes, the API looks much cleaner than adding the assembly code directly to the WS2812 driver. However, using such API would most likely lead to violating the timing restrictions described in the official datasheet. E.g, the current WS8212B datasheet available from http://www.world-semi.com/Certifications/WS2812B.html shows the following values for various timings:

* `T0H` — 220…380 ns
* `T1H` — 580…1000 ns
* `T0L` — 580…1000 ns
* `T1L` — 580…1000 ns
* `RES` — >280 µs

The older version of the WS2812 datasheet available at https://cdn-shop.adafruit.com/datasheets/WS2812.pdf recommended slightly different timings:

* `T0H` — 350±150 (200…500) ns
* `T1H` — 700±150 (550…850) ns
* `T0L` — 800±150 (650…950) ns
* `T1L` — 600±150 (450…750) ns
* `RES` — >50 µs

The actual implementation at the moment (without this PR) compiles to this code for ATmega32u4 @ 16 MHz:

```
00002d46 <loop106>:
    2d46:       55 b9           out     0x05, r21       ; 1
    2d48:       00 00           nop                     ; 1
    2d4a:       00 c0           rjmp    .+0             ; 2
    2d4c:       67 ff           sbrs    r22, 7          ; 1 / 2
    2d4e:       45 b9           out     0x05, r20       ; 1 / 0
    2d50:       66 0f           add     r22, r22        ; 1
    2d52:       00 00           nop                     ; 1
    2d54:       00 c0           rjmp    .+0             ; 2
    2d56:       00 c0           rjmp    .+0             ; 2
    2d58:       00 c0           rjmp    .+0             ; 2
    2d5a:       45 b9           out     0x05, r20       ; 1
    2d5c:       00 c0           rjmp    .+0             ; 2
    2d5e:       7a 95           dec     r23             ; 1
    2d60:       91 f7           brne    .-28            ; 2
```

This gives the following timings within a byte:

* `T0H` — 5 cycles, 312.5 ns
* `T1H` — 14 cycles, 875 ns
* `T0L` — 15 cycles, 937.5 ns
* `T1L` — 6 cycles, 375 ns
* total bit time — 20 cycles, 1250 ns

Hmm, looks like this code already violates the official restrictions for `T1L` (and `T1H` as it was in the old version of the datasheet), but nobody noticed any problems with this… The potential problem is that adding extra code will increase `T0L` and `T1L`, and especially in the case of `T0L` might increase it beyond the datasheet limit. However, this might not matter if actual LEDs do not care about the actual value of `T0L` as long as it is below the reset detection threshold (which is significantly higher than other timings).

I could try to prepare and test the API implementation suggested by @mtei, but I have only a couple of PCBs with ATmega32u4 @ 16 MHz and “new” WS2812-style LEDs (with the reset threshold around 230 µs, as I found out when testing PR #9302).

**Comment by mtei** [comment]
I think `RES -- >280us` or `RES -- >50us` means that spacing of at least less than 50us is allowed at byte boundaries.

**Comment by sigprof** [comment]
> I think `RES -- >280us` or `RES -- >50us` means that spacing of at least less than 50us is allowed at byte boundaries.

Either at byte, or, which is even more likely, at LED data block boundaries (3 bytes for the usual RGB LEDs, or 4 bytes for RGBW LEDs, which I don't have at all). However, this is not explicitly written anywhere in the datasheet, so we could only guess and experiment with some hardware that we have available.

**Comment by mtei** [comment]
For reference, I observed the behavior of `qmk_firmware/drivers/avr/ws2812.c` on January 14 of this year on an oscilloscope.  The results of measuring the spacing of the byte boundaries were as follows.

IMG_2982

**Comment by mtei** [comment]
FYI:
I also tried to implement it to get rid of the extra spacing on byte boundaries.

```diff
commit 988fddf648e0696a5b0ac6d9eb390e357e90c711
Author: mtei <2170248+mtei@users.noreply.github.com>
Date:   Thu Jan 16 17:49:00 2020

    Eliminate extra time on byte boundaries in ws2812.c output

diff --git a/drivers/avr/ws2812.c b/drivers/avr/ws2812.c
index 82d985c20..806b02ae0 100644
--- a/drivers/avr/ws2812.c
+++ b/drivers/avr/ws2812.c
@@ -129,12 +129,12 @@ void inline ws2812_sendarray_mask(uint8_t *data, uint16_t datlen, uint8_t maskhi
     sreg_prev = SREG;
     cli();
 
-    while (datlen--) {
-        curbyte = (*data++);
-
-        asm volatile("       ldi   %0,8  \n\t"
-                     "loop%=:            \n\t"
-                     "       out   %2,%3 \n\t"  //  '1' [01] '0' [01] - re
+    if (datlen>0) {
+        curbyte = *data++;
+        asm volatile("       ldi   %0,7     \n\t"
+                     "byte_loop%=:          \n\t"
+                     "bit_loop%=:           \n\t"
+                     "       out   %2,%3    \n\t"  //  '1' [01] '0' [01] - re
 #if (w1_nops & 1)
                      w_nop1
 #endif
@@ -186,9 +186,67 @@ void inline ws2812_sendarray_mask(uint8_t *data, uint16_t datlen, uint8_t maskhi
 #endif
 
                      "       dec   %0    \n\t"  //  '1' [+2] '0' [+2]
-                     "       brne  loop%=\n\t"  //  '1' [+3] '0' [+4]
+                     "       brne  bit_loop%=\n\t"  //  '1' [+3] '0' [+4]
+                     "last_bit%=:           \n\t"
+                     "       ldi   %0,7     \n\t"
+                     "       out   %2,%3    \n\t"  //  '1' [01] '0' [01] - re
+#if (w1_nops & 1)
+                     w_nop1
+#endif
+#if (w1_nops & 2)
+                         w_nop2
+#endif
+#if (w1_nops & 4)
+                             w_nop4
+#endif
+#if (w1_nops & 8)
+                                 w_nop8
+#endif
+#if (w1_nops & 16)
+                                     w_nop16
+#endif
+                     "       sbrs  %1,7  \n\t"  //  '1' [03] '0' [02]
+                     "       out   %2,%4 \n\t"  //  '1' [--] '0' [03] - fe-low
+                     "       ld    %1,Z+ \n\t"
+#if ((w2_nops-1) & 1)
+                     w_nop1
+#endif
+#if ((w2_nops-1) & 2)
+                         w_nop2
+#endif
+#if ((w2_nops-1) & 4)
+                             w_nop4
+#endif
+#if ((w2_nops-1) & 8)
+                                 w_nop8
+#endif
+#if ((w2_nops-1) & 16)
+                                     w_nop16
+#endif
+                     "       out   %2,%4 \n\t"  //  '1' [+1] '0' [+1] - fe-high
+#if ((w3_nops-1) & 1)
+                     w_nop1
+#endif
+#if ((w3_nops-1) & 2)
+                         w_nop2
+#endif
+#if ((w3_nops-1) & 4)
+                             w_nop4
+#endif
+#if ((w3_nops-1) & 8)
+                                 w_nop8
+#endif
+#if ((w3_nops-1) & 16)
+                                     w_nop16
+#endif
+
+                     "       subi  r26,1              \n\t"
+                     "       sbc   r27,__zero_reg__   \n\t"
+                     "       brne  byte_loop%=        \n\t"
                      : "=&d"(ctr)
-                     : "r"(curbyte), "I"(_SFR_IO_ADDR(_SFR_IO8((RGB_DI_PIN >> 4) + 2))), "r"(maskhi), "r"(masklo));
+                     : "r"(curbyte), "I"(_SFR_IO_ADDR(_SFR_IO8((RGB_DI_PIN >> 4) + 2))),
+                       "r"(maskhi), "r"(masklo),
+                       "z"(data), "x"(datlen));
     }
 
     SREG = sreg_prev;
```

IMG_2983

**Comment by mtei** [comment]
FYI:
https://cpldcpu.wordpress.com/2014/01/14/light_ws2812-library-v2-0-part-i-understanding-the-ws2812/

**Comment by sigprof** [comment]
Thanks for that information; 9 µs is 144 cycles at 16 MHz, or 72 cycles at 8 MHz — not very much, but it should be possible to fit the timer update code there. Although there are no measurements of T<sub>RESET</sub> on the [page about SK6812](https://cpldcpu.wordpress.com/2016/03/09/the-sk6812-another-intelligent-rgb-led/), so even those 9 µs might not be safe in practice.

**Comment by drashna** [comment]
Has this been tested with RGBW LEDs too?

**Comment by sigprof** [comment]
I don't have any RGBW LEDs, and no “old” WS2812 LEDs (with the reset threshold of 9 µs) or SK6812 LEDs either.

BTW, another thing which could benefit from polling inside the WS2812 bitbang loop is the `BACKLIGHT_PWM_TIMER` code; this part I can test, but my XD87 HS PCB has “new” WS2812 LEDs, so I might not notice that other LED types with more strict timing requirements have issues.

**Comment by drashna** [comment]
> I don't have any RGBW LEDs, and no “old” WS2812 LEDs (with the reset threshold of 9 µs) or SK6812 LEDs either.

I would prefer that this be tested as well.  I know that adafruit sells a simple 8x LED board (which is what I use for testing RGBW).  

> BTW, another thing which could benefit from polling inside the WS2812 bitbang loop is the `BACKLIGHT_PWM_TIMER` code; this part I can test, but my XD87 HS PCB has “new” WS2812 LEDs, so I might not notice that other LED types with more strict timing requirements have issues.

Actually, if you look at the legacy code, RGB Light used PWM.   That said, I would would say that doing this should be part of a `ws2812_pwm` driver, like we have for chibiOS.

**Comment by sigprof** [comment]
>  I know that adafruit sells a simple 8x LED board (which is what I use for testing RGBW).

I have never been able to see anything except “Error 1020” from adafruit.com, so apparently they don't want to do any business with my region. Maybe I could find something usable on AliExpress.

> Actually, if you look at the legacy code, RGB Light used PWM. That said, I would would say that doing this should be part of a `ws2812_pwm` driver, like we have for chibiOS.

I'm not sure what “legacy code” do you mean, but the `ws2812_pwm` driver has nothing to do with what I wrote — AVR does not have the hardware which would be needed for that.

The `BACKLIGHT_PWM_TIMER` code that I wrote about is for a plain single-color LED backlight, which should be connected to a hardware PWM pin if the board was designed correctly. Unfortunately, there is, e.g., the whole series of XD* keyboards “designed by Xiudi” sold by KPrepublic, where the backlight is connected to a pin which does not support hardware PWM. The code in `quantum/backlight/backlight_avr.c` has support for such hardware configurations — if the configured `BACKLIGHT_PIN` does not support hardware PWM, the code sets up a hardware timer and toggles the backlight pin from the timer interrupt handlers. However, any other code which disables interrupts for a relatively long time will then interfere with that emulated PWM code, causing the backlight to flicker. I was thinking about the possibility to check for pending timer interrupts in the WS2812 loop, which could make that flicker less noticeable, but would violate the official WS2812 datasheet.

**Comment by drashna** [comment]
This has merge conflicts

**Comment by tzarc** [comment]
At this point, shall we just get this in and treat other issues as separate issues? Been open for long enough.

**Comment by tzarc** [comment]
If we can get the conflicts resolved, I'll merge it. Sat for too long.

**Comment by mtei** [comment]
If someone approves of this, I won't object strongly. But I am not inclined to agree with manipulating the timer in this file as I already wrote above.

**Comment by tzarc** [comment]
Deferring again.

**Comment by tzarc** [comment]
Cleaning up PRs, feel free to reopen if we want to make some progress.

**Pull request closed without merging**
