### PR TITLE
Introducing a flexible build environment, especially improving STM32 builds

### PR DESCRIPTION
**Pull request by elagil**
## Description

This aims to fix https://github.com/qmk/qmk_firmware/issues/16534.

### Improved `mcu_selection.mk` for STM32
This PR introduces a separate `mcu_selecion_stm32.mk`, just for STM32 processors. It is loaded within `mcu_selection.mk` and requires much less manual work for adding support for new chips. Find it in [`builddefs/mcu_selection_stm32.mk`](https://github.com/elagil/qmk_firmware/blob/stm32_flexible_build_selection/builddefs/mcu_selection_stm32.mk).

### Update all keyboards to specific processor models
I updated all affected boards (using STM32) with a specific processor variant. 

For the processor variant, I selected the one, which is used as the default model in the current firmware, so everything builds just like before.

### The new `ProcessorFactory`
This PR introduces a new `ProcessorFactory`, which replaces the old lists of supported chips. It assembles the list of supported processors by itself when it is provided with the corresponding information. For that, it uses the additional `Processor` class. See [`lib/python/qmk/processors.py`](https://github.com/elagil/qmk_firmware/blob/stm32_flexible_build_selection/lib/python/qmk/processors.py).

### Building
I **tested all boards** with their default keymap with

```
make all:default
```

**all of them build fine**. No errors were reported. See the [build log here](https://gist.github.com/elagil/258af8f896462c93527698b2e4507de3).

### `new_keyboard` CLI
The `new_keyboard` CLI was adjusted as well, now presenting a list of all supported processors and memory configuration suffixes:

<details>
<summary>Output of 'qmk new-keyboard'</summary>

```
Ψ Generating a new QMK keyboard directory

Name Your Keyboard Project
For more infomation, see:
https://docs.qmk.fm/#/hardware_keyboard_guidelines?id=naming-your-keyboardproject

Keyboard Name? 0000

Attribution
Used for maintainer, copyright, etc

Your GitHub Username?  [elagil] 

More Attribution
Used for maintainer, copyright, etc

Your Real Name?  [elagil] 

Pick Base Layout
As a starting point, one of the common layouts can be used to bootstrap the process

Default Layout? 
        1. 60_abnt2
        2. 60_ansi
        3. 60_ansi_arrow
        4. 60_hhkb
        5. 60_iso
        6. 64_ansi
        7. 64_iso
        8. 65_ansi
        9. 65_iso
        10. 66_ansi
        11. 66_iso
        12. 68_ansi
        13. 68_iso
        14. 75_ansi
        15. 75_iso
        16. 96_ansi
        17. 96_iso
        18. alice
        19. ergodox
        20. fullsize_ansi
        21. fullsize_iso
        22. numpad_4x4
        23. numpad_5x4
        24. numpad_5x6
        25. numpad_6x4
        26. numpad_6x5
        27. ortho_1x1
        28. ortho_2x3
        29. ortho_2x6
        30. ortho_3x10
        31. ortho_4x10
        32. ortho_4x12
        33. ortho_4x16
        34. ortho_4x4
        35. ortho_4x6
        36. ortho_5x10
        37. ortho_5x12
        38. ortho_5x14
        39. ortho_5x15
        40. ortho_5x4
        41. ortho_5x5
        42. ortho_6x4
        43. planck_mit
        44. split_3x5_2
        45. split_3x5_3
        46. split_3x6_3
        47. tkl_ansi
        48. tkl_iso
        49. tkl_nofrow_ansi
        50. tkl_nofrow_iso
        51. none of the above
Please enter your choice:  [51] 1

What Powers Your Project
For more infomation, see:
https://docs.qmk.fm/#/compatible_microcontrollers

MCU? 
        1. MKL26Z64
        2. MK20DX128
        3. MK20DX256
        4. MK66FX1M0
        5. STM32F042x6
        6. STM32F072xB
        7. STM32F103x8
        8. STM32F103xB
        9. STM32F103xD
        10. STM32F103xE
        11. STM32F103xG
        12. STM32F303x8
        13. STM32F303xC
        14. STM32F303xE
        15. STM32F401xC
        16. STM32F401xE
        17. STM32F405xG
        18. STM32F407xE
        19. STM32F407xG
        20. STM32F411xC
        21. STM32F411xE
        22. STM32F446xC
        23. STM32F446xE
        24. STM32G431xB
        25. STM32G474xE
        26. STM32L072x8
        27. STM32L072xB
        28. STM32L072xZ
        29. STM32L073x8
        30. STM32L073xB
        31. STM32L073xZ
        32. STM32L412xB
        33. STM32L412xC
        34. STM32L422xB
        35. STM32L422xC
        36. STM32L432xB
        37. STM32L432xC
        38. STM32L433xB
        39. STM32L433xC
        40. STM32L442xB
        41. STM32L442xC
        42. STM32L443xB
        43. STM32L443xC
        44. GD32VF103
        45. WB32F3G71
        46. at90usb162
        47. atmega16u2
        48. atmega32u2
        49. atmega32u4
        50. at90usb646
        51. at90usb647
        52. at90usb1286
        53. at90usb1287
        54. atmega32a
        55. atmega328p
        56. atmega328
        57. attiny85
Please enter your choice:  [49] 24
Ψ Created a new keyboard called 0000.
Ψ To start working on things, `cd` into keyboards/0000,
Ψ or open the directory in your preferred text editor.
Ψ And build with qmk compile -kb 0000 -km default.
```

</details>

### Further info
For the moment, I removed the check against `keyboard.jsonschema` and do all checking in Python directly. I find it sensible to only check for compatible processors in a single place.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/qmk/qmk_firmware/issues/16534

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation: Add more supported processors
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
At this point, perhaps we should discuss whether or not we should be _generating_ the ldscripts. @fauxpark what do you think?

As far as I can tell the majority of the ones used for ChibiOS are identical, with the only things changing being the flash size, the ram size, and if we've got a different offset for placing the resulting binary (custom bootloader etc.) -- the rest _should_ be basically common between all of them.

**Comment by tzarc** [comment]
I'd suggest putting this on hold to some degree until discussion occurs on #16534 -- if we go down a specific route it makes little sense making a whole bunch of changes only to find out that it's irrelevant after discussion.

**Comment by elagil** [comment]
I modified the `new_keyboard` CLI to work with the new `ProcessorFactory` in https://github.com/qmk/qmk_firmware/pull/16536/commits/d39e8212f9e47f6c6d0d0c6ed3bb3a78179b42e8. Here is how the new list of supported processors looks: [Example](https://gist.github.com/elagil/8f78e1c144ff9a00c68a1d565375906e).

Currently, I test build all keyboards with their default keymap, so that I can catch any errors.

**Comment by elagil** [comment]
> if we go down a specific route it makes little sense making a whole bunch of changes only to find out that it's irrelevant after discussion

Yes, but I find it easier to discuss, when you have some code to look at. In this PR I will just implement some suggested changes as a basis for improvement.

**Comment by tzarc** [comment]
Exempting this from stalebot processing -- we want to get something along these lines in, eventually.

**Pull request closed without merging**
