### PR TITLE
fix #12673

### LINKED ISSUE #12673: `last_hit_buffer` in `quantum/rgb_matrix.c` does not properly maintain counts if a custom `rgb_matrix_map_row_column_to_led_kb` is defined that returns nonzero
https://github.com/qmk/qmk_firmware/blob/8f5cc8d762db8a9a4ce3f41e4b66a8602f2da6f0/quantum/rgb_matrix.c#L233

should read `last_hit_buffer.count = LED_HITS_TO_REMEMBER - led_count;`, so that after

https://github.com/qmk/qmk_firmware/blob/8f5cc8d762db8a9a4ce3f41e4b66a8602f2da6f0/quantum/rgb_matrix.c#L242

that is executed `led_count` times, `last_hit_buffer.count` will be equal to `LED_HITS_TO_REMEMBER`

Present behavior:
the `last_hit_buffer` may remember less and less keys pressed and eventually stop remembering new keypresses if a custom `rgb_matrix_map_row_column_to_led_kb` is defined returning nonzero, causing problems with reactive RGB matrix effects with stale keypresses (older than the last `LED_HITS_TO_REMEMBER` keypresses) being remembered.

Expected behavior:
the `last_hit_buffer` should not have amnesia and always be able to maintain the last `LED_HITS_TO_REMEMBER` keypresses as long as `rgb_matrix_map_row_column_to_led_kb` always returns a value strictly less than `LED_HITS_TO_REMEMBER` (so that `rgb_matrix_map_row_column_to_led` always returns a value less then or equal to `LED_HITS_TO_REMEMBER`).

### PR DESCRIPTION
**Pull request by jhanschoo**
## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #12673

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

Failures when running `make all` don't seem to be related to my change. Note that I came across this bug while reading the source learning to implement a custom RGB matrix effect, so I might be mistaken and any input from maintainers more experienced is very welcome.

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by fauxpark — CHANGES_REQUESTED** [review]
Should also be done for LED Matrix.

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
This has some merge conflicts that need resolving.

**Comment by jhanschoo** [comment]
bump @drashna @fauxpark

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
