### PR TITLE
Add a layout to support tsangan bottom row with split bs and rshift

### PR DESCRIPTION
**Pull request by cdarwin**
As the title says. I couldn't find a reference to this layout anywhere else in the repo. I think this is the correct place for it.

### CODE REVIEW

**Comment by drashna** [comment]
This should go in `layouts/default/`, actually.

**Comment by cdarwin** [comment]
Updated

**Comment by noroadsleft** [comment]
It's nitpicky, but I'd prefer if this were named `LAYOUT_60_ansi_tsangan_split_bs_rshift` rather than `60_ansi_split_bs_rshift_tsangan`. Reasoning being I'd consider this a variant of the Tsangan variant of 60_ansi, rather than it being a Tsangan variant of the Split Backspace and Right Shift variant of 60_ansi, if that makes sense.

**Comment by cdarwin** [comment]
I absolutely agree!

**Comment by mechmerlin** [comment]
This is starting to sound like the naming scheme for DBZ, Super Saiyan God Super Saiyan.

**Comment by cdarwin** [comment]
I don't have write access on the repo so if someone wants to merge in these changes that would be rad

**Comment by mechmerlin** [comment]
> I don't have write access on the repo so if someone wants to merge in these changes that would be rad

Only collaborators/owners of QMK can merge changes in. Depending on availability and what we ask to change, it can take us anywhere from a few hours to a few days. This looks good to me though =)

**Pull request merged**
