### PR TITLE
Fix out of bound OLED font access

### PR DESCRIPTION
**Pull request by kitlaan**
## Description

The default font is 1344 bytes, or a total of 224 glyphs (each 6-bytes wide).
OLED_FONT_END defaults to 224, which if used will then index off the end of
the font array. So either the documentation or code is wrong.

Instead of figuring out the rewording of the documentation, just change
the OLED_FONT_END default value to 223, to match the documentation and code.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by kitlaan** [comment]
As an aside... the default oled font has a bunch of trailing empty glyphs (25 of them). So both the font array and define could be reduced even further if someone wants some flash savings (possibly without any breaking changes). The array would then be 1200 bytes in length, and font would have last char of 199... if I maths properly.

**Comment by drashna** [comment]
@XScorpion2 Comments, thoughts, etc?

**Comment by XScorpion2** [comment]
Ya, this is an appropriate change. I implemented end originally like a length value, but used it as last index value instead.

**Comment by zvecr** [comment]
Thanks all!

**Pull request merged**
