### PR TITLE
Fixing Ergodox_EZ rgb_led initialization

### PR DESCRIPTION
**Pull request by XScorpion2**
Fixing the rgb_led initialization to use the correct row / col & x / y offsets for each LED.

## Description

Ergodox EZ Glow now works correctly with key reactive rgb matrix

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
I've tested this already, and can verify that it works.  

@ezuk Just wanted to make sure that you've signed off on this, before it gets merged.

**Comment by ezuk** [comment]
Thank you, @drashna! @fdidron and @jackhumbert, thoughts?

**Comment by XScorpion2** [comment]
11m approval from the man himself.

**Comment by drashna** [comment]
Thanks!

**Comment by alecgeatches** [comment]
Very excited to have reactive animations working on the Ergodox EZ Glow, thank you for addressing this @XScorpion2. I'm having trouble getting the reactive animations to work with these changes. I recompiled a freshly pulled master (which has this change) and added

```c
#define RGB_MATRIX_KEYREACTIVE_ENABLED
```

to the *config.h* file for my keymap and built/uploaded. When I try cycling through the reactive matrix effects, I see that they're active but keypresses aren't causing any reactive effects. For the majority of the reactive effects, I'm only seeing a unlit keyboard, and none of them are reactive. Is there something else I need to do in order to get the reactive animations working?

I also tried the build source [taken directly from the EZ configurator](https://configure.ergodox-ez.com/layouts/nXLW/latest/0) and adding the same `RGB_MATRIX_KEYREACTIVE_ENABLED` define to *config.h*, but that has the same effect of inactive reactive effects. Any idea why these aren't working?

Thank you!

**Comment by XScorpion2** [comment]
@alecgeatches wrong define, that's an internal define. You want to use RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES

**Pull request merged**
