### PR TITLE
Sleep until USB port becomes writable before running avrdude

### PR DESCRIPTION
**Pull request by datagrok**
## Description

Currently, running with :avrdude as a target will monitor /dev/tty* for the appearance of a new device, then sleep for one second, then launch avrdude to flash the keyboard.

For reasons that I haven't yet determined, that one-second sleep is insufficient on my system. `/dev/ttyACM0` appears with root:root ownership, and it takes udev a good 2.5 seconds or so to change its permissions to root:dialout, giving my normal user write access. This causes avrdude (and make) to exit with an error most of the time:

```
avrdude: ser_open(): can't open device "/dev/ttyACM0": Permission denied

avrdude done.  Thank you.

make[1]: *** [tmk_core/avr.mk:228: avrdude] Error 1
Make finished with errors
make: *** [Makefile:551: mitosis:datagrok:avrdude] Error 1
```

To account for this I have replaced the 1-second sleep with a small loop, similar to the other, to wait for the device to become writable. This seems to successfully resolve the problem, at least on my Debian Linux machine.

If there is a known fix that will make my udev rules do their thing faster, I'm eager to hear about it.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

None that I am aware of.

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
This breaks `:avrdude` on MSYS2 (Windows), as it never "becomes writable". 

It looks like we need to check the OS before calling this routine.

**Comment by drashna** [comment]
Also, `avrdude-loop` may work instead

**Comment by datagrok** [comment]
@drashna I resurrected the `sleep 1`, moving it into the conditional that checks for MSYS, with my waiting-for-writable loop in its else block. Still accomplishes what I want on my system. Does this unbreak `:avrdude` on Windows? (I don't have a Windows box to test.)

**Comment by yanfali** [comment]
needs testing on macOS too

**Comment by drashna** [comment]
Confirmed working on MSYS2, now.  Thanks!!

**Pull request merged**
