### PR TITLE
fix Helen 80 matrix mapping

### PR DESCRIPTION
**Pull request by LSChyi**
Fix matrix macro mapping in Helen 80.

## Description

Fix macro expand of `LAYOUT_tkl_ansi` in Helen 80
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by spidey3 — APPROVED** [review]
Approved, but perhaps @yj7272098 may want to comment before this is merged...

**Review by noroadsleft — APPROVED** [review]
Looks good to me.

**Comment by noroadsleft** [comment]
[Play Keyboard's site](https://playkeyboard.tw/products/helen-80-%E9%8D%B5%E7%9B%A4%E5%A5%97%E4%BB%B6) includes a link to a [Google Drive folder](https://drive.google.com/drive/folders/1UZto_LSVDSALjz5JC6lLs4gm3AwEGXY1) (through bit.ly) that includes the VIA-format JSON file. Checked it out, and according to that JSON file, the matrix submitted to QMK was wrong.

image

**Comment by noroadsleft** [comment]
Thanks!

**Comment by LSChyi** [comment]
Thank you! @yj7272098 and I are friends and he is not familiar with git and c language, so I helped him to fix some issue.

**Pull request merged**
