### PR TITLE
add a way to have only one oled display on split kbs

### PR DESCRIPTION
**Pull request by oresk**
When there is only one display on split keyboards,
there is a lag on the half that does not have the display.
That produces a lot of frustration especially for new,
less experienced users.

This commit allows to disable the display on one side,
without disabling the oled driver completely.

By defining OLED_NO_DISPLAY_ON_MASTER or
OLED_NO_DISPLAY_ON_SLAVE we disable the oled display.

This closes https://github.com/qmk/qmk_firmware/issues/9060

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR
https://github.com/qmk/qmk_firmware/issues/9060
* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
I'm not sure I'm a fan of this.  

IIRC, @zvecr may have had a solution that prevents the lag (which can/will happen on both halves, IIRC), overall.  

Additionally, boards like the ErgoDox EZ actually has some handling that will check for i2c errors, and prevent it from "spamming" i2c commands when it can't find the device.   I think that may be a better way to handle this, rather than defines.  
Especially, as ... what if you use EE_HANDS with a split, and change what side is plugged in?  Then these settings are now useless.

**Comment by oresk** [comment]
> I'm not sure I'm a fan of this.
> 
> IIRC, @zvecr may have had a solution that prevents the lag (which can/will happen on both halves, IIRC), overall.
> 
> Additionally, boards like the ErgoDox EZ actually has some handling that will check for i2c errors, and prevent it from "spamming" i2c commands when it can't find the device. I think that may be a better way to handle this, rather than defines.
> Especially, as ... what if you use EE_HANDS with a split, and change what side is plugged in? Then these settings are now useless.

Could you point me in the direction of the EZ code that handles the i2c errors (I'm still finding my way round the project), for sure that code should be general and a part of the core, right?

**Comment by drashna** [comment]
> Could you point me in the direction of the EZ code that handles the i2c errors (I'm still finding my way round the project), for sure that code should be general and a part of the core, right?

Not a problem, at all!  

https://github.com/qmk/qmk_firmware/blob/c9eaf1ac2ba0e9114343815432de524062f4c94f/keyboards/ergodox_ez/matrix.c#L113-L129

And if you notice, basically every time the ergodox's matrix reads from i2c it updates `mcp23018_status` (which is an i2c port expanded).

**Comment by tzarc** [comment]
Could this take into account the new function added in #10382 ?

**Comment by drashna** [comment]
Sorry for the delay! 
The ErgoDox EZ saves the status for all of the i2c calls, and if there is an error, it has to run a certain number of loops (255, by default) before it tries to re-init the controller.   
https://github.com/qmk/qmk_firmware/blob/6ad813e811bd1889f8e45afcb671b118ebf5f51d/keyboards/ergodox_ez/matrix.c#L82-L96

Also, if there is an error, it avoids running scans until the status has been reset. 

https://github.com/qmk/qmk_firmware/blob/6ad813e811bd1889f8e45afcb671b118ebf5f51d/keyboards/ergodox_ez/matrix.c#L143-L144


This prevents it from trying to run the i2c commands every cycle, which can have a 10-100ms timeout (which is what causes the slowdown).

**Comment by drashna** [comment]
This should be resolved by #11129

**Pull request closed without merging**
