### PR TITLE
GEN ONE Eclipse_65 keyboard addition

### PR DESCRIPTION
**Pull request by rojasa1990**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by rojasa1990 — COMMENTED** [review]
This is not the correct folder where I need to add. I uploaded file in a more recent time. Deny this addition and go the more recent addition.

**Review by zvecr — CHANGES_REQUESTED** [review]
> Deny this addition and go the more recent addition

You will have to fix that up your end, as this PR cannot be merged with the files dupicated at the root level.

**Comment by rojasa1990** [comment]
> > Deny this addition and go the more recent addition
> 
> You will have to fix that up your end, as this PR cannot be merged with the files dupicated at the root level.

Do I have to erase all the forked files that are on my copy of QMK_Firmware master folder that I downloaded? Erase all files except for mine?

**Review by rojasa1990 — COMMENTED** [review]
Changes Approved

**Review by rojasa1990 — COMMENTED** [review]
Made Changes for review

**Review by rojasa1990 — COMMENTED** [review]
Made changes. Why does the continuous integration (travis-ci) check all the keyboard files and not just mine?

**Comment by rojasa1990** [comment]
> > Deny this addition and go the more recent addition
> 
> You will have to fix that up your end, as this PR cannot be merged with the files dupicated at the root level.

I have changed the errors specified. Any help during this pull request would be gladly accept, this is my first pull request and new to github. Thanks.

**Pull request closed without merging**
