### PR TITLE
Allow for oled_init_kb and oled_task_kb.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

Adds support for oled_init_kb and oled_task_kb, matching the standard _kb -> _user overridable function chains.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
@XScorpion2

**Comment by XScorpion2** [comment]
Task changes look good and make sense, Init changes I don't think will actually work out how you are expecting. 

The entire purpose of the init function is to just return a single rotation value, so how would this be implemented at the keyboard and user level? At the keyboard level, you have no way of knowing if the user init was implemented or the default user init function and if the return value from that is one that is a value you can change, or one the user really wanted.

**Comment by tzarc** [comment]
It's more that in some cases the OLED orientation is keyboard-specific rather than user-specific.
The board itself may have a "preferred" orientation, but still allow for the user to override it should they be Australian and want it upside-down ;)

**Comment by XScorpion2** [comment]
Maybe it's just my dislike of implementing something just because it's a pattern. Especially in this case as there is nothing useful gained from this pattern that cannot already be done now:

e.g. in mykeyboard.c:

```
__attribute__ ((weak))
oled_rotation_t oled_init(oled_rotation_t rotation) {
     // We're vertical by default...
    return OLED_ROTATION_90;
}
```

and in keymap.c:

```
oled_rotation_t oled_init(oled_rotation_t rotation) {
    // ...yeah, nah, I'm aussie, mate.
    return OLED_ROTATION_270;
}
```

**Comment by tzarc** [comment]
As an aside, what are the rules when there are two weakly-bound functions with no non-weak override?

If there’s nothing in the keymap, can the board reliably override what’s in the normal oled_driver.c implementation?

Guess I should go looking in the gcc docs...

**Comment by drashna** [comment]
In this case, I agree with @XScorpion2 here.   There are a number of reasons to use the `_kb` methods, but ... for this, I don't think that there is a good reason for doing so here.   

Specifically, it a lot of cases, there are things that you can want to do on a keyboard and user level.  Macros is a very good example.  

However, for here, ..... at best, you'd want a place holder function for the oled, as you'd need to override the functionality for user keymaps, rather than expand functionality (since you can't really expand functionality).  

So, IMO, the best coarse of action may be to set the functions in the keyboard.c file, but set them "weakly", so they can be overwritten by the keymap file.

**Pull request closed without merging**
