### PR TITLE
fix logic and move PLOOPY_DRAGSCROLL_MOMENTARY to config.h

### PR DESCRIPTION
**Pull request by albinger**
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — COMMENTED** [review]
I'm not sure what you're trying to accomplish here.  This isn't fixing the logic.  Instead, it's moving it out of pre-processors and moving it into C code, which will increase the firmware size, and memory usage.

**Comment by albinger** [comment]
the code as currently written checks to see if PLOOPY_SOMETHING is defined.  If not defined it defines it.  THen it checks to see if PLOOPY_SOMETHING is defined lower in the code.  Not surprisingly it IS always defined.

If you have a cool way to undefine PLOOPY_SOMETHING then please add it to the comments otherwise I submit that working code is better than cool preprocessor tricks that don't work.

**Comment by drashna** [comment]
Ah, sorry, I missed the context, as the other ploopy boards are set up differently, and handle it properly. I've been meaning to consolidate all of the ploopy code (and that may be the best option here, long term)

**Comment by albinger** [comment]
This seems to be more in the spirit of the pre-processor.  I'm not a "real coder" but this is likely more of what you were looking for.

**Pull request closed without merging**
