### PR TITLE
Update config.h

### PR DESCRIPTION
**Pull request by jotix**
arduino pro micro pinout change

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Just a heads up, D7 won't use hardware PWM, which may not be optimal.  
But if that's fine with you...

Also, Travis CI failures are unrelated to this change, and are due to community layouts.

**Comment by jotix** [comment]
i am absolute noob in arduino things, i made the connection follow the image in the link:
https://i.imgur.com/ZNlHd7p.jpg
the pinout in the image indicates that D7 is a PWM pin.
What do you think, also I have free the arduino 7 (PE7) pin.
Thank you!

**Comment by drashna** [comment]
Personally, I prefer this image:
https://cdn.sparkfun.com/datasheets/Dev/Arduino/Boards/ProMicro16MHzv1.pdf

However, according to the code, only the B pins support hardware PWM for backlighting.  The other pins may support PWM, but I think it needs the 16 Bit PWM pins to properly work.  However, I'm not sure about that. 
https://docs.qmk.fm/#/feature_backlight?id=caveats

You can use any pin, though.  It's just a matter of what you give up.  And without the hardware PWM support, you give up the backlight breathing, it looks like.

**Comment by jotix** [comment]
ok, thank you for the information,
I make the necesary changes to the pinout

**Comment by jotix** [comment]
I think now is ready

**Pull request closed without merging**
