### PR TITLE
[Keyboard] Move Hillside out of handwired

### PR DESCRIPTION
**Pull request by mmccoyd**
## Description

Move Hillside keyboard family out of handwired as suggested by keyboard-magpie.

Context: Hillside started in handwired, despite being PCB based, based on an old organization standard for non-commercial boards.

~The keymaps included by user manna-harbour_miryoku break because they still include RESET.~

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by keyboard-magpie — APPROVED** [review]

**Comment by mmccoyd** [comment]
Are the remaining CI fails a CI bug? It builds fine locally. Discord suggests it still has issues.

**Comment by drashna** [comment]
Yeah, there is some misconfiguration here, as it shouldn't be attempting to compile "keymaps", as if it was a keymap folder.

**Comment by mmccoyd** [comment]
> Yeah, there is some misconfiguration here, as it shouldn't be attempting to compile "keymaps", as if it was a keymap folder.

That does not seem something I can fix, if the QMK CI is reporting issues that do not exist.

**Comment by sigprof** [comment]
The problem is this part of the CI code:
https://github.com/qmk/qmk_ci_executor/blob/88605f9607f8554535c8b8d168f9797ce950b3a0/runner/app/ci_worker.py#L288-L300
together with the presence of `keyboards/hillside/48/keymaps/json2hill48.py` in this PR.

The CI code mistakenly parses the `keyboards/hillside/48/keymaps/json2hill48.py` path and infers `keymap="keymaps", possible_keyboard="hillside"` from it, then that nonexistent keymap gets added for all `hillside/*` keyboards.

**Comment by mmccoyd** [comment]
> The CI code mistakenly parses the `keyboards/hillside/48/keymaps/json2hill48.py` path and infers `keymap="keymaps", `

Thanks! I can remove the .py  so the config issue isn't triggered.

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
