### PR TITLE
Add new keyboard layout to Let's Split based on Ergodox Thumbcluster

### PR DESCRIPTION
**Pull request by ethanspitz**
Adds a new layout to Let's Split. I'm coming from an Ergodox and really though having similar layout to an Ergodox would be a good idea.

I'm willing to take suggestions if someone has them on how to make it even closer to how the ergodox is layed out with out sacrificing 40% efficiencies.

On base layer, makes left space key a backspace and enter key a right shift.

On the raise and lower layers, the left space key is a delete and the right space key is enter

### CODE REVIEW

**Comment by r2d2rogers** [comment]
I'm looking at something similar, going between Ergodox and Let's Split.  One of the things I'm trying is moving the space keys in one position and putting the adjust keys on the corners as dual role keys.  The left is backspace on tap and the right is enter on tap to mirror my thumbs on the ergodox.

**Comment by jackhumbert** [comment]
Nice :) thanks!

**Comment by ethanspitz** [comment]
@r2d2rogers, that's an interesting idea. I think that with the frequency that we use the raise and lower though, it's ideal to have it in the thumb cluster rather than by the pinkies.

Honestly, an orthodox looks like the best of both worlds if you can't live without dedicated keys for enter space and backspace delete.

**Comment by r2d2rogers** [comment]
@ethanspitz, I'm sorry, I didn't explain that very well. I just swapped the raise and lower keys with the spaces.

**Comment by r2d2rogers** [comment]
@ethanspitz, I'm sorry, I didn't explain that very well. I just swapped the raise and lower keys with the spaces.

**Pull request merged**
