### PR TITLE
Allow for removal of hysteresis on 4x encoders

### PR DESCRIPTION
**Pull request by tucvbif**
Sometimes, controller skips encoder pulses and when it returns to default position, the encoder_pulses variable isn't equals 0. And when I turn encoder in opposite direciton, it skips first click becase of encoder_pulses crosses zero. To prevent this, I add the ENCODER_DEFAULT_POS constant, and reset encoder_pulses into 0 when the state variable equals ENCODER_DEFAULT_POS.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
You have a merge conflict here, and need to rebase to fix it.

**Comment by drashna** [comment]
You need to rebase to fix this.

**Comment by tucvbif** [comment]
Yes, I definitely need help.

**Comment by drashna** [comment]
I've rebased the PR, so it should be up to date, now.

For reference, the process is outlined here:
https://docs.qmk.fm/#/newbs_git_best_practices

Which is basically what I did.  However, since this looks like it was done from the web UI, I figured it was probably simplest to do it myself.

**Comment by drashna** [comment]
Also, could you add documentation for the option?

**Comment by tucvbif** [comment]
How can I do this?

**Comment by drashna** [comment]
Basically by editing: https://github.com/qmk/qmk_firmware/blob/develop/docs/feature_encoders.md

**Comment by tucvbif** [comment]
Also, I appreciate if someone check the grammar.

**Review by tzarc — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Pull request merged**
