### PR TITLE
[WIP]  [Keymap,User] Fix users/mtei/encoder_update_user.c

### PR DESCRIPTION
**Pull request by mtei**
## Description

It seems that calling tap_code() on the slave side should not be done because the keycode cannot be sent to the host.

If `encoder_update_user()` is the following code

```c
bool encoder_update_user(uint8_t index, bool clockwise) {
    DEBUG_PIN_ON();
    switch (index) {
    case 0: tap_code(clockwise ? KC_A : KC_B); break;
    case 1: tap_code(clockwise ? KC_C : KC_D); break;
    case 2: tap_code(clockwise ? KC_E : KC_F); break;
    case 3: tap_code(clockwise ? KC_G : KC_H); break;
    }
    DEBUG_PIN_OFF();
    return true;
}
```

The timing chart on the master side is as follows. The execution time of `encoder_update_user()` is very short.
encoder_master2

The timing chart on the slave side are as follows. The execution time of `encoder_update_user()` is very long.
As a result, the speed of execution of the main loop is temporarily slowed down and changes in the encoder signals become partially unreadable.
In other words, the same number of inputs as changes in the encoder's signal will not be performed.
encoder_slave_bug2

If `encoder_update_user()` is the following code
```c
#define TAP_CODE(x) if (is_keyboard_master()) { tap_code(x); }

bool encoder_update_user(uint8_t index, bool clockwise) {
    DEBUG_PIN_ON();
    switch (index) {
    case 0: TAP_CODE(clockwise ? KC_A : KC_B); break;
    case 1: TAP_CODE(clockwise ? KC_C : KC_D); break;
    case 2: TAP_CODE(clockwise ? KC_E : KC_F); break;
    case 3: TAP_CODE(clockwise ? KC_G : KC_H); break;
    }
    DEBUG_PIN_OFF();
    return true;
}
```
The timing chart on the slave side are as follows. The execution time of `encoder_update_user()` is very short as well as that of the master side.
encoder_slave_new2

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Is it causing issues?  

If so, then it is something that should probably be applied to the core code.

**Comment by mtei** [comment]
> Is it causing issues?

Phenomenon description added.

**Comment by drashna** [comment]
> > Is it causing issues?
> 
> Phenomenon description added.

So, yes, it is causing issues. And likely for every split board with an encoder on the slave side. 

If that's the case, this should really go into the core code, rather than user level code, I think. 

Also, I suspect that this won't happen when using the new encoder map feature, in develop.

**Comment by monksoffunk** [comment]
I think it is reasonable to handle this in the core, but it would be a bit disappointing if the following implementation would not be easily possible.

- Control OLEDs, LEDs, and audio mounted on the slave side by the encoder on the slave side.

though I don't know if anyone is doing that kind of coding.

**Comment by drashna** [comment]
> * Control OLEDs, LEDs, and audio mounted on the slave side by the encoder on the slave side.

Almost all of that can already be handled by split data sync already. And what isnt could be added with the custom data syncing.

**Comment by zvecr** [comment]
Closing as userspace was removed last develop cycle.

**Pull request closed without merging**
