### PR TITLE
FightPad! macropad

### PR DESCRIPTION
**Pull request by AlisGraveNil**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by AlisGraveNil** [comment]
I have no idea why my PR is trying to change anything more than the macropad I'm trying to add; I resync'd my local repository before I uploaded anything...

**Review by zvecr — CHANGES_REQUESTED** [review]
image
In its current form, we wouldn't be able to accept this PR. You will need to do something like a rebase to tidy the state up.

**Comment by AlisGraveNil** [comment]
Can you delete this PR so I can try again?
The guides I'm finding online for how to rebase my PR don't seem to be helping, the result my CLI keeps giving me is that I'm 700+ commits *ahead* of the master, and I don't know what else to do (my CLI knowledge is limited to whatever someone else's guide shows)

**Comment by zvecr** [comment]
Cant really "delete" but you can open a new PR from a new branch, or reuse (and fix) this PRs branch and reopen.

**Pull request closed without merging**
