### PR TITLE
[Bug] Develop - DC01 left

### PR DESCRIPTION
**Pull request by Xelus22**
## Description

https://github.com/Xelus22/QMK-VIA-Hex-Develop/runs/3103052314?check_suite_focus=true#step:13:597
Issue due to automatic changes in #13471 

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fix DC01 Left compile issue

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by skullydazed** [comment]
This reintroduced a data error:

```
☒ dc01/left: MATRIX_COLS is inconsistent with the size of MATRIX_COL_PINS: 6 != 21
```

How can we get `MATRIX_COLS` and `MATRIX_COL_PINS` into sync here?

**Comment by Xelus22** [comment]
@yiancar would there be an easy solution?

**Comment by yiancar** [comment]
No clue whats happening here :)
The idea is that the left part has the matrix for the "whole" keyboard. In my mind it is actually a "whole"keyboard if that makes sense. Just reports nothing for the other parts if they are not connected.

**Comment by skullydazed** [comment]
> No clue whats happening here :)

Data normalization, basically. :) We recently added a check to ensure that `MATRIX_COLS` is the same as the length of `MATRIX_COL_PINS`. In the case of this keyboard it isn't. I initially added `NO_PIN` (which seems to work everywhere else) to pad out the unused pins, but apparently that does not work here.

So now we're in a situation where it works but throws a warning, because the values don't match.

**Comment by skullydazed** [comment]
I dug into this a bit more, I think something like this would fix it up at the cost of a few extra bytes: https://github.com/qmk/qmk_firmware/commit/eab6f658bb44fbd8fa986259ae6fdad08be25c10

**Pull request merged**
