### PR TITLE
Add config for macro delay

### PR DESCRIPTION
**Pull request by Dhertz**
Be able to configure more delay to make sure letters are not skipped.

Please let me know where it is appropriate to document this change, and then I will update this PR.

### CODE REVIEW

**Comment by drashna** [comment]
Ah, looking at this, .... I'm not sure that this is needed, at all. 

You can call this function directly.   And if you need the "SS" stuff, you can do this: 

`send_string_with_delay_P(PSTR( ____ ), 10)`, replacing the _____ with the normal SEND STRING stuff.

**Comment by Dhertz** [comment]
Sounds good - feel free to close then!

**Comment by drashna** [comment]
Will do ... but I think it would be a good idea to add this info to the docs.

https://github.com/qmk/qmk_firmware/blob/7c9d5ace143d3cc6d767a354acde814926d566fd/docs/feature_macros.md

**Comment by drashna** [comment]
(closing since it isn't really needed.  But better documentation is)

**Pull request closed without merging**
