### PR TITLE
Allow CI to build all board revisions when not using DEFAULT_FOLDER

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Currently if a planck or keebio/iris keymap is added or modified, CI will fail as those boards do not use a `DEFAULT_FOLDER`.
```console
$ make keebio/iris:drashna
QMK Firmware 0.7.92
make: *** No rule to make target 'keebio/iris:drashna'. Stop.
```
This allows compilation issues to slip through the PR process.

Another potential problem is these boards have top level code files, for example `keyboards/planck/planck.h`. If these change, the same issue arises. CI has no way to key the changes against what to build.

`DEFAULT_FOLDER` was removed from some of these boards, as people were trying to build/flash the wrong firmware. To maintain this contract, but allow CI to have a sane behaviour, this PR adds in logic to support partial matching within the travis environment.

```console
$ make keebio/iris:drashna
QMK Firmware 0.7.92
Making keebio/iris/rev1 with keymap drashna                                                            [OK]
Making keebio/iris/rev1_led with keymap drashna                                                        [OK]
Making keebio/iris/rev2 with keymap drashna                                                            [OK]
...
```

### Alternative solutions
1. configure a `CI_DEFAULT_FOLDER` option within the top level rules.mk, which will behave like `DEFAULT_FOLDER` would, but only within CI. 
2. configure  `NO_USER_DEFAULT_FOLDER` that disables `DEFAULT_FOLDER` when not in CI. 

The downside to this, is the reliance on keyboards to be configured correctly.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
For CI, on every push to PR or master, we currently have the rule "if a user keymap has changed -> build keymap". This falls over on planck/preonic/iris due to the lack of DEFAULT_FOLDER.

Longer term, it could be nice for keymaps to have a way to express which board revision/s they are targeting, potentially cutting down a lot of the ambiguity.

**Comment by drashna** [comment]
>Longer term, it could be nice for keymaps to have a way to express which board revision/s they are targeting, potentially cutting down a lot of the ambiguity.

As long as that also includes "any/all/some", since people may have multiple revisions of the board.

**Comment by zvecr** [comment]
Yeah we would want that sort of configurability, but i would imagine thats way down the line when everything is json.

**Comment by zvecr** [comment]
Slight spanner, `make list-keyboards` doesn't list the parent so we still now see the issue in the CI detection code. I think a rules.mk with `CI_DEFAULT_FOLDER` might have to be the short term solution

**Pull request closed without merging**
