### PR TITLE
Add additional layout options to knight_plus keyboard

### PR DESCRIPTION
**Pull request by XBowsTech**
## Description

Add additional layout options to knight_plus keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by XBowsTech** [comment]
I resubmitted a request.@zvecr

**Review by zvecr — CHANGES_REQUESTED** [review]
Right now, the changes do not really add any value given they just duplicate what already exists.

`xbows/knight_plus` has the slight exception that it renders the middle backspace/enter keys to a different width.

**Comment by XBowsTech** [comment]
> Right now, the changes do not really add any value given they just duplicate what already exists.
> 
> `xbows/knight_plus` has the slight exception that it renders the middle backspace/enter keys to a different width.

Yes, these changes are to make it more beautiful and tidy. Also, when I use QMK Configurator and load the default Settings, it prompts "* Sorry there is no default for the xbows/knight_plus keyboard... yet! ", what's the reason?

**Comment by XBowsTech** [comment]
> Right now, the changes do not really add any value given they just duplicate what already exists.
> 
> `xbows/knight_plus` has the slight exception that it renders the middle backspace/enter keys to a different width.

It is worth noting that in xBows/Numpad, "." It overlaps with the "Enter" key, so I need to change the info.json file.

**Review by zvecr — CHANGES_REQUESTED** [review]
> Yes, these changes are to make it more beautiful and tidy. Also, when I use QMK Configurator and load the default Settings, it prompts "* Sorry there is no default for the xbows/knight_plus keyboard... yet! ", what's the reason?

<https://docs.qmk.fm/#/configurator_default_keymaps>, needs a PR to a different repo


> It is worth noting that in xBows/Numpad, "." It overlaps with the "Enter" key, so I need to change the info.json file.

However your PR currently doesnt do anything but add duplication
image

If this were the intention, and the change is purely for presentation, you would only need to update `LAYOUT` not rename and duplicate.

**Comment by XBowsTech** [comment]
Here's the key change:
changes
Also, do you want me not to add the same layout? Although just to distinguish between "DEFAULT" and "VIA"
Or could you help me make a modification? I hope it will be uploaded and used soon.@zvecr

**Comment by XBowsTech** [comment]
I renamed the original layout and copied it to distinguish "default" from "via".
If it is inappropriate, I can change it back to the original version, or you can edit it directly.
I'm sorry for causing some trouble to you! @zvecr

**Comment by XBowsTech** [comment]
drashna, hello!
Can you check these codes for me? What is wrong or unnecessary in it?
@drashna

**Comment by XBowsTech** [comment]
What other changes do I need to make? 
Thanks for your help!@zvecr

**Comment by XBowsTech** [comment]
I can't seem to get in touch with @zvecr. Could you please help me to see what changes I need to make?
I hope this request will be approved soon. Thanks for your help! @fauxpark

**Pull request closed without merging**
