### PR TITLE
Move IDOBAO keyboards to the Idobao sub-folder

### PR DESCRIPTION
**Pull request by vinorodrigues**
## Description

This is a minor, brand specific, clean-up of the keyboards folder to align the [IDOBAO](https://idobao.net/) keyboards into an `idobao` sub-folder in accordance to the project [guidelines](https://docs.qmk.fm/#/hardware_keyboard_guidelines?id=sub-folders).

No attempt has been made to correct any issues *(if they exist)* or modify any existing code except in the `README.md` file wherein the "make" command was modified to show the `idobao/` folder *(and in some cases the product image link was corrected)*.  After move the change was tested by attempting to compile with the corrected `make` command, and all complied with no issues.

The folder move was applied with the `git mv` command and affects 4 IDOBAO keyboards, namely the **ID67**, **ID80**, **ID87**, and the **Montex**.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard *(addition or update)*
- [ ] Keymap/layout/userspace *(addition or update)*
- [ ] Documentation

## Issues Fixed or Closed by This PR

*n/a*

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything *(as well as I can manage)*.

### CODE REVIEW

**Comment by zvecr** [comment]
https://github.com/qmk/qmk_firmware/pull/14369#issuecomment-916629673

**Comment by vinorodrigues** [comment]
@zvecr  - sorry .. I canned the #14369 PR as I'd mistaken the Idobo for the ID75.  The Idobo is indeed branded by YMDK, so that should not have been included.  *(The ID75 uses the same PCB as the YMDK-Idobo, but I didn't want to contravene the branding.)*

**Comment by zvecr** [comment]
Just push more commits to the same branch, theres no need to close and reopen.

**Comment by vinorodrigues** [comment]
I'd posted this 3 months ago.  Unfortunately if this does not get rolled into a main project branch (in this case "develop") it becomes impossible to maintain as the core code keeps changing and the PR reports *"Only those with write access to this repository can merge pull requests"* which makes the upkeep evermore so difficult.

As such, I'll withdraw the PR.

**Comment by peepeetee** [comment]
I have lots of time on my hand, do you want me to take over?

**Comment by vinorodrigues** [comment]
@peepeetee - not much to take over from ... it's just a file move to a sub-folder.  It's 2, maybe 3, minutes of work.  It's not a work effort problem, it's a moving goal problem.  If you move a file from one folder to the another then someone else edits the original file in the original folder then you get a merge conflict that only project editors can resolve.

It's actually quicker to just take a new branch and move the files again.

**Comment by peepeetee** [comment]
yee, when I was doing similar work on another vendor's folder I made a script to do the changes automatically, and ran it everytime it changed. I'd recommend doing it near or at the breaking change period. If you're still up for this, I'd say keep this PR and do the changes here. If you no longer feel up for it I can just do it for you

**Comment by peepeetee** [comment]
> @zvecr - sorry .. I canned the #14369 PR as I'd mistaken the Idobo for the ID75. The Idobo is indeed branded by YMDK, so that should not have been included. _(The ID75 uses the same PCB as the YMDK-Idobo, but I didn't want to contravene the branding.)_

May I ask how you came to this conclusion? I'm trying to figure out if Idobo should indeed go into the IDOBAO folder

**Comment by vinorodrigues** [comment]
The ***Idobo 75 Keys Ortholinear Layout QMK Anodized Aluminum Case Plate hot-swappable Hot Swap Type C PCB Mechanical Keyboard Kit** is a YMDK product, not an IDOBAO product.  *(May well be mnf. by the same, but sold as different brands.)*

See https://ymdkey.com/products/idobo-75-keys-ortholinear-layout-qmk-anodized-aluminum-case-plate-hot-swappable-hot-swap-type-c-pcb-mechanical-keyboard-kit

**Comment by peepeetee** [comment]
> Idobao.net does not have a ortho in it's repertoire.

https://idobao.net/collections/60-layout/products/idobao-id75v1-hot-swappable-mechanical-keyboard-kit
image

**Comment by peepeetee** [comment]
YMDK also sells the other IDOBAO products, currently I believe that they are just reselling IDOBAO's product

**Comment by vinorodrigues** [comment]
Yes, sorry ... Idobao does have a Ortho *(missed it)*

**Comment by vinorodrigues** [comment]
I have no idea here.  But what I can say is from personal experience:  When I bought a Idobao ID96 there was no QMK build for it.  So I contacted Idobao on their support line and the reply was *(paraphrasing)*:  **"It's the same board as the YMDK Melody 69, just use that."**.

From this I can assume, having working in the hardware industry myself, albeit printers, that either:
1. Idobao is sourcing it's boards from YMDK (or visa versa), or
2. Both Idobao and YMDK are sourcing their OEM PCB's from a third (unpublished) manufacturer.

Assuming *(from my printer experience)* that there is indeed a 3rd-party then we cannot assume that moving a folder like the ID75 should live in either Idobao or YMDK vendor folder (or indeed Drop's).

The reason I canned the PR's to move the folders was just this.

The only correct way to do this is to have either the vendor themselves look after their codebase, or the original QMK author *(of the KB bit that is)*.  For the Idobo ID75 *(note the spelling is different)* this would be @MechMerlin *(yes, the same one with the YouTube channel)* - and he built this code for the Drop variant --- so should live in the "Drop" vendor folder.

To be honest, another reason I gave up is that it's just too messy... the guidelines in docs.qmk.fm recommend using a vendor folder, but yet kb's are continuously being added to the root by the maintainers.  So if they're not following their own "rules" then trying to clean after-the-fact is a losing battle.

**Pull request closed without merging**
