### PR TITLE
Makefile Fixes

### PR DESCRIPTION
**Pull request by 333fred**
Made in separate commits for review and revertability.

Commit 1: Standardize include ordering for `config.h` and `rules.mk`. Keymap-specific should always be included last so it wins over the userspace defines.
Commit 2: Fix revision building

### CODE REVIEW

**Comment by 333fred** [comment]
@jackhumbert this now additionally fixes an issue (commit 3) where the `LAYOUTS` field of keyboard subrevisions wasn't getting considered when choosing what layout to build, so make would think that `make handwired/dactyl_manuform:bakingpy` should be attempting to run the `bakingpy` target on every layout, instead of pulling in the `bakingpy` layout from the `ortho_4x12` layouts folder.

**Comment by 333fred** [comment]
Based on discord feedback from @drashna, I've pulled the gitter->discord commit out of this PR and I'll submit a separate PR for that.

**Comment by drashna** [comment]
Just thinking ... the issue with this, is that it .... well breaks my userspace, since I'm adding features to it, and then using the keymap's rules.mk to toggle that. 

I don't think that we shouldn't change that because ... of well, my needs.... but maybe we should add handling for a "features.mk" for the userspace?  
@jackhumbert does that sound good?

**Comment by jackhumbert** [comment]
Nice! I think I'd prefer a name that makes things clearer - maybe something like `pre_rules.mk` or `early_rules.mk`? I think we'll need some docs with this addition as well, describing how to use each with examples/where certain lines should go.

**Comment by drashna** [comment]
Also, why a secondary makefile for the keymap folders?  

Wouldn't it be better to add a "build_user.mk`  where the "old" include was, that way it gets processed in such a way that you can add features in the userspace and set them with the one rules.mk for the keymap? 

Eg, using this instead of 27dfa9af3d673cf8d6521eb4fc32d857fcb16c55
```
diff --git a/build_keyboard.mk b/build_keyboard.mk
-include $(USER_PATH)/build_user.mk
+
 # Object files directory
 #     To put object files in current directory, use a dot (.), do NOT make
 #     this an empty or blank macro!
```

I mean, both methods work, but ... it feels more natural to use the `build_user.mk` in the userspace, than having a second makefile in the keymap folder.


Also, cc72c0e47ff96ed7945cd714101ada2c3250d0b1 breaks travis, I think you replaced the wrong files here.

**Comment by jackhumbert** [comment]
Awesome - thanks!

**Pull request merged**
