### PR TITLE
Custom OLED timeout

### PR DESCRIPTION
**Pull request by Ga68**
Allows a keyboard and/or user to dynamically set the OLED timeout based on the current keyboard state.

## Description

Currently the timeout for your OLED display is set statically in config.h. This change enables a keyboard and/or user level function to return the timeout. Users can use this to change the timeout based on the keyboard state. For example, they may want the timeout to be longer when CAPS LOCK is on, if they're displaying that on their OLED, so that they don't forget.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by zvecr — CHANGES_REQUESTED** [review]
A user trying to configure `OLED_TIMEOUT` when a keyboard is using `OLED_CUSTOM_TIMEOUT` and `oled_timeout_kb` will have potential issues.
1. Currently the user will have zero indication that their config.h value will not be honoured
2. `oled_timeout_kb` has no way to know if user behaviour should take preference
    * `oled_timeout_user` would need a magic value to indicate that the default keyboard level behaviour should be used. (The return true/false behaviour of various _user/_kb functions)

**Comment by drashna** [comment]
for number 2, passing the timeout as a pointer may be a good solution.

That said, I am not really a fan of this, in part because of the first reason, but also because it may be simpler to just implement this at the user (or kb) level if and when it pops up.

**Comment by Ga68** [comment]
The first is a good point I hadn't caught. Thanks for catching it! I've thought about it some, but can't think of a good way to handle that, without some breaking change that would fundamentally change the nature of OLED_TIMEOUT. And this particular use case is far more esoteric than the primary use case.

However, I could change the nature of the feature to be a user-only feature, which would avoid the kb-override problem. I would eliminate the _kb function and document it as a _user only feature. I'm not sure I've seen that pattern before. Do you think that still has value if executed in that way?

**Comment by drashna** [comment]
Honestly, I think that adding code examples may be a better solution than adding code.

**Comment by Ga68** [comment]
Okay, sounds good. I haven't "added code examples" before. Is that something to do in a pull request here, by modifying documentation, or is it better to just close this one down and it's done elsewhere?

**Comment by drashna** [comment]
> Okay, sounds good. I haven't "added code examples" before. Is that something to do in a pull request here, by modifying documentation, or is it better to just close this one down and it's done elsewhere?

By code examples, what I mean specifically is adding to documentation, and add to an examples section.  Much the way that the macros docs or tap dance docs have multiple examples of different stuff you can implement and how to do so. 

Eg, add to the docs more examples, and how to use a custom timeout for the board.

The SplitKB boards may be a good example of this.  Especially the Zima, as I have a lot of code in there to do some cool stuff, including ...a screen saver. :D

**Comment by Ga68** [comment]
Awesome. I'll close this down, take a look at the examples you pointed out, and when/how it makes sense, I'll open up another PR for just some documentation changes with examples on how to do this. Thanks so much for all the thought and advice.

**Pull request closed without merging**
