### PR TITLE
Allow joysticks to be used without analog pins

### PR DESCRIPTION
**Pull request by skullydazed**
## Description

Currently you have to define an analog pin to use joystick support. This allows you to use it without defining that analog pin.

## Types of Changes

- [x] Core
- [x] Bugfix
- [x] Enhancement/optimization
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by skullydazed** [comment]
@a-chol @sigprof Tagging both of you for review/comment since you each worked on this

**Comment by a-chol** [comment]
I had thought about this feature when developping the initial PR and added the JOYSTICK_AXIS_VIRTUAL define that defines an axis that is not read from an analog pin. It is used in the definition array of the axes, as follows:
joystick_config_t joystick_axes[JOYSTICK_AXES_COUNT] = {
    [0] = JOYSTICK_AXIS_VIRTUAL,
    [1] = JOYSTICK_AXIS_VIRTUAL
};
for instance, if you want 2 axes not read from analog pins. The feature is detailed in the documentation. 
Is this the feature that you intended?

**Comment by skullydazed** [comment]
There are two separate issues here.

1. Simply enabling joystick support also pulls in `analog.c`. We should not require this in situations where we aren't using it.
2. The documentation is not at all clear about how to map simple buttons to joystick axii.

This PR only addresses 1, but 2 is also a concern I have, and seems to be what you are addressing with your comment.

**Review by fauxpark — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
