### PR TITLE
Utilize Docsify's embed feature to single-source documentation keycodes

### PR DESCRIPTION
**Pull request by jakevandervaate**
I created individual files for each set of keycodes on the [Full List of Keycodes page](https://docs.qmk.fm/#/keycodes).

Each set of keycodes is now stored in its own  `keycodes_***.md` file (e.g. the "letters and numbers" keycodes are stored in `keycodes_letters_and_numbers.md`). These indidividual keycode files can be embedded into other pages with Docsify's "[embed](https://docsify.js.org/#/embed-files)" feature.

Linking to these keycode files creates a single source for each set of codes and prevents different pages from having mismatched sets of keycodes for the same feature.

I also updated the pages that the "Full List" page references, when that page also had keycodes listed on it.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* #4610 
* Discussed with @Erovia [here](https://github.com/qmk/qmk_firmware/issues/4610#issuecomment-1079345333)

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
I don't know if we want to be leaning into Docsify-specific features, there are plans to move the docs to something that can be indexed by Google (beta.docs.qmk.fm used Gitbook as a stopgap for some time and is now defunct).

**Comment by jakevandervaate** [comment]
@fauxpark I can definitely understand not wanting to be locked into one solution; I did consider that before taking this on. I think there is still value in this solution, or a similar one, from a few different perspectives.

1. Assuming potential new solutions have a similar embed feature (this is one of the most beneficial features I'd look for), changing all the include tags to the new syntax wouldn't be difficult (`grep ':include' docs/*.md` shows all the places that use Docsify embeds currently).
2. If the new docs solution didn't have an embed/include feature, and assuming it creates static HTML pages, creating a similar function would be fairly simple with a shell or Python script.
3. If we decide to not pursue this embed feature, having a "main" keycode file for each feature is valuable, even if it means manually updating pages with a copy of the contents of that file when new keycodes are added. 

Let me know what you think and I'll be happy to adjust accordingly.

**Comment by Erovia** [comment]
If we move ahead with this approach, I think it'd make sense to have all the keycode "plugin" files in a dedicated directory and include them from there.
`docs/` is already over-convoluted as it is.

**Comment by jakevandervaate** [comment]
@Erovia I can move the keycode files into `docs/keycodes/` to keep `docs/` more organized. I agree that it's a little difficult to connect the names of the files in the `docs/` repo with the links that are on the website, but that could probably be its own, separate issue.

Would you like me to restructure this with a new `docs/keycodes/` directory to accomodate all the new files I created?

**Comment by jakevandervaate** [comment]
I consolidated the keycodes into `docs/keycodes/` and tested the changes with `qmk docs`.
Let me know if you'd like any other changes.

**Pull request closed without merging**
