### PR TITLE
Helix trivial fix

### PR DESCRIPTION
**Pull request by marksard**
It reflects the matter pointed out at merging to crkbd.

Thank you for your advice.

### CODE REVIEW

**Comment by marksard** [comment]
TO: @MakotoKurauchi , @mtei 

Point of view

* Replace header from define to pragma once

 Since it is always pointed out in the review, it is fixed in advance.

* Replace from sizeof to define

 It is correction of point out that it is better not to use sizeof every time in #3798 review.

* Removed warning about ws2812.d

 Since we removed this warning in the review of #3798, helix also fixed.
 This warning occurred when ws2812.c is duplicated and registered in the SRC.

**Comment by MakotoKurauchi** [comment]
Thank you.
It does not seem to be a problem.

**Comment by mtei** [comment]
I have some comment.
But now I am little busy.
Please wait for a few days.

**Comment by drashna** [comment]
@MakotoKurauchi if you're using a customized ws2812.c file, then we need `RGBLIGHT_CUSTOM_DRIVER = yes` in the rules.mk.  

This will prevent the RGBLIGHT feature from adding the basd ws2812.c driver, so that this error doesn't occur. 

https://github.com/qmk/qmk_firmware/blob/master/common_features.mk#L110-L114

@marksard If you could re-add the file, and add `RGBLIGHT_CUSTOM_DRIVER = yes` to the rules.mk (where appropriate), it should fix that error/warning too.

**Comment by marksard** [comment]
@MakotoKurauchi Where is there the custom ws2812.c?

**Comment by MakotoKurauchi** [comment]
Oh, what we customized was ssd1306.c. It was a misunderstanding. I'm sorry.

**Comment by drashna** [comment]
So this should be ready to go?

**Comment by marksard** [comment]
@MakotoKurauchi Thanks :)
@mtei , Could you write to comment?

**Comment by mtei** [comment]
about 4 header files.
```
keyboards/helix/pico/serial_config.h
keyboards/helix/rev1/keymaps/OLED_sample/serial_config.h
keyboards/helix/rev1/serial_config.h
keyboards/helix/rev2/serial_config.h
```

I think it is better not to change these files.

Actually, serial_config.h does not need either "#pragma once" or "#ifndef SOFT_SERIAL_CONFIG_H". Because it is included only from helix/config.h.

Still if you do a guard just in case, it is necessary to use "#ifndef SOFT_SERIAL_CONFIG_H" so that only the first one becomes valid when these files conflict.

"#pragma once" prevents double loading of one file, but it can not deal with this case.

**Comment by mtei** [comment]
About keyboards/helix/rev2/matrix.c.

I think it is better not to change this file.
Because this change worsens maintainability.

**Comment by marksard** [comment]
* serial_config.h
Basically, header file is need to include guard.
Even if it is not necessary now, the future is unclear.

* matrix.c.
https://github.com/qmk/qmk_firmware/pull/3798#discussion_r213903943
It seems that he was concerned about the sizeof (at compile time) performance.

**Comment by marksard** [comment]
@drashna 
I think to close this PR once and I want to redo the PR. (I will try to PR a little smaller units.)
Thanking you in advance.

**Comment by drashna** [comment]
@mtei For the serial config, that's why elsewhere, I've said that I don't think that this should be a separate file, like this. 

Instead, this should be part of the serial.h file, but use `#ifndef` blocks for these values.  That way, you can override them, as needed, and they're handled in a way that is consistent with most of the other QMK core configuration defines.

**Pull request closed without merging**
