### PR TITLE
Add Pulsar Xboard to QMK. ( QMK and VIA-compatible 80% keyboard)

### PR DESCRIPTION
**Pull request by skylupin03**
## Description

Add Pulsar Xboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by adophoxia** [comment]
Will this be the **only** PR you'll open? A word of caution as opening and closing new PRs after every change you make may get you banned from the repo.

**Comment by waffle87** [comment]
I advise you start with `qmk new-keyboard` and restart with this keyboard's firmware — there are many things that will not be accepted. Please also thoroughly read the [PR checklist](https://docs.qmk.fm/#/pr_checklist).

**Comment by skylupin03** [comment]
> Will this be the **only** PR you'll open? A word of caution as opening and closing new PRs after every change you make may get you banned from the repo.

thank you.
It's been modified many times, and it's gotten messy. I closed the previous PR, and I uploaded a new one.

**Comment by skylupin03** [comment]
> I advise you start with `qmk new-keyboard` and restart with this keyboard's firmware — there are many things that will not be accepted. Please also thoroughly read the [PR checklist](https://docs.qmk.fm/#/pr_checklist).

I made it "qmk new-keyboard" last year and kept modifying it.
I will further organize and revise it.
I'll read PR checklist again.
Thank you

**Comment by adophoxia** [comment]
Seeing all this...stuff...was this all cobbled up together from reading the QMK Docs? Right now, no way is this mergeable.

**Pull request closed without merging**
