### PR TITLE
Draft: Enhance Viktus OSAv2 Topre Firmware with Customizable Key Actuation Sensitivity

### PR DESCRIPTION
**Pull request by seansica**
## Description
This pull request introduces enhancements to the QMK firmware for the Viktus Design LLC Topre PCB that powers the Viktus OSAv2 keyboard. The changes focus on improving the process of modify the actuation sensitivity for specific keys to provide a more satisfactory user customization experience.

The main modifications include:
- Separating the key position definitions and key level configurations into separate files (`key_positions.h`, `key_positions.c`) for better organization and maintainability.
- Defining KeyPosition objects for all keys in the matrix using a consistent naming convention (`KEY_{ROW}{COL}_{FRIENDLY_NAME}`).
- Allowing users to specify custom actuation levels for specific keys by modifying the `key_level_configs` array in `key_levels.c`.
- Updating the `ec_matrix_scan` function in `ec.c` to apply the configured actuation levels during the matrix scan.
- Implementing a fail-safe mechanism to ensure that the difference between `reset_pt` and `actuation_pt` is at least 5 points for each key.

These changes enhance the firmware by providing a more intuitive and customizable approach to adjusting the actuation sensitivity of individual keys, without modifying the main scanning logic.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Requiring a user to modify a keyboard level file (`keyboards/viktus/osav2_topre/ec.c`) isnt really much of an improvement over the existing code. The implementation of `key_positions.h` bleeds assumptions on keymapping into the config, as well as dirties the namespace, which should be really be avoided. 

What I would expect is some form of weakly defined function (or structure) which can be implemented keymap level.

As a separate note, this also does not conform to the guidelines on header guards and licence headers.

**Comment by seansica** [comment]
> Requiring a user to modify a keyboard level file (`keyboards/viktus/osav2_topre/ec.c`) isnt really much of an improvement over the existing code. The implementation of `key_positions.h` bleeds assumptions on keymapping into the config, as well as dirties the namespace, which should be really be avoided.

The notion that this approach "dirties the namespace" assumes that the proposed implementation with `key_positions.h` does not provide value. On the contrary, it simplifies the process for users to modify actuation levels by leveraging the predefined `KeyPositions` object and making changes within `KeyConfig`. This approach promotes better readability and separation of concerns, as users no longer need to navigate complex code or manually identify where actuation levels are set.

Can you elaborate on how this implementation is not a clear improvement? It has demonstrably provided value by enabling users to set custom per-key actuation levels without concerning themselves with the core logic.

**Comment by zvecr** [comment]
> Requiring a user to modify a keyboard level file (keyboards/viktus/osav2_topre/ec.c) isnt really much of an improvement over the existing code.

Any change which still requires a user to modify a keyboard level file, is not an improvement. It is not compatible with workflows such as external userspace, and is known to produce conflicts when updating local copies of repos.

> The implementation of key_positions.h bleeds assumptions on keymapping into the config, as well as dirties the namespace, which should be really be avoided.

The provided solution makes assumptions in its config, when it assumes `KEY_00_KC_DEL` is always associating `KC_DEL` to matrix position 0,0. When a user chooses to remap a given key, for example to dvorak, it fails to increase readability as it no longer keys together correctly.

The code also does not make use of `PROGMEM`. It unnecessarily bloats RAM usage, and can lead to random runtime issues when it overflows.

**Comment by seansica** [comment]
> Any change which still requires a user to modify a keyboard level file, is not an improvement.

I respectfully disagree with this point. The proposed change enhances readability and organization compared to the current implementation. While it may not meet a theoretical ideal, it represents a meaningful iterative improvement. We should embrace these enhancements where possible. Could you please point me to the specific qmk guidelines that define what constitutes an "improvement"? 

> It is not compatible with workflows such as external userspace, and is known to produce conflicts when updating local copies of repos.

I understand and agree that compatibility is important. Could you clarify if these concerns are unique to the changes proposed in this PR, or if similar issues exist in develop/main as well?

> The provided solution makes assumptions in its config, when it assumes KEY_00_KC_DEL is always associating KC_DEL to matrix position 0,0. When a user chooses to remap a given key, for example to dvorak, it fails to increase readability as it no longer keys together correctly.

So just to confirm, we are discussing *variable names* now, correct? 

While I understand your concern about potential confusion when remapping keys, I believe the context of our project—QMK firmware on a custom PCB with a relatively small (<100) user base—mitigates this concern. Most users, including Dvorak users, will intuitively understand `KC_DEL` compared to a matrix position like `(0,15)`. This approach simplifies the code for those familiar with the product's context.

**Comment by zvecr** [comment]
> I respectfully disagree with this point. The proposed change enhances readability and organization compared to the current implementation. While it may not meet a theoretical ideal, it represents a meaningful iterative improvement. We should embrace these enhancements where possible

But knowingly adding in something that is against the paradigms we wish to support is not good for maintaining QMK. I've outlined why its not a good idea, and why we want to avoid it. If we accept this change, and then have to refactor it again to fix the obvious limitations, then there is the potential that users will have to migrate their changes. These will then conflict as its almost certain to be non backward compatible. This leads to unnecessary confusion, questions on discord, issues in the tracker. etc. This is not a theoretical issue, its one that has been hit frequently across similar scenarios in the code base. 

You are welcome to disagree, but I cant see this getting accepted in its current form.

**Comment by seansica** [comment]
Closing this PR unless and until amendments are made to address the aforementioned issues/concerns.

**Pull request closed without merging**
