### PR TITLE
Fix ATSAM's USB HID descriptor to support higher heycodes

### LINKED ISSUE #4548: F12 - 24 Keys not working on Massdrop CTRL
When assigning any keycode between F13-F24, nothing happens when they key is pressed. This happens with both the online configurator when manually building the firmware. register_code() and unregister_code() are also non-functional with these keycodes.

### PR DESCRIPTION
**Pull request by drashna**
## Description

Assuming I understand this correctly, this should set the max scancode to E7 (RGUI), which is the last listed code in the main list (everything else use for internal QMK/TMK stuff).

## Types of Changes

- [X] Core
- [ ] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

*  Fixes #4548, partially addresses #4597 

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
"MC_Rohan" on discord tested this change, and confirms that it works. 

@fauxpark @patrickmt

**Comment by fauxpark** [comment]
Since I don't have a merge button, is me clicking "Approve" particularly useful? Should I be using it?

**Comment by drashna** [comment]
@fauxpark approval is good. But comments is enough. 
Waiting on patrick for confirmation, though. 

Also, would it be better to set the max to 0xFF for consistency (it looks like LUFA is using 0xFF), or do you think it should be file to leave it as is (we're not using anything past 0xE7 "externally", IIRC).

**Comment by fauxpark** [comment]
Might as well max it out to `0xFF`, it won't cost any memory on the MCU as it just defines the range of values the host should expect. Someone, somewhere, will *really* want to send an `0xF2` for whatever wacky idea they have.

**Comment by drashna** [comment]
Well, they can on LUFA, and VUSB, (and chibiOS I think), so might as well make it consistent. :)

**Comment by drashna** [comment]
Also, @fauxpark would you mind approving the PR, if you are so inclined?

**Comment by drashna** [comment]
@patrickmt any issues with this?

**Comment by patrickmt** [comment]
This is good to go!

**Comment by drashna** [comment]
@patrickmt if you wouldn't mind, could you approve the PR?

**Comment by drashna** [comment]
Awesome, thanks!

**Comment by skullydazed** [comment]
Thanks!

**Pull request merged**
