### PR TITLE
Lilith101 keyboard addition, SK6805/SK9816 improvements/support and relevant documentation changes

### PR DESCRIPTION
**Pull request by St0RM53**
## Description

- Added new keyboard: lilith101
- Added SK6805 configuration and updated the documentation
- Added SK9816 support, configuration and updated the documentation

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Core changes cannot be within the same PR as keyboard additions and must go via `develop`.

**Comment by St0RM53** [comment]
Ok, changed the branch to `develop`

**Comment by zvecr** [comment]
> Core changes cannot be within the same PR as keyboard additions

**Comment by St0RM53** [comment]
Made the changes required, and created 2 separate draft pull requests. Closing this one now.

**Pull request closed without merging**
