### PR TITLE
Add support for Bootmagic lite when using SPLIT_HAND_PIN

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Pulled the bootmagic logic into its own file. And to avoid implementing the logic in 2 places, I have merged the via override logic in.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Seems like this might fail for right hand boards with `EE_HANDS` enabled, on the second trigger, as Bootmagic Lite clears the EEPROM.

**Comment by zvecr** [comment]
@fauxpark I can make the PP checks more verbose, but as with a lot of QMK features, it comes down to "just stop doing it wrong". Given this is generally going to be a feature touched during keyboard porting, not end users, do we see this as an issue?

Personally I would like to keep the logic simple :man_shrugging:.

**Comment by fauxpark** [comment]
It's not about the preprocessor checks - from what I can tell, something like this will happen on the left hand board:

EECONFIG_HANDEDNESS is set to 1 (left hand)
Bootmagic Lite is triggered, looks at pins designated for left hand
EEPROM is cleared, EECONFIG_HANDEDNESS set to FF (which will presumably evaluate to false)
...
Bootmagic Lite is triggered again, looks at pins designated for right hand - won't continue as the "wrong" key is being held

Although, perhaps this is all moot, as now I'm looking closer it seems that on AVR `eeconfig_init_quantum()` doesn't erase the entire EEPROM, and for Arm `INIT_EE_HANDS_LEFT`/`RIGHT` will correct the handedness after performing `EEPROM_Erase()`. I do note that this still might be an issue for split boards using the I2C EEPROM driver, as that will cause `eeprom_driver_erase()` to be called.

**Comment by zvecr** [comment]
Im saying i could change the check to 
```c
#if defined(BOOTMAGIC_LITE_ROW_RIGHT) && defined(BOOTMAGIC_LITE_COLUMN_RIGHT) && defined(SPLIT_HAND_PIN)
```

This isnt really a feature for EE_HANDS, its trying to fix broken behaviour for SPLIT_HAND_PIN

**Comment by fauxpark** [comment]
OH. My brain completely skipped over the whole split hand pin part... makes a whole lot more sense now, carry on.

🤦‍♂

**Comment by zvecr** [comment]
Little code shuffle to avoid having to implement the same logic within via. Should be good to go now.

**Pull request merged**
