### PR TITLE
Add Solus support to linux_install.sh script

### PR DESCRIPTION
**Pull request by chax**
## Description

I recently packaged cross-compilers for arm-none-eabi and avr targets on Solus and now i made addition to linux_install.sh script that will handle installation of tools on Solus distro.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by chax** [comment]
Keep in mind that these packages are not yet available in Solus stable repository, but they are available in Solus unstable repository which will probably sync to stable on Friday.

**Comment by drashna** [comment]
I'm marking as "on hold", so it won't get merged until confirmation that the packages are available in the stable repo.

If you could, let us know when that happens.

**Comment by chax** [comment]
Will do. Thanks

**Comment by chax** [comment]
@drashna these packages are now available in Solus stable repository.

**Comment by drashna** [comment]
Awesome, thanks!

**Pull request merged**
