### PR TITLE
Added oled_write_raw and oled_write_raw_P functions to the OLED driver

### PR DESCRIPTION
**Pull request by splitkb**
## Description

The current way to write images to OLED displays is by making use of the font functionality. This has several limitations:

- The way to serialize images into the font format isn't obvious;
- The font format limits the image size to a maximum of 128x32, while 128x64 OLED displays are too supported by QMK.

This pull request, code written by @XScorpion2, intends to introduce an easier way to write custom images to OLED displays within QMK.

## Types of Changes

- [X] Core
- [ ] Bugfix
- [X] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by splitkb** [comment]
Note that I did not write the code, @XScorpion2 did. Documentation still needs to be written, and while I tried my best to cover the intent of the change, I'd like to kindly request @XScorpion2 to verify and possibly elaborate.

This pull request is a prerequisite to #7222.

**Comment by drashna** [comment]
Yeah, if docs could be added.

It doesn't need to be full stuff, just entries into the `feature_oled_driver.md` page for it.

**Comment by splitkb** [comment]
I have added, admittedly quite basic, method entries into the document mentioned.

XScorpion generated the data for me to use on my keyboard. I think some additional documentation on how to generate those files could be useful, and I'd be happy to elaborate once I understand how, but I think that could be done in an additional PR.

**Comment by drashna** [comment]
Well, I have an idea of how they're generated, actually.   Same way that the font files are.  
Each byte is actually a bitmask for a column of pixels, IIRC.   So the format isn't difficult, it's just ... complicated to write something for. 

But yes, that should DEFINITELY be a different PR.

**Comment by manna-harbour** [comment]
https://javl.github.io/image2cpp/ can be used to convert images. Choose Draw mode: Vertical.

**Pull request merged**
