### PR TITLE
Refactor jj40 to current standards

### PR DESCRIPTION
**Pull request by zvecr**
## Description

So far:

- Remove use of custom matrix
- Use ps2avrgb implementation for RGB underglow
- Use generic i2c_master instead of its own copy
- Use default backlight functionality
- Update default keymap to include RGB and Backlight keycodes

Dependencies:

- #4324 - required for hardware pwm support
  - short term "fix" has been applied as that issue currently has build issues

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
There seem to be a few broken layouts, including community ones. 

- drashna
  - `error: ‘PORTE’ undeclared`
  - Due to port not existing on atmega32a
- fun40
  - missing `KEY_LOCK_ENABLE = yes` rules.mk flags
- krusli
  - `error: ‘_NUMPAD’ undeclared here`
    - seems broken during #3197
- waples
  - unused variable `cie_lightness`

Mostly simple fixes, but wont be fixed given the current stance on keymaps. (fun40 is not clear it has an owner)

**Comment by drashna** [comment]
@zvecr in the future, feel free to tag the owners of these keymaps.  That way stuff can git fixed. 

@jackhumbert @skullydazed, any issues with the backlight pin addition?

**Comment by noroadsleft** [comment]
@zvecr,

The `drashna` keymap is, well, @drashna's, and as I recall, he doesn't own a JJ40.

The `fun40` keymap seems to have confusing prominence. I think perhaps the user who contributed it deleted their GitHub account, and then someone else registered the same username. ([The PR pre-dates the account creation.](https://github.com/qmk/qmk_firmware/pull/2056))

The issues with the `krusli` keymap (@krusli) do indeed seem to be my fault. I distinctly remember having a reason for that change, but heck if I can remember what it was. :(

The `waples` keymap was submitted by... @Waples.


@drashna,

> That way stuff can _git fixed_.

:laughing: 

\- @noroadsleft 
*has made similar typos on occasion*

**Comment by drashna** [comment]
@noroadsleft correct.  I don't.  I do own several 4x12 ortho boards, and am using the community layout.  I've fixed the issue in a branch, so it shouldn't trigger the issue in the future. 

And yeah, I type git so much, "get" ends up "git" too often.  And I figured it was too good to fix here. :D

**Comment by krusli** [comment]
@noroadsleft `_NUMPAD` was a holdover from when I was trying a numpad layer on my jj40. I’ve also since moved to having all my ortho boards share the same layout (community layouts) too.

Let me go have a look if I don’t have anything I need, or jj40 specific left in there — if so then it should be fine to just take my keymap out of the jj40 dir.

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
