### PR TITLE
Atreus62 keymap macro fix

### PR DESCRIPTION
**Pull request by jprMesh**
I don't know why it has those previous commits in here. I can try to fix that if you'd like, but it looks like only my changes are actually in the PR.

### CODE REVIEW

**Comment by jackhumbert** [comment]
The current notation is actually preferred - if you'd like to use that definition, feel free to make a new macro!

**Comment by jprMesh** [comment]
Interesting. So in the current style is it required to have the full keycode, including KC_ for all keys? I'm curious as to the reason for this, as it would not save much screen space or effort over the native array representation.

**Comment by jprMesh** [comment]
Also, the documentation is not very clear in this respect. Both [the keymap FAQ](https://github.com/qmk/qmk_firmware/wiki/FAQ-Keymap) and [the tmk docs](https://github.com/tmk/tmk_core/blob/master/doc/keymap.md) refer to a syntax without the KC_ prefixes. Perhaps it needs to be updated?

**Comment by jackhumbert** [comment]
We have lots of keycodes that don't begin with `KC_`, so it allows people to use those without confusion. 

The documentation links referenced are remnants from TMK that haven't really been updated yet :)

**Comment by jprMesh** [comment]
See #1163

**Pull request closed without merging**
