### PR TITLE
Unicode input_mode persistance

### PR DESCRIPTION
**Pull request by Zay950**
Gave the Unicode input mode a spot in the eeprom. Every time set_unicode_input_mode() is called, the eeprom is updated with the target value. On the first call to process_unicode() after powering on, the previous value of input_mode is restored.

My keymaps for the planck and preonic are also included. Nothing super exciting in those.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Sorry for the late (holy cow) reply, but would you mind pulling from master to retrigger the travis check?

**Comment by Zay950** [comment]
Oh wow, I haven't touched this in a while, I can try to refamiliarize myself with it this weekend. Sorry, I'm still not very experienced with collaboration here, when you say 'pull from master', do you mean resubmit the pull request?

**Comment by jackhumbert** [comment]
Yeah, there's just some conflicts that need to be resolved before we can merge it - I think you should be able to merge them locally without a problem!

**Comment by Zay950** [comment]
Closing to resubmit pull request.

**Pull request closed without merging**
