### PR TITLE
Lime rev1: Fix QMK Configurator Implementation

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

Fixes the key sequence. Also applies human-friendly formatting to `info.json`.

image

cc @HellSingCoder (keyboard maintainer)

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
 
## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Comment by HellSingCoder** [comment]
Are you building one of these or just fixing up my mess? 😅

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
> Are you building one of these or just fixing up my mess? 😅

Noroadsleft is our configurator json expert.  So yeah, it's cleaning up some issues.  You can see the image where some of the keys are incorrectly placed.

**Comment by noroadsleft** [comment]
> Are you building one of these or just fixing up my mess?

Mainly cleaning up, but I'll confess there was a period of time during this that I wished I had one on my desk.

**Comment by HellSingCoder** [comment]
Thanks for the cleanup then! It now shows correctly on the QMK configurator, it's a shame that the OLED stuff is not compatible with that. I'm sure you found this already but, if you want one you can find anything you need [here](https://github.com/HellSingCoder/LimeKeyboard). Waiting on the new mouse pointer stuff to be merged to add that functionality to the joystick, then off to the LED support.

**Comment by noroadsleft** [comment]
I actually cloned your hardware repo while working on this once I realized it was open source. Hardware design fascinates me and I always have a good time looking on what other people are doing. :)

**Pull request merged**
