### PR TITLE
Remove hjson

### PR DESCRIPTION
**Pull request by Foxboron**
## Description

It seems like hjson is only used to provide an `OrderedDict` for the object type, but this is well supported by the `json` stdlib. This also removes a fairly obscure dependency from being added by distributions which hasn't had a proper update for years.

## Types of Changes
- [x] Enhancement/optimization

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by skullydazed** [comment]
Thanks for the suggestion!

The history is actually a little more complex, and we have future plans for hjson. Alas, there have been more than a few things that have taken higher priority than QMK this year and those developments have not happened as quickly as we hoped. 

One of the upcoming changes will be to use hjson for all json processing, to make info.json files easier and friendlier to edit. Because of that we'd like to keep this in so that everyone has it already.

**Comment by Foxboron** [comment]
Then the file should be `info.hjson`, they are two different formats. Personally I don't see why you would want this. It makes `qmk` artifacts hard to interact with across the board as you'd depend on the arbitrary "json" parser `hjson` being available other places. And considering `json` is already enforced loosely across the ecosystems I think it's a bad idea personally.

**Comment by fauxpark** [comment]
From what I can tell hjson actually cannot be removed, because its current (but only) use case is to parse [KLE raw data](http://www.keyboard-layout-editor.com/), which is in a nonstandard format. Changing the `hjson.loads()` there causes `qmk kle2json` to fail with eg:
```
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 30 (char 67)
```

**Comment by Foxboron** [comment]
Hm, I did test with data from the webpage, and `qmk pytest` was passing. Would be good to add test cases if it does produce non-standard JSON.

**Comment by fauxpark** [comment]
Apparently the test only checks the return code, however kle2json *should* be returning > 0 here. The problem is that setting the return code for a CLI subcommand is not as straightforward in MILC (as far as I know, skully may correct me here). Instead `assert 'Wrote out' in result.stdout` should be added to `test_kle2json()`.

**Comment by skullydazed** [comment]
> The problem is that setting the return code for a CLI subcommand is not as straightforward in MILC (as far as I know, skully may correct me here).

Setting is easy, it's taken from the return value of the entrypoint. If `kle2json` needs to return a non-zero value here it should, and it shouldn't be too hard to achieve.

**Pull request closed without merging**
