### PR TITLE
Update docs: QMK Introduction

### PR DESCRIPTION
**Pull request by evantravers**
1. There was an artifact of the old build system on here… a reference to Makefile instead of `rules.mk`

2. Reword the `config.h` section

This section didn't include the possibility of a user `config.h`, and it
wasn't clear exactly how the settings override works.

### CODE REVIEW

**Comment by evantravers** [comment]
@fredizzimo… would you mind making sure this is true and makes sense?

**Comment by drashna** [comment]
In the "Basic QMK Structure", it would be a good idea to add the Userspace structure too.  
That's namely rules.mk, readme.md, and config.h.

**Comment by evantravers** [comment]
@fredizzimo I've adjusted the boilerplate and the docs around it. I am correct in believing you don't need the `#endif` anymore?

@drashna I added a mention of the userspace to the section describing basic QMK structure. I just made a bare mention of it, and linked to the page of the docs describing the feature.

**Comment by jackhumbert** [comment]
Awesome - this should jump-start our switch to `#pragma once`. Thanks!

**Comment by evantravers** [comment]
@jackhumbert @fredizzimo would it be worthwhile to migrate some of the popular "default" keymaps to use `#pragma once`? I'll guess many people will most likely just `cp default <newfolder>` and not even read the docs till later.

**Comment by drashna** [comment]
Yeah, I think it would be.  But more importantly, it would be best to change the template's default:
https://github.com/qmk/qmk_firmware/blob/master/quantum/template/base/keymaps/default/config.h

**Comment by evantravers** [comment]
@drashna good idea… I didn't even know that was there. Opened a new PR for that one: #3415

**Pull request merged**
