### PR TITLE
Dimple: Fix Caps Lock LED behaviour

### PR DESCRIPTION
**Pull request by Erovia**
## Description
Fix one of my small mess-ups. The Caps Lock indicator should be On when the CL is on and Off when CL is off, not the other way around. :)

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
I think it would be a better idea to fix this in dimple.c instead, that way the function names are accurate.

**Comment by Erovia** [comment]
> I think it would be a better idea to fix this in dimple.c instead, that way the function names are accurate.

Isn't `writePinLow` for turning a led Off and `writePinHigh` turning it On?

**Comment by fauxpark** [comment]
It depends how the LED is wired. Usually it will be between the MCU and GND, so pulling the pin high will light up the LED. In this case the pin is configured as a "current source". But sometimes it is between the MCU and VCC, and setting the pin low turns the LED on - the pin is then a "current sink".

The same thing happens with backlighting, where some boards use a PNP or PMOS transistor to control the LEDs, which activates when the gate pin is low, instead of NPN/NMOS. This is why there is a `BACKLIGHT_ON_STATE` define provided :)

**Comment by Erovia** [comment]
@fauxpark, I've checked the PCB and the LED in question is indeed wired to VCC. Modified the code accordingly.

**Pull request merged**
