### PR TITLE
EC Pro X JIS Layout Touch-Up

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

- keymap refactor (grid-align keycodes)
- touch-up layout macro
  Fixes an issue that resulted in correct key assignment only if the keymap being compiled/flashed was based upon the `via` keymap. (`default` and `via` keymaps previously passed the same keycodes in a different order, while using the same layout macro)
  cipulot_ec_prox_jis_default

cc @Cipulot (keyboard maintainer)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
Implementation with this changeset included:
image

**Review by fauxpark — APPROVED** [review]

**Comment by Cipulot** [comment]
Tested with hardware and can confirm that this touch-up fixes the issue with the incorrect key assignment when compiling with VIA. I had to use 2 different positioning originally to mitigate this issue.

Thanks for the CC and look into this.

**Comment by noroadsleft** [comment]
@Cipulot,

Slight misunderstanding here. The `via` keymap in relation to the `info.json` layout data is fine; it's the `default` keymap that has the incorrect assignment. You can see this if you check out a QMK's current `master` branch, and run the following commands:

```
qmk compile -kb cipulot/ec_prox/jis -km via
qmk compile -kb cipulot/ec_prox/jis -km default -e VIA_ENABLE=yes
# adjust the path as needed:
shasum ~/qmk_firmware/cipulot_ec_prox_jis_*.bin
```

The resulting files should have the same hash because they're meant to be identical, but they don't. If you flash the `default` keymap *without* VIA enabled, Left Control will be assigned to where the Enter key is meant to be, and the whole home row will be off by one, as shown in the original post. (I'm not sure what the VIA clients do in this regard, should you flash the `VIA_ENABLE`d `default` keymap.)

**Comment by Cipulot** [comment]
@noroadsleft you're right, my bad. Tested with the `default` right now and yeah, as it was before it's shifted, the patch proposed fixes the shifting.

**Review by drashna — APPROVED** [review]

**Pull request merged**
