### PR TITLE
Add info.json for RGBKB Pan

### LINKED ISSUE #12215: [Bug] QMK Configurator for RGBKB Pan displaying all keys in 1 row with a very small font
## Describe the Bug

When selecting RGBKB Pan 32a or poroton_c keyboard, the display shows all keys in a single row, instead of 5 rows.

## Additional Context

image

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

image

@Legonut let me know if this needs any tweaking.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #12215 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by taithethai** [comment]
I saw this issue as well, but was too overwhelmed by it's many layouts/configurations. Should we try and gather them all now, or add them down the line as people need the particular layout?

**Comment by taithethai** [comment]
After looking it up again, I feel like the pan plates RGBKB sells are the three configurations that should be added at this time.

EEE
image

SSS
image

EEK
image

**Comment by fauxpark** [comment]
At the moment this PR just adds the info.json layout for the one existing layout macro in the code. I don't own this board so I can't say which keys are on which matrix positions, which is necessary to create additional layout macros. VIA support would be helpful here as the VIA JSON contains the matrix data, but I don't see it in their repo.

**Review by noroadsleft — APPROVED** [review]

**Comment by sadiwali** [comment]
If I wanted to add a new layout, do I just edit info.json and submit a pull request?

**Comment by fauxpark** [comment]
And pan.h, yes.

**Comment by dayofdoom** [comment]
I have a blank PCB in my posession. Is there anything I can do to contribute here?

**Comment by noroadsleft** [comment]
@dayofdoom,

Tracing the switch matrix would tell us what physical locations are where in the electrical sense, which would give us the information needed to create extra layout macros.

MechMerlin's [Porting with Ports YouTube series](https://www.youtube.com/watch?v=w78_LvpdaXA&list=PLZlceRZZjRuhgztKmHPFdnpfbnEf1dqzk&index=2) can walk you through this.

**Pull request merged**
