### PR TITLE
Ergo42: Refactor and Configurator support

### PR DESCRIPTION
**Pull request by noroadsleft**
Refactor:

- Matrix `KEYMAP` renamed to `LAYOUT`
- Matrix `KC_KEYMAP` renamed to `LAYOUT_kc`
- Keymaps
  - now `#include QMK_KEYBOARD_H`
  - white space changes

Configurator:

- added `info.json`

### CODE REVIEW

**Comment by drashna** [comment]
Wouldn't it be better to use `LAYOUT_ortho_4x14` everywhere?

**Comment by noroadsleft** [comment]
> Wouldn't it be better to use `LAYOUT_ortho_4x14` everywhere?

I suppose, if we're doing the community layouts thing here.

----

Switched the macro names around:

- `LAYOUT_kc` <-> `LAYOUT_kc_ortho_4x14`
- `LAYOUT` <-> `LAYOUT_ortho_4x14`

**Comment by drashna** [comment]
Yeah, travis is having issues ATM. So it's not you/your PR.

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
