### PR TITLE
Fix rotation with 'rx' in Signum keyboard

### PR DESCRIPTION
**Pull request by i5ar**
The Signum keyboard have key rotations, unfurtunately they are not correct.

## Description

Fix key rotations and move keys 1/4 unit to the right.
For the time being you can use [this](https://i5ar.github.io/yake/) to verify the rotation.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/qmk/qmk_configurator/issues/310

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
QMK Configurator doesn't support rotation, actually.  IIRC.

**Comment by noroadsleft** [comment]
> QMK Configurator doesn't support rotation, actually. IIRC.

This. Rotation values are valid data, but the Configurator's UI doesn't know how to interpret them. There was also the question internally of the best way to handle rotation. The info.json format is based on KLE's, but KLE's structure is stateful, while our format is stateless. Being stateless, what happens to one key has zero bearing on what happens to subsequent keys.

@skullydazed would also know something about the state of this.

**Comment by i5ar** [comment]
> QMK Configurator doesn't support rotation, actually. IIRC.

I know, I made this PR because someone has added rotations (This PR fixes rotations, doesn't add them). With this fix you can use this keyboard to test the implementation in the future.

> The info.json format is based on KLE's, but KLE's structure is stateful, while our format is stateless. Being stateless, what happens to one key has zero bearing on what happens to subsequent keys.

KLE (layout.json) is stateful but the UI shows stateless coordinates and rotations so those are pretty easy to verify.
path4149-9-1-3-69

This is the fix for that specific key: https://github.com/qmk/qmk_firmware/blob/e439f32592e7b83d261385c4fbeb78f1c941002b/keyboards/signum/3_0/elitec/info.json#L47

KLE implements `r`, `rx` and `ry` the same way SVG does so, regardless KLE being stateful those are gereral concepts for rotation.
[YAKE ](https://i5ar.github.io/yake/)is based on SVG so I only had to had `transform="rotate(<r> <rx> <ry>)"`.

**Comment by drashna** [comment]
I think this may have been fixed in another PR, sorry!

Otherwise, there is a merge conflict here.

**Pull request closed without merging**
