### PR TITLE
Fixed grep issue in bootloader build target

### PR DESCRIPTION
**Pull request by MxBlu**
Changed use of '\s' in grep to '[ \t]' for portability.

@TerryMathews Please test and confirm this works for you.

### CODE REVIEW

**Comment by mechmerlin** [comment]
I tried running this on macOS High Sierra 10.13.6. Not even sudo gets me through the permissions errors

```
sh: tmk_core/make_dfu_header.sh: Permission denied
```

Had to chmod it to get compiling.

**Comment by yiancar** [comment]
please @MxBlu make  the file executable:)

**Comment by MxBlu** [comment]
Will do, is that just a matter of running `chmod a+x` on it?

**Comment by yiancar** [comment]
should be yes

**Comment by drashna** [comment]
@jackhumbert or @skullydazed Thos look good?

**Pull request merged**
