### PR TITLE
fix rgblight.c:rgblight_check_config()

### PR DESCRIPTION
**Pull request by mtei**
## Description

fix rgblight.c:rgblight_check_config();

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #5334

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mtei** [comment]
If there is something wrong with the value of rgblight_config, I think that it should default it. So, I tried it more simple.

**Comment by mtei** [comment]
It's been almost a month since I opened this PR. Is there still some obstacle in deciding whether to adopt or reject this?

**Comment by drashna** [comment]
waiting on others to review.  I know @skullydazed been working his way through the backlog. 

Also, I'm not a fan of resetting the the config if it's out of bounds, but rather limit it to the correct range.  
But I can see the benefits of this approach.

**Comment by mtei** [comment]
It is very rare for `rgblight_check_config()` to modify the value of rgblight_config. In most cases, the rgblight_config value stored in EEPROM is correct. 

rgblight.o including `rgblight_check_config()` is 180 bytes larger. I do not feel worthwhile to always enable `rgblight_check_config()` to allow for this 180-byte size increase.

So I made `rgblight_check_config()` an option, and specified `RGBLIGHT_EEPROM_CHECK=yes` at make time to make `rgblight_check_config() `effective.

If you can not agree with the above explanation, please tell me that. In that case I change  `rgblight_check_config()` to always be enabled.

**Comment by drashna** [comment]
I'm not sure that this change is needed anymore. 

There was a recent change to the rgb light code, that changes the hue range to 0-255, and switches the hue variable to a `uint8_t`.  In theory, this should handle out of bound errors better.

**Comment by mtei** [comment]
The current compilation size is as follows.

```
$ make crkbd:default
 * The firmware size is fine - 26372/28672 (2300 bytes free)
$ make RGBLIGHT_EEPROM_CHECK=yes crkbd:default
 * The firmware size is fine - 26486/28672 (2186 bytes free)

2300 - 2186 = 114
```

What do you think of increasing 114 bytes by enabling `rgblight_check_config()` ?

**Comment by drashna** [comment]
There are some merge conflicts here now.

**Comment by mtei** [comment]
> There was a recent change to the rgb light code, that changes the hue range to 0-255, and switches the hue variable to a `uint8_t`. In theory, this should handle out of bound errors better.

I rethought and decided to close this request.

**Pull request closed without merging**
