### PR TITLE
TV44 keymap changes

### PR DESCRIPTION
**Pull request by belak**
There are a few oddities in here. Specifically KEYMAP_COMMAND (and in extension, KEYMAP_ARROW_COMMAND):

The macro arguments should match what the keymap looks like, even if it's in an odd order. However, note that it doesn't seem to match https://github.com/evangs/tmk_keyboard/blob/master/keyboard/low-writer/keymap_common.h#L63 but that the macro was defined by using the key ordering on the pcb, rather than the logical arrangement (In this macro I used `K30, K31, K34, K32` because that's how it works on my board).

```
#define KEYMAP_COMMAND( \
    K00, K01, K02, K03, K04, K05, K06, K07, K08, K09, K0A, K0B, \
    K10, K11, K12, K13, K14, K15, K16, K17, K18, K19, K1A, K1B, \
    K20, K21, K22, K23, K24, K25, K26, K27, K28, K29, K2A, K2B, \
    K30, K31, K34, K32,      K33, K37,           K38, K39, K3B  \
) \
{ \
    { K00,   K01,   K02,   K03,  K04,   K05,   K06,   K07,   K08,   K09,   K0A,   K0B }, \
    { K10,   K11,   K12,   K13,  K14,   K15,   K16,   K17,   K18,   K19,   K1A,   K1B }, \
    { K20,   K21,   K22,   K23,  K24,   K25,   K26,   K27,   K28,   K29,   K2A,   K2B }, \
    { K30,   K31,   K32,   K33,  K34,   KC_NO, KC_NO, K37,   K38,   K39, KC_NO,   K3B }  \
}
```

I plan to add another keymap eventually which will work with my board using the KEYMAP_ARROW_COMMAND, so it may be worth waiting until I can finish that to merge this.

I've kept commits as separate as possible, so it's easy to revert any one of the changes I made.

### CODE REVIEW

**Comment by belak** [comment]
I've confirmed on my board (which uses the arrow_command layout) that all the keys work just fine. It looks like I just forgot to soldier down a switch before which is why the arrow layout wasn't working properly.

**Comment by belak** [comment]
This should be ready now. I've just finalized the first version of my minivan layout (technically a tv46 I guess, but it's the same layout for the most part).

**Comment by jackhumbert** [comment]
Are you sure you don't have any EEPROM setting enabled? `AG_SWAP` would swap the place of ALT and GUI, which would make it seem like your `K34` and `K32` are swapped. You can [clear your EEPROM](https://github.com/qmk/qmk_firmware/tree/master/quantum/tools) to double-check.

**Comment by belak** [comment]
Yep, I'm sure. I originally tested by setting the bottom keys to 1, 2, 3, 4 on the left and 5, 6, 7, 8 on the right and hitting them in order. I just tested it again by clearing the EEPROM and trying it again. Same result.

If you look on the bottom of the board, it's pretty easy to see the labeled keys and that they're in that order. I'd be happy to provide a picture when I get home and can take it apart again if you'd like.

**Comment by belak** [comment]
Also if you look at this: https://github.com/evangs/tmk_keyboard/blob/master/keyboard/low-writer/keymap_command.c#L19

You can see the key ordering on the bottom as `LCTL,  FN1,  LGUI,     ENT, H,      SPC,   RALT,   RSFT,  FN2` even though the main spacebars are set to ENT and SPC.

**Comment by jackhumbert** [comment]
Gotcha :) cool, thanks!

**Comment by smt** [comment]
@belak Hey thanks a lot for the update :+1:

**Pull request merged**
