### PR TITLE
Add support for SH1107 oled

### PR DESCRIPTION
**Pull request by mrninhvn**
## Description

- Add new file for sh1107 oled driver
- Update makefile to make it clear how to configure and easily add new drivers in the future.
Origin source code from: https://github.com/KarlK90/qmk_firmware/tree/yaemk-split-kb/drivers/oled

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
as per discord conversion, the sh1107 changes should be rolled into the existing ssd1306/sh1106 driver, rather than as a separate file.   There is a LOT of overlap, so it reduces redundant code, and reduces the maintenance burden. 

I've opened a PR with that in mind: 
https://github.com/mrninhvn/qmk_firmware/pull/4

Also, you may want/need to rebase upon develop, as there are some changes you don't have.

**Comment by mrninhvn** [comment]
> as per discord conversion, the sh1107 changes should be rolled into the existing ssd1306/sh1106 driver, rather than as a separate file. There is a LOT of overlap, so it reduces redundant code, and reduces the maintenance burden.
> 
> I've opened a PR with that in mind: [mrninhvn#4](https://github.com/mrninhvn/qmk_firmware/pull/4)
> 
> Also, you may want/need to rebase upon develop, as there are some changes you don't have.
> 
> Also, @KarlK90

From my perspective, independent files for each driver are better.
- No need to change the file name every time add a new one.
- No need to change main driver file, so review and merge will be faster.
- Maintenance burden, yes, but that keeps the bugs from affecting all.

Each driver file can be optimized to reduce overlap.

Take a look at zephyr display driver: https://github.com/zephyrproject-rtos/zephyr/tree/main/drivers/display

**Comment by tzarc** [comment]
#10174 decouples hardware drivers from rendering code.

This old code doesn't, and is not really in a position to have wholesale modifications done to it, especially given that a replacement API is in the pipeline.

**Comment by mrninhvn** [comment]
> #10174 decouples hardware drivers from rendering code.
> 
> This old code doesn't, and is not really in a position to have wholesale modifications done to it, especially given that a replacement API is in the pipeline.

So, All changes will be postponed until new API is available right?
Or should i change according to @drashna suggestion in the meantime?

**Comment by KarlK90** [comment]
@mrninhvn Ha nice to see that you picked up code from my keyboard :slightly_smiling_face:.

> So, All changes will be postponed until new API is available right?
> Or should i change according to @drashna suggestion in the meantime?

 I'll take the liberty to answer that question if no one minds.

This driver code should not be modified until #10174 lands as it substantially changes the whole display and rendering API of QMK. AFAIK @tzarc also tested SH1107 OLEDs with the new code but I might be wrong. So any new driver should follow the new style of display drivers and not extend the existing system.

**Comment by mrninhvn** [comment]
> @mrninhvn Ha nice to see that you picked up code from my keyboard 🙂.
> 
> > So, All changes will be postponed until new API is available right?
> > Or should i change according to @drashna suggestion in the meantime?
> 
> I'll take the liberty to answer that question if no one minds.
> 
> This driver code should not be modified until #10174 lands as it substantially changes the whole display and rendering API of QMK. AFAIK @tzarc also tested SH1107 OLEDs with the new code but I might be wrong. So any new driver should follow the new style of display drivers and not extend the existing system.

Ah i see, thank you for your answer.
@tzarc If i want to work with SH1107 using new API, where can i start?

**Comment by KarlK90** [comment]
One place to start would probably be the PRs that others already opened for QP on [tz's github](https://github.com/tzarc/qmk_firmware/pulls) there is also an open one for mono displays but this where I stop with my suggestions as I don't want to send you on the wrong track. ;-)

**Comment by drashna** [comment]
Closing this now.  SH1107 support has been added to oled driver, and tzarc has a draft pr for sh1106 out.

**Pull request closed without merging**
