### PR TITLE
Fix for issue #10386 - Can't compile preonic:dudeofawesome

### PR DESCRIPTION
**Pull request by FilipParyz**
## Description
I've wanted to help @NeoScaler with his bug. He couldn't compile Preonic (rev3) with dudeofawesome keymap as it wasn't prepared for STM and it had some issues described in [#10386](https://github.com/qmk/qmk_firmware/issues/10386).

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* [#10386](https://github.com/qmk/qmk_firmware/issues/10386)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage) - I've compiled but can't flash the keyboard as I don't have it available.

### CODE REVIEW

**Comment by zvecr** [comment]
image

We wont be able to accept this PR in its current form, due to the vast amount of unnecessary changes. Per the contribution guide, it will also require sign off from @dudeofawesome.

**Comment by FilipParyz** [comment]
That seems terrible, but how can I keep my repo up to date and not have all the Merges from original repo show up in the PR's later? I know I f***ed up on the develop merge so I reverted it but that still seems to mess with the PR. How to keep the branch clean and up to date?

**Comment by drashna** [comment]
The simplest way is to rebase, not merge.  This creates a cleaner history and prevents this sort of issue. 

noroadsleft, being the awesome person he is has a great guide on how to work with git and github and how to keep things up to date. 
https://docs.qmk.fm/#/newbs_git_best_practices

And specifically: https://docs.qmk.fm/#/newbs_git_resynchronize_a_branch

**Comment by drashna** [comment]
Worst case, I think that this may fix your issue: 
```
git fetch upstream
git reset upstream/master --hard
git cherry-pick 38ac0356aff5b31fc32288b9b026bfc54bec4035
git push --force-with-lease
```

**Comment by FilipParyz** [comment]
Okay! I've finally managed to fix my issues with the great help from you @drashna ! Thank you very much :)

The build succeeded and it could be merged but first we need a sign of from @dudeofawesome 
Louis, do we have your permision for editing your code and merging it into the official QMK repo?

**Comment by dudeofawesome** [comment]
Hi, sorry for the late response. Everything LGTM!

**Comment by FilipParyz** [comment]
Hey @drashna :) We've got the approval, does my fix look good enough to merge? :D

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by fauxpark** [comment]
Thanks!

**Comment by FilipParyz** [comment]
Thank you guys very much :D

**Pull request merged**
