### PR TITLE
knight malposition fix

### PR DESCRIPTION
**Pull request by moyi4681**
knight malposition fix

### CODE REVIEW

**Comment by zvecr** [comment]
The LAYOUT macro changing has some implications for users who have already created keymaps locally, but also with Configurator.

It looks like the info.json is currently top aligning the numpad enter key. Is the aim here to fix Configurator?

**Comment by noroadsleft** [comment]
Looking this over, I agree with @zvecr – the info.json file should be edited, especially if the firmware works as intended when compiled outside of Configurator.

**Comment by moyi4681** [comment]
In fact, the keyboard hasn't been put on the shelves yet. We are testing and fixing some of the problems

**Comment by noroadsleft** [comment]
> In fact, the keyboard hasn't been put on the shelves yet. We are testing and fixing some of the problems

In that case, I'm okay with these changes.

**Comment by zvecr** [comment]
No qmk_configurator default keymap so should be good to go

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
