### PR TITLE
fix qmk docs broken link in docs/ja/*.md and docs/newbs_best_practices.md

### PR DESCRIPTION
**Pull request by mtei**
## Description

* Fix broken link
  * docs/newbs_best_practices.md
    ```diff
    -2. You've [set up your build environment](newbs_getting_started.md?id=environment-setup).
    +2. You've [set up your build environment](newbs_getting_started.md#set-up-your-environment).
    ```
  * docs/ja/*.md

* Improvements to simplify for the translation of links
  * Japanese version. 
    ```diff
    -## 環境構築
    +## 環境構築 :id=set-up-your-environment
    ```

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Would it be possible to use this method instead: https://docsify.now.sh/helpers?id=customise-id-for-headings
It looks much neater than HTML tags everywhere.

**Comment by mtei** [comment]
Thank you for letting me know docsify.

I tried the following command.

           python3  -m http.server 9000

And I found that the behavior differs between docsify and file display on the repository screen of github.

If you link the following in `docs/ja/newbs.md`, you will jump to the English version of the document.
```
* [はじめに](newbs_getting_started.md)
* [コマンドラインを使用して初めてのファームウェアを構築する](newbs_building_firmware.md)
```
This is different from the file display on the repository screen of github.

To jump to the Japanese document, you had to write:
```
* [はじめに](ja/newbs_getting_started.md)
* [コマンドラインを使用して初めてのファームウェアを構築する](ja/newbs_building_firmware.md)
```

When I checked Chinese and Spanish documents at `https://docs.qmk.fm`, I clicked on a link in the written document and jumped to the English version of the document.
This is not the expected behavior.

**Comment by fauxpark** [comment]
Yes, GitHub does not understand the translation system Docsify uses. It's not really unexpected behaviour as they are rendering the Markdown in different ways.

However, it looks as though you can manually prefix the links with the desired language and Docsify will not prefix it again. I think this will make the links correct on both.

**Comment by mtei** [comment]
Should I add `ja/` when translating into Japanese?

English version xxxx.md
```
  * [foo bar](foo_bar.md)
```

Japanese version xxxx.md
```
  * [ほげはげ](ja/foo_bar.md)
```

If so, can you write that in `docs/translating.md` ?

**Comment by fauxpark** [comment]
Yup - it seems Docsify is smart enough to not make it `ja/ja/foo_bar.md`.

I'll make a PR to update the translation guidelines in a bit, I also noticed some other things which could be improved about that page.

**Comment by mtei** [comment]
As a result of the discussion I made corrections. I think this is complete.

**Comment by mtei** [comment]
I opened #7430 and #7431 which divided this PR into two.

**Pull request closed without merging**
