### PR TITLE
uni660rev2 added

### PR DESCRIPTION
**Pull request by danielhklein**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by danielhklein** [comment]
@zvecr if I understand how Via [reads keymaps](https://caniusevia.com/docs/configuring_qmk/#create-a-keymapc-in-keyboardskeyboardnamekeymapsvia) correctly, and the fact that the ISO and ANSI PCBs are wired differently rather than just a layout change, we need a separate Via keymap directory for each, correct? That would prevent having a unified keymap directory for rev2.

**Comment by zvecr** [comment]
In which case, `keyboards/sirius/uni660/rev2/rev2.h` should not contain both LAYOUT macros, and instead a iso.h and ansi.h created in their respective directories.

**Comment by danielhklein** [comment]
The suggested changes have been made

**Comment by zvecr** [comment]
Thanks!

**Pull request merged**
