### PR TITLE
[Bug] Fix the bug that  chibios ws2812 spi divisor cannot be customized define

### PR DESCRIPTION
**Pull request by jiaxin96**
## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* When customizing WS2812_SPI_DIVISOR, an error will be reported for redefined. Add a suffix to fix this bug to allow users to customize the spi frequency.

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
This has a merge conflict that needs to be resolved.

**Comment by jiaxin96** [comment]
> This has a merge conflict that needs to be resolved.

I have tested it on my F401 keyboard and it works normally, and I continue to search the qmk directory, the change will not affect the keyboard and related documents.

**Comment by drashna** [comment]
> > This has a merge conflict that needs to be resolved.
> 
> I have tested it on my F401 keyboard and it works well, and I have searched the qmk directory, the change will not affect any keyboards and related documents.

It still has merge conflicts that MUST be resolved.  As in, we are unable to merge it until those conflicts are resolved.  The option is disabled. 

Specifically, it looks like you need to rebase your PR before it can be accepted. 
If you need help with this, we can help out. 



Also, it looks like the only change here is that the define names are changed, with no change to functionality/behavior.

**Comment by zvecr** [comment]
Needs to be like <https://github.com/qmk/qmk_firmware/commit/7dd524f6412b7b1eb61f93afa2b649e1d51ad86e>

**Pull request closed without merging**
