### PR TITLE
change to cmm.studio saka68 folder. split to solder and hotswap, add hotswap fimware

### PR DESCRIPTION
**Pull request by CMMS-Freather**
## Description
split the folder to hot-swap and solder folder 
adds hot-swap firmware

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by CMMS-Freather — COMMENTED** [review]
everything looks good but I don't know why for the hotswap readme.md, it gives me errors and fails the check

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
It's failing to compile because the files exist in the saka68 folder already, so they're getting picked up, used, and causing conflicts. 
eg:
https://github.com/qmk/qmk_firmware/tree/master/keyboards/cmm_studio/saka68

You probably need to update your repo, remove the files and push an update.  This should fix the issue.

**Comment by CMMS-Freather** [comment]
> It's failing to compile because the files exist in the saka68 folder already, so they're getting picked up, used, and causing conflicts.
> eg:
> https://github.com/qmk/qmk_firmware/tree/master/keyboards/cmm_studio/saka68
> 
> You probably need to update your repo, remove the files and push an update. This should fix the issue.

In my repo it is successfully split into two folders. I did attempt to push, but I am not too sure if that worked. 
you can see the updated files here
https://github.com/CMMS-Freather/qmk_firmware/tree/master/keyboards/cmm_studio/saka68

**Comment by drashna** [comment]
Yeah, but the QMK repo doesn't have that, and your PR doesn't explicitly remove them.  So it creates this weird issue. 

You want to do this, I think: 
https://docs.qmk.fm/#/newbs_git_resolving_merge_conflicts

**Comment by CMMS-Freather** [comment]
> Yeah, but the QMK repo doesn't have that, and your PR doesn't explicitly remove them. So it creates this weird issue.
> 
> You want to do this, I think:> https://docs.qmk.fm/#/newbs_git_resolving_merge_conflicts

checked the link. seem like it is a kind of complicated progress. is it possible to have you  guys delete the whole folder first then I make a new pr to merge in the form of my new folders?

**Comment by drashna** [comment]
Well, you could get away with just: 
```
git fetch upstream
git rebase upstream/master
```

You may run into merge conflics, which the rest of the doc covers well. 


Another option is that you could open a PR on github from qmk/qmk_firmware to your repo, and merge that.  That may be a bit simpler.

**Comment by CMMS-Freather** [comment]
> Well, you could get away with just:
> 
> ```
> git fetch upstream
> git rebase upstream/master
> ```
> 
> You may run into merge conflics, which the rest of the doc covers well.
> 
> Another option is that you could open a PR on github from qmk/qmk_firmware to your repo, and merge that. That may be a bit simpler. Eg:
> 
> [CMMS-Freather/qmk_firmware@master...qmk:master](https://github.com/CMMS-Freather/qmk_firmware/compare/master...qmk:master)

have it updated and seem to work now. thank you so much. submit for review

**Review by CMMS-Freather — COMMENTED** [review]
Good to go. Thank you

**Review by tzarc — APPROVED** [review]

**Pull request merged**
