### PR TITLE
Slight tidy up of keyboard task loop

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Cherry picked from 15722 to hopefully minimise changes.

Main aim is to reduce the size of `keyboard_task`, as its become fairly bloated by the matrix scanning logic. Functionality should hopefully be identical after the changes.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by KarlK90** [comment]
This looks good! Do you mind joining the forces with #15292 especially commit 314b067f0de8a4abd3b1d7de20049672d88d0643 which targets the same code region and goals?

**Comment by zvecr** [comment]
Would rather not couple this minor change to others, given its aim is to minimise diffs of future works.

I guess the crossover is more with #15722, as both intend to modify behaviour.

**Review by daskygit — APPROVED** [review]
Looks good, tested on a couple of boards too.

**Comment by KarlK90** [comment]
> Would rather not couple this minor change to others, given its aim is to minimise diffs of future works.
> 
> I guess the crossover is more with #15722, as both intend to modify behaviour.

Fair enough! I also had eyes on that one but as it was still in draft I decided that it would make more sense to post it here. Hmmn, what do you think about my proposal to do it for #15722 ?

**Review by drashna — APPROVED** [review]

**Pull request merged**
