### PR TITLE
Merge in some custom keymaps from forked repository

### PR DESCRIPTION
**Pull request by RobertDhaene**
I have created some custom keymaps for the Iris and Planck keyboard for my personal sets.

### CODE REVIEW

**Comment by drashna** [comment]
Looks like ChibiOS got changed here.
Running `make git-submodule` and pushing a new commit may fix that.

**Comment by RobertDhaene** [comment]
Hi @drashna I just ran that command to update the submodules but git is showing no changes. Do you know why that is?

Thanks for the help!

**Comment by drashna** [comment]
No, not sure. 

@jackhumbert may have a better idea why

**Comment by RobertDhaene** [comment]
I am just manually updating the submodule hashes to match what's in master. That should get the PR fixed. It will be interesting to see why make git-submodule did not work. I can take a look perhaps tomorrow.

**Comment by RobertDhaene** [comment]
Ok, have the submodules fixed up.

**Comment by drashna** [comment]
Awesome, thanks!

**Pull request merged**
