### PR TITLE
ST7565 tidyup

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Some cleanups to help me work on migrating the ST7565 out of uGFX.

 - Modified visualizer.mk to decouple compilation of the ST7565 and its backlight (I only have a white backlight display; the modules in the Ergodox Infinity are RGB)
 - For consistency, replaced the logo image with that used by the SSD1306 driver
 - Updated the Ergodox Infinity's board file, and the template under drivers, to use QMK-style GPIO macros
 - Updated the ST7565 driver itself to more closely align with its current form in upstream uGFX

There should be no functional change, however, since I only have a 128x64 display, and the Ergodox Infinity's are 128x32, I'm not 100% certain that these changes work for the Infinity. So I would be grateful if anyone with one of these boards could test this PR.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
There is now some slight functional difference - the "Drive Strength Enable" bit is not set for the MOSI and SCLK pads when configuring them as alternate mode 2; however, I am not entirely sure it is necessary anyway.

This was done because it seems nontrivial to get at the PCR register using only the QMK-style pin - `PAL_PORT()` gives us a `GPIO_TypeDef` but `PCR` lives in a `PORT_TypeDef`.

**Comment by fauxpark** [comment]
Travis errors unrelated (issue with default keymaps for `kingly_keys/ave`).

**Comment by drashna** [comment]
(feel free to tag me for testing, I do have an ergodox infinity, and I will see about testing these changes)

**Comment by fauxpark** [comment]
I actually just today got my breakout PCBs for the specific LCD the Infinity uses...it shows the logo briefly then goes full black, although if I look at it from a certain angle I can see the data is indeed displaying. Modifying the contrast seems to do nothing.

**Comment by fauxpark** [comment]
It's now working on the 128x32, but not the 128x64. It seems the `ST7565_RESISTOR_RATIO` value needs to be 0x3 for 128x64, and 0x1 for 128x32. However, this is not exposed as a configuration option, so I had to pick one.

I may circle around and try to get it working automatically for both, at some point, but for now all that's left to check is the Kinetis SPI stuff. @drashna, over to you.

**Comment by drashna** [comment]
Can confirm it works, and that the colors also work.

**Review by drashna — APPROVED** [review]

**Pull request merged**
