### PR TITLE
[Core] Process all changed keys in one scan loop, deprecate `QMK_KEYS_PER_SCAN`

### PR DESCRIPTION
**Pull request by KarlK90**
**For Reviewers:** The changeset is huge as many keyboards where adjusted in the process.
The important changes to core functionality are in separate and small commits. I have taken great care to not break any existing keyboard, hopefully this was successful.

### Short version

* Move matrix processing from `keyboard_task()` into seperate `matrix_task()`
* Process all key changes in one scan loop if there are changes in the key matrix
  * Deprecate `QMK_KEYS_PER_SCAN` (#2022) which previously allowed to process more than one key in a single scan
  * ~~Make `debounce()` algorithms signal changes in the debounced "cooked" keyboard matrix via a return value~~ (will be a separate PR)
* ~~Add `LEGACY_MATRIX_SCAN` bodge and info message for custom matrix scanning implementations that do not signal matrix changes~~ (will be a separate PR)

### Long version

This PR moves the core matrix processing from `keyboard_task()` into a separate `matrix_task()`. Processing all key changes of the matrix is also done in one scan loop if and only if there are key changes to be processed. ~~This lazy evaluation of key changes is done by making the `debounce()` algorithms signal changes in the debounced "cooked" keyboard matrix via a return value.~~ Previously the processing of more than one key change per scan loop could be enabled by setting `QMK_KEYS_PER_SCAN` to a number like 4 or 5 which was introduced in #2022 and I guess as a precaution not enabled for other keyboards. ~~As a temporary bodge custom keyboard matrix implementations get a config flag `LEGACY_MATRIX_SCAN` which activates a info message like this:~~

## Size impacts

**ARM: +220 Bytes**

```
❯ ./util/size_regression.sh -d maintenance/keyboard-scan-task planck/rev6:default
Size:    53368, delta:    +32 -- 9f6e1703bc Process the complete matrix in one scan loop
Size:    53336, delta:   +188 -- 7d5d9c3472 Remove QMK_KEYS_PER_SCAN option
Size:    53148, delta:     +0 -- 168a631720 Add support for MacroCat Keyboard (#17480)
```

**AVR: -154 Bytes**

```
❯ ./util/size_regression.sh -d maintenance/keyboard-scan-task crkbd:default
Size:    26254, delta:    +60 -- 9f6e1703bc Process the complete matrix in one scan loop
Size:    26194, delta:   -214 -- 7d5d9c3472 Remove QMK_KEYS_PER_SCAN option
Size:    26408, delta:     +0 -- 168a631720 Add support for MacroCat Keyboard (#17480)
```

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* (Hopefully) Reduce code complexity by refactoring the matrix loop into a separate task
* Make `QMK_KEYS_PER_SCAN` the default behavior as this benefits some users and won't hurt others
* Clean-up some `matrix_scan()` API and use its potential for lazy evaluation of the matrix
* Remove dead code

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
> Remove deprecated matrix_is_modified() dead code

This should really be tackled in its own PR.

**Comment by drashna** [comment]
Doesn't appear to break anything, at the very least.  been running it for a full day now, and appears to work fine.

**Comment by KarlK90** [comment]
@zvecr I have dropped the commit and openend #15349 that removes yet another unused method.

**Comment by KarlK90** [comment]
Rebased.

**Comment by KarlK90** [comment]
Rebased.

**Comment by Xelus22** [comment]
Just also want to comment that I have been using this and seems to be working fine.

**Comment by KarlK90** [comment]
Rebased.

**Comment by tzarc** [comment]
Deferred to Q3 cycle due to conflicts.

**Comment by ecerulm** [comment]
@KarlK90 ,  is this PR still alive?

**Comment by KarlK90** [comment]
@ecerulm currently on hold until the rp2040 support is finished

**Review by tzarc — APPROVED** [review]

**Comment by alex-ong** [comment]
Thanks for the merge; does QMK now send multiple keys in one report? or is that waiting for #12686?

**Pull request merged**
