### PR TITLE
Add diff logic to py/file format subcommands

### PR DESCRIPTION
**Pull request by zvecr**
## Description

cherry-picked from #11909, this aligns the other formatting commands with the current `cformat` behaviour
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by skullydazed** [comment]
Have you checked to see how/if this overlaps with #11476?

**Comment by zvecr** [comment]
This PR has 3 main parts. The first is avoiding formatting files i have not changed, which is happening a lot on develop the last week or so. The 2nd is consistency between commands. Lastly is to allow better scripting, to the `trilom/file-changes-action` action with something like `qmk fileformat $(cat $HOME/files.txt)`, or `git diff --name-only upstream/master | qmk fileformat`.

While I dont expect massive changes in CI, binding them a little less tightly has some advantages. However I think both PRs plus <https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message> will give us a good formatting workflow.

**Comment by skullydazed** [comment]
> The first is avoiding formatting files i have not changed, which is happening a lot on develop the last week or so.

One of the things #11476 does is to make improperly formatted files a failing lint check, which should prevent this.

> The 2nd is consistency between commands.

#11476 addresses this too.

> Lastly is to allow better scripting

Better scripting is good, and I want to make sure we support your goals here. It seems like there are a lot of code change overlaps with #11476 here which is why I wanted to see how these two overlap.

**Comment by zvecr** [comment]
#11476 doesn't really solve the consistency issues i'm tackling here. Note that with this PR, the 3 formatting command have the same behaviour when it comes down to passed files, `-a` and the `git diff` behaviour.

**Review by Erovia — APPROVED** [review]
I think `subprocess.run` could be changed/updated to `cli.run`, but otherwise LGTM.

**Comment by zvecr** [comment]
Replaced by 15155 and 15156.

**Pull request closed without merging**
