### PR TITLE
Tidy up dztech default keymaps and info.json

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Mostly whitespace/alignment. I have more queued for the rest of the keyboard code.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
I don't quite understand the point of them, really. `key_count` could/should be dynamically calculated based on the number of elements in the object? And as for the labels, shouldn't info.json just define the geometry of the layout?

**Comment by noroadsleft** [comment]
It makes the files easier to debug if there are problems.

`key_count` can be dynamically calculated, but explicitly saying how many keys there *should* be makes it easier to check for mismatches. `label` makes it easier to identify keys at a glance if they're incorrectly positioned or out of sequence.

**Comment by fauxpark** [comment]
Sure, but when a decent GUI editor comes along it'll render that pretty much useless, right? Since if you're missing a key or have one too many it would be fairly obvious. And what about layouts that don't resemble the typical ANSI/ISO format? I guess I just don't see why info.json should have an opinion on which keys "do" what, unless the goal for it is to also include a default set of keycodes or something.

**Comment by noroadsleft** [comment]
> Sure, but when a decent GUI editor comes along it'll render that pretty much useless, right? Since if you're missing a key or have one too many it would be fairly obvious.

A GUI editor IMO only solves this if two things happen:

1. Said editor also checks the key count given in the keyboard.h file
2. Said editor also lets you edit the JSON directly for solving out-of-sequence issues (think ISO Enter being on QWERTY Row vs. Home Row)

>  I guess I just don't see why info.json should have an opinion on which keys "do" what, unless the goal for it is to also include a default set of keycodes or something.

It doesn't; it's mainly for the human reading the file, though yanfali and I did recently discuss the possibility of doing exactly what you've described.

**Pull request merged**
