### PR TITLE
Adjusted the linear led table and hsv_to_rgb to better handle 255 hue

### PR DESCRIPTION
**Pull request by XScorpion2**
## Description

255 hue separated into 6 regions is exactly 42.5. The code we have today uses 43 instead which is close. However this can cause some artifacts to occur in certain hues. So to handle this correctly I adjusted the math slightly to get the same results as float math but using ints. This greatly improves the qualit of the hsv to rgb conversion.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
This adds some noticeable flickering on a number of the animations. :(

**Comment by XScorpion2** [comment]
@drashna which animations and color values?

**Comment by drashna** [comment]
Any animation that fades into other colors.  Such as left to right, up to down, pinwheel, etc. 

As for the colors... well, for rgblight, magenta shows up as blue.  I didn't test many of the other colors, yet.

**Comment by XScorpion2** [comment]
OK, if you can give me a few hsv values that are problematic that will help, as the the animations I'll check them out tonight. That may give me hsv values as I debug the issue, but having specifics doesn't hurt.

**Comment by drashna** [comment]
That fixes both issues I saw, awesome!

**Comment by Wilba6582** [comment]
good stuff 👌

**Comment by XScorpion2** [comment]
my bad, deleted wrong branch, thank god for restore

**Pull request merged**
