### PR TITLE
Fix snailmap compilation error

### PR DESCRIPTION
**Pull request by jaygreco**
After #14024 was merged, my local NIBBLE builds started failing. 

```c
keyboards/nullbitsco/nibble/keymaps/snailmap/keymap.c: In function 'change_RGB':
keyboards/nullbitsco/nibble/keymaps/snailmap/keymap.c:485:34: error: implicit declaration of function 'oled_get_brightness' [-Werror=implicit-function-declaration]
             int new_brightness = oled_get_brightness() + 10;
                                  ^
keyboards/nullbitsco/nibble/keymaps/snailmap/keymap.c:487:17: error: implicit declaration of function 'oled_set_brightness' [-Werror=implicit-function-declaration]
                 oled_set_brightness(new_brightness);
                 ^
cc1: all warnings being treated as errors
```

The OLED driver is not being enabled properly. Updated `rules.mk` to fix it.

## Description
`OLED_DRIVER_ENABLE = yes` --> `OLED_ENABLE = yes`. Tested locally.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by zvecr** [comment]
cc @dogspace for signoff

**Comment by dogspace** [comment]
@jaygreco
The keymap will also need to be updated. Please replace `#ifdef OLED_DRIVER_ENABLE` on lines 62 and 467 with `#ifdef OLED_ENABLE`

**Comment by jaygreco** [comment]
@dogspace good catch! I'm making those changes and testing on my local nibble now.

**Comment by jaygreco** [comment]
Alright, updated and tested on my board! Everything looks good to me. This keymap is such a seriously such a treat 🙂

**Review by fauxpark — APPROVED** [review]

**Review by zvecr — APPROVED** [review]

**Pull request merged**
