### PR TITLE
Add Atreus50 keyboard

### PR DESCRIPTION
**Pull request by nooges**

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! Is this a PCB that's available anywhere?

**Comment by nooges** [comment]
@jackhumbert This was a handwire

**Comment by jackhumbert** [comment]
Nice - would you mind moving it to the handwired folder, and updating your readme then? Thanks! :)

**Comment by nooges** [comment]
Okay, updated the README and moved the folder under `handwired`

**Comment by jackhumbert** [comment]
Thanks!

**Pull request merged**
