### PR TITLE
Fix Indicator LED issues with md_rgb_matrix.c

### PR DESCRIPTION
**Pull request by 50an6xy06r6n**
## Description
The indicator LED code in `md_rgb_matrix.c` wasn't built to handle the iterative behavior associated with RGB_MATRIX_LED_PROCESS_LIMIT, causing indicator LED behavior to be buggy (scroll lock broken on Drop CTRL, for example). Modernized the code to use `rgb_matrix_indicators_advanced` instead.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Review by zvecr — CHANGES_REQUESTED** [review]
As user keymaps would need to be updated, this should really target develop in its current form.

**Comment by 50an6xy06r6n** [comment]
Why would user keymaps need to be updated?

**Comment by 50an6xy06r6n** [comment]
Changing to target develop, as advised.

**Review by drashna — APPROVED** [review]

**Comment by ewersp** [comment]
Curious, is the [video from this post](https://www.reddit.com/r/olkb/comments/eoez6b/weird_caps_lock_issue_on_drop_alt_anyone_know_how/) (eg with the flickering/stuck caps lock key) the buggy behavior you're seeing that this PR now fixes?

**Comment by 50an6xy06r6n** [comment]
@ewersp it might be related, but the issue I was trying to fix was the indicator not following pattern behavior properly. i.e. I had code that inverted the indicator color relative to the underlying pattern, but the inversion was happening multiple times per cycle, since RGB_MATRIX_LED_PROCESS_LIMIT causes the matrix code to operate on smaller blocks. On the CTRL there's 119 LEDs, processed 15 at a time. Scroll lock is in the first block, so it was getting inverted 8 times (i.e. no change), while caps lock is in the 4th block, so it was getting inverted 5 times (thus working as expected). I suppose this might fix flickering, depending on how your inversion code is configured. 

This is for a via-enabled keymap I made for the CTRL. Not sure how it would deal with the stock firmware, since I believe that's generated on a legacy branch of QMK

**Comment by ewersp** [comment]
Ah interesting, I may have noticed the behavior you're describing as well. After a little more digging, I believe the specific issue I was seeing has since been fixed in this PR https://github.com/qmk/qmk_firmware/pull/10818

**Review by drashna — APPROVED** [review]

**Comment by 50an6xy06r6n** [comment]
@drashna is there any action needed on my part here?

**Comment by drashna** [comment]
@zvecr look good?

**Review by tzarc — APPROVED** [review]

**Pull request merged**
