### PR TITLE
Fix OSMs getting stuck

### PR DESCRIPTION
**Pull request by kasimir-k**
## Description

This PR fixes OSMs getting stuck with double tapping or holding another mod. The bug was caused by `oneshot_mods` being converted to regular mods with `registed_mods` and thus loosing possibility to unregister those mods, and also not clearing the mods.

The commits of this PR are: 

1. Remove handling of multiple taps: other than `ONESHOT_TAP_TOGGLE` functionality, single tap and double tap (or n-tap) should be treated equally
2. Leave OSMs intact on press-and-hold: holding an OSM should behave exactly like a regular mod, and should have no effect on OSMs
3. Remove redundant outer conditional block: this is mainly to improve readability and also to make it clearer that key-up of a tap has only effect with `ONESHOT_TAP_TOGGLE`
4. Add function `del_oneshot_locked_mods()`: improves readability over `set_oneshot_locked_mods(~mods & get_oneshot_locked_mods());` and also makes it clearer that releasing a held mod unlocks it, if it was locked
5. Fix clearing OSMs: locking a mod with toggle should not clear all OSMs, only the toggled OSM 
6. Improve readability: add comments and change setting OSMs to explicit adding of one mod
7. Add `add_oneshot_locked_mods()`: align utils for locked mods with other mods utils 

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #3963 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Could you add tests to verify that this behavior is being processed correctly? 

(you can see some tests in `tests/basic/test_one_shot_keys.cpp`)

**Comment by kasimir-k** [comment]
Before writing new tests I wanted to see what the existing tests say, but they said no. 

Any pointers how to get them running on a M1 Mac? 

```
❯ make test:basic
QMK Firmware 0.19.9
Making test basic

Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Compiling: tests/test_common/test_driver.cpp                                                       In file included from tests/test_common/test_driver.cpp:17:
In file included from tests/test_common/test_driver.hpp:22:
tests/test_common/keyboard_report_util.hpp:38:81: error: non-constant-expression cannot be narrowed from type 'qk_keycode_defines' to 'unsigned char' in initializer list [-Wc++11-narrowing]
    return testing::MakeMatcher(new KeyboardReportMatcher(std::vector<uint8_t>({keys...})));
                                                                                ^~~~
tests/test_common/test_driver.cpp:63:5: note: in instantiation of function template specialization 'KeyboardReport<qk_keycode_defines, qk_keycode_defines, qk_keycode_defines>' requested here
    EXPECT_REPORT(driver, (KC_LCTL, KC_LSFT, KC_U));
    ^
tests/test_common/test_driver.hpp:64:80: note: expanded from macro 'EXPECT_REPORT'
#define EXPECT_REPORT(driver, report) EXPECT_CALL((driver), send_keyboard_mock(KeyboardReport report))
                                                                               ^
tests/test_common/keyboard_report_util.hpp:38:81: note: insert an explicit cast to silence this issue
    return testing::MakeMatcher(new KeyboardReportMatcher(std::vector<uint8_t>({keys...})));
                                                                                ^~~~
                                                                                static_cast<unsigned char>( )
tests/test_common/keyboard_report_util.hpp:38:81: error: non-constant-expression cannot be narrowed from type 'qk_keycode_defines' to 'unsigned char' in initializer list [-Wc++11-narrowing]
    return testing::MakeMatcher(new KeyboardReportMatcher(std::vector<uint8_t>({keys...})));
                                                                                ^~~~
tests/test_common/keyboard_report_util.hpp:38:81: note: insert an explicit cast to silence this issue
    return testing::MakeMatcher(new KeyboardReportMatcher(std::vector<uint8_t>({keys...})));
                                                                                ^~~~
                                                                                static_cast<unsigned char>( )
tests/test_common/keyboard_report_util.hpp:38:81: error: non-constant-expression cannot be narrowed from type 'qk_keycode_defines' to 'unsigned char' in initializer list [-Wc++11-narrowing]
    return testing::MakeMatcher(new KeyboardReportMatcher(std::vector<uint8_t>({keys...})));
                                                                                ^~~~
tests/test_common/keyboard_report_util.hpp:38:81: note: insert an explicit cast to silence this issue
    return testing::MakeMatcher(new KeyboardReportMatcher(std::vector<uint8_t>({keys...})));
                                                                                ^~~~
                                                                                static_cast<unsigned char>( )
tests/test_common/keyboard_report_util.hpp:38:81: error: non-constant-expression cannot be narrowed from type 'qk_keycode_defines' to 'unsigned char' in initializer list [-Wc++11-narrowing]
    return testing::MakeMatcher(new KeyboardReportMatcher(std::vector<uint8_t>({keys...})));
                                                                                ^~~~
tests/test_common/test_driver.cpp:78:5: note: in instantiation of function template specialization 'KeyboardReport<qk_keycode_defines>' requested here
    EXPECT_REPORT(driver, (KC_SPC));
    ^
tests/test_common/test_driver.hpp:64:80: note: expanded from macro 'EXPECT_REPORT'
#define EXPECT_REPORT(driver, report) EXPECT_CALL((driver), send_keyboard_mock(KeyboardReport report))
                                                                               ^
tests/test_common/keyboard_report_util.hpp:38:81: note: insert an explicit cast to silence this issue
    return testing::MakeMatcher(new KeyboardReportMatcher(std::vector<uint8_t>({keys...})));
                                                                                ^~~~
                                                                                static_cast<unsigned char>( )
4 errors generated.
 [ERRORS]
 |
 |
 |
make[1]: *** [.build/test_obj/basic/tests/test_common/test_driver.o] Error 1
Make finished with errors
make: *** [test:basic] Error 1
```

**Comment by fauxpark** [comment]
Nope, clang doesn't like the tests.

**Comment by kasimir-k** [comment]
Added three tests for:
- chaining OSMs (not part or my changes, but it was missing and related)
- OSM double tap not locking previous OSMs
- OSM holding not locking previous OSMs

Also verified that the two latter tests failed on the master branch as they should.

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Comment by mcp292** [comment]
@kasimir-k Thank you for your hard, clean work on this! I really appreciate it. Very nice!

**Pull request merged**
