### PR TITLE
Expose rgb_matrix_update_pwm_buffers to be available in keymaps

### LINKED ISSUE #24572: [Bug] rgb_matrix_update_pwm_buffers() is not explicitly declared
### Describe the Bug

When implementing the following example documented in https://docs.qmk.fm/custom_quantum_functions#example-shutdown-user-implementation:

```c
bool shutdown_user(bool jump_to_bootloader) {
    if (jump_to_bootloader) {
        // red for bootloader
        rgb_matrix_set_color_all(RGB_RED);
    } else {
        // off for soft reset
        rgb_matrix_set_color_all(RGB_OFF);
    }
    // force flushing -- otherwise will never happen
    rgb_matrix_update_pwm_buffers();
    // false to not process kb level
    return false;
}
```

Compiling a keymap with this code runs into:

```
./keyboards/massdrop/alt/keymaps/ericvw/keymap.c: In function 'shutdown_user':
./keyboards/massdrop/alt/keymaps/ericvw/keymap.c:73:5: error: implicit declaration of function 'rgb_matrix_update_pwm_buffers'; did you mean 'rgb_matrix_step_reverse'? [-Werror=implicit-function-declaration]
     rgb_matrix_update_pwm_buffers();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     rgb_matrix_step_reverse
cc1: all warnings being treated as errors
```

### Keyboard Used

massdrop/alt

### Operating System

macOS and Windows

### qmk doctor Output

```text
> qmk doctor
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.6
Ψ QMK home: /Users/eric/projects/qmk_firmware.git
Ψ Detected macOS 15.0 (Apple Silicon).
Ψ Userspace enabled: False
Ψ Git branch: massdrop/alt/ericvw
Ψ Repo version: 0.26.9
⚠ The official repository does not seem to be configured as git remote "upstream".
Ψ CLI installed in virtualenv.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 8.5.0
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 8.0
Ψ Found dfu-programmer version 1.1.0
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2024-02-17 19:20:06 +0000 --  (be44b3305)
Ψ - lib/chibios-contrib: 2024-04-03 20:39:24 +0800 --  (77cb0a4f)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go, but minor problems were found
```

### Additional Context

I have a commit that changes `quantum/rgb_matrix.h` to declare `rgb_matrix_update_pwm_buffers` for a pull request if this is the desired change to address.

Alternatively, I am calling `rgb_matrix_driver.flush()`, which I'm not sure is desired to be called directly in keymaps.

### PR DESCRIPTION
**Pull request by ericvw**
Exposing this API enables the examples in the keyboard shutdown/reboot documentation to compile instead of calling `rgb_matrix_driver.flush` directly.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #24572

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by waffle87 — APPROVED** [review]
You're also welcome to remove the existing prototypes that keyboards using this function have:
[`keyboards/bastardkb/dilemma/dilemma.c`](https://github.com/qmk/qmk_firmware/blob/develop/keyboards/bastardkb/dilemma/dilemma.c#L357)
[`keyboards/bastardkb/charybdis/charybdis.c`](https://github.com/qmk/qmk_firmware/blob/develop/keyboards/bastardkb/charybdis/charybdis.c#L396)
[`keyboards/miiiw/blackio83/rev_0100/rev_0100.c`](https://github.com/qmk/qmk_firmware/blob/develop/keyboards/miiiw/blackio83/rev_0100/rev_0100.c#L168)

**Comment by ericvw** [comment]
Great suggestion. I'll be able to update the PR this weekend and will remove the extraneous prototypes.

**Comment by ericvw** [comment]
> Great suggestion. I'll be able to update the PR this weekend and will remove the extraneous prototypes.

@waffle87, I got around to removing the extraneous local prototype declarations. The PR has been updated.

**Comment by waffle87** [comment]
LGTM.

**Review by drashna — APPROVED** [review]

**Pull request merged**
