### PR TITLE
Youtube Checker request

### PR DESCRIPTION
**Pull request by LetsPlayNintendoITA**
Sorry but I can't find any other way to contact you or write a request there.
It seems youtube has changed the api key and now your great extension died :(
I attached the log
[EJJkxzKf.txt](https://github.com/qmk/qmk_firmware/files/8275892/EJJkxzKf.txt)
.

### CODE REVIEW

**Comment by LetsPlayNintendoITA** [comment]
it's not random. wtf?
it's the log from their extension...
it says in the extension to send the log to the creator...

**Comment by tzarc** [comment]
This is not a browser extension repository. You're in the wrong place.

**Comment by tzarc** [comment]
I have no idea what browser extension you're referring to.

**Comment by LetsPlayNintendoITA** [comment]
too bad that the repository for it is closed so i can't post there

**Comment by LetsPlayNintendoITA** [comment]
> I have no idea what browser extension you're referring to.

Youtube Checker, their extension:  https://github.com/XrXr/YoutubeSubscriptionChecker

**Comment by tzarc** [comment]
This discussion has run its course -- that repository is where you need to be posting.

**Pull request closed without merging**
