### PR TITLE
Organized versions of mikeneko65

### PR DESCRIPTION
**Pull request by takishim**
## Description
Organized versions of mikeneko65.
- change v4 version to v1 version
- delete v3 version

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Comment by fauxpark** [comment]
Merge conflicts need resolving.

**Comment by takishim** [comment]
I don't know why there are conflicts.

**Comment by takishim** [comment]
The following files were simply deleted.
- keyboards/mikeneko65/rev3/keymaps/default/keymap.c
- keyboards/mikeneko65/rev3/keymaps/via/keymap.c

**Comment by takishim** [comment]
I merged with master branch and resolved conflicts.
Please review again.

**Pull request merged**
