### PR TITLE
Remove/migrate action_get_macro()s from default keymaps

### PR DESCRIPTION
**Pull request by fauxpark**
## Description
Getting rid of the old macro code, once again only touching default and default-looking keymaps. The pointless/unused ones were removed and the active ones turned into `process_record_user()`s.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
@noroadsleft yeah IIRC there are some pre-existing issues with the Hadron firmware so I don't think it's particularly related.

**Comment by noroadsleft** [comment]
@fauxpark There I go not being clear again; that was exactly my point.

**Comment by fauxpark** [comment]
I was agreeing ;)

**Comment by noroadsleft** [comment]
*pokes @drashna*

**Pull request merged**
