### PR TITLE
Allow overlapping combos

### LINKED ISSUE #4302: Overlapping Combos
QMK does not currently support combos that share a common key. A reimplementation of Combo that supports all possible combinations of keys would need to be robust enough to support a large number of possibilities without overlaps causing any detriment to performance. This can most likely be done by calculating the 'value' of the matrix and indexing an array/calling a function based off that value, whether keys are shared or not shouldn't matter. 

Example: Using a 2x3 set of keys to type all 26 letters of the alphabet. 

2x3

This is how I would think to implement combinations on a small scale. A larger grid would have numbers too big for a 16 bit or 32 bit integer to hold but all that matters is that each combo is uniquely identifiable just based off the state of the matrix. I don't know too much about the specifics of Combos' current implementation or if doing it this way would run into difficulties.

I just want to be able to use combinations like in the example. How it's eventually done doesn't matter if it works well. The actual usage of Combo should look the same, since this calculation and the indexing should just be internal. 

Getting this working is a priority of mine so any help/advice is greatly appreciated. I'll be trying to get it working locally on my planck/rev6.

### PR DESCRIPTION
**Pull request by alexspeller**
## Description

Add option to only send the longest combo when multiple combos are held down

I wanted to have multiple combos on the home row, that overlapped - e.g. `SDF` for shift and `DF` to change layers. However the combos were sent immediately as they were pressed, so I would change layers when I really wanted to shift.

I've added a `COMBO_ONLY_SEND_LONGEST_COMBO` flag that will debounce the combos and only send the longest one, allowing overlapping independent combos like this.

This still allows combos to be used as modifier keys - it only delays sending the combo by `COMBO_TERM`.

I am far from a competent C programmer so I might be doing stupid stuff here.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* fixes #4302 

## Checklist

- [ ] My code follows the code style of this project. **it follows the code style of the file it's in, which seems not quite to follow the documented project style in terms of indentation**
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes. **I can't find tests for combos at all - am I missing them?**
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Well, you can run `git revert 24d0e1ae058d7d89adce6be65917cb40c740ccbf` 

Or you ran run `git rebase HEAD~2 -i` and "drop" the first commit.  


Also, if you did this locally, you probably ran `git checkout -B branch_name`, when you should have run `git checkout -B branch_name master` (this creates a new branch based on master, rather than the current working branch).

**Comment by alexspeller** [comment]
I cleaned this up a little moving to a function and fixed it so the combo works instantly if a non-combo key is pressed.

R.e. the git comments, what I mean is that git is actually completely broken for me without including that commit, which I did intentionally. e.g. `git rebase` doesn't let you rebase because it thinks you have local modifications. Event `git checkout master` doesn't work with a clean repo:

```
➤  git status                                                                                                                                                                                      
On branch allow-overlapping-combos
nothing to commit, working tree clean
➤  git checkout master
error: The following untracked working tree files would be overwritten by checkout:
	keyboards/tada68/keymaps/hhkb68/README.md
Please move or remove them before you switch branches.
Aborting
```

If that PR is merged soon, then this will be moot, but if it doesn't get merged soon I can figure out how to rebase this. Likely by doing it in a docker image or something. And then curse OSX for being case insensitive by default :)

**Comment by alexspeller** [comment]
Oh it did just get merged - I rebased fine now, thanks!

**Comment by noroadsleft** [comment]
This is potentially a duplicate of #5527.

**Comment by noahfrederick** [comment]
> I've added a `COMBO_ONLY_SEND_LONGEST_COMBO` flag

I don't think this should be behind a flag—it should just be how the Combo feature works. The previous behavior of triggering all sub-combos is unintuitive.

If there is some use case for the old behavior, then maybe introduce a flag with the opposite meaning.

**Comment by drashna** [comment]
I agree with @noahfrederick actually.

**Comment by alexspeller** [comment]
So, thinking about this, I think it might be best to have both.

I.e., update `process_combo_event` to have the new behaviour, but make a new callback `process_combo_event_immediate` that calls immediately so that users can react at both points.

Whilst it's hard for me to articulate a concrete use case for `process_combo_event_immediate` right now, there are definitely things that you might want to be able to do there that you just can't do if the combo is debounced. I can imagine tapping combos, for example, would suffer if you only got the combo press after a `COMBO_TERM` debounce.

I guess it just feels right, because you can implement the debounced behaviour in userspace if you only have the immediate behaviour in core, but not the other way round.

Either way, I'm going to do some refactoring here and see if I can hash that implementation out a little better. I've also found a little bug in my implementation: although the presses are debounced, the release of the combos still send releases for each combo. This probably isn't an issue most of the time if you're just doing `layer_off` on release, but it's a bit ugly to get `COMBO ASD pressed` and then `COMBO AS released, COMBO ASD released`.

Would you prefer I close this PR and come back with a new one later, or leave it open until I do the refactoring?

**Comment by drashna** [comment]
Both may be best, but I still think that the "send longest" should be the default behavior.  We can hide the older method behind preprocessor lines.

**Comment by drashna** [comment]
There is a merge conflict here. Could you rebase and fix this?

**Comment by drashna** [comment]
Any update on this?

**Comment by alexspeller** [comment]
Hi, I used this a little on my own board and I found that it's a bit unreliable - I've been meaning to come around and figure out why and get it more reliable. I was trying to figure out if I could write some tests that would help me try out all the cases however I didn't find a way to do that kind of testing, and that's about as far down the rabbit hole as I got :(

**Comment by germ** [comment]
@alexspeller Did you manage to figure out where the unreliability came from or do any further work? Asking before I take a stab at this. Would like to get this merged into core as a few of my boards a 100+ combos on them :P

**Comment by alexspeller** [comment]
@germ unfortunately not, I took a different approach to my keymap in the end without any overlapping combos

**Comment by germ** [comment]
Damn. You mind if I use this PR as a starting point for my own work @alexspeller ?

**Comment by alexspeller** [comment]
@germ please feel free, if you get it working I'd love to try it out again myself!

**Pull request closed without merging**
