### PR TITLE
Add movement hook to ps2_mouse

### PR DESCRIPTION
**Pull request by manna-harbour**
## Description

Process mouse movement in the keymap before it is sent to the host.  Example uses include filtering noise, adding acceleration, and automatically activating a layer.  To use, define the following function in your keymap: 

void ps2_mouse_moved_user(report_mouse_t *mouse_report);

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by manna-harbour** [comment]
Ready for review, thanks!

**Comment by manna-harbour** [comment]
Thanks drashna!  Is these anything I should add to make this easier for others to review?

**Comment by drashna** [comment]
Nope, just needs more eyes on it.

**Comment by manna-harbour** [comment]
Is there anyone in particular who looks after ps2_mouse?

**Comment by manna-harbour** [comment]
Thanks everyone!

**Comment by manna-harbour** [comment]
Thanks everyone!

Could someone please update the labels on #9461, which had this PR as a prerequisite?  Thanks!

**Pull request merged**
