### PR TITLE
Enable visualizer support for ergodox infinity

### PR DESCRIPTION
**Pull request by kesslern**
A few people have requested this, and it certainly works well enough.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool - @fredizzimo, what are you thoughts on this?

**Comment by kesslern** [comment]
I've been using this as my daily driver for a few days without any real issues. The only problem I've ran into is the state syncing across halves can be slow and inconsistent. On my device, I disabled sharing the state, so only the master half's visualizer updates. The slave stays on the last keyframe of the initialization animation.

I'd be happy to make a flag to toggle state sharing across halves and add it to this pull request.

**Comment by fredizzimo** [comment]
I will check this out, and make sure everything works as it should. I think at least #1122 should be fixed first. There should also be at least some default visualizer example and documentation. 

I'll make this a priority over my other work with the effect system. Better get this working first, as it probably still will take some while until the effect system is ready.

**Comment by jackhumbert** [comment]
I think this can be closed now, right @fredizzimo?

**Comment by fredizzimo** [comment]
Yes. My pull request does all this (well actually fixes the oneshot timeout bug instead of working around it) and more.

**Comment by jackhumbert** [comment]
Perfect - thanks guys :)

**Pull request closed without merging**
