### PR TITLE
KBDFans KBD67 Support

### PR DESCRIPTION
**Pull request by mechmerlin**
KBDFans is killing it! New 65% board is out!

### CODE REVIEW

**Comment by drashna** [comment]
Nice!

**Comment by Durkslol** [comment]
Hey @mechmerlin , thanks for adding this 😄 

I'm new to QMK, is it possible to use `layout_all` to achieve a ISO layout?

**Comment by drashna** [comment]
Yup.

`LAYOUT_all` typically includes every matrix position, even ones that you can't use.   So you could absolutely achieve that, if the board physically supports it.

**Comment by Durkslol** [comment]
awesome thanks :)

**Pull request merged**
