### PR TITLE
 Updated ACR60, Mechmini, ALU84 readme information and config.h descriptors

### PR DESCRIPTION
**Pull request by TurboMech**
Update MECHKEYS keyboards to be uniform in readmes and config.h's PID, MANUFACTORER, and DESCRIPTIONS.   This allows the keyboards to be more uniform amongst the different types produced by MECHKEYS.

### CODE REVIEW

**Comment by TurboMech** [comment]
Whoops, should have made a separate branch or cherry-picked in order to not have 3 commits when I was only attempting to PR d236cab.  @jackhumbert let me know if this causes issues, I'll close and reopen if need be in a one commit to reduce clutter.

**Comment by TurboMech** [comment]
Yeah @jackhumbert gonna go ahead and close this and open up a new one that doesn't fail.  Sorry about that.

**Comment by jackhumbert** [comment]
That's no problem - we can squash the commits! But the failure looks like it may be coming from your titlecase keymap folder name - generally we encourage keymaps to be all lowercase, because some OSes are case-sensitive (like our build system), and others aren't. If you wanna change your keymap to lowercase and reopen this PR, that'd be great!

**Comment by TurboMech** [comment]
I don't know why the titlecase changed.  No big deal, I'm creating a new pull request

**Comment by jackhumbert** [comment]
Please reopen when you can (via force pushing to your branch) - we get a lot of duplicate PRs that inflate our PR count.

Not all keymaps are tested when system-wide changes are made, since [Travis runs through everything to just test the default keymaps](https://travis-ci.org/qmk/qmk_firmware/builds/323681710?utm_source=github_status&utm_medium=notification), but the TurboMech keymap would have failed if tested here - it might not fail locally because Windows is case-insensitive.

**Pull request closed without merging**
