### PR TITLE
Add keymaps to momokai keyboards that switches debounce to asym_eager_defer_pk

### PR DESCRIPTION
**Pull request by peepeetee**
## Description

This here pull request adds a keymap to each momokai keyboards that switches debounce to asym_eager_defer_pk
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by waffle87** [comment]
Keyboard updates must target develop.

**Comment by peepeetee** [comment]
> Keyboard updates must target develop.

oh wow it's just changing the base branch I thought I would have to rebase it

**Comment by peepeetee** [comment]
> Keyboard updates must target develop.

I have decided to make this change with a new keymap instead, and the pull request should reflect that now. from what I recall this should be able to target master now? so I changed base branch back to master for now

**Review by drashna — APPROVED** [review]

**Comment by peepeetee** [comment]
unstale agin

**Pull request closed without merging**
