### PR TITLE
Remove redundant eeconfig inits

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Dependent on #8532

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
This seems to bork my splits. Not exactly sure why.

**Comment by tzarc** [comment]
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

**Comment by zvecr** [comment]
> This seems to bork my splits. Not exactly sure why.

works on my lets_splits so i assume its down to one of the enabled features. However more testing will happen in due course.

**Comment by drashna** [comment]
For testing, been running this for a while, and doesn't seem to cause any issues.

**Comment by zvecr** [comment]
Closing as the required change will be staged separately.

**Pull request closed without merging**
