### PR TITLE
Configurator fixes for handwired/concertina/64key

### PR DESCRIPTION
**Pull request by veikman**
## Description

Fixes and enhancements for the use of QMK Configurator specifically with the Concertina, following a tip by @noroadsleft.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by noroadsleft — COMMENTED** [review]
Does this look correct? (Disregarding that I have QWERTY assignments here instead of Colemak)

image

**Comment by veikman** [comment]
Yes, that’s correct as far as Configurator is able to render what’s really going on under Colemak. The biggest invisible customization is this snippet from `keyboards/handwired/concertina/64key/keymaps/default/config.h`:

```C
#define LCPO_KEYS KC_LCTL, KC_TRNS, KC_LBRACKET
#define RCPC_KEYS KC_RCTL, KC_TRNS, KC_RBRACKET
#define LAPO_KEYS KC_LALT, KC_LSFT, KC_LBRACKET
#define RAPC_KEYS KC_RALT, KC_RSFT, KC_RBRACKET
```

Those custom space-cadet-style modifier-and-tap combinations all render as `/(` and `/)`, but are really brackets and braces. I know of no better (i.e. renderable) way to implement the functionality.

**Comment by noroadsleft** [comment]
Ah, Configurator's API doesn't have any support for being able to change the default Space Cadet keys, which are:

```
#define LCPO_KEYS KC_LCTL, KC_LSFT, KC_9
#define RCPC_KEYS KC_RCTL, KC_RSFT, KC_0
#define LAPO_KEYS KC_LALT, KC_LSFT, KC_9
#define RAPC_KEYS KC_RALT, KC_RSFT, KC_0
```

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
