### PR TITLE
Move transport.c to QUANTUM_LIB_SRC

### PR DESCRIPTION
**Pull request by drashna**
## Description

LTO can cause issues for the transport, and cause sync issues, especially if there is a lot of data.  

## Types of Changes

- [x] Core
- [x] Bugfix

## Issues Fixed or Closed by This PR

* Issues with LTO being enabled and sync issues on split.

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Also, wondering if it's worth adding `__attribute__((packed))` to the data structures, as well.

**Comment by tzarc** [comment]
> 
> 
> Also, wondering if it's worth adding `__attribute__((packed))` to the data structures, as well.

In theory, yes. In practice, we're going to get a lot of "why doesn't split work after flashing?!?!?!". I guess we're not going to get anything drastically different compared to now, though.

**Review by tzarc — APPROVED** [review]

**Comment by drashna** [comment]
> In theory, yes. In practice, we're going to get a lot of "why doesn't split work after flashing?!?!?!". I guess we're not going to get anything drastically different compared to now, though.

Point. Should be fine without

**Review by mtei — APPROVED** [review]
weak approve.

**Pull request merged**
