### PR TITLE
Fixed: inconsistent MATRIX_COLS and MATRIX_COL_PINS in facew.

### PR DESCRIPTION
**Pull request by elfmimi**
## Description

The fix compiles OK. But I don't have the corresponding hardware so I cannot actually test it.
TBH, I have a feeling that this code has no user at all.

I need consistency of MATRIX_ROWS and MATRIX_COLS against MATRIX_ROW_PINS and MATRIX_COL_PINS respectively for all keyboards to shape my next PR complete.

Could you help? @mechmerlin

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/qmk/qmk_firmware/issues/8106

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mechmerlin** [comment]
Hey thanks for the submission, however I do have some issues with this

1. Typically its not a good idea to change pins on firmware when you don't have hardware to actually test this on. I no longer have the board, but with the current firmware, it was my work board for a good 2 years. Unfortunately I cannot test your change either. 

2. All but 1 bootmapperclient type boards, use A0, B0 as the reset switch. This is typically programmed in QMK as the Row 0 and Col 0, so that `K00` is the location of the reset switch. This disrupts it. 

3. One reason why winkeyless.kr closed, is people just rampantly copied their boards without permission. FaceW is a copy of the b.face with a few things different. Both boards have since been copied many times over. I have encountered boards that are named facew, but when flashed with this firmware they fail. My FaceW is direct from Sprit himself.

**Comment by elfmimi** [comment]
Thank you for reviewing! I very much appreciate those information you provided.

I was hoping that you have this keyboard in possession and you could test it.
And the situation was more complicated than I thought.
While the code for this keyboard appears as a simplest of kind, that BootMapperClient thing adds complexity which we don't want to handle now.

I'll rethink about what to do.

**Comment by elfmimi** [comment]
I did survey and I couldn't find out any proof that the binary of qmk-firmware built from this code is meant to be used in conjunction with Bootmapper Client.

I'm guessing this only serves as a placeholder before it gets overwritten with the binary equipped with Bootmapper Client.

**Comment by elfmimi** [comment]
_Minimum change for minimum impact._
Please merge this.

If there is a real need for removing vacant columns in the matrix, facew is not the only one that should get treated. So it should be handled in a separate issue/pull-request.
One example is bfake keyboard. https://github.com/qmk/qmk_firmware/blob/master/keyboards/bfake/bfake.h

**Comment by elfmimi** [comment]
... closing and reopening was unintentional.

It's been stale, so I'd like to state again that current code is apparently wrong and it's not functioning and it's inconsistency is blocking another PR of mine. I need this merged.

**Comment by elfmimi** [comment]
branch re-synchronized to the new master.

**Comment by tzarc** [comment]
Ultimately, something needs to be fixed, as we have `#define MATRIX_COLS 11` but `MATRIX_COL_PINS` only has 10 entries on `master`. Can we find someone who _does_ have this board?

**Comment by giammin** [comment]
I have this board! facew sprit edition ps2avru v1.0

**Comment by elfmimi** [comment]
@giammin Thank you for making contact with us. Are you using QMK as a firmware for your facew?

**Comment by giammin** [comment]
not yet, I was looking to see if I could use qmk instead of bootmapper client

if I don't risk to fry my board  I can do some tests

**Comment by giammin** [comment]
@elfmimi i had some time to test it: i tried flashing the default layout and it does not work 

if you tell me what to change i can test if you are right about the columns count

**Comment by elfmimi** [comment]
@giammin Thank you for so much kindness helping us out. If it does not work I believe unmodified build should also be not working. If that is the case we need to find out why.
This is the point where this keyboard last got major change. https://github.com/qmk/qmk_firmware/issues/8106#issuecomment-582964450
1) It could have already been broken at this point.
2) Something must have broke it since then to date.

**Comment by giammin** [comment]
i found this PR https://github.com/qmk/qmk_firmware/pull/2493

**Comment by giammin** [comment]
@elfmimi good news! As expected with [this modify ](https://github.com/giammin/qmk_firmware/commit/259266fd3fc6df47d1d31712742318a4ed91c106#diff-3693efb5a03a46fd3d14cccd4b47f0ffd0ec2251155f4a55f34227a8d42c962a)it works

**Comment by elfmimi** [comment]
@giammin Fantastic. Ok then let us reorganize information.
You said it didn't work when you tried for the first time. That one was the unmodified one. is this correct?
Next. The modification you tried and successfully worked is identical to that of this pull-request's latest commit. Please confirm this.

**Comment by giammin** [comment]
> You said it didn't work when you tried for the first time. That one was the unmodified one. is this correct?
yes

> The modification you tried and successfully worked is identical to that of this pull-request's latest commit. Please confirm this.

yes! just added C5 on the pin list:

#define MATRIX_COL_PINS { A0, A1, A2, A3, A4, A5, A6, A7, C7, C6 **, C5** }

**Comment by elfmimi** [comment]
Let's merge this. @ **drashna** **fauxpark** **zvecr** **tzarc**

**Review by tzarc — APPROVED** [review]

**Pull request merged**
