### PR TITLE
New RGB Matrix effect: Single color reactive

### PR DESCRIPTION
**Pull request by MatthewRobo**
## Description

This adds a new effect to RGB_Matrix.
The new effect is a single-colored reactive flash, set to the color in the EEPROM that is adjustable via keycodes like `RGB_HUI`, `RGB_VAI`, and `RGB_SAI`.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by MatthewRobo** [comment]
@yanfali Unfortunately not, but as far as I can tell, the RGB Matrix doc does not even describe what any of the effects do.

**Comment by mechmerlin** [comment]
> @yanfali Unfortunately not, but as far as I can tell, the RGB Matrix doc does not even describe what any of the effects do.

I think it would be a good idea to document this so people know what it does and can use it properly.

**Comment by XScorpion2** [comment]
Will pull this down this weekend and review with https://github.com/qmk/qmk_firmware/pull/5372

**Comment by drashna** [comment]
This ready to go?

**Comment by XScorpion2** [comment]
Documentation is something I plan on writing soon'ish as it was a massive learning experience from fixing all the animations.

**Pull request merged**
