### PR TITLE
Add ARM Teensy flashing support

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Teensy 3.x and LC both use teensy_loader_cli for flashing and expect a `.hex` file.

The change has been stolen from avr.mk, im not sure if there is a more centralised location to avoid duplication? (MCU logic will need to be slightly different between ARM and AVR due to ARM teensy requiring `MCU  = cortex-m0plus` and that not being what `-mmcu` expects).

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Nope, that's fine.   And actually, I think that's the correct way, since of the difference (and what I did for my draft wally PR)

However, is `MCU_LDSCRIPT` correct for the boards that would use the teensy_loader_cli?

**Comment by zvecr** [comment]
`MCU_LDSCRIPT` is currently set to the correct values for teensy boards, however with the old chibios fork i don't know if this will change. I can add an additional `rules.mk` flag to pass down if it helps clarify or contain the issue ( i was just being lazy and reusing an existing one).

**Comment by drashna** [comment]
If it does change, we'll have to deal with that, then. 

The worst case, is that for now, we could add a new variable: `TEENSY_MCU_ARG`, and set it to `MCU_LDSCRIPT` if it's not set

**Comment by zvecr** [comment]
Happy to go whatever direction on the flags, dealers choice.

**Comment by drashna** [comment]
I think for now, this should be fine.

**Pull request merged**
