### PR TITLE
Added support for audio using pins C4, C5, B6, B7

### PR DESCRIPTION
**Pull request by walkerstop**
This is helpful for Clueboard 2x1800 which has the speaker pads connected to C4 and B7

### CODE REVIEW

**Comment by walkerstop** [comment]
@skullydazed @jackhumbert could you please take a look at this?  Thanks!

**Comment by walkerstop** [comment]
Thanks for your help @Wilba6582

**Comment by walkerstop** [comment]
@mechmerlin

**Comment by drashna** [comment]
You should update the docs too, so it lists all of the possible pins that can be used.

https://github.com/qmk/qmk_firmware/blob/master/docs/feature_audio.md

**Comment by walkerstop** [comment]
Ok

**Comment by walkerstop** [comment]
I updated the documentation
Mike

**Comment by drashna** [comment]
Well, I for one am excited about this.  It means that I may be able to finally add audio to my ergodox. :)

**Comment by jackhumbert** [comment]
This is awesome - thanks!

**Comment by walkerstop** [comment]
Please do try it if you have a chance, I will try to test more tonight but
I'm mostly just using c4 and b7, I haven't tested c5 or b6 yet

**Pull request merged**
