### PR TITLE
Eager pk/pr optimization

### LINKED ISSUE #5620: Eager PR issue
## Describe the Bug

Eager Per Row debouncing causes system to immediately wake up from sleep.

This only happens with Eager Per Row debouncing, and ONLY on the Ergodox EZ, from what I can tell.

Tested with Sym_G and Eager_PK, and no issue with sleep. Tried Eager_PR on the Iris, no issue. 
Reverted #5498 also fixes the issue.  So there is something here that is causing the Ergodox EZ to stay awake. 

@alex-ong 

## System Information

 - Keyboard:  Ergodox EZ
 - Operating system: Windows 10 x64
 - AVR GCC version: 8.3.0
 - QMK Firmware version: 0.6.334
 - Any keyboard related software installed?  No

### PR DESCRIPTION
**Pull request by alex-ong**
Eager pk/pr will now have effectively 0 runtime when no debouncing is required

## Description
A boolean stores whether we are currently debouncing anything.
We can skip scanning the matrix if we are are not debouncing.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Closes #5620 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

Haven't gotten around to testing the changes due to no qmk keyboard easily available.
May alleviate #5620, though i see no reason why it would.

### CODE REVIEW

**Comment by drashna** [comment]
Tested.  And this appears to fix #5621

**Comment by alex-ong** [comment]
> Tested. And this appears to fix #5621

Works... but i don't know why...
image

**Comment by noroadsleft** [comment]
> Tested. And this appears to fix #5621

#5620*

**Comment by XScorpion2** [comment]
So an interesting possible future extention using a dirty boolean: if scanning a large matrix takes too much time, you could switch that boolean to a dirty mask that can identify smaller portions of the matrix that need to be scanned for debounce. I do that in the oled driver pr #5288 as an example.

**Pull request merged**
