### PR TITLE
[Driver] Support IS31FL3741 and IS31FL3741A.

### PR DESCRIPTION
**Pull request by melgeek001365**
## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by melgeek001365** [comment]
Support IS31FL3741

**Comment by fauxpark** [comment]
You do not need to keep opening new PRs. Please just push to the same branch if you need to make changes. You can force push if you need to.

**Comment by melgeek001365** [comment]
> You do not need to keep opening new PRs. Please just push to the same branch if you need to make changes. You can force push if you need to.

sorry. I'm not familiar with github.

**Comment by melgeek001365** [comment]
> > You do not need to keep opening new PRs. Please just push to the same branch if you need to make changes. You can force push if you need to.
> 
> sorry. I'm not familiar with github. Could you mind tell me how to handle it?



> You do not need to keep opening new PRs. Please just push to the same branch if you need to make changes. You can force push if you need to.

I will give it a try now.

**Pull request closed without merging**
