### PR TITLE
Added basic support for JJ50 (preonic-like based on atmega32A)

### PR DESCRIPTION
**Pull request by WarmCatUK**
Added support for JJ50 from KPRepublic, no rgb or backlight control yet. Added as a layout of ymd96 at the moment (same microprocessor). Basic keymap with three layers to get started.

### CODE REVIEW

**Comment by jackhumbert** [comment]
That actually looks like it'd be enough to start a separate `jj50` folder - would you be ok with setting that up?

**Comment by WarmCatUK** [comment]
I can give it a go, is there somewhere/file which lists the keyboards? Also, any strict naming etc I should be aware of?

**Comment by WarmCatUK** [comment]
There we go, I've created a separate jj50 folder and updated documentation etc.
You can dismiss the first commit (a2c92db).

**Comment by jackhumbert** [comment]
Perfect :) thanks!

**Pull request merged**
