### PR TITLE
update ishtobs hadron keymap

### PR DESCRIPTION
**Pull request by ishtob**
making some changes to keymap

### CODE REVIEW

**Comment by drashna** [comment]
You have some conflicts here. :)

**Comment by ishtob** [comment]
sorry looks like i was doing the PR from an un-updated branch, it included a patch of something already merge, causing the conflict

**Comment by noroadsleft** [comment]
What's up with the readme files?

- https://github.com/qmk/qmk_firmware/blob/bb48a8098a14e6563db93e49b6622c9b0204702c/keyboards/handwired/fivethirteen/readme%20(Case%20Conflict).md
- https://github.com/qmk/qmk_firmware/blob/bb48a8098a14e6563db93e49b6622c9b0204702c/keyboards/handwired/gamenum/readme%20(Case%20Conflict).md

**Comment by ishtob** [comment]
> What's up with the readme files?
> 
>     * https://github.com/qmk/qmk_firmware/blob/bb48a8098a14e6563db93e49b6622c9b0204702c/keyboards/handwired/fivethirteen/readme%20(Case%20Conflict).md
> 
>     * https://github.com/qmk/qmk_firmware/blob/bb48a8098a14e6563db93e49b6622c9b0204702c/keyboards/handwired/gamenum/readme%20(Case%20Conflict).md

fixed, not sure why they showed up. maybe a dropbox issue

**Comment by drashna** [comment]
Was this ready to go?

**Comment by ishtob** [comment]
yes good to merge now

**Comment by drashna** [comment]
Awesome!

**Pull request merged**
