### PR TITLE
Lily58 Add support for RGB MATRIX

### PR DESCRIPTION
**Pull request by ShadowProgr**
Add support for rgb matrix for folks using Lily58-Glow

## Description

There was no `g_led_config` in the code to support the rgb matrix for [Lily58-Glow](https://github.com/qtkb/Lily58-Glow). I created this PR so other Lily58-Glow users could have the sweet rgb matrix effects without spending time setting it up.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Duplicate of #7495 and #8890, this is a lighter touch so maybe gets my vote? (though last time I checked it was still an unofficial hardware fork, so might still get in the way long term)

**Comment by ShadowProgr** [comment]
> Duplicate of #7495 and #8890, this is a lighter touch so maybe gets my vote? (though last time I checked it was still an unofficial hardware fork, so might still get in the way long term)

I just took a look at those 2 PRs and I think those 2 and mine are different? #7495 and #8890 seem to only differ from original lily58 by the amount of LEDs. My PR adds `g_led_config` so that end-users can have working RGB matrix just by defining `RGB_MATRIX_ENABLE`, the other 2 doesn't have that.

Also #7495 seems to have 128 LEDs (I wonder how much power does it need lol), I don't think it's the Lily58-Glow.

Regarding possible long term issues that might arise, I think it would be better to have a separate glow version as in #8890. And then I can add RGB matrix support to it instead of editing the official rev1, which currently doesn't have per key RGB

**Comment by ShadowProgr** [comment]
Yes that makes sense, I will move all of this to lily58/glow. But I'll probably do so after qmk:future merges into master, since it lily58 code is refactored in it.

**Comment by noroadsleft** [comment]
Sounds good @ShadowProgr, I'll mark this as being `on hold` until then.

**Comment by ShadowProgr** [comment]
So I started working on this today and found out that since Lily58 uses split common now, it cannot have rgb matrix working (for the slave side) until #5998 is merged.

Now since lily58-glow main changes from official version is rgb per key, it's kinda pointless to implement this PR without rgb matrix working, putting this on hold again.

Am I missing anything or am I basically stuck until rgb matrix support is brought over to split common?

**Comment by AnanyaKirti** [comment]
is it working now?

**Comment by ShadowProgr** [comment]
Woah it's been so long I completely forgot about this.

I'll probably get it done this weekend

**Comment by tzarc** [comment]
Removed the tags preventing stalebot from kicking in.
If it's worth going in, I'd suggest picking it back up.

**Pull request closed without merging**
