### PR TITLE
Merge pull request #2 from qmk/master

### PR DESCRIPTION
**Pull request by o193746285**
update from original

### CODE REVIEW

**Comment by o193746285** [comment]
update from original

**Comment by drashna** [comment]
This doesn't change anything. 

Were you trying to add something here?

**Comment by o193746285** [comment]
Sorry I was just trying to do a pull request from the master branch to update my fork. I'm not familiar with github still and googled the steps. Where did I go wrong? 
--------------------------------------------
On Thu, 5/24/18, Drashna Jaelre <notifications@github.com> wrote:

 Subject: Re: [qmk/qmk_firmware] Merge pull request #2 from qmk/master (#3035)
 To: "qmk/qmk_firmware" <qmk_firmware@noreply.github.com>
 Cc: "o193746285" <scizor09@yahoo.com>, "State change" <state_change@noreply.github.com>
 Date: Thursday, May 24, 2018, 5:29 PM
 
 This doesn't change
 anything.
 Were you trying to add something here?
 
 —
 You are
 receiving this because you modified the open/close state.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by drashna** [comment]
You're trying to update your repo? 

Then you need to do so locally, ideally.  `git merge` is the simplest way to do that. Otherwise, git rebase is cleaner, IMO. 

But to do this, you need to make sure you clone from your fork, and then set the upstream:
https://help.github.com/articles/configuring-a-remote-for-a-fork/

Then, you'd want to do this: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

And ... because merge conflicts are pretty much inevitable: https://help.github.com/articles/addressing-merge-conflicts/

**Comment by drashna** [comment]
And I'm going to close this.  If you need more help with this, open an issue and I (or somebody else) will assist you there.

**Pull request closed without merging**
