### PR TITLE
[Keymap] nharward = qwerty/vi miryoku + swap(space, backspace)

### PR DESCRIPTION
**Pull request by nharward**
## Description

Keymap based on miryoku (copying + patching miryoku source). Customization uses QWERTY, vi-navigation, and most importantly swaps the space and backspace keys similar to the Kinesis Advantage2.

## Types of Changes

- [ ] ~Core~
- [ ] ~Bugfix~
- [ ] ~New feature~
- [ ] ~Enhancement/optimization~
- [ ] ~Keyboard (addition or update)~
- [x] Keymap/layout/userspace (addition or update)
- [ ] ~Documentation~

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] ~My change requires a change to the documentation.~
- [ ] ~I have updated the documentation accordingly.~
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] ~I have added tests to cover my changes.~
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — COMMENTED** [review]
I'm actively opposed to the symlinks here.

**Comment by nharward** [comment]
> I'm actively opposed to the symlinks here.

Will put in draft while I remove symlinks then will resubmit. Any other issues besides symlinks?

**Comment by nharward** [comment]
> > I'm actively opposed to the symlinks here.
> 
> Will put in draft while I remove symlinks then will resubmit. Any other issues besides symlinks?

Updated to remove symlinks, instead copying original source from miryoku then patching with my customizations.

**Comment by nharward** [comment]
Running `make all:nharward` locally fails a few keyboards whose firmwares compile but resulting bin sizes are too big (listed below). I saw similar failures running `make all:manna-harbour_miryoku` which is what this keymap is based on, so hopefully this PR is still OK even with these failures.

Failed locally with size too big:
* boardsource/microdox/v1
* boardsource/microdox/v2
* crkbd/r2g
* kakunpc/suihankey/split/rev1
* pteron36

**Comment by zvecr** [comment]
Unfortunately since this PRs creation, QMK has [changed its stance](https://docs.qmk.fm/#/ChangeLog/20230827?id=notable-changes) on accepting user keymaps to the repository.

> qmk/qmk_firmware is no longer accepting PRs for keymaps other than for manufacturer-supported keymaps. User keymap workflow has been documented [here](https://docs.qmk.fm/#/newbs) for several years. This change is to progressively reduce the maintenance burden on the project, and to allow us to focus on the core features of QMK.

In the near future we will be providing a more user focused workflow for keymaps, but till then the suggestion is to keep changes in your own fork.

While we appreciate the time that was taken on this PR, hopefully you understand we are closing it, so that QMK can improve in the long term.

**Pull request closed without merging**
