### PR TITLE
Establish support for Bathroom Epiphanies Tiger Lily controller

### PR DESCRIPTION
**Pull request by TerryMathews**
Code to support replacement controller for Filco Majestouch 2 104 key keyboard. BE advises code will also work with the Black Petal controller - I don't have one to test with. Tests working perfectly on my Filco.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Awesome! Is there any reason for the custom matrix? It looks like it could be adapted to use the quantum one with a `matrix_int_kb`.

**Comment by TerryMathews** [comment]
Honestly, I don't know. I just adapted the existing frosty_flake code in QMK with the correct pin mapping from the TMK tree. I know all these controllers use a pair of HC42 decoders in order to compress 20 rows into 8 signal lines - can QMK's internal matrix code manipulate decoders like that now? I thought it could only handle straight-pin addressing.

**Comment by jackhumbert** [comment]
Ah, the decoders might make that difficult then. I didn't catch that in the matrix file. Sounds good - thanks!

**Comment by TerryMathews** [comment]
I imagine any keyboard controller using decoders in this matter would need to scan the matrix in a similar manner. It would be neat to turn this code into an in built function in QMK, an alternative matrix.

Another project for another day.

**Pull request merged**
