### PR TITLE
Remove custom backlight code for PS2AVRGB boards

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

And in the process, adding proper LED indicator support to them. Some are guesses based on form factor and available images, so if anyone has any of these boards and knows they have or don't have certain lock LEDs, please comment!

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Oops. Done.

**Comment by noroadsleft** [comment]
A lot of keymaps are too big on this branch in Travis:

Defaults that are too large:

- donutcables/budget96
- exclusive/e6v2/le_bmc
- exclusive_e6v2/oe_bmc
- facew
- mehkee96
- singa

Fix now, or do another PR?

**Comment by fauxpark** [comment]
Yep, turned off Console for them - hopefully Travis will be happier.

**Comment by noroadsleft** [comment]
Much better, thanks!

**Pull request merged**
