### PR TITLE
Found a bug in `layer_state_cmp`

### PR DESCRIPTION
**Pull request by colinta**
Fixes `layer_state_cmp` when layer is "default" layer.  The default layer, `0`, can be activated two ways:

```
layer_clear();  // layer_state = 0
layer_move(0);  // layer_state = 1UL<<0 = 1;
```

My initial implementation of `layer_state_cmp` had a special case for when `layer_state == 0`, but not for `layer_state == 1`

@jackhumbert I'd love to add tests to make sure `layer_state_cmp` works as I'd expect, but I couldn't figure out how to write specs.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Nice! I might have missed some convos on Gitter, but I think @fredizzimo might be able to help with that - he implemented the test system we have now :) would you like to wait to merge until you're able to mess around with those?

**Comment by colinta** [comment]
I’ll hit him up on gitter, this has been tested in “production” code, so I think it’s GTG.

**Comment by fredizzimo** [comment]
This looks good to me

**Comment by colinta** [comment]
@jackhumbert @fredizzimo success!!  thanks for the help & patience.  good to merge.

**Comment by jackhumbert** [comment]
Awesome! Thanks folks :)

**Pull request merged**
