### PR TITLE
Allow to specify serial to dfu-util flash

### PR DESCRIPTION
**Pull request by akatrevorjay**

### CODE REVIEW

**Comment by akatrevorjay** [comment]
Bump?

**Comment by jackhumbert** [comment]
I'm generally inexperienced with chibios stuff, so I'll leave this for @fredizzimo when he has time to weigh-in!

**Comment by fredizzimo** [comment]
Sorry for the delay. 

The changes looks good to me, but it would be good if you also could update the documentation with instructions how to use it.

**Comment by fredizzimo** [comment]
@jackhumbert, I think you can merge this as the Wiki could be updated any time.

**Comment by jackhumbert** [comment]
Sounds good :) thanks!

**Pull request merged**
