### PR TITLE
Add pcewing Speedo v3 keymap

### PR DESCRIPTION
**Pull request by pcewing**
## Description

* Add my personal keymap for the CozyKeys Speedo v3 keyboard
* Add some code under `users/pcewing` for a key repeater
    * Useful for repeatedly pressing mouse button 1 while a key is held
    * Similar to "rapid fire" feature on some game controllers

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]
Very neat!

Also, it might be worth looking into the deferred executor code, as that may be able to simplify some of your code (but possibly not).

**Comment by pcewing** [comment]
Not familiar with the deferred executor stuff but I'll check it out!

**Review by keyboard-magpie — CHANGES_REQUESTED** [review]
Agree, very cool- to the point where it would be awesome to include a readme.md in your userspace for other users, to briefly explain what you're doing.

**Comment by pcewing** [comment]
Sure thing, if you want to hold off on merging I can add this to the PR 👍

**Comment by drashna** [comment]
> Not familiar with the deferred executor stuff but I'll check it out!

https://docs.qmk.fm/#/custom_quantum_functions?id=deferred-execution

Basically, it lets you run code at an interval.  It's more reliable than relying on matrix scan, and timers, too. 

I personally use it for a few things, such as luna/etc animation timing, and the startup animation for rgblight.


> Sure thing, if you want to hold off on merging I can add this to the PR 👍

Not a problem, at all.

**Comment by pcewing** [comment]
Ok I just added a readme with an explanation of the feature and a tutorial of how to use it.

Since I could see this being something other folks may want to use, I made the implementation a little bit safer:
* Converted `key_repeater_t` to an opaque type so that internal state can't be accidentally modified
* Optimized the case where min/max values are the same
    * Don't bother randomly generating the duration in this case which is pointless
* Make sure all calls are safe-guarded against `NULL`
* No-op if the user sets the key code to `KC_NO`

Also realized `keyboard_post_init_user` exists so I switched to using that instead of checking the static bool in my `matrix_scan_user` and initializing the rng that way.

After reading that doc you linked, I do think this could probably be rewritten to use the deferred execution feature. Rather than polling the repeater class could do something like:
```
- When repeater is enabled in `process_record_user`:
    - Execute "keypress"
        - If repeater has been disabled, early out (Never true on first execution)
        - Register keycode
        - Determine key press duration P ms
        - Register a deferred callback to "keyrelease" after P ms
    - On "keyrelease"
        - Unregister keycode
        - If repeater has been disabled, early out (Never true on first execution)
        - Determine wait duration W ms
        - Register a deferred callback to "keyrelease" after W ms
- The 2 callbacks will just continue to execute each other via deferred execution until the repeater is disabled via another event in `process_record_user`
```

For now I'd like to leave it as is so I can at least get my keymap merged and I'm not too concerned with the performance hit in `matrix_scan_user` since most of the time this just no-ops but might revisit that implementation change later on

**Review by keyboard-magpie — APPROVED** [review]

**Pull request merged**
