### PR TITLE
nix: parse requirements-dev.txt to construct development shell

### PR DESCRIPTION
**Pull request by adisbladis**
## Description

This completely removes the poetry environment & poetry2nix from qmk and instead parses requirements-dev.txt and constructs an environment completely with packages from nixpkgs.

That means that there is no more need to manually keep pyproject.toml in util/nix up to date and no need to do any dependency locking.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by adisbladis** [comment]
Ping @sigprof

**Comment by sigprof** [comment]
Sorry, I completely missed this PR in the flood of other notifications.

@purcell What do you think about this approach (using Python packages from Nixpkgs instead of rolling our own through Poetry)?  The Python packages in Nixpkgs are sometimes not the most recent ones (e.g., `jsonschema` is 4.19.0, even though 4.20.0 had been released), but apparently all required packages are present there.  In fact, there is even a `qmk` package in Nixpkgs which provides QMK CLI.

One potentially problematic thing here is that there are some talks about pinning the `jsonschema` dependency to 4.17.3, because more recent versions require Rust to build (through the `rpds-py` dependency), which is a problem for some environments; however, Nixpkgs already has the 4.19.0 version, and does not have any older ones (in general, only a single version of each Python package is provided in Nixpkgs, unless there are some important users of old major versions).

We will also lose the dependabot notifications about the Python packages being out of date (dependabot can generate PRs to update `poetry.lock`).

**Review by sigprof — CHANGES_REQUESTED** [review]
Also this does not actually work — there is no `qmk` executable in the resulting environment, because `requirements.txt` does not actually contain `qmk`, and there is no `python3.pkgs.qmk` in Nixpkgs anyway (there is a top-level `qmk` package, which is built as a Python application, not a library, and that package already does mostly the same things as this `shell.nix`).  Previously `pyproject.toml` contained the `qmk = "*"` entry which had been added manually (not just copied from `requirements.txt`).

**Comment by purcell** [comment]
I commented there without reading back through everything. In general I trust @adisbladis' judgement very much, and he wrote poetry2nix in the first place, so I'm happy with the proposed approach if that's what he thinks is best.

**Pull request closed without merging**
