### PR TITLE
update keymap to readable version

### PR DESCRIPTION
**Pull request by yulei**
## Description
update keymap to human readable version and fixed inconsistent between keymap and info.json 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by yulei** [comment]
> Are the deleted `K113` and `K413` locations present on this keyboard's PCB?

yes, they exist on the keyboard. but the currently plate does not support them.

**Comment by noroadsleft** [comment]
Is it possible to build the board without a plate?

**Comment by yulei** [comment]
> Is it possible to build the board without a plate? Trying to determine if a `LAYOUT_all` macro is needed here.

This board does not support plateless build. and currently there are two plate:
https://github.com/yulei/qmk_webusb_tool/blob/master/public/m12_fullplate.jpg
https://github.com/yulei/qmk_webusb_tool/blob/master/public/m12_halfplate.jpg

non support split backspace and right shift.

**Comment by noroadsleft** [comment]
@yulei Thanks. In that case I'm good with these changes as-is.

**Pull request merged**
