### PR TITLE
Iris send backlight info over i2c

### PR DESCRIPTION
**Pull request by joedevivo**
Backlight state on the slave half of the keyboard was not being written when using I2C, only Serial.

This PR uses the first byte of the i2c_slave_buffer, and writes the information there before switching to a read operation for the slave's matrix.

### CODE REVIEW

**Comment by joedevivo** [comment]
@nooges, are you the right person to look at this?

**Comment by nooges** [comment]
@joedevivo Yeah, I'll take a look at it today.

**Comment by joedevivo** [comment]
@nooges mind looking at this?

**Comment by nooges** [comment]
Okay, tested it out, looks good.

@jackhumbert Ready to go

**Comment by jackhumbert** [comment]
Awesome - thanks folks!

**Pull request merged**
