### PR TITLE
Require Python 3.7

### PR DESCRIPTION
**Pull request by skullydazed**
## Description

Bump our required Python version to 3.7. This also removes support for linux distributions which are currently broken.

## Types of Changes

- [x] Core
- [x] Enhancement/optimization

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by skullydazed** [comment]
We could use some wider eyes on this one. Pinging people who have contributed some of the niche OS support:

@BlitzKraft @chax @csssuf @manuel-arguelles @petejohanson @shieldsd @skewwhiffy @umanwizard @zjp

**Comment by zjp** [comment]
Per https://www.gentoo.org/support/news-items/2020-04-22-python3-7.html Python 3.7 is now the default python version on Gentoo, so I think this is OK.

**Comment by BlitzKraft** [comment]
It looks good to me. Sabayon is rebranding to mocaccinoOS. I am not sure if it is relevant. 

Is it possible to have the installer skip the uname check and have it use a generic tool with some warning? For example all debian based distros can use apt. So, check for an env variable, say, `QMK_INSTALL_DISTRO`. And if it exists, and set to a valid value, uname can be skipped, and the debian/ubuntu installer will be called. The installer logs/prints this preference. 

The reason I mention this is because of the sabayon rebranding, as well as covering as many use cases as possible without having to account for the name of each distro uname string. User from elementary/popOS/zorin etc can set variable to debian, and the installer does its thing.

**Comment by skullydazed** [comment]
> Is it possible to have the installer skip the uname check and have it use a generic tool with some warning?

As long as `ID_LIKE` in `/etc/os-release` contains `debian` you should match the existing debian check. I don't know the history behind why sabayon/mocaccino has a separate script, but if that reason no longer applies we'd be very happy to have one less platform to explicitly support.

**Comment by BlitzKraft** [comment]
sabayon has a different package manager. Hence the need for the separate script. ID_LIKE is not guaranteed to be present, is it?

**Comment by skullydazed** [comment]
We check both `ID` and `ID_LIKE`. Our grep is actually overly broad for the purpose, in that we're pulling in any variable from `/etc/os-release` that contains the string `ID`, but it's been "good enough" for a long time.

The use case you describe is already handled by [`/etc/os-release`](https://www.freedesktop.org/software/systemd/man/os-release.html). If sabayon can use the same install script as another distribution that's the best way to invoke the proper script.

**Comment by chax** [comment]
Solus currently uses pyrhon 3.7.9 as main python3 version, and since Solus is rolling release distro, version will only go up. You can see current version here: https://dev.getsol.us/source/python3/

Do you need me to test this PR?

**Comment by skullydazed** [comment]
> Do you need me to test this PR?

If you're confident it works fine there's no need to test now. There will be time to test all of `develop` before it's merged into `master` in a couple months time.

**Review by zvecr — APPROVED** [review]

**Pull request merged**
