### PR TITLE
Update info.json - Program Yoink

### PR DESCRIPTION
**Pull request by melonbred**
Revise `info.json` for ortho_split layout.

## Description
The PR to include ortho support for the Program Yoink just got merged yesterday, and I noticed a couple of lines in `info.json` slipped past my review. Really apologize for such a minor PR, but this picks up the two revisions and should show ortho_split correctly in configurator.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Review by noroadsleft — APPROVED** [review]
I suspect this file may need some more fixes, but it'll be easier for me to give it an in-depth look if we get this in. `info.json` files are my specialty around here.

**Comment by noroadsleft** [comment]
Thanks!

**Comment by noroadsleft** [comment]
K, I've done my in-depth check and determined more fixes are needed.

PR incoming...

**Comment by noroadsleft** [comment]
@melonbred, is this one PCB that supports both staggered and ortho layouts, or is there one PCB for staggered and a second PCB for ortho?

**Comment by melonbred** [comment]
> @melonbred, is this one PCB that supports both staggered and ortho layouts, or is there one PCB for staggered and a second PCB for ortho?
@noroadsleft Staggered and ortho layouts are separate. However, the pinout for column and rows are the same. Should they listed as separate keyboards?

**Comment by noroadsleft** [comment]
@melonbred Ah yes, they should be listed as separate keyboards.

I can do this but I'd need you to check and make sure I don't break anything with the changeset.

**Comment by melonbred** [comment]
@noroadsleft I can definitely review if you have time to make the change.

For my future reference, is there a naming convention to break out stagger and ortho of the same keyboard name?

Thanks for your review! Still learning lots with qmk, and I appreciate your assistance/insight.

**Comment by noroadsleft** [comment]
@melonbred [The Ave by Kingly Keys](https://github.com/qmk/qmk_firmware/tree/1bb9f155a67414d41b219e6834396e0fbca11ef7/keyboards/kingly_keys/ave) does something similar.

**Comment by melonbred** [comment]
@noroadsleft Thank you for the reference. 

Having looked at The Ave and a few other keyboards for reference, I have a couple of questions:

- I noticed that configurator does not pull the default keymap for Program Yoink. Is there something that specifically needs to be done in `info.json` for configurator to populate?

- How does configurator handle rotary encoder support? In the case for the Program Yoink keyboard, I have included rotary encoder support in the default keymap.

**Comment by noroadsleft** [comment]
> * I noticed that configurator does not pull the default keymap for Program Yoink. Is there something that specifically needs to be done in `info.json` for configurator to populate?

Ah, QMK Configurator doesn't use the keymaps that exist on this repository. That was actually the reason why I mentioned needing to do an in-depth check on your `info.json` file – I'm going through adding default keymaps to QMK Configurator, which are on another repository. I already have the files made, but I need to make sure everything with this codebase and its `info.json` files is sound.

> * How does configurator handle rotary encoder support? In the case for the Program Yoink keyboard, I have included rotary encoder support in the default keymap.

QMK Configurator doesn't yet support Rotary Encoders natively – Configurator-compiled firmware doesn't include encoder support in the keymaps, but there is a work around for this that will support the encoders, but it won't allow the users to modify what the encoders do natively in Configurator. I'm glad you mentioned this, because that's something I didn't think about when I was thinking/working through splitting up the support for the Staggered and Ortho PCBs.

**Pull request merged**
