### PR TITLE
Rebound underglow settings for via

### PR DESCRIPTION
**Pull request by Rossman360**
## Description

Rebound has allowed underglow for a while now, and the next rev has it pre-soldered, so I'd like to enable it for Via, which I also happen to need an open PR for here, I think.

I accidentally blew up https://github.com/qmk/qmk_firmware/pull/12268/commits/eca1ab16cf4c96b5c7dc864430d7f83b3c1d5242 when I created this, so I added the most recent changes from that to this.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ x] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Rossman360** [comment]
okay so I either forgot I still had an open PR ( https://github.com/qmk/qmk_firmware/pull/12029 ) or at least didn't realize I would blow it up with this one. The most recent commit here contains all the requested changes from the linked PR. Hope that's okay.

**Review by drashna — APPROVED** [review]

**Comment by tzarc** [comment]
Why does this PR contain a second keyboard?

**Comment by Rossman360** [comment]
> Why does this PR contain a second keyboard?

I forgot the PR for first keyboard was still open when I rebased my master for submitting the second one

**Comment by drashna** [comment]
That's why we don't recommend using the master branch for PRs, ever.  it can/will get you into this exact situation. 

For reference:
https://docs.qmk.fm/#/newbs_git_using_your_master_branch

And basically, could you pull out the specific commit, and the associated keyboard changes.  You can move them over to a separate branch, and open that branch as a PR, as well.

**Comment by Rossman360** [comment]
Trio directory nuked!

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
For future reference, we recommend against committing to your `master` branch as you've done here, because pull requests from modified `master` branches can make it more difficult to keep your QMK fork updated. It is highly recommended for QMK development – regardless of what is being done or where – to keep your master updated, but **NEVER** commit to it. Instead, do all your changes in a branch (branches are basically free in Git) and issue PRs from your branches when you're developing.

There are instructions on how to keep your fork updated here:

[**Best Practices: Your Fork's Master: Update Often, Commit Never**](https://docs.qmk.fm/#/newbs_git_using_your_master_branch)

[Fixing Your Branch](https://docs.qmk.fm/#/newbs_git_resynchronize_a_branch) will walk you through fixing up your `master` branch moving forward. If you need any help with this just ask.

**You do not need to close this pull request at this time.** Until your pull request is merged, please continue to commit relevant changes to your `master` branch.

**Pull request merged**
