### PR TITLE
Fix problem that Chidori is not recognized by host computer.

### PR DESCRIPTION
**Pull request by ka2hiro**
## Description

Added USB-related definitions to config.h that were changed by consolidated usbconfig.h.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by keyboard-magpie** [comment]
Would you be able to provide some context as to what issues you were having, and how you have discovered these changes?

**Comment by ka2hiro** [comment]
@keyboard-magpie 
When I plugged Chidori, with the latest QMK written to it, into my computer, it was not recognized as a USB device.

I have not been following QMK updates for a while, so I checked the code in the latest the repository and noticed that usbconfig.h has been consolidate.

The consolidated usbconfig.h defined default values that were not defined in Chidori's old usbconfig.h, so I defined values to cancel them.

Hope this answers your question.

**Comment by keyboard-magpie** [comment]
Thanks. I will try this on some of my VUSB boards I have here (although I personally have not had issues with recent QMK code). From running this past @zvecr briefly a concern may be how USB_COUNT_SOF interacts with suspend.

**Comment by pondodev** [comment]
@keyboard-magpie for what it's worth, my mate who had recently built a chidori found that latest on master showed this issue of not enumerating as a USB device. I have that chidori with me at the moment for testing and have been able to reliably reproduce this issue which is then fixed with this patch. interestingly enough though, i've not really experienced this issue on my one other keyboard running V-USB, a plaid. this said it is known to sometimes not be recognised by the host machine when plugged in so maybe this is the cause for that?

**Comment by ka2hiro** [comment]
@drashna @fauxpark @zvecr 
Hello, Is there any missing information to review this PR? If so, please let me know.

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
