### PR TITLE
[Feature] Compilation warning if both `keymap.json` and `keymap.c` exist

### LINKED ISSUE #19467: [Feature Request] Keymap compilation warning
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

When compiling a keymap whose folder contains both `keymap.json` and `keymap.c`, `json` takes precedence **without any warning** (which isn't consistent with the way `info.json` vs `c`/`h` works, so i was expecting it to work the other way around)

I tried fixing it, but looking at the `compile.py` I'm pretty sure it only builds and runs the `make` command and couldn't figure out neither
a) How to check if both files exist
b) How to print a warning-formatted string

Line 157 on `builddefs/build_keyboard.mk` is checking if the `keymap.json` exists, could maybe add another `if` on that block to check if `.c` exists too, and throw a warning similar to the ones like "info.json configuration will be override by config/rules" 
I would write it if I had any knowledge about `mk` but I guess it will be pretty much trivial for someone who knows

I dont have any idea on which of the two should take precedence, but the warning would definitely avoid some headaches

### PR DESCRIPTION
**Pull request by elpekenin**
## Description
Small changes so that we look for both files, instead of not searching for C file when JSON exists.
With this information we can check if both were found to throw a warning, and then procede to compile JSON.
This prevents people(aka happened to me a few weeks ago) from going insane if working on a folder where `json2c` has been used and JSON hasn't been deleted.

Tested:
- JSON- or C-only setups work as usual
- Having none of them throws the regular "no keymap found" error
- Having both shows the warning and compiles the JSON file

⚠️  This is my 1st time ever writing MK, it can probably be cleaned/simplified, but I've struggled enough getting it to work.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [X] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #19467 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by elpekenin** [comment]
Dumb bot remove the tag...

I've updated to remove the `ifeq` which will always be true as the `KEYMAP_PATH` variable isn't set on `build_json.mk` anymore. 

However, this made me realize that my changes will pull `mk` files from the keymap folder on `keymap.json` compilations while previous code didn't do such thing... No idea if it could cause any issues and was made like that intentionally or not

**Review by tzarc — APPROVED** [review]
Seems fine.

**Review by zvecr — APPROVED** [review]

**Comment by zvecr** [comment]
> However, this made me realize that my changes will pull mk files from the keymap folder on keymap.json compilations while previous code didn't do such thing... No idea if it could cause any issues and was made like that intentionally or not

If this is `rules.mk` files adjacent to `keymap.json`, this seems fine to me.

**Comment by zvecr** [comment]
Its done later, as the searching is skipped when running `compile_configurator_json` from the python world. While it shouldnt do any harm it probably should be updated to not set `KEYMAP_PATH`.

**Comment by tzarc** [comment]
@elpekenin was zvecr's query handled?

**Comment by elpekenin** [comment]
> @elpekenin was zvecr's query handled?

Im not sure what im supposed to change, to be honest... If both files (c and json) exist, `KEYMAP_JSON_PATH` and `KEYMAP_PATH` will be the same. Then, since they were splitted into 2 different variables (to be able to warn after finding for both) from `KEYMAP_PATH`, i copy the value (just for extra safety tho, it shouldn't be needed). So, new code should work fine (and the same way as old one), and as far as my testing back in the day went, it does

Perhaps you are refering to the consistency i asked about... Given my lack of knowledge of the `compile_configurator_json` pipeline -and the whole makefile thing- i opted not doing anything about it, but the changes on the PR are good to go from my side

**Pull request merged**
