### PR TITLE
Switch process_combo to using global register and timer

### LINKED ISSUE #1984: Multiple COMBO cause a key press for each occurence of the given key
with my (Action) [layout](https://github.com/gcaferra/qmk_firmware/blob/master/keyboards/tada68/keymaps/devchords/keymap.c)

when I press F   3 [f] are typed when i press D 2 [d] are typed and so on for each occurrence in the combo_key matrix this seems like is needed to "exit" after the first sending  if  the key if already sent before this [line](https://github.com/qmk/qmk_firmware/blob/05f15b789f4f6098a72474e028a19fdbccdaf2d3/quantum/process_keycode/process_combo.c#L98)

Someone can point me to a solution for this?

### PR DESCRIPTION
**Pull request by rsheldiii**
This fixes #1984

Since combos keep local state about what keys have been previously pressed, when combos are layered, multiple keypresses will register for any key with multiple combos assigned to it. Short of keeping some sort of dynamic inter-combo record of what keys have been emitted I don't think there's a viable way to solve this with local state.

In order to fix this, I switched process_combo to use a global keycode / keyrecord register and timer. When a keypress is consumed by a combo, it gets stored in the register and the timer is updated; when the next keypress takes too long or a key is pressed that isn't part of any combo, the buffer is emitted and the timer reset.

This has a few side effects:

1. I couldn't _not_ fix combo keys printing out of order (as mentioned [here](https://github.com/qmk/qmk_firmware/pull/960#issuecomment-269439454)) while also fixing this bug, so combo keys print in order correctly when a combo fails
2. Since combos no longer have local timers, the logic around when combos time out has changed. now that there is a single timer pressing any combo key (including one in a different combo) will reset the timer for all combos, making combo entry a little more lenient
3. Since combos no longer have local keycode / keyrecord state, there is an edge case where incomplete combo keys can be consumed. if you have a combo for a+s = tab and a combo for b+n = space, if you press a+b+n, only a space will be emitted. This is because when b+n completes successfully, it drops the register. This could be mitigated by having combos only drop records from the register for which they have keycodes, but a good way to do that escapes me.

I'm more than happy to take comments and do some refactoring if need be! I know this is a lot of changes for a bug fix, but I couldn't find a simpler way to fix the bug.

### CODE REVIEW

**Comment by fredizzimo** [comment]
This seems to be a good improvement over the previous implementation, and I think treating keys that are not part of a combo as a way to abort the combo is a good way to do it.  So this change is probably good to merge as it is, even if quite a few problem remains. But they can be fixed later.

I have several suggestions for different ways of fixing some of the ordering problems. One way is to support flushing of the start of the buffer too, but that doesn't support activating multiple combos with mixed order of the pressed keys:
So for your third example, it would work like this

1. when you press `a` it's buffered
2. when you press `b` then a `a` is removed from the buffer and output, `b` is buffered
3 When `n` is pressed, then `b+n` combo is activated

In order to support activation of multiple combos with mixed order. Something like this could be imlemented
1. when you press `a` it's buffered
2. when you press `b` it's buffered. This is a bit special since the buffer now contains two potential combo combinations.
3. When `n` is pressed, we still don't do anything, since we don't know if this will be a dual combo combination or not (we haven't used up all keys in our buffer)
4. 
    a. If `s` is now pressed, we can activate both combos
    b. If some other key is pressed instead, we start from the beginning of the buffer, and notice that `a` can't be part of any combos, so it's output. Then the rest `b+n` can be processed as a combo.

It gets slightly more complex than this for even more simulataneous combinations, but I think it's implementable.

All algorithms should furthermore process releases of keys correctly, so for example if you firt press `a` then release it, it should be threated as an aborted combo, and a keypress of `a` should be sent.

For releases of combos, I think the current buffer approach is not good enough. We should probably have a list of all currently active combos, and process key releases against those first.

**Comment by rsheldiii** [comment]
hey @drashna, just saw this in my email. Do you need anything from me on this? I don't have permissions to merge this PR, this is my first contribution. I was unaware it hadn't been merged so happy to see it go into master :)

**Comment by drashna** [comment]
It looks good to me. The only think I'd like to see is it reformatted to conform to the [QMK coding convention guidelines](https://docs.qmk.fm/#/contributing?id=coding-conventions).  But that's not mandatory. 

But I wanted some of the others to check the code out first.

**Comment by drashna** [comment]
This has some merge conflicts.  Would you mind fixing them?

**Comment by rsheldiii** [comment]
will do!

**Comment by drashna** [comment]
Any update on the merge conflicts?

**Comment by rsheldiii** [comment]
@drashna sorry for the wait, let this get away from me. I just merged up and tested with a+s=1 and a+s+d=2 (patch [here](https://gist.github.com/rsheldiii/db03c1d54e1da8c5d32bf4fe81bb026d)) and got what I was expecting

**Comment by rsheldiii** [comment]
those CI failures don't look related to my changes...

**Comment by drashna** [comment]
Correct. Let me see if I can help push this along.

**Pull request merged**
