### PR TITLE
fix bootloader size for teensy2.0++ to 2048 bytes

### PR DESCRIPTION
**Pull request by greenjack-z**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
This is incorrect. The Halfkay bootloader for the Teensy 2.0++ is 1024 bytes:
https://github.com/PaulStoffregen/teensy_loader_cli/blob/master/teensy_loader_cli.c#L1076
131072 - 1024 = 130048

**Comment by greenjack-z** [comment]
> This is incorrect. The Halfkay bootloader for the Teensy 2.0++ is 1024 bytes:
> https://github.com/PaulStoffregen/teensy_loader_cli/blob/master/teensy_loader_cli.c#L1076
> 131072 - 1024 = 130048

however here stated 2048 - https://beta.docs.qmk.fm/faqs/faq_build#:~:text=Note%20that%20Teensy2.,%2B%2B%20bootloader%20size%20is%202048byte.

and well known keyboard firmware builder use the 2048 in riles.mk and firmware works well

**Comment by fauxpark** [comment]
Yes, any value larger than actual will work fine, because that extra space (assuming the application code is small enough to not overlap) is usually just full of NOPs, so the processor will simply go through them until it hits the start of the bootloader code. But this is not really ideal, since this value is also used to calculate the amount of usable flash space for the usage % at the end of compilation.

That particular piece of the docs seems outdated and wrong, TBH it should be removed altogether since bootloader.mk abstracts this away from the user anyway. Does 1024 bytes not work then?

**Comment by greenjack-z** [comment]
I have some issues with the firmware done by QMK Configurator, so that is the first difference I've found. Probably it's not the case. So I will make PR with 2048 bytes in my keyb rules.mk file and test after merging. When if yes - I will come back to this PR.

**Comment by fauxpark** [comment]
I also note that the exact bootloader address is found here: https://www.pjrc.com/teensy/jump_to_bootloader.html
It lines up with what the teensy_loader_cli code says - `0x20000 - 0x400 = 0x1FC00`.

And in fact, changing `BOOTLOADER_SIZE` will not affect what address QMK will jump to anyway: https://github.com/qmk/qmk_firmware/blob/master/tmk_core/common/avr/bootloader.c#L200

**Comment by greenjack-z** [comment]
So, looks like this parameter not affect at all?
However - I can check it by local rules.mk

**Comment by greenjack-z** [comment]
can I use QMK Configirator (or its fork) together with my fork branch of QMK firmware, instead of pull requests to master branch QMK Firmware each time I need to test something?

**Comment by fauxpark** [comment]
Yes: https://github.com/qmk/qmk_web_stack

**Comment by greenjack-z** [comment]
thanks will learn for

**Comment by greenjack-z** [comment]
> Yes: https://github.com/qmk/qmk_web_stack

Can I use it at GCloud instance or not? Looks like it's not right for it. I've got more success when run the docker comands from the QMK_Configurator page itself, however I can't realize how to run it with a lockal keyboards tree

**Pull request closed without merging**
