### PR TITLE
Add Melody96 Configurator key layout for PMK Nuclear base kit

### PR DESCRIPTION
**Pull request by donahue5000**
## Description

New to QMK, Configurator, and GitHub... apologies if i broke everything...
Trying to add new layout to the QMK Configurator for Signature Plastics Nuclear Data keycaps base kit, for a Melody96 with 1.25u modifiers on both sides of 6.25 space, full size 2.75 right shift, and all 1u keys in the numpad area.
It looks like info.json is where Configurator looks for key size/layout data? Maybe? It is the only place I see in the QMK Firmware repository where key dimensions are declared, so I assume Configurator looks here to generate it's keyboard graphic.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mechmerlin** [comment]
In addition to creating this layout,  there needs to be a corresponding LAYOUT macro set in the keyboard's `.h` file. 

However, typically speaking, keysets are made to accommodate the physical layout of a keyboard, rather than a board accommodating the keys available in a keyset. I looked at the base kit and it seems to fit a standard 100% keyboard. The melody96 is not a 100% keyboard nor does it have the most standard of keysizes. I would suggest that in addition to my earlier suggestion, a better name for this layout would also be appropriate.

**Comment by donahue5000** [comment]
Thanks mechmerlin, I will address the keyboards .h file and naming convention.

**Comment by yanfali** [comment]
Hey, so not really sure what this PR is about? How does a keyset need a layout? are you talking about the legends? Because we don't use the labels for the legends in configurator. If you want to add the colorway to configurator, then you need to modify configurator.

You would first need to get permission from Signature plastics, or the original designer. If they don't mind then we can add the colorway.

**Comment by donahue5000** [comment]
Just adding a layout to use 1u keycaps in place of 2u on the numpad in the Configurator. The name seems to be making waves, closing PR.

**Comment by yanfali** [comment]
Hey, sorry, didn't mean for you to close the PR. Was just trying to understand the intention.

**Comment by donahue5000** [comment]
No worries, I decided I don't understand the firmware well enough yet to be tinkering publicly. My intention was just to add a layout to the configurator so folks could generate a keymap with a base kit keycap set without buying all the extra special size miodifier kits, like short left shift and 1u right alt, ctrl etc.

**Comment by yanfali** [comment]
> No worries, I decided I don't understand the firmware well enough yet to be tinkering publicly. My intention was just to add a layout to the configurator so folks could generate a keymap with a base kit keycap set without buying all the extra special size miodifier kits, like short left shift and 1u right alt, ctrl etc.

We'd be happy to help you with that. It's a good way to learn

**Pull request closed without merging**
