### PR TITLE
SSD1306 OLED codes cleanup

### PR DESCRIPTION
**Pull request by ishtob**
## Description

The driver for SSD1306 has fragmented over the past year and now split between the keyboard folders, drivers/avr/ssd1306.c and qwiic/micro_oled.c. This PR is intended to close the gaps between the 3 and have a way to combine the features from these drivers into one unified driver.

## Types of changes

- [ ] Core
- [ ] Bugfix
- [ ] New Feature
- [ ] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* 

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by pelrun** [comment]
It looks like this code is doing multi-byte transactions in a really convoluted manner. i2c_writeReg should be used instead of doing it manually.

**Comment by ishtob** [comment]
> It looks like this code is doing multi-byte transactions in a really convoluted manner. i2c_writeReg should be used instead of doing it manually.

any advice would be appreciated, these codes are going a bit over my head.

from what I understand if I did writeReg, i would only be saving a line or two (no longer need to set the first byte of the array to 0x00 for command or 0x40 for data... then again I may be wrong. is there a better way to enter the string of bytes for the data section of the i2c_trasmit/writeReg?

**Comment by pelrun** [comment]
Have a look at https://github.com/pelrun/qmk_firmware/commit/abfb5b6c30ba5c7a94f5096df133358f44dabae7

We can do more than this, but it's a good start. clear_display() is left alone because it's programmatically sending a lot of 0's, which would require a large RAM buffer to do using ii2c_writeReg().

**Comment by ishtob** [comment]
part of the reason I am changing the send command function to use the byte array is because the i2c_master for arm does not have the `i2c_write()` function and any data has to somehow be made into a string and sent via `i2c_transmit` or `i2c_writeReg()`

**Comment by pelrun** [comment]
Also, renaming the functions isn't enough. i2c_master.c's API isn't simply renamed versions of the old i2c.c ones, the parameters required are different (mostly they just need a timeout value added to the end of the list.)

**Comment by ishtob** [comment]
so i took @pelrun and reset the branch and redid the codes, it now works wit hi2c_master without having the complicated buffering.... i think, can someone test this if they have a board with oled? the original ssd1306.c functions are all the same, just the i2c bits are changed

**Comment by drashna** [comment]
It looks like #5288 may compete with this, actually.  And that PR may be a better implementation.  

@ishtob if you wanted to take a look at that PR?  Because, personally, I'd like to see one unified implementation.

**Comment by skullydazed** [comment]
@ishtob what are your thoughts here? Do you want to work on this one or close this so we can focus on #5288?

**Comment by ishtob** [comment]
Agreed on closing this, #5288 looks much further along

**Pull request closed without merging**
