### PR TITLE
Prefer make over gmake

### PR DESCRIPTION
**Pull request by zvecr**
## Description

A fair amount of users have issues within MSYS due to `PATH` containing extra toolchains. A longer term solution of sanitising the environment is underway, however the solution to this point has to be uninstalling stuff or `MAKE=make` env workarounds.

Given the number of Windows users outweighs those of BDS variants, it makes sense to me that the `make` check be the other way round. This will help resolve issues in the short term.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
This breaks compilation on MacOS.

**Comment by zvecr** [comment]
I cant see how? was it previously using gmake?

**Comment by drashna** [comment]
Yup.  the gmake check was there, I think explicitly for macOS.

**Comment by zvecr** [comment]
Nope, was added for BSD.

**Comment by fauxpark** [comment]
Works fine for me.

Possibly should change the check to !gmake?

**Comment by drashna** [comment]
> Works fine for me.
> 
> ~Possibly should change the check to !gmake?~

if you run `qmk config user.parallel=2`, does it still work?

**Comment by skullydazed** [comment]
> Nope, was added for BSD.

It was added for BSD, but later on we found out that the `--sync-output` flag is not supported on the version of make shipped with macos. We have to use gmake to pick up the homebrew version of make.

**Comment by fauxpark** [comment]
> > Works fine for me.
> > ~Possibly should change the check to !gmake?~
> 
> if you run `qmk config user.parallel=2`, does it still work?

Doesn't seem to have done anything, actually. I still see `--jobs=1`.

**Comment by drashna** [comment]
> > > Works fine for me.
> > > ~Possibly should change the check to !gmake?~
> > 
> > 
> > if you run `qmk config user.parallel=2`, does it still work?
> 
> Doesn't seem to have done anything, actually. I still see `--jobs=1`.
> 
> EDIT: It's `compile.parallel`, apparently, and yeah, that breaks it.

if you already have compile.parallel, yeah, it will default to that.  If not, it falls back to user.parallel. (not confusing at all). 

However, it looks like adding `export MAKE="gmake"` to my .zshrc file fixes this.  But I don't think that's a good solution.  But adding a specific check for macOS feels cludgy, too.

**Comment by zvecr** [comment]
Leaning on a behaviour added for another platform seems a little fragile, however if gmake is being used outside the BSD case then im inclined to close and evaluate different solutions.

**Comment by skullydazed** [comment]
> But adding a specific check for macOS feels cludgy, too.

Platform differences are a fact of life. We have fought the good fight against platform specific code for a long time but TBPH I think we've caused ourselves more work than we've ever saved by avoiding platform specific code.

We have a similar problem with homebrew and needing to `brew link` specific versions of the toolchains. If we had OS specific code we could be checking for the versions we want and using those directly, instead of relying on `brew link`.

This PR shows the weak point of avoiding platform specific code- something that was added to be compatible with one platform ends up hiding a problem on another platform, but that context isn't captured.

**Pull request closed without merging**
