### PR TITLE
Support multiple pointing devices simultaneously 

### PR DESCRIPTION
**Pull request by daskygit**
## Description
Very early WIP to allow support for multiple pointing devices including multiple instances of the same driver.

Preliminary work has been done to allow for multiple sensors, it supports per device config, throttle, motion, rotation etc.

### Current issues

- Reports from target side can be missed (this also occurs with the current core code)

		sending initiator status back and delaying target caused pointer issues but no missed reports
		small delay on target side reduce number of missed reports

### To be completed
- [ ] Pass data structure to remove static variables from inside driver (allow multiple instances)
- [ ] Docs need a complete rewrite
- [ ] Comments
- [ ] Cirque driver extras - gesture/glide/tap
- [ ] Debugging for shared CPI
- [x] Per device call backs (init/task)
- [x] Simple call backs (init/task)
- [ ] Generic device OK check with a reset (already removed some error handling from some drivers to prep)
- [ ] Modify keyboards/keymaps

### Bonus points
- [ ] DD config
- [ ] Unit testing?
- [ ] Mouse button mapping (probably PR after)

### Options verified
- [ ] Motion pin
	- [ ] active low
- [ ] Throttle
- [ ] Pointing activity
- [ ] Mouse keys
- [ ] Set report
- [ ] Shared CPI
	- Initiator
	- [ ] Get target
	- [ ] Set target
	- Target
	- [ ] Get initiator
	- [ ] Set initiator

### Drivers tested 
I can test :white_check_mark: items but wait until the to be completed items are done before testing.

- ADNS5050
	- [ ] single
	- [ ] multiple
- ADNS9800
	- [ ] single :white_check_mark:
	- [ ] multiple
- Analog Joystick :white_check_mark:
	- [ ] single
	- [ ] multiple
	- [ ] click
- Azoteq IQS5XX :white_check_mark:
	- [ ] single 
- Cirque
	- I2C
		- [ ] single
		- [ ] multiple (Does it have an alternative I2C address?)
	- SPI
		- [ ] single :white_check_mark:
		- [ ] multiple
	- [ ] Mixed SPI/I2C
	- Glide 
		- [ ] single :white_check_mark:
		- [ ] multiple
	- Taps
		- [ ] single :white_check_mark:
		- [ ] multiple
	- Gestures
		- [ ] single :white_check_mark:
		- [ ] multiple
- PAW3204
	- [ ] single
	- [ ] multiple
- Pimoroni Trackball :white_check_mark:
	- [ ] single :white_check_mark:
	- [ ] multiple :white_check_mark:
- PMW3360
	- [ ] single
	- [ ] multiple
- PMW3389
	- [ ] single
	- [ ] multiple
	- [ ] Mixed with PMW3360 (shared common code)

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
FWIW, the Cirque i2c doesn't support multiple addresses, from what I can tell. 
Spec sheet for the 40mm version: https://www.dropbox.com/s/vkbm3jfm7xjwknw/GP-DS-170415%20TM040040%20SPI-I2C%20PINN%20Trackpad%20Spec.pdf?dl=0

**Comment by daskygit** [comment]
There's an unpopulated resistor footprint on the PCB labelled `ADR` which is supposedly meant to change the address from  0x2A to 0x2C.

**Comment by Antebios** [comment]
I have pulled this PR into my qmk fork and have not been able to get my dual analog joysticks working as a pointer to move the cursor.  I was able to get the code to compile and added more debugging statements, but no X/Y coordinate changes are happening when I move the joystick.  Have you been able to get multiple analog joysticks to move a cursor?  If so, what defines or rules do you set or required so I may compare to what I have set?

**Comment by daskygit** [comment]
I've just rebased so I expect stuff to be broken, I have a backup before the rebase here https://github.com/daskygit/qmk_firmware/tree/pr/multiple_sensors_old for the few people I know using the branch.

**Comment by daskygit** [comment]
@Antebios the code in this branch is fairly behind at the moment, I'd recommend using current master it should support an analog joystick as a mouse on both sides. You can ask for help in our discord. https://discord.gg/qmk

**Comment by Antebios** [comment]
> @Antebios the code in this branch is fairly behind at the moment, I'd recommend using current master it should support an analog joystick as a mouse on both sides. You can ask for help in our discord. https://discord.gg/qmk

The master branches looks like it does but it actually does not work properly.  I have run tests and debugging, and the second analog pointer is jittery and does not register the joystick movements all the time.  But when I connect to one side or the other exclusively then the pointer works perfectly, so it's not the connection nor signal, but code.  I gave up and am creating a second custom analog driver.

**Comment by daskygit** [comment]
I'm going to be splitting this up into stages as much as possible, so closing this PR.

**Pull request closed without merging**
