### PR TITLE
Allow encoder config from info.json

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Current plan is to munge <https://docs.qmk.fm/#/feature_encoders> into,
```json
    "encoder": {
        "enabled": true,
        "rotary": [
            { "pin_a": "B5", "pin_b": "A2", "resolution": 2 }
        ]
    }
```

Once format has been decided, DD docs will be updated.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by KarlK90 — APPROVED** [review]
How much work would it be to support `ENCODER_DIRECTION_FLIP` and `ENCODER_DEFAULT_POS` in this PR? Because that would cover all the encoder features besides callbacks and encoder maps. 

> Once format has been decided, DD docs will be updated.

As the format seems pretty much nailed down this can be added now?

Otherwise LGTM!

**Comment by zvecr** [comment]
`ENCODER_DIRECTION_FLIP` shouldnt exist at the keyboard level so wont have a ton of value (people should just swap a/b pins). `ENCODER_DEFAULT_POS` was only in 2 keymaps, though it could be added? Wasnt sure of its use case really to know how it factors in.

**Comment by drashna** [comment]
`ENCODER_DEFAULT_POS` is very much like the flip.  I think it should only be set in keymap config.

**Comment by jvbroek** [comment]
Necro-ing here a tiny bit, I saw that the docs for encoders don't mention anything about info.json.  Figured I'd draw attention to it.

**Pull request merged**
