### PR TITLE
[WIP] Kitten Paw refactor and Configurator update

### PR DESCRIPTION
**Pull request by noroadsleft**
- Renamed matrix `KEYMAP` to `LAYOUT`
- Added matrix `LAYOUT_fullsize_ansi`
- Keymaps refactored to use `#include QMK_KEYBOARD_H` and new matrix name
- Added `LAYOUTS = fullsize_ansi` to `rules.mk`
- Added `info.json` file
- White space fixes on readme file

I strongly suspect the Kitten Paw controller can support an ISO layout as well - the `LAYOUT` matrix is actually ANSI layout with an ISO-split Left Shift - but I haven't nailed down where the key that would be `KC_NUHS` on an ISO-layout board is in the matrix. I suspect it may just swap with ANSI Backslash, but I'm not 100% sure.

I have the same feeling about the Frosty Flake controller, whose matrix differs from the Kitten Paw's in only four places.

## To Do:

- [ ] Learn how to fix the `make` error

### CODE REVIEW

**Comment by noroadsleft** [comment]
[Travis error](https://travis-ci.org/qmk/qmk_firmware/builds/397660698#L922) seems to indicate it's trying to run a function that doesn't exist. What I don't know - assuming the previous statement is correct - is how to fix it.

**Comment by drashna** [comment]
Try adding references to the h file and see if that works? 

that or try adding: 
```c
__attribute__ ((weak))
void matrix_init_user(void) {
}

__attribute__ ((weak))
void matrix_scan_user(void) {
}
```
To the c file.

**Comment by noroadsleft** [comment]
Went for adding to the `.c` file. Was my first guess correct: the functions weren't defined?

**Comment by drashna** [comment]
Something missing in the references, I think. Not 100% sure.

**Comment by drashna** [comment]
Thanks

**Pull request merged**
