### PR TITLE
Fix layers from getting stuck on the Kyria default layout

### PR DESCRIPTION
**Pull request by splitkb**
## Description

The Lower layer kept getting stuck. This turned out to be an error on my side while developing the keymap. I've fixed the layout, and now layers aren't getting stuck anymore.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Is this a recent thing? One that looks like #8693 will fix.

**Comment by splitkb** [comment]
I recall seeing the behaviour about three to four weeks back, possibly longer, I hadn't taken the time to fix it yet.

**Comment by drashna** [comment]
> I recall seeing the behaviour about three to four weeks back, possibly longer, I hadn't taken the time to fix it yet.

The bug that introduced this (#4892, 5117dff) was committed march 22nd, so that sounds about right for the timing.

And looking at the keymap, these are LT keycodes.  So this should be fixed by updating the repo.

**Comment by drashna** [comment]
@splitkb Is it okay if we close this?  The issue this code change attempts to fix has been addressed already, and shouldn't be needed.

**Comment by splitkb** [comment]
@drashna If it's not needed then it can be closed, thank you for looking into it.

**Comment by zvecr** [comment]
```python
"shouldn't be needed" + "If it's not needed then it can be closed" == closed
```

**Pull request closed without merging**
