### PR TITLE
Asymmetric encoders, encoder tests.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

Previous asymmetric encoders PR was broken, and was rolled back shortly after merge.
In addition, encoders had tests, but weren't hooked up.

This PR attempts to address both situations -- enabling the existing test runs showed that encoder tests were broken, so I figured it was best to actually fix up encoder sizing assumptions at the same time.

Modifications

* Encoder tests have been re-enabled
* Encoder tests have been added to:
  * Initialisation now clears out the encoder state, fixing commented-out tests
  * Asymmetric tests have been added, with encoder counts: L=R, L<R, L>R, L=0, R=0.
* Encoder implementation has been fixed up such that asymmetric encoders are usable
  * `keymap.h` has new defines to allow shorthand for encoder counts, as well as per-side
  * Split common has been amended to ensure only the required number of encoders are transmitted
  * Encoder resolutions weren't correctly being set up in keyboards -- we had `ENCODER_RESOLUTIONS_RIGHT` already documented but there were places where keyboards were using `ENCODER_RESOLUTIONS` and `ENCODER_RESOLUTIONS_RIGHT` incorrectly together (or not at all).
  * `ENCODER_RESOLUTIONS` is used for both left and right if `ENCODER_RESOLUTIONS_RIGHT` is unspecified, matching `ENCODERS_PAD_A`.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by mtei** [comment]
FYI:

Last September, I experimented with encoder_read() by rewriting it as follows.

As a result, the estimated execution time of encoder_read() in normal time went from 18 microseconds to 2 microseconds.

```c
bool encoder_read(void) {
    bool changed = false;
    for (uint8_t i = 0; i < NUMBER_OF_ENCODERS; i++) {
        uint8_t new_status = (readPin(encoders_pad_a[i]) << 0) | (readPin(encoders_pad_b[i]) << 1);
        if ((encoder_state[i]&0x3) != new_status) {
            encoder_state[i] <<= 2;
            encoder_state[i] |= new_status;
            changed |= encoder_update(i, encoder_state[i]);
        }
    }
    return changed;
}
```

**Comment by tzarc** [comment]
@mtei great, thanks, added to the PR.

**Comment by drashna** [comment]
> FYI:
> 
> Last September, I experimented with encoder_read() by rewriting it as follows.
> 
> As a result, the estimated execution time of encoder_read() in normal time went from 18 microseconds to 2 microseconds.
> 
> ...

Can confirm that it doesn't seam to break anything, at least.

**Comment by mtei** [comment]
> Correction. There are some regressions here. It reintroduces the "trigger encoder on startup" issue, again.

You probably have to wait for the input signal to stabilize after the pull-up resistor is enabled.
```diff
diff --git a/quantum/encoder.c b/quantum/encoder.c
index 2f37bee6d9..83758a8cbd 100644
--- a/quantum/encoder.c
+++ b/quantum/encoder.c
@@ -121,7 +121,9 @@ void encoder_init(void) {
     for (uint8_t i = 0; i < thisCount; i++) {
         setPinInputHigh(encoders_pad_a[i]);
         setPinInputHigh(encoders_pad_b[i]);
-
+    }
+    wait_ms(1); // After the pull-up resistor is enabled, wait for the input signal to stabilize.
+    for (uint8_t i = 0; i < thisCount; i++) {
         encoder_state[i] = (readPin(encoders_pad_a[i]) << 0) | (readPin(encoders_pad_b[i]) << 1);
     }
 }
```

**Comment by tzarc** [comment]
@mtei great, will integrate #16372 into this PR once `develop` is merged and reopens.

**Comment by drashna** [comment]
Can confirm that fixes the issue I was seeing with this.

**Pull request merged**
