### PR TITLE
mitosis:datagrok layout and readme improvements

### PR DESCRIPTION
**Pull request by datagrok**
- Added a changelog, clearer layout images, and a heck of a lot more text to the readme.
- Experiment: no-modifier underscore on right shift key, by abusing Space Cadet.
- New combined numbers + keypad arrangement. No more worrying about Num Lock key.
- Move Function-keys to left board.
- Audio is working!
- Move Tab and Space to upper thumb row.
- Discard silly `#defines` for "Meta", "Super", and "Hyper".
- Move Backspace to Red+A. I shouldn't be using it much anyway.
- Distribute paired symbols symmetrically across boards like `\<{([ ])}>/`. (Opening symbols on left hand.)
- Change default back to target a 16Mhz/5v Pro Micro.

Thank you to @cari66ean, @drashna, and @codeincontext for discussion, tips and encouragement. Big thanks to @noroadsleft for helping to get the Mitosis (and many other keyboards!) working with the QMK configurator, which I have not yet attempted to understand :sweat_smile:

### CODE REVIEW

**Comment by drashna** [comment]
Thanks!

**Comment by cari66ean** [comment]
Hey! Nice work as always... I'm really enjoying those changes. I have only swapped the red and blue keys and shift and space to how it was in the previous version. Reason is that I use high profile keys on the upper thumb row and low profile keys on the bottom row. So in essence homing on either row feels perfectly natural but it's just much more awkward to reach down from the upper row than to reach up from the lower row. So that kind of makes me prefer the previous configuration with space and red keys on the lower row and shift and blue on the upper row. I guess you've come to prefer homing on the upper row?

**Comment by cari66ean** [comment]
Btw. another possibly useful thing I've come to use is TT() on the layer switches in combination with "#define TAPPING_TOGGLE 2"

**Comment by codeincontext** [comment]
This has inspired me to tweak my layout a little

I have a general mnemonic like so:
- Blue layer moves the number row down, so `asdf` is `1234` and `qwer` is `!@#$`
- Red layer moves the left and right mod columns in, so `q` is `esc`, `a` is tab, `p` is backspace, etc. The inner top row is `\ < { [ ] } > /` and I get vim-style `hjkl` for arrows

It covers most keys with muscle memory I'm already familiar with.

To navigate windows I use `cmd+tab` and `cmd+grave`. I don't want to use two mods for this so I put both of those combinations on the purple layer and gave the purple layer a thumb key. I needed some QMK code to keep `cmd` active until I leave the layer so I can switch more than one window at a time

**Comment by datagrok** [comment]
@cari66ean that's a great recommendation. I'll give it a try if I can't get my "Lock the current layer" key idea to work. (I haven't even had time to fix the bug you found, and thank you for catching that!)

@codeincontext what a great idea! Thanks for describing it!

**Comment by cari66ean** [comment]
Actually I‘m working on a second solution that involves pressing the mod buttons on both halves to toggle the layer but I‘m not satisfied with the purple layer yet, that‘s a bit more complicated.

**Pull request merged**
