### PR TITLE
add QMK DFU make option, bootloader replacement instructions

### PR DESCRIPTION
**Pull request by wanleg**
in wanleg readme: update flashing instructions, add bootloader replacement instructions (replace default Caterina with QMK DFU).

add make option for QMK DFU

### CODE REVIEW

**Comment by drashna** [comment]
the QMK DFU stuff can and probably should be added to your keymap files, rather than as a revision of the board

**Comment by wanleg** [comment]
Is it possible to add it to my own files and have it still function as a make option?
e.g. use `make gherkin/qmkdfu:default:dfu` on boards that have QMK DFU on them, but use `make gherkin:default:avrdude` on those that don't? Otherwise i have to have two versions running around all the time depending on the bootloader that's on the microcontroller...
Because of the low cost, i have a few of these boards AND have also been selling some to some people not yet super-comfortable with QMK, so i'm trying to make this convenient for everyone.

**Comment by drashna** [comment]
Yes,  though, it would be more like `make gherkin:mykeymap:dfu USE_DFU=yes`, and have it fully localized, rather than set to the entire keyboard. 

If you added something like this to your rules.mk file
```makefile
ifeq ($(strip $(USE_DFU)), yes)
    BOOTLOADER = qmk-dfu
endif
```
That should allow you to change which bootloader to use at compile time, and this would override what the keyboard sets 

And you could leave the settings in your config.h, as they're not used, except when compiling the bootloader. 

This is an extension of what I do for a number of my boards (I don't use the make variable, so ...)

Additionally, you could add a macro to handle the `make` output automatically.  And I have a sample of that in the userspace page: https://docs.qmk.fm/#/feature_userspace?id=consolidated-macros

But you'd want to use: 
```c
  case KC_MAKE:
    if (!record->event.pressed) {
      SEND_STRING("make " QMK_KEYBOARD ":" QMK_KEYMAP
#if  (defined(BOOTLOADER_DFU) || defined(BOOTLOADER_LUFA_DFU) || defined(BOOTLOADER_QMK_DFU))
       ":dfu USE_DFU=yes "
#elif defined(BOOTLOADER_HALFKAY)
      ":teensy "
#elif defined(BOOTLOADER_CATERINA)
       ":avrdude "
#endif
        SS_TAP(X_ENTER));
    }
    return false;
    break;
```

This would make flashing the correct version of the firmware a lot simpler, since you hit a key, and it types out everything for you.

**Comment by wanleg** [comment]
Perfect! Thank you for the detailed explanation. I learned a lot and made the recommended changes.

**Comment by drashna** [comment]
You're very welcome!   And I'm glad to have helped!   There is a lot of really cool stuff that you can do, once you know how.

And thanks!

**Pull request merged**
