### PR TITLE
Jarred's Plaid keymap

### PR DESCRIPTION
**Pull request by JarredSteenvoorden**
## Description

Adding plaid keymap based on userspace code

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
If you have a plaid and a planck, you may want to use the community layout feature, instead. 

Specifically, if you move the files into `/layouts/community/ortho_4x12/(name)`, it will be picked up by both boards.

**Comment by JarredSteenvoorden** [comment]
Thanks I wasn't aware of the common layout feature! I've also got a few 60% keymaps that I'll have to move to across later.

**Comment by drashna** [comment]
Well, then, I'm very glad that I mentioned them!  And yeah, it's a pretty awesome feature! 

Just make sure your boards support them first (the rules.mk for the keyboard or revision should have `LAYOUTS = ` in it, with the layouts that it supports)

**Comment by JarredSteenvoorden** [comment]
I have moved over to using the layouts/community/ortho_4x12/jarred folder, is this ok to merge now?

**Pull request merged**
