### PR TITLE
Move to organization folder

### PR DESCRIPTION
**Pull request by yfuku**
I've opened my own keyboard store.
I want to organize all the keyboards I've made so far into an organizational directory.

## Description
I have moved the directory and made the necessary fixes for that.
I also updated the readme.md.

wings42 is also my keyboard, so I'd like to move it with me, but I'll move it once the PR here is merged.
https://github.com/qmk/qmk_firmware/pull/13702

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Retargeted `develop` as any keyboard moves need to occur on the breaking changes cycle.

**Review by drashna — APPROVED** [review]

**Comment by tzarc** [comment]
#13702 has been merged -- did you want to add that board's move to this PR?

**Comment by yfuku** [comment]
@tzarc Yes.
Can I add the wings42 move to this PR?
Or should it be in another PR?

**Comment by tzarc** [comment]
You can add it to this PR, but you'll need to merge the current develop branch from upstream qmk/qmk_firmware first, so that the files in the old location exist.

**Comment by yfuku** [comment]
@tzarc Thank you!
I merged from the develop branch and did some additional pushes.

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Thanks!

**Pull request merged**
