### PR TITLE
Converted RGB matrix to use last_input_activity_elapsed().

### PR DESCRIPTION
**Pull request by pneisen**
## Description
After setting RGB_MATRIX_TIMEOUT to a value on my macro pad (winry315), the timeout worked as expected, but I was frustrated that turning my encoder knobs would not turn the LEDs back on and would not prevent them from turning off.

This solution was suggested by @drashna . It removes the special timer used by RGB matrix in favor of using the last_input_activity timer. Since this timer is reset by encoder activity, it fixes the issue I was seeing and probably fixes other inputs that didn't reset the old timer.

I did quite a bit of testing on my one device (winry315) that uses RGB matrix and has encoders. RGB_MATRIX_TIMEOUT worked as advertised and all inputs I could provide with this device reset the timer and would wake the RGB matrix. 

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

I think the encoder activity not waking the rgb matrix was technically a bug with the RGB_MATRIX_TIMEOUT feature, but I was unable to find an issue on it.

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
These changes should be applied to led matrix, as well (since the features are very similar, to keep parity between the two)

**Comment by pneisen** [comment]
I made the changes on the LED matrix side, but you'll have to let me know how you want to resolve the issues with splits as I am not familiar with how splits are handled.

**Comment by drashna** [comment]
> I made the changes on the LED matrix side, but you'll have to let me know how you want to resolve the issues with splits as I am not familiar with how splits are handled.

Given https://github.com/qmk/qmk_firmware/pull/21703, I'd say that updating the post_config.h file for rgb/led matrix would be a good idea.

**Comment by pneisen** [comment]
> Given #21703, I'd say that updating the post_config.h file for rgb/led matrix would be a good idea.

I read over that pull request, but I am not sure what you mean by updating the post_configs. Are you saying that we probably need to define RGB_MATRIX_KEYPRESSES if RGB_MATRIX_TIMEOUT > 0? I'm not quite sure why we would need to do that since RGB_MATRIX_KEYPRESSES looks to be a different thing from activity. 

I'm probably just missing what you are hinting at.

**Comment by zvecr** [comment]
> Given https://github.com/qmk/qmk_firmware/pull/21703, I'd say that updating the post_config.h file for rgb/led matrix would be a good idea.

That is solving a completely different sort of issue. The fact that what is mostly an optimisation, has bled to over 800 references in keyboards. As this is coupling between multiple components, it doesnt infer the same solution.

For whats best in this scenario, the suggested might be best but its not something ive really looked into.

**Comment by pneisen** [comment]
> If you have `RGB_MATRIX` enabled but not `RGB_MATRIX_KEYREACTIVE`, `deltaTime` goes unused and compilation fails.

Good catch! I fixed this issue in both rgb_matrix and led_matrix. I also looked around for similar issues I might have caused and didn't find any.

**Review by tzarc — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Pull request merged**
