### PR TITLE
Add bootloader size

### PR DESCRIPTION
**Pull request by datafx**
Bootloader size needs to be 6144 to allow QMK to jump to the correct location with bootmagic

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/qmk/qmk_firmware/issues/13283

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Already done in https://github.com/qmk/qmk_firmware/pull/13724, though it's targeting develop.

**Comment by drashna** [comment]
> Already done in #13724, though it's targeting develop.

I'd be fine with this, but given the closeness to the end of the breaking changes cycle...

**Comment by fauxpark** [comment]
We've got a whole month left before develop merges to master, we may as well move the other bootloader size fixes into this PR.

**Comment by datafx** [comment]
> We've got a whole month left before develop merges to master, we may as well move the other bootloader size fixes into this PR.

Looks like it was only one other board so I've included that one too.

**Review by fauxpark — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Pull request merged**
