### PR TITLE
DZ60: Add LAYOUT_directional_625_space

### PR DESCRIPTION
**Pull request by noroadsleft**
This should help move @mesnik (#3115) along.

Adds a `LAYOUT_directional_625_space` matrix to `dz60.h` and a corresponding layout in `info.json` for the Configurator.

cc @drashna

### CODE REVIEW

**Comment by drashna** [comment]
Awesome, thanks!

**Comment by mesnik** [comment]
Very cool!!! Thanks!!!!

**Comment by noroadsleft** [comment]
No problem, @mesnik.

You should be able to generate your keymap [here](https://config.qmk.fm/#/dz60/LAYOUT_directional_625_space) now.

**Comment by mesnik** [comment]
I saw it and as my keycaps showed up today, I already soldered the switches in and now I am playing with my custom keymap!!  Thanks so much again and have a great weekend!

**Pull request merged**
