### PR TITLE
Fixes for failures during 'make lets_split'

### PR DESCRIPTION
**Pull request by zvecr**
Before i make any changes to the lets_split board, i wanted to make sure the whole folder was building. The failures are as follows

- OLED_sample
  -   firmware too large - disabled mouse support to trim size as it was not used
- pyrol
  -   bad case on the `#include`
- bakingpy
  - Instead of adding a lets_split case to a wall of `else ifeq` I've refactored in the style of LAYOUTS_HAS_RGB
- talljoe
  - ~~the community layout talljoe, is still failing as mentioned in #4487.~~
  - #4487 was merged so ive added the required conditional build fixes

### CODE REVIEW

**Comment by drashna** [comment]
Honestly, we're generally not a fan of editing other people's keymaps.  It's impolite usually. 

Also, for Travis related issues, we will ignore a keymap that causes issues, as long as the default keymap compiles fine.  

Flagging somebody about the issue is okay, though.

**Comment by zvecr** [comment]
From my background, failing code is failing code.

The reason i was making this change was I planned to swap the lets split over to using the shared split implementation. (already testing it at https://github.com/zvecr/qmk_firmware/tree/feature/ortho_4x12-keymap). However broken code makes these changes extremely difficult. You can no longer rely on the state of the code base being good, and investigate anything that is broken by your changes.

**Comment by zvecr** [comment]
I mean no disrespect with my previous comment, and i understand about the case for other peoples keyboards.

However techical debt is a term that plagues all software projects. The state of the repo has changed over time, use of `#pragma once`, deprecated tmk macros, makefile changes, ect. A new contributor has to battle against these unwritten rules when they copy-paste something as their basis for change.

Surely we should spend effort to crush technical debt, and make the code base reflect the current standards?

Welcoming everyone goes both ways, so for now i think it better to close this PR and move on.

**Comment by drashna** [comment]
Well, if it helps, we're discussing this exact issue internally right now.  So closing this may be a bit premature.

And more specifically, we need to figure out an official policy for how to handle keymaps in this sort of case.   That way, everything is much clearer going forward.

**Comment by noroadsleft** [comment]
Since it's relevant here:

I was actually thinking about doing a PR that *only* removes the

```makefile
ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
```

blocks, but does so from the whole repo.

I kind of agree with @zvecr's point about technical debt. Broken keymaps bother me. But I understand your point, @drashna, about respecting other people's property. Lately I've been trying to make as few changes as possible to other people's keymaps, and only if it's relevant to the goal of whatever my PR is.

One exception I have to that guideline is keymaps that are unmaintained, because what I've noticed is a lot of copy-paste contributions in keymaps, where a prospective QMK user finds a keymap they like, copies and edits it, and then submits a PR and gets hit with a bunch of review comments because the keymap they copied hadn't been updated in a year. I think that raises the "barrier to entry" a bit and is something I'd much prefer to avoid.

In the instances of unmaintained keymaps, I try to modernize them to current QMK standards as best as I am capable. Some things like Tap Dance I mostly leave alone, as I have no experience with some QMK features.

**Pull request closed without merging**
