### PR TITLE
Fix zero condition of reactive runners that will suspend RGB animation

### PR DESCRIPTION
**Pull request by filterpaper**
## Description

If user keyboard's RGB speed setting (`rgb_matrix_config.speed`) is at zero, key press animation will remain static. Reactive runners will keep one key or entire keyboard lit.

This change avoid both conditions with a minimum value to the `tick` variable. 

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by jhanschoo** [comment]
I don't really agree that this should be the behavior. Note that it isn't overflowing; the ticks are just being multiplied by zero. For effects that light up the keyboard at the instantaneous moment of a keypress, this will indeed result in lighting up the entire keyboard.

That is, at speed=0, only the zeroth frame of the reactive animation will play (a little more complicated for mutikey effects, but essentially the same), and this persists for around 65 ms or max keypresses remembered is reached. If this is not the behavior of an animation, the animation is what should be fixed.

**Comment by filterpaper** [comment]
> I don't really agree that this should be the behavior. Note that it isn't overflowing; the ticks are just being multiplied by zero. For effects that light up the keyboard at the instantaneous moment of a keypress, this will indeed result in lighting up the entire keyboard.

I do see your point, but I don't believe that's the _spirit_ of the reactive light intention. That said, @XScorpion2 is the original coder—will let him/her comment if "zero" RGB reactive speed is meant to light up the entire board.

**Comment by jhanschoo** [comment]
I think that with respect to spirit, documentation on the speed variable might also serve well: mention that speed 0 means the animation will literally freeze at the zeroth frame, 1 is the slowest speed, and 255 is fastest.

If this PR is accepted, there should also be documentation on why 1 is added to the divisor in this particular runner and not the other runners.

Note that "lighting up the board" is a consequence of this particular runner: for instance, for `effect_runner_i.h`, or `effect_runner_reactive_splash.h`, there is value for zero speed, for the result is the zeroth frame effect is applied to the last N keypresses, and a solid effect can be simulated (e.g. flickering firefly effect whose maximum value decays with time, speed used to control rate of decay)

**Comment by XScorpion2** [comment]
So, this may sound like a stupid reason as to why I allowed 0:
All the step value defines default to 16 currently, which ensures that when you reach max, you hit 255 exactly, and reach min, you hit 0 exactly. This way when you hit the extents and reverse, you always can get to the same value as before, without having to reach the other extent to reset your scale. When you limit the min to 1, this causes a shift of +1 to occur once you hit that, then increase the value again. 

So your value changes would look something like:
32 -> 16 -> 1 -> 17 -> 33

Instead of today where it looks like this:
32 -> 16 -> 0 -> 16 -> 32

**Comment by filterpaper** [comment]
Thanks for the input. In this case, setting the minimum value at `RGB_MATRIX_SPD_STEP` will cover both cases. All bets are off for users that avoid powers of two.

**Comment by filterpaper** [comment]
> All the step value defines default to 16 currently, which ensures that when you reach max, you hit 255 exactly, and reach min, you hit 0 exactly.

@XScorpion2 I did a quick console test to verify the values of `rgb_matrix_config.speed`. It will max at 255. There after default `RGB_SPD` will decrease its value by 16, counting down in this manner:
` 255 - 239 - 223 ... 31 - 15 - 0 - 16 - 32 ...`

They don't seem to align at powers of 2 when decrementing from max 255.

**Comment by XScorpion2** [comment]
> 
> 
> > All the step value defines default to 16 currently, which ensures that when you reach max, you hit 255 exactly, and reach min, you hit 0 exactly.
> 
> @XScorpion2 I did a quick console test to verify the values of `rgb_matrix_config.speed`. It will max at 255. There after default `RGB_SPD` will decrease its value by 16, counting down in this manner:
> ` 255 - 239 - 223 ... 31 - 15 - 0 - 16 - 32 ...`
> 
> They don't seem to align at powers of 2 when decrementing from max 255.

I may be off on my memory, but that was the original intent at any rate when I implemented it. Ah well, not really all that important as it's more about what people would prefer either way.

**Comment by jhanschoo** [comment]
I think I now agree with @filterpaper to add one, and it should be implemented on all the runners. Animation writers that want the weird behavior at speed=0 should just subtract 1 themselves.

**Review by drashna — APPROVED** [review]

**Comment by tzarc** [comment]
Would it not be better to have these as `max(speed, 1)`?

**Pull request merged**
