### PR TITLE
WB32F3G71 config migration with removal of unnecessary items.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

WB32F3G71 support had unnecessary config formats which would prevent ChibiOS upgrade.
@wb-Joy would be nice if you could confirm that these work.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by wb-Joy — COMMENTED** [review]
Both files can be deleted，The chconf configuration is default.

**Comment by tzarc** [comment]
> Both files can be deleted，The chconf configuration is default.

Thanks for confirmation.

**Review by wb-Joy — APPROVED** [review]

**Comment by wb-Joy** [comment]
I made a mistake, The value of CH_CFG_ST_TIMEDELTA must be 0.

**Comment by tzarc** [comment]
Please make a new bugfix PR.

**Pull request merged**
