### PR TITLE
Relocate pca9555 driver to core

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Remove duplication of `pca9555` code.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
## Questions

1. Better name than `drivers/gpio` for the whole port expander multiplier terminology?
1. Should this be a "feature" with something like `GIPO_DRIVER = pca9555`?

**Comment by noroadsleft** [comment]
>     1. Better name than `drivers/gpio` for the whole port expander multiplier terminology?

I think `drivers/gpio` is fine, though someone else may have a different (better) idea.

>     2. Should this be a "feature" with something like `GIPO_DRIVER = pca9555`?

IMO yes, but only if the rule spells `GPIO` correctly. :smile:

**Comment by drashna** [comment]
As for feature, yes, definitely.  The ergodox ez and it's clones would be targets for this sort of change, too.  

And that would make it easier to generalize the code for it, too.

**Comment by zvecr** [comment]
While it would be simple to add something to `common_features.mk` to generalise the rules.mk stuff that is used in this scenario, its quite a bit more work to flesh out the full solution. Work items include creating a generic API to cover all port expanders, caching pin state, and advertising a `readpin` `setPinInputHigh` style functionality, as well as the added docs requirements.

Given that another kimera core board might be ported soon, and it needs finer port control, I think some of the above will eventually be required.

So i guess my question changes slightly
1. Should this be merged as is, and a 2nd round later to add the above?
2. Should i add the bare minimum to get this scenario working?
    > GIPO_DRIVER = pca9555
3. Is there a hard requirement to provide the full feature up front?

Due to other commitments right now, and the increased amount of work, if option 3 is the only way forward then I might have to park this till a later date.

**Comment by drashna** [comment]
I think that merging as is should be fine.  At the very least, it should allow you to easily call the file, and maintain a single copy of it.   Over time, it can be improved.

**Pull request merged**
