### PR TITLE
Melody96 refactor

### PR DESCRIPTION
**Pull request by fauxpark**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by mjparme** [comment]
@fauxpark Every since this refactor of the melody96 was merged the Enter key is the backslash key and the backslash key is the enter key when using the default keymap. I don't really understand why either because the layouts in melody96.h match the layouts from an older version of melody96.h (QMK Firmware 0.16.8) where using the default keymap doesn't result in the enter and backslash being mixed up.

I can fix it by swapping k93 and k84 in the LAYOUT_all but I can't figure out why that would be necessary. Because it used to work fine. Do you have any insight why enter and backslash are mixed up in the default keymap after your refactor?

**Comment by sigprof** [comment]
@mjparme Do you have a hotswap version of the PCB? AFAIK one weirdness with Melody96 is that the hotswap and soldered versions of the PCB are not 100% compatible — on the hotswap PCB the matrix positions for Enter and backslash are swapped with respect to the same key positions on the soldered PCB. The old code had the `LAYOUT_hotswap` macro specifically for the ANSI hotswap PCB, which accounted for this difference; however, during the refactoring that layout macro was dropped.

I think that the proper way to fix this would be to split this keyboard into two separate versions — maybe `ymdk/melody96/soldered` and `ymdk/melody96/hotswap`, and make sure that each of those versions has accurate layout macros. But doing that requires having the actual PCBs for testing. The fact that the Melody96 hotswap PCB also has multiple layout options (configurable by choosing which locations for the hotswap sockets to populate) also complicates things. Also apparently the hotswap PCB now has two different revisions (“Hotswap 96 V1” and “Hotswap 96 V2”); not sure whether they have any important differences except switch orientations.

**Comment by mjparme** [comment]
@sigprof I _do not_ have the hotswap version of the PCB. I have two of these  https://www.aliexpr_ess.com/item/2251832660403665.html. One I bought in Feb 2021 and the other I bought in Nov 2021. Both are experiencing the swapped backslash and enter key when using the `default` keymap (which uses the `LAYOUT_all` macro) from the master branch.

If I instead use an older branch that I have that is at commit 675ce769723109c1526e25d1c08c6e5282fd088d (it reports itself as `QMK Firmware 0.16.8` during compilation) the backslash and enter keys are not swapped when using the default keymap. Doing a diff between LAYOUT_all in master branch and my older branch shows no differences in the macro. 

It is very puzzling to say the least.

I have created a `LAYOUT_backslash_enter_swapped` macro where I have swapped k93 and k84 and this works but for the life of me I can't figure out why this was necessary.

**Comment by noroadsleft** [comment]
@mjparme I've had your report kicking around in the back of my mind, intending to investigate your report. I finally went back to investigate this by checking out the commit previous to this PR, and doing my own refactor from that.

I'm fairly confident that this PR switched the Backslash and Enter locations when it should not have. My reasoning for this, in addition to the refactor I did locally, is the fact that the commit that brought this PR's changes into QMK's mainline has [position `k93` above position `k84`](https://github.com/qmk/qmk_firmware/blob/aab2ac22c5217afcbbbaff8b5444b02765f6de66/keyboards/melody96/melody96.h#L59-L79), but the previous commit has the [corresponding position `K084` above `K093`](https://github.com/qmk/qmk_firmware/blob/61ba8efa3e358fbf4495c76b9d7c33aa2ec1259e/keyboards/melody96/melody96.h#L5-L25).

I also was able to look up a Discord exchange with a user who had this board (I don't know if they still do). Their keymap is in the repo (the `konstantin` keymap), and in the Discord exchange they confirmed that their board was built using an ANSI Enter. I cross-referenced their keymap with the layout macro QMK had at the time, and confirmed that macro had position `K084` above `K093` as well.

My thoughts are:

- The original Soldered PCBs have position `K84` as Backslash and `K93` as Enter.
- Hotswap PCBs have this reversed: `K93` as Backslash and `K84` as Enter. This has been the case since Hotswap PCB support was added in #5985.

I also just checked the VIA support. It seems the keys in question have had their positions switched *three times* since support was initially added. I suspect the users in question have different revisions of the board, and that none of them talked to each other. I also note that the VIA data only supports seems to support the Hotswap PCB.

It'd be a help if @NoFunDon and @vinorodrigues could specify which versions of the Melody96 they own(ed).

**Comment by NoFunDon** [comment]
I have the hotswap version of the Melody96

**Comment by vinorodrigues** [comment]
original solder version for me

**Comment by noroadsleft** [comment]
Thanks for the replies.

At the very least, I think on the VIA side this would require two different JSON data files, because making the data valid for one (either Hotswap or Soldered) seems to make the data *invalid* for the other. The QMK codebase would also need multiple revisions to differentiate the Vendor/Product ID pairings, though technically it should have that anyway –  the QMK guideline is "different PCBs should be added as different keyboards," though that wasn't well-enforced in the early days.

@NoFunDon, do you happen to have a product link for the PCB/keyboard you bought? I searched `melody 96` on AliExpress (knowing YMDK has an active storefront there) and found two different hotswap PCBs: A "Melody 96 Pro" with per-key RGB, and a "Hotswap Melody 96 Kit 1" with a different PCB that's more like a soldered PCB with hotswap sockets pre-installed (buyer is offered the choices of ANSI or ISO, and 3x 1u or 2x 1.5u mods on the right side).

Additionally, there are at least two versions of the Soldered PCB: one with a USB Micro B connector, and one with a Type C. Fortunately, I have no reason to believe there's any difference in them besides the connector.

@mjparme, does your Melody96 PCB have a Type C connector?

**Comment by vinorodrigues** [comment]
Well ... if you skip Ali and go direct to ymdkey dot com you get 4 "versions":
* YMD-96 Soldering PCB
* YMD-96 Hotswap QMK Underglow PCB (V1 South Facing)
* YMD-96 Hotswap QMK Underglow PCB (V2 North Facing)
* YMD-96 V3 RGB Hotswap PCB
*( FYI: @noroadsleft  )*

**Comment by mjparme** [comment]
@noroadsleft my PCBs have a USB-C connector

**Comment by noroadsleft** [comment]
Okay, here's some firmware for testing. Both of these should have proper Enter key placement (I hope!).

@mjparme and @vinorodrigues,

If you're willing, please flash the appropriate firmware file to your Melody96s and sideload the VIA JSON files (which are V2 spec; I don't know V3 spec yet), and let me know if they work as they should. Both firmware files are VIA enabled, and the top right key on the default layer is `QK_BOOT` (aka `RESET`; jump to bootloader).

| Firmware | VIA JSON |
| :------- | :------- |
| [ymdk_melody96_hotswap_nrl_dev.hex.txt](https://github.com/qmk/qmk_firmware/files/9944580/ymdk_melody96_hotswap_nrl_dev.hex.txt) | [melody96_hotswap.json.txt](https://github.com/qmk/qmk_firmware/files/9944588/melody96_hotswap.json.txt) |
| [ymdk_melody96_soldered_nrl_dev.hex.txt](https://github.com/qmk/qmk_firmware/files/9944581/ymdk_melody96_soldered_nrl_dev.hex.txt) | [melody96_soldered.json.txt](https://github.com/qmk/qmk_firmware/files/9944589/melody96_soldered.json.txt) |

Also @mjparme,

I asked you the wrong question previously, forgetting at the time that your board is Hotswap. A more appropriate question is: does your PCB have South-facing LEDs footprints, or North-facing? I'm wondering how confident to be about the V1 and V2 Hotswap boards having the same matrices.

**Comment by vinorodrigues** [comment]
ok tested it
- **good news**: andter and \| are correctly oriented
- **bad news**: F5 somehow comes up as a Left-Win, and the whole num-pad is unresponsive.

**Comment by mjparme** [comment]
> Also @mjparme,
> 
> I asked you the wrong question previously, forgetting at the time that your board is Hotswap. A more appropriate question is: does your PCB have South-facing LEDs footprints, or North-facing? I'm wondering how confident to be about the V1 and V2 Hotswap boards having the same matrices.

My PCB is _not_ hotswap. It is soldered.

**Comment by noroadsleft** [comment]
@mjparme, My apologies. I got your board mixed up with NoFunDon's. Disregard the testing firmware and VIA instructions – vinorodrigues was able to verify the data I had for the Soldered PCBs.

@NoFunDon, does your PCB have South-facing LEDs footprints, or North-facing? If you're willing, please download the testing firmware and VIA JSON [I posted here](https://github.com/qmk/qmk_firmware/pull/16455#issuecomment-1304620149) and let me know:

1. if your Enter and Backslash keys behave as they should
2. if the VIA data is accurate for your board.

**Pull request merged**
