### PR TITLE
Documentation: Newbs Flashing: Hightlight that sudo may be needed

### PR DESCRIPTION
**Pull request by pnomolos**
## Description
Highlight the note about sudo so it's more prominent, especially because this is a newbs guide.  Also added "dfu-programmer: no device present" into the doc text so that anyone searching for that particular error can hopefully find the page.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

### CODE REVIEW

**Comment by drashna** [comment]
Actually, you may 2ant to use ?> or !> at the beginning of the line.

As is, this may highlight in GitHub, but may not highlight on the docs site. The above will render correctly.

**Comment by pnomolos** [comment]
@drashna Thanks, I think I found an old commit and used that as the basis for adding the warning.

**Comment by drashna** [comment]
Well, I know that we changed the doc site a few times

**Comment by mechmerlin** [comment]
The need for this commonly pops up on linux systems. I forget why though. What systems have you seen this on.

**Comment by pnomolos** [comment]
@mechmerlin I'm on Ubuntu 19.04 myself.  I presume it's because `dfu-programmer` doesn't have write access to the device unless you've got root access to the system?

**Comment by drashna** [comment]
Correct. Or you've set the udev rules to allow the user access. Which is much safer than running as sudo

**Comment by pnomolos** [comment]
@drashna I updated the file to indicate that you should read the FAQ rather than just recommending sudo :)

**Pull request merged**
