### PR TITLE
Hp69 - Update led logic

### PR DESCRIPTION
**Pull request by AnanyaKirti**
## Types of Changes

- [ ] Core
- [*] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [*] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [*] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by AnanyaKirti** [comment]
had inverted the caps lock logic, corrected it now

**Comment by zvecr** [comment]
You have conflicts that need to be resolved, its also worth cleaning up the history so the file diff does not include all your previous changes.

**Comment by AnanyaKirti** [comment]
hey! The conflict is the error I'm trying to connect, the LED logic got inverted. So this PR is to correct the LED logic, thanks!

**Review by zvecr — APPROVED** [review]

**Comment by zvecr** [comment]
Its not that i misunderstood the PRs intention, its that you didn't provide PR content that we could action.
Given the intentions are simple enough, i've gone in and fixed the issues so that this can potentially be merged.

As a recommendation, I would adopt the workflow within <https://docs.qmk.fm/#/newbs_git_best_practices> and refrain from reusing branches.

**Review by fauxpark — APPROVED** [review]

**Comment by fauxpark** [comment]
Thanks!

**Pull request merged**
