### PR TITLE
Convert V-USB usbdrv to a submodule

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

✨

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Tested and working on plaid-pad 👍 🎉

**Comment by yiancar** [comment]
Tested and working

**Comment by drashna** [comment]
Not sure if it should be done here, but ... I think that we need a check for the number of endpoints, and error out if there are too many. Much the way that AVR and chibiOS does, in the `usb_descriptor.h` file.   Though I think this conversation (or part of it) has been brought up elsewhere.

**Comment by fauxpark** [comment]
@noroadsleft just FYI this will require https://github.com/qmk/qmk_compiler/pull/62 to be merged simultaneously, otherwise Configurator will probably break when building V-USB boards.

Will add a changelog in a bit.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
