### PR TITLE
Zlant refactor and Configurator support

### PR DESCRIPTION
**Pull request by noroadsleft**
- Matrix/keymap refactor
  - White space and readability updates
- Configurator support
  - Added `info.json` file.
- Readme update
  - Markdown formatting

### CODE REVIEW

**Comment by drashna** [comment]
Didn't want to use `LAYOUT_ortho_4x12`? 😄

**Comment by drashna** [comment]
lol, that's mee too.  Though, I'm using a desktop with Windows 10, not a laptop with Windows 7 

@jackhumbert @skullydazed @yanfali 

Here's a question for you.  The Zlant uses a 4x12 grid for the keys, but each row is offset by 0.5U, so it's not really ortho.  

However, the layout fits the ortho_4x12 layout perfectly.    

So, should we support the ortho layout, or just leave it as "LAYOUT"?

**Comment by noroadsleft** [comment]
LOL @drashna, you would ask this as I'm making the changes to support ortho_4x12 keymaps.

Also, I'm not sure what happens in the Configurator API with these changes. I remember the API doesn't like macro aliases, but I can't remember if the `info.json` file needs to use the aliased name, or the direct name.

The rows, incidentally, are offset by 0.25u, not 0.5u.

----

Need to work out a matrix for planck_mit; forgot about that.

**Comment by yanfali** [comment]
I think this is a special case of Ortho. All the keys are uniform. Their just offset. We still call the iris Ortho and it's vertically offset.

**Comment by noroadsleft** [comment]
I hate userspaces. :(

**Comment by drashna** [comment]
You mean layouts. 

https://github.com/qmk/qmk_firmware/blob/master/layouts/community/ortho_4x12/wanleg/rules.mk

**Comment by noroadsleft** [comment]
I hate *everything*. :(

**Comment by noroadsleft** [comment]
What happens with the commits in this PR if I run `git rebase upstream/master` and `git push origin cf/zlant --force` ? qmk:master and this branch have diverged; the branch's initial commit predates the commit that added wanleg's files, so wanleg's files don't actually exist in my fork.

I also have no idea how to solve the errors on bakingpy's keymap.

**Comment by drashna** [comment]
bakingpy's keymap is having issues because BACKLIGHT is enabled. Wanleg's keymap is having issues because Swap Hands is enabled

**Pull request merged**
