### PR TITLE
Translated CODE_OF_CONDUCT.md in Hindi

### PR DESCRIPTION
**Pull request by kichloo**

### CODE REVIEW

**Comment by kichloo** [comment]
I translated it in Hindi.

**Comment by fauxpark** [comment]
This just replaces the entire contents of the original CoC with the Hindi version...

**Comment by jackhumbert** [comment]
Please try to keep the formatting of the original file as well :)

**Comment by fauxpark** [comment]
@zvecr that could get out of hand fast, I think the CoCs could go in their own repo like https://github.com/docker/code-of-conduct, or even qmk/qmk, and each repo link to it in a single `CODE_OF_CONDUCT.md`.

**Comment by zvecr** [comment]
Thank you for your contribution!
This pull request has been automatically closed because it has not had activity in the last 30 days. Please feel free to give a status update now, ping for review, or re-open when it's ready.

**Pull request closed without merging**
