### PR TITLE
Handwired Teensi2.0 clone

### PR DESCRIPTION
**Pull request by binaryplease**
Hi, 
I have created a handwired planck clone with a teensy 2.0 and was told on gitter it would be okay to submit a pull request. I would like to include my keyboard under the handwired ones.

Thanks for the good work!

### CODE REVIEW

**Comment by fredizzimo** [comment]
As commented yesterday, the alternative would be to just add a keymap under the normal Planck keyboard, and make a few adjustments to the keymap specific makefile. The `KEYMAP` macro here could be  replaced by `PLANCK_MIT`. That way there would be no need for a custom keyboard. 

@jackhumbert can tell which option he prefers.

**Comment by binaryplease** [comment]
@fredizzimo You are probably right. The layout is actually copied from the official planck one mostly. I think your alternative is better, but don't know what changes have to be made to the makefile. If you want, I can create a pull request with the additional keymap and continue working from there

**Comment by fredizzimo** [comment]
@ binaryplease, from what I can see the only thing that need to be changed in the `rules.mk` is the bootloader size, and the disabling of the LEDs and AUDIO. 

I can also see that the pins are slightly different, those could be handled by `#undef` and redefining in your keymap config.h file. But perhaps these changes are too big, so maybe it's better to keep the keyboard separate after all. Or what do you think @jackhumbert?

**Comment by jackhumbert** [comment]
@binaryplease you should be able to override those settings in your `config.h` and `Makefile` in your keymap folder. I would like to have a notation for keymaps that make hardware changes like that, so people don't accidentally flash them. Maybe prefix your keymap's name with `handwired_`?

**Comment by fredizzimo** [comment]
@binaryplease, I forgot to add, instead of `KEYMAP`, you can use `PLANCK_MIT`, which should have the same effect.

**Pull request closed without merging**
