### PR TITLE
[keyboard] rename id80 v1 to v2 to clear up confusion

### PR DESCRIPTION
**Pull request by vinorodrigues**
## Description

IDOBAO support has received a few support calls with developers confused with the "v1" name used in the folder structure introduced in #15992.

The code in the `v1` folder is perfectly suited to the current `v2` boards and correct naming will prevent developers from inadvertently using `v3` codebase in their `v2` boards.

This PR seeks to rename the "v1" folder to "v2" *(to eliminate confusion)*, and then add a `readme.md` and `rules.mk` file to the "v1" *(ensuring backward compatibility)*.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Not an issue - more a follow on from #15992

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
> @vinorodrigues marked this pull request as ready for review 4 hours ago

Seems there are conflicts.

**Comment by vinorodrigues** [comment]
> Seems there are conflicts.

Yes, sorry ... I wrote this off the `master` and was asked by @sigprof to PR to `develop`.  The conflict is in @zvecr 's PR #17037 wherein the `default/keymap.c` and `via/keymap.c` files had `RESET` changed to `QK_BOOT`.

I did not rebase the code *(or rather do not know how to)*, but the change is in there.  Just don't have privilege to auto-resolve.

*(I will try learning how to rebase...)*

**Comment by vinorodrigues** [comment]
@$%^#@^$%##$^%^!   I broke it!  Will redo in another PR --- starting with the correct base.

**Comment by vinorodrigues** [comment]
redone as #17137

**Pull request closed without merging**
