### PR TITLE
Add the RMI-KB Mini AT boards

### PR DESCRIPTION
**Pull request by ramonimbao**
## Description

Adds the Mini AT firmware files:
- Rev 1 using RP2040
- Rev 2 using STM32G431

Both Rev 1 and Rev 2 PCBs support multiple layouts but each firmware supports only select layouts:
- Base 
- 40s

The layout support for both revisions is identical.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by ramonimbao** [comment]
> If its a single PCB, then it should not be split into a "base" and "forties" subrevision.

It felt like it's way easier to manage all the different layouts in the PCB with separate firmwares. Though I can merge them all the one if that's better.

**Comment by ramonimbao** [comment]
image

This is all the layouts supported. I'm not sure how you'd be able to switch between the base and forties while also allowing the other layout sub-options in VIA.

**Comment by zvecr** [comment]
> It felt like it's way easier to manage all the different layouts in the PCB with separate firmwares

Unfortunately it's not really the way things are managed for this project. It adds additional maintenance costs due to both the duplication, and redundant build targets, which in turn increases CI build times and increases refactoring efforts. 

> This is all the layouts supported. I'm not sure how you'd be able to switch between the base and forties while also allowing the other layout sub-options in VIA.

Though i'm sure it can be solved with "layout options" covering most of the switches, limitations of third party tools should not require QMK to accept a sub-optimal solution.

**Comment by ramonimbao** [comment]
Okay, understood. I'll merge the base and forties

**Pull request closed without merging**
