### PR TITLE
add valor_frl_tkl info.json

### PR DESCRIPTION
**Pull request by Xelus22**
## Description

Add info.json for configurator as asked by @fauxpark 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fix  configurator with valor_frl_tkl
* #12222 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]
image

**Comment by noroadsleft** [comment]
@Xelus22 Does this board actually have the macro keys on the left? The `info.json` object should have as many keys as are assigned by `keymap.c`/expected by `valor_frl_tkl.h`, but this isn't the case:

image

**Comment by Xelus22** [comment]
> 
> 
> @Xelus22 Does this board actually have the macro keys on the left? The `info.json` object should have as many keys as are assigned by `keymap.c`/expected by `valor_frl_tkl.h`, but this isn't the case:
> 
> image

Yep you're right it doesnt, that is my bad. haha

**Comment by Xelus22** [comment]
@noroadsleft  should be  ok now :D

**Review by fauxpark — APPROVED** [review]

**Review by noroadsleft — APPROVED** [review]
image

:+1:

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
