### PR TITLE
Don't clear keys on layer change unless STRICT_LAYER_RELEASE is enabled

### LINKED ISSUE #18300: [Feature Request] Add option similar to STRICT_LAYER_RELEASE but for mouse keys.
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

[Mouse buttons are cleared on layer change.](https://github.com/qmk/qmk_firmware/blob/master/quantum/action.c#L1078-L1081) However, holding down buttons can cause strain for people with carpal tunnel. This is difficult when applications require a mouse button be held often.

Could you please add an option similar to `#define STRICT_LAYER_RELEASE` but for mouse keys so that the mouse button won't be cleared on layer change?

### PR DESCRIPTION
**Pull request by drashna**
## Description

Previous behavior clears mousekeys on layer change, which is not expected/proper behavior. 

Not sure if extrakeys should be moved too?

## Types of Changes

- [x] Core
- [x] Bugfix
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #18300

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
`clear_keyboard_but_mods_and_keys` seems to imply it should clear everything *but* the normal keyboard report, hence why extrakeys and programmable buttons are in there too. So I think this functions must be being used incorrectly.

**Comment by drashna** [comment]
Yeah, the naming here is ... messy. 

And to be honest, I'm not sure that clearing the extrakeys here is the right behavior, either.

**Comment by sigprof** [comment]
Apparently `clear_keyboard_but_mods_and_keys()` is called only in 3 places:
- `clear_keyboard_but_mods()`, which is just a more extensive clear (and that looks like the correct place to clear mousekeys, extrakeys and programmable buttons);
- `default_layer_state_set()`;
- `layer_state_set()`.

The real question is why we even need to perform that clear on layer state changes if `STRICT_LAYER_RELEASE` is not defined?  Was that a workaround for some cases when the source layer cache did not work properly?

If we move clearing of “unusual” keys to `clear_keyboard_but_mods()`, then the only code remaining in `clear_keyboard_but_mods_and_keys()` would be
```c
    clear_weak_mods();
    send_keyboard_report();
```
Normally weak mods are cleared only on key press events (so that weak mods that were applied to some keypress stay active until another key is pressed).  Should a layer state change affect them too?

**Comment by drashna** [comment]
Looks like this is basically left over from the switch to "prevent stuck mods" to being default. 

#3905 added the checks for strict layer release, but original PR didn't change behaviors. 

So, that kind of begs the question, how should this really be handled?

**Comment by KarlK90** [comment]
There is actually a unit-test https://github.com/qmk/qmk_firmware/blob/master/tests/basic/test_action_layer.cpp#L362-L402 that describes a use-case that should normally work but that fails because the modifiers are discarded during `layer_state_set()`.

**Comment by KarlK90** [comment]
LGTM but I wonder if we can just remove the `SEMI_STRICT_LAYER_RELEASE` case.

**Comment by drashna** [comment]
> LGTM but I wonder if we can just remove the `SEMI_STRICT_LAYER_RELEASE` case.

Definitely can.  Was there as a "just in case". Can remove now, but might be worth leaving for now and remove next cycle.

**Review by KarlK90 — APPROVED** [review]

**Review by zvecr — APPROVED** [review]

**Pull request merged**
