### PR TITLE
New iso layout and keymap for dz60 with 4th row all 1u

### PR DESCRIPTION
**Pull request by madhogs**
Added new ISO layout for DZ60 including keymap

## Description

I could not find an existing layout for the DZ60 which allowed both a iso Enter key and all the keys on the 4th row to be 1u in size.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by madhogs** [comment]
I see the build has failed, however when I do `make dz60:all` on the master branch, I get the same failures. Not sure these failures are related to this change?

**Comment by CurryFurious** [comment]
Since you added a new layout in dz60.h, this adds more bytes to the compiled files. Therefore some of the keymaps that were really close to max size were pushed over. Something you could do is try to either re-purpose an existing LAYOUT macro, or define the new macro inside the keymap.c

**Comment by madhogs** [comment]
I added a new layout as I could not find one that would allow someone to have an Iso enter key and all 1u on the 4th row.

The keymaps that fail also do so on the master branch, I even re-cloned qmk to a new folder and only ran `make dz60:all` The ones that fail seem to be over the max size by a similar amount.

Is this something that needs fixing in general for the dz60? I noticed other pull requests which added a new layout also failed to build due to the same keymaps. (such as https://github.com/qmk/qmk_firmware/pull/6996)

**Comment by CurryFurious** [comment]
Seems that something else broke it, looking into it now.

**Comment by drashna** [comment]
@Curry @madhogs  The keymaps that are too large appear to be community layouts, or due to feature creep, or changes to core (such as the cRGB error).  

As this change doesn't directly effect those, they can be ignored, for now. 

Though, @yanfali may want to fix his community layout for the dz60. :)

**Comment by madhogs** [comment]
Hi, is there anything else I can do to get this merged in?

**Comment by noroadsleft** [comment]
Sorry for the delay! Thanks for contributing!

**Pull request merged**
