### PR TITLE
XD75 cleanup

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Not sure if I should remove the `LAYOUT_kc` as well.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — APPROVED** [review]

**Comment by zvecr** [comment]
Removal of `LAYOUT_kc` could be considered breaking, either way the current change set is a move in the right direction so why not get that in sooner than later

**Comment by fauxpark** [comment]
Done, but also decided to fix all the user keymaps not using the LAYOUT macro. The list is probably too long to tag...

**Review by Erovia — APPROVED** [review]

**Comment by Buckwich** [comment]
Thanks @fauxpark. I was thinking about fixing them myself but you were faster. Now I can generate all the keymap.json files for https://qmk-helper.github.io/keyboard-browser/?keyboard=xd75

**Review by drashna — APPROVED** [review]

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
