### PR TITLE
DZ60 cleanup

### PR DESCRIPTION
**Pull request by noroadsleft**
At the point where I want to get eyeballs on this. I think it's pretty much ready but I want input on if I should make any further changes.

As there have been a couple bugs found with the DZ60 code, I wanted to go through it with a fine-tooth comb, so to speak, and make sure everything was in order. The idea was to modernize the code and keymaps found, as there have been quite a few people coming to the QMK Discord for help and such regarding the DZ60, and I wanted to bring everything "up to spec" to hopefully prevent issues down the line.

I think the commit messages explain everything, but there may be a couple things I missed.

### CODE REVIEW

**Comment by noroadsleft** [comment]
Regarding the iso_7u_space keymap, it could actually be refactored to use the new `60_iso_tsangan` layout, but I wasn't sure if that was actually desired.

It and the iso_6u_space keymap both have a modified version of @drashna's block comment in [this post](https://github.com/qmk/qmk_firmware/pull/3924#issuecomment-422177441), which I was debating adding to every keymap, as well as the new_project template (in a separate PR).

**Comment by mechmerlin** [comment]
Since you're refactoring anyway, why not use K(hex number)(hex number) instead of sticking with kbfirmware's method?

**Comment by noroadsleft** [comment]
@mechmerlin sounds good. I actually am not crazy about the matrix locations only being numbered; I think I prefer `k<row number><column letter>`.

**Comment by noroadsleft** [comment]
Done here.

There may be some Configurator weirdness here for a bit, because its API seems to have stopped pulling changes from qmk_firmware over the weekend. (Probably the API updates that were recently made. @skullydazed pls)

**Comment by drashna** [comment]
Awesome, thanks!

**Pull request merged**
