### PR TITLE
Seebs/debouncez

### PR DESCRIPTION
**Pull request by seebs**
This results from some chat with freddizzimo about the debouncing algorithm. The ergodox EZ tends to need a long debounce period to avoid stutter, which makes it less responsive, and this has been aggravated by the improvements to scan rates. This change gets back some of the responsiveness but has basically entirely elimintated stutter for me.

Note that the underlying innovation (?) of doing debounce per-row, rather than per-keyboard, may also work elsewhere. Debouncing per-key might be better still, but requires a much larger pool of debounce information (note the MATRIX_ROWS*MATRIX_COLS allocation in the old version), which is enough storage to be a problem for some keyboards. The decision to store that per-row is influenced by the fact that, on the ergodox, "row" actually means "column" in that a single "row" is all keys hit by the same finger, meaning there's usually not a lot of very fast movement within a row; fast typists will be causing changes in multiple columns.

Also important: This dramatically reduces reordering. If you hit three adjacent keys with the standard keyboard-wide debounce code, and you hit each before the keyboard's done waiting out the previous one's debounce, you will always get them in matrix order. With this, each row reports as soon as it's done debouncing, and it's much less reordered.

### CODE REVIEW

**Comment by drashna** [comment]
Any reason this can't be merged as is? 

@ezuk @jackhumberk ?

**Comment by seebs** [comment]
I'm not sure what the current state of my code is. I eventually concluded that it was safe to process keys becoming pressed on the very first state transition to pressed, I think; no matter how spiky the transition is, it shouldn't happen *at all* unless the switch has actually closed.

**Comment by drashna** [comment]
Okay. 

did you want to close this?  Or was this still a good addition to the board?

**Comment by seebs** [comment]
I've honestly forgotten where I was with this, or what I was up to. I would definitely like to see improved debouncing, because the performance tweaks I did a while back made the old debounce code stutter noticably sometimes. I just don't remember which debouncing I'm on, and haven't had a chance to check because Everything Keeps Happening.

**Comment by fredizzimo** [comment]
There's another debounce pull request open https://github.com/qmk/qmk_firmware/pull/3720, so I think these two should consolidated into one. Taking the best parts of both. 

I will try to check out these two a bit more later today, to get a better overview of the differences.

**Comment by drashna** [comment]
Looks like there are some merge conflicts here, as well.

**Comment by seebs** [comment]
If there's another similar thing being considered, it's probably better, especially if it doesn't need to be ergodox-specific. I was overall very happy with "eagerly jump to a pressed state, but debounce before leaving it"; that appears to produce very few false positives, without the frustrating lag of debouncing in both directions.

**Comment by drashna** [comment]
The other debounce PR is #3720, for reference, and to make it easier to find.

**Comment by drashna** [comment]
@seebs #3720 has been merged, and it may be better to just incorporate that with the Ergodox EZ's matrix.

Would you mind updating the PR to reflect that, or is it okay for me to close this?

**Comment by seebs** [comment]
I haven't had a chance to look at it, and I'm not sure whether it's practical -- the EZ's matrix behavior is weird. I do think that *some* kind of debouncing improvement would probably help a lot, though.

**Comment by seebs** [comment]
on further study, it looks like alex's PR has the same effect, and does it in a cleaner way, so I think I'm gonna opt to close this one since it's now redundant.

**Pull request closed without merging**
