### PR TITLE
`horrortroll/handwired_k552`: fix RGB Matrix LED config

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Moving `g_led_config` for this board to data driven. Since all of the LEDs appear to be marked as underglow this mismatch is not much of an issue:

```
⚠ horrortroll/handwired_k552: led_config: handwired_k552.c: Number of columns in row 0 (16) does not match matrix (17)
```

CC @HorrorTroll, would appreciate some verification if possible.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
image
This looks like it might be out of order?

**Comment by HorrorTroll** [comment]
> This looks like it might be out of order?

Ahh, probably I was typo wrong order for it. Can you resolved that one for me? Thanks.

**Comment by fauxpark** [comment]
Done. Everything else look good?

**Comment by HorrorTroll** [comment]
Yes, everything look good now.

**Pull request merged**
