### PR TITLE
Fix 2U backspace key in ansi_blocker layout for GrayStudio Space65 keyboard

### PR DESCRIPTION
**Pull request by Sibicle**
When building firmware for the GrayStudio Space65 keyboard using the `LAYOUT_65_ansi_blocker` layout, in both the online configurator, as well as building the firmware locally, the key in the backspace position does not work.

## Description

Swap the location of the blank layout position.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Sibicle** [comment]
Done. I also updating the spacing to make it match they keyboard's actual layout more closely, and used Karabiner-EventViewer to double check that all the keycodes were working properly for `gray_studio/space65:default FORCE_LAYOUT=65_ansi_blocker`

**Comment by noroadsleft** [comment]
@Sibicle Are you ready for this to be merged?

**Comment by Sibicle** [comment]
Yup, looks good to me if it does to you!

**Comment by noroadsleft** [comment]
Thanks for the report, and the fixes!

**Comment by Sibicle** [comment]
of course! thanks for the work you do maintaining the project 😄 🙌

**Pull request merged**
