### PR TITLE
[Keymap Removal] keyboard with most keymaps

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Some of the keyboards with most keymaps.

```
find keyboards -type d  -wholename "*/keymaps/*"  | rev | cut -d / -f 3- | rev | sort | uniq -c | sort -nr | head -n 50
```

Keymaps removed manually as hitting diminishing returns on greps.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
keymaps:
```
c
```

**Review by fauxpark — APPROVED** [review]

**Comment by heatxsink** [comment]
Why? I would like to understand why this needed to happen.

**Comment by keyboard-magpie** [comment]
https://github.com/qmk/qmk_firmware/issues/22724

**Comment by heatxsink** [comment]
Thank you!

**Pull request merged**
