### PR TITLE
Add Configurator support for ai03/orbit

### PR DESCRIPTION
**Pull request by zvecr**
## Description

QMK api error log (http://compile.qmk.fm/v1/keyboards/error_log) contains:
```json
{
	"message": "Error: Could not parse qmk_firmware/keyboards/ai03/orbit/info.json as JSON: Expecting value: line 1 column 1 (char 0)",
	"severity": "error"
}
``` 

Added info.json aligned with current LAYOUT and keymaps. Flagging @ai03-2725 for feedback as maintainer.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mechmerlin** [comment]
Tagging @ai03-2725 as I know he said he was looking into this.

**Comment by zvecr** [comment]
@noroadsleft I went with images from the board, https://pbs.twimg.com/media/D0zPs1dU8AAOQgq.jpg. Which from my eyes, has a slightly different stagger, however i will align that part to the kle. As rotation is not supported within the Configurator, i left that part out.

**Comment by zvecr** [comment]
This is what i now have for the kle aligned version.
image

**Comment by noroadsleft** [comment]
> Does the Configurator handle arbitrary x,y combos?

Yes. Any floating-point number for `x` or `y` is valid and supported.

**Comment by ai03-2725** [comment]
Everything looks fine. Thanks!

**Pull request merged**
