### PR TITLE
x-bows nature: fix led order and colors

### PR DESCRIPTION
**Pull request by mikhirev**
## Description

This PR is for two fixes in X-bows Nature LED matrix:

- Fix bug #12872.
- A minor fix of LED numbering. Seems that LED 44 (PageUp) was accidentally moved to the wrong place in the array and LED numbers shifted.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

### CODE REVIEW

**Comment by tzarc** [comment]
@XBowsTech  can you confirm this fix, or is it due to a different PCB revision?

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]
`#pragma weak`

**Comment by drashna** [comment]
Thanks!

**Comment by x3rAx** [comment]
The commit https://github.com/qmk/qmk_firmware/pull/12871/commits/b0a7dbddfce03ac53b52701ecd9df339627ef846 causes my `y` key to have the wrong color. When I switch to the LED test mode, all keys right of the `y` key have their LEDs shifted to the right and when I press `PgUp` the `y` key lights up:

[Video](https://i.imgur.com/MrYvK54.mp4)

I received my X-Bows Nature yesterday, so I assume it's a pretty recent version. If there are no changes in the PCB, I guess this is not correct.

**Comment by mikhirev** [comment]
@x3rAx I confirm this. There's one more place somewhere where numbers need to be fixed… I'll take a look.

**Comment by mikhirev** [comment]
I'm sorry, it was my mistake. The strange numbering of LEDs reflects the wiring of keys. That commit should be reverted.

**Pull request merged**
