### PR TITLE
Add BOOTMAGIC_ENABLE=both which combines lite and full mode

### PR DESCRIPTION
**Pull request by dkjer**
Add BOOTMAGIC_ENABLE = both which combines lite and full mode

## Description

Currently BOOTMAGIC_ENABLE can either be 'lite' ('yes') or 'full'.  VIA currently forces 'lite' mode when enabled, presumably to have a method for clearing eeprom and entering bootloader mode that isn't reliant on a particular set of keys being available on layer 0 (which VIA may change). 

This change allows for both 'full' mode and 'lite' mode to be enabled at the same time.  VIA still defaults to enabling 'lite' mode, but will allow for 'both' mode if bootmagic 'full' functionally is also desired.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
You'll need a `via_eeprom_reset()` call somewhere as per bootmagic lite.

**Comment by dkjer** [comment]
> You'll need a `via_eeprom_reset()` call somewhere as per bootmagic lite.

Is there a reason bootmagic full's `eeconfig_init()` won't work for this purpose?

**Comment by dkjer** [comment]
I have updated the PR to allow for both lite mode and full mode, so that there is always a 'failsafe' method to call `via_eeprom_reset()`

**Comment by zvecr** [comment]
As full bootmagic is on the list of things that might be removed in the near future, could you go into some detail behind the use case for this change (and maybe touch on why [the magic keycodes](https://docs.qmk.fm/#/feature_bootmagic?id=keycodes) wont suffice).

**Comment by dkjer** [comment]
> As full bootmagic is on the list of things that might be removed in the near future, could you go into some detail behind the use case for this change (and maybe touch on why [the magic keycodes](https://docs.qmk.fm/#/feature_bootmagic?id=keycodes) wont suffice).

I honestly don't have a strong use case for bootmagic full, and if its on the list of things to be removed then we can just close this PR.

The main thing I liked keeping it enabled for is having the toggling of debug flags actually being written to eeprom via `eeconfig_update_debug`, as opposed to using `MAGIC_KEY_DEBUG_*` which doesn't update eeprom.  Obviously someone could add their own functionality to suite their preferences, but it was convenient to have a built-in way to choose whether or not to have your debug settings be 'sticky' when iterating on firmware changes.

**Comment by drashna** [comment]
> > You'll need a `via_eeprom_reset()` call somewhere as per bootmagic lite.
> 
> Is there a reason bootmagic full's `eeconfig_init()` won't work for this purpose?

Because VIA doesn't properly hook into eeconfig_init.  It's an oversight that I have a PR open to fix. 
https://github.com/qmk/qmk_firmware/pull/13243

**Comment by drashna** [comment]
> The main thing I liked keeping it enabled for is having the toggling of debug flags actually being written to eeprom via `eeconfig_update_debug`, as opposed to using `MAGIC_KEY_DEBUG_*` which doesn't update eeprom. Obviously someone could add their own functionality to suite their preferences, but it was convenient to have a built-in way to choose whether or not to have your debug settings be 'sticky' when iterating on firmware changes.

Well, `bootmagic_lite` can be overwritten to do more than just the reset, so ... that may be the better way to go.

**Comment by noroadsleft** [comment]
> As full bootmagic is on the list of things that might be removed in the near future, could you go into some detail behind the use case for this change (and maybe touch on why [the magic keycodes](https://docs.qmk.fm/#/feature_bootmagic?id=keycodes) wont suffice).

Full Bootmagic's removal was actually placed on the agenda for QMK back in early March, and this develop cycle is scheduled to remove Full Bootmagic as a feature.

**Pull request closed without merging**
