### PR TITLE
If RGBLIGHT_EFFECT_BREATHE_CENTER is undefined, use fixed breathe table instead of exp() and sin()

### PR DESCRIPTION
**Pull request by mtei**
## Description

This is alternative (radical) version of #5480.

Changed rgblight.c's breathing effect to use a fixed table instead of calculating with exp() and sin(). This change reduces the size of the firmware when using the rgblight breathing effect.

~~I could not decide whether to adopt #5480 or this. So I presented both.~~
This is the result of compilation smaller than #5480, so use this.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/qmk/qmk_firmware/pull/5480#issuecomment-475970683

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Lenbok** [comment]
I've been testing this one for the last few days, it gives a nice reduction in firmware size!

**Comment by drashna** [comment]
Is it possible to specify a custom table for this?

**Comment by Lenbok** [comment]
@drashna In the top of `rgblight_breathing_table_calc.c` it tells you how to generate a custom table for your keymap.

**Comment by drashna** [comment]
Ah, I missed that. 

And I see that if you add the define for the table in a config.h, you can use your own.

**Comment by drashna** [comment]
[RGB Light Breathing Animation improvements](https://trello.com/c/JSQoc594/9-rgb-light-breathing-animation-improvements)

**Comment by drashna** [comment]
It's not really in the scope of this PR, but unfortunately, you cannot use the userspace folder to host the file.  It has to be in a keymap file. Which is unfortunate.

**Comment by mtei** [comment]
The current makefile system has a search path set as follows:

```
$ make crkbd:drashna
....
$ cat .build/obj_crkbd_rev1_drashna/cflags.txt | tr ' ' '\n' | grep ^-I
-Ikeyboards/crkbd/keymaps/drashna       ** keymap **
-Ikeyboards/.
-Ikeyboards/.
-Ikeyboards/.
-Ikeyboards/crkbd
-Ikeyboards/crkbd/rev1
-I.
-Itmk_core
-Iquantum                               ** quantum **
-Iquantum/keymap_extras
-Iquantum/audio
-Iquantum/process_keycode
-Iquantum/api
-Idrivers
-Iquantum/serial_link
-Idrivers/oled
-Idrivers/avr
-Iusers/drashna                         ** users ***
-Itmk_core/protocol
-Itmk_core/common
-Itmk_core/protocol/lufa
-Ilib/lufa
```

**Comment by mtei** [comment]
Another way is to do the following:
```
$ ./util/rgblight_breathing_table_calc > users/drashna/breathe_table.h
$ echo "#include <breathe_table.h>" > keyboards/crkbd/keymaps/drashna/rgblight_breathe_table.h
```

**Comment by drashna** [comment]
Thanks for the info! 

I think the changes to `build_keyboard.mk` is the best option, long term. But outside the scope of this PR.   Until that change drops, the change to the userspace looks fine.


Also, I've tested the code, and it works perfectly. I don't see any issues with it, and I do see a drop in the firmware size.   And I'd like to see this merged sooner, rather than later. 

Also, a similar change for the rgb matrix feature may be a good idea, for the future.

**Pull request merged**
