### PR TITLE
Keymaps for several of my boards

### PR DESCRIPTION
**Pull request by mterhar**
These keymaps mostly have dynamic macros enabled.  One thing I like on smaller boards is making the Tab key into a tapkey for function layer that reveals the F1-F15 keys.  I don't see that mechanic used very often, but on a 40% board, it saves a lot of space!

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! It looks like you have some unwanted modifications to ChibiOS though - would you mind running 

    git submodule sync --recursive
    git submodule update --init --recursive

To reset those?

**Comment by mterhar** [comment]
I tried running those and it didn't seem to change anything.  Git add didn't find anything new to add so I couldn't commit anything...  I'm sure I'm just misunderstanding how the submodules work.

**Comment by mterhar** [comment]
Dangit... now all the submodules are insane.

**Comment by mterhar** [comment]
Looks like I've finally gotten the submodules and shared files all back to what the master branch expects so all the changes in the PR are in my keymap folders.   If Travis succeeds, it should be ready!

Thanks for your patience, @jackhumbert

**Comment by jackhumbert** [comment]
Awesome - thanks! :D

**Pull request merged**
