### PR TITLE
New keyboard - keyprez unicorn

### PR DESCRIPTION
**Pull request by csandven**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
In its current form, this PR cannot be accepted due to the submodule changes in `lib/`.

**Comment by drashna** [comment]
It looks like you have changes to the submodules here.  These need to be reverted before the PR can be approved. 

Rebasing sometimes will fix this. Otherwise, you'd want to do something like this to fix them:
```sh
git checkout master
git submodule foreach 'git log -n1 --oneline'
# remember the first abcdef1234 on the submodules that have an issue
git checkout @@your-branch@@
# for each of the problematic repo's:
cd lib/@@name@@
git checkout abcdef1234
```

**Comment by csandven** [comment]
> In its current form, this PR cannot be accepted due to the submodule changes in `lib/`.

Sorry about that. Accidentally committed them. Will fix, thanks for feedback.

**Comment by csandven** [comment]
> It looks like you have changes to the submodules here. These need to be reverted before the PR can be approved.
> 
> Rebasing sometimes will fix this. Otherwise, you'd want to do something like this to fix them:
> 
> ```shell
> git checkout master
> git submodule foreach 'git log -n1 --oneline'
> # remember the first abcdef1234 on the submodules that have an issue
> git checkout @@your-branch@@
> # for each of the problematic repo's:
> cd lib/@@name@@
> git checkout abcdef1234
> ```

Thanks. Will try that.

**Pull request closed without merging**
