### PR TITLE
Updated slave encoder sync to reduce dropped pulses - v2

### LINKED ISSUE #7055: Rotary encoder unresponsive on slave half of split keyboard
## Describe the Bug

I am using a split keyboard I designed myself, which supports an encoder on both halves. While testing, I found that the master side of the encoder always works as expected, but the slave side encoder drops a lot of keypresses. See below for more test cases.

## System Information

 - Keyboard: Kyria (Firmware not yet in master branch, it's in [this fork](https://github.com/splitkb/qmk_firmware/tree/kyria/keyboards/kyria) until I've verified it works)
   - Revision (if applicable): 1.0
 - Operating system: Windows 10
 - AVR GCC version: 5.4.0
 - ARM GCC version: N/A
 - QMK Firmware version: 0.7.40
 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

The used encoder was the ALPS EC11K1524406 which has a resolution of 2.

## Additional Context

I went through the following tests, and made sure to flash both halves of the keyboard after each recompile:

- `make clean`
- Reverted commit `46c49ae4e639509ceb6e81c460855d2eb89086b8` 
- Disabled Link Time Optimization
- Added `#define TAP_CODE_DELAY 10`, also with values 50 and 100
- Tried `#define SELECT_SOFT_SERIAL_SPEED 2` and `#define SELECT_SOFT_SERIAL_SPEED 0` 
- Tried basic logging using https://docs.qmk.fm/#/newbs_testing_debugging?id=testing-and-debugging, and code like `print("pgdn enc 1;");`
- Tried `#define EE_HANDS` and flashing right EEPROM to each half

When switching the USB cable to the other half, that halves encoder will work perfectly fine, and cause the slave half to exhibit the same behaviours as the other way around. The connected side will always work.

There is no predictability to when the slave encoder does or does not work. When rotating fast it'll be sure to send a few events, but when rotating slowly, tick by tick, it might work 10% of the time.

Other dual split keyboards are the Iris rev3 and rev4, and the Sol rev2.

I've discussed this issue with @zvecr on Discord.

### PR DESCRIPTION
**Pull request by XScorpion2**
##  Description

Fixes the slave encoder state syncing to reduce dropped pulses.
Includes fix for Iris rev3/rev4 phantom pulses.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #7055

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by yanfali** [comment]
tested on iris v3 and spamming issue appears to be gone, I tested just the right side and with trrs between both halves.

**Comment by drashna** [comment]
This completely breaks encoders for the kyria.... :(

When plugging into USB on the left side, only the left encoder works. 
When plugged into USB on the right side, both encoders trigger the left side functionality, and seem to trigger both the clockwise and counterclockwise functionality.

**Comment by XScorpion2** [comment]
@drashna found one more line of code to fix, will do that in a bit

**Comment by XScorpion2** [comment]
@drashna @yanfali just pushed up the last index fix up for split change. Should be good for all cases now.

**Comment by drashna** [comment]
If I plug the USB into the left side, it works correctly, as expected.
If I plug into the right side, but run the left side index.

This is on the kyria. Which does use the `ENCODERS_PAD_x_RIGHT` stuff

**Comment by XScorpion2** [comment]
@drashna Ok, that made a lot more sense! Pushed another fix.

**Comment by drashna** [comment]
sorry for not being clear. 
I blame it on turkey brain :D

Will test in a sec.

**Comment by drashna** [comment]
That works 100%, at least on the kyria.

**Comment by XScorpion2** [comment]
Should work on the Iris still then. Issue was that I didn't consider, or test, right hand master setups.

**Comment by drashna** [comment]
@yanfali ?

**Comment by yanfali** [comment]
> @yanfali ?

I only tested that it stopped spamming. I don't have encoders installed on the Iris v3 I have, it's just a bare PCB. So I can't verify this fixes anything. Iris v3 only supports 1 encoder on right side.

**Comment by drashna** [comment]
So what you're saying is that I should buy an iris and some more encoders.   Oh. No.  Don't twist my arm like that. :D

**Comment by yanfali** [comment]
> So what you're saying is that I should buy an iris and some more encoders. Oh. No. Don't twist my arm like that. :D

I mean you're not wrong. @nooges might be able to weigh in on how well it works on iris v4 and get you sorted out with hardware.

**Comment by drashna** [comment]
Well, I'm sure he can test it out, as well, which would be nice. 

I know it works on the kyria, for both encoders, with both sides master. But I'd like to make sure that the same is true for the iris v3/v4 before this gets merged.  That's my main concern.

**Pull request merged**
