### PR TITLE
Update BM68RGB Caps Lock Backlight status indication

### PR DESCRIPTION
**Pull request by sergiopoverony**
Caps Lock Backlight status

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by sergiopoverony** [comment]
Please pull to master

**Comment by drashna** [comment]
> Please pull to master

Just to let you know, you can edit the title, and this allows you to choose which branch you want the PR to traget.

I've already updated it to target master, so you should be okay.

**Review by drashna — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by fauxpark** [comment]
Merge conflict.

**Comment by peepeetee** [comment]
How important is this feature? Should this be in as default? 
I could reopen a PR for this, just need some tips on weather there is a need for it

**Comment by sergiopoverony** [comment]
> How important is this feature? Should this be in as default? I could reopen a PR for this, just need some tips on weather there is a need for it

In default bm68rgb from shop, this is function work.

**Comment by peepeetee** [comment]
Do you want to resolve the merge conflicts yourself, or do you want me to do another pull request for you?

**Pull request merged**
