### PR TITLE
[WIP] [Keyboard] [Sonix SN32] Redragon K556

### PR DESCRIPTION
**Pull request by CalcProgrammer1**
## Description

This is a work in progress and is not ready to merge yet.  I'm opening this PR so that progress on this work may be tracked.

Adds support for the Redragon K556 keyboard, which uses the Sonix SN32F248B microcontroller.  ChibiOS support for this microcontroller is added in my submodule commit.

Based on work done by @smp4488 here:

https://github.com/smp4488/qmk_firmware/

## Types of Changes

- [X] Core (adding Sonix SN32)
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by CalcProgrammer1** [comment]
Force pushed the branch a few times, but at the current state the keyboard is working with this branch.  Built in effects line up and all OpenRGB related code has been stripped out.  Only works in Linux at the moment, Windows has a USB failure.  Also, the keyboard randomly locks up sometimes.

**Comment by CalcProgrammer1** [comment]
Another update - fixed the mapping of the number pad 0 key.

**Comment by CalcProgrammer1** [comment]
Updated again to fix the LED mapping to go with the Number Pad 0 keymap change.  Now number pad 0 key works and lights up properly.

**Comment by CalcProgrammer1** [comment]
Adjusted timer prescaler from 0x40 to 0x20 - it was flickering a bit too much and it seemed like the slow matrix refresh was causing occasional double typed keypresses.

**Comment by CalcProgrammer1** [comment]
Updated keymap so that the Fn key cycles through RGB modes

**Comment by drashna** [comment]
Because this includes core changes, and a new keyboard, this should be broken up into separate PRs. One for the core changes, and one for the keyboard itself. 

Additionally, looks like there are some merge conflicts.

**Comment by CalcProgrammer1** [comment]
Sounds like a good plan.  I can split it up after I get the rest of the issues worked out.

I just spent several hours figuring out why it detected fine on my AMD Linux desktop but kept having descriptor errors on my Intel Windows laptop.  I traced the issue down to IN transfers greater than 64 bytes (which is the EP0 endpoint size).  Moved some ACK statements around and finally got it working.  I can now use raw HID on my laptop (which was failing because the configuration descriptor becomes >64 bytes when raw HID is enabled).

**Comment by CalcProgrammer1** [comment]
Worked out some more issues.  I was having random lockups.  It turns out these seem to be related to the compiler version used.  GCC 8 is what Debian includes for arm-none-eabi, and my builds were locking up within 60 seconds of fast typing (as I tested using an online typing test).  Someone else testing the port didn't have this issue, so I tested his build on my keyboard and it was fine.  He was using Arch Linux and had GCC 10 arm-none-eabi.  I set up Arch in a docker container and built using GCC 10, no lockups.

Then we were getting debounce issues where keys were double typing.  I sped up the matrix interrupt by reducing the timer prescaler value in matrix.c and this seems to have eliminated most if not all of the double typing issues.

**Comment by CalcProgrammer1** [comment]
We created a new GitHub organization to work on the Sonix SN32 port.  The new development branch can be found here:

https://github.com/SonixQMK

We also have a Discord server where we're discussing the porting efforts here:

https://discord.gg/q8VjhRgzRw

**Comment by CalcProgrammer1** [comment]
We're making good progress on the Sonix port on our fork.  We have solved the USB Raw EP issues so that OpenRGB communication works on all operating systems.  We fixed some issues with the LED matrix (eliminated dim LEDs when off, vastly improved flickering to the point it's better than stock firmware).  We've improved key matrix scan (enabled debouncing, synchronized key scan with LED matrix scan).   We've improved key mapping and added a function layer that includes reset to bootloader for easy reflashing.  We've brought up the SN32F248 non-B chip to essentially the same level of support as the SN32F248B.  I've been using my Redragon K556 with QMK as a daily driver for a few weeks, and while it still occasionally misses a key or hangs on a key for a second or so, the major typing issues have been mostly resolved.  It used to lock up the keyboard if you typed too much, and double typing letters was a frequent occurrence.

Our fork is a month or two behind upstream QMK at this point so rebasing is probably a good idea.

**Pull request closed without merging**
