### PR TITLE
Add info.json for keebio/viterbi

### PR DESCRIPTION
**Pull request by taithethai**
## Description

Created info.json file for the Viterbi.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by taithethai** [comment]
I was able to get the proper layout to appear in the configurator by Ctrl+Alt+I. Unsure if I put info.json in the correct location.

**Comment by taithethai** [comment]
The Travis CI build failed apparently because of community layouts for `./layouts/community/ortho_5x14/peej` and  `./layouts/community/ortho_5x14/yet-another-developer`.

**Comment by taithethai** [comment]
The keymap was originally authored by @bakingpy / @nooges 

- No functionality should have changed as a result of this PR.

**Review by fauxpark — COMMENTED** [review]
I would recommend adding a 1u space between the halves, otherwise looks good.

**Review by fauxpark — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Hmmmm. Looks like you might've been beaten to the punch.
I'd recommend looking at what's currently in the repo and fixing up the new one if it's somehow wrong.

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
Looks like this has been fixed by danny.

**Pull request closed without merging**
