### PR TITLE
Improve stock bootloader list

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Just some tweaks to make this section a bit cleaner (and more complete with the addition of the AT90USB64 and 8MHz Pro Micro bootloaders).

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Whoops. Fixed.
For reference, the Atmel DFU bootloaders are from here: http://ww1.microchip.com/downloads/en/DeviceDoc/megaUSB_DFU_Bootloaders.zip
And the PS2AVRGB one is from https://blog.winkeyless.kr/152 per #4993... although it's apparently been updated since, the MD5s don't match.

**Comment by noroadsleft** [comment]
Thanks!

**Comment by dsanchezseco** [comment]
I'm trying to use the ps2avrgb bootloader flashing with an elite-c(pro micro) without success.

In theory it goes well, but then i cannot flash the keymap, the bootloadHID does not find the MCU and dmesg keeps printing errors about being unable to set the USB device address.

Is and USBasp the only way to flash the bootloaders or does the pro_micro_ISP_B6_10.hex need an update??

I couldn't did it either with the previous version for the atmega32a...

**Comment by fauxpark** [comment]
The PS2AVRGB bootloader only works with the ATmega32A, it will not run on the Pro Micro or Elite C.

**Comment by dsanchezseco** [comment]
I now, what i wanted to say is that instead of using an usbasp as ISP flasher I'm using an elite-c with the pro_micro_ISP_B6_10.hex.

then connecting the atmega32a as said to the elite-c(miso, mosi, reset...) i flash the ps2avrgb, which seems to go well, but later when connecting the atmega32a to the pc it is not recogniced and those errors happen

**Comment by fauxpark** [comment]
What board are you trying to flash?

**Comment by dsanchezseco** [comment]
One I'm designing myself

-------- Original Message --------

**Comment by fauxpark** [comment]
I do know that PS2AVRGB boards are all more or less standardised around a single reference circuit and the bootloader is customised to some extent by the creators, so it may be making some assumptions about how the MCU is wired.

https://github.com/showjean/ps2avrU/blob/master/firmware/ps2avrGB/Circuit/ps2avrGB/20140829_140848_001.png

**Comment by dsanchezseco** [comment]
and the previous bootloader for the atmega32a?? which is the recommended bootloader then for that chip?

**Comment by yiancar** [comment]
I would recommend to go tor a usbasp type bootloader as discipline has:)

**Comment by fauxpark** [comment]
> and the previous bootloader for the atmega32a?? which is the recommended bootloader then for that chip?

If you mean the file added in this PR, it's the same one, just updated to version 1.0.1.

**Comment by dsanchezseco** [comment]
@yiancar is comming on sunday, but anyway there should be one bootloader for the atmega32a or is the only way to flash the keymaps to do ISP flashing every time?

I'll try again with this one when the usbasp comes.

I manually flashed the discipline one with the pro-micro-as-isp and it was recogniced, but as an usbasp and only when the boot pin was low.

**Comment by fauxpark** [comment]
You can use the bootloadHID bootloader (used in PS2AVRGB boards), or you can use the USPAspLoader bootloader as Yiancar suggested. Both will require your circuit to conform to a certain schematic.

**Comment by dsanchezseco** [comment]
I got it working finally! thanks for the tips. I managed to using a pro micro flash the usbasp bootloader(w/o the usbasp dongle).

The problem was a mix of concepts. I wired my board as a usbasp, but as it is an atmega32a y was using the bootloadHID(wrong!). Also the first time i managed to get into the USBasp i tried to flash with :bootloadHID (wrong again!) instead of using USBasp.

I think the root of the problem was that i thought that USBasp was only the dongle, not also the bootloader.

If you will I can PR with updated docs, cause the atmega32a is only marked to be flashed with the bootloadHID.

Regarding the USBasp with the pro micro I guess some docs/changes can be done, but in it's repo.

**Comment by fauxpark** [comment]
Glad to hear it. Yeah, the naming is a little confusing, but makes a kind of sense: USBasp is the name of the ISP flashing tool, but there is also a bootloader called USBaspLoader which *emulates* one.

**Comment by dsanchezseco** [comment]
umm thinking about it like that makes more sense the naming. Thanks for all

**Comment by sfnvm** [comment]
Does [this file](https://github.com/qmk/qmk_firmware/blob/master/util/bootloader_atmega32u4_1.0.0.hex) support tada68 board (using atmega32u4 controller)? I'm accidentally bricked mine (press evil 'eject' button like usually do with my usb :smile:)

**Comment by fauxpark** [comment]
@sfnvm yes, that file is the default bootloader flashed onto 32U4s at the factory :)

**Comment by eriqadams** [comment]
I am unable to enter bootloader mode using QMK Toolbox using this new bootloader (bootloader_atmega32u4_1.0.0.hex) but when able to enter it using old bootloader (bootloader_atmega32u4_1_0_0.hex). So, for blackplum keyboard I go back into older bootloader ?

**Comment by fauxpark** [comment]
It's the exact same file.

**Pull request merged**
