### PR TITLE
Split atreus

### PR DESCRIPTION
**Pull request by henxing**
This is a new keymap. It ports the Atreus' default layout to the Let's Split, while maintaining the Let's Split's method of handling layers.

### CODE REVIEW

**Comment by skullydazed** [comment]
Thanks for putting this together! 

We think that calling this atreus may lead to confusion and would like to make sure it's clear that it's not compatible with the atreus keyboard in anyway. Would you be ok with renaming it? Most people use their github username, but you could call it something like `atreus_like` if that's not something you want to do.

**Comment by henxing** [comment]
Good point! I'll rename it to my username and put a Readme in it explaining its connection to the Atreus layout. Thanks!

**Comment by henxing** [comment]
Ok @skullydazed, I've renamed the layout `henxing` and put `Readme.md` in the keymap folder that explains the motivation for the layout. Let me know if you have any other comments!

**Comment by skullydazed** [comment]
Perfect, thanks!

**Pull request merged**
