### PR TITLE
Make the size of MATRIX_ROW_PINS and MATRIX_ROW_PINS_RIGHT the same

### PR DESCRIPTION
**Pull request by takai**
## Description

As described in [this documentation](https://docs.qmk.fm/#/config_options?id=other-options), the size of MATRIX_ROW_PINS and MATRIX_ROW_PINS_RIGHT must be the same.

> Currently, the size of MATRIX_ROW_PINS must be the same as MATRIX_ROW_PINS_RIGHT and likewise for the definition of columns.

This PR will fix the problem.

Related PR: #12111

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by mtei — APPROVED** [review]
Looks good to me.

**Review by fauxpark — COMMENTED** [review]
Perhaps using `NO_PIN` instead would be a little more self-explanatory.

**Comment by mtei** [comment]
> Perhaps using `NO_PIN` instead would be a little more self-explanatory.

In the current implementation of matrix.c, NO_PIN is meaningful only if DIRECT_PINS is used.

**Comment by fauxpark** [comment]
That shouldn't matter as in this situation whatever the result of "reading" a `NO_PIN` would be gets discarded anyway, no?

**Comment by mtei** [comment]
@takai, I would say it would be better to define matrix_mask as well, just in case. Unfortunately, there is no description of matrix_mask in the documentation, so please see #11974 instead.

**Comment by mtei** [comment]
> That shouldn't matter as in this situation whatever the result of "reading" a `NO_PIN` would be gets discarded anyway, no?

Is there any guarantee that `readPin(NO_PIN)` is safe to execute? It looks like there is no guarantee, at least on AVR.

**Comment by fauxpark** [comment]
`NO_PIN` is essentially defined as `0xFF`, which none of the supported AVRs use as a register. It would probably be a noop trying to read from it, at most you'd get garbage but again, it's basically ignored by the KC_NOs on those spots.

**Comment by drashna** [comment]
@mtei @fauxpark I had this sitting, but: https://github.com/qmk/qmk_firmware/pull/12238

That should solve any issues with using `NO_PIN`

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Pull request merged**
