### PR TITLE
adding my keymap + adding the altgr function for sendstring

### PR DESCRIPTION
**Pull request by AdrienLF**
## Description

Adding a very specific keymap for macro for After Effect and other adobe softwares for the sentraq macropad in ortho layout.

Adding an altgr function in quantum to allow to use characters that need altgr in the new SEND_STRING() macros. 

Changing the ascii_to_keycode_lut[] from 0x80 to 0x100 in the hope of being able to assign the ASCII codes beyong 127. Not 100% this is working yet, but it compiles. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x ] New feature
- [ x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
@AdrienLF I think this PR may handle the AltGR stuff better:
https://github.com/qmk/qmk_firmware/pull/4046  

Also, for stuff like this, we really do want to have a separate PR for the keymap, and for the core code change. 

Additionlly, the `kb.h` and `kb.c` files are wrong here.  You want `number_pad.h` and `number_pad.c`. 


Also, for your keymap, ....
You can use `layer_state_set_user` instead. This will set the rgb modes, no matter what keycode you use for the layer change. 

Additionally, you want to use the `noeeprom` versions of the rgbligh functions, or you'll burn through your eeprom.

**Comment by drashna** [comment]
> Changing the ascii_to_keycode_lut[] from 0x80 to 0x100 in the hope of being able to assign the ASCII codes beyond 127. Not 100% this is working yet, but it compiles.

you don't need to do this. In fact, this is wrong.

0x80 is hex. Converted to decimal is 128.  So the 0x80 already supports the ENTIRE ascii table. There is no need to change those settings.

**Comment by AdrienLF** [comment]
@drashna Thank you for reviewing this, it's my first pull request ever, in a language I don't know.

I wrongly believed I could use the extended ASCII, hence my mistake. I'm sorry. 

About your way to handle the AltGR: but adding it to the quantum, aren't you limiting it to one layout? For example, qwerty and azerty don't need altgr for the same keys, so I'm not sure how it could be the same for both, but I may not understand how this works. Very new at all this. 

Likewise, I updated my keymap to use `layer_state_set_user` but now it doesn't light up when I plug the keyboard, only when I switch layer. 

As for the noeeprom, I'm not sure to understand exactly how it works and the doc says to be careful, so for now I don't really know how I would use it, nor why not using it would burn through my eeprom. 

Thank you for your patience.

**Comment by drashna** [comment]
Sorry for losing track of this. 

For the send string stuff, it relies on the host system's layout.  And then in the firmware, we try to mapp that to the correct stuff.  It's hackish, at best. But that's because of how the USB HID stuff works.

And you could create a `keymap_azerty.h` and `sendstring_azerty.h` in the process_extras folder for both of these.


As for the layer_state_set_*, yeah .... if you add this, it should fix the issue: 
```
void keyboard_post_init_user(void) {
  layer_state_set_user(layer_state);
}
```

**Comment by drashna** [comment]
@AdrienLF There was another PR that added the AltGr/RAlt functionality to SEND_STRING. 

You may need to remove your changes, and/or rebase (or update) your branch here.

**Comment by drashna** [comment]
Another PR addressed the same problem, and has been merged. 

This looks to be unneeded?

**Pull request closed without merging**
