### PR TITLE
Addition of new designer (Flx) and keyboard (Virgo)

### PR DESCRIPTION
**Pull request by Flexerm**
## Description

Added a keyboard from a new designer - FLX - Virgo - which is will be coming onto the market soon.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
For future reference, we recommend against committing to your `master` branch as you've done here, because pull requests from modified `master` branches can make it more difficult to keep your QMK fork updated. It is highly recommended for QMK development – regardless of what is being done or where – to keep your master updated, but **NEVER** commit to it. Instead, do all your changes in a branch (branches are basically free in Git) and issue PRs from your branches when you're developing.

There are instructions on how to keep your fork updated here:

[**Best Practices: Your Fork's Master: Update Often, Commit Never**](https://docs.qmk.fm/#/newbs_best_practices?id=your-fork39s-master-update-often-commit-never)

If you need any help with this just ask.

**You do not need to close this pull request at this time.** Until your pull request is merged, please continue to commit relevant changes to your `master` branch.

**Comment by Flexerm** [comment]
Understood, thank you for the link apologies, I'll keep to this in the future. 

Travis ci failed, but nothing seems to relate to my push, can you advise solution, please?

Thank you.

**Comment by noroadsleft** [comment]
> Travis ci failed, but nothing seems to relate to my push, can you advise solution, please?

Can confirm Travis CI failure is unrelated. Your code compiles fine.

However, your codebase looks like it was made using conventions that are out of date (`KEYMAP` instead of `LAYOUT`, old-style header include guards, etc.), like it's from an old fork of QMK. Did you happen to generate this code using something like kbfirmware.com? And if so, can you post the Zip file? There are quite a lot of changes needed for this code to be acceptable, even though it compiles.

**Comment by Flexerm** [comment]
Thanks, Norodsleft, 

I did use kbfirmware.com for convenience, though I tried to change the file structures to match some of the other boards already in the firmware library.

If your able to point me in the direction of a new commit that follows current guidelines, I'd be happy to change things as necessary.

[flxvirgodefault.zip](https://github.com/qmk/qmk_firmware/files/3826099/flxvirgodefault.zip)

note the files in the .zip are not verbatim as pushed.

Thanks for your time.

**Comment by noroadsleft** [comment]
I realized after opening the Zip file that it actually doesn't have the file I was looking for, which was the kbfirmware.com Configuration JSON.

kbfirmware.com is based on a QMK codebase that's about three years out of date. Earlier this year I wrote a tool that converts kbfirmware.com Configuration JSON files into current-spec QMK data:

https://noroadsleft.github.io/kbf_qmk_converter/

It needs some minor updates for some of the newer QMK conventions/capabilities, but if you have the KBFirmware JSON, running it through this should get your code closer to spec.

Some issues your code currently has:

## Old-style Header Include Guards

Your include guards are in the format of:

```c
#ifndef CONFIG_H
#define CONFIG_H
...
#endif
```

For this purpose, we use `#pragma once` now.

```c
#pragma once
...
```

## Layout Macro names

Your layout macro is named `KEYMAP`. We switched to using `LAYOUT` for this purpose, because "layout" describes the physical arrangement of keys, while "keymap" describes what the keys do when pressed.

## Layout Macro / Keymap Formatting

The purpose of the layout macro is to turn a code block that represents the physical arrangement of keys *and* their function into a switch-matrix-encoded format. The [top half of the layout macro ](https://github.com/qmk/qmk_firmware/blob/17bcde7d4b9a18114ae5088f053b1531c775c22c/keyboards/flx/virgo/virgo.h#L6-L19) should resemble the layout of the assembled keyboard, while [the bottom half](https://github.com/qmk/qmk_firmware/blob/17bcde7d4b9a18114ae5088f053b1531c775c22c/keyboards/flx/virgo/virgo.h#L19-L32) represents how the switches are wired in rows and columns. Your keymap layers in any `keymap.c` files should also resemble the assembled board.

**Comment by noroadsleft** [comment]
You didn't actually need to close this PR, you can still use the branch for it. When you open a pull request, GitHub tracks the "head" branch from which the changes are being brought in, which is your `master` branch for this PR. Any changes you push to the branch will automatically update the pull request with them, until the PR is merged.

If you want to update your code to a new branch and open a new PR, that's fine too – I'm just saying you don't strictly *have to* do so.

**Pull request closed without merging**
