### PR TITLE
Makes the docker build of layouts faster

### PR DESCRIPTION
**Pull request by douglascamata**
## Description

To compile the layouts we just need the following files:

- Desired keyboard files.
- Drivers.
- Quantum.
- TMK Core.
- Lib.
- Makefile.
- All the .mk files.

I also send the QMK version as an environment variable to the Docker
container and updated the Makefile to properly use it. This is needed
to be able to avoid copying the whole `.git` folder.

I ran this in my personal computer with such config: 
- Macbook Retina mid 2015, i7 2.2 GHz, 16 GB
- Docker for Mac Version 2.0.0.3 - 31259, configured with 4 cores and 2 GiB memory, 1 GiB swap) 

And got these results ⬇️

**Before changes:**

```sh
❯ time util/docker_build.sh ergodox_ez:default
QMK Firmware 0.5.132
Making ergodox_ez with keymap default

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/ergodox_ez/matrix.c                                                            [OK]
Compiling: drivers/avr/i2c_master.c                                                                 [OK]
Compiling: keyboards/ergodox_ez/ergodox_ez.c                                                        [OK]
Compiling: keyboards/ergodox_ez/keymaps/default/keymap.c                                            [OK]
Compiling: quantum/quantum.c                                                                        [OK]
Compiling: quantum/keymap_common.c                                                                  [OK]
Compiling: quantum/keycode_config.c                                                                 [OK]
Compiling: quantum/debounce/eager_pr.c                                                              [OK]
Compiling: quantum/process_keycode/process_unicode.c                                                [OK]
Compiling: quantum/process_keycode/process_unicode_common.c                                         [OK]
Compiling: quantum/color.c                                                                          [OK]
Compiling: quantum/rgblight.c                                                                       [OK]
Compiling: drivers/avr/ws2812.c                                                                     [OK]
Compiling: quantum/led_tables.c                                                                     [OK]
Compiling: quantum/process_keycode/process_space_cadet.c                                            [OK]
Compiling: tmk_core/common/host.c                                                                   [OK]
Compiling: tmk_core/common/keyboard.c                                                               [OK]
Compiling: tmk_core/common/action.c                                                                 [OK]
Compiling: tmk_core/common/action_tapping.c                                                         [OK]
Compiling: tmk_core/common/action_macro.c                                                           [OK]
Compiling: tmk_core/common/action_layer.c                                                           [OK]
Compiling: tmk_core/common/action_util.c                                                            [OK]
Compiling: tmk_core/common/print.c                                                                  [OK]
Compiling: tmk_core/common/debug.c                                                                  [OK]
Compiling: tmk_core/common/util.c                                                                   [OK]
Compiling: tmk_core/common/eeconfig.c                                                               [OK]
Compiling: tmk_core/common/report.c                                                                 [OK]
Compiling: tmk_core/common/avr/suspend.c                                                            [OK]
Compiling: tmk_core/common/avr/timer.c                                                              [OK]
Compiling: tmk_core/common/avr/bootloader.c                                                         [OK]
Assembling: tmk_core/common/avr/xprintf.S                                                           [OK]
Compiling: tmk_core/common/magic.c                                                                  [OK]
Compiling: tmk_core/common/mousekey.c                                                               [OK]
Compiling: tmk_core/common/command.c                                                                [OK]
Compiling: tmk_core/protocol/lufa/lufa.c                                                            [OK]
Compiling: tmk_core/protocol/usb_descriptor.c                                                       [OK]
Compiling: tmk_core/protocol/lufa/outputselect.c                                                    [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c                                        [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c                                [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c                                      [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c                                          [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c                                    [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c                                          [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c                                 [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/Events.c                                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c                                         [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/USBTask.c                                                 [OK]
Linking: .build/ergodox_ez_default.elf                                                              [OK]
Creating load file for flashing: .build/ergodox_ez_default.hex                                      [OK]
Copying ergodox_ez_default.hex to qmk_firmware folder                                               [OK]
Checking file size of ergodox_ez_default.hex                                                        [OK]
 * The firmware size is fine - 26330/32256 (5926 bytes free)
      149.63 real         0.04 user         0.02 sys
```

**After changes:**

```sh
$ time util/docker_build.sh ergodox_ez:default
QMK Firmware 0.5.132
Making ergodox_ez with keymap default

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/ergodox_ez/matrix.c                                                            [OK]
Compiling: drivers/avr/i2c_master.c                                                                 [OK]
Compiling: keyboards/ergodox_ez/ergodox_ez.c                                                        [OK]
Compiling: keyboards/ergodox_ez/keymaps/default/keymap.c                                            [OK]
Compiling: quantum/quantum.c                                                                        [OK]
Compiling: quantum/keymap_common.c                                                                  [OK]
Compiling: quantum/keycode_config.c                                                                 [OK]
Compiling: quantum/debounce/eager_pr.c                                                              [OK]
Compiling: quantum/process_keycode/process_unicode.c                                                [OK]
Compiling: quantum/process_keycode/process_unicode_common.c                                         [OK]
Compiling: quantum/color.c                                                                          [OK]
Compiling: quantum/rgblight.c                                                                       [OK]
Compiling: drivers/avr/ws2812.c                                                                     [OK]
Compiling: quantum/led_tables.c                                                                     [OK]
Compiling: quantum/process_keycode/process_space_cadet.c                                            [OK]
Compiling: tmk_core/common/host.c                                                                   [OK]
Compiling: tmk_core/common/keyboard.c                                                               [OK]
Compiling: tmk_core/common/action.c                                                                 [OK]
Compiling: tmk_core/common/action_tapping.c                                                         [OK]
Compiling: tmk_core/common/action_macro.c                                                           [OK]
Compiling: tmk_core/common/action_layer.c                                                           [OK]
Compiling: tmk_core/common/action_util.c                                                            [OK]
Compiling: tmk_core/common/print.c                                                                  [OK]
Compiling: tmk_core/common/debug.c                                                                  [OK]
Compiling: tmk_core/common/util.c                                                                   [OK]
Compiling: tmk_core/common/eeconfig.c                                                               [OK]
Compiling: tmk_core/common/report.c                                                                 [OK]
Compiling: tmk_core/common/avr/suspend.c                                                            [OK]
Compiling: tmk_core/common/avr/timer.c                                                              [OK]
Compiling: tmk_core/common/avr/bootloader.c                                                         [OK]
Assembling: tmk_core/common/avr/xprintf.S                                                           [OK]
Compiling: tmk_core/common/magic.c                                                                  [OK]
Compiling: tmk_core/common/mousekey.c                                                               [OK]
Compiling: tmk_core/common/command.c                                                                [OK]
Compiling: tmk_core/protocol/lufa/lufa.c                                                            [OK]
Compiling: tmk_core/protocol/usb_descriptor.c                                                       [OK]
Compiling: tmk_core/protocol/lufa/outputselect.c                                                    [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c                                        [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c                                [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c                                      [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c                                          [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c                                    [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c                                          [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c                                 [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/Events.c                                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c                                         [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/USBTask.c                                                 [OK]
Linking: .build/ergodox_ez_default.elf                                                              [OK]
Creating load file for flashing: .build/ergodox_ez_default.hex                                      [OK]
Copying ergodox_ez_default.hex to qmk_firmware folder                                               [OK]
Checking file size of ergodox_ez_default.hex                                                        [OK]
 * The firmware size is fine - 26322/32256 (5934 bytes free)
       42.32 real         0.08 user         0.04 sys
```

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code (hopefully) follows the code style of this project.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Technically, we may want the layouts and user folders too, otherwise, you may see breakage on some keymaps when compiled, or may break stuff without knowing.

**Comment by zvecr** [comment]
Correct me if i'm wrong, but by passing the minimal amount of files, you are trying to bypass the expensive git calls. For most cases, the bind mounts themselves should add little overhead.

If the Above holds true, the same thing could be done with just
```
-e SKIP_GIT=true \
```

**Comment by douglascamata** [comment]
@drashna: from the Travis build, the only broken compilations are the ones that are also broken on other `master` commits. 

@zvecr: I'm not trying to bypass expensive git calls. I'm trying to avoid mounting huge folder because I'm not running Linux. I need Docker for Mac and mounting the whole repository in this setup takes almost 2 minutes. Maybe, as a consequence, I also ended up bypassing the expensive git calls. 😬

**Comment by zvecr** [comment]
When you say mounting takes 2 minutes, are you referring to the `time` statistics you mention above?

If so, i'm not sure you can conclusively say that mounting is the issue. The `GET_KEYBOARDS` functionality would have to find fewer boards, which i have seen perform badly on Vagrant, to the extent that you have recorded. My preference would be to address issues like that directly.

Have you profiled any deeper to know where your time is being spent?

**Comment by douglascamata** [comment]
@zvecr I edited that because it was not clear... I actually meant mounting + compiling was taking more than 2 minutes (it's edited there now).

I perceived that most of the time spent between seeing `QMK Firmware 0.5.40` and `Making ergodox_ez with keymap default`. Like, A LOT. When the compilation actually starts, it takes more or less the same time. Nothing very scientific. 

No deeper profiling too.

**Comment by zvecr** [comment]
Good that sounds like the same issue i see with Vagrant. If i prepare my alternative solution (the one i'm currently using for Vagrant), would you be willing to give it a quick speed test? It would be awesome to potentially "2 birds 1 stone" this.

**Comment by douglascamata** [comment]
@zvecr sure, count me in!

FYI, I just tried the `SKIP_GIT` env var on master branch and compared to the branch in this PR.

52 seconds on master + `SKIP_GIT`, with some cache used: 

```sh
> time util/docker_build.sh ergodox_ez:default
QMK Firmware 0.5.132
Making ergodox_ez with keymap default

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text	   data	    bss	    dec	    hex	filename
      0	  26330	      0	  26330	   66da	.build/ergodox_ez_default.hex

Compiling: keyboards/ergodox_ez/keymaps/default/keymap.c                                            [OK]
Compiling: tmk_core/common/command.c                                                                [OK]
Linking: .build/ergodox_ez_default.elf                                                              [OK]
Creating load file for flashing: .build/ergodox_ez_default.hex                                      [OK]
Copying ergodox_ez_default.hex to qmk_firmware folder                                               [OK]
Checking file size of ergodox_ez_default.hex                                                        [OK]
 * The firmware size is fine - 26312/32256 (5944 bytes free)
       51.94 real         0.04 user         0.09 sys
```

46 seconds without `SKIP_GIT`, but with this PR's changes:

```sh
time util/docker_build.sh ergodox_ez:default
QMK Firmware 0.5.132
Making ergodox_ez with keymap default

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/ergodox_ez/matrix.c                                                            [OK]
Compiling: drivers/avr/i2c_master.c                                                                 [OK]
Compiling: keyboards/ergodox_ez/ergodox_ez.c                                                        [OK]
Compiling: keyboards/ergodox_ez/keymaps/default/keymap.c                                            [OK]
Compiling: quantum/quantum.c                                                                        [OK]
Compiling: quantum/keymap_common.c                                                                  [OK]
Compiling: quantum/keycode_config.c                                                                 [OK]
Compiling: quantum/debounce/eager_pr.c                                                              [OK]
Compiling: quantum/process_keycode/process_unicode.c                                                [OK]
Compiling: quantum/process_keycode/process_unicode_common.c                                         [OK]
Compiling: quantum/color.c                                                                          [OK]
Compiling: quantum/rgblight.c                                                                       [OK]
Compiling: drivers/avr/ws2812.c                                                                     [OK]
Compiling: quantum/led_tables.c                                                                     [OK]
Compiling: quantum/process_keycode/process_space_cadet.c                                            [OK]
Compiling: tmk_core/common/host.c                                                                   [OK]
Compiling: tmk_core/common/keyboard.c                                                               [OK]
Compiling: tmk_core/common/action.c                                                                 [OK]
Compiling: tmk_core/common/action_tapping.c                                                         [OK]
Compiling: tmk_core/common/action_macro.c                                                           [OK]
Compiling: tmk_core/common/action_layer.c                                                           [OK]
Compiling: tmk_core/common/action_util.c                                                            [OK]
Compiling: tmk_core/common/print.c                                                                  [OK]
Compiling: tmk_core/common/debug.c                                                                  [OK]
Compiling: tmk_core/common/util.c                                                                   [OK]
Compiling: tmk_core/common/eeconfig.c                                                               [OK]
Compiling: tmk_core/common/report.c                                                                 [OK]
Compiling: tmk_core/common/avr/suspend.c                                                            [OK]
Compiling: tmk_core/common/avr/timer.c                                                              [OK]
Compiling: tmk_core/common/avr/bootloader.c                                                         [OK]
Assembling: tmk_core/common/avr/xprintf.S                                                           [OK]
Compiling: tmk_core/common/magic.c                                                                  [OK]
Compiling: tmk_core/common/mousekey.c                                                               [OK]
Compiling: tmk_core/common/command.c                                                                [OK]
Compiling: tmk_core/protocol/lufa/lufa.c                                                            [OK]
Compiling: tmk_core/protocol/usb_descriptor.c                                                       [OK]
Compiling: tmk_core/protocol/lufa/outputselect.c                                                    [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c                                        [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c                                [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c                                      [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c                                          [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c                                    [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c                                          [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c                                 [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/Events.c                                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c                                         [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/USBTask.c                                                 [OK]
Linking: .build/ergodox_ez_default.elf                                                              [OK]
Creating load file for flashing: .build/ergodox_ez_default.hex                                      [OK]
Copying ergodox_ez_default.hex to qmk_firmware folder                                               [OK]
Checking file size of ergodox_ez_default.hex                                                        [OK]
 * The firmware size is fine - 26322/32256 (5934 bytes free)
       45.87 real         0.08 user         0.04 sys
```

**Comment by douglascamata** [comment]
Now, this PR's changes + adding the `.build` volume: 16.61 seconds.

```sh
$ time util/docker_build.sh ergodox_ez:default
QMK Firmware 0.5.132
Making ergodox_ez with keymap default

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text	   data	    bss	    dec	    hex	filename
      0	  26312	      0	  26312	   66c8	.build/ergodox_ez_default.hex

Compiling: keyboards/ergodox_ez/keymaps/default/keymap.c                                            [OK]
Compiling: tmk_core/common/command.c                                                                [OK]
Linking: .build/ergodox_ez_default.elf                                                              [OK]
Creating load file for flashing: .build/ergodox_ez_default.hex                                      [OK]
Copying ergodox_ez_default.hex to qmk_firmware folder                                               [OK]
Checking file size of ergodox_ez_default.hex                                                        [OK]
 * The firmware size is fine - 26322/32256 (5934 bytes free)
       16.61 real         0.07 user         0.03 sys
```

**Comment by zvecr** [comment]
One thing to note, that last result is an incremental build. While something that should be supported, to avoid comparing apples with oranges, the testing scenarios need to be locked down. The 16s run is potentially comparable to the "52 seconds on master + SKIP_GIT, with some cache used"

**Comment by zvecr** [comment]
@douglascamata At your leisure, feel free to test my solution i was using for Vagrant.

<https://github.com/zvecr/qmk_firmware/tree/feature/get_keyboard_speed>

I have updated the `docker_build.sh` to use the relevant flags.

**Comment by douglascamata** [comment]
@zvecr that works extremely well! I just got a 10 seconds incremental build on master + the alternative keyboard find. A full build took only 48 seconds, in line with what I get from my crazy-hacky idea. This is very nice! 👏 

**Build from scratch:**

```sh
$ time util/docker_build.sh ergodox_ez:default
USING ALT FIND
Making ergodox_ez with keymap default

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/ergodox_ez/matrix.c                                                            [OK]
Compiling: drivers/avr/i2c_master.c                                                                 [OK]
Compiling: keyboards/ergodox_ez/ergodox_ez.c                                                        [OK]
Compiling: keyboards/ergodox_ez/keymaps/default/keymap.c                                            [OK]
Compiling: quantum/quantum.c                                                                        [OK]
Compiling: quantum/keymap_common.c                                                                  [OK]
Compiling: quantum/keycode_config.c                                                                 [OK]
Compiling: quantum/debounce/eager_pr.c                                                              [OK]
Compiling: quantum/process_keycode/process_unicode.c                                                [OK]
Compiling: quantum/process_keycode/process_unicode_common.c                                         [OK]
Compiling: quantum/color.c                                                                          [OK]
Compiling: quantum/rgblight.c                                                                       [OK]
Compiling: drivers/avr/ws2812.c                                                                     [OK]
Compiling: quantum/led_tables.c                                                                     [OK]
Compiling: quantum/process_keycode/process_space_cadet.c                                            [OK]
Compiling: tmk_core/common/host.c                                                                   [OK]
Compiling: tmk_core/common/keyboard.c                                                               [OK]
Compiling: tmk_core/common/action.c                                                                 [OK]
Compiling: tmk_core/common/action_tapping.c                                                         [OK]
Compiling: tmk_core/common/action_macro.c                                                           [OK]
Compiling: tmk_core/common/action_layer.c                                                           [OK]
Compiling: tmk_core/common/action_util.c                                                            [OK]
Compiling: tmk_core/common/print.c                                                                  [OK]
Compiling: tmk_core/common/debug.c                                                                  [OK]
Compiling: tmk_core/common/util.c                                                                   [OK]
Compiling: tmk_core/common/eeconfig.c                                                               [OK]
Compiling: tmk_core/common/report.c                                                                 [OK]
Compiling: tmk_core/common/avr/suspend.c                                                            [OK]
Compiling: tmk_core/common/avr/timer.c                                                              [OK]
Compiling: tmk_core/common/avr/bootloader.c                                                         [OK]
Assembling: tmk_core/common/avr/xprintf.S                                                           [OK]
Compiling: tmk_core/common/magic.c                                                                  [OK]
Compiling: tmk_core/common/mousekey.c                                                               [OK]
Compiling: tmk_core/common/command.c                                                                [OK]
Compiling: tmk_core/protocol/lufa/lufa.c                                                            [OK]
Compiling: tmk_core/protocol/usb_descriptor.c                                                       [OK]
Compiling: tmk_core/protocol/lufa/outputselect.c                                                    [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c                                        [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c                                [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c                                      [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c                                          [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c                                    [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c                                          [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c                                 [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/Events.c                                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c                                         [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/USBTask.c                                                 [OK]
Linking: .build/ergodox_ez_default.elf                                                              [OK]
Creating load file for flashing: .build/ergodox_ez_default.hex                                      [OK]
Copying ergodox_ez_default.hex to qmk_firmware folder                                               [OK]
Checking file size of ergodox_ez_default.hex                                                        [OK]
 * The firmware size is fine - 26312/32256 (5944 bytes free)
       47.88 real         0.04 user         0.03 sys
```

**Incremental build**

```sh
$ time util/docker_build.sh ergodox_ez:default
USING ALT FIND
Making ergodox_ez with keymap default

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text	   data	    bss	    dec	    hex	filename
      0	  26322	      0	  26322	   66d2	.build/ergodox_ez_default.hex

Compiling: keyboards/ergodox_ez/keymaps/default/keymap.c                                            [OK]
Compiling: tmk_core/common/command.c                                                                [OK]
Linking: .build/ergodox_ez_default.elf                                                              [OK]
Creating load file for flashing: .build/ergodox_ez_default.hex                                      [OK]
Copying ergodox_ez_default.hex to qmk_firmware folder                                               [OK]
Checking file size of ergodox_ez_default.hex                                                        [OK]
 * The firmware size is fine - 26312/32256 (5944 bytes free)
        9.76 real         0.04 user         0.09 sys

```

**Comment by zvecr** [comment]
Another thing to note is i have added support for MAKEFLAGS on that branch, if you run something like `export MAKEFLAGS="-j4 --output-sync"` and then build, it should increase speed of the cold builds by a fair chuck.

**Comment by douglascamata** [comment]
Closing this in favor of #6073. Thanks a lot, @zvecr! I'm much happier with faster Docker-based compilation. 😍

**Pull request closed without merging**
