### PR TITLE
Enable forcing of master side for split boards

### PR DESCRIPTION
**Pull request by elagil**
## Description

Since changing split behaviour as in https://github.com/qmk/qmk_firmware/pull/9742 requires too many changes to the code base (at the moment), I made it possible to force one side of a split board to be the master. This is done regardless of the USB connection status. Therefore, keyboard startup happens with no timeout or delay.

This can be enabled by defining `FORCE_MASTER` in a keyboard's `config.h`. The master side is then determined by `MASTER_RIGHT` or `MASTER_LEFT`, so the setting defaults to making the left side the master.

A check in the define statements prevents an infinite loop.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by elagil** [comment]
Rebased onto the development branch

**Comment by elagil** [comment]
Any updates on this?

**Comment by tzarc** [comment]
Can you describe a scenario where the following code isn't sufficient, when placed into your keyboard or keymap code?

```c
bool is_keyboard_master() {
   return is_keyboard_left();
}
```

It seems like a whole bunch of stuff to do something trivial, and of limited usefulness.

**Comment by elagil** [comment]
> Can you describe a scenario where the following code isn't sufficient, when placed into your keyboard or keymap code?

I tried 
```
#include "split_util.h""

bool is_keyboard_master() {
   return isLeftHand;
}
```
since `is_keyboard_left()` is not exposed in `split_util.h`. 

Anyway, this doesn't work at all, as it leaves the slave side unresponsive. `usbDisable()` is never called and is equally not exposed in `split_util.h`. Not calling this function leaves the slave side in a waiting state that it never gets out of.

As for the usefulness: This functionality is crucial for me, because the timeout of the USB detection approach makes the keyboard react too slowly on PC startup, e.g. for getting into UEFI/BIOS. Likewise, a power cycle of the PC can result in the  keyboard being undetected, as described in https://github.com/qmk/qmk_firmware/issues/8990.

**Comment by tzarc** [comment]
Whilst `usbDisable` isn't exposed, the underlying implementation is still able to be executed, and thus can end up allowing keyboard code changes without requiring core updates, e.g. in the case of the Djinn, there's a plug detection I/O input:
```c
bool is_keyboard_master(void) {
    static bool determined = false;
    static bool is_master;
    if (!determined) {
        determined = true;
        setPinInputLow(SPLIT_PLUG_DETECT_PIN);
        wait_ms(50);
        is_master = readPin(SPLIT_PLUG_DETECT_PIN) ? true : false;
        if (!is_master) {
            usbStop(&USBD1);
        }
    }

    return is_master;
}
```

**Comment by elagil** [comment]
Ok, I may implement something like that for my specific board. I thought that the feature was generally of interest, but probably less than I expected.

**Pull request closed without merging**
