### PR TITLE
Update iris default

### PR DESCRIPTION
**Pull request by nooges**
Update default keymap for Iris to move around some keys and add grave to base layer.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Thanks!

**Comment by noroadsleft** [comment]
@nooges a corresponding update to the Configurator defaults would be appreciated, so they don't fall out-of-sync.

https://github.com/qmk/qmk_configurator/blob/master/public/keymaps/keebio_iris_rev2_default.json
https://github.com/qmk/qmk_configurator/blob/master/public/keymaps/keebio_iris_rev3_default.json

**Comment by nooges** [comment]
@noroadsleft Yeah, I actually updated Configurator files first

**Comment by noroadsleft** [comment]
@nooges Indeed you did. I looked at the commit dates but didn't check the contents.

**Pull request merged**
