### PR TITLE
Remove useless wait in AVR suspend code

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

No other references to `BOOTLOADER_TEENSY` in the repo. Seems to be dead code.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
This is needed, or any teensy based with rgb light enabled an rgblight sleep enabled will not wake up.  Such as the ergodox ez.

**Comment by fauxpark** [comment]
Doesn't seem to be, since as is, it doesn't get compiled in.

**Comment by drashna** [comment]
That's because it's generated here: 
https://github.com/qmk/qmk_firmware/blob/01c7108db52677c2a4210bcda0afd2b1d3f7619f/bootloader.mk#L67

However ... testing this out, I can no longer reproduce the behavior that necessitated this in the first place.

**Review by drashna — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by fauxpark** [comment]
Looks like you added it in https://github.com/qmk/qmk_firmware/pull/3461, however if I check out the parent commit (https://github.com/fauxpark/qmk_firmware/commit/df8e417032bace12d69b5d75aebf257ea5dadb86), I get 0 hits...

So I don't know if it ever did anything.

**Pull request merged**
