### PR TITLE
make the doctor less opinionated about the `qmk` path

### PR DESCRIPTION
**Pull request by rupa**
it's a long story how i noticed but, i don't think this hurts, and helps
me out a bit ☺
anyway from looking at history, seems like a path here is an artifact of
when we were globbing several `qmk-*` commands, and hasn't been needed
for a while.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by skullydazed** [comment]
This check is actually deliberate, we need `bin/qmk` to work for some of the make infrastructure. Are you running into a problem because of this check?

**Comment by rupa** [comment]
Fair, I do a lot of python work so my environments can be a bit ... funky. What was going on for me was `qmk doctor` and build commands complaining it couldn't find `bin/qmk` despite that the make/qmk commands run correctly and work fine.

I can deal with this other ways, for sure :) only submitted the PR because it seemed it might be unintentional

**Comment by skullydazed** [comment]
Try doing a `qmk compile -kb clueboard/california -km default`. We don't have a lot of places where `bin/qmk` is called yet, but that's one where it happens for sure. If that doesn't work for you then sorting out your environment is probably going to be needed.

**Comment by rupa** [comment]
Yeah, I can compile that board. To be more clear, my issue wasn't because i had moved any executables.  I believe it was because of self-inflicted hijinks with where a suitable `python3` could be found. So leaving things the way it is is :100: fine by me & apologies for the noise.

**Comment by skullydazed** [comment]
Sounds good, just wanted to make sure we were all on the same page. Thanks for your contribution, even though we didn't end up using it. :)

**Pull request closed without merging**
