### PR TITLE
2020 February 29 Breaking Changes Update

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

Updates QMK's `master` branch with the changes from this Breaking Changes cycle.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Can we make sure we run a `qmk cformat` as the last commit on this branch before merge? There are a handful of files in the repo that aren't formatted, and the CI only applies it to last commit.

**Comment by noroadsleft** [comment]
I would like to but I can't actually run `qmk cformat`... my QMK Python toolchain is broken somehow.

**Comment by Maxr1998** [comment]
@noroadsleft could you als pull in #7680?

**Comment by noroadsleft** [comment]
@Maxr1998 We're currently in our testing period, and as such, only accepting bugfixes to the future branch at this time.

Additionally, your PR currently has some merge conflicts, and can't be merged in its current state anyway.

**Comment by noroadsleft** [comment]
Okay, these changes are merged, but GitHub's not picking it up here. There's something about my workflow GitHub doesn't like.

26eef35f07698d23aafae90e1c230b52e100a334

**Pull request closed without merging**
