### PR TITLE
Seebs/ergodox optimize

### PR DESCRIPTION
**Pull request by seebs**
Performance improvements for the ergodox ez, which reduce scan time from ~3.17ms to ~2.24ms, mostly by performing scans of the two sides in parallel, also dropping some redundant or inefficient operations.

### CODE REVIEW

**Comment by seebs** [comment]
I screwed this one up, there's a "/*" at the end of a comment that should be "*/". the branch has been fixed.

**Comment by ezuk** [comment]
I commented about this code in the bigger PR, do we still need this one open? or do we want to centralize discussion there and close the other two?

**Comment by seebs** [comment]
I was thinking of this as a separate thing from the big PR, because this is probably useful even without it. The big one is only there because I wanted the code to be handy for people to look at.

The magic number should indeed go away; 7 should be (MATRIX_ROWS / 2). What that code is doing is selecting one row on each hand simultaneously, getting results from both, then deselecting them.

The PINF thing isn't just terser, it's several times faster. I went and played a bit with it and debugged assembly, it's going from 36 instructions some of which are jumps to 12 instructions. (And, amusingly, it's clearer... to me.)

**Comment by ezuk** [comment]
Great re the PINF and the magic number -- are you going to make those changes here?

**Comment by ezuk** [comment]
I mean just the magic number change obv. :)

**Comment by seebs** [comment]
I fixed the magic number thing, cleaned up the DEBOUNCE comment and reverted the substantive change for now.

**Comment by ezuk** [comment]
From my side, this is looking good! @jackhumbert do we have your sign-off on this?

**Comment by jackhumbert** [comment]
Awesome! Thanks :)

**Comment by drashna** [comment]
Should help improve issue in #910

**Pull request merged**
