### PR TITLE
Update handwired/evk

### PR DESCRIPTION
**Pull request by YangPiCui**
Updated versioning to be consistent with project description at https://github.com/YangPiCui/ErgonomicVerticalKeyboard/tree/master/EVKVersions

Added the QWERTY layout as the default base layout. Modified and moved my custom layout to the 1st layer.
https://github.com/YangPiCui/ErgonomicVerticalKeyboard/tree/master/EVKVersions/EVK_v0.1.0#2-keymap

Repositioned two keys on the QMK configurator to match the physical layout

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by YangPiCui** [comment]
https://github.com/qmk/qmk_configurator/pull/936

**Comment by drashna** [comment]
This needs a rebase most likely, due to the changes to the chibiOS modules.

**Comment by YangPiCui** [comment]
> chibiOS

Hi, am I the one who should rebase this commit? Do you mean there is a change to QMK's chibiOS module?

**Comment by drashna** [comment]
Yup, you'd want to do so. 

We have a section in the docs that covers that, actually: 
https://docs.qmk.fm/#/newbs_git_best_practices

If you're using it via command line, let us know.

**Comment by YangPiCui** [comment]
Hello, I have rebased the branch. Does this look good?
Capture

**Comment by YangPiCui** [comment]
Should I be doing something?

**Pull request closed without merging**
