### PR TITLE
JJ40: Remove unused Makefile options, minor keymap fixes

### PR DESCRIPTION
**Pull request by Oscillope**
This pull request:

- Adds Caps lock and Key lock to the "oscillope" keymap.
- Removes some unnecessary makefile options to attempt to make boot faster.
- Removes leftover "rgblight" code from the ps2avrgb port, since the JJ40 doesn't have RGB LED support.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool - thanks!

**Comment by runninghack** [comment]
Thank you for your contribution. It's not related, but is it possible to add per switch LED support for JJ40 with QMK?

**Comment by Oscillope** [comment]
@runninghack if you mean individually controllable LEDs per switch, I don't think that the JJ40 PCB actually supports that... As far as I know it only supports controlling all of the switch LEDs at once through the backlight function.

If you want to be adventurous, you could probably get a strip of WS2812 LEDs and attach them to an unused pin on the AVR, and control them using the [RGBlight feature](https://docs.qmk.fm/feature_rgblight.html). I haven't tried this, so I have no idea if it would work.

**Comment by runninghack** [comment]
Controlling all the switch LEDs is just what I meant. On the other hand adding the RGB LED strips also sounds interesting to me. I'll give it a try when I'm available.

**Pull request merged**
