### PR TITLE
Add the FS026 model MCU.

### PR DESCRIPTION
**Pull request by 108360205**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Requires ChibiOS Contrb bump.

**Comment by 108360205** [comment]
"I have added the bootloader functionality, and currently there are no modifications needed. THX!

**Comment by tzarc** [comment]
There are plenty of modifications needed, you've rolled back changes made to QMK.

**Comment by 108360205** [comment]
The ChibOS Contrib changes have not been submitted as a Pull Request yet.

**Review by tzarc — CHANGES_REQUESTED** [review]
As per the PR checklist:
* PR should be submitted using a non-master branch on the source repository
* PRs should contain the smallest amount of modifications required for a single change to the codebase
* valid license headers on all *.c and *.h source files
* fix all merge conflicts before opening the PR (in case you need help or advice, reach out to QMK Collaborators on Discord)
  * PR submitters will need to keep up-to-date with their base branch, resolving conflicts along the way
* readme.md:
  * must follow the template
  * valid hardware availability link (unless handwired) – private groupbuys are okay, but one-off prototypes will be questioned. If open-source, a link to files should be provided.
  * clear instructions on how to reset the board into bootloader mode
  * a picture about the keyboard and preferably about the PCB, too
* Do not include VIA json files in the PR. These do not belong in the QMK repository as they are not used by QMK firmware – they belong in the [VIA Keyboard Repo](https://github.com/the-via/keyboards)
* Do not include KLE json files in the PR. These have no use within QMK.
* all core PRs must now target develop branch, which will subsequently be merged back to master on the breaking changes timeline
* any new boards adding support for new hardware now requires a corresponding test board under keyboards/handwired/onekey
  * for new MCUs, a new “child” keyboard should be added that targets your newly-added MCU, so that builds can be verified

There's a reason why we wrote the [PR Checklist](https://docs.qmk.fm/#/pr_checklist) - this PR is a prime reason why. Until all issues are fixed this PR will not proceed any further.

**Comment by tzarc** [comment]
#23392 is now the new one, apparently.

**Pull request closed without merging**
