### PR TITLE
Revert "handwired/split89 Layout Macro Refactor (#15210)"

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

This reverts commit 26ae43219001dfe20aa525b6fb35f2aeb2b76617.

Requested by @jurassic73.

Apparently something about #15210 breaks the mapping for QMK Configurator, even though I checked binary reproducibility before I opened that PR. Will likely revisit this at a later date.

## Types of Changes

- [x] Bugfix
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
No need to revert.
```c
#define LAYOUT( \
    K04,      K05, K06, K07, K08, K09,        K60, K61, K62, K63, K64, K65, K66,   K67, K68, K69, \
    K24, K14, K15, K16, K17, K18, K19,        K70, K71, K72, K73, K74, K75, K76,   K77, K78, K79, \
    K34, K25, K26, K27, K28, K29,        K90, K80, K81, K82, K83, K84, K85, K86,   K87, K88, K89, \
    K44, K35, K36, K37, K38, K39,        KA0, K91, K92, K93, K94, K95,      K96, \
    K54,      K45, K46, K47, K48, K49,        KB0, KA1, KA2, KA3, KA4,      KA6,        KA8, \
    K55, K56, K57, K58,           K59,        KB1,           KB3, KB4, KB5, KB6,   KB7, KB8, KB9 \
) { \
    { XXX, XXX, XXX, XXX, K04, K05, K06, K07, K08, K09 }, \
    { XXX, XXX, XXX, XXX, K14, K15, K16, K17, K18, K19 }, \
    { XXX, XXX, XXX, XXX, K24, K25, K26, K27, K28, K29 }, \
    { XXX, XXX, XXX, XXX, K34, K35, K36, K37, K38, K39 }, \
    { XXX, XXX, XXX, XXX, K44, K45, K46, K47, K48, K49 }, \
    { XXX, XXX, XXX, XXX, K54, K55, K56, K57, K58, K59 }, \
    { K60, K61, K62, K63, K64, K65, K66, K67, K68, K69 }, \
    { K70, K71, K72, K73, K74, K75, K76, K77, K78, K79 }, \
    { K80, K81, K82, K83, K84, K85, K86, K87, K88, K89 }, \
    { K90, K91, K92, K93, K94, K95, K96, XXX, XXX, XXX }, \
    { KA0, KA1, KA2, KA3, KA4, XXX, KA6, XXX, KA8, XXX }, \
    { KB0, KB1, XXX, KB3, KB4, KB5, KB6, KB7, KB8, KB9 } \
}
```

**Review by tzarc — APPROVED** [review]

**Comment by jurassic73** [comment]
This is still incorrect in the QMK Configurator website tool when I compile firmware and install on my keyboard.

Can this please be rolled back two pull requests to my last pull request which was confirmed working?

**Comment by noroadsleft** [comment]
> This is still incorrect in the QMK Configurator website tool when I compile firmware and install on my keyboard.
> 
> Can this please be rolled back two pull requests to my last pull request which was confirmed working?

It'll have to wait until sometime during the weekend as QMK's `master` branch is currently frozen, pending the release of version 0.15 on Saturday.

**Comment by jurassic73** [comment]
This is working again for the QMK Configurator web interface to create a functional default firmware file.  Thank you!

**Pull request merged**
