### PR TITLE
Tentative Teensy 3.5 support

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Depends on https://github.com/ChibiOS/ChibiOS-Contrib/pull/306

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by Erovia — APPROVED** [review]
LGTM, although I don't have the hw to test it.
I recommend a rebase so the new MCU can be added to the `MCU2BOOTLOADER` list in `lib/python/qmk/constants.py`.

**Comment by drashna** [comment]
This waiting on anything else?

**Comment by fauxpark** [comment]
Just contrib submodule update.

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Looks like it just needs an update w.r.t. the list of MCUs now that RP2040 is in. Collision on the same line, I'd imagine.

**Pull request merged**
