### PR TITLE
Merge ChibiOS and LUFA descriptor support

### PR DESCRIPTION
**Pull request by fredizzimo**
This enables (at least) the following features on ChibiOS
* Midi
* Virtual Serial Port and Steno
* Raw HID

It also fixes some keyboard descriptor fixes that were applied to LUFA, but not ChibiOS

Additionally the USB code now mostly uses a slightly patched CDC driver, so it's much more simple to follow and efficient.

The console output also uses that,  which means that it's no longger dropping characters or even whole lines.

There's also some minor code cleanup and re-organization for the Midi support,  so that the code can be shared.

### CODE REVIEW

**Comment by Wilba6582** [comment]
Maybe I'm reading the diffs wrong, but it seems that this bit I added has been lost:

`/* index of interface */
#define KEYBOARD_INTERFACE          0

// It is important that the Raw HID interface is at a constant
// interface number, to support Linux/OSX platforms and chrome.hid
// If Raw HID is enabled, let it be always 1.
#ifdef RAW_ENABLE
#   define RAW_INTERFACE        	(KEYBOARD_INTERFACE + 1)
#else
#   define RAW_INTERFACE        	KEYBOARD_INTERFACE
#endif`

Comments explain why it should be kept.

**Comment by fredizzimo** [comment]
@Wilba6582, that part is still there, unchanged https://github.com/qmk/qmk_firmware/pull/2362/files#diff-66e939c937b5f0ef05ea673404726a34R138

**Comment by Wilba6582** [comment]
OK so I was reading diffs wrong. Nevermind.

**Comment by jackhumbert** [comment]
Awesome! Thanks :)

**Pull request merged**
