### PR TITLE
Adds the Planck Light keyboard

### PR DESCRIPTION
**Pull request by jackhumbert**

### CODE REVIEW

**Comment by Wilba6582** [comment]
My comments from #1857 still apply. There is no need for `struct is31_led`. LEDs can be easily addressed by an int, and arrays mapping that int to registers, bit offsets, etc. like I did in the original code.

There is no reason you cannot commit my original IS31FL3731 driver code as is, and use it in the Planck Light implementation, thus allowing me the ability to merge my Zeal60 implementation back to master.

**Comment by jackhumbert** [comment]
Never said they didn’t - this latest commit is a very small step in cleaning all of this up. As I mentioned before, the int was not easy to calculate/figure out - a macro to map these three variables to an int may make sense here, but I haven’t looked into if that’s feasible yet.

**Comment by Wilba6582** [comment]
No worries, just assumed a PR means it's finished.

The original code maps an integer "ID" to a driver/matrix/location. Since the max number of locations per matrix is 17, and per driver is 36, the mapping of int to driver/matrix/location is basically:

driver = ID / 36
matrix = ID / 17
location = ID % 17

In the code, I don't use % and / to be optimal.

Thus all the keyboard implementation needs to do is map "ID" in the range 0..71 (or more or less depending on how many drivers) to their physical location. I do this by a 1D array of "points" where "ID" is the index into the array. I also use a 2D array indexed by row/column, which maps to the ID of the LED. This gives an easy way of mapping a switch matrix row/column to a LED ID.

IMHO backlight code works better (and is typically more optimal) when you iterate over the full LED range e.g. 0..71 and then decide what color to make that LED based on lookups etc. Given the ID, you can lookup its position quickly (using a map of ID to position), and then choose a color based on position. I use a fine grained position that can handle offsets present in non-ortho keyboards, but in an ortho keyboard, position could just be row/col. I've recently been tinkering with positions being polar coordinates from the center (and stretched horizontally) to do effects like radial and circular gradients. All the trig math is thus pre-calculated and stored in the array of ID->position, so it's optimal.

But alternatively, you can iterate over row/col, then use a 2D array that maps row/col to LED ID, just like a keymap maps row/col to keycode. Since the number of LEDs is going to be less than 255, you can use 255 as a "not used" value.

My point is that the driver code does not need to know about keyboards or switch matrices, or how the LEDs are physically arranged. Doing so with an int as the ID for the LED means that backlight implementations can be very optimal, and use that ID as the index to arrays, or as the type of an array. Likewise, backlight implementations do not need to know about how many LED drivers are being used, how many matrices per LED driver, etc.

**Comment by jackhumbert** [comment]
The RGB stuff has been removed from this port for now - it'll be added back in once we get it ready to merge.

**Pull request merged**
