### PR TITLE
Updated ACR60, Mechmini, ALU84 readme information and config.h descripters

### PR DESCRIPTION
**Pull request by TurboMech**
In reference to #2230 fixed issues.

Update MECHKEYS keyboards to be uniform in readmes and config.h's PID, MANUFACTORER, and DESCRIPTIONS.   This allows the keyboards to be more uniform amongst the different types.

### CODE REVIEW

**Comment by TurboMech** [comment]
@jackhumbert thats really weird, because in #2206 it is the same keymap and came back with no errors??

**Comment by TurboMech** [comment]
It seems to be failing at the point where it includes my userspace `turbomech.h`, at the keymap level.  @jackhumbert let me know how you'd like to proceed

**Comment by jackhumbert** [comment]
> the failure looks like it may be coming from your titlecase keymap folder name - generally we encourage keymaps to be all lowercase, because some OSes are case-sensitive (like our build system), and others aren't. If you wanna change your keymap to lowercase and reopen this PR, that'd be great!

> Not all keymaps are tested when system-wide changes are made, since Travis runs through everything to just test the default keymaps, but the TurboMech keymap would have failed if tested here - it might not fail locally because Windows is case-insensitive.

**Comment by TurboMech** [comment]
@jackhumbert for some reason on Mac, change the case of the keymap folder does not register as a change within git or GitHub desktop. Any ideas?

**Comment by jackhumbert** [comment]
Recasing things can be tricky - I usually try to use git mv:
https://help.github.com/articles/renaming-a-file-using-the-command-line/

**Comment by TurboMech** [comment]
@jackhumbert for the future using git mv does not seem to allow changes to the folder name (maybe I did something incorrect who knows).  What I did however is edit the folder name via GitHub's web interface https://github.com/blog/1436-moving-and-renaming-files-on-github.

I simply clicked the edit option on the actual keymap then edited the actual folder name from there and viola!

**Comment by jackhumbert** [comment]
I wouldn't use the GUI - it looks like that just renamed the `keyboards/alu84/keymaps/TurboMech/config.h` file to `keyboards/alu84/keymaps/turbomech`, which isn't what we want haha :)

**Comment by TurboMech** [comment]
@jackhumbert yup just saw that fixed it back for now.  I'll fix this

**Comment by TurboMech** [comment]
@jackhumbert fixed this issue by using `git mv TurboMech tempname && git mv tempname turbomech`

**Comment by TurboMech** [comment]
when one thing throws an error, another error rears its ugly head.  Fixed fb7b004

**Comment by jackhumbert** [comment]
Perfect! Thanks :)

**Pull request merged**
