### PR TITLE
Add support for YMDK YD60

### PR DESCRIPTION
**Pull request by DisguisedOtter**
## Description

Add support for YMDK YD60 with default keymaps and optional via support

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — CHANGES_REQUESTED** [review]
Could you add a GPL2+ compatible license header to each of the `c` and `h` files in this PR.

**Comment by DisguisedOtter** [comment]
> Could you add a GPL2+ compatible license header to each of the `c` and `h` files in this PR.

Done :+1:

**Comment by fauxpark** [comment]
This board already exists as `yd60mq`...

**Comment by DisguisedOtter** [comment]
> This board already exists as `yd60mq`...

The MQ has backlight, this version does not. I previously attempted to add via support for the regular yd60 inside the yd60mq but this caused issues with dependencies on led functions.

**Comment by fauxpark** [comment]
The image you've given in the readme shows a PCB with backlight pins.

**Comment by fauxpark** [comment]
From what I can tell the listing has several options, one of them being whether or not to add the underglow LEDs. It's the exact same PCB, they just don't solder the WS2812s on.

**Comment by owestend** [comment]
I also have a PCB like this. In the next days I wanted to build a keyboard from it.
Maybe we could create a new version of the YD60MQ called **noled**?

**Comment by noroadsleft** [comment]
I agree with @fauxpark – I think we should add this as a YD60MQ revision, perhaps `yd60mq/noled`?

**Pull request closed without merging**
