### PR TITLE
Add handwired/byanni

### PR DESCRIPTION
**Pull request by byanni**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by byanni** [comment]
How can I add a info.json file?

**Comment by drashna** [comment]
https://docs.qmk.fm/#/reference_info_json

And the new keyboard template has most of the config in the info.json. 

That said, are you actually compiling locally?  If not, that will greatly slow down things.

**Comment by byanni** [comment]
I wasn't before but even then I'm given the same error.

<class 'ValueError'>
☒ not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/milc/milc.py", line 528, in __call__
    return self.__call__()
  File "/usr/local/lib/python3.9/dist-packages/milc/milc.py", line 533, in __call__
    return self._subcommand(self)
  File "/__w/qmk_firmware/qmk_firmware/lib/python/qmk/decorators.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/__w/qmk_firmware/qmk_firmware/lib/python/qmk/decorators.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/__w/qmk_firmware/qmk_firmware/lib/python/qmk/cli/lint.py", line 170, in lint
    if not keyboard_check(kb):
  File "/__w/qmk_firmware/qmk_firmware/lib/python/qmk/cli/lint.py", line 102, in keyboard_check
    kb_info = info_json(kb)
  File "/__w/qmk_firmware/qmk_firmware/lib/python/qmk/info.py", line 53, in info_json
    layouts, aliases = _search_keyboard_h(keyboard)
  File "/__w/qmk_firmware/qmk_firmware/lib/python/qmk/info.py", line 648, in _search_keyboard_h
    new_layouts, new_aliases = find_layouts(keyboard_h_path)
  File "/__w/qmk_firmware/qmk_firmware/lib/python/qmk/c_parse.py", line 74, in find_layouts
    macro_name, layout, matrix = _parse_layout_macro(line.strip())
  File "/__w/qmk_firmware/qmk_firmware/lib/python/qmk/c_parse.py", line 169, in _parse_layout_macro
    layout, matrix = layout.split(')', 1)
ValueError: not enough values to unpack (expected 2, got 1)
Error: Process completed with exit code 255.

**Comment by drashna** [comment]
It looks like an issue with the layout macro, specifically

**Comment by byanni** [comment]
Do you know a possible solution?

**Comment by drashna** [comment]
The simplest option? 

Set up the build environment, run `qmk new-keyboard` and start over from there.

**Pull request closed without merging**
