### PR TITLE
Durgod K310/K320 Refactor

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

Simplifies the structure of the Durgod K310 and K320 codebases, at the cost of some code duplication.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
8b9408676034b2aee92f21dbafca6eeb43edf71c leaves `keyboards/durgod/k3x0/readme.md` in place deliberately instead of deleting it, even though 0985714dc8abf7ed57dbc9a325bb90b0a5f2d19d leaves it as the only file in this directory. I intend to combine this file with the readme from `keyboards/durgod/dgk6x/`, but I want to refactor that codebase similarly to this one, and combine the contents in that refactor.

**Comment by noroadsleft** [comment]
I don't understand why the [lint check fails](https://github.com/qmk/qmk_firmware/runs/8107327491?check_suite_focus=true#step:7:95) on `durgod/k320/base`:

```sh
 noroadsleft  ~/qmk_firmware/keyboards/durgod  (rf/durgod)
$ git log -1 --oneline
d73821aea3 (HEAD -> rf/durgod, origin/rf/durgod) fix broken links in keyboard readmes

 noroadsleft  ~/qmk_firmware/keyboards/durgod  (rf/durgod)
$ qmk compile -e SILENT=true -kb durgod/k320/base -km default
Ψ Compiling keymap with make --jobs=4 --output-sync=target SILENT=true durgod/k320/base:default


Making durgod/k320/base with keymap default                                                            [OK]
```

**Comment by fauxpark** [comment]
Could it be something to do with this?
image

**Comment by noroadsleft** [comment]
That was exactly it. I messed up a `git add -N` somewhere.

**Review by keyboard-magpie — APPROVED** [review]

**Comment by noroadsleft** [comment]
# PR Notes

This PR consolidates the build options for the Durgod K310 and K320 keyboards as follows:

| What was...                           | is now...                        |
| :------------------------------------ | :------------------------------- |
| `make durgod/k310:<keymap>`           | `make durgod/k310/base:<keymap>` |
| `make durgod/k310/base:<keymap>`      | `make durgod/k310/base:<keymap>` |
| `make durgod/k3x0/k310:<keymap>`      | `make durgod/k310/base:<keymap>` |
| `make durgod/k3x0/k310/base:<keymap>` | `make durgod/k310/base:<keymap>` |
| `make durgod/k320:<keymap>`           | `make durgod/k320/base:<keymap>` |
| `make durgod/k320/base:<keymap>`      | `make durgod/k320/base:<keymap>` |
| `make durgod/k3x0/k320:<keymap>`      | `make durgod/k320/base:<keymap>` |
| `make durgod/k3x0/k320/base:<keymap>` | `make durgod/k320/base:<keymap>` |

As such, keymaps have been relocated as follows:

- The user keymap `kuenhlee` (@kuenhlee) has been moved from `keyboards/durgod/k3x0/k320/keymaps/kuenhlee/` to `keyboards/durgod/k320/keymaps/kuenhlee/`
- The keymaps that were formerly located in `keyboards/durgod/k3x0/keymaps/` – `chimera`, `default`, `default_mac`, `typhon`, and `via` – are now located in `keyboards/durgod/k310/keymaps/`.
- The `default`, `default_mac` and `via` keymaps now have equivalent versions for the K320 in `keyboards/durgod/k320/keymaps/`.

@moults31, your keymap remains present in `keyboards/durgod/k320/keymaps/`, but please note the changes to the keyboard names, and adjust your compilation method accordingly.

cc @dkjer, @tylert (keyboard maintainers)

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
