### PR TITLE
Add sp60 again

### PR DESCRIPTION
**Pull request by Hiiwwy**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Reopening with zero fixes isnt going to gain you any favour ....

**Comment by Hiiwwy** [comment]
I've removed the invalid layer, please let me know what else needs to be changed

**Comment by Hiiwwy** [comment]
> 以零修复重新开放不会给你带来任何好处......

I've removed the invalid layer, please let me know what else needs to be changed

**Review by zvecr — CHANGES_REQUESTED** [review]
> I've removed the invalid layer, please let me know what else needs to be changed

I have multiple times.

You clearly are not testing your submission.. as it does not even compile.

**Pull request closed without merging**
