### PR TITLE
`dp60`: move RGB Matrix LED config to data driven

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

```
⚠ dp60: led_config: dp60.c: Number of columns in row 0 (14) does not match matrix (15)
```

This is a weird one. The number of columns in the LED config is actually correct; instead the `MATRIX_COLS` define is the issue. However, rendered out it still doesn't quite make sense to me.
image
image

For reference, [an image of the board's per-key LEDs](https://imgur.com/GZC0yNs). All 72 LEDs are accounted for, but their matrix positions and ordering is all over the place.
This goes all the way back to the original source: https://github.com/yulei/qmk_firmware/blob/wm690/keyboards/stm60/dp60/dp60.c

I think the ISSI config may be partially to blame here, as it does not have to be in a particular order, but it necessarily forces the RGB Matrix config to follow that order.

CC @yulei, would you be able to provide either a fixed version of this config, or the board schematics (at least the relevant parts) so that I can do it?

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by fauxpark** [comment]
I've redone the LED config, so we are most of the way there now:
image
image
However, this means it is out of sync with the `g_is31fl3731_leds` array, and it will need to be reordered to match.

**Comment by yulei** [comment]
[dp60.pdf](https://github.com/user-attachments/files/16194282/dp60.pdf)
finally find out the schematics file, and what's the current problems?

**Comment by fauxpark** [comment]
As you can see in the above images, the RGB Matrix LEDs are now positioned and ordered correctly. This means the order of the LEDs in the `g_is31fl3731_leds` array no longer matches (if it did previously). It needs to be updated too.

It looks like the LED symbols in the schematic all correspond to the switch symbols (eg. RGB101 = S101 etc), is that correct?

**Comment by yulei** [comment]
> It looks like the LED symbols in the schematic all correspond to the switch symbols (eg. RGB101 = S101 etc), is that correct?

yes, switch and led use same number

**Comment by fauxpark** [comment]
Thanks. Using the schematic I figured out which LED corresponds to which entry in the `g_is31fl3731_leds` array and reordered it to the best of my ability. However I'm not 100% sure of the ordering - for example is `RGB1015-2` the LED for the 2u backspace, or is it `RGB1015`?

Since there are no silkscreen refdes' on the images of the PCB I could find, I have no way of knowing. Could you please verify and suggest changes if required?

**Comment by yulei** [comment]
Please check the silkscreen file, and thanks for your working 

[dp60_silks.pdf](https://github.com/user-attachments/files/16202090/dp60_silks.pdf)

**Comment by fauxpark** [comment]
Great, that was super helpful. This should be ready to go now.

**Review by zvecr — APPROVED** [review]

**Pull request merged**
