### PR TITLE
Document RGB_MATRIX_FRAMEBUFFER_EFFECTS

### PR DESCRIPTION
**Pull request by peepeetee**
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — CHANGES_REQUESTED** [review]
Same needs to be done for LED Matrix (on develop)

**Comment by peepeetee** [comment]
> 
> 
> Same needs to be done for LED Matrix (on develop)

#12986

**Comment by peepeetee** [comment]
> 
> 
> Same needs to be done for LED Matrix (on develop)

I didn't find the corresponding feature flag in LED Matrix's documentation

**Comment by peepeetee** [comment]
> 
> 
> Same needs to be done for LED Matrix (on develop)

#12987

**Review by fauxpark — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Pull request merged**
