### PR TITLE
Fix symmetric70_proto build break on develop branch

### PR DESCRIPTION
**Pull request by mtei**
## Description

Make the changes made to `quantum/matrix.c` in #13045 to symmetric70_proto/matrix_debug/matrix.c` as well.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Comment by fauxpark** [comment]
Merge conflict.

**Comment by fauxpark** [comment]
Ah, it's already been fixed by https://github.com/qmk/qmk_firmware/pull/13645

**Comment by drashna** [comment]
Yeah, but this is a more proper fix.

**Review by drashna — APPROVED** [review]

**Comment by mtei** [comment]
Thanks for quick merge!

**Pull request merged**
