### PR TITLE
[keyboard] yanfali fruity60 prototype

### PR DESCRIPTION
**Pull request by yanfali**
Adds an adafruit bluefruit 32u4 based keyboard to the handwired folder

## Description
The fruity60 is an experimental keyboard using a bluefruit to have a working test platform to play with bluetooth on QMK. This is the basic setup for the keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by yanfali** [comment]
I'll look into user space issue this afternoon

**Comment by mechmerlin** [comment]
Did you get it to work wirelessly with macos yet?

**Comment by yanfali** [comment]
> Did you get it to work wirelessly with macos yet?

I have not gotten it to work with HIgh Sierra. @fauxpark has had success with Catalina. I have had it work well with ChromeOS and Windows 10. I have not had much success with Android Nougat, other than bonding but then it looses connectivity. There are also issues reconnecting. Once bonded it should reconnect automatically but I have no success with this across 3 operating systems. Right now it's pretty much experimental and somewhat flakey.

When it does work it seems pretty solid, and the latency is quite good. @fauxpark thinks the HID GATT specifiers are insufficient and only certain HID codes work on Mac vs Windows/Linux where he thinks the codes would not work because they are enforcing the HID descriptor.

**Comment by fauxpark** [comment]
See https://github.com/adafruit/Adafruit_BluefruitLE_nRF51/issues/48#issuecomment-541535972, it seems macOS will register F13-F24 etc. even though it shouldn't as defined by the descriptor. Windows, Android and Linux probably don't.

**Comment by yanfali** [comment]
OK, I just updated to Mojave and now the bluetooth works. I guess it was just a bug in the bluetooth stack in High Sierra. I'm typing this update right now from the prototype. Pretty awesome.

**Pull request merged**
