### PR TITLE
Add STM32F401/F411 to mcu_selection.mk

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

🧁

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by nooges — APPROVED** [review]

**Review by noroadsleft — APPROVED** [review]

**Comment by fauxpark** [comment]
I'm thinking this could/should actually go straight into master. It's not *really* a core change since it only affects the build process itself, and so there should be no functional difference in the compiled .bin files...

**Comment by noroadsleft** [comment]
> I'm thinking this could/should actually go straight into master. It's not _really_ a core change since it only affects the build process itself (barely), and so there should be no functional difference in the compiled .bin files...

On `qmk:master`:

```shell
58badd7aca01876350fa12e3e88e024d6f2a5459 *handwired_onekey_blackpill_f401_default.bin
96c601ff2cd4ea9976f6a31a646d2ef1f0b52da1 *handwired_onekey_blackpill_f411_default.bin
c161f2348aa966604ce6f84f4b5254a89e34ddd5 *handwired_riblee_f401_default.bin
5ab23022a00e1ac25bc9d4d090dce457c4454199 *matrix_m20add_default.bin
0ab95c0fa2d4b38b4c50e0d47960383687690c24 *matrix_noah_default.bin
d9361837d8fdd05c460cd50f447dbf4a67520687 *zvecr_zv48_f401_default.bin
27296ae01b35d102ea71c6d6fa632ccc8caa4049 *zvecr_zv48_f411_default.bin
```

This PR on `git rebase -i master`:

```shell
58badd7aca01876350fa12e3e88e024d6f2a5459 *handwired_onekey_blackpill_f401_default.bin
96c601ff2cd4ea9976f6a31a646d2ef1f0b52da1 *handwired_onekey_blackpill_f411_default.bin
c161f2348aa966604ce6f84f4b5254a89e34ddd5 *handwired_riblee_f401_default.bin
28d61ca5b6a40e1be5f7ef831d9351bc953718af *matrix_m20add_default.bin
3d78f80482585e8dcd42ced1700815c22d6d50d9 *matrix_noah_default.bin
d9361837d8fdd05c460cd50f447dbf4a67520687 *zvecr_zv48_f401_default.bin
27296ae01b35d102ea71c6d6fa632ccc8caa4049 *zvecr_zv48_f411_default.bin
```

Not sure what the Matrix boards are doing, but I'd say this checks out.

**Comment by fauxpark** [comment]
Yeah, and if this goes into develop I'm gonna have to make a followup PR for `phoenix` and `tkw/stoutgat/v2/f411` once develop is rebased. Whereas if we put this into master I can add those here now, and we can catch future F4 boards in review.

**Review by noroadsleft — APPROVED** [review]
Looks good to me.

**Review by drashna — APPROVED** [review]

**Pull request merged**
