### PR TITLE
Adding standard keymap for wave keyboard to fix #22695

### PR DESCRIPTION
**Pull request by etiennecollin**
## Description

The wave keyboard had a `feature` keymap which was truly ready to use, but it was deleted by https://github.com/qmk/qmk_firmware/pull/22695 . I am therefore adding it once again, this time as the `standard` keymap to be coherent with the naming conventions.

This `standard` keymap is needed on top of the `default` one because the `default` keymap cannot use special features (such as home-row mods) which make a 36 key keyboard truly usable.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by filterpaper** [comment]
Mod-tap keys are permitted in the default keymap.

**Comment by etiennecollin** [comment]
> Mod-tap keys are permitted in the default keymap.

The keymap also features:
- Caps words
- Home row mods
- Multiple layouts on different layers (colemak, qwerty and gaming)
- Multiple layers (media, mouse, numbers, symbols, etc),
- Combos
- `BOTH_SHIFTS_TURNS_ON_CAPS_WORD`

Would that all be accepted for the default keymap? Initially, this is why I had a `feature` keymap.
Thank you for your time.

**Comment by filterpaper** [comment]
Self hosted userspace might be the right place for feature rich keymaps: #22724

**Comment by etiennecollin** [comment]
> Self hosted userspace might be the right place for feature rich keymaps: #22724

Thank you for the link, this is something new. #22724 mentions vendor keymaps; I believe I classify as a vendor since I am the creator/maintainer/designer of this keyboard.

I would like to offer a fully featured, usable keymap to everyone who either buys or builds my keyboard.
Should I simply contact QMK Collaborators on Discord?
Thanks!

**Comment by etiennecollin** [comment]
> > The keymap also features:
> > ```
> > * Caps words
> > 
> > * Home row mods
> > 
> > * Multiple layouts on different layers (colemak, qwerty and gaming)
> > 
> > * Multiple layers (media, mouse, numbers, symbols, etc),
> > 
> > * Combos
> > 
> > * `BOTH_SHIFTS_TURNS_ON_CAPS_WORD`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would that all be accepted for the default keymap? Initially, this is why I offered a `feature` keymap. Thank you for your time.
> 
> My understanding is that the only feature in this list which would not be allowed is the combos.

If that is the case, then I guess that by setting this keymap as the default one, I wouldn't be straying really far from the rule.

**Comment by etiennecollin** [comment]
Hello!
I just replaced the `default` keymap with the `feature` one because the latter is not allowed anymore. The goal is, as the creator of this 34 key split keyboard, to provide a usable keymap by default.
Let me know if you believe I should change something.

**Review by drashna — APPROVED** [review]

**Review by fauxpark — CHANGES_REQUESTED** [review]
Keyboard updates need to go through `develop`.

**Comment by etiennecollin** [comment]
> Keyboard updates need to go through `develop`.

To make sure I understand, I am to merge this PR into the `develop` branch and then that branch will be merged at some point in `master`?

**Comment by fauxpark** [comment]
Yes.
https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs
> keyboard updates and refactors (eg. to data driven) must go through develop to reduce master -> develop merge conflicts

**Review by fauxpark — APPROVED** [review]

**Comment by etiennecollin** [comment]
@drashna @fauxpark Hi, I just want to make sure: is this PR missing something to be merged? Thank you for your time!

**Pull request merged**
