### PR TITLE
RGB Matrix support for Massdrop CTRL/ALT

### PR DESCRIPTION
**Pull request by daniel5151**
Building off of the excellent work done by @helluvamatt a few months ago, this PR switches the Massdrop CTRL/ALT to use QMK's built-in RGB Matrix LED lighting system.

It does also implement 2 small RGB Matrix tweaks: a new breathing effect, and a `RGB_MATRIX_EXTRA_TOG` option. This brings RGB Matrix a bit closer feature-wise to the old Massdrop system.

## Description

- [ALT/CTRL keyboards] Add RGB Matrix compatible LED location definitions
- [ALT/CTRL keymaps] Update keymaps to use RGB Matrix keycodes
    - Tries to keep the layout as-close as possible to the old system
- [Massdrop Configurator] Maintain backwards compatibility with existing configurator
    - Defining `USE_MASSDROP_CONFIGURATOR` enables overriding RGB Matrix effects with effects defined using `led_instruction_t led_instructions[]`.
    - This code is ported over from Massdrop's qmk_firmware fork
- [RGB Matrix] Add Breathing effect
- [RGB Matrix] Add RGB_MATRIX_EXTRA_TOG option
    - When defined, RGB_TOG cycles through 4 lighting modes 
        - ON > JUST_KEYS > JUST_UNDERGLOW > OFF vs. just ON/OFF
    - This is on by default for the ALT/CTRL

## Known Issues

- This PR breaks two keymaps: massdrop/alt:reywood and massdrop/ctrl:responsive_pattern
  - They both hooked into the old Massdrop system for custom lighting effects
    - I've added README files to the two keymaps mentioning that they need to be updated
  - Fortunately, there are similar effects in RGB Matrix, though they are not enabled by default (see notes about performance below)
  
- Performance
  - Some effects (notably those hidden behind RGB_MATRIX_KEYPRESSES) are pretty intense, and can interfere with the timings of the CTRL/ALT
  - As a result, this PR does not enable RGB_MATRIX_KEYPRESSES for the CTRL/ALT by default
  - @XScorpion2 is working on some architectural improvements to the RGB Matrix system which should improve performance, and so, a future PR might enable these effects to run by default

- No EEPROM support (see #4625)
  - i.e: no saving configuration between reboots.
  - Not a major issue, just annoying haha

## Future Improvements

- Switching over to the existing IS31FL3733 driver
    * There already exists a IS31FL3733 driver, why not use it?
    * One major issue is that the current driver implementation only supports a _single_  driver, while the CTRL & ALT both have _two_ drivers.
    * Also, Massdrop's driver seems to be using DMA, while the RGB Matrix doesn't?
    * I took a crack at getting it working and couldn't figure it out... someone better versed in embedded development should take a stab at this. @patrickmt has it on his radar, but it's not high-priority
- Removing legacy Massdrop lighting support entirely
  - This would require the Massdrop configurator to be updated to use RGB Matrix's patterns
  - Moreover, there would have to be a good way to layer several effect per-layer, something the current RGB Matrix system doesn't support
    - This is something that might be solved in the future through @XScorpion2's work

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* #4567 

## Checklist

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by daniel5151** [comment]
@patrickmt, when you get the chance, could you check if these changes have reasonable performance?
If not, see if adjusting `RGB_MATRIX_SKIP_FRAMES` in config_led.h has any effect.

**Comment by skullydazed** [comment]
This is looking pretty good. :)

Before we merge this I'd like to see all the affected users contacted first. There is a tension here between not breaking travis and not breaking a user's git workspace, and it would be best if we could resolve that tension by getting sign-off from everyone involved.

By my reckoning we need sign-off from @abishalom, @reywood, and @valen214. Have I missed anyone?

This also seems to add new keymaps like `massdrop/alt:prilik` and `massdrop/ctrl/mac_md`. Generally we add keymaps separately from core changes unless there's a good reason to include them. Is there a reason here, or could those be moved to a separate PR?

**Comment by daniel5151** [comment]
Good to hear!

The `massdrop/alt:prilik` keymap is my own, and yea, we can definately push it out into a separate PR if need be. The `massdrop/(alt|ctrl):(default|mac)_md` keymaps should be included in this PR, as they are keymaps that use `USE_MASSDROP_CONFIGURATOR` for backwards compatibility with the Massdrop configurator.

@abishalom _should_ be okay, since he didn't mess around with any of the Massdrop lighting stuff. I did tweak his keymap to use the new RGB Matrix system keycodes, and I recall flashing it to confirm that it worked fine. Though, as I'm writing this now, it might make sense to revert those changes, and active the Massdrop compatibility mode flag, as it could be jarring to wake up one morning, flash your keymap, and see that your default lighting effects have changed :) Up to him if he wants me to revert those changes.

@patrickmt attempted to fix @reywood's and @valen214's keymaps to work with the Massdrop compatibility mode, and had some success in doing so. IIRC, reywood's effect is working, but valen214's was far too complicated to try and debug. That said, due to the nature of this PR, these breakages are almost unavoidable, since the whole point is to transition off of the unique Massdrop system, and onto the standard RGB Matrix system. Plus, once XScorpion2's RGB Matrix performance improvements get merged, and `RGB_MATRIX_KEYPRESSES` can be enabled for these boards, a whole wealth of reactive effects similar to these custom keymaps will open up to everyone :)

**Comment by skullydazed** [comment]
Those reasons are good, but they don't address our primary concern- that these people may wake up one day, try to update qmk, and then have a merge conflict on their hand that they have no clue how to fix. Our preferred way to address that is for them sign off to let us know they're aware of and ok with this change to their files.

**Comment by daniel5151** [comment]
Ah, gotcha.

I'm was just trying to offer some background as to why things have changed the way they have :smile:

**Comment by reywood** [comment]
Consider me warned 😃👍

**Comment by abishalom** [comment]
Fine with the changes; don't really care about the RGB customization tbh.

**Comment by valen214** [comment]
> Consider me warned 😃👍

same here 🙂

**Comment by drashna** [comment]
@skullydazed well, we have the sign offs from affected users.

And I believe that @patrickmt was going to test these changes too.
And if there are performance issues, it may be a good idea to test with #5372, as that PR seems to significantly improve performance of the core qmk rgb matrix code.

**Comment by XScorpion2** [comment]
Merged this into #5372 locally, performance was fantastic with the two worst offenders rgb_matrix_multisplash and rgb_matrix_digital_rain only taking 6ms of time to completed compared to the 35ms without the perf improvements.

**Comment by drashna** [comment]
@patrickmt if you could check out this PR, and make sure it's okay? 
And approve the PR, if it's good. 

Though, like @XScorpion2 mentions, it may be worth testing this PR with #5372, as that PR drastically improves performance.

**Comment by XScorpion2** [comment]
<https://github.com/XScorpion2/qmk_firmware/tree/dev/rgb_ctrl> has all the goodies merged in. Tough I did a crap job merging in ws2812 support so don't try rgblight on that branch...

**Comment by patrickmt** [comment]
I've taken a quick look at XScorpion2's branch:

default_md keymaps for both CTRL and ALT do not compile. The main reason is that for #5096, there existed a global variable in rgb_matrix.h which replaced the Massdrop version's frame counter. To remedy this for my tests, I declared g_tick in tmk_core/protocol/arm_atsam/led_matrix.c and increment this counter once per flush.

RGB updates are happening as fast as possible instead of their intended 10ms intervals. This is derailing other timings on the system. Again, methods were in place in #5096 that solved this issue.

@daniel5151 please look into this again

**Comment by XScorpion2** [comment]
Hmm, thats off that it's affecting system timings that much. Can you provide info on what you are seeing that is affected and on which board? I've got a CTRL that I've been using for testing, but just been using the Default keymap. Didn't even realize there was a default_md as well. Will try and repro it as well tonight and see if there are changes in rgb matrix that I should change too.

**Comment by daniel5151** [comment]
@patrickmt does everything work as expected on this PR (i.e: without XScorpion2's cahnges)?

**Comment by XScorpion2** [comment]
Thought about it a bit more, I suspect the timings are animation speed related, which is actually expected with my PR as I did a lot to ensure the following:
- animations use a real-time based timer. 
- All config (hue, val, sat, SPD) values are used and respected in all animations. 
So this means board performance will no longer affect animation speed, and you can adjust any value including speed to levels that you lile and the animation will respect it. The end result is that you can no longer use animation speed as an indication of performance, and the compared to previously the animations may appear faster or slower. So use the key code to increase or decrease speed to your desired level.

**Comment by XScorpion2** [comment]
OK, I see the issue with default_md. It is using a combination of RGB_MATRIX_SKIP_FRAMES 10, the old 32 bit g_tick timer, and USE_MASSDROP_CONFIGURATOR to ensure the 10ms interval animation timing. This is an easy fix and is entirely on my PR https://github.com/qmk/qmk_firmware/pull/5372. That being said, I'd suggest merging just this PR as is and don't merge my PR until I fixed the above issue.

@patrickmt thanks again for the review.

**Comment by patrickmt** [comment]
@daniel5151 I will be testing this PR alone as well soon.

@XScorpion2 That sounds good if it is an easy fix and exactly what is missing. Thanks!

**Comment by XScorpion2** [comment]
@patrickmt pushed up fixes to the merge branch mentioned earlier. Animation timing should be back to normal, within a few frames, and no more compile error.

**Comment by patrickmt** [comment]
After testing this PR and talking it over with @daniel5151, its still not quite ready. Some key features are still missing which are batched updates of LED effects and timed updates of the LED drivers. These together allow for the system to interleave other functions, most critically of which is the power monitoring which is in place to prevent port overloading from lighting and external USB devices coming and going.

With that being said, we think its best to wait on @XScorpion2's PR #5372 to merge. I've tested it again and it has fixed the animation speed very nicely and batched updates are working well (modified update amount from 30 to 15 to align with original Massdrop code). I still don't see how to limit processing/updates to say every 10ms though, if that is implemented. Ex: Setting a current time + 10ms at start of processing. Then after a flush, not processing the next frame until time has caught up.

**Comment by XScorpion2** [comment]
@patrickmt the frame skip define I removed as it's really not the correct way to handle a rendering system. And it's not really ideal to tell users, hey this team skip thingy will make this render task run once every 10ms when in practice that is not true as it's subject to the speed of every other task before it in the loop on the system as this is not a rtos platform. I'm on qmk discord under Xulkal, ping me and we can go over in more detail what the needs are for batching.

**Comment by drashna** [comment]
#5372 has been merged now.  If you could update this to fix the merge conflicts?  And then we'll see about getting this merged in.

**Comment by daniel5151** [comment]
Awesome!

Unlike #5338, this one will take a bit more effort to properly port over and test. I'll try to find some time to get it updated.

**Comment by XScorpion2** [comment]
If you want, I can handle it tonight

**Comment by daniel5151** [comment]
Yeah, feel free!

**Comment by XScorpion2** [comment]
Merge looks good on this pr changes view!

**Comment by drashna** [comment]
This ready to go?  

@patrickmt?

**Comment by patrickmt** [comment]
A few modifications are needed which can be seen here: https://github.com/qmk/qmk_firmware/commit/1a41ed3ea6545747e9a16fcc72a20cb85b525bbf.

This looks ready to go afterwards!

**Comment by daniel5151** [comment]
Righty-o, changes added!

I've also gone ahead and removed my own (out of date) keymap from the PR. Once things land (notably the custom lighting PR), I'll look into open a separate PR for pushing some of the neat things I've cooked up in my keymap (snake and 2048 on a keyboard??)

**Comment by drashna** [comment]
That's why I don't necessarily trust Travis. 

Specifically, it's an issue with the recent zeal code change (sorry), and doesn't affect this. 

So aside from the Travis issues, this is good to go, correct?

**Comment by patrickmt** [comment]
Good job everyone!

**Comment by drashna** [comment]
[RGB Matrix support for Massdrop Boards](https://trello.com/c/Q0PrmO2i/7-rgb-matrix-support-for-massdrop-boards)

**Pull request merged**
