### PR TITLE
[Keyboard] xd60/rev3: Add layout with split spacebar and 6x1U bottom row

### PR DESCRIPTION
**Pull request by sigprof**
## Description

The support for the XD60/XD64 Rev3 PCB was incomplete: this PCB revision supports more layout options for the bottom row, such as split spacebar and 6x1U keys to the right of the spacebar (this 6x1U layout option is available only together with the 2.25U/2.75U split spacebar).

Add the `LAYOUT_all_rev3()` macro which should support all possible switch position of the XD60/XD64 Rev3 PCB (split backspace, split Enter, 15x1U shift row, split spacebar with 3 keys on the left side and 6 keys on the right side).  This new layout is only available when compiling for the `xd60/rev3` model; the older `xd60/rev2` model cannot support it.  The `LAYOUT_all()` macro still contains the older layout of Rev2 PCBs for compatibility with existing keymaps.

Thanks to Reddit users [u/CloudySkys](https://www.reddit.com/user/CloudySkys) (who made a working layout macro for the split spacebar with 6x1U bottom row layout) and [u/Boojakascha](https://www.reddit.com/user/Boojakascha) (who actually has the PCB with that layout and did the required testing).

**Note:** At the moment the final macro has not been tested on a real PCB, so I'm opening this as a draft.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #4387 (that issue was autoclosed, and the requested XD60 Rev3 support was eventually added, but without the split spacebar part which was wanted).

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by alanennis** [comment]
have a couple of these keyboards are would love to see the split space bar options in there.

**Comment by drashna** [comment]
Looks like there is a merge conflict here

**Comment by tzarc** [comment]
If we get the merge conflict sorted it can go in?

**Comment by zlice** [comment]
Got pointed to this from sigprof to get my bottom row working on rev3. (Thanks again)

Works on my end as far as 'testing' goes.

**Pull request closed without merging**
