### PR TITLE
docs: eclipse: recommend changing the default project make target

### PR DESCRIPTION
**Pull request by stapelberg**
Should this target `develop` or `master`?

## Description

This is required for example for quickly iterating with a debugger, where
Eclipse will build the project automatically.

It’s also shorter than the previous steps.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by stapelberg** [comment]
> It’s also shorter than the previous steps.

I think the previous steps might be from before this change even: https://qmk.fm/changes/2017-09-08-making-from-root-and-no-more-makefiles

**Comment by drashna** [comment]
For this, I think targetting `master` is fine.

**Comment by stapelberg** [comment]
> For this, I think targetting `master` is fine.

Thanks. Now targeting master.

**Comment by stapelberg** [comment]
This should be ready to merge

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
