### PR TITLE
Make sure NOBITS is set on reset_key to fix avr-gcc 8.2+ builds

### PR DESCRIPTION
**Pull request by nooges**
Patch from https://github.com/qmk/qmk_firmware/issues/3657#issuecomment-415147411

Tested on avr-gcc 8.3 on Mac.

Still needs testing on Windows and Linux to confirm.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/qmk/qmk_firmware/issues/3657

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Tested on Windows (MSYS2) with AVR-GCC 8.2 and 8.3. Compiles.

**Comment by yanfali** [comment]
Can we get a better description on the commit for what this does please? A reference to a man page is good.

**Comment by nooges** [comment]
So that issue link (https://github.com/qmk/qmk_firmware/issues/3657#issuecomment-415147411) pretty much covers it. Long story short, in avr-gcc pre-8.2, `reset_key` was assigned to a memory area that was in a normal range, but when 8.2 came out, that memory got moved to an out of range area, causing errors like `0x800293 out of range`. Apparently, this was fixed up in avr-gcc, but we haven't seen a release with the fix yet (we expected it in 8.3, but that didn't happen for some reason).

What this commit does is move the `reset_key` back to the original memory location it was in before.

**Comment by yanfali** [comment]
@nooges, do me a favor and amend the commit to reflect this please. Future you and others will be grateful.

**Comment by nooges** [comment]
Done

**Comment by fauxpark** [comment]
Apparently fixed in (avr-)binutils 2.32:

```
$ avr-nm -n satan_default.elf
...
00800239 B reset_key
0080023d B _end
00810000 N __eeprom_end
```
```
$ avr-readelf -S satan_default.elf
...
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .data             PROGBITS        00800100 0046f4 000030 00  WA  0   0  1
  [ 2] .text             PROGBITS        00000000 000094 004660 00  AX  0   0  2
  [ 3] .bss              NOBITS          00800130 004724 000109 00  WA  0   0  1
  [ 4] .noinit           NOBITS          00800239 004724 000004 00  WA  0   0  1
```

**Comment by nooges** [comment]
@fauxpark Nice! I'd still leave the patch in anyhow.

**Comment by drashna** [comment]
The real question, is there any harm in merging this in? 

If not, I think it may be a good idea to include this change, if "they" decide to re-apply the patch that caused the issue in the first place.

**Comment by nooges** [comment]
@drashna Yeah, I don't think there's any harm in merging it in

**Pull request merged**
