### PR TITLE
Add VIA support for yd60mq

### PR DESCRIPTION
**Pull request by DisguisedOtter**
## Description

Add via support for yd60mq. This is without backlight support, as I wasn't comfortable defining 12 or 16 led. It can be enabled easily if you define BACKLIGHT_NUM and change RGBLIGHT_ENABLE to yes. Also add a keymap to use with via

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR
none

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by DisguisedOtter** [comment]
Anything I need to change? As far as I can tell it builds with the default keymaps, it just fails on some rgb stuff that's not used in the via config

**Comment by rbange** [comment]
hey, I actually wanted to port this board to via too and found your pr's:

For me (and in CI too) the build fails due to the following error:

```
Compiling: keyboards/yd60mq/yd60mq.c                                                               In file included from quantum/quantum.h:41,
                 from keyboards/yd60mq/yd60mq.h:3,
                 from keyboards/yd60mq/yd60mq.c:1:
quantum/rgblight.h:232:21: error: 'RGBLED_NUM' undeclared here (not in a function); did you mean 'RGB_HUD'?
 extern LED_TYPE led[RGBLED_NUM];
                     ^~~~~~~~~~
                     RGB_HUD
 [ERRORS]
 |
 |
 |
```

How did managed to compile your version?

**Comment by DisguisedOtter** [comment]
> 
> 
> hey, I actually wanted to port this board to via too and found your pr's:
> 
> For me (and in CI too) the build fails due to the following error:
> 
> ```
> Compiling: keyboards/yd60mq/yd60mq.c                                                               In file included from quantum/quantum.h:41,
>                  from keyboards/yd60mq/yd60mq.h:3,
>                  from keyboards/yd60mq/yd60mq.c:1:
> quantum/rgblight.h:232:21: error: 'RGBLED_NUM' undeclared here (not in a function); did you mean 'RGB_HUD'?
>  extern LED_TYPE led[RGBLED_NUM];
>                      ^~~~~~~~~~
>                      RGB_HUD
>  [ERRORS]
>  |
>  |
>  |
> ```
> 
> How did managed to compile your version?
> 
> EDIT:
> Seems like one need define the `RGBLED_NUM` and `DEVICE_VER` within `yd60mq/via/config.h`. I managed to the get the firmware built and flashed on my 16LED board with:
> 
> ```
> #define DEVICE_VER 0x0002
> 
> #define RGBLED_NUM 16
> ```

Yeah, I mentioned in the PR that those need to be defined for some keymaps, however with the default keymaps it builds without it. Mine doesn't have any backlight so for me there was no way to test and build it with RGB enabled.

**Comment by rbange** [comment]
Ok. First I made a mistake and checked out your master which probably lead to my build errors.

To clarify: You have an "unmodified" yd60mq without any underglow leds? I am asking, as I've never seen such a model. Following the logic of the old PR https://github.com/qmk/qmk_firmware/pull/8629. This would result in a new `DEVICE_VER` aka revision.

Can you provide some information about your board e.g. photos or links?

I have 2 problems with your current implementation:
1. Defining the `DEVICE_VER` in the top-level `config.h` leads to a build error on the 16led revision
2. Im also uncomfortable with defining an `RGBLED_NUM` for via so I would recommend following structure:

```
yd60mq
|-- 12led
|    |-- ...
|-- 16led
|    |-- ...
|-- noled
|    |-- ...
+-- keymaps
    |-- default
    |-- iso
    |-- krusli
    |-- via
```

This has following advantages:
1. Defining VIA support in the `keymaps/` folder is described in the docs (https://caniusevia.com/docs/configuring_qmk)
2. Defining VIA within a keymap delegates the `RGBLED_NUM` problem to its revision.


Maybe we could also give the `noled` version a different product_id, so we can provide 2 jsons in VIA one w/ lighting tab activated and one w/o?

**Comment by DisguisedOtter** [comment]
> Ok. First I made a mistake and checked out your master which probably lead to my build errors.
> 
> To clarify: You have an "unmodified" yd60mq without any underglow leds? I am asking, as I've never seen such a model. Following the logic of the old PR #8629. This would result in a new `DEVICE_VER` aka revision.
> 
> Can you provide some information about your board e.g. photos or links?
> 
> I have 2 problems with your current implementation:
> 
>     1. Defining the `DEVICE_VER` in the top-level `config.h` leads to a build error on the 16led revision
> 
>     2. Im also uncomfortable with defining an `RGBLED_NUM` for via so I would recommend following structure:
> 
> 
> ```
> yd60mq
> |-- 12led
> |    |-- ...
> |-- 16led
> |    |-- ...
> |-- noled
> |    |-- ...
> +-- keymaps
>     |-- default
>     |-- iso
>     |-- krusli
>     |-- via
> ```
> 
> This has following advantages:
> 
>     1. Defining VIA support in the `keymaps/` folder is described in the docs (https://caniusevia.com/docs/configuring_qmk)
> 
>     2. Defining VIA within a keymap delegates the `RGBLED_NUM` problem to its revision.
> 
> 
> Maybe we could also give the `noled` version a different product_id, so we can provide 2 jsons in VIA one w/ lighting tab activated and one w/o?

Hmm, I made a mistake. I have the 'regular' yd60, which is basically the yd60mq without underglow leds. It uses the same firmware and everything though. Guess it needs to be added as a separate device though. I'll change what's needed and put in a new PR.

**Comment by rbange** [comment]
Well, nevertheless VIA support for the yd60mq is a desirable feature. Will you add this to your new PR too, or should I open another PR?

Also, if you introduce a new board, I would advice you to put into into the `ymdk/` tree. The yd60mq, as well as some mother boards still reside in `keyboards/` even though a directory for its manufacturer exists.

**Pull request closed without merging**
