### PR TITLE
Fix some bug.

### PR DESCRIPTION
**Pull request by wb-Joy**
## Description

 Fixed issue where spi_master.c was not included when using flash_spi.
## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by tzarc — CHANGES_REQUESTED** [review]
I'd also like to point out that there are some omissions for WB32 support that we'd like rectified.

The [PR Checklist](https://docs.qmk.fm/#/pr_checklist) states that support for new hardware needs corresponding builds under `keyboards/handwired/onekey`. Generally the approach is that MCUs get a build target for an appropriate devkit, and external peripherals get a keymap that exercises that peripheral, allowing for the peripheral to be tested against many MCUs at once. You can see examples of the devkit support [here](https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/onekey). Are there WB32 devkits that can be targeted?

It's evident from this "bugfix" PR that things weren't tested properly previously, and considering that there are no `onekey` equivalent builds that can verify functionality for either WB32 MCU or SPI Flash, QMK collaborators are reluctant to provide any followup support for untested and unproven code.

Realistically, WB32 MCUs should not have been merged into QMK until these were present and exercised in the corresponding PRs. We'll make sure to update our checklists to ensure new MCU submissions from all manufacturers/vendors also include such information before we consider merging.

That said, given there are no usages of WB32 MCUs in the repository, and there aren't any sanity checks for the SPI Flash code -- we're going to likely need to place a halt on WB32 PRs in the near future unless some confidence in the submissions is restored. The MCUs in question don't even exist on your website, so right now we're strugging to find relevance for inclusion into QMK, especially given that there's quite literally zero ability for QMK collaborators to verify and/or maintain anything related to WB32-related code. Any restructuring undertaken may well break things, and we'll have no feedback due to the lack of being exercised.

Obviously you're using this as an avenue to sell your MCUs to other keyboard manufacturers -- but at this point any effort QMK collaborators are providing to add WB32 support accounts for zero tangible benefit. The number of PRs submitted and considerable time spent reviewing them overall is not something we wish to continue providing, considering zero use in the code.

Please rectify the above `onekey` scenarios, and we'll address future PRs as they come through on a case-by-case basis.

**Comment by wb-Joy** [comment]
@tzarc Thank you very much for pointing out my shortcomings, but I don't agree with what you said that I didn't test the code I provided.
I have tested all flash_SPi-related code on three different hardware platforms (GMMK Pro REV2, GMMK2 P96, gmMK2 P65).As for why I did not find this problem, it is because spi master is used for these three keyboards, so I did not find the problem that SPI_master.c is not included when SPI Master is not applicable.

**Comment by drashna** [comment]
At a *minimum*, we really need `handwired/onekey` boards, so that there is an easy way to test multiple controllers, and verify that they least compile under different configurations.

Eg, if the onekey config had existed, and had been compiled against, this most likely would not have slipped through.  Which is exactly the point of the onekey stuff.

This is to reduce the number of issues/bugs that may pop up, and fixes for them. Which means fewer PR that need to be reviewed, less work for us.  So, it's not unreasonable to ask for a tester keyboard.

**Comment by wb-Joy** [comment]
> At a _minimum_, we really need `handwired/onekey` boards, so that there is an easy way to test multiple controllers, and verify that they least compile under different configurations.
> 
> Eg, if the onekey config had existed, and had been compiled against, this most likely would not have slipped through. Which is exactly the point of the onekey stuff.
> 
> This is to reduce the number of issues/bugs that may pop up, and fixes for them. Which means fewer PR that need to be reviewed, less work for us. So, it's not unreasonable to ask for a tester keyboard.

Ok, I'll do it.

**Pull request closed without merging**
