### PR TITLE
mimic atreus firmware defaults

### PR DESCRIPTION
**Pull request by joedevivo**
Fixed an issue where you couldn't get back to level0 from level2. This keymap change brings default  in line with the documentation that ships with the atreus

### CODE REVIEW

**Comment by Xyverz** [comment]
Why use KC_NO instead of KC_TRNS?

**Comment by joedevivo** [comment]
The goal was to get the exact layout described in this document that shipped with the Atreus kit

img_1399

**Comment by jackhumbert** [comment]
Cool! Thanks :)

**Comment by Xyverz** [comment]
Excellent. Thank you for this, Joe.

**Pull request merged**
