### PR TITLE
Add Tap Dance example to the docs

### PR DESCRIPTION
**Pull request by dustypomerleau**
## Description

* Add an example of using Tap Dance to emulate mod-tap and layer-tap keys with non-basic/modified keycodes
* Add a link to the Advanced Keycodes doc to make people aware that this workaround exists, despite the limitations described for `MT()` and `LT()`, and redirect them to the appropriate docs under Tap Dance
* Per Skullydazed's request, add a note to the Contributing docs about naming conventions for enums

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by dustypomerleau** [comment]
It appears that, due to the fact that my last PR is not merged yet, this PR includes those changes (which are to my keymap) as well as the documentation changes. Is it poor form to submit the PR like this, or does it not matter if the PRs are submitted in order? Should I be checking out a clean version of master that doesn't contain any of my unmerged keymap changes before editing the docs? Happy to do this if it's going to create hassle for maintainers. Thanks.

**Comment by drashna** [comment]
Even still, It has a lot of the same commits, so that's what is causing the issue.

In the future, it may be worth running `git checkout -B new_branch upstream/master` to create a new branch that is up to date with the main QMK repo.

**Comment by dustypomerleau** [comment]
I can rebranch from an updated master and submit a new PR for this, would that help?

**Comment by drashna** [comment]
I think that would be best.  

Rebasing it may help too.

Also, this doc may help to prevent this in the future: https://docs.qmk.fm/#/newbs_best_practices

**Comment by dustypomerleau** [comment]
Closing this - will resubmit thanks

**Pull request closed without merging**
