### PR TITLE
Added songs from Game of Thrones

### PR DESCRIPTION
**Pull request by DDRnJn**
## Description

Added my 3 favorite songs from the Game of Thrones OST to song_list.h:

1. The main theme
2. The Rains of Castamere
3. The Light of the Seven

Tested on a Preonic V2

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by XScorpion2** [comment]
I'm pretty sure this isn't legal...

**Comment by Lenbok** [comment]
If that's true, it would also apply to a bunch of other tunes already in here.

**Comment by drashna** [comment]
I believe that this and the other songs we include are covered by Fair Use clauses for US Copyright laws, actually.

There are a number of considerations for fair use.  I know that one of the is the purpose of the use.  Another is if we are using the full song or just a portion of it. 

But yeah, it's a fair point.

**Comment by DDRnJn** [comment]
Yeah, I'm a bit confused by the initial comment to be honest. Fair use covers transformative work pretty extensively, and representing a song in this manner definitely qualifies. 

Consider that youtube covers of these songs are allowed, and even monetized, while still being covered under fair use.

**Comment by drashna** [comment]
Well, it's a fair concern, to be honest.  I'd rather it be brought up, than just ignored. 

Also, since these aren't recordings, and aren't the full song in most cases, they should definitely be covered under fair use.

**Comment by XScorpion2** [comment]
Fair Use is one of those things that tends to be tested in court. While I personally agree this probably falls into Fair Use, until that is tested, I'm never a fan of testing it (especially with something as popular as GOT) thus my initial comment.

**Comment by DDRnJn** [comment]
Fair enough, I understand the concern. It's hard for me to imagine it being an issue, but it's your call.

**Comment by jackhumbert** [comment]
Nice! I think this is probably transformative, but I think we need to get some actual policy/advice on things like this.

**Comment by DDRnJn** [comment]
Sure! Let me know if it's alright. I've been adding a bunch of stuff the past month, since I thought having a large repository of songs here would be pretty cool, but if it's an issue I can stick to just adding classical music.

**Comment by skullydazed** [comment]
Thanks for submitting this, but we've decided to play it safe with WRT song copyrights for now.

**Pull request closed without merging**
