### PR TITLE
Add Ploopy nano scrollball feature

### PR DESCRIPTION
**Pull request by mrlinuxfish**
I have seen many musings about adding a scrolling 'keymap' for the Ploopy nano so I decided to give it a go implement a scrollball keymap.

## Description

This feature re-implements the drag scroll code from the full size ploopy trackball and exposes a variable `#PLOOPY_SCROLL_BALL` to enable the drag scroll functionality as there are no physical buttons on the Ploopy nano trackball.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — COMMENTED** [review]
Actually, there is an issue I missed with the PR that added the nano.  I have a fix that should be opened shortly, and that will allow you to use `process_mouse_user` in the keymap.c, without touching core code. 

If you like, I can add this to my PR.

**Comment by drashna** [comment]
for reference: #12889

If let me know if you'd like me to keep the code in there for the "scrollball".

**Comment by mrlinuxfish** [comment]
My main goal is to push a scrolling only keymap if anyone wants it. Being able to interact with process mouse in keymap.c is going to be very helpful going forward

**Comment by drashna** [comment]
@mrlinuxfish code fix up PR is in, if you wanted to update your PR?  It should work with only keymap code, now.

**Pull request closed without merging**
