### PR TITLE
Migrate platform independent code from tmk_core -> quantum

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Trying to catch the end of the develop cycle to minimise merge issues

```
git mv tmk_core/common/*action* quantum/
git mv tmk_core/common/key* quantum/
git mv tmk_core/common/eeconfig.* quantum/
```

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Need to retarget `develop`.

**Comment by zvecr** [comment]
Will rebase closer to develop closing, to minimise any potential issues with other user PRs.

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
I'm not sure why, but this break split side detection.  EE Hands, master left/right doesn't matter, the USB side registers as left.  Period.  Confirmed on 3 different boards.  And both with merging into a branch and checkout out this PR directly.

**Comment by sigprof** [comment]
> I'm not sure why, but this break split side detection.

Probably because these files get linked in a different order after applying the PR:
```
quantum/split_common/split_util.c:__attribute__((weak)) bool is_keyboard_left(void) {
tmk_core/common/keyboard.c:__attribute__((weak)) bool is_keyboard_left(void) { return true; }
```

`build_keyboard.mk` contains:
```make
SRC += $(KEYBOARD_SRC) \
    $(KEYMAP_C) \
    $(QUANTUM_SRC)
...
# this appends $(QUANTUM_DIR)/split_common/split_util.c to $(QUANTUM_SRC) if requested
include common_features.mk
...
SRC += $(TMK_COMMON_SRC)
```
So before the PR `quantum/split_common/split_util.c` was listed in `$(SRC)` before `tmk_core/common/keyboard.c`, but after the PR the order of those files is reversed — and this apparently affects the choice between multiple weak definitions of the `is_keyboard_left` symbol.

Note that the behavior of `ld` in the presence of multiple weak definitions of a symbol does not seem to be documented anywhere, therefore relying on the first weak definition overriding subsequent weak definitions might actually be unsafe. However, this might not be the only place in QMK where multiple different weak definitions of the same symbol are used.

**Comment by zvecr** [comment]
Kinda meh, but the latest commit should resolve the split issues. Given the other `SPLIT_KEYBOARD` guards in quantum, its no worse, but overall it would be nice to introduce nicer abstractions for some of this stuff.

**Review by drashna — APPROVED** [review]
Can confirm it works

**Comment by drashna** [comment]
Found an issue.
```c
quantum/via.h:19:10: fatal error: tmk_core/common/eeconfig.h: No such file or directory
 #include "tmk_core/common/eeconfig.h"  // for EECONFIG_SIZE
```

**Review by tzarc — APPROVED** [review]

**Pull request merged**
