### PR TITLE
added dual driver support for IS31FL3737

### PR DESCRIPTION
**Pull request by ccullin**
Added dual driver support for RGB Matrix Driver IS31FL3737

## Description
Changed IS31FL3737 drive config to mirror that of IS31FL3733.
IS31FL3737 now support DRIVER_COUNT 2 with ADDR1 and ADDR2.

if only one Driver is required the config.h file should now NOT include DRIVER_ADDR_2 and have DRIVER_COUNT = 1.    
Previously the code required DRIVER_ADDR_2 = DRIVER_ADDR_1 in order to compile and only one Driver was supported.

if two Drivers are required set DRIVER_COUNT = 2 and set DRIVER_ADDR_1 and DRIVER_ADDR_2 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

Documentation has not been updated but happy to update.

### CODE REVIEW

**Comment by zvecr** [comment]
> if only one Driver is required the config.h file should now NOT include DRIVER_ADDR_2 and have DRIVER_COUNT = 1.
Previously the code required DRIVER_ADDR_2 = DRIVER_ADDR_1 in order to compile and only one Driver was supported.

Given this, and that without additional changes various keyboards will be broken by the change, ive updated this to target `develop`.

**Comment by ccullin** [comment]
hi Joel,

good point.  I can modify the code so older configurations would not break
- but I believe the best solution is to make the code consistent across
Drivers and have users update their configs.
I believe there is precedent for this as I experienced changes with
RGB-Matrix recently.

If you would like me to update to maintain backward compatibility let me
know.  (first time opensource contributor and learning the process - not
sure what 'target develop' means).

Thanks
Chris

0419-269-741
LinkedIn/Chris-Cullin <https://www.linkedin.com/in/chris-cullin>

**Comment by ccullin** [comment]
Is there a way to update this pull request or should it be canceled and restarted?  I would like to make a minor code tweak

**Comment by ccullin** [comment]
cancelling the PR as I will update it further and include documentation changes.

**Pull request closed without merging**
