### PR TITLE
Language update

### PR DESCRIPTION
**Pull request by rmwphd**
## Description

A first attempt to excise the word "slave" from the repo as part of updating terminology. I've replaced every instance of "slave" found with Sublime Text 3's regex find (not whole word only, not case sensitive) and renamed two files that had "slave" in the filename. So far, a very large number of keyboards build correctly, including several splits (e.g., crkbd, ergodox_ez, kyria), but make all takes forever to run and I'm seeing a lot of keymaps with errors from rgb pin things and other errors that shouldn't have anything to do with my changes. 

## Types of Changes

- [X] Core
- [ ] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* #9376 

## Checklist

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by rmwphd** [comment]
Okay, apparently I branched off of my own branch for the language_update branch in such a way that commits from my last PR (relating to my personal keymaps) are included.... I'm having a hard time removing them from this PR in a clean way. Any advice?

**Comment by RossBarnie** [comment]
Take a look at https://github.com/RossBarnie/qmk_firmware/tree/language_update, you'll notice the only commit on top of qmk_firmware's master is your language update commit. I created this by doing the following:
```
git remote add upstream https://github.com/qmk/qmk_firmware.git
git fetch upstream
git checkout -b language_update upstream/language_update
git rebase upstream master -i
... Replace "pick" with "drop" (or "d") for all commits except your language update ...
git push -f
```

Alternatively (and more safely) you could do the following to get to the same point without rewriting history:
```
git checkout -b language_update_new upstream/language_update --no-track
git cherry-pick a4952cf3d
```

You can then update the PR as necessary.

Let me know if you need any lily58 testing @rmwphd

**Comment by rmwphd** [comment]
Thanks @RossBarnie ! I used a cherry-pick to get that commit and put it on a more up-to-date branch and then force pushed it over the version on my personal remote.

**Comment by zvecr** [comment]
While there is some desire to proceed, each area needs to be considered in isolation to ensure:

* Terminology is aligned with standards, For example, I2C will have different terms than SPI.
* Terms are correct for the QMK use-case. For example, the "role" a keyboard takes within splits.

A blanket find-replace is unfortunately not going to be accepted at this time. Start small with the somewhat "well" defined SPI terms, and build outward.

**Pull request closed without merging**
