### PR TITLE
Add DYN_REC_STOP to the dynamic macros, cleanup PR #1267

### PR DESCRIPTION
**Pull request by Vifon**
Do not record the layer modifiers (and other keys) released just after initiating the macro recording.

Includes and closes #1267.

### CODE REVIEW

**Comment by Vifon** [comment]
While I was at it, I fixed some other minor bugs I discovered in the meantime. Sorry for piggybacking.

**Comment by Vifon** [comment]
My proposal for the issue I pointed out [here][1] can be found in vifon@4b50ea15a954de2e6062aa7228bd1f9f76669ce7, Opinions needed, I don't really like it but it should work.

[1]: https://github.com/qmk/qmk_firmware/pull/1267#issuecomment-299059781

**Comment by cinaeco** [comment]
Ah, I see. I did not think about that. Thanks for weighing in! 
https://github.com/Vifon/qmk_firmware/commit/4b50ea15a954de2e6062aa7228bd1f9f76669ce7 works for me.

I can't really think of a way to discriminate layers (e.g. my `MREC` layer) being recorded at the end, but as you said, it doesn't appear to affect actual macro operation, just some perpetually wasted space.

**Comment by jackhumbert** [comment]
Awesome - thanks folks!

**Pull request merged**
