### PR TITLE
Klackygears into main

### PR DESCRIPTION
**Pull request by Klackygears**
Adding my keymaps and user files to the main branch.

## Description

Adding in various keyboards and my user space to upstream. Also, adding my handwired Brain keyboard. This is my first pull request. Please, be gentile! :-)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X ] Keyboard (addition or update)
- [X ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Klackygears** [comment]
I'll have to figure that out! LOL! Will do it though!

**Comment by Klackygears** [comment]
closing this request in favor of recreating

**Comment by zvecr** [comment]
Thanks and sorry to be a pain! We have some docs on the git basics <https://docs.qmk.fm/#/newbs_git_best_practices> which will give you the multiple branches required to raise separate PRs. You should be able to apply parts of this PRs branch to a newly created branch (something like <https://stackoverflow.com/a/1355990>).

**Comment by Klackygears** [comment]
It's no pain! I'm learning! I'm submitting another request now with fewer changes, lol!

**Pull request closed without merging**
