### PR TITLE
[Proposal?] Allow RGB Underglow to turn off when host is idle/asleep

### PR DESCRIPTION
**Pull request by drashna**
Wasn't sure how to tag this, really...

But it would be nice if when the host system went to sleep, that the RGB underglow would turn off, as well.  THis way, the keyboard isn't a beacon in the night (for instance). 

This does work on the three boards I've tested it on (ergodox ez, orthodox, woodpad).  I don't have a chibiOS board to test, so I can't verify on one of those.

It does have the issue where it flickers when the board starts up.  Not sure why.

### CODE REVIEW

**Comment by TurboMech** [comment]
@drashna I did this same thing to my personal suspend.c never thought people would be interested in it.  Plus suspend doesn’t work on Mac (what I use mostly) so I never thought to PR it. Good work!

**Comment by drashna** [comment]
Actually, I think most of this code is from reddit, and from chatting with you.  I've had it sitting in a branch, and cleaned up some of the issues I found with it.  (like causing the firmware to lock up).  

And yeah, my keyboards are in my bedroom, so.... beacons of light makes it annoying! 

I'm still not sure why it flickers though, and that's ... annoying

**Comment by drashna** [comment]
If #2106 gets merged, this should use "rgblight_disable" instead.  That may be cleaner, overall.

**Comment by TurboMech** [comment]
Never heard of it flickering. I’ll check my code when I get home and compare it with yours.  On mobile and never pushed the suspend.c to my repo.

**Comment by drashna** [comment]
It only flickers on initialization. After that, there is no issue.
So it may be a timing issue?

**Comment by MagFlux** [comment]
@jackhumbert I know this is an older pull request and now has some conflicts (very minor/simple) but is there anyway we can get this merged in?  

After coming across this post on Reddit (https://www.reddit.com/r/olkb/comments/79nizx/qmk_kbd75_underglow_stays_on_when_pc_is_shut_down/) I realized I wasn't the only one who has had this issue regarding boards with RGB under lighting when the host PC is suspended/put to sleep. I never got around to looking into it myself but when I saw these changes I went ahead and gave them a shot and they work perfectly on my KBD75 and S65-X. I spoke with the OP crzone and these changes still work for him and I assume the same goes for @drashna unless he chimes in saying otherwise.  

While yes it's easy enough for me to merge these changes in locally for personal use I feel like this should be made part of the master branch as without them it definitely goes against the expected behavior for lit USB devices when connected to a host that suspends/sleeps. I constantly use the sleep functionality on my PCs so I always found the behavior to be odd considering the lighting would stay on while all my other USB devices would turn off their lighting when the computer suspended.

Thanks in advance!

**Comment by drashna** [comment]
Conflicts resolved, and maybe I should rebase the branch... (but ... ugh, I'd rather not, just in case) 

And yeah, getting this merged in would be fantastic.

**Comment by MagFlux** [comment]
@drashna Thanks for resolving those conflicts (that was fast). Forgot to mention it in my previous comment but it's much appreciated in regards to you putting together this pull request, nicely done. 😃

**Comment by drashna** [comment]
Welcome.  And I pretty much always have github open, so ...

**Comment by jackhumbert** [comment]
Nice :) looks good! Would you mind sticking some documentation on it somewhere?

**Comment by drashna** [comment]
There is an entry in the feature_rgblight, under the Optional Configuration: 
https://github.com/drashna/qmk_firmware/blob/rgb_sleeping/docs/feature_rgblight.md#optional-configuration

If this needs to be expanded, I can do so.

**Comment by jackhumbert** [comment]
Doy - somehow missed that despite being the first file :) perfect! Thanks :D

**Comment by MagFlux** [comment]
Fantastic, thanks everyone for the help!

**Pull request merged**
