### PR TITLE
Reduce default mouse key acceleration

### PR DESCRIPTION
**Pull request by filterpaper**
## Description

Default acceleration is a tad too fast. This change reduces it further; and document a few more mouse key config options.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by daskygit** [comment]
I don't know how I feel about updating mouse key defaults again, it seemed to cause a little hassle last time?

**Comment by filterpaper** [comment]
> I don't know how I feel about updating mouse key defaults again, it seemed to cause a little hassle last time?

This is just reducing the acceleration. Are you referring to the kinetic mode that took 2 tries?

**Comment by daskygit** [comment]
> > I don't know how I feel about updating mouse key defaults again, it seemed to cause a little hassle last time?
> 
> This is just reducing the acceleration. Are you referring to the kinetic mode that took 2 tries?
> 

Possibly, I just recall people coming into discord complaining their mouse keys don't function the same way as before.

**Comment by filterpaper** [comment]
> Possibly, I just recall people coming into discord complaining their mouse keys don't function the same way as before.

Pretty sure those were related to mouse key change reporting function. This is an innocuous edit to a default that was reported as too fast in discord.

**Pull request closed without merging**
