### PR TITLE
Updates send_string functionality, adds terminal feature

### PR DESCRIPTION
**Pull request by jackhumbert**
# `send_string` updates

`send_string()` has been moved to `send_string_P()`, where it accesses the strings from program space - `send_string()` now pulls from flash memory. The helper functions work similarly with `_P` - there's some redundancy here with the tap/down/up functionality, but that can be reworked in the future. `SEND_STRING()` is now a shortcut for the `_P` function, so nothing should break (I don't think anyone was using it directly).

With these changes, you can now enter any keycode into the function, like this:

    SEND_STRING(SS_TAP(X_HOME));

Which will tap (down & up) `KC_HOME`.

Keycodes have a `X_` prefix because of some pre-processor magic - these have different values than normal `KC_` keycodes, and not all keycodes were copied over (0 - 0x98 + mods), but all are one byte (< 256), which is what allows us to get away with this.

All current functions available are:

```
#define SS_TAP(keycode) "\1" SYMBOL_STR(keycode)
#define SS_DOWN(keycode) "\2" SYMBOL_STR(keycode)
#define SS_UP(keycode) "\3" SYMBOL_STR(keycode)

#define SS_LCTRL(string) SS_DOWN(X_LCTRL) string SS_UP(X_LCTRL)
#define SS_LGUI(string) SS_DOWN(X_LGUI) string SS_UP(X_LGUI)
#define SS_LALT(string) SS_DOWN(X_LALT) string SS_UP(X_LALT)
```

`SS_LCTRL` and similar functions act differently, and can take strings as arguments - I'm open to some naming suggestions here, for these functions, but also the `X_` prefix (this was chosen because it's the hex code without a `0x`).

These functions are a little odd syntactically, and can be combined/concat'd with literal strings, like this:

    SEND_STRING("no"SS_TAP(X_HOME)"oh");

Which makes things a bit easier when you wanna do everything all in one line.

# Terminal feature 

This is a fun little thing I was messing with, and the reason the send_string stuff happened - check out [the docs of it here](https://github.com/qmk/qmk_firmware/blob/fd4c5c669c16261f4cc610959aa9bef7f3a855df/docs/feature_terminal.md).

Some things worth talking about in the future:

* Keyboard/user-extendable commands
* Smaller footprint
* Arrow key support
* Command history
* SD card support
* LCD support for buffer display
* Keycode -> name string LUT
* Layer status
* *Analog/digital port read/write*
* RGB mode stuff
* Macro definitions
* EEPROM read/write
* Audio control

### CODE REVIEW

**Comment by Maartenwut** [comment]
Hi Jack, I really like the idea of a terminal for qmk. However, I'm getting some errors.

`> about
QMK Firmware
  va9014f-dirty
  Built: 2017-08-30-10:07:15
> keycode 0 1 1
command "keycode011"not found
> keymap 1
command "keymap1"not found
> exit`

**Comment by jackhumbert** [comment]
Ah, currently this only works with the basic keycodes - support for all of them is possible, but it might be kinda messy!

**Comment by Maartenwut** [comment]
That makes sense, because I have my space bar on LT(). KC_SPACE works at it should 👍

**Comment by WillEccles** [comment]
Today I have been messing with making the arrow keys work. Up/Down are very difficult to work with, so for the moment I haven't touched them, but I have added left/right support. They will work just fine so long as the user does not move the cursor using the mouse. I also added home/end support, so when they press "home," it moves to *after* the `> ` prompt, rather than before it.

The way I have implemented them is by using a cursor location integer, which corresponds to the index in the buffer that they want to type into. For example, when they type normally (i.e. don't use the arrow keys) they cursor location is always equal to `strlen(buffer)`, but when they use the left arrow, the location would be `strlen(buffer) - 1`. I also added a method to place a character in a string at whatever location is desired, rather than simply appending it (although it should work if you just want to append as well, but I have yet to test fully).

I am going to test this all tonight when I have access to my keyboard, but for the moment I have implemented these changes as they are now. After I confirm that they work, should I open a pull request (this would add my Preonic keymap as well)? I am trying to participate in Hacktoberfest and this seems to be the only open source project I care about, and the terminal feature could use some help 😄

**Comment by jackhumbert** [comment]
@WillEccles awesome! A PR would be great :)

**Comment by WillEccles** [comment]
Will test this weekend when I have a chance!

**Pull request merged**
