### PR TITLE
kint36: switch to sym_eager_pk debouncing

### PR DESCRIPTION
**Pull request by stapelberg**
## Description

This change shaves off ≈5ms of input latency by switching to eager debouncing.

Before:
```
% benchstat screenlog-kint36.0
name                 time/op
KeypressToLEDReport  7.61ms ± 8%
```

After:
```
% benchstat screenlog-kint36-eager.0
name                 time/op
KeypressToLEDReport  2.12ms ±16%
```

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Comment by badgersow** [comment]
I would like to comment on this, in case somebody googles the problem and ends up here.

I've soldered a Kint36 controller to my KB605 on a weekend and I've noticed that when I type, once in every couple minutes I'm having repeated key presses. For example when I type "of", the keyboard can receive "ofo". It's pretty hard to reproduce on purpose, but it happens regularily when I just type naturally. My typing speed is around 55-60WPM.

I've used Karabiner-EventViewer to monitor the keypresses on my macOS and the picture was something like:

```
o - down
f - down
o - up
o - down
o - up
f - up
```

I've seen it happening with different keys, so it shouldn't be a faulty switch. I've also never seen this problem with previous native Kinesis controller, so it's safe to assume the problem came with Kint36.

I've tried different things, but eventually I've set the debouncing algorithm to `sym_defer_g` and it helped. I've never seen a repeated keypress ever since.

Because this was my first soldering experience, it's very much possible that I've messed with something and made a bad soldering joint without understanding it. Maybe `sym_defer_g` is just masking the problem I've introduced with my expert soldering skills. Or maybe Kint36 really should have `sym_defer_g` in some cases. I don't know how to check this. I'm happy to do any experiments to get to the root of this problem, if there any suggestions about testing I can do (@stapelberg maybe you have any ideas on the top of your head). If not - that's also fine, because the controller seems to work perfectly with the new debouncing algorithm setting.

Still, if somebody else is in the same situation, I hope they will come to this PR and try what I did - this might save a lot of time.

**Comment by stapelberg** [comment]
Thanks for reporting this!

> I've tried different things, but eventually I've set the debouncing algorithm to `sym_defer_g` and it helped. I've never seen a repeated keypress ever since.

Alternatively, can you try `sym_eager_pk`, but increase https://github.com/qmk/qmk_firmware/blob/6bafefa88602c8032f6f861844ba0ac886d312a0/keyboards/kinesis/kint36/config.h#L54 from its default 5ms to, say, 20ms?

If that doesn’t help, perhaps it is time to implement `asym_eager_defer_pk`, as mentioned on https://beta.docs.qmk.fm/using-qmk/software-features/feature_debounce_type

**Comment by stapelberg** [comment]
> If that doesn’t help, perhaps it is time to implement `asym_eager_defer_pk`, as mentioned on https://beta.docs.qmk.fm/using-qmk/software-features/feature_debounce_type

I implemented debounce algorithm `asym_eager_defer_pk` in commit https://github.com/kinx-project/qmk_firmware/commit/335d80393c3f400aa4922a6d21a5f1f3176bd192 (branch https://github.com/kinx-project/qmk_firmware/commits/kint41-upstream-debounce). If you want to give that a shot (I’m testing it on my keyboard currently), please let me know how it goes!

**Comment by badgersow** [comment]
Thanks for letting me know. During the week I've played with the timeout on `eager_pk` and with the value of 30 milliseconds I don't see any problems. With 25 I still had very rare chatter (1-2 times per day).
To be honest, I don't know how to interpret that, because Cherry MX claims to have at most 5 ms of bouncing. There is also clearly not a problem with noise, because I'm getting repeated strokes, not just random keys. On the other hand, I know that Ergodox uses 30ms of eager debounce by default. It will be interesting to know what Kinesis Controller does by default.

> I’m testing it on my keyboard currently

Are you testing 5ms for asymmetrical algorithm? What previous timeout for `eager_pk` did you have on Kint 3.6?

**Comment by stapelberg** [comment]
> Thanks for letting me know. During the week I've played with the timeout on `eager_pk` and with the value of 30 milliseconds I don't see any problems. With 25 I still had very rare chatter (1-2 times per day).
> To be honest, I don't know how to interpret that, because Cherry MX claims to have at most 5 ms of bouncing.

Cherry’s claim seems to be overly optimistic indeed. In a different firmware project, I have previously bumped debounce time from Cherry’s 5ms claim to 10ms observed, then to 20ms as the key switches aged: https://github.com/kinx-project/mk66f-fw/commit/36f3df7f283b5a7af01602717e61cab0a764e8d6

> It is also clearly not a problem with noise, because I'm getting repeated strokes, not just random keys.

I think it is noise, but only for pressed keys. (They get detected as unpressed, then pressed, then unpressed, …)

> Are you testing 5ms for asymmetrical algorithm?

Yes, I’m currently testing with 5ms debounce time with `asym_eager_defer_pk`, and it seems to work well.

> What previous timeout for `eager_pk` did you have on Kint 3.6?

You can see the history at https://github.com/qmk/qmk_firmware/blame/master/keyboards/kinesis/kint36/config.h — we always defined DEBOUNCE as 5ms, just like most other QMK keyboards.

**Comment by badgersow** [comment]
I've just merged your branch to mine and compiled an asymmetrical algorithm. I'll try it over the week and let you know how it goes. 
I've also noticed commits to support Teensy 4.1 from you. When it is mostly working, if you need help with testing it, I'm happy to try it.

**Comment by badgersow** [comment]
As promised, status update from me.
I've been using this new debouncing setting for 2 weeks and I've bumped it to 20ms eventually. I've also tried `sym_defer_g` with 5ms and quickly realized that I need to bump the timeout as well.
So, the conclusion is that I don't have a problem with algorithm, I have a problem with small timeout and the value 20-30ms seems to work fine for me for every algorithm I've tried.

**Comment by stapelberg** [comment]
Thanks for reporting back! I’ll send PRs to increase the debounce value to 20ms.

Out of curiosity, how many years old are the Cherry switches on your board?

**Comment by badgersow** [comment]
Thanks for doing this. 

> Out of curiosity, how many years old are the Cherry switches on your board?

I've bought the new keyboard and have been using it for 3 years. Sticker on the bottom says 2016, but I don't know if that means it was assembled in 2016 or not.

**Pull request merged**
