### PR TITLE
Improve new_keymap.sh in the style of new_keyboard.sh

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Like #5191, but for generating a new keymap.

@orngshdw

```
$ ./util/new_keymap.sh
Generating a new QMK keymap

Keyboard Name: wasdat
Keymap Name [fauxpark]: 

Copying default keymap to fauxpark... done

Created a new keymap for wasdat called fauxpark.

To start working on things, cd into keyboards/wasdat/keymaps/fauxpark,
or open the directory in your favourite text editor.

Compile a firmware file with your new keymap by running:
    make wasdat:fauxpark
from the qmk_firmware directory.
```

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
@ymzcdg can you make sure that my changes to the zh-cn docs still make sense to you? 😆

**Comment by yanfali** [comment]
Thanks for doing this, but I question how much more we should invest in shell now we have python.

**Comment by fauxpark** [comment]
Is this useful/necessary anymore, now that #6066 is in?

**Comment by skullydazed** [comment]
I don't think so. I think our long march of removing things from `util/` has started now.

**Comment by fauxpark** [comment]
I was hoping to keep my current purple streak, but ah well 😁

**Pull request closed without merging**
