### PR TITLE
[Core] Unite half-duplex and full-duplex serial drivers

### PR DESCRIPTION
**Pull request by KarlK90**
## Description

So this is a follow-up on #9842 with a plot twist as it removes the DMA backed full duplex driver and adds the full duplex functionality to the existing interrupt based driver. There are multiple reasons for this change:

1. The DMA based driver was faster than the existing half-duplex driver, but wasn't actually faster than a full duplex driver backed by interrupts. The biggest overhead comes from clearing the input queues, after sending on the half-duplex I guess.
2. The original DMA driver hadn't any flow control, so possible baud rates without timeouts are tightly coupled to optimization levels and the both halves reacting to transactions at the same pace. I extended the driver to use a state machine and software flow control in [my personal repo](https://github.com/KarlK90/qmk_firmware/blob/76326e3cad8606a03a487156a69cd3f838ffc48a/drivers/chibios/serial_usart_duplex.c). This solved this problem, but this driver is **much more** complex.
3. Even the extended driver is a bit slower than the full duplex interrupt based driver. So there are no benefits left using the DMA backed one. QMK is mostly single threaded at this point and the transactions sizes are a couple of bytes (the biggest being the matrix), so DMA doesn't offer anything at this point. 
4. The driver straight-out didn't work on the djiinn by @tzarc for unknown reasons and it uses DMA channels which could lead to conflicts, especially for people building boards and not having the deeper embedded knowledge about DMA conflicts.

The benefits of this Implementation:

1. Faster than the DMA full duplex driver.
2. Maintainable.
3. Better compatibility with MCUs.
4. It targets #11930 by default.

Tested on GD32VF103 and STM32F303 in both half-duplex and full-duplex configuration.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* none

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Targets #11930 -- might end up cherry-picking it into that PR, given the prerequisite.

**Comment by KarlK90** [comment]
I was able to save quite a few cycles for the half-duplex implementation by discarding the bytes from the input queue after transmitting without actually [reading them back](https://github.com/qmk/qmk_firmware/blob/9d205a7a4eb757d51aa93935f98a17d9f6a64b18/drivers/chibios/serial_usart.c#L41-L78). Also sdClear ([which is now called usart_reset](https://github.com/qmk/qmk_firmware/blob/9d205a7a4eb757d51aa93935f98a17d9f6a64b18/drivers/chibios/serial_usart.c#L111-L119)) is only called in case of transmission errors and hard resets the input queue. With these changes the full-duplex and half-duplex driver are within a few hundred matrix scans, full-duplex still being slightly faster.

**Comment by firetech** [comment]
Responding to a comment from #13089 (that's more relevant here). Main topic is the [custom serial driver](https://github.com/firetech/qmk_firmware/blob/ergodox_infinity_split_common/keyboards/ergodox_infinity/serial_daisy_usart.c) I implemented for porting Ergodox Infinity over to using split_common.

> From what I see in your code the serial_config, assigned serial driver and some hooks into the side specific init code would have to be configurable right? Feel free to chime in the serial PR :-)

@KarlK90 I think that's about it. I think the assigned serial driver is already configurable, but the Ergodox Infinity is a bit special since it uses one U(S)ART port for the master and a different from the slave (in theory allowing "infinite" daisychaining). A separate define (e.g. `SERIAL_USART_SLAVE_DRIVER`) that is set to `SERIAL_USART_DRIVER` by default would solve that issue, though.

The initialization code in my driver is taken directly from the corresponding code in serial_link (currently only used by Ergodox Infinity), not entirely sure what it actually does. :P

**Comment by KarlK90** [comment]
So I just pushed some changes that make the driver much more configurable and STM32 independent.

* The serial driver is now assignable and not a fixed constant. So re-assignable from init code.

```c
static SerialDriver* serial_driver = &SERIAL_USART_DRIVER;
```

* For side specific initializations overrideable weak defined hooks exist, e.g. here you can assign a different serial driver.

```c
/**
 * @brief Overridable master specific initializations.
 */
__attribute__((weak)) void usart_master_init(void) { usart_init(); }

/**
 * @brief Overridable slave specific initializations.
 */
__attribute__((weak)) void usart_slave_init(void) { usart_init(); }

```

* For a non standard serial config just define SERIAL_USART_CONFIG and this will be used.

```c
#if defined(SERIAL_USART_CONFIG)
static SerialConfig serial_config = SERIAL_USART_CONFIG;
#else
static SerialConfig serial_config = {
    .speed = (SERIAL_USART_SPEED), /* speed - mandatory */
    .cr1   = (SERIAL_USART_CR1),
    .cr2   = (SERIAL_USART_CR2),
#    if !defined(SERIAL_USART_FULL_DUPLEX)
    .cr3   = ((SERIAL_USART_CR3) | USART_CR3_HDSEL) /* activate half-duplex mode */
#    else
    .cr3 = (SERIAL_USART_CR3)
#    endif
};
#endif
```

**Comment by firetech** [comment]
> * The serial driver is now assignable and not a fixed constant. So re-assignable from init code.
> 
> ```c
> static SerialDriver* serial_driver = &SERIAL_USART_DRIVER;
> ```

In practice, since that is a static variable, can I really change its value from code outside that file? 🤔

**Comment by KarlK90** [comment]
You're right I have dropped the static qualifier. Maybe QMK standard :stuck_out_tongue:

**Comment by firetech** [comment]
> You're right I have dropped the static qualifier. Maybe QMK standard 😛

Another solution would have been to send a pointer to the variable as an argument to `usart_master/slave_init`, i.e. `void usart_master_init(SerialDriver** driver)`. 🤷

**Comment by firetech** [comment]
So, I've gotten this to work on Ergodox Infinity now. Prototype code [here](https://github.com/firetech/qmk_firmware/tree/usart_test).

However, due to incompatible code in `usart_init` (even though it's overwritten elsewhere), it still doesn't compile for K20x unless I comment out the `palSetLineMode` calls in `usart_init`. Some more `#define` magic is needed there for full compatibility...

Also, I realized I also added [some code] (https://github.com/firetech/qmk_firmware/commit/1c27092cffb1fbb88dfc61d04d4efd609837ff76) to my custom serial driver to make it possible to use a master half without a slave connected (since the constant wait for serial read timeout make the scan rate unusably slow otherwise). I would not at all call it perfect, but with `SERIAL_USART_TIMEOUT` set to 50, I don't really notice any missed keys while typing _very_ fast (`get_current_wpm` reported well over 200 "WPM" of ordered nonsense).

Not sure how relevant that feature is, it's definitely not a requirement. I partly implemented it for fun, and partly because I thought more than once that the firmware was broken while porting Ergodox Infinity to split_common (the Infinity uses the same USB-C/micro B port for USB input from host to master and serial input from master to slave, so you need to disconnect the slave from the master to be able to flash the slave, making disconnects a bit more common than for other split boards).

**Comment by KarlK90** [comment]
Alright, I guarded that stm32 specific init code behind a define and added a info message about the necessity to init the pins yourself. In the future this can be expanded to support specific ports like Kinetis quite easily.

The driver is now static again and the side specific init functions get a pointer passed to it.

**Comment by firetech** [comment]
> The connect/disconnect feature is really cool, but IMHO should go in a more universal spot. I think the scan logic would be a good fit as it already has a error [disconnect counter](https://github.com/firetech/qmk_firmware/blob/firetech/quantum/split_common/matrix.c#L259-L282).

I think the main issue is that there are often more than one transaction per scan cycle (for LED/RGB Matrix, WPM, etc.), and I think stopping all of them would be quite messy if not done somewhere within the actual transport/transaction code (i.e. in `transport_execute_transaction` or the functions it calls).

> Do the changes fix your compile issues? Haven't tested with a real compilation on non stm32 platforms.

Haven't tried yet, but it looks like they should. I'll try it out later today or during the weekend.

**Comment by KarlK90** [comment]
This is my attempt to [support disconnected peripheral sides.](https://github.com/KarlK90/qmk_firmware/commit/b2c3e8c5d50e6d86a858fbfb1712aac9592773eb). But you are right, this should probably set a global flag and stop all transactions regardless where they are started from. I also think that could be done in a rather clean way, should attempt that after the split transactions PR is merged.

The other reason why I'm opposed to do this in the driver is that this would have to be done for all drivers like serial and i2c which is duplicated efforts as well and it is in the hot-path of the application which should do as little logic as possible. :thinking:

**Comment by firetech** [comment]
> The other reason why I'm opposed to do this in the driver is that this would have to be done for all drivers like serial and i2c which is duplicated efforts as well and it is in the hot-path of the application which should do as little logic as possible. 🤔

That is a good point. I didn't think that much about where it should be implemented since I put it in a completely custom driver when I came up with it.

It might be an idea to implement it in a driver-independent wrapper around `transport_execute_transaction` (also known as `transport_read` and `transport_write`). Then it should affect all transactions (including RPC) in any driver, right?

**Comment by KarlK90** [comment]
> It might be an idea to implement it in a driver-independent wrapper around transport_execute_transaction (also known as transport_read and transport_write). Then it should affect all transactions (including RPC) in any driver, right?

Sounds good! And maybe that is the perfect time to summon the djinn aka. @tzarc and hear what he has to say about it :stuck_out_tongue:.

**Comment by firetech** [comment]
> Do the changes fix your compile issues? Haven't tested with a real compilation on non stm32 platforms.

Tried it out now, compiles fine :) Code [here](https://github.com/firetech/qmk_firmware/commit/usart_test).

However, I have two issues now:
1. For some reason, my patch to make a master half usable on its own makes the slave half unusable with your recent patches. Not that of a big deal, since we've already established that it wasn't implemented in the best of places.
2.  More seriously, I noticed missed keystrokes (with the halves connected), and after enabling debugging, I'm seeing quite a lot of failed handshakes... ☹️ It appears to work at first glance, but maybe 1-2% of keystrokes are being missed, on both halves.

**Comment by KarlK90** [comment]
Could you [revert the unconditional clearing](  https://github.com/qmk/qmk_firmware/pull/13081/commits/cefc73a50a01f014386f0a1e2896afa98f5e071) and see if the issue persists? Also try lowering the usart speed.

**Comment by KarlK90** [comment]
Before I push the changes you can try the changes from [this branch](https://github.com/KarlK90/qmk_firmware/commit/d881e4ceb8a9f5d2824da6c096a3649774487f67).

**Comment by firetech** [comment]
> Before I push the changes you can try the changes from [this branch](https://github.com/KarlK90/qmk_firmware/commit/d881e4ceb8a9f5d2824da6c096a3649774487f67).

That commit seems to have solved both my issues. 👍

**Comment by KarlK90** [comment]
Perfect, applied the changes and pushed them.

**Comment by KarlK90** [comment]
Squashed and pushed. From my side ready for review.

**Review by tzarc — APPROVED** [review]

**Comment by daskygit** [comment]
I'm having issues with this freezing the master side of my keyboard which appears to happen at random. I'm using a STM32G483 and half duplex. I had it freeze with hid_listen open and no further messages appeared.

I've pinged KarlK90 on discord so sorry for the double notification.

**Comment by drashna** [comment]
For reference: 
https://discord.com/channels/440868230475677696/440868230475677698/855448515295576094

**Comment by KarlK90** [comment]
With the latest the commit the freezes that @daskygit had with this driver in half-duplex mode should be fixed. I also increased the default TX/RX buffer size for the serial driver to 128 bytes per buffer to have some head space for larger transactions.

# Background

After an extensive debugging session it became clear that the clearing of the input queue in half-duplex mode was the root cause. The assumption that every byte that was send will also be present in the input queue was wrong. Under the right circumstances (e.g. bad cables paired with high baud rates) less bytes are present in the input queue, which traps the master half in a while loop waiting for more bytes. Therefore a timeout is strictly needed to guard against this possibility. 

I bench marked possible implementations with timeouts against the non-timeout `usart_discard_bytes` function and came to the conclusion that the overhead added by the unnecessary `memcpy` calls in `sdReadTimeout` isn't worth maintaining a solution without them. So `usart_discard_bytes` is just replaced with `receive`.

# Performance Benchmarks (Matrix scans per second.)

* MCU: STM32F303
* YAEMK Keyboard
* RGB-Matrix, Encoders etc. enabled.
* USB-C Cables for split communication
* @2.25MBit baud rate
* 1.82K Pull-up resistor for half-duplex.

## Half-Duplex

| method                                               | `-Ofast -flto` | `-Os -flto` |
| ---------------------------------------------------- | -------------- | ----------- |
| vanilla `sdReadTimeout`                              | 6204           | 5113        |
| modified `sdReadTimeout` without `memcpy` calls.     | 6264           | 5245        |
| `usart_discard_bytes` without any timeout mechanism. | 6301           | 5250        |


## Full-Duplex

| `-Ofast -flto` | `-Os -flto` |
| -------------- | ----------- |
| 6416           | 5333        |

**Comment by daskygit** [comment]
It's been a couple of days now using the suggested fix above without any freezing, only managed maybe an hour before freezing without the fixed code.

Thanks for the prompt fix.

**Comment by KarlK90** [comment]
That is great to hear! 🙂

**Review by XScorpion2 — APPROVED** [review]

**Pull request merged**
