### PR TITLE
Fix installation for Linux Fedora

### PR DESCRIPTION
**Pull request by miguelgr**
Changed `grep` command in installation script to match Fedora in `/etc/os_release`

### CODE REVIEW

**Comment by Erovia** [comment]
RHEL and its derivatives still use the `yum` package manager.
`dnf` is Fedora-only for now.

It would also be worth to check if all these packages are available in the standard RHEL/CentOS/etc repositories or a 3rd party one (like EPEL) needs to be enabled first.

**Comment by miguelgr** [comment]
@Erovia I just added the check for fedora, but I agree about dnf use.
Maybe we should split that check in two and use yum & dnf?

PS: I had no problems downloading the packages via dnf.

**Comment by Erovia** [comment]
I think we have to decide first, if the script should support RHEL and its derivatives.

I've just tested it on both a fresh install of RHEL7.5 and CentOS7.5 and the following packages are not available: `dfu-util, dfu-programmer, avr-gcc avr-libc, binutils-avr32-linux-gnu, arm-none-eabi-gcc-cs, arm-none-eabi-binutils-cs, arm-none-eabi-newlib`.
Sadly, they are not even present in EPEL or ElRepo.

**Comment by skullydazed** [comment]
Thanks!

If someone wants to go through the working of making RHEL work with this script we'd love to accept it. In the meantime I don't see any reason to hold back fedora users.

**Pull request merged**
