### PR TITLE
RGB Matrix Support for Split Keyboards

### PR DESCRIPTION
**Pull request by Gansgar**
This is an advancement from #5998 
The idea is to implement the rgb matrix module for split keyboards, as it is currently missing.

## Description

This is some basics to get RGB matrix support onto split keyboards. The main change of idea between this and #5998 
is, that this feature line does not enable keyboard evaluation on the slave side, but instead the config is always synced from master to slave only if changes occur. (very similar to how the RGB lighting module works). 
As such both keyboards cannot get out of sync, has it can happen on #5998.

For interactive animations, the state of the master is transferred to slave, but only rgb matrix specific functions for keyboard evaluation are triggered. 

- rgb matrix config is synced between both halves  
- `timer.c` is now sync'd between halves
- Small changes to RGB Matrix to know what indexes apply to which half.
- introduction of Lily58l keyboard as it is the one I'm working with (see https://github.com/BenRoe/qmk_firmware/tree/Lily58L as he's the original author)
- "fixed" bug, where Elite-C flash failed, even though it worked. Probably my fault 

### Still to do

- [x] suspend isn't synced
- [ ] a interactive effect triggered from the slave takes longer to get to the master side, than when an effect that is triggered on the master is transferred to the slave. But this effect is for me only visible, when `LT(_LOWER, KC_BSPC)` was used. (an LT modifier on master side doesn't seem to be so problematic)
- [ ] i2c testers as I can only test it with a serial connection
- [ ] As of now `timer.c` is synced with an static offset to account for transfer delay. If issues occur it might be more plausible to implement a real timer sync protocol similar to [Cristian's Algorithm](https://en.m.wikipedia.org/wiki/Cristian%27s_algorithm)
- [x] Split common also syncs master half matrix to slave, this allows slave to know the state of the keyboard
  - [x] transfer of keyboard state to `rgb_matrix` on slave side
- [x] doesn't compile with `make all` as definitions from `sync_timer` weren't found  

### Known issues
- LT(layer, kc) with KC_CAPS causes reactive animation stutter. This is because it has an inline wait_ms(200). Not much can be done to improve this situation as it hard locks all processing of the keyboard. (maybe. Didn't test it)

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* a lot

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by XScorpion2** [comment]
Good first start, but there is a reason why the slave half needs to enable keyboard evaluation which is reactive rgb matrix animations. With out that hook, the reactive effects will not work, and I don't see anything in this PR to improve that.

**Comment by Gansgar** [comment]
I'll sync the states and directly tap into `rgb_matrix` to sync the states circumventing all other methods that are normally called

**Comment by XScorpion2** [comment]
Thanks for taking this over. RL has been a major issue lately for me.

**Comment by Gansgar** [comment]
You're welcome. I'm happy to take this over. First mayor contribution to an OS project for me. 

I'm also really lucky that the whole situation rn hasn't affected me really at all. Wishing you the best!

**Comment by Gansgar** [comment]
Works now, but I'm unhappy with the solution, as keypress evaluation is turned on.

**Comment by rhruiz** [comment]
common split code already has a check for `RESET`. Keypress evaluation on the slave side has a nice benefit of allowing things like making the slave OLED react to layer change and keypresses (this works in #5998)

**Comment by Gansgar** [comment]
But `RESET` is not the only problem. As for now the slave side also does evaluation of RGB MATRIX commands. That is a very dirty approach especially, since the slave side config is overwritten in the next frame. Using EEPROM cycles, ...

**Comment by Gansgar** [comment]
Thanks to @sigprof I found a solution that works nicely. Sadly slave still can't show the current layer information

**Comment by Gansgar** [comment]
It's now working as expected. There are only some major problems with the design and how future proof it might be.

**Comment by tzarc** [comment]
This needs to be retargeted to `develop`, but should only be done once `master` is merged into `develop`, otherwise there are over 450 files changed.

**Comment by Gansgar** [comment]
Please see #9619 for general issue for the problem

**Comment by drashna** [comment]
> But to my understanding #5998 has a lot bugs, because of slave side keyboard evaluation.

It's less of that. But it's a lot of changes.  

Additionally it's missing some things like state syncing, so it's always sending the matrix code. 

Breaking up the PR into chunks (like the sync timers) would make it easier to get merged in, as it would be easier to review, which would make it faster to get in.

**Comment by Gansgar** [comment]
Okay. Didn't opened an issue for the sync timer yet, if people wanted to suggest a radically different way for this.

**Comment by tzarc** [comment]
Looks like we're going to need a rebase on top of `develop` -- lots of irrelevant changes here.

**Comment by Gansgar** [comment]
Whatya mean? My idea honestly was to do #9665 first from a clean slate on (develop branch). I know what to change and it isn't much. My troubles are:
a) I'd like some feedback on it before delving into it 😅
b) I've exams and other time sensitive stuff in the next 1½ months (after that I'm fine)

**Comment by KarlK90** [comment]
I am running your code successfully on my split keyboard. Communication is via serial link on an stm32f103. Please let me know if I can help testing the changes. :slightly_smiling_face:

**Comment by tzarc** [comment]
> 
> 
> Whatya mean? My idea honestly was to do #9665 first from a clean slate on (develop branch). I know what to change and it isn't much. My troubles are:
> a) I'd like some feedback on it before delving into it 😅
> b) I've exams and other time sensitive stuff in the next 1½ months (after that I'm fine)

Yeah that's fine - it's more that in this PR's files list above, it's got tons of changes from the branch which isn't part of your PR.
Rebasing the changes to the top of `develop` will make it so that there's only the appropriate changes here.

But... if you're going to refactor with a clean slate, then I'll mark this as "on hold" until #9665 and any other prerequisites are sorted.

**Comment by robhaswell** [comment]
I can confirm this is working great with my Lily58L.

Also I noticed that this branch includes Lily58L support, which is strictly beyond the scope of this branch. I will submit a PR for basic Lily58L support with RGBLIGHT, at least then the matrix modifications in this branch for the keyboard will be relevant.

**Comment by XScorpion2** [comment]
Should be closed for the updated pr: https://github.com/qmk/qmk_firmware/pull/11055

**Pull request closed without merging**
