### PR TITLE
Generate version.h during CI instead of compile time

### PR DESCRIPTION
**Pull request by skullydazed**
## Types of Changes

- [x] Core
- [x] Enhancement/optimization

## Checklist

- [x] My code follows the code style of this project.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
> I am not entirely sure that this is a good idea. I rely upon being able to unambiguously determine the code base that was used to generate a particular firmware (and I've added code so that I can always interrogate the keyboard for that information). If QMK_VERSION now only contains a CI-generated version number, that will no longer work.

The problem with that, is that if you don't update your local branch correctly, it can be missing tags, which means that the version number may be wrong *anyways*.   And that's not uncommon.

**Comment by spidey3** [comment]
> The problem with that, is that if you don't update your local branch correctly, it can be missing tags, which means that the version number may be wrong _anyways_. And that's not uncommon.
That's true, but I have to say that as a developer I really don't care about the tag, it's just noise (but I'm willing to hear arguments to the contrary). What matters to me is which commit I compiled to get this firmware, and the tag doesn't tell me that.
 
I think the best solution here is to provide both — the generated tag, and also the git hash.

**Comment by tzarc** [comment]
I'd unequivocally say this is a _bad idea_.
During the ChibiOS upgrade cycle, I was providing binaries that were based off non-CI revisions of submodules.
Should builds such as these be providing out-of-date information? What about branch builds?

In the case of the upgrades, the following would be showing what's currently on master regardless of any revision updates that have been put in place:
```c
#ifdef PROTOCOL_CHIBIOS
    print("CHIBIOS: " STR(CHIBIOS_VERSION) ", CONTRIB: " STR(CHIBIOS_CONTRIB_VERSION) "\n");
#endif
```

I really do not see the benefit of this.

**Comment by skullydazed** [comment]
I just talked with @tzarc about this on discord and wanted to jot down some thoughts from that discussion.

One of the driving factors here is how long it takes to generate this information dynamically. We want to use it in the CLI, but sometimes it can take many seconds for the git commands to run, particularly when using docker volumes. (Like when doing API development.) By generating this information at CI time we can effectively use it in the CLI and other latency sensitive places.

There is concern that generating the submodule information could lead to out of date information being reported. For example, if someone changes the chibios submodule but doesn't update version.h. We talked about the possibility of having a version.h specific to each submodule. We also talked about the possibility of removing the submodule version information entirely.

Speaking to @spidey3's use case we think getting only the current git hash of qmk_firmware should be cheap, as long as we don't care about dirty state. This would allow us to provide that dynamically, possibly by passing `-DQMK_GIT_HASH=${CALCULATED_HASH}` at compile time. That would have the (beneficial?) side effect of invalidating gcc's cache and forcing a clean build after every commit. It's still an open question as to how critical identifying a dirty tree is to this use case.

**Comment by spidey3** [comment]
Can we do the full check (including dirty status) when compiling, but skip checking the dirty state in the "latency sensitive" cases?

**Comment by skullydazed** [comment]
That's a good question and brings up a point I forgot to include. One of the possibilities we talked about was having an environment variable you could set to do the full check, for people who want that dirty check.

**Comment by spidey3** [comment]
Could this be a configuration option in the cli, rather than an envar? Just as we can set the user.keyboard and user.keymap?

**Pull request closed without merging**
