### PR TITLE
Align ATSAM HID descriptors with LUFA/ChibiOS

### PR DESCRIPTION
**Pull request by fauxpark**
## Description
Should be no behaviour changes. I fixed the raw HID descriptor to have the correct usage page and usages, but since there is no raw HID implementation for ATSAM yet anyway, we don't need to worry about it breaking anything.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by yanfali** [comment]
@fauxpark can we get someone with the actual hardware to test this please? I don't feel comfortable changing this without an actual hardware test. @XScorpion2 @MatthewRobo if you have time and inclination?

**Comment by fauxpark** [comment]
@ash0x0 can also test.

**Comment by ash0x0** [comment]
yeah, let me pull and test

**Comment by ash0x0** [comment]
Everything works fine, tested again with the latest commit. Console, Terminal, Keycodes, Status LEDs (The ones I have on the ctrl), Modifiers, System control, everything fine and no issues with either the default keymap or my keymap.

**Pull request merged**
