### PR TITLE
add folders and capsule65

### PR DESCRIPTION
**Pull request by EasonQian1**
add folders and capsule65

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — CHANGES_REQUESTED** [review]
Files have been added to the wrong location, and not to the `keyboards` folder.

**Comment by drashna** [comment]
Duplicate of #16608, #16609, #16613, and #16613.

Please stop closing and opening new PRs for the same code changes

**Comment by EasonQian1** [comment]
> Duplicate of #16608, #16609, #16613, and #16613.
> 
> Please stop closing and opening new PRs for the same code changes

Sorry, I don't know much about the rules. The previously submitted library has been deleted and cannot be resubmitted.

**Comment by fauxpark** [comment]
If you need to make further changes, you can simply commit and push to the same branch, and the PR will be updated.

**Comment by EasonQian1** [comment]
> If you need to make further changes, you can simply commit and push to the same branch, and the PR will be updated.
Sorry, the previous branch was accidentally deleted and can only be resubmitted

**Review by zvecr — CHANGES_REQUESTED** [review]
Will render on Configurator badly.

**Comment by EasonQian1** [comment]
> Will render on Configurator badly.
> 
> ```
> Layout Layout:
> ┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐
> │K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0│
> └──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘
> ┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐    ┌──┐
> │K1││K1││K1││K1││K1││K1││K1││K1││K1││K1││K1││K1││K1││K1│    │K1│
> └──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘    └──┘
> ┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐        ┌──┐
> │K2││K2││K2││K2││K2││K2││K2││K2││K2││K2││K2││K2││K2│        │K2│
> └──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘        └──┘
> ┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐    ┌──┐
> │K3││K3││K3││K3││K3││K3││K3││K3││K3││K3││K3││K3││K3││K3│    │K3│
> └──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘    └──┘
> ┌──┐┌──┐┌──┐        ┌──┐            ┌──┐┌──┐┌──┐┌──┐┌──┐    ┌──┐
> │K4││K4││K4│        │K4│            │K4││K4││K4││K4││K4│    │K4│
> └──┘└──┘└──┘        └──┘            └──┘└──┘└──┘└──┘└──┘    └──┘
> ```

I don't know what to do, can you tell me thanks

**Comment by EasonQian1** [comment]
> Will render on Configurator badly.
> 
> ```
> Layout Layout:
> ┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐
> │K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0││K0│
> └──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘
> ┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐    ┌──┐
> │K1││K1││K1││K1││K1││K1││K1││K1││K1││K1││K1││K1││K1││K1│    │K1│
> └──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘    └──┘
> ┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐        ┌──┐
> │K2││K2││K2││K2││K2││K2││K2││K2││K2││K2││K2││K2││K2│        │K2│
> └──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘        └──┘
> ┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐    ┌──┐
> │K3││K3││K3││K3││K3││K3││K3││K3││K3││K3││K3││K3││K3││K3│    │K3│
> └──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘    └──┘
> ┌──┐┌──┐┌──┐        ┌──┐            ┌──┐┌──┐┌──┐┌──┐┌──┐    ┌──┐
> │K4││K4││K4│        │K4│            │K4││K4││K4││K4││K4│    │K4│
> └──┘└──┘└──┘        └──┘            └──┘└──┘└──┘└──┘└──┘    └──┘
> ```

Changed, please review, thank you

**Review by drashna — APPROVED** [review]

**Review by Erovia — APPROVED** [review]

**Pull request merged**
