### PR TITLE
[Core] [Bug] Keycode MIDI fix up missing commas

### PR DESCRIPTION
**Pull request by Xelus22**
## Description

Fix up missing commas in MIDI keycode file

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fix up missing commas in MIDI keycode file

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
As we use hjson, this change isn't strictly required.

**Review by fauxpark — APPROVED** [review]

**Comment by Xelus22** [comment]
i would personally prefer if we could parse this with a normal json parser without external libraries so that we can easily convert for VIA and other libraries easily.

**Comment by zvecr** [comment]
Then you should be fetching <https://keyboards.develop.qmk.fm/v1/constants/keycodes_0.0.1.json> instead rather than the raw files.

**Comment by Xelus22** [comment]
oh ok thanks i didn't know these were being hosted and could be fetched this way. Thanks!

**Pull request closed without merging**
