### PR TITLE
Fix pressing two keys with the same keycode but different modifiers

### LINKED ISSUE #1708: Rollover 'delayed' when pressing both unshifted and shifted keycodes at the same time
I have both `=` and `+` bound to seperate keys in my keymap. When I first press one of them, then press the other while the first key is still being held, the second keypress does not register.
If I press the second key a second time (or keep holding it) while the first key is still being pressed, then those presses are registered.

I found this behaviour while typing `+=`. Apparently I often still have my finger on `+` while already typing the `=`. I would expect to immediately get the `=` like it is the case with other keys.

This also happens with other keycodes that are basically shifted/unshifted versions of the same key, such as `{` and `[`.

### PR DESCRIPTION
**Pull request by fredizzimo**
Fix #1708

When two keys that use the same keycode, but different modifiers were pressed at the same time, the second keypress wasn't registered. This is fixed by forcing a key release when we detect a new press for the same keycode.

**Note** that this might have some unforseen consequences. If that's the case we can enable/disable this behaviour with a define. But so far I haven't thought of anything, so I rather enable it completely, than having too many confusing configuration options.

### CODE REVIEW

**Comment by drashna** [comment]
Looks like this has a merge conflict now.

**Comment by skullydazed** [comment]
Once the merge conflict is fixed this looks good to merge

**Comment by raetiacorvus** [comment]
Any chance that this could be looked at again? Using this PR now for a week without any problems and it allows me to drop my personal buggy workaround for this issue.

**Comment by drashna** [comment]
It looks like there are a couple of merge conflicts here, and just some minor ones. 

If these could be cleaned up?

**Comment by oberien** [comment]
@fredizzimo Are you planning on updating this PR to fix the merge issues?

**Pull request merged**
