### PR TITLE
Whitefox refactor

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

* Removed custom matrix (looks to be much the same deal as the K-Type)
* Added community layout support (`65_ansi_blocker_split_bs` is missing)
* General code tidyup

Compiles, but as I don't have the hardware (just going off of the schematics), testers would be appreciated. Haven't touched the visualizer/3731 LED matrix stuff just yet.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
@vomindoraan @jetpacktuxedo @dudeofawesome you appear to have keymaps for this board, mind testing this out?

**Comment by fauxpark** [comment]
Travis error unrelated (community layouts again).

**Comment by jetpacktuxedo** [comment]
I sold my whitefox about a year ago, so I don't have hardware to test with either unfortunately 😕

**Comment by fauxpark** [comment]
@vomindoraan @dudeofawesome friendly ping :)

**Comment by albertogg** [comment]
@fauxpark yes, I do have it.

**Comment by belak** [comment]
Yes, this is my daily driver. I'll try to test later today, though I don't have any LEDs.

I've actually got 2 revisions, so that may be helpful.

I think this was a direct port from TMK, hence the custom matrix, but I don't remember for sure - it was quite a while ago.

**Comment by belak** [comment]
Everything I've tested so far works well, at least on my main USB-C Whitefox. Unfortunately, I sold my original micro-usb one with the LEDs, so I can't test that revision.

Is there a reason you renamed the layouts, specifically in the json? That would be way more confusing, at least for me since I know I have the True Fox, not the 65% ANSI Blocker Split Backspace.

**Comment by noroadsleft** [comment]
> Is there a reason you renamed the layouts, specifically in the json? That would be way more confusing, at least for me since I know I have the True Fox, not the 65% ANSI Blocker Split Backspace.

@belak, The rename enables the Whitefox to use the [Community Layouts feature](https://docs.qmk.fm/#/feature_layouts), and the old layout names are present [at the bottom of the header file](https://github.com/fauxpark/qmk_firmware/blob/fcd7354d59d75be5eaf684f5fa85204073714d48/keyboards/whitefox/whitefox.h#L234-L238). You'll be able to use the old names as long as those definitions are present.

**Comment by belak** [comment]
Ah, got it, that works. Thanks for clarifying.

**Comment by fauxpark** [comment]
As I mentioned, I didn't touch the Visualizer stuff except to clean it up a little, so there should be no issues there, and this can probably be merged.

**Comment by albertogg** [comment]
@fauxpark I just tested this for the vanilla layout (LAYOUT_65_ansi) and it works. Unfortunately I don't have LEDs in my keyboard so I can't help you with that!

**Review by tzarc — APPROVED** [review]

**Comment by ToyKeeper** [comment]
This is working nicely on my Whitefox.  However, I don't have LEDs in mine, so I can't test that.

The only thing I've noticed which doesn't seem to work correctly is the RESET button.  It doesn't put the Whitefox into a state where it can be reflashed.  It's detected as being in a flashable state, but flashing fails...  so I have to use a paperclip on the bottom of the board instead.

Also, if I don't disable the visualizer in rules.mk, it gets a compile error.  My layout is in a [fork](https://github.com/ToyKeeper/qmk_firmware/tree/add-tk-whitefox/keyboards/whitefox/keymaps/toykeeper) in case it helps to see the sources.

```
lib/ugfx/src/gdisp/gdisp.c: In function '_gdispInit':
lib/ugfx/src/gdisp/gdisp.c:566:4: error: useless type name in empty declaration [-Werror]
    extern GDISPVMTLIST        GDISP_DRIVER_LIST;
    ^~~~~~
```

This might be why whitefox builds are currently failing in the configurator.

**Comment by L-A** [comment]
Chiming in super late to confirm that LEDs are working fine on a micro-USB Whitefox! The layout is ISO, which also works well.

**Pull request merged**
