### PR TITLE
Added an alternative way to check if half is master

### PR DESCRIPTION
**Pull request by Duckle29**
## Description

This change determines if a half of a split keyboard is the master half, by checking if it's been enumerated, or if it's been contacted by another master half.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
@nooges @mtei @pelrun  Could you double check this?

**Comment by drashna** [comment]
@nooges @mtei @pelrun  Could you double check this?

**Comment by Duckle29** [comment]
This does not currently work. I pushed this too fast. I'll look into getting this working, and will comment when it does

**Comment by Duckle29** [comment]
I'm closing this PR as there were way too many changes to be made to implement this. I'll leave my rev1 on my custom split implementation, and write rev2 for split_common

**Pull request closed without merging**
