### PR TITLE
YMD96 refactor

### PR DESCRIPTION
**Pull request by noroadsleft**
Goal: bringing the YMD96 codebase up to modern standards and add layout support to QMK Configurator.

### CODE REVIEW

**Comment by noroadsleft** [comment]
@harshitgoel96 Near as I can tell, your keymap (as it's checked in to QMK's master) doesn't have any way to access the `_RAISE` layer. You have a keycode assigned for it, but it seems [the layout macro locks it to `KC_NO`](https://github.com/qmk/qmk_firmware/blob/23086808a78c9234232e2ddbf0c977d1fb2cb6ae/keyboards/ymd96/ymd96.h#L53).

Please advise/clarify whether this is the case. I don't have any intentions of modifying user keymaps here more than necessary, but I'd like to get rid of the KC_NO on the `KEYMAP_CUSTOM`/now `LAYOUT_custom` macro - it's relevant to the Configurator's support for the board - but if I do that, your keymap will break.

**Comment by harshitgoel96** [comment]
Hi, I have a pr open for this. I noticed the issue and have fixed it. But there are some other recommendations for the PR which I have been able to work on due to bad health.I plan to start work on them soon.

**Comment by noroadsleft** [comment]
Thanks for the prompt reply. Sorry to hear your health has been poor.

I obviously forgot you had a PR open for this. (I commented several times! :man_facepalming: )

If you'd like, I'll close this, or reduce the scope of this PR. You were the first one to these changes, so I'll leave the decision to you.

**Comment by harshitgoel96** [comment]
I will update you tomorrow on this, once I fix the PR.

**Comment by harshitgoel96** [comment]
Hi, I have updated the PR with suggested changes. Can you please check the PR #4982 , and adjust the scope for this PR ?

**Comment by noroadsleft** [comment]
Left a review on your PR; will place this PR on-hold until yours is merged, so I can integrate your changes cleanly.

**Comment by noroadsleft** [comment]
This PR is ready... except I have no idea why Travis is suddenly failing.

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
