### PR TITLE
Convert Viterbi to Split Common code

### PR DESCRIPTION
**Pull request by drashna**
To be honest, I don't have a full split board to test this on, as I only using a single half. 

But it compiles and flashes onto my board just fine.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Could we get somebody to test this out on a full board? Maybe a `needs testing` label would be useful?

**Comment by drashna** [comment]
Yeah, a `needs testing` label may be a good idea.  There have been a few PRs that have really needed some testing, so it would be a good idea.

**Comment by drashna** [comment]
Travis is a liar.  My firmware images are too large.  (they aren't locally).

**Comment by drashna** [comment]
@nooges This look good?

**Pull request closed without merging**
