### PR TITLE
Added wob/rd75 mechanical keyboard

### PR DESCRIPTION
**Pull request by Wob-lab**
## Description

Added wob/rd75 mechanical keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [ x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
image

**Comment by Wob-lab** [comment]
Okay, I'll add the wireless-code. But how can I add it? Can you give me some suggestions for my reference?

**Comment by vlovini** [comment]
Hi! Dear @Wob-lab colleagues! Could you please share the RD75 Pro in another repository or at least in a separated branch while the code to be merged into the main branch are under analysis? 

This would be great for us owner of the keyboard that wants to tinker with it (with wireless capabilities).

Thanks a lot!

**Comment by vlovini** [comment]
@Wob-lab Guys, any place I can get the RD75 code? I'm looking forward to customize mine. 

Thank you in advance!

**Pull request closed without merging**
