### PR TITLE
Fixes for newbs_getting_started.md

### PR DESCRIPTION
**Pull request by xplusplus**
## Description

Various fixes for the Setup page in the QMK documentation. These fixes fix issues on both [the main documentation site](https://docs.qmk.fm/#/newbs_getting_started) and the [GitBook site](https://beta.docs.qmk.fm/tutorial/newbs_getting_started).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* Removed extraneous `:id=` code that was appended to Sections 2 and 3.
* H3 sections under Sections 2 and 3 display literal double-asterisks, `**`, rather than displaying bold H3 headers.
* Added a [clipboard ](https://emojipedia.org/clipboard/) and [warning ](https://emojipedia.org/warning/) emoji to the existing callouts. 
    * While the existing info and warning callouts, which are of the form `?>` and `!>`, render as expected on the qmk.fm website, neither [Github callouts](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#callouts) nor [GitBook callouts](https://docs.gitbook.com/editing-content/markdown#hints-and-callouts) appear to render properly. To remedy this, I took the liberty of prepending emojis to these sections to denote a callout, ensuring that the users still find them even if they are not rendered properly on Github or the Gitbook site.

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
> Removed extraneous :id= code that was appended to Sections 2 and 3.

This is intentional, its used to give consistent links for translations

**Comment by xplusplus** [comment]
For the translation links, are they currently working? The tags meant for them were only on two of the five sections of this document. Should they be on them all and printed literally?

For the bold issue, are you looking at the beta docs? This issue only arises in the main Github version:

image

**Comment by zvecr** [comment]
Non beta site has tabs, so not sure whats going on your end

image

**Review by zvecr — CHANGES_REQUESTED** [review]
Personally, I dont thing this change needs to go in.

**Comment by drashna** [comment]
Also, should be noted that `qmk docs` will create a mini web server that shows the main doc site and how it's formatted.  This should be used for verification locally, for bugs and the like.

**Pull request closed without merging**
