### PR TITLE
Added analog support for WB32 MCU.

### PR DESCRIPTION
**Pull request by itarze**
## Description
As the title.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by itarze** [comment]
No one review ?

**Comment by drashna** [comment]
This is one of the areas that I'm not really comfortable with, so I haven't reviewed it.

However, the people that are more familiar with this section haven't had a chance to get to it yet.

**Review by fauxpark — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Just waiting on CI to confirm.

**Comment by itarze** [comment]
Ok, thank you very much for your review.

**Comment by tzarc** [comment]
Please apply this patch so the onekey variants work -- we don't have write access to the PR.

[onekey-analog.patch.txt](https://github.com/qmk/qmk_firmware/files/9897457/onekey-analog.patch.txt)

**Comment by itarze** [comment]
Ok.

**Comment by tzarc** [comment]
I can see you're trying to fix all of the onekey keymaps -- for now there's no need, just the analog would have sufficed for the context of this PR. It's great that the I2C ones are now sorted as well!

If you wish to create a followup PR in the future to fix others that's fine, but analog was really the only concern at this point.

**Comment by itarze** [comment]
Can I handle all the onekey keymaps in this PR at once?

**Comment by tzarc** [comment]
> Can I handle all the onekey keymaps in this PR at once?

Sure, let me know when you're happy and I'll re-review.

**Comment by itarze** [comment]
@tzarc All the work items have been passed, you can review them now.

**Review by tzarc — APPROVED** [review]

**Pull request merged**
