### PR TITLE
Refactor and Configurator update for Chocopad

### PR DESCRIPTION
**Pull request by noroadsleft**
# Refactor

- `chocopad.h`
  - `KEYMAP` renamed to `LAYOUT`
  - `KC_KEYMAP` renamed to `LAYOUT_kc`
- `keymaps/default/keymap.c`
  - Keymap updated and refactored to use `LAYOUT` macro
  - `#include "chocopad.h"` updated to `#include QMK_KEYBOARD_H`

# Configurator

- Add `info.json`

### CODE REVIEW

**Comment by noroadsleft** [comment]
Also wondering as to whether or not I should assign the layout macro as `LAYOUT_ortho_4x4` rather than `LAYOUT`, and add `LAYOUTS = ortho_4x4` to `rules.mk`.

**Comment by drashna** [comment]
Yes, I think we should add ortho 4x4

**Comment by drashna** [comment]
Thanks!

**Comment by noroadsleft** [comment]
Uhhh... I wasn't done.

**Pull request merged**
