### PR TITLE
#define AUTO_SHIFT_SETUP

### PR DESCRIPTION
**Pull request by ThePreviousOne**
## Description

I added a config option called AUTO_SHIFT_SETUP for `autoshift_timer_report` `autoshift_enable` `autoshift_disable` funtions and  `KC_ASRP` `KC_ASUP` `KC_ASDN` keycodes

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by ThePreviousOne** [comment]
I missed the keycodeds, force pushed to avoid unnessesary commits in the history

**Comment by ThePreviousOne** [comment]
sorry

**Comment by zvecr** [comment]
I would rather keep the old behaviour as default so we are not silently breaking existing users workflow. Without maintaining the existing contract, it will need to go through the breaking change process.

Going with something like `AUTO_SHIFT_NO_SETUP` allows us to avoid that.

**Comment by ThePreviousOne** [comment]
I'm only 'removing' the report function can't imagine anyone using that on daily basis, But I get you're point.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ThePreviousOne** [comment]
I just made the change and when to reflect it in the docs and found `Remove `AUTO_SHIFT_SETUP` from your `config.h`.`
I didn't add it, it's already there. It's just not in the code.

Am I implementing a feature that has supposed to have existed for a while now?

**Comment by ThePreviousOne** [comment]
@zvecr its no longer a breaking change

**Comment by tzarc** [comment]
Retargeted to `develop` due to core changes.

**Comment by noroadsleft** [comment]
Thanks!

For future reference, we recommend against committing to your `master` branch as you've done here, because pull requests from modified `master` branches can make it more difficult to keep your QMK fork updated. It is highly recommended for QMK development – regardless of what is being done or where – to keep your master updated, but **NEVER** commit to it. Instead, do all your changes in a branch (branches are basically free in Git) and issue PRs from your branches when you're developing.

There are instructions on how to keep your fork updated here:

[**Best Practices: Your Fork's Master: Update Often, Commit Never**](https://docs.qmk.fm/#/newbs_git_using_your_master_branch)

[Fixing Your Branch](https://docs.qmk.fm/#/newbs_git_resynchronize_a_branch) will walk you through fixing up your `master` branch moving forward. If you need any help with this just ask.

Thanks for contributing!

**Comment by ThePreviousOne** [comment]
This wasn't technically on my master branch I was using a seperate instance in a different location. because at the time I had implemented alot of small breaking changes do to memory constraints in my controller.

**Pull request merged**
