### PR TITLE
updated a vendor name / fixed minor keymap issues

### PR DESCRIPTION
**Pull request by noclew**
## Description

We changed the vendor name of our keyboards, so I updated the vendor name in all our keyboard config files. Also, I noticed a few minor keymap issues, so they were fixed. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Updated vendor name and minor keymap issues

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
This will probably need to target `develop` since the keyboard names have changed.

**Comment by noclew** [comment]
> This will probably need to target `develop` since the keyboard names have changed.

Ah, I see. Thanks for letting me know! I will close this request and make a new one as you instructed.

**Comment by fauxpark** [comment]
Yeah, should be all good from master to develop. The other way around can be problematic, though.

**Review by fauxpark — APPROVED** [review]

**Comment by noclew** [comment]
> Yeah, should be all good from master to develop. The other way around can be problematic, though.

Thank you Ryan!

**Review by drashna — APPROVED** [review]

**Pull request merged**
