### PR TITLE
Quefrency xeal

### PR DESCRIPTION
**Pull request by alex-ong**
Add user keymap with faster debounce.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by alex-ong** [comment]
i can see that rev1 doesnt build. I use Rev2. Is there a way to specify that this keyboard only builds for Rev2 (onwards)? so that we can pass CI?

**Comment by fauxpark** [comment]
There's no way to exclude revisions, AFAIK, but you can place the keymap inside the rev2 directory.

**Comment by alex-ong** [comment]
> There's no way to exclude revisions, AFAIK, but you can place the keymap inside the rev2 directory.

Will that fix ci? If it doesn't I'm hesitant to move my stuff since it makes the repo look less clean :(

**Comment by alex-ong** [comment]
I've moved the keymap into rev2. It builds successfully!

**Pull request merged**
