### PR TITLE
Use the new ST7565 driver on Ergodox Infinity

### PR DESCRIPTION
**Pull request by firetech**
## Description

Add config for the new ST7565 driver by @fauxpark (#13089 ) to Ergodox Infinity, and enable it by default, disabling the uGFX-based Visualizer.

This means that the Ergodox Infinity is now built without uGFX (by default). A default (weak) display implementation, somewhat inspired by the old default visualizer (showing keyboard leds and layer state on the master half) has been added.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Somewhat related to #5268

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by firetech** [comment]
Side note, switching over to this for my daily driver firmware, with basically the same things rendered to the LCDs roughly quadrupled the matrix scan rate on my board (from ~250 to ~1000). 😄

**Comment by firetech** [comment]
@fauxpark Oh, I should probably mention... I did observe some weird issues while creating the sample display implementation... I first tried writing `QMK_VERSION` to the line below the logo, but got weird behaviour when that text overflowed from the last line to the first. Partly seemed like only the part that overflowed got marked as dirty, even if I wrote the logo after that text to overwrite the overflowing text.

**Comment by drashna** [comment]
If you add the task function to the infinity's c file, but set it as weak, it will have a default graphic that can be overwritten.  The `splitkb/zima` is a good example of where I did this.

**Comment by firetech** [comment]
> If you add the task function to the infinity's c file, but set it as weak, it will have a default graphic that can be overwritten.

I considered doing that, but got the feeling from @fauxpark in a comment in #13089 that it wasn't desired. 😛

**Comment by drashna** [comment]
> > If you add the task function to the infinity's c file, but set it as weak, it will have a default graphic that can be overwritten.
> 
> I considered doing that, but got the feeling from @fauxpark in a comment in #13089 that it wasn't desired. 😛

I think it's more of a "less than ideal situation" for the handling.  But IMO, it should be okay.

**Comment by firetech** [comment]
I added a default (weak) `st7565_task_user` implementation, so the default display behaviour is now quite similar to the default display behaviour with `VISUALIZER_ENABLE = yes`.

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by fauxpark** [comment]
Thanks!

**Comment by minusmario** [comment]
> I added a default (weak) `st7565_task_user` implementation, so the default display behaviour is now quite similar to the default display behaviour with `VISUALIZER_ENABLE = yes`.

It seems that the screen on the non-master side won't react with both display and backgroundcolor to user input, eg. demostrate layer or numlock state, is this the default behavior of qmk or did I do something wrong? I've deleted the is_keyboard_master if block in my own st7565_task_user function. Thanks.

**Comment by firetech** [comment]
> It seems that the screen on the non-master side won't react with both display and backgroundcolor to user input, eg. demostrate layer or numlock state, is this the default behavior of qmk or did I do something wrong? I've deleted the is_keyboard_master if block in my own st7565_task_user function. Thanks.

That's just the default behaviour of QMK. You need to add `SPLIT_LAYER_STATE_ENABLE` and `SPLIT_LED_STATE_ENABLE` to your config for the secondary half to be aware of those things. More information and more such options can be found [in the documentation](https://beta.docs.qmk.fm/using-qmk/hardware-features/feature_split_keyboard#data-sync-options).

**Pull request merged**
