### PR TITLE
Remove keyboard description from Adafruit BLE device name

### PR DESCRIPTION
**Pull request by fauxpark**
## Description
As I mentioned in https://github.com/qmk/qmk_firmware/pull/4967#discussion_r252911811, Adafruit BLE keyboards include the keyboard description from `config.h` in the device name. I think this is not really the right place for it, especially since some descriptions can be quite long.

## Types of changes

- [x] Core
- [ ] Bugfix
- [ ] New Feature
- [x] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* None.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
@drashna any love for this PR? :)

**Comment by fauxpark** [comment]
Hey @skullydazed mind taking a quick look at this? Is there anything holding it back?

**Comment by vosechu** [comment]
@fauxpark Seems like you're good to go! Mind merging?

**Comment by fauxpark** [comment]
Unfortunately I don't have the big red- er, *green*, button. One of the people on the right hand side there needs to do that.

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
