### PR TITLE
Update reviung34 PRODUCT_ID

### PR DESCRIPTION
**Pull request by gtips**
## Description

PRODUCT_ID changed

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — COMMENTED** [review]
If this is for VIA, then you will need to change the VID as well. Otherwise, LGTM.

**Comment by gtips** [comment]
Thank you fauxpark.
It may be VIA support in the future, but not right now.
If change VID in the future, will the new VID be common to all my keyboard series?

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by noroadsleft** [comment]
> If change VID in the future, will the new VID be common to all my keyboard series?

We do like for vendors with VIA-supported keyboards to use the same unique `VENDOR_ID` across all their boards.

Anyway, this is fine.

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
