### PR TITLE
DRV2605L Continuous Haptic Feedback Support

### PR DESCRIPTION
**Pull request by mechmerlin**
## Description

Provide a continuous feedback mode for DRV2605L equipped keyboards such as the Hadron Rev 3 by @ishtob.

This introduces three new keycodes `HPT_CONT` for toggling continuous feedback, and `HPT_CONI`, `HPT_COND` for increasing and decreasing feedback strength. 

Tested on ver3 sample from Ishtob. 

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by ishtob** [comment]
looks good, not sure if i want to do a longevity test with the LRA motors on the hadrons, but maybe I should?

**Comment by mechmerlin** [comment]
> looks good, not sure if i want to do a longevity test with the LRA motors on the hadrons, but maybe I should?

My tests have shown that when haptic feedback is set too strongly, the whole case rattles to a point where its a high pitched rattle rather than the soft smooth vibrations when set at a medium level. This starts to occur perhaps about 10-15 seconds in.

**Comment by drashna** [comment]
Merge conflicts

**Comment by mechmerlin** [comment]
@drashna I fixed the merge conflicts. We ready to shake things up?

**Comment by drashna** [comment]
> We ready to shake things up?

💩

**Comment by drashna** [comment]
Looks good!

**Pull request merged**
