### PR TITLE
Convert split_common to use generic GPIO api

### PR DESCRIPTION
**Pull request by pelrun**
## Description

One tiny step towards refactoring split_common so it can be used by both AVR and ARM builds. This PR replaces the raw AVR gpio accesses with the generic QMK GPIO api calls. Functionality should be completely unchanged for existing users, but this needs verification.

This is just a starting point for discussion; as I see it to get split_common properly decoupled there are several significant issues that will require discussion/buy-in from other interested parties:
- [x] Replace raw AVR GPIO accesses
- [ ] Replace raw AVR USB master/slave test (should use/override is_keyboard_master instead)
- [ ] Allow overriding handedness check by keyboard code (maybe calling a weak is_keyboard_lefthanded function?)
- [ ] Properly separate matrix and i2c/serial code, use a transport-agnostic API like that in the hydra serial code and link in the desired transport code at build time (allows replacing the existing AVR-specific transports with a custom one)
- [ ] Rework chibios main loop (is tightly coupled to ergodox-infinity and quantum/serial-link)

## Types of changes

- [ ] Core
- [ ] Bugfix
- [ ] New Feature
- [x] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Tested this as is, and it seems to work just fine, though required flashing both sides. :)

However, this is breaking the Dactyl Manuform keymap.

**Comment by drashna** [comment]
@nooges @That-Canadian @mtei 
Could you take a look/verify that this doesn't break anything, and looks good?

**Comment by drashna** [comment]
>Replace raw AVR USB master/slave test (should use/override is_keyboard_master instead)
There are already a couple of options here.  But yeah, we need a hardware agnostic check.  That or ifdef the check so that it's AVR/ARM specific. 

>Allow overriding handedness check by keyboard code (maybe calling a weak is_keyboard_lefthanded function?)
Technically, SWAP_HANDS will do this, if it's set up for the keyboard.  :)

Also, it would be nice to be able to set the handedness for EE_HANDS via a keycode. 
This could actually be done via bootmagic_lite, too. 

>Properly separate matrix and i2c/serial code, use a transport-agnostic API like that in the hydra serial code and link in the desired transport code at build time (allows replacing the existing AVR-specific transports with a custom one)

Agreed. 
Also, it would be nice if we could convert the i2c stuff to use i2c_master.c from the drivers folder. Merge that code together.  That way, we'd have a much better way to maintain this, and it would be hardware specific. 

>Rework chibios main loop (is tightly coupled to ergodox-infinity and quantum/serial-link)

Check out the Muon light branch, as that has some i2c stuff for ARM.  
Also, check out the qwiic stuff. 

>Rework chibios main loop (is tightly coupled to ergodox-infinity and quantum/serial-link)

I can't really comment on this. 

But you may want to add/comment on this issue:
https://github.com/qmk/qmk_firmware/issues/4254

**Comment by pelrun** [comment]
> Technically, SWAP_HANDS will do this, if it's set up for the keyboard. :)

That isn't quite sufficient for my case - my handwired keeb just has a jumper across two spare gpio's on the right side, which requires a bit more code to detect than the existing SPLIT_HAND_PIN stuff. Simply adding the weak attribute lets you replace the code with something custom meaning any weird scheme can be handled easily. But that's for another PR :)

**Comment by drashna** [comment]
@pelrun This ready to be merged, now?

**Comment by pelrun** [comment]
Yes, it's good to go.

**Comment by drashna** [comment]
Thanks!

**Comment by mtei** [comment]
Sorry, I have a question.

```c
 static void select_row(uint8_t row)
 {
-    uint8_t pin = row_pins[row];
-    _SFR_IO8((pin >> 4) + 1) |=  _BV(pin & 0xF); // OUT
-    _SFR_IO8((pin >> 4) + 2) &= ~_BV(pin & 0xF); // LOW
+    writePinLow(row_pins[row]);
+    setPinOutput(row_pins[row]);
 }
```

```c
 static void select_col(uint8_t col)
 {
-    uint8_t pin = col_pins[col];
-    _SFR_IO8((pin >> 4) + 1) |=  _BV(pin & 0xF); // OUT
-    _SFR_IO8((pin >> 4) + 2) &= ~_BV(pin & 0xF); // LOW
+    writePinLow(col_pins[col]);
+    setPinOutput(col_pins[col]);
 }
```

The order to make it output-mode changed.
Is it a good thing or a bad thing?

**Comment by pelrun** [comment]
It's intentional, and means that when the pin changes to output it's already at the proper level. If it's the other way around, there's a possibility of driving the wrong level for a very short time before the next statement sets it correctly.

Honestly it's very unlikely to make any difference in this instance, but I try to avoid driving glitches where possible.

**Comment by mtei** [comment]
@pelrun 
I think you misunderstood. In AVR, I experimented and confirmed that your code does not behave as you expected.

So I opened # 5174.

**Pull request merged**
