### PR TITLE
Fixed the ortho60 and ortho48 matrix layout after testing

### PR DESCRIPTION
**Pull request by nblyumberg**
After working through the testing setup with Drashna, we were able to confirm that ortho60 (and ortho48 based on feedback from another user) has the wrong matrix layout and spacebar should be 4,6 instead of 4,5

Image from qmk toolbox console
image

Revised the .h files for both to fix

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by Erovia — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by zvecr** [comment]
Thanks!

**Comment by cyril279** [comment]
@nblyumberg , @drashna ,
This commit breaks the 2u-layout by rendering the 2u key-position inactive.

The 2u spacebar position-35 (dual routed for left/center switch) traces directly to pin A6 of the controller.
key-position 36 traces directly to pin A5 of the controller.
this commit tellls the 2u layout to listen to the (empty) position 36 for key-press.
This is backed-up by the matrix_col_pins of the config.h
I cannot vouch for its effect on the ortho60, but based upon a look at the config files, the effect should be the same.

**Comment by nblyumberg** [comment]
> @nblyumberg , @drashna ,
> This commit breaks the 2u-layout by rendering the 2u key-position inactive.
> 
> The 2u spacebar position-35 (dual routed for left/center switch) traces directly to pin A6 of the controller.
> key-position 36 traces directly to pin A5 of the controller.
> this commit tellls the 2u layout to listen to the (empty) position 36 for key-press.
> This is backed-up by the matrix_col_pins of the config.h
> I cannot vouch for its effect on the ortho60, but based upon a look at the config files, the effect should be the same.

How are you determining this? Based on a PCB trace, qmk code, via code or something else?

**Comment by cyril279** [comment]
pcb-trace. I own the keyboard. I had to troubleshoot why my keyboard suddenly didn't respond to spacebar presses.

**Comment by cyril279** [comment]
It is not clear to me what the qmk toolbox screenshot is confirming/showing, but when the count starts at zero, then the position 3,5 is correct for the 4x12 ortho48, and 4,5 is the correct position for the 5x12 ortho60.

**Comment by nblyumberg** [comment]
> It is not clear to me what the qmk toolbox screenshot is confirming/showing, but when the count starts at zero, then the position 3,5 is correct for the 4x12 ortho48, and 4,5 is the correct position for the 5x12 ortho60.

So I believe you may have an ortho48 rather than an ortho60, I have an ortho60 with a 2u spacebar that I used for my testing. My board is soldered but I was able to use tweezers to verify the behavior when I was making the fix. What I suspect may be the case is that the ortho60 has the traces going one way, and the ortho48 has it going another way. The alternative theory to that is that there are two different versions of the PCB where the routing was changed. 

The qmk toolbox screenshot is showing the debug printing of the matrix position that was being pressed at the time. 
If you can give me the exact steps to reproduce the issue, I will give it a shot on my ortho60.

The issue that we initially ran into (another user identified this) was that the VIA mapping was not working as intended for him where when he had toggled it to a 2x1u config. I worked with Drashna to confirm that what I understood was the wrong behavior and we added debugging statements to check what matrix positions were being used and then added this fix in to remedy the issues.

**Comment by cyril279** [comment]
To determine the board-tracing in a practical way that also helps to ensure that we are counting/considering positions the same way:
Using the x12 layout, we can change the last-row positions `lower, space, space, raise` to `4, 5, 6, 7`.
Shorting the contacts of the center-switch will specifically tell us which of the neighboring switches it is traced to.

Whether the kit is soldered as 1x2uC or 4/5x12, the result will be the same. two of the center three switch positions will output either 5 or 6, incidating which column is traced to the 2uC position, and confirming the matrix.

Using the **default ortho keymap** (which uses the full-grid layout), replace the last row with:
```
    BL_TOGG, KC_LCTL, KC_LALT, KC_LGUI, KC_4,    KC_5,    KC_6,    KC_7,    KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT
```

This method, since it uses the grid layout is UNAFFECTED by the commit, and simply tells us about the mapping of the pcb. 
I tried this with my ortho48 this morning, and the center switch contacts output 5, while the grid-switch contacts output 4,5,6,7. This indicates that the center button is traced to the 3,5 position of this pcb.

**Pull request merged**
