### PR TITLE
Limit RGB max brightness on KPrepublic BM-series keyboards

### PR DESCRIPTION
**Pull request by TheBeastOfCaerbannog**
## Description

When using maximum brightness without limit LEDs are overheating (you can even feel it through the case, no joke) and power issues arise. This PR limits the maximum brightness to the one used in default firmwares by vendor.
[Here ](https://drive.google.com/drive/folders/1k3eYafJzdJONsAvhI28h85DWGxdk_g50)are the default firmwares that have `rgbVol` 180.
Here's also the confirmation from KPrepublic:
image
I've tested the changes on BM40HSRGB and it works fine, I'm quite sure it would work on the rest of BM-series too.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by TheBeastOfCaerbannog** [comment]
Thanks for the approval! What should should be the next step to get it merged?

**Comment by drashna** [comment]
> Thanks for the approval! What should should be the next step to get it merged?

Per the PR Checklist docs:

>In general, we want to see two (or more) approvals that are meaningful (e.g. that have inspected code) before a PR will be considered for merge.

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
@drashna This will need a follow-up on `develop` for the suspend behavior change.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
