### PR TITLE
Noeeprom functions for rgb_matrix

### PR DESCRIPTION
**Pull request by tynanbe**
## Description

Added eeprom_helpers for toggle, mode, sethsv, speed, similar to rgblight versions.
Added set_speed function.
Added helper functions, similar to those in rgblight, in order to:
Add noeeprom versions of toggle, step, hue, sat, val, and speed.
Minor: spelling correction for EEPROM in a debug message.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* Unsure, probably should have opened one first.

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tynanbe** [comment]
>     * clang-format should be run across the 2 changed files
> 
>     * `docs/feature_rgb_matrix.md` should be updated with the new functions
>       
>       * do the `*_eeprom_helper` functions need to be exposed as part of the public API?

- Ran `qmk cformat` and updated `docs/feature_rgb_matrix.md`
- Unsure if `*_eeprom_helper` functions need to be exposed; tried to follow `quantum/rgblight.h`, but now I see it only exposes `rgblight_sethsv_eeprom_helper` and `rgblight_mode_eeprom_helper`

**Comment by drashna** [comment]
I would say that the helper functions don't need to be exposed, at all.

**Comment by tynanbe** [comment]
Rebased on current develop branch.
Removed rgb_matrix_*_eeprom_helper functions from quantum/rgb_matrix.h

**Comment by drashna** [comment]
It looks like it grabbed a bunch of other commits too. :(

Probably needs to be rebased again.  That, or some git magic.

**Comment by noroadsleft** [comment]
Looks like `develop` was merged into this branch at some point, instead of this branch being rebased upon `develop`. (They're not the same thing.)

@tynanbe, you need to run `git rebase -i develop`, which should give you a window that looks something like this:

image

Type `:1,23d` and hit the Enter key. This will delete the first 23 lines of the file. Then, type `:wq` and hit Enter again to save and close. Git will do some magic, and then finish with a message that reads something like `Successfully rebased and updated refs/heads/develop-rgb_matrix-noeeprom.`

After that, run `git push --force-with-lease` – this will update this branch to have only the four commits that you authored.

**Comment by tynanbe** [comment]
@zvecr @noroadsleft Please do a final review; all requested changes have been made.

**Comment by noroadsleft** [comment]
> @noroadsleft Please do a final review; all requested changes have been made.

I actually fully reviewed this last night... then forgot to mark it reviewed :man_facepalming:

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
