### PR TITLE
Nebula12 RGBLIGHT buffer workaround

### PR DESCRIPTION
**Pull request by yiancar**
## Description

The keyboard has only 4 WS2812B LEDs.
I have tried both the bitbang and SPI drivers. The first LED is set incorrectly.
When setting the number of LEDs > 8, the first LED is now correct.

I know that this is not ideal as the effect are "missing" some LEDs but I cant figure out any other reason other than that the initial timing is incorrect due to the buffer being to small.

Also renamed the board definition to make it unique. This has nothing to do with the LED problem. A different board file is needed to change the DMA mapping. This looks like it can only be done at function `boardInit`

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Please do something like this, instead of replicating board files.:
https://github.com/qmk/qmk_firmware/pull/10214/commits/f0275b369ccb5aa82a335797e9970e22641367cc

**Review by tzarc — CHANGES_REQUESTED** [review]
No new board files should be added to the repo.
Please see the commit I linked earlier, as well as [early init](https://docs.qmk.fm/#/platformdev_chibios_earlyinit) for subsequent information.

**Comment by yiancar** [comment]
Done! @tzarc I didnt know you guys made it so configurable. Cheers:)

**Comment by tzarc** [comment]
> 
> 
> Done! @tzarc I didnt know you guys made it so configurable. Cheers:)

Still in progress! We don't want to maintain ChibiOS configs or board files in QMK, so we've been working towards their elimination. Adding new ones in is a backward step, so we try and avoid it unless it's to add support for a new MCU.

**Comment by tzarc** [comment]
This will be coming too: https://github.com/qmk/qmk_firmware/pull/10418/commits/1d993c1017547efb2d13b4ae4d92d0ac7839d662

It likely won't work at the moment -- the whole of #10418 needs to get done at the same time -- but it should simplify a lot of things going forward.

**Comment by yiancar** [comment]
Thats really cool! I had a look with a logic analyzer and the data seems correct btw... I am using a 2n7002 level shifter... maybe it doesnt initialize the first bit correctly at the beginning?!

**Comment by sigprof** [comment]
You can call `rgblight_set_effect_range(0, 4);` to make the effects use only the 4 existing LEDs while still having a larger `RGBLED_NUM`.

**Comment by yiancar** [comment]
That does not work @sigprof as the issue is with my level shifter first edge response. The above still only outputs 4 packets.

**Review by drashna — APPROVED** [review]

**Comment by yiancar** [comment]
Bump!

**Review by tzarc — APPROVED** [review]

**Pull request merged**
