### PR TITLE
JJ50 Refactor and updates

### PR DESCRIPTION
**Pull request by noroadsleft**
- Matrix `LAYOUT` renamed as `LAYOUT_ortho_5x12`
  - aliased as `LAYOUT`
- Added `info.json` file
- Added `LAYOUTS = ortho_5x12` to `rules.mk`
- Some cleanup on the readme file.

### CODE REVIEW

**Comment by drashna** [comment]
Travis CI error is unrelated to this change (mostly).  One of the layouts has NKRO enabled, but it's not supported on this board.

Thanks!

**Comment by noroadsleft** [comment]
It's xyverz's community keymap, naturally. :smile:

**Comment by drashna** [comment]
Well, the issue is that VUSB doesn't support NKRO, which .... isn't great. 

And there isn't a good way to compile all of the keymaps that your layout uses to test from compatibility.

**Comment by Xyverz** [comment]
'Eh wot? Something wrong with my keymap? Please advise.

**Comment by drashna** [comment]
Yeah, VUSB doesn't support NKRO, so one of the boards is throwing errors when attempting to compile.

If you replace the 
```makefile
NKRO_ENABLE       = yes
```
with this: 
```makefile
ifeq ($(strip $(PROTOCOL)), VUSB)
NKRO_ENABLE       = no
else
NKRO_ENABLE       = yes
endif
```

That should fix the issue in the future.  I've tested, and am doing this myself.

**Comment by Xyverz** [comment]
I need to put this in the .../community/ortho_5x12/xyverz/rules.mk?

**Comment by drashna** [comment]
Correct.

**Pull request merged**
