### PR TITLE
Add bootloadHID binary to shell.nix

### PR DESCRIPTION
**Pull request by nrabulinski**
## Description

This change adds the bootloadHID binary necessary for flashing some of the boards to `shell.nix`.
I have tested the change and in fact used it to flash my Keychron V4 which was what prompted me to make this PR :smile: 

## Types of Changes
- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by nrabulinski** [comment]
> > I have tested the change and in fact used it to flash my Keychron V4
> 
> 
> 
> That is a STM32 board and uses `dfu-util` and definitely not `bootloadHID`.

Then I have been bamboozled by the readme, I stand corrected. It should still work though, but someone with a compatible keyboard should probably test it then 😅

**Comment by sigprof** [comment]
Also I think that the proper way is to add the package to the upstream nixpkgs (there was an abandoned attempt to do that: https://github.com/NixOS/nixpkgs/pull/214397).

**Comment by nrabulinski** [comment]
> Also I think that the proper way is to add the package to the upstream nixpkgs (there was an abandoned attempt to do that: https://github.com/NixOS/nixpkgs/pull/214397).

I wanted to do that too but this repo is on an ancient nixpkgs and from all the PRs it seems like it's not moving anywhere so we wouldn't be able to use the upstream anyway

**Comment by sigprof** [comment]
> this repo is on an ancient nixpkgs

That's mostly because any change to the pinned nixpkgs version would trigger a long rebuild at least for the macOS users (alternatively, `*-darwin` platforms could get a different version of `avr-gcc`, but then some firmwares might not build there due to those versions generating larger binaries; although this might ultimately be required for `aarch64-darwin`, because avr-gcc8 apparently does not build there at all, but more recent versions could be built; but I don't have any hardware to test that anyway, and GitHub offers only x86_64 free runners for macOS).  And getting the package upstream would mean that it could be taken from the official binary cache instead of building it locally.

**Comment by nrabulinski** [comment]
Well, I happen to have an M1 machine so if it'd be welcome I'm happy to contribute and test out on both x86-64 and aarch64 Linux/Darwin 😄

**Pull request closed without merging**
