### PR TITLE
Adds IS31F13731 RGB matrix implementation

### PR DESCRIPTION
**Pull request by jackhumbert**
This is a pretty rough integration into QMK, but the core of the driver is pretty solid, thanks to @Wilba6582. 

I'm hesitant to add thorough documentation, since things may change dramatically in the future.

The entire thing is configured from a matrix and a few config variables (see #1856 for the Planck Light's implementation of this), which look like this:

```c
const is31_led g_is31_leds[DRIVER_LED_TOTAL] = {
/*   driver
 *   |  matrix
 *   |  |  modifier (used in some effects)
 *   |  |  |  control_index
 *   |  |  |  |  {row | col << 4}
 *   |  |  |  |  |             {x=0..224, y=0..64} */
    {0, 0, 1, 3, {0|(0<<4)},   {20.36*0, 21.33*0}},
    ...
};
```

and

```c
// This is a 7-bit address, that gets left-shifted and bit 0
// set to 0 for write, 1 for read (as per I2C protocol)
// The address will vary depending on your wiring:
// 0b1110100 AD <-> GND
// 0b1110111 AD <-> VCC
// 0b1110101 AD <-> SCL
// 0b1110110 AD <-> SDA
#define DRIVER_ADDR_1 0b1110100
#define DRIVER_ADDR_2 0b1110110

#define DRIVER_COUNT 2
#define DRIVER_1_LED_TOTAL 25
#define DRIVER_2_LED_TOTAL 24
#define DRIVER_LED_TOTAL DRIVER_1_LED_TOTAL + DRIVER_2_LED_TOTAL
```

### CODE REVIEW

**Comment by Wilba6582** [comment]
The way you have changed the configuration using `g_is31_leds` results in storing way more data than is required. Mapping of a single integer (in this case 0..71) to the LED driver/matrix/registers is constant, and easily done in code - i.e. there is a logical pattern to it, LEDs are grouped by driver/matrix/RGB LED.

You've removed that simplicity, added redundant data to arrays, and then merged this all with the concept of "modifier" (i.e. whether a key is alpha or modifier) as well as the coordinate of that RGB LED... these things should be at the keyboard implementation level, either by a) an array using LED index as the index, mapping to something like a coordinate, or b) a 2D array using row/col as index, mapping to LED index.

Also, `g_map_control_index_to_register` is an inefficient refactoring of the original code.

**Comment by jackhumbert** [comment]
We're definitely sacrificing a lot of storage and efficiency here, but the I'm hoping that the clarity and  ease in driver/matrix configuration is worth it - the folks I've chatted with about implementing RGB into their boards have been pretty hesitant to do so because of the complexity (configuring the Light with the original format was pretty difficult for me and @ishtob).

What data in the array is redundant? IIRC, there was something you had as a constant in the driver level that needed to be changed for our implementation.

**Comment by Wilba6582** [comment]
The original code worked fine... everything at the driver level was addressable by a LED index in the range 0..71 (for two drivers), and could have been expanded/reduced if necessary.

How a PCB arranges the LEDs is an implementation detail. At the keyboard level of code, do what is required to maintain a mapping of row/col to LED index, or whatever. 

So the original code had a constant mapping of LED index to driver/matrix/position in matrix, it was simple. That `g_is31_leds` array is indexed by LED index, but then instead of reusing the simple mapping of LED index to driver/matrix/position, it stores driver/matrix/position.

That bit is redundant and not required. The other data in `g_is31_leds` is not even used at the driver level, it's only relevant to the calling code, i.e. at the keyboard level, when deciding what color to set that LED.

What I'm saying is, you've introduced more complexity and storing more data than is required. End users only need to determine what the "LED Index" is for each RGB LED on their PCB. Given a LED Index, they can then programmatically enable the LEDs that are physically present (i.e. not "empty" locations in the LED matrix),  using `IS31FL3731_set_led_control_register`, and then set the color of that RGB LED, addressable by LED Index, using `IS31FL3731_set_color`

How end users want to map LED index to other state like row/col etc. can be done at the keyboard level, like how you've defined `g_is31_leds`... you just need to make it an array where the index is the LED index, not have the redundant driver/matrix/control_index data members of that struct.


`g_map_control_index_to_register` is a refactoring of the three arrays used to map the Nth RGB LED in a matrix to the PWM register. See the original code. Since the offsets are the same for matrix A and B per driver, you only need to define the offsets for matrix A and apply a constant offset to get the register address for matrix B. You must have known this was redundant already, since you manually added "+8" to half that array's constant values.

**Comment by Dbroqua** [comment]
Hello,

If I understand the documentation for the is31fl3731, this controller is able to control individually all leds of one keyboard?

What kind of led can be used and how to implement this on the firmware?

Regards
Damien

**Comment by Wilba6582** [comment]
@Dbroqua this driver is specifically designed to control RGB LEDs not individual LEDs. At the lowest level, it's controlling individual LEDs, but the interface is designed to control the red/green/blue of an RGB LED.

**Comment by Dbroqua** [comment]
Ok,

We can use WS2812B or other RGB led ? (like those sold by Zeal)

What difference with this driver and the other method? Better control of the color of leds?

**Comment by Wilba6582** [comment]
@Dbroqua IS31FL3731 is good for controlling RGB LEDs that go under switches, you have control over total current, and it handles the PWM brightness. The IC is small making it better to fit on keyboard PCBs with limited space. WS2812B is an OK solution for a low number of LEDs on the bottom of a PCB.

**Comment by Dbroqua** [comment]
Thanks for your replies @Wilba6582

**Pull request closed without merging**
