### PR TITLE
Fix dactyl manuform 6x6 LAYOUT_6x6_5_thumb rendering

### PR DESCRIPTION
**Pull request by DuMaM**
This should fix all configurator problems for 6x6 dactyl manuform variants

## Description
There is no way to check configurator behavior after changes. I don't know why it's unable to load default keymap for any layout. I compared this with other keyboard with similar solutions where are multiple boards defined. I hope I found out correct solution.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR
-

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by DuMaM** [comment]
Please do not merge it yet. Other PR need to be merged first. https://github.com/qmk/qmk_firmware/pull/15890
I also need to check if my PR is detected by CI linter. This will mean I finally heave a working version.

**Comment by DuMaM** [comment]
Ok, I got confirmation form CI Linter that my keyboard will be recognized by configurator.

**Review by zvecr — CHANGES_REQUESTED** [review]
This PR wont really change any behaviour for loading keymaps.

<https://docs.qmk.fm/#/configurator_default_keymaps>

<https://github.com/qmk/qmk_configurator/blob/master/public/keymaps/h/handwired_dactyl_manuform_6x6_default.json> needs to be duplicated/renamed.

**Comment by DuMaM** [comment]
@zvecr Ok, I will add this then also to qmk configurator.
This PR fill fix qmk linting in github action and displaying LAYOUT_6x6_5_thumb in configurator though.
So please merge it :pray:

**Comment by zvecr** [comment]
If you revert everything but the info.json changes, sure. Everything else is not required.

**Comment by DuMaM** [comment]
@zvecr I reverted this and now QMK Lint is not working in Github Actions.

**Review by zvecr — APPROVED** [review]

**Comment by zvecr** [comment]
The actions script is a little naive and wont correctly intersect the changes against the keyboard list. The changes are fine.

```bash
$ qmk lint -kb handwired/dactyl_manuform/6x6
Ψ Lint check passed!
$ qmk lint -kb handwired/dactyl_manuform/6x6/blackpill_f411
Ψ Lint check passed!
$ qmk lint -kb handwired/dactyl_manuform/6x6/promicro
Ψ Lint check passed!
```

**Review by drashna — APPROVED** [review]

**Comment by DuMaM** [comment]
@zvecr I added https://github.com/qmk/qmk_configurator/pull/1048 this according to your suggestions.

**Pull request merged**
