### PR TITLE
Initial vusb console support

### PR DESCRIPTION
**Pull request by zvecr**
## Description

In a similar effort to #8380, this enables console support for vusb. Given the endpoint limitations, this also has to have mouse/extra disabled for it to work.

### Notes
* Tested on windows && linux with and without hid_listen running

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Rebased and retested now that #8572 has gone in.

**Comment by zvecr** [comment]
Rebased and retested now that #8380 has gone in.

**Comment by yiancar** [comment]
Could we wait a few more days for https://github.com/qmk/qmk_firmware/issues/8593 to be decided before merging?:)

**Comment by zvecr** [comment]
This targets console as its currently implemented. I would rather merge this "as is", given i have already had to rebase this twice due to change in the same area. However if any console endpoint work is merged first, then i will update it to match.

**Comment by yiancar** [comment]
I think we should also try to figure out why early logging locks it up as well rather than timer it out if possible.

As soon as https://github.com/qmk/qmk_firmware/issues/8593 is decided ill try to look into the lock up as well.

It looks to me that CONSOLE_EPSIZE should be 32 to match with the rest.
also at the function `sendchar` could you try `usbSetInterrupt3((void *)&c, sizeof(c));` I know its 1 byte but it makes a lot more sense to have the compiler do it for you.

**Comment by zvecr** [comment]
I went with CONSOLE_EPSIZE of 8 to match RAW_EPSIZE introduced in #8380.

Also with the latest changes, the timer is no longer required.

**Comment by yiancar** [comment]
AH got it about CONSOLE_EPSIZE:) 

Amazing! thanks mr ring buffer:)

**Comment by tzarc** [comment]
Seems to _work_ but the ring buffer drops output when it's too long... which is one of the constraints.

e.g.:
```
*** HID device connected: coseyfannitutti MYSTERIUM (6B62:8769:0001)
  > DEBUG: enabled.
  > Enabling calligraphy mode
  > Disabling repeat mode
    nabled: true
  > Config enabled: false
     WoW repeat mode
    g repeat mode
  > Enabling WoW repeat mode
  > Disabling repeat mode
     WoW repeat mode
    g repeat mode
  > Enabling WoW repeat mode
  > Disabling repeat mode
     WoW repeat mode
    g repeat mode
  > Enabling WoW repeat mode
  > Disabling repeat mode
     WoW repeat mode
    g repeat mode
```

If that's acceptable, then yeah. Merge away.

**Comment by tzarc** [comment]
Output is specific to qmk_toolbox, hid_listen is A-OK.

**Pull request merged**
