### PR TITLE
First pass at reorganizing docs

### PR DESCRIPTION
**Pull request by skullydazed**

### CODE REVIEW

**Comment by drashna** [comment]
Mostly looks good.  The main issue that I have, is that by removing the keycode stuff, it's much harder to find.... since we lack a table of contents.

**Comment by skullydazed** [comment]
It's all still there just folded into Features. Currently we have a ton of duplication between the two sections.

**Comment by drashna** [comment]
.... we still need a ToC, IMO. :)

**Comment by drashna** [comment]
Thanks

**Pull request merged**
