### PR TITLE
Add privileged flag to runtime command

### PR DESCRIPTION
**Pull request by Siilwyn**
## Description
Seems like this flag is always needed?

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #18130

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
You’ll have to explain why you think it’s needed — works fine for me without it.

**Comment by Siilwyn** [comment]
@tzarc maybe you're using a different OS?
What more info would you like to see besides what's described in https://github.com/qmk/qmk_firmware/issues/18130?

**Comment by tzarc** [comment]
Have replied on the issue, can't reproduce it locally.

**Comment by zvecr** [comment]
Closing as the current implementation isnt the solution we would want, further discussion can continue in the linked issue.

**Pull request closed without merging**
