### PR TITLE
Move Iris via support to Via keymap

### PR DESCRIPTION
**Pull request by drashna**
## Description

And move it out of the main keyboard files

Otherwise, it's breaking the keyboard for a bunch of users, myself included. 
## Types of changes

- [ ] Core
- [X] Bugfix
- [ ] New Feature
- [ ] Enhancement/Optimization
- [X] Keyboard (addition or update)
- [X] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
@nooges

**Comment by drashna** [comment]
Travis CI errors are unrelated to this change.
https://travis-ci.org/qmk/qmk_firmware/builds/482149913#L919-L928

Specifically, old compiler version causing inflated file sizes.

**Comment by Wilba6582** [comment]
I don't see the `via` keymap. Could be cos it's Monday morning here, though ;-)

**Comment by nooges** [comment]
Yeah I don't see it either

**Comment by drashna** [comment]
Nope, that's my bad, and me being super tired today.  Give me a bit.

**Comment by Wilba6582** [comment]
I think the `config.h` in the `via` keymap is redundant, the one in `iris` should have all that is needed for dynamic keymaps if enabled.

**Comment by drashna** [comment]
Well, the `config.h` file is a direct copy from the default keymap. 

The USE_SERIAL, and MASTER_LEFT should be left in, since they control how communication is handled, and the orientation of the actual keyboard.  Though, without these, it defaults to these settings.   But leaving them in makes it easier to reference if somebody uses the keymap and changes it.

As for the RGB stuff, most of that could be removed, as it will default to the built in values. The one that shouldn't is the RGBLIGHT_ANIMATION, since that's not defined in the keyboard's `config.h` file, so removing it would actually disable animations for the keyboard.

**Comment by drashna** [comment]
Okay.

**Comment by nooges** [comment]
Can we get this merged in?

**Pull request merged**
