### PR TITLE
Delete jscotto directory.

### PR DESCRIPTION
**Pull request by joe-scotto**
## Description

I've been modifying all keyboards within the `handwired/jscotto` directory in addition to moving them to `handwired/scottokeebs`. I have opened individual PRs for each keyboard to move into `/handwired/scottokeebs` so `/handwired/jscotto` can be removed.

- Scotto9 (#21105)
- Scotto36 (#21104)
- Scotto40 (#21103)
- ScottoCMD (#21102)
- ScottoStarter (#21101)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
This shouldn't have been done in this way. Each keyboard should have been directly moved in individual PRs, rather than duplicating and then removing this old folder.

**Comment by fauxpark** [comment]
Sorry this wasn't better communicated. Per the PR checklist, [keyboard moves need to go through `develop`](https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs). The above PRs have basically duplicated your boards on `master`. This is a problem because `master` is merged into `develop` when commits are made to it, so any attempt to undo the duplication will propagate, and you'll have to start over targeting the correct branch.

**Comment by joe-scotto** [comment]
@fauxpark Sorry this is confusing...

What should be done now then? Should I branch off develop for each board in jscotto and move the files there as well as updating them? So for example:

1. Branch develop -> scotto9-move
2. Move `jscotto/scotto9` -> `scottokeebs/scotto9`
3. Update code for that board in the new location

What would have to be done about the other boards then? Since now they're basically duplicated like you say... why can't the directory just be deleted?

**Comment by fauxpark** [comment]
The key part is this:

> The above PRs have basically duplicated your boards on `master`.

https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/jscotto
https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/scottokeebs

These PRs should not have been merged to `master`; they should have gone to `develop`. The only way forward here is to revert all of your changes so far and redo them properly:

> This is a problem because master is merged into develop when commits are made to it, so any attempt to undo the duplication will propagate, and you'll have to start over targeting the correct branch.

**Comment by joe-scotto** [comment]
@fauxpark So two questions then....

1. How exactly can I go about reverting the changes if they've already been merged into `master`?
2. Can the new PRs, targetting develop, have changes in them to the keymaps as well?

But with that said, I guess I'm not really understanding why in this case the `jscotto` directory can't just be deleted after the boards are merged into `scottokeebs`. I read the part about aliases in the contributing document and can easily update that file but to have to start all over with 5 boards doesn't make much sense to me.

**Comment by fauxpark** [comment]
> I guess I'm not really understanding why in this case the jscotto directory can't just be deleted

Because this would only affect `develop`. The boards are still duplicated in `master`.

**Comment by fauxpark** [comment]
It would...in just under 3 months.

**Comment by joe-scotto** [comment]
So should I just have `jscotto` deleted from master? I'm really confused on what exactly needs to happen here.

**Comment by fauxpark** [comment]
Everything needs to be reverted. Then you should move + alias each board in individual PRs targeted at `develop`. No need for a followup PR like this one deleting the old folder, because Git doesn't consider empty folders.

**Comment by joe-scotto** [comment]
@fauxpark Aliases added along with merge conflicts being resolved. Let me know if anything else needs attention on this one.

**Comment by joe-scotto** [comment]
@fauxpark Moved to #21157.

**Pull request closed without merging**
