### PR TITLE
Add 30wer config and keymap

### PR DESCRIPTION
**Pull request by FSund**
I would like to add 30wer to the database of QMK supported keyboards.

Some background information on the keyboard can be found in the [Keebtalk thread](https://www.keebtalk.com/t/gb-30wer-by-8o7wer/3618).

### CODE REVIEW

**Comment by FSund** [comment]
FYI: One of the commits mention that the firmware is untested on a real board -- the most recent version *has* been tested, and works very well.

**Comment by FSund** [comment]
I've never set up Configurator support before, but I can have a look if it's a requirement to get accepted..?

**Comment by noroadsleft** [comment]
@FSund Here's a doc I put together a while back of how to do it.

https://github.com/noroadsleft/qmk_firmware/blob/docs/cf/docs/reference_configurator_support.md

**Comment by FSund** [comment]
Thanks @noroadsleft, that was very helpful. I've added `info.json` in a new commit, hope it looks okay!

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
