### PR TITLE
[WIP] Updated info.json for Duck Jetfire

### PR DESCRIPTION
**Pull request by noroadsleft**
Generated a new `info.json` file. @mechmerlin asked my help in debugging this file. Firmware works as expected if built from source, but not if built from the Configurator.

I'll need @mechmerlin's okay on these changes before this PR is merged. He has his own instance of Configurator that he'll be using for testing.

### CODE REVIEW

**Comment by drashna** [comment]
@mechmerlin This look good?

**Comment by mechmerlin** [comment]
Yes it does! But fingers crossed that we got the layout correct to actually work lol.

**Comment by drashna** [comment]
@noroadsleft This ready to merge?

**Comment by noroadsleft** [comment]
Good to go. *also crosses fingers*

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
