### PR TITLE
Fix Xorg segfault with KeebCats PCBs

### PR DESCRIPTION
**Pull request by amberstarlight**
## Description

Hi folks,

We have discovered a bug with xorg where it will [segfault when a USB device with a % in the product name is connected](https://gitlab.freedesktop.org/xorg/xserver/-/issues/1280). This PR removes the % from the KeebCats x Cutie Club PCBs that we have identified as affected.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — APPROVED** [review]

**Comment by fauxpark** [comment]
There are a handful of other boards with `%` in `PRODUCT`/`keyboard_name`, for reference:
```
bt66tech/bt66tech60
clueboard/17
clueboard/60
clueboard/66/rev1
clueboard/66/rev2
clueboard/66/rev3
clueboard/66/rev4
clueboard/66_hotswap/gen1
clueboard/66_hotswap/prototype
infinity60
kingly_keys/smd_milk
spaceman/2_milk
switchplate/southpaw_65
tkw/stoutgat/v2
```
Not as many as I expected, and nothing for `MANUFACTURER`/`manufacturer`.

**Comment by amberstarlight** [comment]
That's interesting, not very many! But still a good idea to pick out any others. How do you think best to proceed?

**Review by lewisflude — APPROVED** [review]
Looks good to me!

**Review by itspngu — APPROVED** [review]

**Comment by fauxpark** [comment]
Well, I kinda feel like this isn't a QMK issue - `%` is a perfectly valid character for a USB string descriptor. But I'm not sure how long this bug has been around, and it could be a good while before we can consider it "safe", given how slow some distros move...

**Comment by amberstarlight** [comment]
No absolutely - this is an issue with Xorg. USB string descriptors are simply UTF-16 ASCII and as you've rightly said these should be valid. From the logging we are seeing Xorg attempting string replacement like you would see in C. I know some people are digging into this currently.

From my perspective as the designer of these PCBs for KeebCats I would like users to be unaffected regardless; what do you think is the best course of action? Is it something that we can apply in the mean time whilst waiting for a fix from Xorg? Understand completely if you'd rather avoid hacks around OS bugs! 😁

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
