### PR TITLE
Keymap colors

### PR DESCRIPTION
**Pull request by Erovia**
## Description
This is a follow up of qmk#5300, therefore only can be merged after that one. 

- modify all keymaps to use the new color definitions  
- remove the old color macros

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Not all keymaps are within the qmk/qmk_firmware repo, for example, mine exist on my fork and i have no real intentions of submitting a PR.

My concern would be that the colour values are not typed, therefor code completion can never really happen and i would have to potentially dig through code or docs to find that its `RGB_WHITE` that i should use.

Is there value, in removing the old named colour macros?

**Comment by drashna** [comment]
> Not all keymaps are within the qmk/qmk_firmware repo, for example, mine exist on my fork and i have no real intentions of submitting a PR.

This is my biggest concern, actually.

I think that editing the docs to use the defines is a good idea, though.  And any default keymaps.

But I think that removing the functions are problematic, at best, at this point.  Though, updating them to use the rgb/hsv defines would be good.

**Comment by zvecr** [comment]
A method to mark them as deprecated (that plays nice with warnings as errors), and an plan to remove deprecated functionality could help.

**Comment by drashna** [comment]
I know this is something that has been discussed.  But I don't think there is a good/perfect answer here.   And that's actually why I keep my stuff in the repo. So if there is a major change, I'm not left wondering WTF RGB lights are no longer working.... :)

**Comment by Erovia** [comment]
@zvecr and @drashna 
Yeah, it's a breaking change and it was a rookie mistake that it lumped together the breaking code and non-breaking code into one PR. 

The only value in removing the macros is just code cleanup  

Maybe there should be a designated area on the website, where breaking/major changes are announced. It'd have saved me a lot of headache when my split board stopped working after the recent split code rework.

**Comment by skullydazed** [comment]
Re: breaking changes, let me make QMK's stance clear: Breaking changes do not happen without a very good reason. Breaking changes need to be announced and discussed in the community before they are merged.

That being said, we are currently in a period of growth. Some breaking changes are going to happen by mistake, and when they do we should revert them. We do not want to break any keymaps in the wild, especially since there is not currently a good way to learn about them.

Cleanup is good, but not breaking people's keymaps is better. If you feel something needs to be removed mark with a comment for now and we can come back to it later.

(For those wondering if/when breaking cleanup will ever happen, it will, but it will need to correspond with a new major release of QMK. We have yet to do such a thing so it's hard to say what it will look like.)

**Comment by Erovia** [comment]
@skullydazed thanks for the official statement on the topic.
Reverting back 7317b900943520efa9ee2a9e896646a6347a4b66 and inserting instead of a "banner" with something like "these functions are obsoleted and will be removed in a future release" good enough?

**Comment by skullydazed** [comment]
Yeah, that's a good path forward. The wording I would suggest looks something like this:

> These functions have been deprecated and may be removed in a future release

We also need to remove the user keymap changes. If any of those users have local changes to their repo this will require them to do merge conflict resolution, and we don't want to force that on unsuspecting users who may not know git well enough to fix it.

**Comment by Erovia** [comment]
Valid point.
I think I'll just close this PR and open a new one with the changes we agreed upon.

**Pull request closed without merging**
