### PR TITLE
65_ansi_blocker support for Doro67

### PR DESCRIPTION
**Pull request by mechmerlin**
## Description

With the recent inclusion of the 65_blocker_ansi default layout, I can start putting it everywhere applicable. The Doro67 is the first keyboard I own and can actually test properly with this layout. 

EDIT: Renamed to 65_ansi_blocker

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mechmerlin** [comment]
In the middle of doing this, I've found it a lot easier to say 65_ansi_blocker rather than 65_blocker_ansi. Any opinions on whether or not I should change it?

**Comment by noroadsleft** [comment]
> In the middle of doing this, I've found it a lot easier to say 65_ansi_blocker rather than 65_blocker_ansi. Any opinions on whether or not I should change it?

I actually nearly left that suggestion on that PR, then decided it was too nitpicky. But if you want to change it – and I actually think `65_ansi_blocker` makes more sense given our naming scheme – I think now is the best time for that.

**Comment by mechmerlin** [comment]
> > In the middle of doing this, I've found it a lot easier to say 65_ansi_blocker rather than 65_blocker_ansi. Any opinions on whether or not I should change it?
> 
> I actually nearly left that suggestion on that PR, then decided it was too nitpicky. But if you want to change it – and I actually think `65_ansi_blocker` makes more sense given our naming scheme – I think now is the best time for that.

Will do!

**Comment by drashna** [comment]
Yeah, I think that `65_ansi_blocker` sounds better

**Pull request merged**
