### PR TITLE
Fix annepro2/c18:iso_default

### PR DESCRIPTION
**Pull request by zvecr**
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Review by fauxpark — COMMENTED** [review]
Actually, this is already fixed in develop as part of the move to info.json.

**Comment by zvecr** [comment]
Nah its still broken

**Comment by fauxpark** [comment]
Oops, didn't realise this was a keymap.

**Comment by zvecr** [comment]
Alternatively we could just sack off the header, as to me the change doesnt add a ton of value (and would be incorrect for the `c15` target).

**Comment by fauxpark** [comment]
Sounds good to me.

**Pull request merged**
