### PR TITLE
Added Brazilian keymap for BM40RGB

### PR DESCRIPTION
**Pull request by lmlask**
## Description

Added Brazilian ABNT2 keymap for KPRepublic's BM40rgb as well as a detailed readme.
All added files are inside keyboards/kprepublic/bm40hsrgb/keymaps/wolff_abnt2.
Code compiles and flashes just fine.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — CHANGES_REQUESTED** [review]
Please remove the images from the PR.  We don't accept binary files like images. 

You can use an image hosting service such as imgur for that and link to them here.

**Comment by lmlask** [comment]
Deleted images folder.

The images weren't being used at all, I had just forgotten to remove them. Images in the readme are hosted elsewhere.

**Comment by lmlask** [comment]
@drashna I've deleted the images folder and the PR seems to have registered it. Is there anything else required?

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Comment by dlucenad** [comment]
If I might ask, since there is a dedicated MIDI layer and Audio on/off options, how did you add a piezo speaker/buzzer to this board?

**Pull request merged**
