### PR TITLE
[Keyboard] Add IDOBAO ID80

### PR DESCRIPTION
**Pull request by sigprof**
##  Description

Add support for the IDOBAO ID80 keyboard (available [on AliExpress](https://www.aliexpress.com/item/4000590804514.html) and [on Drop](https://drop.com/buy/idobao-id80-75-hot-swappable-mechanical-keyboard-kit?mode=guest_open)).

Most of the work was actually done automatically by the [KBFirmware JSON to QMK Parser](https://noroadsleft.github.io/kbf_qmk_converter/), using [the ID80.json file published on Drop](https://drive.google.com/file/d/16ZXPVl89HslGbrYalHmHrRyY4hopysMo/view?usp=sharing) as the data source.

Some things I'm not 100% sure about:

1. ~~`#define RGBLED_NUM 28` value comes from the JSON data, but the actual PCB that I got has 16 underglow LEDs and 4 more LEDs on the top surface (20 total). However, the PCB photos from [the Drop listing for a separate ID80 PCB](https://drop.com/buy/idobao-id80-75-hot-swappable-pcb?mode=guest_open) show 6 LEDs on the top surface (22 total). Should the value be set to 20 (to match the actually existing PCB that I have, even though it is apparently not a final revision — the seller told that the first batch of PCBs had incorrect sizes, therefore a batch of cases with enlarged top bezel was made just for those PCBs, and the first AliExpress buyers, including me, got PCBs and cases from that batch), to 22 (to match what is shown on Drop, although that version also looks like another prototype — it even has some missing components), or left alone (because all those RGB LEDs are not really visible through the metal case)?~~ **Resolved:** I decided to set `RGBLED_NUM` to 20, which is correct for the PCB I got from AliExpress; if a future PCB revision with a different number of LEDs would appear, it would be possible to add support for it in the same way as was done for `yd60mq`.

2. ~~The matrix layout described in the JSON data has a completely empty row (row 6, connected to pin F0; I looked at the PCB, and the corresponding MCU pin does not seem to have any PCB track connected to it). Should this row be removed from the matrix completely, or is keeping the row and column numbers identical to the vendor-provided JSON useful in some way?~~ **Resolved:** I decided to remove the unused row to save EEPROM space in case VIA is enabled.

3. The numbering of rows in the matrix is from bottom to top, which is different from most other keyboards and requires defining `BOOTMAGIC_LITE_ROW` and `BOOTMAGIC_LITE_COLUMN` to make Bootmagic Lite use the Esc key for its activation. I guess it does not really matter, because the only place where those details of the matrix layout are really visible is VIA (the saved JSON keymap contains mappings in the matrix order), and those files are not supposed to be edited manually.

4. Is `CONSOLE_ENABLE` useful to have in the default configuration, or should it be turned off to save some space? With the current code and avr-gcc 8.4.0 I see 88% flash usage for `make id80:default`, and 90% usage for `make id80:via` (this part is not included in the PR yet). Setting `CONSOLE_ENABLE=no` brings the flash usage down to 75% and 76%.

I also tried to add VIA support, and it seems to work well, but the matrix layout must be 100% frozen before enabling VIA, so I did not add files for it yet.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mechmerlin** [comment]
YEESSSS!!! Thank youuu!

**Comment by sigprof** [comment]
After some more thinking I decided to remove the empty row from the matrix, mostly to save the EEPROM space when VIA is enabled. Having a 9×12 matrix leaves just 122 bytes available for dynamic macros; reducing the matrix size to 9×11 leaves 194 bytes for macros.

**Comment by sigprof** [comment]
After looking at #8629, I decided to set `RGBLED_NUM` according to the actual PCB that I got from AliExpress — if boards from Drop will have with a different number of LEDs, this could be fixed later by creating a separate revision, as was done for `yd60mq`.

The RGB behavior is still not ideal, because the underglow effects assume that all LEDs are arranged uniformly around the PCB edges, therefore the extra 4 LEDs on top somewhat break the animation. This could be fixed by invoking `rgblight_set_effect_range(0, 16);` somewhere, but then some custom solution would be needed to control the extra 4 LEDs on top. Given the fact that the stock ID80 case does not provide proper visibility for any of those LEDs, I'm not sure that I should invest any more time into this.

**Comment by zvecr** [comment]
Thanks!

**Comment by orvils** [comment]
Thank you for the work! Just compiled and flashed this onto my board. Works fine.

One question - by default ID80 enters bootloader by holding down Space+B while plugging the USB in, after flashing your firmware this does not seem to work? I did add RESET key on one of the layers, so not a big issue, just wondering.

Waiting on VIA support.

**Comment by sigprof** [comment]
@orvils 
I enabled [Bootmagic Lite](https://docs.qmk.fm/#/feature_bootmagic?id=bootmagic-lite) (hold Esc when plugging the USB in to reset the EEPROM and enter the bootloader) instead of the full bootmagic, therefore Space+B and other full bootmagic combinations no longer work. Apparently Bootmagic Lite is preferred for new boards, and enabling the VIA support also forces `BOOTMAGIC_ENABLE := lite`, so even I would choose to enable full bootmagic, the VIA firmware would still use the lite variant, which would be even more confusing.

Note that the stock firmware apparently has RESET on Fn+Esc, so you do not even need to know about Space+B to replace it.

**Review by lmbundit — COMMENTED** [review]
Hi,

Can you add an alternative for RGB 22?
Thank 

Bundit

**Comment by noroadsleft** [comment]
@lmbundit Are you able to flash a .hex file and test it if I can get you one?

**Comment by lmbundit** [comment]
Hi,

Due to I mod your pcb (id80) in order to add 6 led on upper side (as per
id80 pcb provided LED pad), so your default is 20 leds but it require 22
leds (16 undergrow + 6 upper). I don’t have a problem because i can modify
code and compile by qmk msys but our client prefer to use qmk firmware. So
I would like you add alternative option for 22 leds.

Best Regards,

**Comment by sigprof** [comment]
@lmbundit Actually I already wondered for some time whether the range of LEDs which are used for effects should be limited by default:
```c
    rgblight_set_effect_range(0, 16);
```
The reason is that many lighting effects are set up for a ring of LEDs (actually it's a rectangle on this PCB, but the point is that the effects assume a closed shape where the first LED of the chain is near the last one). Currently the effects assume there are 20 LEDs, but actually only 16 of them are visible if the acrylic bottom is used, and there is a visible discontinuity on the left edge of the keyboard, where LED 0 is near LED 15. Limiting the effect range would solve this issue, but the LEDs on top would no longer light up, unless some custom code to control them is added.

I assume that you want some way to make the ID80 firmware with support for 6 top LEDs available from [config.qmk.fm](https://config.qmk.fm/); however, the problem is that currently the web configurator does not offer any way to set custom options, therefore the only way to provide such an option would be to define another keyboard model (actually two, because there are separate models for the ANSI and ISO versions of the PCB).

I looked what is offered on [idobao.net](https://idobao.net), and it seems that even the most recent “Crystal” version of ID80 (with either transparent acrylic or smokey PC case) would not provide good visibility for the LEDs on top of the PCB (the plate does not have any holes above those LEDs, so you would get just a limited amount of light bleeding through the space between the plate and the PCB). So any modifications which make those LEDs visible would probably require a custom case (or, for that Crystal version, a customized plate) and some soldering to install those LEDs. I'm not sure that the existence of such a custom modification would be a good justification for adding two extra keyboard models to the already huge list. Adding a keymap which enables all LEDs could be possible (that keymap then could be used as a starting point for user keymaps), but it would not help users who want to use the web configurator.

It could be possible to make some hacks for the VIA firmware to make the number of LEDs configurable from there (using the layout options in a non-standard way), but I'm afraid that such hacks would be frowned upon.

**Pull request merged**
