### PR TITLE
Add STK100 keyboard base on STM32WB55

### PR DESCRIPTION
**Pull request by JackyJia73**
Add STK100 keyboard base on STM32WB55

## Description
Add STK100 keyboard base on STM32WB55

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Add STK100 keyboard base on STM32WB55

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
So you've chosen a wireless MCU but not implemented wireless capability?
Or is this an attempt at getting a keyboard merged into QMK in order to satisfy VIA requirements, with no intention of actually providing wireless binding source code?

**Comment by JackyJia73** [comment]
@tzarc As I know，BLE is not allowed by QMK because of license reason. and chibios has no BLE support to stm32wb. actually, I have implemented BLE on STM32WB + QMK，code is ugly and huge but working. ST code use some os like code, need to migrate to chibios. another issue, stm32wb is duel core , BLE stack is on M0. Any, I think it not easy. So, I would like to satisfy via requirement firstly. Do you have any suggestions?  Thank

**Comment by tzarc** [comment]
Consider this comment an official request to provide wireless code, in order to comply with the GPL.
QMK's license -- the GPL -- requires full disclosure of sources upon such a request.

You're more than welcome to keep your code in your fork, but as per the PR checklist QMK is not accepting non-wireless firmwares just to satisfy VIA's requirement of a keyboard in QMK `master`.

Converting this to draft so an accidental merge isn't possible.

**Comment by tzarc** [comment]
For reference:

image

**Comment by JackyJia73** [comment]
@tzarc Thanks for your clarify.

**Comment by JackyJia73** [comment]
@tzarc Add https://github.com/JackyJia73/STM32CubeWB.git to lib.  Do you think this is the right direction ?  Or I need put all STM32CubeWB into kb directory. Thanks

**Comment by JackyJia73** [comment]
@tzarc As STM32wb is dual core mcu，BLE stack is in cpu2. cpu1 interface with cpu2 by HCI(ipcc). All the code can be under kb directory. No need to work on Chibios. I will try work it out this way(using  a few files in STM32cubeWB lib). Thanks

**Comment by Cipulot** [comment]
> @tzarc As STM32wb is dual core mcu，BLE stack is in cpu2. cpu1 interface with cpu2 by HCI(ipcc). All the code can be under kb directory. No need to work on Chibios. I will try work it out this way(using  a few files in STM32cubeWB lib). Thanks 

The approach is interesting and definitely a good way of doing it utilizing the Mailbox approach as STM describes it. Having the second core code up in your fork will allow devs to give feedback and also clean up a bit, since as you mentioned in a prior comment it's a big repo. Lots of people might benefit from this.

**Pull request closed without merging**
