### PR TITLE
audio refactor: replace deprecated PLAY_NOTE_ARRAY

### PR DESCRIPTION
**Pull request by JohSchneider**
remove the deprecated PLAY_NOTE_ARRAY macro throughout the code, and replace it with PLAY_SONG

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR
code cleanup :-)
* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by JohSchneider** [comment]
the replaced macro internally redirected to PLAY_SONG anyway - the keymaps that still used the PLAY_NOTE_ARRAY won't notice the difference => not breaking anything :-)

**Comment by zvecr** [comment]
You might have a different view for what the terminology would mean, however it falls under the following in the linked docs:

> Edits to User Keymaps A user may submit their keymap to QMK, then some time later open a pull request with further updates, only to find it can’t be merged because it was edited in the qmk/qmk_firmware repository. As not all users are proficient at using Git or GitHub, the user may find themself unable to fix the issue on their own.

**Comment by JohSchneider** [comment]
ok - thats a good point

**Comment by JohSchneider** [comment]
is it correct to have this branch set to 'merge into furture' for it to be considered in the next merge window, or should it stay on master?

**Comment by noroadsleft** [comment]
If you want this to go in through the next Breaking Changes cycle, it needs to target the `future` branch, and be ready to ship by next Saturday (unless we change the timeline).

There are [some details in the docs](https://docs.qmk.fm/#/breaking_changes_instructions) to which your PR will need to conform to be considered for the next Breaking Changes cycle. Of particular note, you will need to add a changelog entry to this PR to have it merged in.

**Comment by JohSchneider** [comment]
ok, thanks for the confirmation
a chagnelog is presetn, the PR is - at least from my side - ready... all thats missing are reiviews :-)

**Comment by noroadsleft** [comment]
@JohSchneider Would you mind rebasing this on `future` one last time?

**Comment by JohSchneider** [comment]
git rebase origin/future; git push --force; echo "done :-)"

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
