### PR TITLE
Added Contra keyboard support

### PR DESCRIPTION
**Pull request by adiron**
The configuration came from a source distribution of the firmware on the
Contra's official website available here under "firmware":
https://cartel.ltd/contra/

I have also included a simple MIDI keymap. (Which works)

This is my first time contributing anything to QMK so sorry in advance if I get stuff wrong.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Nice! Would you mind adding a [readme.md to the keyboard directory following this template](https://docs.qmk.fm/documentation_templates.html#keyboard-readmemd-template)? 

These variables in the `config.h` can be updated as well:

    #define MANUFACTURER Cartel
    #define PRODUCT Contra

**Comment by adiron** [comment]
Sure, I can make the changes. However I'm not sure I should be the maintainer here as I have very little time and knowhow when it comes to keyboard. I'm just some guy who managed to get it to work almost by mistake. 🤷‍♂️  Should I leave it blank?

**Comment by jackhumbert** [comment]
You can put the QMK Community there :) it should be Cartel, but I'm not sure how active they are on Github.

**Comment by adiron** [comment]
Alright, there it is

**Comment by jackhumbert** [comment]
Perfect - thanks! :)

**Pull request merged**
