### PR TITLE
Add mechlovin9 rev2 PCB

### PR DESCRIPTION
**Pull request by mechlovin**
## Description

Move mechlovin9 PCB from `mechlovin/hannah65/mechlovin9` to `mechlovin/mechlovin9`
And add mechlovin9 rev.2

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mechlovin** [comment]
bump

**Review by drashna — APPROVED** [review]
Should target develop, I think.

Otherwise, looks fine.

**Comment by mechlovin** [comment]
> Should target develop

How do I do it? 
Im noob with it, sorry.

**Comment by drashna** [comment]
If you edit the title, right below it, it well let you choose a branch to target.  Select `develop` and save it. 

You may need to rebase after doing so, but probably not, in this case.

**Comment by mechlovin** [comment]
Got it, Thank you :D

**Comment by drashna** [comment]
This does have a merge conflict now.

**Comment by mechlovin** [comment]
The conflict has been resolved.

**Comment by drashna** [comment]
Looks like this needs a rebase, maybe.  It has some additional changes/commits that it shouldn't.

**Comment by mechlovin** [comment]
Hi @drashna.
Is there anything else I should do?
Thank you.

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Comment by mechlovin** [comment]
Hi @drashna 

I should have targeted this to Master. Should I follow this instruction here: https://stackoverflow.com/questions/7161860/how-to-move-the-current-working-branch-to-master-branch-in-git?fbclid=IwAR1eVpktkOBiVj8x3ydwR10WVvjrECheZJkkILdiOzd8QOPukaR1vdp3CvA

Really sorry for the back and forth.

**Pull request merged**
