### PR TITLE
Program Yoink! refactor

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

The existing codebase has support for two different PCBs. This PR splits the support into two codebases with shared code, and aims to verify the Configurator implementation.

cc @melonbred (keyboard maintainer)

This PR is a follow-up to #11558.

## Types of Changes

- [x] Bugfix
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
@melonbred,

Here's the pull request to split up the existing codebase into one codebase each for Staggered and Ortho versions.

What we'll need to do:

## 1. Test each keymap for correct functionality.

Making sure each key is on the correct switch, etc. The keymaps should work exactly the same when compiled from this branch, as they do when compiled from the current QMK `master` branch. The only difference should be the device name that shows in your operating system (`Program Yoink! Staggered` or `Program Yoink! Ortho` as appropriate), and the Ortho PCB now has a different USB Device Product ID (`0xF10C` instead of `0xF10B`).

Once that's done, we move to...

## 2. Merging this PR and testing the Configurator implementation.

After this PR is merged, Configurator can compile firmware that includes the changes this PR makes. I'll provide some JSON files to you, which you will import into Configurator, and compile without changing the keymap, to verify two things:

1. That the labels shown on Configurator's user interface match what happens when that key is pressed on the flashed board, and
2. That the firmware works the same as the keymaps being compiled locally from QMK source, with the exception of the Combos. (Unfortunately, there's no Configurator work-around for Combos like there is for encoders.)

If everything checks out at this point, we're done. If not, I'll be able to work out what's still broken and fix it.

----

Do you use Git through GitHub's website only, or do you have a local clone of the `qmk_firmware` repository? I can give some tips to try to smooth out this whole review/test process, if you need.

Let me know.

**Comment by melonbred** [comment]
@noroadsleft Thank you for preparing this PR!

I have a local clone of the `qmk_firmware` repository and use GitHub desktop to update/pull/push. If you have any tips on how to make the workflow smoother, I certainly an open to trying them.

I'll start compiling and testing firmware tonight and let you know if I run into any issues. Thanks again!

**Comment by noroadsleft** [comment]
@melonbred,

Okay, in GitHub Desktop, all you need to do is click the area where it shows what branch you're currently on, and the menu that opens is a list with two tabs: Branches and Pull Requests. Change to the Pull Request tab, type in `11636`, and hit Enter. GitHub Desktop will do some fetching, and you'll end up with a branch named `pr/11636`. (GitHub Desktop may warn you about CRLF line endings in `desktop.ini` - just keep trying and eventually it'll go through if that happens.)

At this point, you should be go to your `qmk_firmware` directory and compile the firmware from this branch as you normally would, using the following `make` command:

```
make program_yoink/staggered:all program_yoink/ortho:all
```

When that's done, you should have four new HEX files:

```
program_yoink_ortho_default.hex
program_yoink_ortho_ortho_split.hex
program_yoink_staggered_default.hex
program_yoink_staggered_split_bar.hex
```

Should be self-explanatory what keymap each one is – they're simply renamed from before. Please test each keymap for correct functionality and report back your findings.

**Comment by melonbred** [comment]
@noroadsleft I just compiled and flashed the hex files per your instructions, and everything is working as intended.

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by noroadsleft** [comment]
@melonbred k, Time for Phase 2:

[program_yoink_configurator_jsons.zip](https://github.com/qmk/qmk_firmware/files/5861032/program_yoink_configurator_jsons.zip)

Four JSON files here. Please check:

* That the labels shown on Configurator's user interface match what happens when that key is pressed on the flashed board, and
* That the firmware works the same as the keymaps being compiled locally from QMK source, with the exception of the Combos.

**Comment by melonbred** [comment]
@noroadsleft Thanks for providing the JSONs. I have confirmed that the labels shown on Configurtaotr's UI matches key presses, and the firmware compiled locally works the same. I've also changed some keys in Configurator, recompiled and flash for additional verification, and all works as expected.

Regarding the swap in Slash and Up for `ortho_split`, that was an oversight during my review and testing during Phase 1. Slash and Up should for `ortho_split` should conform with `ortho_default`. However, the keys still function as shown in Configurator and if compiled locally. Should I submit a PR to pick up this revision?

Please let me know if there's anything else I can do for this. Thank you for helping me through this process so far. I've definitely been learning a lot.

**Comment by noroadsleft** [comment]
@melonbred So the Ortho split spacebar keymap only needs a keymap fix. If you have that ready you can go ahead and submit it as a new pull request.

**Pull request merged**
