### PR TITLE
python scripts to generate the led and rgb matrix header files with all effects to disable

### PR DESCRIPTION
**Pull request by agodinhost**
python scripts to generate the led and rgb matrix header files with all effects to disable

## Description

I added two python scripts to qmk cli,
   generate-rgb-matrix-header and
   generate-led-matrix-header,
to generated a complete header file to disable all led and rgb matrix effects.

The sample output, disable_all_led_matrix.h and disable_all_rgb_matrix, were added
into the quantum/led_matrix_animations and quantum/rgb_matrix_animations folders
and are ready to use.

These headers will help in cases where you only want to use a few effects without
having to enumerate all effects that are already in the animations folder.

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
We're actually in the process of inverting the logic such that animations are opt-in, rather than opt-out.
`develop` merge today should bring that bunch of changes in, and we've got a transitional header that continues with the original model.

Might suggest updating `master` later today once the `develop` branch gets merged -- this might not be as relevant?

**Comment by drashna** [comment]
I think we were actually headed in the direction of explicitly enabling animations, rather than disabling them. 

This way, new animations can be added without causing existing boards to go over firmware limits.

**Comment by agodinhost** [comment]
> I think we were actually headed in the direction of explicitly enabling animations, rather than disabling them.
> 
> This way, new animations can be added without causing existing boards to go over firmware limits.

Explicitly enabling animations would force people that are already using all animations to set ALL required defines. I think it's an inversion of the same idea. My guess is that this script could be used to help with this inversion of logic yet.

My idea was to make the code cleaner - I saw a lot of user layouts with way too many #defines that could be in just one place -without forcing then to copy and paste the complete list of defines because they are kinda lazy to see what we have into the animations folder (imho).

my config.h using this approach:
#include "quantum/rgb_matrix_animations/disable_all_rgb_matrix.h"
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_RAINDROPS
#undef DISABLE_RGB_MATRIX_RAINDROPS
#undef DISABLE_RGB_MATRIX_DIGITAL_RAIN

**Comment by drashna** [comment]
The thing is, some of the changes have already been made: 
https://github.com/qmk/qmk_firmware/commit/7da97c293da851851c204af065a0c8d2f884effd

So, either it would need to continue in the direction that it's in, or the previous commit reverted.  

However, there already has been discussion about the animation stuff, and I believe that the general direction was to change it to explicitly enabled, rather than explicitly disabled.  The reason for this is that every time new animations are added, it will increase the compiled size.  And that risks making the firmware too large to compile for existing boards.  For most ARM boards, this isn't a problem.  But for a lot of the AVR boards (eg, the ones using atmega32u4s) this has already started to be a problem.  

For instance: https://github.com/qmk/qmk_firmware/pull/13677

**Comment by agodinhost** [comment]
Yup, I have one KPRepublic BM68rgb and this was my first motivation, I had to reduce my hex size however I wanted some lights blinking.

This same script could create the led_matrix_legacy_enables.h or rgb_matrix_legacy_enables.h instead. It would help to keep these files up to date for those with more animations - they could copy their animations into some user sub folder and then run this script to recreate the headers.

**Comment by skullydazed** [comment]
> This same script could create the led_matrix_legacy_enables.h or rgb_matrix_legacy_enables.h instead. It would help to keep these files up to date for those with more animations - they could copy their animations into some user sub folder and then run this script to recreate the headers.

Speaking on this from a high level, longer term perspective-

We are very early in the process of [moving away from `config.h` and to `info.json`](https://hackmd.io/XP62n35EQ7qt3N0XGfwxWg) for configuration. We're building out schemas and infrastructure that will allow users to configure their keyboard using yet to be written tooling, such as GUIs and TUIs. When new animations are added it's expected they'll show up in this tooling automatically so that users will be able to enable them then.

I'd you'd like to help that happen sooner you can work on improving `info.json` support for rgb matrix. No one is working on that yet and it's pretty far down on my list of things to work on. The process is pretty simple:

* Make sure all the documented options on the rgb matrix page have `info.json` equivalents: <https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-lighting>
* I've written a doc on the mechanics of that here: <https://docs.qmk.fm/#/data_driven_config?id=data-driven-configuration>
* When you need to add new keys put some thought into the best structure for them. We want a balance between normalized data and a relatively flat structure.
* Don't do anything that would require incrementing the API version. We're letting V1 grow as it may and planning to do a lot of data normalization for V2.

There is a pretty big caveat when it comes to implementing rgb matrix- the `g_is31_leds` array. That is a pretty big piece that we want to integrate into layouts, but there are a lot of open questions still to work out for that. If you decide to take this project this should not be included in your work.

**Comment by agodinhost** [comment]
> 
> Speaking on this from a high level, longer term perspective-
> 
> We are very early in the process of [moving away from `config.h` and to `info.json`](https://hackmd.io/XP62n35EQ7qt3N0XGfwxWg) for configuration. We're building out schemas and infrastructure that will allow users to configure their keyboard using yet to be written tooling, such as GUIs and TUIs. When new animations are added it's expected they'll show up in this tooling automatically so that users will be able to enable them then.
> 
Okay, understood.
Should I close this PR?

> I'd you'd like to help that happen sooner you can work on improving `info.json` support for rgb matrix. No one is working on that yet and it's pretty far down on my list of things to work on. The process is pretty simple:
> 
> * Make sure all the documented options on the rgb matrix page have `info.json` equivalents: https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-lighting
> * I've written a doc on the mechanics of that here: https://docs.qmk.fm/#/data_driven_config?id=data-driven-configuration
> * When you need to add new keys put some thought into the best structure for them. We want a balance between normalized data and a relatively flat structure.
> * Don't do anything that would require incrementing the API version. We're letting V1 grow as it may and planning to do a lot of data normalization for V2.
> 
> There is a pretty big caveat when it comes to implementing rgb matrix- the `g_is31_leds` array. That is a pretty big piece that we want to integrate into layouts, but there are a lot of open questions still to work out for that. If you decide to take this project this should not be included in your work.

I like this idea of tooling and I would be glad to help.
I think I can write some python scripts to parse the info you mentioned above - but I'm kinda confuse - the URL that you linked is more "generic", it seems to me that it covers ALL main aspects of the build configuration.

Thinking about the whole QMK project - I saw a lot of layouts and user folders that were discontinued, aborted or are not mass produced (used only once or provided as samples) and I'm wondering about the effort it would take to parse this info from them.

Would not be better to split these folders away first? I think that a formal folder reorganization would be required in order to filter all unused, deprecated or unsupported folders - it would help to reduce this tooling start up by limiting our goal, and setting a standard that wasn't settled before.

More food for thought.
I'm afraid of the amount of configuration files that will be laying around - would not be better to keep this parsed info into a database? It would help to reduce the final number of files and it would help this "configuration management" effort by centralizing all info in just one place.

**Comment by skullydazed** [comment]
> Okay, understood.
> Should I close this PR?

Yes, I don't think we want to use this.

> I like this idea of tooling and I would be glad to help.
> I think I can write some python scripts to parse the info you mentioned above - but I'm kinda confuse - the URL that you linked is more "generic", it seems to me that it covers ALL main aspects of the build configuration.

The data driven config page does attempt to be generic, but it also documents exactly what you need to do here- add new `info.json` keys that map to existing `config.h` and `rules.mk` configurations.

> Thinking about the whole QMK project - I saw a lot of layouts and user folders that were discontinued, aborted or are not mass produced (used only once or provided as samples) and I'm wondering about the effort it would take to parse this info from them.
> 
> Would not be better to split these folders away first? I think that a formal folder reorganization would be required in order to filter all unused, deprecated or unsupported folders - it would help to reduce this tooling start up by limiting our goal, and setting a standard that wasn't settled before.

We try to balance competing interests. While I agree that there is a lot of stuff in the repo that seems redundant, that is exactly the sort of activity that pulls people into the qmk community. Plus, having a large set of things to parse helps to keep the bug count low by giving us lots of test cases. :)

> I'm afraid of the amount of configuration files that will be laying around - would not be better to keep this parsed info into a database? It would help to reduce the final number of files and it would help this "configuration management" effort by centralizing all info in just one place.

This is another place where we are balancing competing interests. If we centralize this in a database we make the configuration harder to examine, because you will have to use a tool. Many of the people maintaining the C side of QMK are already uncomfortable with the amount of python sneaking into the build process- using a database instead would aggravate that situation. 

I have been considering doing some caching using something similar to `qmk generate-api`, but to do that right is a pretty serious reworking of the way info.json is parsed and I think that will be a pretty big project on its own.

**Pull request closed without merging**
