### PR TITLE
Add central location for ChibiOS defines

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Given the ChibiOS HAL doesnt have a unified API, we end up in a HAL of HAL's situation where various code areas have to sniff config options and compile in different blocks of code. Unfortunately it doesn't look like there are internal "this board is using gpiov2" defines we can leverage.

Rather than have these defines duplicated, this PR aims to add a central location to manage the mcu logic.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by yanfali** [comment]
Where is this file? "chibios_config.h"

**Comment by zvecr** [comment]
On my machine, which everyone clearly has access to....

**Comment by drashna** [comment]
ah, good ol' `git commit -a` rather than `git add` (or `git commit /path/to/fie`), I'm guessing 😆 

Also, `ergodox_stm32` doesn't like this change:
```bash
drivers/arm/i2c_master.c:37:5: error: 'I2C1_OPMODE' undeclared here (not in a function)
     I2C1_OPMODE,
     ^~~~~~~~~~~
 | 
 | 
 | 
tmk_core/rules.mk:377: recipe for target '.build/obj_ergodox_stm32_default/i2c_master.o' failed
make[1]: *** [.build/obj_ergodox_stm32_default/i2c_master.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

It uses an STM32F103, IIRC.

**Comment by zvecr** [comment]
Rebased now #7571 is in, carried over the F4 logic.

**Pull request merged**
