### PR TITLE
Add macro for momentarily switching to a layer while some mods are active

### PR DESCRIPTION
**Pull request by snyman**
Plus cleaning up some semi-related documentation.

### CODE REVIEW

**Comment by DanielGGordon** [comment]
I've always wanted this feature! I haven't had a chance to look through your change yet, but would this support multiple modifiers? Like switch to Layer 2 with control and shift?

**Comment by snyman** [comment]
Yes! You can OR the modifiers together, e.g. `LM(LAYER_2, MOD_LCTL | MOD_LSFT)`. The possible values are the left-side values in the `mods_bit` enum in `tmk_core/common/action_code.h`.

**Comment by drashna** [comment]
Couldn't this be done with `layer_state_set_user`, by setting and clearing mods, as well?

**Comment by DanielGGordon** [comment]
Also what would be required to do a similar feature for `TT`?

**Comment by drashna** [comment]
@DanielGGordon No. But it would basically be hard coded for a layer.   

Basically, it would be something like: 
```
uint32_t layer_state_set_user(uint32_t state) {
  if (biton32(state) == _ALTLAYER) {
    register_code (KC_LALT);
  } else {
    unregister_code(KC_LALT);
  }
  reture state;
}
```

Which would enable "LALT" for that layer, and turn it off, if changed to something else.   Or you could get more complicated it you read the layer mask, rather than running it through `biton32`.

But I suppose, in the long run, it comes out about the same.

**Comment by snyman** [comment]
@drashna I don't think `layer_state_set_user` would actually work for my use-case, because I have two different keys to go to the layer(s) in question: one without the modifier, and one with the modifier. If I understand your code correctly, switching to `_ALTLAYER` must always have left alt active, meaning I'd need to duplicate my layers to get the same result.

The way I was getting this behaviour before was using the `fn_actions` array to create custom keycodes that use the tmk_core macros (`ACTION_...`) directly, but when I saw that many of those had been given more user-friendly macros I decided to add this one to round out the functionality I needed. However, given how little space there seems to be in the `quantum_keycodes` enum, I would understand if you didn't want to include this change in favor of a potentially more useful feature in the future.

@DanielGGordon Unfortunately adding similar functionality to `TT` would be difficult. First, you'd have to either find an available 256-long block in `quantum_keycodes` enum (not easy), or add a restriction to TT for only the first 16 layers (potentially breaking backwards-compatibility). Also, even if you did that, there's no convenient functionality already in tmk_core to combine tap-toggle a layer with mods active. I'm not sure how much work it would be to add that, but I suspect it would not be trivial.

**Comment by jackhumbert** [comment]
Awesome! Thanks :)

**Comment by DanielGGordon** [comment]
@snyman now you have given me a reason to get my local qmk build up to date!

**Pull request merged**
