### PR TITLE
Fix for ES_ACUT dead key for spanish languaje

### PR DESCRIPTION
**Pull request by madkoding**
## Description

Fix issue with ES_ACUTE ´ dead key, missing in sendstring_spanish for spanish iso layout

## Types of Changes

- [ ] Core
- [ x ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

### CODE REVIEW

**Comment by elpekenin** [comment]
My code for making a code-block on discord works fine with both versions tho (gotta say im working on a SonixQMK board, but im pretty sure the repo is up to date with main one)

Used on a tap-dance, probably that doesnt matter, but saying just in case
```c
SEND_STRING("```" SS_LSFT("\n\n") "```");
```

**Review by fauxpark — APPROVED** [review]

**Review by fauxpark — COMMENTED** [review]
Actually, this is not correct. The bit being changed here corresponds to the ASCII character ´{´, which of course is not a dead key.

**Comment by madkoding** [comment]
> Actually, this is not correct. The bit being changed here corresponds to the ASCII character `{`, which of course is not a dead key.

oh, but this references to spanish keyboard layout where ASCII character `{` correspond to character ´ which is a dead key

**Comment by fauxpark** [comment]
Send String only supports ASCII characters.

To type a `{` with this layout you have to press `AltGr+´`. `´` is a dead key but is not part of ASCII. `{` is in ASCII, but is not a dead key, so it does not need that bit set in `ascii_to_dead_lut`.

**Pull request closed without merging**
