### PR TITLE
[Core] Add CRC8 calculation subsystem to quantum

### PR DESCRIPTION
**Pull request by KarlK90**
* Intended usage is data validation in [extensible split data sync code](https://github.com/qmk/qmk_firmware/pull/11930).
* Default is space efficient algorithm with opt-in fast table based algorithm by `#define CRC8_USE_TABLE` switch.
* Define switches for size and speed optimized versions, the default is size optimized by using `uint_least8_t` as datatype for calculations.
  * `#define CRC8_OPTIMIZE_SPEED` uses `uint_fast8_t` as datatype for calculations, this only affects 32-bit Archs like ARM and RISC-V.
  * Placeholder `crc_init()` function for hardware backed crc calculation, not implemented yet.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* none

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [?] My change requires a change to the documentation.
- [?] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by tzarc — APPROVED** [review]
It's just what I always wanted. 

Thanks for helping get this stuff over the line!

**Comment by tzarc** [comment]
For clarity, I'd been in discussion with @KarlK90 who had implemented the CRC8 using on-chip hardware -- I suggested that perhaps we formalise the CRC "subsystem" so that we can start adding things like the ChibiOS hardware drivers down the line.

**Comment by KarlK90** [comment]
For reference this is what a [hardware implementation could look like.](https://github.com/KarlK90/qmk_firmware/blob/6bddf560f6f5d6567855fd805ad3ad3b794c7b0f/drivers/chibios/crc_hardware.c). From personal testing the fast table based crc8 implementation is faster.

**Review by drashna — APPROVED** [review]
`__attribute__((weak))` ✅

**Comment by drashna** [comment]
Also, has merge conflict

**Review by zvecr — APPROVED** [review]

**Pull request merged**
