### PR TITLE
Updated Initial MBI5042GP 16-bit LED PWM driver release

### PR DESCRIPTION
**Pull request by fishman**
## Preface

This is based on https://github.com/qmk/qmk_firmware/pull/5748

Numicro support was just merged into upstream ChibiOS

https://github.com/ChibiOS/ChibiOS-Contrib/pull/226

## Description

Macroblock MBI5042GP 16-bit 16 output PWM LED driver for QMK

I had to add a 16-bit CIE1931 curve dataset and extend the driver calling code in quantum, otherwise everything is in its own drivers folder (mbi5042gp)

This is part 1 of the Ducky One2mini integration into QMK (hopefully only 2 other parts for the full integration)

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — COMMENTED** [review]
I think we would want to make this driver more platform agnostic if at all possible, given it's being added to `VALID_MATRIX_TYPES`. The fact that it doesn't seem to be using I2C or SPI complicates things :/

**Comment by fishman** [comment]
> I think we would want to make this driver more platform agnostic if at all possible, given it's being added to `VALID_MATRIX_TYPES`. The fact that it doesn't seem to be using I2C or SPI complicates things :/

What's the recommendation here?

**Comment by fishman** [comment]
@fauxpark you're saying the interrupt vector and stuff like that are too nuvoton specific functions? where would you move these?

**Comment by fauxpark** [comment]
@fishman it's not a question of moving it, the issue is that if you are adding a driver to core then it is reasonably expected to be available on both ARM and AVR. Considering how this driver works, and the fact that exactly one keyboard seems to be using it, IMO it can live in the keyboard directory for the time being, unless you want to provide an AVR implementation as well (if you don't that is perfectly fine by me).

**Comment by fishman** [comment]
Moved it to the keyboard

**Pull request closed without merging**
