### PR TITLE
layout(infinity ergodox): dudeofawesome's layout

### PR DESCRIPTION
**Pull request by dudeofawesome**
A basic ErgoDox layout with Planck-like tri-layer support.

ErgoDox Layout

## Features

- Planck-like tri-layer
- Workman layout
- Work-in-progress gaming layer
- Numpad
- LCD colors are linked together, like the default KLL firmware

### CODE REVIEW

**Comment by jackhumbert** [comment]
I'm not 100% familiar with the visualizer, but I think you can override the default by copying the .c to your keymap folder, right @fredizzimo?

Don't worry about Travis failing - that looks to be a different keymap.

**Comment by dudeofawesome** [comment]
Whoops, I had been working on the main visualizer file before realizing I could copy it in to my keymap folder. I thought I'd reverted all my changes to the main one, but I guess not. I'll fix that.

**Comment by dudeofawesome** [comment]
@jackhumbert I've reverted the changes to the main `visualizer.c`

**Comment by jackhumbert** [comment]
Cool! Thanks :)

**Pull request merged**
