### PR TITLE
Frenchdev v1

### PR DESCRIPTION
**Pull request by npoirey**
A new splitted keyboard.
lot's of tinkering involved since i'm not familiar with bit manipulation but I think I got it okay, at least it works as expected :)

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! Would you mind hosting the image elsewhere (like imgur), and linking it the readme? We're trying to keep images out of the repo :)

**Comment by npoirey** [comment]
no problem, it's done :)

And no, I don't have a pcb nor will I ever make one since the keys aren't all on the same level, it's handwired.

**Comment by jackhumbert** [comment]
Nice! It might make sense to put this into the `/keyboards/handwired/` folder then :) I see that you have a subproject - this isn't really supported in the handwired folder, though. Do you have an explicit need for the subproject?

**Comment by npoirey** [comment]
I guess not, it was part of the transition from V0 to V1 but now I erased everything from v0 since it was a bad idea to ditch I2C. I guess I can move it to handwired if you want. I also have .svg files for laser cut that I could add if it's allowed, but they need to be reworked since they were for the v0 and some things moved around inside.

**Comment by jackhumbert** [comment]
Cool! Yeah, I think handwired's a good fit :) we're getting away from hosting hardware files here, but you could put them/an about page in qmk/qmk.fm! [There's some more info on that here](https://docs.qmk.fm/adding_a_keyboard_to_qmk.html)! Just added this page today :)

**Comment by npoirey** [comment]
Okay, I will do that and update this thread when done, thanks :)

**Comment by Dbroqua** [comment]
Salut,

Sympa ton clavier et encore plus d'en voir un Bépo ^^ .

**Comment by npoirey** [comment]
Okay, everything should be good now :) 

@Dbroqua merci ^^

**Comment by jackhumbert** [comment]
Awesome! Thanks :)

**Pull request merged**
