### PR TITLE
Adding my kbd67mkii keymap and some changes to kumo

### PR DESCRIPTION
**Pull request by kingwangwong**
## Description
Just a keymap for my kbd67mkii and small changes to kumo keymap

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ x] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — COMMENTED** [review]
Could you add a GPL2+ compatible license header to these files?

**Comment by drashna** [comment]
Also, there looks like there is a merge conflict here, that needs to be resolved.

**Comment by kingwangwong** [comment]
I'm really sorry I have no idea on how to do any of that, I think I'll stop contributing

**Comment by drashna** [comment]
> I'm really sorry I have no idea on how to do any of that, I think I'll stop contributing

Sorry about that.  We are more than willing to help out, if you need/want help!  We'd much rather spend the time helping out and explaining than have you stop!  But it's easy for us to fall into the trap of assuming that you're familiar with the PR and review process. Not everyone is.  So, if you have ANY questions, feel free to ask here, on the QMK Discord, or PM me.

For the GPL2+ license headers, I mean something like this: 
https://github.com/qmk/qmk_firmware/blob/e4a4ed3b0c053ebed902a28b2a8f68cdf78597f5/quantum/template/base/keyboard.c#L1-L15

Replace `%YoUR_NAME% with your username/email address/etc
As for editing, you can edit directly for the github UI, or you can edit it locally, commit and push via git, and that will update the PR. 

If you would like, I should be able to do this for you.


As for the merge conflict, below the last reply, there should be a "Resolve conflicts" button. You can click that and edit the files that have conflicts. 

https://docs.qmk.fm/#/newbs_git_resolving_merge_conflicts

This has some useful info on how to resolve the conflicts, if your not sure. 

We can also do this, but in general, it's much more polite to let the contributor (you) handle that.

**Comment by kingwangwong** [comment]
Thank you for your empathy here, I've done to the best of my ability to fix this. I will remember to put the GPL2 license at the top from now on

**Review by noroadsleft — APPROVED** [review]
Looks good to me.

@kingwangwong Don't worry about not knowing things – all of us started out as novices and learned as we went. Lord knows my first couple of pull requests were far from ideal. I never imagined when I started contributing to QMK two years ago that I'd be here now, helping to actually maintain it.

One of the things I love about being part of this is the active and vibrant community around QMK, comprised of people from all different walks of life, from all over the world. Without people just like you, **that community doesn't exist.** So truly, **thank you** for getting involved. No matter how small or great your contribution, we're glad to have you here.

**Review by fauxpark — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
