### PR TITLE
Reclassify alpha/special auto shift keys for software Dvorak

### PR DESCRIPTION
**Pull request by p00ya**
## Description

Currently the autoshift macros (NO_AUTO_SHIFT_SPECIAL and NO_AUTO_SHIFT_ALPHA) may behave in surpising ways when remapping QWERTY -> Dvorak in software (i.e. the OS, rather than QMK).  For example, if NO_AUTO_SHIFT_SPECIAL is defined (and NO_AUTO_SHIFT_ALPHA is not defined), then KC_Q *will* be auto-shifted, but this will be remapped by the OS to shift-quote, seemingly inconsistent with the intent to not auto shift punctuation characters.

This PR adds alternative logic conditional on a new INVERT_DVORAK_FOR_AUTO_SHIFT preprocessor symbol that classifies keys as SPECIAL/ALPHA according to what that would be *after* an additional layer of remapping.

This approach isn't really scalable to other software remaps, so I'll understand if you don't want to merge it into the main QMK repo.  That said, I know I'm not the only one remapping US -> Dvorak in software, since there's already some keymaps designed for that.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

N/A

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by p00ya** [comment]
FWIW, I do have an idea for a more scalable (i.e. support more remapping combinations without unreadable C preprocessor code) implementation.  The idea is to have a lookup table that performs the remapping.  So the `switch` in `process_auto_shift.c` would look like:

```
#ifdef INVERT_KEYCODES_FOR_AUTO_SHIFT
if (keycode < sizeof(keycode_inversion_table)) {
  keycode = keycode_inversion_table[keycode];
}
#endif
switch (keycode) {
```

Then the keymap would be expected to define `INVERT_KEYCODES_FOR_AUTO_SHIFT` and `uint8_t keycode_inversion_table[64]`, with some convenience headers for pre-defining the table for common software-remaps like dvorak and colemak.  The downsides are that it is more complex to use and that it increases the binary size with a 64-byte lookup table (and that's with the hack of limiting the input space to 6-bit and the output space to 8-bit, rather than supporting the full uint16_t keycodes).

**Comment by IsaacElenbaas** [comment]
> I'm not the only one remapping US -> Dvorak in software, since there's already some keymaps designed for that.

Why? Not saying this shouldn't be added, but it seems much easier to just rearrange on the keyboard-end and have the OS not worry about screwing with stuff. It also makes your keyboard more portable. Do you switch layouts OS-end often?

**Comment by skullydazed** [comment]
> it seems much easier to just rearrange on the keyboard-end and have the OS not worry about screwing with stuff.

I can't speak for anyone else, but in my own experience it's best to let the OS remap. The primary reason is that it's much easier to allow someone else to use your computer (you can switch back easily and temporarily) and some software (typically games) reads the keycodes directly so you end up remapping them anyway.

**Comment by noroadsleft** [comment]
> I can't speak for anyone else, but in my own experience it's best to let the OS remap. The primary reason is that it's much easier to allow someone else to use your computer (you can switch back easily and temporarily) and some software (typically games) reads the keycodes directly so you end up remapping them anyway.

For context (though I don't use Auto Shift), I deal with exactly this.

I'm a pretty avid player of arena FPS games. I've played Quake II (released December 1997) pretty much since it came out, and it locks any typed input to US QWERTY, regardless of what you have set in the operating system. I worked out a whole convoluted layer system such that when I'm entering text, it's in Dvorak, but game input is QWERTY, so I didn't have to rewrite my entire game config.

**Comment by p00ya** [comment]
> > I'm not the only one remapping US -> Dvorak in software, since there's already some keymaps designed for that.
> 
> Why? Not saying this shouldn't be added, but it seems much easier to just rearrange on the keyboard-end and have the OS not worry about screwing with stuff. It also makes your keyboard more portable. Do you switch layouts OS-end often?

To add to what the others said - my keyboard never moves from its place on my desk, but my laptop *does* move around with me.  So when I take my laptop to the couch and type on its built-in keyboard (*gasp*), using OS remapping, I can still seamlessly type in Dvorak.

All that said, I may convert this PR to a draft since I'm not proud of the code readability/scalability (and it has conflicts with other AS PRs), so don't want to waste too much of the QMK maintainers' time.  It's there for folks to patch in if they want.

**Comment by drashna** [comment]
> I can't speak for anyone else, but in my own experience it's best to let the OS remap. The primary reason is that it's much easier to allow someone else to use your computer (you can switch back easily and temporarily) and some software (typically games) reads the keycodes directly so you end up remapping them anyway.

I disagree.  I have ... a lot of layouts on my keyboards. So somebody could attempt to use key keyboards, especially if I switch back to qwerty on the keyboard. 


That said, I don't think that this is the right way to handle this.  I think something more like how music mask is handled may be better. 

https://docs.qmk.fm/#/feature_audio?id=music-mask

Eg, add a define, and it adds a user hook that can be used to enable/disable autoshift per key.  Though, maybe with an int8, so you can use -1 for "not handled", and true/false.

**Comment by IsaacElenbaas** [comment]
@drashna My original custom auto shifts pull request worked like that, but I disliked the negative return values. It likely won't be merged anyway, as me and @p00ya are working on getting custom shift values working with keyrepeat and what I have so far is cleaner than the old, but it could do the same. We could add a section of the docs with starter configs for different layouts, or make additional functions hidden behind \#defines that are called if the user doesn't customize the key themselves and some layout variable is set to what the function corresponds to.

**Pull request closed without merging**
