### PR TITLE
Add Arm Teensys to mcu_selection.mk

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

🍔

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
@Oryhara just a heads up as this modifies your keymap's rules.mk (only to remove stuff that is already inherited from the top-level rules.mk, and the MCU selection makefile)

**Comment by fauxpark** [comment]
I did notice that, but I'm under the impression the onekey boards are kind of "example" code (as well as a testbed), so I'd prefer to reduce the boilerplate even if no real boards are using the Teensy LC yet. It should also help with the MCU selection in the new keyboard Python script.

**Comment by zvecr** [comment]
MK20DX128 was infinity60, though that does remind me i have yet to PT the lc support for 40percentclub/i75.

**Comment by fauxpark** [comment]
Don't know why I read that as MKL26Z64... my answer then is "for completeness".

**Comment by noroadsleft** [comment]
@Oryhara Are you okay with the changes to `keyboards/ergodox_infinity/keymaps/halfkeyboard/rules.mk` here?

**Comment by fauxpark** [comment]
In the interest of pushing this along I've rolled back the changes to the halfkeyboard keymap - this is no longer a breaking change.

**Pull request merged**
