### PR TITLE
XD75 keymap -  Germanized

### PR DESCRIPTION
**Pull request by hypnocrat**
A keymap for the XD75RE.  
Customized for German layout users and switching from staggered QWERTZ, this keeps most alphanumerics in their default positions. 
Nav keys are on the default layer, many modifiers are dual use. Designed to be used together with an additional macropad, doesn't contain a numpad layer in the most current version.

### CODE REVIEW

**Comment by skullydazed** [comment]
Thanks for your contribution!

Can you please change your keymap name to be all lowercase and remove the Old_Layouts directory and keymap.example? We like to keep everything tidy and easy to browse through.

**Comment by hypnocrat** [comment]
I removed the relevant files and fixed the capitalization :)

**Comment by skullydazed** [comment]
Thanks, that's looking better!

It looks like the case change didn't take though. You may have to `git mv Germanized temp_name && git mv temp_name germanized` to have that work.

**Comment by hypnocrat** [comment]
Should be fixed now, thanks for the help!

**Comment by jackhumbert** [comment]
Perfect :) thanks!

**Pull request merged**
