### PR TITLE
Add sophisticated encoder keymap options for Viendi 8L

### PR DESCRIPTION
**Pull request by Gondolindrim**
## Description

On the [original PR](https://github.com/qmk/qmk_firmware/pull/17943), the `default` keymap had the vanilla encoder behavior with volume control, as per requests of the PR reviewers on the basis the default behavior should be as simple as possible, especially given the QMK configurator tool. However, the VIA keymap of the board contained the encoder behavior originally intended. On [a following PR](https://github.com/qmk/qmk_firmware/pull/18017) the encoder behavior wanted by Viendi was removed, hence the need for reintroducing the encoder behavior was it was originally intended.

Adds two keymaps to Viendi8L: `encoder` and `gondolindrim`, the former having the default encoder behavior by Viendi and the latter my personal preference for encoder behavior which includes a tap-hold mechanic for the encoder click.

PM'ing @fauxpark (author of the following PR).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by keyboard-magpie — APPROVED** [review]

**Review by drashna — COMMENTED** [review]
I feel like a lot of this could be simplified by using the encoder map feature.  Especially as it supports the entire process_record chain (including supporting custom keycodes).

**Comment by Gondolindrim** [comment]
> I feel like a lot of this could be simplified by using the encoder map feature. Especially as it supports the entire process_record chain (including supporting custom keycodes).

To be quite honest I tried, but the problem is that the encoder map feature uses a `const` definition which prevents the encoder keycodes from being updated on-the-fly; the idea here being that the "encoder modes" feature be user-adjustable through the (upcoming) new VIA mechanism and custom GUI. Not only that, the encoder modes and their keycodes are three-dimensional (one dimension for the encoder mode counter, another for the layer and another for the direction CW, CCW, push and hold). I was not able to integrate this into the encoder map feature.

I am currently trying to make it work with the feature using pointers, as the `const` qualifier can be manipulated by setting up addresses and manipulating the pointers of those addresses; the problem being that I need official support for the encoder modes feature as the PCBs are in production and will be shipped to users shortly, and they will surely get confused if the advertised intended functioning of the encoder and its modes is not in the official repo.

**Comment by drashna** [comment]
For non-via keymaps, yeah, it's a const.  For via, the encoder map leverages the dynamic keymap functionality, so is update-able. 

>  the idea here being that the "encoder modes" feature be user-adjustable through the (upcoming) new VIA mechanism and custom GUI

Because of encoder map, there is absolutely no reason to have a new feature to does the same thing *as* encoder maps. 

If this is something that is being done via side, then wilba, olivia or the like should ... talk to us about it, so we can be on the same page.  rather than adding redundant functionality. 

Additionally, if you want modes that can change within a non-via keymap, you can add custom keycodes that change behavior based on a locally stored variable.  This could be saved in eeprom, as well.

**Comment by Gondolindrim** [comment]
> For non-via keymaps, yeah, it's a const. For via, the encoder map leverages the dynamic keymap functionality, so is update-able.
> 
> > the idea here being that the "encoder modes" feature be user-adjustable through the (upcoming) new VIA mechanism and custom GUI
> 
> Because of encoder map, there is absolutely no reason to have a new feature to does the same thing _as_ encoder maps.
> 
> If this is something that is being done via side, then wilba, olivia or the like should ... talk to us about it, so we can be on the same page. rather than adding redundant functionality.
> 
> Additionally, if you want modes that can change within a non-via keymap, you can add custom keycodes that change behavior based on a locally stored variable. This could be saved in eeprom, as well.
> 
> Eg, you can have a single keycode used that has multiple different functions based on that local variable. Technically, this is EXACTLY how the magic feature works, in fact.

All of this is news to me; nothing on this is said on the documentation.

**Comment by drashna** [comment]
No worries!  Right now, we still have a good number of keyboards using `action_exec` to hack in encoder support for VIA (since it wasn't available).   And the encoder map feature is pretty new (went in last cycle),  VIA support fore it was added about a month ago. 

https://github.com/qmk/qmk_firmware/pull/17734

Both sides could probably use better documentation.

**Pull request closed without merging**
