### PR TITLE
ChibiOS conf migrations... take 16

### PR DESCRIPTION
**Pull request by tzarc**
## Description

Fixes build for the `boston`.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Would be great if @Bluepylons could confirm that this is all green.

**Review by drashna — APPROVED** [review]

**Review by noroadsleft — APPROVED** [review]

**Comment by bluepylons** [comment]
Got the following errors when I tried compiling:

`Ψ Compiling keymap with make -j 1 boston:default


QMK Firmware 0.12.15
Making boston with keymap default

arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/boston/boston.c                                                               In file included from ./lib/chibios/os/rt/include/ch.h:91,
                 from ./lib/chibios/os/hal/osal/rt-nil/osal.h:32,
                 from ./lib/chibios/os/hal/include/hal.h:28,
                 from quantum/quantum.h:24,
                 from keyboards/boston/boston.h:19,
                 from keyboards/boston/boston.c:17:
./lib/chibios/os/rt/include/chchecks.h:48:2: error: #error "obsolete or unknown configuration file"
   48 | #error "obsolete or unknown configuration file"
      |  ^~~~~
In file included from ./lib/chibios/os/rt/include/ch.h:128,
                 from ./lib/chibios/os/hal/osal/rt-nil/osal.h:32,
                 from ./lib/chibios/os/hal/include/hal.h:28,
                 from quantum/quantum.h:24,
                 from keyboards/boston/boston.h:19,
                 from keyboards/boston/boston.c:17:
./lib/chibios/os/oslib/include/chlib.h:112:2: error: #error "CH_CFG_USE_OBJ_CACHES not defined in chconf.h"
  112 | #error "CH_CFG_USE_OBJ_CACHES not defined in chconf.h"
      |  ^~~~~
./lib/chibios/os/oslib/include/chlib.h:116:2: error: #error "CH_CFG_USE_DELEGATES not defined in chconf.h"
  116 | #error "CH_CFG_USE_DELEGATES not defined in chconf.h"
      |  ^~~~~
./lib/chibios/os/oslib/include/chlib.h:120:2: error: #error "CH_CFG_USE_JOBS not defined in chconf.h"
  120 | #error "CH_CFG_USE_JOBS not defined in chconf.h"
      |  ^~~~~
In file included from quantum/quantum.h:24,
                 from keyboards/boston/boston.h:19,
                 from keyboards/boston/boston.c:17:
./lib/chibios/os/hal/include/hal.h:242:2: error: #error "obsolete or unknown configuration file"
  242 | #error "obsolete or unknown configuration file"
      |  ^~~~~
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [tmk_core/rules.mk:417: .build/obj_boston_default/keyboards/boston/boston.o] Error 1
Make finished with errors
make: *** [Makefile:523: boston:default] Error 1
james@james-desktop:~/qmk_firmware-2$ ^C
james@james-desktop:~/qmk_firmware-2$ ^C
james@james-desktop:~/qmk_firmware-2$ 

`

**Comment by bluepylons** [comment]
Have any other STM32F072 keyboards had issues?

**Comment by tzarc** [comment]
I'm guessing you're not running latest master -- the config files you had previously worked with ChibiOS 19 -- the converted ones work with ChibiOS 20. If you've applied the config PR to yours, but kept the old ChibiOS 19 submodules, I'd guess that's why you've got the error above.

If you run `make git-submodule` it'll hopefully get things up to date -- can you retry the build after doing so?

If it's still problematic, can you confirm which version of ChibiOS you're running, by doing the following, please?
```sh
cd lib/chibios
git log -n1
```

**Comment by tzarc** [comment]
> Have any other STM32F072 keyboards had issues?

All other F072 boards have been converted, so no. `boston` is the only one failing at the moment.

**Comment by bluepylons** [comment]
I freshly cloned qmk_firmware into a new directory (by running git clone https://github.com/qmk/qmk_firmware qmk_firmware-2 ) and ran make git-submodule before I last tried to compile. 

This was what I got after running git log -n1 from lib/chibios

> commit ffe54d63cb10a355add318f8e922e39f1c3d4bfd (HEAD, tag: ver20.3.2, tag: develop_2020_q4, tag: breaking_2021_q1, origin/master, origin/HEAD, master)
> Author: Giovanni Di Sirio <gdisirio@gmail.com>
> Date:   Fri Jul 31 15:43:47 2020 +0000
>  git-svn-id: svn://svn.code.sf.net/p/chibios/svn/tags/ver20.3.2@13800 27425a3e-05d8-49a3-a47f-9c15f0e5edd8
image

**Comment by tzarc** [comment]
And you applied the patch on this PR before building in the new repo?
If you attempt to build on configurator, it fails with the issue you were having, as it's got the 19.x configs instead of 20.x:

https://config.qmk.fm/#/boston/LAYOUT_all

**Comment by bluepylons** [comment]
Sorry I didn't apply the patch - I thought it was already merged into master. Sorry about that. I replaced the 3 files, and it compiled and worked perfectly. You should be all good.

**Comment by tzarc** [comment]
Great, thanks!

**Pull request merged**
