### PR TITLE
Make `PREVENT_STUCK_MODIFIERS` the default

### PR DESCRIPTION
**Pull request by Talljoe**
This implements recommendation in issue #2518. `PREVENT_STUCK_MODIFIERS` (`PSM`) is now the default and can be overridden with `STRICT_LAYER_RELEASE`.

As a precursor to the change I removed leader keys from being a default feature to ensure that the additional 253 bytes from `PSM` didn't cause memory issues. Far more layouts used `PSM` than `KC_LEAD` so I feel this is a fair trade off for defaults. The remaining layouts that used leader keys were built to verify they weren't too large. I also removed `process_chording` as it was permamently disabled in the code, had a hard-coded dictionary in quantum, and was not used anywhere. I will likely resurrect this feature in the future.

I hand examined dozens of layouts and found no layouts that relied on `PSM` and many that likely had bugs that would have been fixed with `PSM`.  The only exception was zer09's user space the explicitly disabled `PSM` and so I added `STRICT_LAYER_RELEASE`.

### CODE REVIEW

**Comment by vomindoraan** [comment]
Would be great to see this merged sometime soon.

**Comment by drashna** [comment]
This has a bunch of merge conflicts now, and would need to be updated before it can be merged.

**Comment by vomindoraan** [comment]
Yeah, I meant after the conflicts are resolved. The previous comment was also a call to the PR author to update his branch.

**Comment by Talljoe** [comment]
I kept it updated for about a month. :/

It's updated now.

**Comment by jackhumbert** [comment]
Great! Thanks :)

**Pull request merged**
