### PR TITLE
Fix for xt_usb converter

### PR DESCRIPTION
**Pull request by DalvikVM**
This is a backport of a few changes hasu made in his TMK firmware to fix general functionality issues that made the firmware pretty much unusable. This code needs to be tested to be certain of its functionality fixes in it's conversion to QMK.

### CODE REVIEW

**Comment by spidey3** [comment]
I am going to build a converter on breadboard to test this with my F-XT (don't want to interfere with my [working] Soarer's converter). Will test in a few days.

**Comment by DalvikVM** [comment]
Sounds good! Thanks!

**Comment by spidey3** [comment]
The hardware that I was waiting for arrived yesterday, and I was able to assemble it today and start testing. My testing environment is:

- Teensy 2.0 flashed with code from this PR.
     - **D1** connected to pin 1 (Clock) [with 4.7kΩ pull-up to Vcc]
     - **D0** connected to pin 2 (Data) [with 4.7kΩ pull-up to Vcc]
     - **B7** connected to pin 3 (Reset)
     - **GND** connected to pin 4
     - **Vcc** connected to pin 5
- IBM Model F-XT
     - model number sticker is gone, but I believe it to be P/N 1801449
     - this keyboard is known to work 100% correctly with Soarer's Converter

The good news: I can register key codes.
The bad news: Bad random things happen:
- Sometimes key events are missed
- That leads to occasional missed keystrokes...
- I also suspect that sometimes the keycode is misinterpreted.
- It also leads to keys being stuck down (when key-up event is missed)
- Sometimes modifiers get stuck (probably again because of miss

I suspect that the problem is actually upstream of `matrix_scan()`, probably in `xt_host_recv()`, or in the interrupt handler that actually receives the bits from the keyboard and stores the bytes read in the ring buffer.

I will explore more tomorrow to see if I can find out more.

**Comment by DalvikVM** [comment]
Yeah, that's the same issues we were having with TMK. I should've reviewed the issue post discussion. I forgot that hasu mentioned he added some error logic and thus I didnt make any changes to add that.

I'd reccomend taking a look at this TMK issue post, it's quite informative: https://github.com/tmk/tmk_keyboard/issues/635

**Comment by DalvikVM** [comment]
Now that I'm looking for it, I found the code changes made in TMKs Core. He mainly made the changes to his newer all-in-one converter firmware. I'll have to look and see if the changes he made in that can be used in the older xt port.

Maybe I'll try and port the whole ibmpc converter over....

It's my bad, I should've gone back and re-read the issue in TMK. 😳

**Comment by spidey3** [comment]
DalvikVM - are you still working on this project?  I would really like to achieve a workable F-XT converter in QMK.  Please let me know if there is anyway I can help.

**Comment by DalvikVM** [comment]
I am stiil working on it slowly. One of the main issues Im having is the tmk_core in qmk is quite far behind TMK. There are loads of errors if I dont update the core in qmk. 

I need to request someone to update it, as I dont have strong enough of a grasp on qmk to know If Ill break anything if I push an update like that.

Or...

Im also wondering if there would be a way to set qmk to use a seperate version of tmk_core just for this converter that would reside in the ibm_pc folder, that way it wouldnt affect the current setup.

If I can get that fixed, then its down to one avr error I believe.

Let me know if you can help with any of that!

Thanks!

**Comment by DalvikVM** [comment]
Im wondering if tweaking the #include files paths may work for that, but I havent had time as of late and Im teaching myself how all this works at the same time....

**Comment by spidey3** [comment]
> I am stiil working on it slowly. One of the main issues Im having is the tmk_core in qmk is quite far behind TMK. There are loads of errors if I dont update the core in qmk.

It's not so much that tmk_core in qmk is behind tmk, so much as that qmk and tmk have diverged [intentionally]. Stuff that tmk implements in the core are handled differently, in quantum, or in keyboard directories. It's a completely different philosophy on separation of code / separation of responsibilities, and the differences will only increase over time [by design].

> Im also wondering if there would be a way to set qmk to use a seperate version of tmk_core just for this converter that would reside in the ibm_pc folder, that way it wouldnt affect the current setup.

I'm not one of the main collaborators, but I can state with pretty high certainty that this is not an approach that would be accepted. If you are going to use a different core, then you might as well just use TMK in toto.

My guess is that the code changes that need to be done should all reside in `.../tmk_core/protocol/xt*` and in `.../keyboards/converter/xt_usb`. Given that the only thing that uses `.../tmk_core/protocol/xt*` is the xt_usb converter, I don't think anyone would mind at all if it was complete replaced with new [working] code.  And if there are code changes needed outside of that, then we need to understand what they are, and eliminate them, because [in theory] adapting QMK should not require changes to the core.

Finally, I think that `keyboards/converter/ibm_terminal` is known to work reasonably well - but looking at the implementation, I wonder if it is focused on boards that connect via a PS2 connector.  Perhaps it would be better to start from there, and adapt it to the ways that F-XT is different.

**Comment by DalvikVM** [comment]
Ok. I messed up on this. I forgot this fix was for the xt_usb converter. Duh. This converter hasnt worked properly for a long time as far as I can tell, and on tmk it isnt being updated anymore. The fix for the xt keyboard was made in TMKs ibm_pc converter.

I started on fixing this old converter and after figuring out that what was needed was buried in the ibm_pc files, I figured I would just port the ibm_pc converter instead of putting a bunch of work into this one.

**Comment by DalvikVM** [comment]
It's ibmpc_usb not ibm_pc. Oye. Tired today.

A quote from the README file:
"The converter translates IBM PC keyboard protocols to use classic keyboards with modern computer with USB ports. It supports both IBM XT and AT protocols, and all of scan code set 1, 2 and 3 with one firmware."

This one should be able to replace all of the other ibm converters in qmk.

Thanks for the response too. I agree that having the separate core is a plain ole bad idea. Not sure where my brain is today.

**Comment by DalvikVM** [comment]
Here's the errors Ive got now. Quite a few less than it was before. 

```
Compiling: keyboards/converter/ibmpc_usb/matrix.c                                                  
keyboards/converter/ibmpc_usb/matrix.c: In function 'matrix_scan':
keyboards/converter/ibmpc_usb/matrix.c:179:13: error: implicit declaration of function 'matrix_clear'; did you mean 'matrix_break'? [-Werror=implicit-function-declaration]
             matrix_clear();
             ^~~~~~~~~~~~
             matrix_break
keyboards/converter/ibmpc_usb/matrix.c: At top level:
keyboards/converter/ibmpc_usb/matrix.c:422:6: error: conflicting types for 'matrix_clear' [-Werror]
 void matrix_clear(void)
      ^~~~~~~~~~~~
keyboards/converter/ibmpc_usb/matrix.c:179:13: note: previous implicit declaration of 'matrix_clear' was here
             matrix_clear();
             ^~~~~~~~~~~~
In file included from ./keyboards/converter/ibmpc_usb/config.h:26,
                 from <command-line>:
keyboards/converter/ibmpc_usb/matrix.c: In function 'process_cs1':
quantum/config_common.h:69:31: error: expected identifier before '(' token
 #    define PINDEF(port, pin) ((PIN##port##_ADDRESS << PORT_SHIFTER) | pin)
                               ^
quantum/config_common.h:112:20: note: in expansion of macro 'PINDEF'
 #        define E0 PINDEF(E, 0)
                    ^~~~~~
keyboards/converter/ibmpc_usb/matrix.c:534:9: note: in expansion of macro 'E0'
         E0,
         ^~
keyboards/converter/ibmpc_usb/matrix.c:579:29: error: 'E1_1D' undeclared (first use in this function)
                     state = E1_1D;
                             ^~~~~
keyboards/converter/ibmpc_usb/matrix.c:579:29: note: each undeclared identifier is reported only once for each function it appears in
keyboards/converter/ibmpc_usb/matrix.c:582:29: error: 'E1_9D' undeclared (first use in this function)
                     state = E1_9D;
                             ^~~~~
In file included from ./keyboards/converter/ibmpc_usb/config.h:26,
                 from <command-line>:
keyboards/converter/ibmpc_usb/matrix.c: In function 'process_cs2':
quantum/config_common.h:69:31: error: expected identifier before '(' token
 #    define PINDEF(port, pin) ((PIN##port##_ADDRESS << PORT_SHIFTER) | pin)
                               ^
quantum/config_common.h:122:20: note: in expansion of macro 'PINDEF'
 #        define F0 PINDEF(F, 0)
                    ^~~~~~
keyboards/converter/ibmpc_usb/matrix.c:744:9: note: in expansion of macro 'F0'
         F0,
         ^~
keyboards/converter/ibmpc_usb/matrix.c:796:29: error: 'E0_F0' undeclared (first use in this function); did you mean 'KC_FN0'?
                     state = E0_F0;
                             ^~~~~
                             KC_FN0
keyboards/converter/ibmpc_usb/matrix.c:851:29: error: 'E1_14' undeclared (first use in this function); did you mean 'KC_F14'?
                     state = E1_14;
                             ^~~~~
                             KC_F14
keyboards/converter/ibmpc_usb/matrix.c:854:29: error: 'E1_F0' undeclared (first use in this function); did you mean 'KC_FN0'?
                     state = E1_F0;
                             ^~~~~
                             KC_FN0
keyboards/converter/ibmpc_usb/matrix.c:874:29: error: 'E1_F0_14' undeclared (first use in this function); did you mean 'KC_FN14'?
                     state = E1_F0_14;
                             ^~~~~~~~
                             KC_FN14
keyboards/converter/ibmpc_usb/matrix.c:883:29: error: 'E1_F0_14_F0' undeclared (first use in this function)
                     state = E1_F0_14_F0;
                             ^~~~~~~~~~~
In file included from ./keyboards/converter/ibmpc_usb/config.h:26,
                 from <command-line>:
keyboards/converter/ibmpc_usb/matrix.c: In function 'process_cs3':
quantum/config_common.h:69:31: error: expected identifier before '(' token
 #    define PINDEF(port, pin) ((PIN##port##_ADDRESS << PORT_SHIFTER) | pin)
                               ^
quantum/config_common.h:122:20: note: in expansion of macro 'PINDEF'
 #        define F0 PINDEF(F, 0)
                    ^~~~~~
keyboards/converter/ibmpc_usb/matrix.c:915:9: note: in expansion of macro 'F0'
         F0,
         ^~
keyboards/converter/ibmpc_usb/matrix.c:955:29: error: 'G80' undeclared (first use in this function)
                     state = G80;
                             ^~~
keyboards/converter/ibmpc_usb/matrix.c:1032:29: error: 'G80_F0' undeclared (first use in this function)
                     state = G80_F0;
                             ^~~~~~
cc1: all warnings being treated as errors
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [.build/obj_converter_ibmpc_usb_default/matrix.o] Error 1
make: *** [converter/ibmpc_usb:default] Error 1
Make finished with errors
```

If I update tmk_core with a few tweaks I get this:

```
QMK Firmware 0.11.33
Making converter/ibmpc_usb with keymap default

tmk_core/rules.mk:418: warning: overriding commands for target `teensy'
tmk_core/avr.mk:106: warning: ignoring old commands for target `teensy'
tmk_core/rules.mk:426: warning: overriding commands for target `dfu'
tmk_core/avr.mk:137: warning: ignoring old commands for target `dfu'
tmk_core/rules.mk:443: warning: overriding commands for target `dfu-start'
tmk_core/avr.mk:140: warning: ignoring old commands for target `dfu-start'
tmk_core/rules.mk:454: warning: overriding commands for target `dfu-ee'
tmk_core/avr.mk:144: warning: ignoring old commands for target `dfu-ee'
tmk_core/rules.mk:462: warning: overriding commands for target `gdb-config'
tmk_core/avr.mk:240: warning: ignoring old commands for target `gdb-config'
tmk_core/rules.mk:475: warning: overriding commands for target `debug'
tmk_core/avr.mk:253: warning: ignoring old commands for target `debug'
tmk_core/rules.mk:499: warning: overriding commands for target `coff'
tmk_core/avr.mk:277: warning: ignoring old commands for target `coff'
tmk_core/rules.mk:505: warning: overriding commands for target `extcoff'
tmk_core/avr.mk:282: warning: ignoring old commands for target `extcoff'

Compiling C: keyboards/converter/ibmpc_usb/matrix.c
avr-gcc: fatal error: cannot specify -o with -c, -S or -E with multiple files
compilation terminated.
make[1]: *** [obj_converter_ibmpc_usb_default/matrix.o] Error 1
Make finished with errors
make: *** [converter/ibmpc_usb:default] Error 1
```

Any insights are welcolme!

**Comment by spidey3** [comment]
> Any insights are welcolme!

It's hard to diagnose compilation errors without having access to the latest code.  Can you commit this on a branch (not your master) and push it so others can see it?

**Comment by DalvikVM** [comment]
Ah. Ok. Itll take me a bit to get things reorganized. Things get a bit messy when I start experimenting....

**Comment by DalvikVM** [comment]
Hey, sorry, but I didnt bother to back up what I had done so far and I had some computer trouble, so what ive done so far is gone.
I dont think I'm gonna have time to redo it and I dont have the knowledge to finish it anyhow...

Hope you can manage to get further than I did. Sorry again...

@spidey3

**Comment by marfrit** [comment]
@DalvikVM I did your backup, but it is only working with codeset 2/ 102 key layout, as that's what I own.
https://github.com/marfrit/qmk_firmware/tree/master/keyboards/converter/ibmpc_usb

**Pull request closed without merging**
