### PR TITLE
Fix spelling of "persistent"

### LINKED ISSUE #1201: Incorrect spelling of 'persistent'
Would it be feasible to correct this [spelling error of persistent (`persistant`)](https://github.com/qmk/qmk_firmware/search?utf8=%E2%9C%93&q=persistant&type=Code) repo wide? Looks like it stemmed from copying the default keymaps for boards in most cases. I guess it's not a big deal, but just seems like a good thing to do for formality's sake.

### PR DESCRIPTION
**Pull request by adzenith**
Fixes #1201.

### CODE REVIEW

**Comment by fredizzimo** [comment]
The build failure is not yours. The `subatomic` folder has a keymap but no keyboard, which confuses the build system. @jackhumbert it would probably be better to move the keymap somewhere else until the keyboard is ready? Or alternatively fix the travis build script to skip that.

**Comment by jackhumbert** [comment]
Thanks for looking into that @fredizzimo! I thought it was configured to skip solders without Makefiles, but that might have changed. Not entriely sure why no others have failed since that commit.

**Comment by jackhumbert** [comment]
Thanks though! This is much needed :)

**Comment by fredizzimo** [comment]
It's probably because no one has modified that keymap, so it hasn't been compiled with the keymap/keyboard only compilation mode before.

**Comment by Xyverz** [comment]
Ya know, for all the keymaps I've built using this persistent layouts, I've never noticed the misspelling! When I first saw this commit note for one of my keymaps, I was embarrassed, but then I realized I'd just copied and pasted that bit of code into my keymaps.

Thanks for catching and fixing this!

**Comment by fredizzimo** [comment]
Yes, that's what usually happens, spelling errors tend to spread throughout the codebase, and stay unoticed for a long time.

I guess that's what happens when we are lazy and use automated tools these days.  We either copy-paste things, or rely on code compeltetion, which happily completes spelling mistakes.

**Comment by smt** [comment]
Thanks for this! :+1:

**Comment by adzenith** [comment]
My pleasure! Thanks for the merge.

**Pull request merged**
