### PR TITLE
Spirals, Pinwheels, and Documentation....Oh My! RGB Matrix Effects

### PR DESCRIPTION
**Pull request by XScorpion2**
## Description

Implementation of effects that require atan2 to calculate angles. 
Video of effects: https://photos.app.goo.gl/gRKNpmazjW4TJkxc8

Yes, I'm the reason you are running out of firmware on AVR

❗️ #5919 contains this work, merge this first, or just merge that pr and close this one.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
>Yes, I'm the reason you are running out of firmware on AVR

100%

**Comment by XScorpion2** [comment]
what's with the confused emoji?

**Comment by drashna** [comment]
while it says confused, the face is more of :/  :)

**Comment by XScorpion2** [comment]
but why :/ 
Is my work not good enough for you anymore?

**Comment by drashna** [comment]
So much AVR room.

But otherwise, it looks great

**Comment by XScorpion2** [comment]
I could put the spirals behind a spiral effect define

**Comment by drashna** [comment]
Nah, that's fine.

**Comment by drashna** [comment]
Sorry, merge conflicts now. :(

**Comment by XScorpion2** [comment]
Rebased on latest master

**Pull request merged**
