### PR TITLE
RGB matrix animation breakout

### PR DESCRIPTION
**Pull request by XScorpion2**
## Description

Breakout of animation code to separate files with explicit param passing for easier unit testing.
Builds on top of https://github.com/qmk/qmk_firmware/pull/5170

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by XScorpion2** [comment]
@drashna can you look at this build failure, works locally for me on those boards. Not sure where to include that folder in the make file.

**Comment by XScorpion2** [comment]
Ok, there we go, fix't

**Comment by drashna** [comment]
Is there a specific reason for the changes? 

You mention unit testing... but I'm not sure how this would really help, nor the advantage to doing this.

**Comment by XScorpion2** [comment]
Breaking the animation functions out like this allows you to more easily have a stand alone project that pulls these files in for testing. The tests themselves are easier to write as you can then just pass in the data directly to the function and examine the results more easily that was as well. Though tbh I'm still trying to understand the existing test code / setup for qmk.

**Comment by XScorpion2** [comment]
closing, going to do some more work on this and integrate it with ctrl/alt matrix work a bit more

**Pull request closed without merging**
