### PR TITLE
ymdk40 leds number wrong for this board

### PR DESCRIPTION
**Pull request by dkruyt**
## Description

The ymdk40 board has 51 leds instead of 8, I compiled it and tested it on my own board, after the change to 51 all leds are working.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Picture linked in readme shows ~6 leds.  Sounds like could be a different board or a different revision.

**Comment by dkruyt** [comment]
> Picture linked in readme shows ~6 leds. Sounds like could be a different board or a different revision.

Thos LED are backlight LED, the one that I changed to 51 are the LED per key.

**Comment by fauxpark** [comment]
The in-switch LED footprints here are not RGB, they are for single colour backlight as there are only two through-hole pads. The four(???) square footprints along the top half of the PCB are RGB underglow LEDs, which is what the RGBLight feature is for.

https://www.aliexpress.com/item/1005004341165858.html
I found this board which does have 51 RGB per-key LEDs, as Drashna said, it is a different revision or a different board altogether (these manufacturers are not good at naming). In any case it should be using RGB Matrix, not RGBlight.

**Comment by dkruyt** [comment]
Mine is a new rev, will make a new pr...

**Pull request closed without merging**
