### PR TITLE
Fixed the LED layout and add underglow for the bm60rgb

### PR DESCRIPTION
**Pull request by jbradforddillon**
Rewrote the LED layout for the bm60rgb.

## Description

The LED layout for the bm60 had a couple of errors. In particular the third row jumped from 37 to 40, and then the bottom row had too many NO_LED markers. I believe this happened because the original author (@mechmerlin) didn't have a board to test on. Since I have one, I was able to test this configuration.

I was also able to add the underglow LEDs, which I saw a bunch of people asking about on r/mk.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Comment by jrodan** [comment]
nice! 
do you see any possibility to trigger the underglow LEDs separately? a static mapping for those LEDs would also be fine.

**Comment by jbradforddillon** [comment]
I actually do have that code written @jrodan. I will try to get a branch up sometime soon.

**Comment by jrodan** [comment]
perfect! 
please give me a hint. I am waiting for this already. 
I guess it somehow needs to me done via the flagging for the LEDs?
for the actual implementation or any hint I am very happy to get support or a solution :) 
thanks!

**Pull request merged**
