### PR TITLE
add 'objs-size' target into tmk_core/rules.mk

### PR DESCRIPTION
**Pull request by mtei**
## Description

Display the size of the created object files.

It is convenient to use as follows.

```
$ make crkbd:all
QMK Firmware 0.6.321
Making crkbd/rev1 with keymap default             [OK]
Making crkbd/rev1 with keymap drashna             [OK]
Making crkbd/rev1 with keymap edvorakjp           [OK]
Making crkbd/rev1 with keymap jarred              [OK]
Making crkbd/rev1 with keymap like_jis            [OK]
Making crkbd/rev1 with keymap omgvee              [OK]
Making crkbd/rev1 with keymap thefrey             [OK]

$ make crkbd:all:objs-size | grep keymap.o
   2558	      0	      0	   2558	    9fe	.build/obj_crkbd_rev1_default/keyboards/crkbd/keymaps/default/keymap.o
      0	      0	      0	      0	      0	.build/obj_crkbd_rev1_drashna/keyboards/crkbd/keymaps/drashna/keymap.o
    438	      0	      0	    438	    1b6	.build/obj_crkbd_rev1_edvorakjp/keyboards/crkbd/keymaps/edvorakjp/keymap.o
   1260	      0	      0	   1260	    4ec	.build/obj_crkbd_rev1_jarred/keyboards/crkbd/keymaps/jarred/keymap.o
      0	      0	      0	      0	      0	.build/obj_crkbd_rev1_like_jis/keyboards/crkbd/keymaps/like_jis/keymap.o
      0	      0	      0	      0	      0	.build/obj_crkbd_rev1_omgvee/keyboards/crkbd/keymaps/omgvee/keymap.o
   2532	      0	      0	   2532	    9e4	.build/obj_crkbd_rev1_thefrey/keyboards/crkbd/keymaps/thefrey/keymap.o

$ make crkbd:all:objs-size | grep rgblight.o
   4010	     14	     32	   4056	    fd8	.build/obj_crkbd_rev1_default/quantum/rgblight.o
      0	      0	      0	      0	      0	.build/obj_crkbd_rev1_drashna/quantum/rgblight.o
   2284	      1	      3	   2288	    8f0	.build/obj_crkbd_rev1_edvorakjp/quantum/rgblight.o
   4010	     14	     32	   4056	    fd8	.build/obj_crkbd_rev1_jarred/quantum/rgblight.o
      0	      0	      0	      0	      0	.build/obj_crkbd_rev1_like_jis/quantum/rgblight.o
      0	      0	      0	      0	      0	.build/obj_crkbd_rev1_omgvee/quantum/rgblight.o
   4010	     14	     32	   4056	    fd8	.build/obj_crkbd_rev1_thefrey/quantum/rgblight.o
```

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
@jackhumbert or @skullydazed, any issues with this?

**Comment by Lenbok** [comment]
I've been using this and it's pretty handy, seems pretty low risk to merge?

**Comment by mtei** [comment]
In which document is this target 'objs-size' appropriate to add a description?

**Comment by mtei** [comment]
By the way, I found that there were `sym` and` lss` targets in `tmk_core/rules.mk`. These are useful for analyzing the resulting object. Is this documented somewhere?

**Comment by drashna** [comment]
@mtei I don't think that there is a good place for adding this for documentation. 

However, I think that a new page with a list of advanced commands, like this, would be a good idea.  

You've added a number of very useful targets recently!  :heart:

**Comment by skullydazed** [comment]
Thanks!

**Pull request merged**
