### PR TITLE
Christmas tree

### PR DESCRIPTION
**Pull request by jsank**

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! It looks like these are @That-Canadian's commits - is this ready to be merged into qmk:master?

**Comment by That-Canadian** [comment]
Dunno why this was requested earlier, is is ready now though! Forgot to do final push yesterday night, doh.

**Comment by jackhumbert** [comment]
Awesome :) thanks!

**Comment by jsank** [comment]
Thanks fellas!

**Pull request merged**
