### PR TITLE
Refactoring wilba.tech PCBs, updating Rama Works U80-A 

### PR DESCRIPTION
**Pull request by Wilba6582**
## Description

- grouped all wilba.tech PCBs under `keyboards/wilba_tech`
- refactoring common code between WTxx PCBs, Rama Works PCBs and Zeal60/Zeal65
- name changes
- generalised ISSI31FL3731 driver like the other ISSI drivers so it isn't hard-coded to 2 drivers
- added Rama Works U80-A RGB matrix implementation

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

### CODE REVIEW

**Comment by drashna** [comment]
Unfortunately, because of how the VIA code is set up here, every board that isn't updated in this PR that uses VIA is broken. 

That includes @yiancar, @awkannan and @nooges' boards.  

I think that for now, the best option for handling this, is to push the changes to the branch for breaking changes, so that others have time to update their boards, without them breaking in the main repo.

**Comment by Wilba6582** [comment]
Sorry, forgot about that. I'll update the broken references, just wanted to get the core changes into review ASAP.

**Comment by drashna** [comment]
Not a problem.  And if appropriate, we can remove the breaking changes tag, and redirect back to master.

**Comment by Wilba6582** [comment]
Please put the base branch back to master

**Comment by Wilba6582** [comment]
ne merge avail? 😂

**Comment by Wilba6582** [comment]
thank you, my smol brane can only handle one working branch at a time

**Pull request merged**
