### PR TITLE
Use modern solution for tri-layer in sofle default layout

### PR DESCRIPTION
**Pull request by rafal0p**
## Description

As per [docs](https://github.com/qmk/qmk_firmware/blob/master/docs/ref_functions.md#update_tri_layer_statestate-x-y-z) handling it in `process_record_user` is no longer necessary.

I don't own OLED version, so I'd like to ask the dear reviewer to verify if `print_status_narrow` still works properly after that change.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Just a heads up, either version is valid, and have their own quirks.  Like the layer state function won't let you activate the third layer (the "adjust" layer here) without the first two layers (raise and lower, here) being active.  That may not be desirable behavior, in some cases/configs.

**Review by drashna — APPROVED** [review]

**Review by zvecr — CHANGES_REQUESTED** [review]
This wont work as KC_LOWER and friends are now a non implemented keycodes.

They need to be removed from the custom keycodes enum, and replaced with,
```c
#define KC_LOWER MO(_LOWER)
```

**Review by fauxpark — APPROVED** [review]

**Comment by rafal0p** [comment]
@drashna, I knew about this limitation, but aforementioned feature (activating `_ADJUST` directly) is not not present in the default layout. But maybe you're right, and for educational purposes it's actually better to leave it as-is?

@zvecr, thanks for spotting the issue, pushed the change with `MO(_LOWER)` (instead of `#define`), do you happen to know if they are equivalent?

**Review by zvecr — APPROVED** [review]
Equivalent as long as you do not need to do `MO(_ADJUST)`

**Pull request merged**
