### PR TITLE
Add tool to generate rgb matrix position data from KLE raw data.

### PR DESCRIPTION
**Pull request by al3ph**
## Description

New tool to allow generation of RGB matrix LED position data, from KLE RawData.
Had to do this manually for a TKL keyboard, it was painful, this should help others to not suffer the same fate.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by al3ph** [comment]
```
Numpad + Func Row
["F1","F2","F3","F4"],
[{y:0.25},"Num Lock","/","*","-"],
["7\nHome","8\n↑","9\nPgUp",{h:2},"+"],
["4\n←","5","6\n→"],
["1\nEnd","2\n↓","3\nPgDn",{h:2},"Enter"],
[{w:2},"0\nIns",".\nDel"]
```

```
./rgb_matrix_tool.py test.raw
Keyboard dimension: 4.0 x 6.25
Keyboard key count: 21

         /*    0    */ /*    1    */ /*    2    */ /*    3    */
/*  0 */ {   0,   0 }, {  75,   0 }, { 149,   0 }, { 224,   0 },
/*  1 */ {   0,  15 }, {  75,  15 }, { 149,  15 }, { 224,  15 },
/*  2 */ {   0,  27 }, {  75,  27 }, { 149,  27 }, { 224,  34 },
/*  3 */ {   0,  40 }, {  75,  40 }, { 149,  40 },
/*  4 */ {   0,  52 }, {  75,  52 }, { 149,  52 }, { 224,  58 },
/*  5 */ {  37,  64 }, { 149,  64 },

```

**Comment by al3ph** [comment]
```
usage: rgb_matrix_tool.py [-h] [--width WIDTH] [--height HEIGHT]
                          [--origin {CENTER,TOP_LEFT,BOTTOM_RIGHT}] [-d]
                          [path [path ...]]

Parse RawData from KeyboardLayoutGenerator and generate RGB position matrix.

positional arguments:
  path                  Path to rawdata, read stdin otherwise. (default: [])

optional arguments:
  -h, --help            show this help message and exit
  --width WIDTH         Structure max X. (default: 224)
  --height HEIGHT       Structure max Y. (default: 64)
  --origin {CENTER,TOP_LEFT,BOTTOM_RIGHT}
                        Origin of key, for positioning (default: CENTER)
  -d, --debug           Debug mode. (default: False)

```

**Comment by drashna** [comment]
That's pretty awesome! 

Though, it may be nice to add documentation to the rgb matrix docs page?

**Comment by al3ph** [comment]
That’s on a separate repo ?  I’ve not looked at how you generate your docs.

You’re welcome, trying to do it by hand is impossible, and I wanted the positions to center properly on keys that are offset and not 1x1, at which point it became clear I had to automate it.

**Comment by al3ph** [comment]
Ah I see the docs now, yup I’ll add in something tomorrow.

**Comment by drashna** [comment]
Sorry, yeah, it's in the repo, on master.  The docs are generated dynamically from it.

**Comment by drashna** [comment]
@XScorpion2 did you want to take a look at this, and validate it?

**Comment by yanfali** [comment]
This looks neat, maybe we could add this functionality to @noroadsleft tool

**Comment by XScorpion2** [comment]
Dude this is awesome! I'll pull it down tonight a d look though it.

**Comment by al3ph** [comment]
It'd be nice if it could also map from keyboard to LED index, but that's tricky as it'd need to parse the users c++, but as you really only need to do this once per keyboard, it's not a biggy, and it only happens if your LED's index doesn't directly map to the key position  ( guess what, my PCB does exactly this :( ).

I've tested with a full TKL layout and it seemed to work. Bear in mind it also accounts for gaps, so you'll possibly see discontinuities in the effects between key clusters, this is intentional. It basically makes the entire keyboard a view-port onto the underlying effect (the keys are windows).

**Comment by drashna** [comment]
@XScorpion2 your opinion?

**Comment by al3ph** [comment]
Yep, it can also be used to generate the info.json with a few tweaks.

⁣Get BlueMail for Android ​

**Comment by Xelus22** [comment]
Does this work for rotated keys?

**Comment by al3ph** [comment]
I think so, as the rotation does effect the key shape, kle defines the bounding box AFAIK, the key is inside this and rotated, my keypad came out with the right values, but I'm not sure whether I tested rotated keys to make sure.

⁣Get BlueMail for Android ​

**Pull request closed without merging**
