### PR TITLE
suv

### PR DESCRIPTION
**Pull request by AlisGraveNil**
## Description

The SUV is a 100% mechanical keyboard; DIY solder kit

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by drashna — CHANGES_REQUESTED** [review]
Could you rename the folder to use lower case?

**Comment by AlisGraveNil** [comment]
@drashna I did something...I have no idea if it renamed it properly

**Comment by drashna** [comment]
Folder name is still uppercase. 

You may need to name it to something else, and then back to `suv` to get it to take, properly.

**Comment by AlisGraveNil** [comment]
changed to 'truck' then back to 'suv' - it looks like it stuck this time

**Review by drashna — APPROVED** [review]

**Review by fauxpark — CHANGES_REQUESTED** [review]
Missing a readme.

**Comment by AlisGraveNil** [comment]
@fauxpark - I've got the readme now

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
