### PR TITLE
Added two songs to song_list.h

### PR DESCRIPTION
**Pull request by avatak**
## Description

I added two songs I use to song_list.h. 

First is FF_PRELUDE, which is the opening music to most Final Fantasy games.  

Second is TO_BOLDLY_GO, which from the main themes of Star Trek TNG and the original series.

It didn't seem like there was any sort of order to the list of songs, so I just added my two at the very end. Sorry if I missed something there.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by skullydazed** [comment]
On a personal aesthetic level I think to boldly go would work better one octave higher, but if you like it lower we'll merge it like this. :)

**Comment by avatak** [comment]
> On a personal aesthetic level I think to boldly go would work better one octave higher, but if you like it lower we'll merge it like this. :)
> 
> (Or it may be the difference between audio on AVR and ARM, I'm looking into that.)

I tested it just now with a Proton-C. Both of these songs sound very different (worse, in my opinion) coming from the Proton-C then they do from any of the AVR boards I've tried them on. 

Also the timing of both sounds really different to me on the Proton-C.

If you're interested, here is a comparison I recorded really quick:

[TO_BOLDLY_GO](https://www.youtube.com/watch?v=_8KCnp8tY0Y) (one octave higher as suggested)

[FF_PRELUDE](https://www.youtube.com/watch?v=n8Gbo3w-pp0) 

All I did for the test is copy the default keymap in the proton-c folder and tell it to play the song on startup. I haven't spent much time with ARM since I prefer split boards.

**Comment by skullydazed** [comment]
I talked to @jackhumbert about this, there's some work that needs to be done on the ARM side of things. Apparently the timing and tuning isn't right yet.

**Comment by avatak** [comment]
Oh okay. If everything should sound like it does through AVR boards in the end then I do think it sounds better in the lower octave. Though it is definitely better one octave up from the Proton-C.

**Comment by drashna** [comment]
Also, rests don't work, IIRC. :(

**Comment by drashna** [comment]
Was this waiting on anything, or ready to commit? 

@skullydazed Any issues with merging as is?

**Pull request merged**
