### PR TITLE
Updating KLOR in QMK Tree

### PR DESCRIPTION
**Pull request by t4corun**
Submitting my modernization take of @GEIGEIGEIST official firmware. Made it compatible with modern QMK while maintaining the features in the original firmware (haptics, audio, oled, encoders, etc)

## Description

- Configuration is now in `.json` files whenever possible to align with future QMK objectives
- The four layout variations are now different boards versus being combined into one file
- now Pro Micro RP2040 native

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [x] Documentation

### CODE REVIEW

**Comment by t4corun** [comment]
Linter failed because the geigeigeist/klor folder only has common configuration for each of the KLOR variants `yubitsume`, `konrad`, `saegewerk`, and `polydactyl`. The layouts are in each variant's keyboard.json file. Please let me know if there are further changes that need to be made

**Comment by zvecr** [comment]
> Configuration is now in .json files whenever possible to align with future QMK objectives

Existing configuration was already aligned. Worse, this PR introduces changes which actually deviate further from current standards.

> The four layout variations are now different boards versus being combined into one file

From what I can tell this is only for the changes to the RGB Matrix config? (Outside this, its actually preferred to have a single build target but fine if actually required to workaround limitations in the lighting framework.)

> now Pro Micro RP2040 native

The more fundamental issue is this change. What are users who built with an 32u4 pro micro, or something like a blok controller expected to use? I cant see us accepting this change.

**Comment by t4corun** [comment]
@zvecr Appreciate your feedback and I'm okay taking this back. So I can learn, would you please elaborate on `this PR introduces changes which actually deviate further from current standards`?

**Comment by zvecr** [comment]
From a quick skim,
* Unnecessary "empty" `.h` and `.c` files
* Changes to default behaviour at keyboard level that should be avoided
  * tapping term
* Setting values that are inferred
  * `rgb_matrix.led_count`
* Duplication of defaults
  * `MASTER_LEFT`
  * `DYNAMIC_MACRO_ENABLE`
  * `split.transport.protocol`
* Removal of keyboard level feature handling
  * OLED rendering
    * previously intentionally implemented for configurator 
* Implementation of `_kb` callbacks at keymap level
  * `oled_task_kb`
* Duplicacation of core behaviours
  * `suspend_power_down_kb`/`suspend_wakeup_init_kb`
* Files not containing licence headers

Plus i'm sure a lot more if I were to be doing a more formal review of the changes.

**Comment by t4corun** [comment]
Those make sense. Thank you again for your feedback. I'll close the PR

**Pull request closed without merging**
