### PR TITLE
Revert UART setup for redox_w keyboard to 0.15 version, fixes #16553

### LINKED ISSUE #16553: redox_w firmware broke with switch to UART
I could no longer produce a working firmware via configurator, while it worked before. I've built maually and verified that it broke between 0.15.25 (works) and 0.16 (does not work), and head also doesn't work. I've tried git bisect but must not be doing it right yet. I'll keep searching to try to figure out the cause.

The bad firmware flashes successfully but no keypresses register.

### PR DESCRIPTION
**Pull request by tomaszj**
## Description

This reverts the UART setup for `redox_w` keyboard back to its state in versions `0.15.x`. The main rationale is to resolve issue #16553 — ensure that `redox_w` users with USB-C receivers (myself included) can have a stable, working firmware whether using `0.16.x` version of `qmk` or the online `QMK Configurator`.

I realise this change reverts some of the good changes applied and I will be happy to explore how to later re-work `0.16` changes to work. At this point, however, my priority is to bring back `redox_w` to a working state, especially as people non-coders are currently affected. Looking forward to seeing guidance from experienced contributors.

The change has been tested on a recent Redox Wireless made by Falba Tech.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #16553 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]
To be blunt, I'd really prefer a fix rather than the revert here.  Mostly because "later" more often than not ends up being "never". 

That's not a comment on you, but just ... past experience. 

Otherwise, LGTM.

**Comment by tomaszj** [comment]
@drashna — I completely understand that. If you/others can point in me in the right direction on the topic, I'll be more than happy to prep the follow-up change (being both a programmer, as well as an electronic engineer). Hell, this could become the first open-source project I properly get stuck into!

However, first I want to avoid other people coming in fresh to QMK world with their Redox Wireless boards and getting confused about whether that purchase of a keeb was a good idea at all (read: that is where I was two days ago) :)

**Comment by drashna** [comment]
Honestly, I'm not sure about it, as I'm not too familiar with the uart stuff.  @fauxpark may be able to help. 

And yeah, can definitely understand that!

**Comment by fauxpark** [comment]
I don't have one of these boards so I can't really test anything, I was just following along with what the original code appeared to be doing. It may be helpful to see some logic analyser traces from working & non-working firmware, if possible.

**Comment by tomaszj** [comment]
@fauxpark — what's the best way to insert traces for QMK when loaded onto ATMega? Happy to experiment and try to get the newer, interrupt-based uart setup working.

Happy to merge this PR in the meantime to bring `master` branch to a working state for `redox_w`?

**Comment by tomaszj** [comment]
Think I've found the problem @fauxpark @drashna, raised a #17203 PR to handle it. For the time being I won't be able to get more into the details why this doesn't work, so let's decide on the new approach or a revert and push ahead to bring the firmware to a working state.

**Pull request closed without merging**
