### PR TITLE
fix issue with retro tapping

### LINKED ISSUE #6557: fast Tapped Key not registering with RETRO_TAPPING and TAPPING_TERM < 100
## Describe the Bug

Hi in my layout i use the following two LT defines:
```
#define ST(LAY) LT(LAY, KC_SPACE)
#define NAV_ESC LT(NAV, KC_ESC)
```

When using them with `RETRO_TAPPING` and `TAPPING_TERM 100` or smaller i noticed that space or esc would not register sometimes even when i clearly pressed and released the corresponding key. After some testing i could easily reproduce this by tapping an LT Key quickly after any other key on my default layer. e.g. <kbd>A</kbd> then <kbd>Space/Layer</kbd> will result in just 'A' rather then 'a ' with a space after it. It seems so be easier to reproduce this by pressing <kbd>Space/Layer</kbd> while <kbd>A</kbd> is still pressed and then release <kbd>A</kbd> first and then <kbd>Space/Layer</kbd>.

### Matrix
r/c for <kbd>A</kbd> is 02/1
r/c for <kbd>Space/Layer</kbd> is 00/7
Case 1 of missing space
```
r/c 0123456789ABCDEF
00: 0000000000000000
02: 0100000000000000

r/c 0123456789ABCDEF
00: 0000001000000000
02: 0100000000000000

r/c 0123456789ABCDEF
00: 0000001000000000
02: 0000000000000000

r/c 0123456789ABCDEF
00: 0000000000000000
02: 0000000000000000
```
Case 2 of missing space
```
r/c 0123456789ABCDEF
00: 0000000000000000
02: 0100000000000000

r/c 0123456789ABCDEF
00: 0000001000000000
02: 0000000000000000

r/c 0123456789ABCDEF
00: 0000001000000000
02: 0000000000000000

r/c 0123456789ABCDEF
00: 0000000000000000
02: 0000000000000000
```
### keyboard report
Missing space
```
keyboard_report: 00 00 04 00 00 00 00 00 
keyboard_report: 00 00 04 00 00 00 00 00 
keyboard_report: 00 00 00 00 00 00 00 00 
keyboard_report: 00 00 00 00 00 00 00 00
```
Working Space
```
keyboard_report: 00 00 04 00 00 00 00 00 
keyboard_report: 00 00 00 00 00 00 00 00 
keyboard_report: 00 00 00 00 00 00 00 00 
keyboard_report: 00 00 00 00 00 00 00 00 
keyboard_report: 00 00 2C 00 00 00 00 00 
keyboard_report: 00 00 00 00 00 00 00 00
```

## System Information

 - Keyboard: Katana60
 - Operating system: Arch Linux
 - AVR GCC version: 9.2 && 8.3
 - QMK Firmware version: 0.6.451

Edit: Also tested on avr-gcc 8.3

### PR DESCRIPTION
**Pull request by AckslD**
## Description
Fixes #6557

## Types of Changes
This is just the patch by @ales and updated by @rautesamtr made into a PR

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #6557

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
This still have the issue from https://github.com/qmk/qmk_firmware/issues/6557#issuecomment-857600505 ?

**Comment by AckslD** [comment]
@drashna Yes, unfortunately! @sigprof have some code (see https://github.com/qmk/qmk_firmware/compare/develop...sigprof:robust-retro-tapping) which could possibly be incorporated with this to solve both issues but I haven't had time to look into it yet

**Comment by drashna** [comment]
Oaky, thank you for confirming that.

I'd prefer to wait on making sure that it doesn't have issues.

**Comment by AckslD** [comment]
@drashna Yeah for sure, I thought it might be better to have this in a PR rather than some patches circling around :) So others might find it also. I added WIP to the title

**Comment by drashna** [comment]
Sounds good.  I've added the "in progress" label so that stale-bot won't close it, until working verified code has landed.

**Comment by AckslD** [comment]
@drashna The issue I had is now fixed. But I suspect that this fix might only work the way I'm using retro tapping and probably not for the normal use. I now simply changed the check of the counter from equality to greater of equal to one. In my case with:
```
#undef TAPPING_TERM
#define TAPPING_TERM 10
#define RETRO_TAPPING
```
it now does exactly what I want, ie this effectively gives permissive hold also for layers.

I'm not sure I have the knowledge for how to fix this properly in all cases, so maybe someone with more insight should look into it. But for anyone wanting to use the above settings this branch now supports that.

**Comment by sigprof** [comment]
This change is still questionable:

1. Because `retro_tapping_counter++` was moved inside `if (event.pressed) { … }` and `&& event.pressed` was added, retro tapping will ignore key release events. Before the change a sequence like “press X (a normal key), press A, release X, release A after tapping term” would not trigger the retro tapping behavior for A, because the “release X” event would increment the counter, making it not match the expected value at the “release A” time. With this change the same sequence will trigger the retro tapping behavior for A, because the release event for X will be ignored.
   This new behavior might actually be useful as an option, because the above sequence can arise just from fast typing, but it also might not be acceptable for some users.
2. The `retro_tapping_counter >= 1` comparison does not seem strict enough — now a sequence like “press A, press B, release A after tapping term” may trigger the retro tapping behavior for A, because the extra press event for B would be accepted by that comparison. However, the same change also fixes the “press A, press B, release B after tapping term” sequence (in this case the original retro tapping code did not trigger for B, even though it looks like it should). And it is impossible to distinguish these sequences without actually comparing the `event.key` values for press and release events.
3. Even if the `retro_tapping_counter >= 1` comparison is made strict again, a more complicates sequence like “press A, tap X (a normal key), press B, release A after tapping term” would still trigger the retro tapping behavior for A, because the tap of X will reset the counter, and then the code would handle “press B, release A” as if it was “press A, release A”.

**Comment by AckslD** [comment]
Thanks for explaining @sigprof! Any idea what a proper fix would be? Do you think some modification do your current branch could work?

**Pull request closed without merging**
