### PR TITLE
gcc 10 compatibility for Drop alt

### PR DESCRIPTION
**Pull request by DelusionalLogic**
According to the official documentation[1] gcc 10 is more strict about
correct extern usage.

I've had to split the definition and declaration of dmac_desc and dmac_desc_wb
from i2c_master.{c,h}. This could be an issue if anyone includes the
i2c_master.h file without liking with the object file.

I've also had to remove the keymap_config definition from all the massdrop alt
keymaps, since it's defined in magic.c as well. The same would have to be done
for other keymaps. It doesn't seem like any of the in-tree keymaps use the
variable anyway. Anyone using it would have to declare it extern in their
keymap.

With these changes all the in-tree keymaps for the massdrop alt now compiles in
gcc 10

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #9268 (This issue tracks multiple problems, this fixes part of it)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by DelusionalLogic** [comment]
For good measure I should probably say that compiling with `-fcommon` is also an option.

**Comment by DelusionalLogic** [comment]
@zvecr Could i ask what the breaking change here is? Keymaps that don't remove `keymap_config` won't compile with gcc 10 (as they won't right now), but will still continue to be compatible with previous gcc versions.

That is to say, people that don't want to remove `keymap_config` won't be any more broken after this patch.

**Comment by zvecr** [comment]
From the contributing guide which you have ticked as read,
> IMPORTANT: If you would like to contribute a bugfix or improvement to user code, such as non-default keymaps, userspace and layouts, be sure to tag the original submitter of the code in your PR. Many users, regardless of skill level with Git and GitHub, may be confused or frustrated at their code being modified without their knowledge.

And also <https://docs.qmk.fm/#/breaking_changes_instructions>,
> Edits to User Keymaps A user may submit their keymap to QMK, then some time later open a pull request with further updates, only to find it can’t be merged because it was edited in the qmk/qmk_firmware repository. As not all users are proficient at using Git or GitHub, the user may find themself unable to fix the issue on their own.

**Comment by DelusionalLogic** [comment]
Fair enough. I figured the since the change didn't really change anything that mattered it was ok, but I see the merge angle being a problem for non-dev users.

Would it be better if I split the changes into an i2c part and a keymap part? that way the i2c part wont be breaking.

Another options would be to forego changing any keymaps except default and let the users change them themselves.

Do you have a preference for either, or should I just leave it as is?

**Comment by drashna** [comment]
> Fair enough. I figured the since the change didn't really change anything that mattered it was ok, but I see the merge angle being a problem for non-dev users.

That may be, but issues arise when users want to update their repo. Not everyone is savvy with git, and handling merge conflicts.  We want to reduce that, or at least reduce the frequency of it happening.

**Comment by FabSchwul** [comment]
Thanks to this PR I could compile my Drop CTRL

**Comment by fauxpark** [comment]
If we get signoff from @abishalom, @bontakun, @favorable-mutation and @reywood, this can go straight into master.

**Comment by favorable-mutation** [comment]
LGTM! Thanks for adding this fix!

**Comment by reywood** [comment]
👍 looks good

**Review by fauxpark — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
@bontakun any objections?

**Comment by abishalom** [comment]
Fine by me

**Comment by tzarc** [comment]
Looks like it'll need to go to `develop` as @bontakun is non-responsive. Will give it another week and then point it at `develop` instead.

**Review by tzarc — APPROVED** [review]

**Pull request merged**
