### PR TITLE
Revert "mkiirgb/v3: Swap R and G lanes to achieve correct RGB."

### PR DESCRIPTION
**Pull request by vinorodrigues**
Reverts qmk/qmk_firmware#15511

WTH?  Who said the RGB was wrong in the first place?  As test use the `rgb_matrix_set_color(index, r, g, b)` [function](https://docs.qmk.fm/#/feature_rgb_matrix?id=direct-operation):
With the #15511 PR the outcome is not correct:
```
  rgb_matrix_set_color(i, 0, 0, 255);  // blue, and correct
  rgb_matrix_set_color(i, 0, 255, 0);  // supposed to be green, but is now red
  rgb_matrix_set_color(i, 255, 0, 0);  // supposed to be red, but now is green
```
Where did the assumption come from, and where is the issue raised that this was a problem?
 
The original (pre- #15511) code worked correctly.

### CODE REVIEW

**Comment by tzarc** [comment]
So now this begs the question -- are there variants of these boards that have different parts populated?

**Comment by tzarc** [comment]
@mik9 @moyi4681 please confirm

**Comment by vinorodrigues** [comment]
Just to affirm my belief that this may be a specific board issue - I have 2x KBD67's .. one brought on 27 July 2021 and another bought 11 December 2021 - both work as per original code base. i.e. @moyi4681 code is correct.

**Comment by mik9** [comment]
```
  rgb_matrix_set_color(i, 0, 0, 255);  // blue, and correct
  rgb_matrix_set_color(i, 0, 255, 0);  // supposed to be green, but is now red
  rgb_matrix_set_color(i, 255, 0, 0);  // supposed to be red, but now is green
```

Yes, these were results on my board before my changes With swapping its correct.
I have recent board from R3 (KDB67 Lite R3 kit).

**Comment by tzarc** [comment]
So basically we're now talking two of the same board, with RGB and BGR fitouts?

**Comment by vinorodrigues** [comment]
**I honestly don't know.**  I can say is that my 2x KBD67 Mk2 V3 (a.k.a. KBD67 Lite), one bought in in round 2 (a.k.a. "restock") and the second bought as a standalone PCB, both work with the before-#15511 code.

If you look at the history of this file; it was first uploaded by use @datafx on 8 Aug '21.  That commit (#13714) spilt out the original code and moved it to `v1` sub-folder, and then a `v3` sub-folder was created.  This codebase has been in use for 5 months with no one raising any issues with the RGB.  My 2 units certainly don't have an issue - and they're definitely v3's and the original code most certainly works.

image

The thing is that only the manufacturer can affirm if there is a variety of boards being used or if there is just a batch problem... I've reached out to them via discord and had no luck there.  Will try email shortly, and hopefully someone in the better know will hop on here and clarify.  Failing that, maybe @datafx or @moyi4681 can look at this?  :(

**Comment by datafx** [comment]
Unfortunately, I don't know too much about this board.  I only reverse engineered it to the best of my abilities when they refused to release the source code because I wanted to customize it.

**Comment by vinorodrigues** [comment]
Thank you @datafx 

I've been in contact with them via online chat - the support person said that they needed their engineer to look at it, and said would get back to me via email.  I'll update here ***if*** I get a response.

**Comment by vinorodrigues** [comment]
I've not heard back from KBDFans ... yet :(

Hopefully someone else with a KBD67 Lite *(and some coding experience)* can try to corroborate this issue - as we have it now, there are 3 known boards that work with the original @datafx code base, and then 1 (?) with the #15511 PR from @mik9 .

If "someone" *(maybe @mechmerlin ??? **please?** )* is willing, it's easy to test by creating a new keymap *(possibly a copy of `default`)* and add the following code:
```
void rgb_matrix_indicators_user(void) {
    if (host_keyboard_led_state().caps_lock)     {
        rgb_matrix_set_color(30, 0xFF, 0x00, 0x00);  // red = 255, green = 0, blue = 0
    }
}
```

If you're using the existing active code (with #15511 included) then pressing the Caps Lock key should light up:  if red then the #15511 PR is correct and we can close this PR and I've been wrong all along.

**Comment by moyi4681** [comment]
the original code is correct.

**Review by tzarc — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by tzarc** [comment]
@mik9 at this stage, given that the original maintainer has confirmed that the original code was correct, you'll have to get in touch with kbdfans support to figure out what's changed and why -- it sounds like you've potentially got a PCB that has had a component swapped out for something that wasn't a direct equivalent.

**Pull request merged**
