### PR TITLE
Update personal keymaps for non-kc LAYOUT (PR 12160)

### PR DESCRIPTION
**Pull request by DavidRambo**
## Description

Dear maintainers,
In light of PR 12160, which will be deprecating LAYOUT_kc, I went through all of my personal keymaps to ensure compatibility:
- crkbd/keymaps/davidrambo/keymap.c
- gh60/satan/keymaps/bri/keymap.c
- keebio/iris/keymaps/davidrambo/keymap.c
- planck/keymaps/davidrambo/keymap.c
- preonic/keymaps/davidrambo/keymap.c
- xd75/keymaps/davidrambo/keymap.c

These all compile.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by DavidRambo** [comment]
I just saw that some files in the chibios submodule are included here...which isn't right. I was having problems with making Preonic Rev3 with any keymap, and `make git-submodule` would not fix it. So I copied over the /lib/chibios from qmk/qmk_firmware to my own fork. Should I cancel this PR and try to resolve this chibios submodule issue before opening another PR?

**Comment by drashna** [comment]
Shouldn't need to close it, but this may help: https://docs.qmk.fm/#/newbs_git_best_practices

**Comment by DavidRambo** [comment]
Thanks, drashna. I've always merged my master and dev branches. I'll shift over to the recommended practices! In any case, the pull request was closed when I started trying to address this submodule issue. (Everytime I `git submodule deinit -f --all` and then `git submodule update --init --recursive`, it resolves my untracked submodule files. However, switching to either branch reinstates the untracked files... I'll initiate a new PR once I've resolved this.)

**Comment by DavidRambo** [comment]
Yes, exactly. I have always merged my master with my dev branch and committed to master. I'll do it through PRs from now on. The docs are super helpful. Thanks again!

**Pull request closed without merging**
