### PR TITLE
process_terminal: added api to allow user to register custom commands…

### PR DESCRIPTION
**Pull request by asterix24**
This pull request allow users register a custom command table to run in the terminal feature.

## Description

The terminal feature is so cool, but for now we can't have custom commands, and if we want to do that we should change qmk core code.
To allow users register custom commands, I did this patch, adding an api to extend terminal commands.

The main change of the module was:
- define `terminal_ctx_t` type
- define `stringcase_t` type
- added function `void process_terminal_register_user_command(stringcase_t * table)`

The `terminal_ctx_t`define terminal context, and hold therminal command and its arguments. This context will be passed to all terminal functions, system functions and user functions.

The `stringcase_t` defines the callback function and its terminal name. To compute the length of the table I will check when I find the table ends marker, in other words, the last element of the table. It should be a couple of NULL, like: `{NULL, NULL}`. This means that user should always add ends marker.. otherwise the fw could crash.

The function `void process_terminal_register_user_command(stringcase_t * table)`, register the user command table to the module, so the process_terminal module will also call the user callbacks.

Here I will show you an example of use:

```
static void cmd_eep_read(terminal_ctx_t *ctx) {
    uprintf("eep\n");
    SEND_STRING("eep..\n");
    for (int i = 0; i < ctx->args_no; i++)
        if (ctx->args[i])
            SEND_STRING(ctx->args[i]);
    SEND_STRING("\n");
}

stringcase_t isokey_cmd_table[] = {
    {"eep", cmd_eep_read},
    {NULL, NULL}, // Table termination
};

void settings_init(void) {
    process_terminal_register_user_command(isokey_cmd_table);
}

```

This example show also the possibilty to write your code where you want, specially in user code side.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Just a heads up that this feature has been in our sights to deprecate/remove due to lack of use and general bitrot. If you're willing to help keep it alive, that would be appreciated, but be warned that we may decide to remove it at some point. I'll defer to the other collaborators' opinions though, and if there are other users of this feature, please chime in with yours :)

**Comment by tzarc** [comment]
For clarity, in the repository this entire feature is only used by 1 keyboard, and 2 keymaps.

**Comment by asterix24** [comment]
Thanks for your fast review.I understand your point of view, but I would ask if you have a "standard" method that you would use to interact with the keyboard (usb feature end point, ecc..). In my mind I figured out a simple method to map a custom key to a special function.. without installing a 3rd part program to configure it, so this terminal function was so pretty.I have no problem maintaining this feature, but if you have an alternate method, I am happy to spend my time implementing my functionality using a "standard" way.

**Comment by fauxpark** [comment]
Any "standard" method of communicating with the keyboard in the way that you want would necessarily be QMK-specific, and thus *require* a 3rd party (or at least custom written) application running on the host. There is not really anything in the USB HID specification that covers this.

QMK does provide a way to send and receive arbitrary data: https://docs.qmk.fm/#/feature_rawhid
But you must define the format of this data, and write the code on both ends to do something with it.
One of the most notable implementations is VIA (and its open source successor VIAL), which allows, among other things, the keymap to be stored in EEPROM and thus modified at runtime using the host-side app.

**Comment by tzarc** [comment]
Apologies for letting this drag on a bit, but after some internal discussion we've decided that given the extremely low use of the terminal feature, we're going to minimise the overall maintenance cost and remove it from QMK.

We appreciate the work that has gone into this PR, but it's not the direction we'd like to take. Sorry!

**Pull request closed without merging**
