### PR TITLE
Dev user: 3x10 matrices, refactor keymaps, add locales.

### PR DESCRIPTION
**Pull request by EricGebhart**
layout matrices are all 3x10 instead of 12. The keymap is configurable, Base layers 
are grouped by locale, process record got cleaned up.  Improved readme.

## Description
Homogenizing my layouts, making locales work better.

Keyboard keymaps are reduced to almost nothing.  layers are chosen in the config.
layers are grouped by locale.  All keymaps are 3x10.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — CHANGES_REQUESTED** [review]
We really wont be able to do much with this PR due to the contents being all over the place.

* random core changes
  *  most likely from a bad merge/rebase
* `qmk_user_eag/` top level folder
* added keyboard should really be separate from keymap/userspace additions
  * also need to follow PR checklist

**Review by EricGebhart — COMMENTED** [review]
I looked over everything fixed a few things.  I think it's in good shape now.

**Comment by EricGebhart** [comment]
> I looked over everything fixed a few things. I think it's in good shape now.

The keyboard addition was a mistake,  The rebase was very painful.  It should have been
just my keymaps and my user space.

**Comment by EricGebhart** [comment]
Rotting.

**Pull request closed without merging**
