### PR TITLE
Kmini refactor and Configurator support

### PR DESCRIPTION
**Pull request by noroadsleft**
Refactored the default keymap to use `#include QMK_KEYBOARD_H`, and gave it a readability update.

Also filled out the `info.json` for Configurator support.

### CODE REVIEW

**Comment by noroadsleft** [comment]
Should solve one of @drashna's [issues](https://github.com/qmk/qmk_firmware/pull/3386#discussion_r202162830) in #3386

**Comment by drashna** [comment]
Could you add the said code to the matrix.c file? ;)

**Comment by noroadsleft** [comment]
Does it matter where the code goes?

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
