### PR TITLE
Fix i2c calls for HotDox keyboard

### PR DESCRIPTION
**Pull request by drashna**
## Types of Changes

- [ ] Core
- [X] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
No, but the avr i2c_master commands changed slightly, to clean them up (eg, bring the ARM and AVR versions more in line with each other). 

This board wasn't included in the update, so it's erroring out now.

**Comment by mtei** [comment]
I found this PR5387 after opening pr5394 and completing the fix. So, I close pr5394. 
This PR5387 seems to require an additional  https://github.com/qmk/qmk_firmware/pull/5394/commits/fe18a6de83028a278f7b45006d1086eaec99663f fix.

**Comment by drashna** [comment]
@mtei Thanks. 
I'd rather not change @JacobJerrell's userspace, if at all possible.  But I've tagged them to let them know about the issue.

**Comment by JacobJerrell** [comment]
> @mtei Thanks.
> I'd rather not change @JacobJerrell's userspace, if at all possible. But I've tagged them to let them know about the issue.

@drashna thank you for the consideration! I've been making some changes to my userspace while I transition into a new role at work. I'm going to sit on them for a while to prevent a stream of tiny updates. I'll be removing any remaining references to OSM's because I can't get my fingers used to it and it causes more problems than it solves.

**Comment by drashna** [comment]
@JacobJerrell You're very welcome!   We generally try to avoid changing user's keymaps, since it can cause issues (merge conflicts, which may not be easy to deal with for people new to git)...   Instead, we try to flag then when there is some cleanup that could be used, so they can change them on their own.

And I'm sorry to hear that OSM hasn't worked out for you. I love them, personally, but I know it's not for everyone.   Though, I mostly just use it for shift, which is amazing. :)

**Pull request merged**
