### PR TITLE
Seebs/lcddisplay

### PR DESCRIPTION
**Pull request by seebs**
This includes a couple of things from other pull requests, but the main thing is the last commit. (This replaces my ugly stenodisplay branch.) This gives a nicely factored out LCD interface, with an example use case for it, but also allowing other users to write their own things that interact with the LCD display in other ways.

### CODE REVIEW

**Comment by drashna** [comment]
Well, lots of merge conflicts now, sorry.

**Comment by seebs** [comment]
I actually have a rebased branch, although I think I'll just drop the LED code, it was an idle curiousity.

I think a bunch of the scanning changes got merged cleanly, but the LCD display code is still a separate thing and not in-tree yet. I should revisit it. Again. Someday when I have time.

**Comment by drashna** [comment]
Lots of merge conflicts

**Comment by seebs** [comment]
i got interrupted partway through submitting my fixed version that gets rid of the merge conflicts, and also drops some of the other code. i think it got broken by a change to the i2c API, then rebroken when I patched for that and the i2c API changed back. :P

**Comment by drashna** [comment]
oh, boy.  Yeah, a lot of i2c changes recently.   A lot of cool stuff added recently.

**Comment by drashna** [comment]
There are a bunch of merge conflicts here, again, sorry!

**Comment by seebs** [comment]
i will see if i can get a look at these again this weekend. i think some of this should probably Go Away, and I need to figure out which of the spare bits of code I have is the one I was actually using for the driver end.

**Comment by seebs** [comment]
So it turns out that apparently last time I got started on this, I actually got as far as uploading the relevant other project, and so on, and then forgot I'd done this.

Rebased my current tree against master cleanly, and here it is. It is possibly not mergeable as is, because of the complexities of the build/rules stuff, but I can't see a way to make this work without a way for features set in keymap rules.mk to control which files are included.

**Comment by drashna** [comment]
Okay, and thanks for the update, at the very least!!

**Pull request closed without merging**
