### PR TITLE
rename kprepublic bm keyboards to have a standardized naming format

### PR DESCRIPTION
**Pull request by peepeetee**
renames

bm60rgb => bm60hsrgb
bm60rgb_iso => bm60hsrgb_iso
bm60poker => bm60hsrgb_poker
bm65rgb => bm65hsrgb
bm65iso => bm65hsrgb_iso
bm68rgb => bm68hsrgb
bm80 => bm80hsrgb

As a result, the directory would look like this:

```
bm16a
bm16s
bm40hsrgb
bm43a
bm43hsrgb
bm60hsrgb
bm60hsrgb_iso
bm60hsrgb_poker
bm65hsrgb
bm65hsrgb_iso
bm80hsrgb
bm980hsrgb(in flight)
```

The standardized naming format I've came up with is :
Boards with rgb should be called `bmxxrgb`, boards with hot swap capability should be called `bmxxhs`, boards with both should be called `bmxxhsrgb`.

Varients are denoted by adding a `_` followed by the varient.
If the board has neither rgb nor hs, then the varient goes directly after `bmxx` without the `_`.
Conversely, if it has either rgb or hs, a `_` should be used.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by peepeetee** [comment]
@deadolus  @bitstarr @rgoulter

**Review by rgoulter — APPROVED** [review]

**Review by bitstarr — CHANGES_REQUESTED** [review]
please edit the build command in /keyboards/kprepublic/bm43rgb/keymaps/bitstarr/readme.md

**Comment by tzarc** [comment]
Just a note for other collaborators: this missed the deadline for the Nov'21 breaking changes -- it's preferable that this goes in earlier rather than later, so I'm marking it to be included.

**Comment by peepeetee** [comment]
please post suggestions to my standardized naming format in the comments, I could really use them

**Comment by bitstarr** [comment]
i'm fine whith this. it's a good idea to streamline naming. please make sure to edit all readmes too, so nobody gets confused.

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
This has merge conflicts that needs resolution

**Comment by peepeetee** [comment]
> 
> 
> i'm fine whith this. it's a good idea to streamline naming. please make sure to edit all readmes too, so nobody gets confused.

I am planning to open another pr to fix individual readmes at a later time, after this has been merged, to minimize work lost if I have to rebase

**Comment by peepeetee** [comment]
This concerns 2 open PRs.
#15001 by @bdtc123: please put your bm60v2_poker inside bm60hsrgb_poker/rev2
#12852 by @umbacos: rename from bm60ec_rgb to bm60hsrgb_ec

**Comment by peepeetee** [comment]
@mechmerlin @markva @bytesapart

**Comment by zvecr** [comment]
> I am planning to open another pr to fix individual readmes at a later time

Would rather it was done as part of the same PR

**Comment by peepeetee** [comment]
> 
> 
> > I am planning to open another pr to fix individual readmes at a later time
> 
> Would rather it was done as part of the same PR
copy, will do

**Comment by peepeetee** [comment]
> 
> 
> > I am planning to open another pr to fix individual readmes at a later time
> 
> Would rather it was done as part of the same PR

I currently have #14784 open, and I am unsure of how I should handle merging this pr with #14784, thus the hesitancy

**Comment by drashna** [comment]
> > > I am planning to open another pr to fix individual readmes at a later time
> > 
> > 
> > Would rather it was done as part of the same PR
> 
> I currently have #14784 open, and I am unsure of how I should handle merging this pr with #14784, thus the hesitancy

mostly, just: 
```sh
git checkout kprepublic_rename
git merge kprepublic_readmes
git commit
git push
```

**Comment by peepeetee** [comment]
> 
> 
> > I am planning to open another pr to fix individual readmes at a later time
> 
> Would rather it was done as part of the same PR

Done, thanks for the suggestion

**Review by tzarc — APPROVED** [review]

**Pull request merged**
