### PR TITLE
`matrix/noah`: move RGB Matrix LED config to data driven

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

```
⚠ matrix/noah: led_config: noah.c: Number of columns in row 0 (14) does not match matrix (15)
```
image
image

As with the DP60 (which is quite similar to this board) the ISSI config needs to be adjusted to match the new ordering. @yulei, I think I will need your help again with this board.

Also perhaps worth noting there appears to be another version of this PCB apparently used for the original Chinese GB, with two extra LEDs on the spacebar (again like DP60).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by yulei** [comment]
`const is31fl3731_led_t PROGMEM g_is31fl3731_leds[IS31FL3731_LED_COUNT] = {
/* Refer to IS31 manual for these locations
 *   driver
 *   |  R location
 *   |  |       G location
 *   |  |       |       B location
 *   |  |       |       | */


    {0, C1_9,   C3_10,  C4_10}, //RGB101
    {0, C1_10,  C2_10,  C4_11}, //RGB102
    {0, C1_11,  C2_11,  C3_11}, //RGB103
    {0, C1_12,  C2_12,  C3_12}, //RGB104
    {0, C1_13,  C2_13,  C3_13}, //RGB105
    {0, C1_14,  C2_14,  C3_14}, //RGB106
    {0, C1_15,  C2_15,  C3_15}, //RGB107
    {0, C1_16,  C2_16,  C3_16}, //RGB108
    {0, C5_16,  C4_16,  C6_16}, //RGB109
    {1, C1_2,   C2_2,   C4_3}, //RGB1010
    {1, C1_3,   C2_3,   C3_3}, //RGB1011
    {1, C1_4,   C2_4,   C3_4}, //RGB1012
    {1, C1_5,   C2_5,   C3_5}, //RGB1013
    {1, C1_6,   C2_6,   C3_6}, //RGB1014
    {1, C1_7,   C2_7,   C3_7}, //RGB1015
    {1, C1_8,   C2_8,   C3_8}, //RGB1016

    {0, C5_9,   C4_9,   C6_9}, //RGB201
    {0, C9_9,   C8_9,   C7_9}, //RGB202
    {0, C9_10,  C8_10,  C7_10}, //RGB203
    {0, C9_11,  C8_11,  C7_11}, //RGB204
    {0, C9_12,  C8_12,  C7_12}, //RGB205
    {0, C9_13,  C8_13,  C7_13}, //RGB206
    {0, C9_14,  C8_14,  C7_14}, //RGB207
    {0, C9_15,  C8_15,  C6_14}, //RGB208
    {0, C9_16,  C7_15,  C6_15}, //RGB209
    {1, C1_1,   C3_2,   C4_2}, //RGB2010
    {1, C5_1,   C4_1,   C6_1}, //RGB2011
    {1, C9_1,   C8_1,   C7_1}, //RGB2012
    {1, C9_2,   C8_2,   C7_2}, //RGB2013
    {1, C9_3,   C8_3,   C7_3}, //RGB2014
    {1, C5_8,   C4_8,   C6_8}, //RGB2015

    {0, C5_1,   C4_1,   C6_1}, //RGB301
    {0, C1_1,   C3_2,   C4_2}, //RGB302
    {0, C1_2,   C2_2,   C4_3}, //RGB303
    {0, C1_3,   C2_3,   C3_3}, //RGB304
    {0, C1_4,   C2_4,   C3_4}, //RGB305
    {0, C1_5,   C2_5,   C3_5}, //RGB306
    {0, C1_6,   C2_6,   C3_6}, //RGB307
    {0, C1_7,   C2_7,   C3_7}, //RGB308
    {1, C9_4,   C8_4,   C7_4}, //RGB309
    {1, C9_5,   C8_5,   C7_5}, //RGB3010
    {1, C9_6,   C8_6,   C7_6}, //RGB3011
    {1, C9_7,   C8_7,   C6_6}, //RGB3012
    {1, C9_8,   C7_7,   C6_7}, //RGB3013
    {1, C5_16,  C4_16,  C6_16}, //RGB3015

    {0, C9_1,   C8_1,   C7_1}, //RGB401
    {0, C9_2,   C8_2,   C7_2}, //RGB402
    {0, C9_3,   C8_3,   C7_3}, //RGB403
    {0, C9_4,   C8_4,   C7_4}, //RGB404
    {0, C1_8,   C2_8,   C3_8}, //RGB405
    {1, C1_10,  C2_10,  C4_11}, //RGB406
    {1, C1_11,  C2_11,  C3_11}, //RGB407
    {1, C1_12,  C2_12,  C3_12}, //RGB408
    {1, C1_13,  C2_13,  C3_13}, //RGB409
    {1, C1_14,  C2_14,  C3_14}, //RGB4010
    {1, C1_15,  C2_15,  C3_15}, //RGB4011
    {1, C1_16,  C2_16,  C3_16}, //RGB4012
    {1, C9_16,  C7_15,  C6_15}, //RGB4013
    {1, C9_15,  C8_15,  C6_14}, //RGB4015

    {0, C9_5,   C8_5,   C7_5}, //RGB501
    {0, C9_6,   C8_6,   C7_6}, //RGB502
    {0, C9_7,   C8_7,   C6_6}, //RGB503
    {0, C9_8,   C7_7,   C6_7}, //RGBSP1
    {1, C1_9,   C3_10,  C4_10}, //RGB506
    {1, C9_9,   C8_9,   C7_9}, //RGBSP2
    {1, C9_10,  C8_10,  C7_10}, //RGB507
    {1, C9_11,  C8_11,  C7_11}, //RGB508
    {1, C9_12,  C8_12,  C7_12}, //RGB5010
    {1, C9_13,  C8_13,  C7_13}, //RGB5011
    {1, C9_14,  C8_14,  C7_14}, //RGB5012


    //{0, C5_8,   C4_8,   C6_8},
    //{1, C5_9,   C4_9,   C6_9},
};`

the final version of noah only has 70 leds

**Comment by fauxpark** [comment]
Hm, I count 72 here:
https://www.carousell.sg/p/matrix-lab-noah-pcb-and-plate-1016707745/
and on the one in this video:
https://www.youtube.com/watch?v=GISZxZHqvFo

**Comment by yulei** [comment]
`const is31fl3731_led_t PROGMEM g_is31fl3731_leds[IS31FL3731_LED_COUNT] = {
/* Refer to IS31 manual for these locations
 *   driver
 *   |  R location
 *   |  |       G location
 *   |  |       |       B location
 *   |  |       |       | */

// left CB
    {0, C1_9,   C3_10,  C4_10}, //RGB201
    {0, C1_10,  C2_10,  C4_11}, //RGB101
    {0, C1_11,  C2_11,  C3_11}, //RGB102
    {0, C1_12,  C2_12,  C3_12}, //RGB103
    {0, C1_13,  C2_13,  C3_13}, //RGB104
    {0, C1_14,  C2_14,  C3_14}, //RGB105
    {0, C1_15,  C2_15,  C3_15}, //RGB106
    {0, C1_16,  C2_16,  C3_16}, //RGB107

    {0, C5_9,   C4_9,   C6_9}, //RGB202
    {0, C5_16,  C4_16,  C6_16}, //RGB304

    {0, C9_9,   C8_9,   C7_9}, //RGB203
    {0, C9_10,  C8_10,  C7_10}, //RGB204
    {0, C9_11,  C8_11,  C7_11}, //RGB205
    {0, C9_12,  C8_12,  C7_12}, //RGB206
    {0, C9_13,  C8_13,  C7_13}, //RGB207
    {0, C9_14,  C8_14,  C7_14}, //RGB306
    {0, C9_15,  C8_15,  C6_14}, //RGB307
    {0, C9_16,  C7_15,  C6_15}, //RGB308

// left CA
    {0, C1_1,   C3_2,   C4_2}, //RGB302
    {0, C1_2,   C2_2,   C4_3}, //RGB305
    {0, C1_3,   C2_3,   C3_3}, //RGB404
    {0, C1_4,   C2_4,   C3_4}, //RGB405
    {0, C1_5,   C2_5,   C3_5}, //RGB407
    {0, C1_6,   C2_6,   C3_6}, //RGB406
    {0, C1_7,   C2_7,   C3_7}, //RGB506-2
    {0, C1_8,   C2_8,   C3_8}, //RGB506

    {0, C5_1,   C4_1,   C6_1}, //RGB303
    {0, C5_8,   C4_8,   C6_8}, //RGB503

    {0, C9_1,   C8_1,   C7_1}, //RGB301
    {0, C9_2,   C8_2,   C7_2}, //RGB401
    {0, C9_3,   C8_3,   C7_3}, //RGB401-2
    {0, C9_4,   C8_4,   C7_4}, //RGB4014, split left shift, left of Z
    {0, C9_5,   C8_5,   C7_5}, //RGB402
    {0, C9_6,   C8_6,   C7_6}, //RGB403
    {0, C9_7,   C8_7,   C6_6}, //RGB501
    {0, C9_8,   C7_7,   C6_7}, //RGB502

// right CA
    {1, C1_1,   C3_2,   C4_2}, //RGB108
    {1, C1_2,   C2_2,   C4_3}, //RGB109
    {1, C1_3,   C2_3,   C3_3}, //RGB1010
    {1, C1_4,   C2_4,   C3_4}, //RGB1011
    {1, C1_5,   C2_5,   C3_5}, //RGB1012
    {1, C1_6,   C2_6,   C3_6}, //RGB1013
    {1, C1_7,   C2_7,   C3_7}, //RGB1015
    {1, C1_8,   C2_8,   C3_8}, //RGB1016

    {1, C5_1,   C4_1,   C6_1}, //RGB208
    {1, C5_8,   C4_8,   C6_8}, //RGB2015

    {1, C9_1,   C8_1,   C7_1}, //RGB209
    {1, C9_2,   C8_2,   C7_2}, //RGB2010
    {1, C9_3,   C8_3,   C7_3}, //RGB2011
    {1, C9_4,   C8_4,   C7_4}, //RGB2012
    {1, C9_5,   C8_5,   C7_5}, //RGB2013
    {1, C9_6,   C8_6,   C7_6}, //RGB2014
    {1, C9_7,   C8_7,   C6_6}, //RGB3013-2
    {1, C9_8,   C7_7,   C6_7}, //RGB3013
// right CB
    {1, C1_9,   C3_10,  C4_10}, //RGB408
    {1, C1_10,  C2_10,  C4_11}, //RGB309
    {1, C1_11,  C2_11,  C3_11}, //RGB3010
    {1, C1_12,  C2_12,  C3_12}, //RGB3011
    {1, C1_13,  C2_13,  C3_13}, //RGB3012
    {1, C1_14,  C2_14,  C3_14}, //RGB3014
    {1, C1_15,  C2_15,  C3_15}, //RGB3013
    {1, C1_16,  C2_16,  C3_16}, //RGB4015

    {1, C5_9,   C4_9,   C6_9},  //RGB409
    {1, C5_16,  C4_16,  C6_16}, //RGB4013

    {1, C9_9,   C8_9,   C7_9}, //RGB4010
    {1, C9_10,  C8_10,  C7_10}, //RGB4011
    {1, C9_11,  C8_11,  C7_11}, //RGB4012
    {1, C9_12,  C8_12,  C7_12}, //RGB507
    {1, C9_13,  C8_13,  C7_13}, //RGB508
    {1, C9_14,  C8_14,  C7_14}, //RGB5010
    {1, C9_15,  C8_15,  C6_14}, //RGB5011
    {1, C9_16,  C7_15,  C6_15}, //RGB5012
};`
OK, should be this one, the pcb shipped with GB keyboards

**Comment by fauxpark** [comment]
Thanks. I'll still need the silkscreen layer as before, to get them into the right order.

**Comment by yulei** [comment]
[noah_silks.pdf](https://github.com/user-attachments/files/16227655/noah_silks.pdf)

**Comment by fauxpark** [comment]
Looks like there is a typo in the code you provided above, there are two `RGB3013`s and no `RGB3015`. Which one is which?
```
    {1, C9_8,   C7_7,   C6_7}, // RGB3013 ?
    {1, C1_15,  C2_15,  C3_15}, // RGB3013 ?
```

**Comment by yulei** [comment]
> {1, C9_8,   C7_7,   C6_7}, //RGB3013

{1, C9_8,   C7_7,   C6_7}, //RGB3015

**Review by drashna — APPROVED** [review]

**Pull request merged**
