### PR TITLE
Add keyboard: mt40

### PR DESCRIPTION
**Pull request by tdehaeze**
Hi guys,

I bought a Chinese board that is a clone of the Planck ([here](https://world.taobao.com/item/548335974877.htm?fromSite=main&spm=a312a.7700824.w4002-6810221593.51.670e68a08mRh69)).

I had to check by myself all pins to make it works with QMK but now it's working like a charm! (even the RGB underglow)

I think some people could be interested by that ;)

Thanks

### CODE REVIEW

**Comment by jackhumbert** [comment]
I'm happy to support other similar hardware, but not under the name `chinese_planck` - do you know the official name for it/would you mind changing it to that? Do you have any contact info for the shop itself? I'd like to ask them to stop using "Planck" to avoid confusion.

**Comment by tdehaeze** [comment]
I'll be happy to change the name. Actually, I don't know what the real name is, but on the back of the PCB it's written "MT". Maybe we can go with "MT40" or something like that ?

Sorry, I don't have any contact... I bought this PCB on reddit (mechmarket).

By the way thank you for your amazing board, my preonic is my favorite :)

**Comment by jackhumbert** [comment]
Perfect! The lowercase `mt40` will work for the folder/filenames :)

Ah, gotcha - it's [this one](https://i.imgur.com/2Y1yTCE.jpg), right? The one on taobao looks a little different (maybe a different version?).

**Comment by tdehaeze** [comment]
I made those changes.

Yes indeed, it's that exact keyboard.

**Comment by jackhumbert** [comment]
Great! Thanks :)

**Pull request merged**
