### PR TITLE
For chibiOS I2C drive, move i2cconfig declaration in header file

### PR DESCRIPTION
**Pull request by yiancar**
## Description
In some complex scenarios the qmk i2c functions are not enough and falling back to the chibiOS i2c functions is needed. To do this for a single configuration, one can reused the i2cconfig already defined.
Currently it lives in the .c file which makes it non usable outside the i2c_master library.
Moving it to the header file seems more correct.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
You'll have to explain these "complex scenarios". Can this be done with an `extern`, instead?

**Comment by yiancar** [comment]
lets say I want to issue a i2cStart during pre_init part of the code.

**Review by zvecr — CHANGES_REQUESTED** [review]
static in headers is generally bad practice, and while we have workarounds for gcc10, these are meant to be temporary.

https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common

**Comment by yiancar** [comment]
Would keeping it as is and using an extern I2CConfig i2cconfig in my keyboard.c work?

**Comment by yiancar** [comment]
tryign to use an extern instead of this case causes a linking error where the linker cannot find the reference from the keyboard.c file.
linking is always my worst nightmare so I cant exactly figure out why it cant find the reference.

**Comment by tzarc** [comment]
So, regardless of the `extern`... what are you intending to do?

**Comment by yiancar** [comment]
Please ignore this thread PR
I did not see that i2c_start was available.

Cheers!

**Pull request closed without merging**
