### PR TITLE
Maartenwut/Maarten namechange to evyd13/Evy

### PR DESCRIPTION
**Pull request by evyd13**
## Description

Bit of a different PR, but I hope it's no problem.
I have changed my GitHub username from Maartenwut to evyd13 and would like to be called Evy, so that is most of the changes in this PR. I have also removed my personal keymaps from boards such as handwired, kbd66 and tada68, as I don't use those anymore. The URL maartenwut.com will stay for now, as I'm not sure what to do with that yet. I've also replaced some outdated stuff :)

Essentially, all occurrences of maartenwut or Maarten Dekkers have been replaced. The keyboards/maartenwut folder is now keyboards/evyd13.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by mrsendyyk — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by evyd13** [comment]
Does this need a changelog to be included in the current develop branch?

**Comment by noroadsleft** [comment]
> Does this need a changelog to be included in the current develop branch?

I'm not doing changelogs for `develop` PRs the way they were being done before. (Full disclosure: I'm not actually running the `develop` merges anymore.)

Anyway, I realized last cycle that there were way too many PRs going to `develop` for it to make sense to have the PR changelogs the way they were previously, so I just wrote one line for each PR, sorted by bugfix/feature addition/etc., and expanded upon that if needed.

The last Breaking Changes changelog was: https://docs.qmk.fm/#/ChangeLog/20200829. This PR would be for the first section, if I follow the same format (I'll probably write the changelog because... well, it needs to be done.)

Due to the scope of the changes, IMO it would be appropriate to target the `develop` branch with this.

**Comment by evyd13** [comment]
How would I target the develop branch? Resubmit the PR?

**Comment by fauxpark** [comment]
Hit the edit button at the top - you may need to rebase manually afterwards though.

**Comment by evyd13** [comment]
Seemed to work 👍

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
