### PR TITLE
Zinc: fix RGBLED_NUM bug

### PR DESCRIPTION
**Pull request by monksoffunk**
## Description

Since Breaking Changes 2021 February 27, rules.mk in keymap no longer affects config.h in higher levels.
As a solution, I moved the codes about RGBLED to post_config.h.

PS
After reading @drashna 's review, it turns out that the problem is not with RGBLED_NUM, but with the unnecessary RGBLED_SPLIT define in info_config.h, which is automatically generated from config.h by　build_keyboard.mk.
In anyway, this PR still works around the problem. See below for more details.
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
As far as I'm aware, there are no changes that would cause this issue to occur. 

n

**Comment by monksoffunk** [comment]
> As far as I'm aware, there are no changes that would cause this issue to occur.
> 
> n

I am sure of it, as I myself confirmed it after hearing about the problem from a user.

**Comment by drashna** [comment]
Testing compilation locally, I'm unable to reproduce any errors when compiling locally.  

Options turn on that are supposed to, etc.   What specific issue are you running into, and what commands are you using, exactly?

**Comment by monksoffunk** [comment]
No error occurs but I get a problem.

What I expect and QMK did before Breaking Changes 2021 February 27:
make ZINC=both zinc:default

'both' option turns on RGBLED_BOTH in keymap/default/rules.mk
https://github.com/qmk/qmk_firmware/blob/master/keyboards/zinc/keymaps/default/rules.mk#L61-L100

Next, rev1/config.h defines RGBLED_NUM 30 properly
https://github.com/qmk/qmk_firmware/blob/master/keyboards/zinc/rev1/config.h#L75-L82

Now, I mean After Breaking Changes 2021 Feb:
only 6 LEDs lite on.

This PR will fix this problem.

strangely enough, adding cont option, the  problem is free without this PR.

**Comment by drashna** [comment]
When I say that I do not experience this problem, I do mean that.  In the rev1 config.h, I've added the following before the `IOS_DEVICE_ENABLE` block to confirm the value that is selected. 
```
#if RGBLED_NUM == 48
#error RGB LEN NUM 48
#elif RGBLED_NUM == 24
#error RGB LEN NUM 24
#elif RGBLED_NUM == 60
#error RGB LEN NUM 60
#elif RGBLED_NUM == 30
#error RGB LEN NUM 30
#elif RGBLED_NUM == 12
#error RGB LEN NUM 12
#elif RGBLED_NUM == 6
#error RGB LEN NUM 6
#endif
```

Compiling with this generates:
```
❯ make zinc:default ZINC=both 
QMK Firmware 0.13.12
WARNING: Some git submodules are out of date or modified.
 Please consider running make git-submodule.

Making zinc/rev1 with keymap default

Zinc customize
-  LED_BACK_ENABLE=no        
-  LED_UNDERGLOW_ENABLE=no   
-  LED_BOTH_ENABLE=yes
-  LED_RGB_CONT=no           
-  RGB_MATRIX=no             
-  LED_ANIMATION=yes        
-  IOS_DEVICE_ENABLE=no      

avr-gcc (Homebrew AVR GCC 8.4.0_2) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text    data     bss     dec     hex filename
      0   16748       0   16748    416c .build/zinc_rev1_default.hex

Compiling: drivers/avr/serial.c                                                                    In file included from <command-line>:
./keyboards/zinc/rev1/config.h:101:2: error: #error RGB LEN NUM 30
 #error RGB LEN NUM 30
  ^~~~~
 [ERRORS]
```

And the other configs compile correctly, as well.

**Comment by monksoffunk** [comment]
Thanks for your confirmation.
It seems that I was mistaken.
The cause of the problem is not RGBLED_NUM, because even if RGBLED_SPLIT is not defined in config.h, the automatically generated info_config.h enables RGBLED_SPLIT { 6, 6 } by default. 

zinc/rev1/config.h handles LEDs in two ways: One mode is to set the appropriate number of LEDs with RGBLED_SPLIT when built with the 'cont' option, and to continuously lite the animation on both sides. The other is a mode in which the left and right sides emit their own separate animation patterns, as many split keyboards did before.

In the former case, RGBLED_SPLIT is defined, so there is no problem, but in the latter case, there is no define, so info_config.h appears to come into affect.

.//.build/obj_zinc_rev1/src/info_config.h
/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION zinc/rev1
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef LAYOUT_ortho_4x12
#   define LAYOUT_ortho_4x12 LAYOUT
#endif // LAYOUT_ortho_4x12

#ifndef MANUFACTURER
#   define MANUFACTURER 25KEYS
#endif // MANUFACTURER

#ifndef RGB_DI_PIN
#   define RGB_DI_PIN D3
#endif // RGB_DI_PIN

#ifndef RGBLED_NUM
#   define RGBLED_NUM 6
#endif // RGBLED_NUM

#ifndef RGBLED_SPLIT
#   define RGBLED_SPLIT { 6, 6 }
#endif // RGBLED_SPLIT

#ifndef RGBLIGHT_LIMIT_VAL
#   define RGBLIGHT_LIMIT_VAL 35
#endif // RGBLIGHT_LIMIT_VAL

#ifndef RGBLIGHT_HUE_STEP
#   define RGBLIGHT_HUE_STEP 10
#endif // RGBLIGHT_HUE_STEP

#ifndef RGBLIGHT_SAT_STEP
#   define RGBLIGHT_SAT_STEP 17
#endif // RGBLIGHT_SAT_STEP

#ifndef RGBLIGHT_VAL_STEP
#   define RGBLIGHT_VAL_STEP 4
#endif // RGBLIGHT_VAL_STEP

#ifndef PRODUCT
#   define PRODUCT zinc/rev1
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0xEA3B
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0x04D8
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 6
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { F4, D4, C6, D7, E6, B4 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 4
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { F6, F7, B1, B3 }
#endif // MATRIX_ROW_PINS


By taking the RGBLED-related processing in question to post_config.h, as in this PR, the behavior seems to be the same as before Breaking Changes 2021 Feb , since that part is not reflected in info_config.h.

**Comment by monksoffunk** [comment]
@drashna This PR just split config.h into config.h and post_config.h.
It doesn't seem to be a problem, does it?

**Comment by monksoffunk** [comment]
another month has passed.
please...

**Review by drashna — APPROVED** [review]

**Review by mtei — APPROVED** [review]

**Comment by monksoffunk** [comment]
Sorry for the delay, but I added RGBLIGHT_SPLIT to make it behave correctly when the cont option is not selected.
@mtei thanks!

**Review by mtei — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by monksoffunk** [comment]
@drashna @mtei thanks!!

**Pull request merged**
