### PR TITLE
Rework paths for eeprom locations.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

NVRAM/Wear-leveling prepwork.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by sigprof — CHANGES_REQUESTED** [review]
`platforms/chibios/flash.mk` → `platforms/chibios/drivers/flash/flash.mk` move looks like a mistake.

And apparently some include path adjustment is needed to make `#include "flash_stm32.h"` work.

**Comment by tzarc** [comment]
> `platforms/chibios/flash.mk` → `platforms/chibios/drivers/flash/flash.mk` move looks like a mistake.
> 
> And apparently some include path adjustment is needed to make `#include "flash_stm32.h"` work.

Yeah, the file move was in error.
Not sure why you're seeing an issue with the `#include "flash_stm32.h"` -- `multibuild` worked fine?

**Comment by drashna** [comment]
It's the test itself that is erroring out.

**Comment by tzarc** [comment]
Yeah, those tests are kinda gross.
Over time they'll swap over to the wear-leveling implementations, so we can get rid of these in due course.

**Review by drashna — APPROVED** [review]

**Comment by KarlK90** [comment]
For the rp2040 PR I took the approach to move vendor specific drivers under `platforms/chibios/drivers/RP/RP2040` and then `serial_vendor.c` and `ws2812_vendor.c` which allows automatic pickup by the makefile system. This might be an approach for the eeprom implementations as well?

**Review by KarlK90 — APPROVED** [review]

**Pull request merged**
