### PR TITLE
Fix broken link in wiki

### PR DESCRIPTION
**Pull request by Iaotle**

### CODE REVIEW

**Comment by Iaotle** [comment]
@fauxpark have you... tried the link? It's broken lmao. I wouldn't make the PR otherwise.

**Comment by nooges** [comment]
The docs are intended to be viewed via https://docs.qmk.fm and not through GitHub viewer.

**Comment by Iaotle** [comment]
baffling that you can't take a second to read the *PR title*

**Comment by Iaotle** [comment]
> The docs are intended to be viewed via https://docs.qmk.fm and not through GitHub viewer.

cool, thanks for the explanation

**Comment by fauxpark** [comment]
I read the title, which is why I linked you to the Vitepress docs.
This repo also doesn't use the GitHub "wiki" function, it was already obvious to me you meant you were looking at the raw markdown files.

**Pull request closed without merging**
