### PR TITLE
[Feature] QMK version information on `version.h`

### PR DESCRIPTION
**Pull request by elpekenin**
## Description

Redo of #20431

Adds versioning to said file, such that we can now `#if QMK_MAJOR == 0 && QMK_MINOR == 20` to check if local repo is at `0.20.x`. This would of course not be used by core code, but would allow/help users building locally when sharing code across several forks (eg VIAL being out of date) or a messy codebase(eg my working branch having 0.20-ish code, with a 0.17? tag)

This is done by:
1. New file `quantum/qmk_version.h`, so that we can really check the version of the codebase (git tags can be out of sync with the actual code)
2. Backwards compatibility: this include is guarded with `#if __has_include("qmk_version.h")` and the defines fallback to:
    - Using the git tag, should be good enough in most scenarios
    - `PRAGMA(GCC error ...` when git isn't checked (or fails doing so). This way, code should -allegedly- not break even if the versioning info can't be extracted but it isnt actually used. On this scenario, error message is slightly cryptic when doing `#if __QMK__ == 0`(pre-processor) while it is perfectly readable if you try and use `__QMK__` somewhere in the code(compiler).

Adds small maintenance burden of updating the file, but i dont feel it is much worse than updating the git, and could perhaps make a small script that does both code-gen the file and creates the git tag.

## Types of Changes

- [X] Core
- [ ] Bugfix
- [X] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by getreuer** [comment]
+1 Thanks for this PR. Being able to check the QMK version would be helpful when sharing userspace feature libraries [like I do](https://github.com/getreuer/qmk-keymap).

A common failure mode is that I share a library using recent QMK features, someone with an older version QMK attempts to use it, and compilation fails in a confusing way. It would be great if I could add a preprocessor check to my library like

```c
#if QMK_VERSION < (min version needed)
#error QMK setup is out of date. Please update.
#endif
```

**Comment by elpekenin** [comment]
Glad someone finds it useful 😃 Let me know if you can think of a better way of throwing errors (or any other sort of feedback)

Tried to create and use the `PRAGMA` macro(`_Pragma` func under the hood). Which according to the docs i read should work like a `#pragma` but with the addition that it can be part of other macros.... However it seems like `#if` works different than a macro (i can see why) and the error reporting is not as good as i would like.

**Comment by tzarc** [comment]
I'm not comfortable having hard-coded "fallback" values in the repo, without any sort of mechanism to automatically keep them updated. They won't get updated.

Additionally, we'd want to be using 2/2/4 BCD format for the version, not 2/3/3 -- this is to align with XAP. It already does so.

**Comment by elpekenin** [comment]
> without any sort of mechanism to automatically keep them updated.

What about a `qmk version x.y.z` (or the like) that both generates the file and the git tag? 
I guess some sort of check could be nice, to avoid users doing "wrong" tags on their clones. 

> 2/2/4, not 2/3/3

Sure, will do as soon as i can

**Comment by zvecr** [comment]
> What about a qmk version x.y.z (or the like) that both generates the file and the git tag?

We dont manually make the tags, so that would be somewhat useless.

**Comment by elpekenin** [comment]
Oh...

After a quick look, if my understanding is correct, the tags are create upon pushing changes to particular paths, thanks to `auto_tag.yml`. I have no idea how GitHub actions work, but making that workflow trigger a `qmk` command to generate the version file upon creating a new tag sounds somewhat easy. Can workflows even add/modify files like that, or would it need some special handling?

**Comment by zvecr** [comment]
> but making that workflow trigger a qmk command to generate the version file upon creating a new tag sounds somewhat easy

It cant be that way round, as then the tag would have the wrong information. You also have the issue where committing a file in a workflow will then trigger workflows.

**Comment by tzarc** [comment]
Not feasible in its current form, would need to be regenerated every build.

**Pull request closed without merging**
