### PR TITLE
Mt84rgbkeyboard

### PR DESCRIPTION
**Pull request by maikongk**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Duplicate of #10830

**Comment by drashna** [comment]
There are a number of issues with this PR, that need to be addressed. 

The main one is that the files added need to be in a folder under `keyboards`.  Eg, `keyboards/mt84rgb/`.

**Comment by maikongk** [comment]
sorry it is my first time to use it ,i had changed it but i dont know right or no ,please tell me ,thank you very much

**Comment by drashna** [comment]
The best place to start off with may be here:
https://docs.qmk.fm/#/newbs_git_best_practices

**Pull request closed without merging**
