### PR TITLE
Infer LED DRIVER_COUNT from configured addresses

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Why does a user need to explicit set the number of drivers? The configurer just had to set `ADDR_1`, `ADDR_2`, etc. There is also the issue where a count could be set incorrectly to the driver addresses, which would currently cause issue with the disconnected binding logic in `rgb_matrix_drivers.c`/`led_matrix_drivers.c`.

This PR reduces the required keyboard level configuration, and should address the additional issue mentioned above.

Once merged, a 2nd pass will be done to remove the redundant keyboard level defines.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by dexter93** [comment]
looks like this will open up a potential issue on declared address index not matching count. 
eg, scenario:
`DRIVER_ADDR_4` is declared, but there are less than 4 LED drivers. Maybe it's a good idea to safeguard it like
```c
#if (defined(DRIVER_ADDR_4) && defined(DRIVER_ADDR_3) && defined(DRIVER_ADDR_2) && defined(DRIVER_ADDR_1))
#    define DRIVER_COUNT 4
...
```
instead of
```c
#if defined DRIVER_ADDR_4
#    define DRIVER_COUNT 4
#elif defined DRIVER_ADDR_3
#    define DRIVER_COUNT 3
...
```
basically, moving the count logic to actually count the drivers needed instead of a declaration.

**Comment by sigprof** [comment]
> looks like this will open up a potential issue on declared address index not matching count

The difference is mostly in “how this code would fail to compile if the configuration is broken” though — in the original case it would fail with something like “`DRIVER_ADDR_3` not defined”, in your case it may be either “`DRIVER_COUNT` not defined” or silently doing some wrong thing if `DRIVER_COUNT` is actually defined somewhere.

**Comment by fauxpark** [comment]
I expect this all to be refactored into something akin to the matrix row/col pin arrays eventually anyway.

**Comment by zvecr** [comment]
> looks like this will open up a potential issue on declared address index not matching count.

Existing code wasn't any better, per keyboard level changes in 22312. The `projectd_65_ansi` case would have then indexed out of bounds in `aw20216s_update_pwm_buffers`. Worst case for this PR now would be extra memory allocated to the various buffers.

**Review by drashna — APPROVED** [review]

**Pull request merged**
