### PR TITLE
COD67 "Support"

### PR DESCRIPTION
**Pull request by mechmerlin**
This is not a 100% working port, but having the configurator will help immensely in my debugging of why I can't flash outside of windows.

### CODE REVIEW

**Comment by drashna** [comment]
Thanks!

**Comment by yangdigi** [comment]
Backlight PIN is PD6
Caps lock LED is PD4

**Comment by carlykaras** [comment]
> Backlight PIN is PD6
> Caps lock LED is PD4

@yangdigi Thank you for the clarification! Would you be able to confirm the RGB PIN as well?

**Comment by yangdigi** [comment]
> > Backlight PIN is PD6
> > Caps lock LED is PD4
> 
> @yangdigi Thank you for the clarification! Would you be able to confirm the RGB PIN as well?
RGB: PB2
/* Column pin configuration
 * col: 0   1   2   3   4   5   6   7   8   9   10  11  12  13 
 * pin: D7  F7  F6  F5  F4  F1  F0  E6  B0  B7  D0  D1  D2  D3 
 */
/* Row pin configuration
 * row: 0   1   2   3   4
 * pin: B5  C6  C7  D7  B4
 */

**Pull request merged**
