### PR TITLE
Enable OLED support for Teensy 3.2/LC

### LINKED ISSUE #7574: ARM I2C driver not implemented for KINETIS MCU's (i.e. Teensy 3.2/3.5/3.6/LC)
The I2C driver used for OLED functionality does not support KINETIS ARM microcontrollers.

## Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

I have been waiting to implement this functionality on my finished keyboard i made about 3 months ago. This has been discussed on the discord server and while some process was made, the driver has no proper definitions to compile and work with the Chibios hal driver. 

Setting the following in:
**mcuconf.h** 
```
#define KINETIS_I2C_USE_I2C1                TRUE
#define KINETIS_I2C_I2C1_PRIORITY           4
```

**config.h**
```
#define USE_I2CV1
#define I2C_DRIVER I2CD1
#define I2C1_OPMODE 1
#define I2C1_CLOCK_SPEED 100000
#define I2C1_DUTY_CYCLE 1

#define I2C1_SCL_BANK GPIOC
#define I2C1_SDA_BANK GPIOC
#define I2C1_SCL 10
#define I2C1_SDA 11
```

will result in the following compilation output:

```
tnf@tnf-VirtualBox:~/Desktop/github/qmk_firmware$ make lilith101:default
QMK Firmware 0.7.97
Making lilith101 with keymap default

arm-none-eabi-gcc (15:6.3.1+svn253039-1build1) 6.3.1 20170620
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text	   data	    bss	    dec	    hex	filename
      0	  34376	      0	  34376	   8648	.build/lilith101_default.hex

Compiling: drivers/arm/i2c_master.c                                                                In file included from <command-line>:0:0:
./keyboards/lilith101/config.h:120:26: error: excess elements in struct initializer [-Werror]
 #define I2C1_CLOCK_SPEED 100000
                          ^
drivers/arm/i2c_master.c:38:5: note: in expansion of macro 'I2C1_CLOCK_SPEED'
     I2C1_CLOCK_SPEED,
     ^~~~~~~~~~~~~~~~
./keyboards/lilith101/config.h:120:26: note: (near initialization for 'i2cconfig')
 #define I2C1_CLOCK_SPEED 100000
                          ^
drivers/arm/i2c_master.c:38:5: note: in expansion of macro 'I2C1_CLOCK_SPEED'
     I2C1_CLOCK_SPEED,
     ^~~~~~~~~~~~~~~~
./keyboards/lilith101/config.h:121:25: error: excess elements in struct initializer [-Werror]
 #define I2C1_DUTY_CYCLE 1
                         ^
drivers/arm/i2c_master.c:39:5: note: in expansion of macro 'I2C1_DUTY_CYCLE'
     I2C1_DUTY_CYCLE,
     ^~~~~~~~~~~~~~~
./keyboards/lilith101/config.h:121:25: note: (near initialization for 'i2cconfig')
 #define I2C1_DUTY_CYCLE 1
                         ^
drivers/arm/i2c_master.c:39:5: note: in expansion of macro 'I2C1_DUTY_CYCLE'
     I2C1_DUTY_CYCLE,
     ^~~~~~~~~~~~~~~
In file included from ./lib/chibios/os/hal/include/hal_pal.h:129:0,
                 from ./lib/chibios/os/hal/include/hal.h:124,
                 from drivers/arm/i2c_master.h:28,
                 from drivers/arm/i2c_master.c:28:
drivers/arm/i2c_master.c: In function 'i2c_init':
drivers/arm/i2c_master.c:66:44: error: 'PAL_MODE_STM32_ALTERNATE_OPENDRAIN' undeclared (first use in this function)
     palSetPadMode(I2C1_SCL_BANK, I2C1_SCL, PAL_MODE_STM32_ALTERNATE_OPENDRAIN);
                                            ^
./lib/chibios-contrib/os/hal/ports/KINETIS/LLD/hal_pal_lld.h:394:36: note: in definition of macro 'pal_lld_setpadmode'
     _pal_lld_setpadmode(port, pad, mode)
                                    ^~~~
drivers/arm/i2c_master.c:66:5: note: in expansion of macro 'palSetPadMode'
     palSetPadMode(I2C1_SCL_BANK, I2C1_SCL, PAL_MODE_STM32_ALTERNATE_OPENDRAIN);
     ^~~~~~~~~~~~~
drivers/arm/i2c_master.c:66:44: note: each undeclared identifier is reported only once for each function it appears in
     palSetPadMode(I2C1_SCL_BANK, I2C1_SCL, PAL_MODE_STM32_ALTERNATE_OPENDRAIN);
                                            ^
./lib/chibios-contrib/os/hal/ports/KINETIS/LLD/hal_pal_lld.h:394:36: note: in definition of macro 'pal_lld_setpadmode'
     _pal_lld_setpadmode(port, pad, mode)
                                    ^~~~
drivers/arm/i2c_master.c:66:5: note: in expansion of macro 'palSetPadMode'
     palSetPadMode(I2C1_SCL_BANK, I2C1_SCL, PAL_MODE_STM32_ALTERNATE_OPENDRAIN);
     ^~~~~~~~~~~~~
In file included from <command-line>:0:0:
drivers/arm/i2c_master.c: In function 'i2c_start':
./keyboards/lilith101/config.h:117:20: error: 'I2CD1' undeclared (first use in this function)
 #define I2C_DRIVER I2CD1
                    ^
drivers/arm/i2c_master.c:76:15: note: in expansion of macro 'I2C_DRIVER'
     i2cStart(&I2C_DRIVER, &i2cconfig);
               ^~~~~~~~~~
drivers/arm/i2c_master.c: In function 'i2c_transmit':
./keyboards/lilith101/config.h:117:20: error: 'I2CD1' undeclared (first use in this function)
 #define I2C_DRIVER I2CD1
                    ^
drivers/arm/i2c_master.c:82:15: note: in expansion of macro 'I2C_DRIVER'
     i2cStart(&I2C_DRIVER, &i2cconfig);
               ^~~~~~~~~~
drivers/arm/i2c_master.c: In function 'i2c_receive':
./keyboards/lilith101/config.h:117:20: error: 'I2CD1' undeclared (first use in this function)
 #define I2C_DRIVER I2CD1
                    ^
drivers/arm/i2c_master.c:89:15: note: in expansion of macro 'I2C_DRIVER'
     i2cStart(&I2C_DRIVER, &i2cconfig);
               ^~~~~~~~~~
drivers/arm/i2c_master.c: In function 'i2c_writeReg':
./keyboards/lilith101/config.h:117:20: error: 'I2CD1' undeclared (first use in this function)
 #define I2C_DRIVER I2CD1
                    ^
drivers/arm/i2c_master.c:96:15: note: in expansion of macro 'I2C_DRIVER'
     i2cStart(&I2C_DRIVER, &i2cconfig);
               ^~~~~~~~~~
drivers/arm/i2c_master.c: In function 'i2c_readReg':
./keyboards/lilith101/config.h:117:20: error: 'I2CD1' undeclared (first use in this function)
 #define I2C_DRIVER I2CD1
                    ^
drivers/arm/i2c_master.c:110:15: note: in expansion of macro 'I2C_DRIVER'
     i2cStart(&I2C_DRIVER, &i2cconfig);
               ^~~~~~~~~~
drivers/arm/i2c_master.c: In function 'i2c_stop':
./keyboards/lilith101/config.h:117:20: error: 'I2CD1' undeclared (first use in this function)
 #define I2C_DRIVER I2CD1
                    ^
drivers/arm/i2c_master.c:115:32: note: in expansion of macro 'I2C_DRIVER'
 void i2c_stop(void) { i2cStop(&I2C_DRIVER); }
                                ^~~~~~~~~~
cc1: all warnings being treated as errors
 [ERRORS]
 | 
 | 
 | 
tmk_core/rules.mk:377: recipe for target '.build/obj_lilith101_default/i2c_master.o' failed
make[1]: *** [.build/obj_lilith101_default/i2c_master.o] Error 1
Makefile:560: recipe for target 'lilith101:default' failed
make: *** [lilith101:default] Error 1
tnf@tnf-VirtualBox:~/Desktop/github/qmk_firmware$ Make finished with errors
```

Default values for OPMODE_I2C and STD_DUTY_CYCLE are missing (that's why they are set in the config file), and USE_I2CV1 should be defined by the driver.

This is the furthest i could get with my skills.
Functionality is already supported in Chibios.
Hopefully the community can implement this properly since it will open up the functionality of QMK even further:)
I can provide hardware testing since it is already build and used daily.

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Another situation where the ChibiOS hal does a poor job of abstraction, where I2Cv1 has a different config structure.

**Note:** Teensy LC do not have enough memory to run a 128x32 OLED in the codebases current state.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #7574

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by laughingrice** [comment]
Not sure if it helps, I merged the changes into master and managed to compile both my code and handwired/onekey on the teensy 3.2 with the i2c_scanner keymap, but no i2c device is found (error -1), I'm guessing that is the first step to get any I2C device working.

I will be happy for any pointers/examples/missing patches. Not sure if the problem is the I2C code or if it's using non-standard I2C pins

**Comment by zvecr** [comment]
Just rebased and retested.

Default pins seem to be 16 and 17 on this image,
image
With those, i2c scanner works fine.

**Comment by laughingrice** [comment]
I must be doing something wrong then.
I ran this sanity check / test using arduino and got "I2C device found at address 0x69"

```
#include <Wire.h>

void ScanI2C()
{
    int nDevices = 0;

    for(byte address = 1 ; address < 127 ; address++)
    {
        Wire.beginTransmission(address);
        byte error = Wire.endTransmission();

        if (!error)
        {
            Serial.print("I2C device found at address 0x");
            Serial.println(address,HEX);
            nDevices++;
        }
    }

    if (nDevices == 0)
        Serial.println("No I2C devices found\n");
}

void setup()
{
    Serial.begin(38400); // USB is always 12 Mbit/sec
    while (!Serial);

    Wire.begin();
    Wire.setSDA(17);
    Wire.setSCL(16);

    ScanI2C();
}

void loop() {}
```

I then tested the said branch:

```
git clone https://github.com/zvecr/qmk_firmware.git
cd qmk_firmware
git checkout feature/teensy_oled
make git-submodule
```

In `keyboards/handwired/onekey/rules.mk` changed the following 

```
DEFAULT_FOLDER = handwired/onekey/teensy_32
LAYOUTS = i2c_scanner
```

ran `qmk compile -kb handwired/onekey -km i2c_scanner`, flashed `.build/handwired_onekey_teensy_32_i2c_scanner.hex` and got

```
Scanning...
No I2C devices found
```

**Comment by zvecr** [comment]
As a FYI, you don't need to modify the rules.mk, just run `qmk compile -kb handwired/onekey/teensy_32 -km i2c_scanner`.

I assume there must be a difference in the I2C arduino implementation, and the device i'm using for testing responds differently.
https://github.com/qmk/qmk_firmware/blob/2f15cb21260f152b93c0ef76e780bba4f33e1938/keyboards/handwired/onekey/keymaps/i2c_scanner/keymap.c#L13-L17

**Comment by St0RM53** [comment]
@zvecr @drashna Anything i can test please let me know. My keyboard with teensy 3.2 has already oled connected to it via i2c that runs a demo if i flash it with an arduino based program, so hardware is functional. Just need you to point me to which code changes to re-compile and test.

**Comment by drashna** [comment]
From github itself, you should be able to run this:
```sh
git fetch origin refs/pull/7591/head
git checkout -b zvecr/feature/teensy_oled FETCH_HEAD
```

You may need to change the "origin" part to match whatever remove you have set for `https://github.com/qmk/qmk_firmware.git`, but aside from that ....  the above command s should let you test out the code change in question.

**Comment by St0RM53** [comment]
@drashna @zvecr 
Updated keyboard to work on latest QMK 0.8.133
Test results after enabling OLED driver in rules.mk :

Before applying the fix: https://pastebin.com/GcddgNbj
After applying the fix: https://pastebin.com/SA8ve5X0

Less errors but still an issue.
Here is the keyboard since i have issues updating by branch properly in github: https://www.dropbox.com/s/wcw5xuxjabdpdoz/lilith101.zip?dl=0

Remember to enable oled driver for testing.

**Comment by St0RM53** [comment]
After help from @zvecr compilation is successful for both I2CD1 and  I2CD2; however only I2CD1 was functional in my testing.

**Comment by St0RM53** [comment]
update:  All working fine for I2CD2 as well, the issue was missing definitions for the GPIO bank used for I2C1 pins as i2c_master.h uses by default Bank B where I2C0 pins are set.

**Comment by laughingrice** [comment]
Everything is working now. Not sure of the exact problem, for some reason this code was much more sensitive to running through a logic level converter than the teensy Arduino library version.

The scope showed that it's running at a much higher default frequency and probably uses a different logic level for 0/1 (logic level shifter was not shifting to the full range for some reason). I removed the logic level converter and am running the passive side (mpc23018) on 3.3 volts (cost a little on the maximum led level) and it's working now.

Looks like my PCB needs to go through another design iteration ...

**Comment by St0RM53** [comment]
@laughingrice  Yes everything is working as expect now. Teensy 3.2 runs on 3.3V so i am assuming your logic shifter might not be designed for that frequency or it's input impedance is too low for the T3.2 output

@drashna I'm assuming this will be closed automatically as soon as it is merged?

**Pull request merged**
