### PR TITLE
Moved tokyo60/ into tokyokeyboard/tokyo60/.

### PR DESCRIPTION
**Pull request by quadcube**
## Description
Moved tokyo60 keyboard into tokyokeyboard vendor directory.

## Types of Changes
1. Moved tokyo60/ into tokyokeyboard/tokyo60/.

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

**Comment by quadcube** [comment]
@tzarc Hi, could you help to review the pull request? Thanks!

**Review by drashna — APPROVED** [review]

**Review by fauxpark — CHANGES_REQUESTED** [review]
The readme will need to be updated with the new name of the keyboard.

**Comment by quadcube** [comment]
> The readme will need to be updated with the new name of the keyboard.

Hi, about the name, is it regarding the make instruction part?
Fixed the instruction with the correct path and broken readme image link

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
