### PR TITLE
`qmk info`: adjust numbering for matrix positions

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

This more closely matches the usual naming convention for `LAYOUT` macros.
image

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by skullydazed** [comment]
I selected a numer/letter combination initially because it's friendlier to people with dyslexia. This change would make it harder for people with trouble keeping numbers in the correct order.

**Comment by fauxpark** [comment]
To me it seems more confusing to have to mentally map between these values and the ones in the macro.

**Comment by skullydazed** [comment]
I agree, but changing all of the ones in the repo currently is a larger project than I want to take on. :) Longer term that definition will move to info.json and the LAYOUT macro will be generated at compile time, at which point there won't be a difference to have to map between.

**Comment by drashna** [comment]
Maybe add an option for `qmk info` on how to render this?

**Comment by fauxpark** [comment]
Done, it's now under the `--hex-matrix` switch, with the current labels as the default again.

**Review by drashna — APPROVED** [review]

**Comment by skullydazed** [comment]
I've been thinking about this one, but even as a temporary thing I'm not a big fan. I think on a long term basis #10790 will make this flag unnecessary, and hopefully now that it's so far along we can have that done sooner rather than later.

**Comment by fauxpark** [comment]
In that case I will replace this PR with something more useful.

**Pull request closed without merging**
