### PR TITLE
Added support for Mechmini v1

### PR DESCRIPTION
**Pull request by chilifries**

### CODE REVIEW

**Comment by jackhumbert** [comment]
Nice. Couldn't this be it's own keyboard in `keyboards/`, though?

**Comment by chilifries** [comment]
The Mechmini uses the same ps2avr board as the B.mini X2, so it more closely resembles a different layout than a new keyboard (at least programmatically).

**Comment by jackhumbert** [comment]
Yeah, but because of the difference in layout, I'd opt for it being a different keyboard altogether, so folks can more easily submit their own layout :) I can merge this and make the changes myself if you'd like!

**Comment by chilifries** [comment]
> I can merge this and make the changes myself if you'd like!

That would be great. Thanks!

**Comment by jackhumbert** [comment]
Cool! Thanks - I might ping you to test it out once I get things modified :)

**Pull request merged**
