### PR TITLE
handwired/3dortho14u: refactor layout data

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

Removes nonextant matrix positions from the layout data.

cc @xia0 (keyboard maintainer)

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Comment by xia0** [comment]
these key positions exist when wired as individual keys rather than 6u space or 2u enter.

**Comment by noroadsleft** [comment]
How would you feel about a PR that added the full ortho layout back in?

**Comment by xia0** [comment]
Yep

**Comment by xia0** [comment]
> How would you feel about a PR that added the full ortho layout back in?

I'll just PR a reversion of this.

**Pull request merged**
