### PR TITLE
Prime_E - Increase number of via layers

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Mentioned by `@Sterenke#4838 ` on Discord. As its quite a small board, we can squeeze a few extra layers in here.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by holtenc** [comment]
would it not be better to make this change at the keymap level? Newer revisions of the Prime_E PCB feature breakouts of used pins so users are mod their PCBs to their liking (ie RGB strips etc). I'm not sure how much EEPROM is utilized by VIA keymap layers or RGB features, but I don't see this as something that needs to be in the keyboard level firmware.

**Comment by holtenc** [comment]
additionally, forcing the loading/saving of more keymaps for all users unnecessarily adds to the time.

**Comment by zvecr** [comment]
> Newer revisions of the Prime_E PCB feature breakouts of used unpins so users are able mod their PCBs to their liking

These changes are almost certainly not going to be picked up by via, especially as its to be configured for the general use case. And given the general use case for 40% users is more layers, why limit it to just 4. **Remember via is for the user who does not want to get their hands dirty**.

> ie RGB strips

Core support is used here, and for most features, so does not expand eeprom use. The only current case is pure custom stuff, which wouldnt be supported on a per user basis anyway.

> forcing the loading/saving of more keymaps for all users unnecessarily adds to the time

This is a fair point, and i could try and provide some timings here.

**Comment by Wilba6582** [comment]
The default of 4 layers was originally based on 60% usage and what can fit in an Atmega32u4. I think as a rule, the number of layers should stay at 4 for 60% size and up, and for smaller, where it might be of some benefit, could go a bit higher. The problem is that the remaining space is used for macros, so it's a compromise... if you allocate all the EEPROM to keymaps, then that limits usability for people who only use less layers.

The number of layers and the amount of memory used for macros could be controlled by VIA - let the user decide at runtime if they'd prefer more layers or more macros - but this would have to wait for a VIA protocol upgrade and isn't as important as other more desperately required features such as generalizing the protocol and UI to let developers control custom things like lighting, encoders, OLEDs, piezos, etc.

For Prime_E, each layer is using 104 bytes, 8 layers is 832 bytes, so there's still 150ish bytes left for macros. Maybe 6 is better, idk... I'll let more experienced 40% users decide what's the optimum.

**Comment by Wilba6582** [comment]
FWIW, support for up to 8 layers will be added in next release of VIA

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
