### PR TITLE
[Docs] add "Adding Default Keymaps to QMK Configurator" doc

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

[title]

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Comment by s-show** [comment]
I have a question about `configurator_default_keymaps.md` which was added by this pull request.

I have translated several documents from [QMK Firmware Docs](https://docs.qmk.fm/#/) into Japanese, and I am currently translating `configurator_default_keymaps.md` into Japanese. I was able to translate most of the text, but there is one part that I cannot translate.

It's line 8, "As much as possible, these should be kept such that they behave the same as running `make <keyboard>:default` from `qmk_firmware `".

Is this sentence claiming that `.hex` created by `make <keyboard>:default` and `.hex` created by [QMK Configurator](https://config.qmk.fm/#/) should behave the same as much as possible? Is this OK?
@noroadsleft @drashna @fauxpark

**Comment by noroadsleft** [comment]
@s-show 

> Is this sentence claiming that `.hex` created by `make <keyboard>:default` and `.hex` created by [QMK Configurator](https://config.qmk.fm/#/) should behave the same as much as possible? Is this OK?

That's exactly what is meant by that sentence.

**Comment by s-show** [comment]
@NoahAndrews 
Thank you very much!

**Comment by NoahAndrews** [comment]
> 
> 
> @NoahAndrews
> Thank you very much!

Haha, I think you meant to thank @noroadsleft. It's been a long time since I've contributed to QMK.

**Pull request merged**
