### PR TITLE
 Update dynamic macros to expect `DYN_REC_STOP`, add cinaeco keymap, update vifon keymap

### PR DESCRIPTION
**Pull request by cinaeco**
(Take no.2) I was adding dynamic macros to my config and found that I wanted to stop macro recording in a different way. I've added DYN_REC_STOP so that it is more flexible.

As far as I can see, there are only 2 keymaps that use dynamic macros, vifon's and mine, so I have updated the @Vifon keymap with a couple of lines in `process_record_user()`. Thoughts on this solution?

### CODE REVIEW

**Comment by ezuk** [comment]
Very nice - if this is merged in, should anything be updated here? https://github.com/qmk/qmk_firmware/wiki/Macros#dynamic-macros-record-and-replay-macros-in-runtime

**Comment by cinaeco** [comment]
Yes, that will need to be updated. I'm happy to do that as well, if people want. Have never used github wikis before, so might need to be pointed in the direction of how to edit.

**Comment by Vifon** [comment]
I see a small potential problem. After your changes, when you release the layer you used to access the `DYN_REC_START` key, this key release gets recorded. I don't think it will cause any real issues apart from taking some constant space in the macro buffer, but it is definitely something to consider.

I'm already working on a solution so please wait with merging this PR.

**Comment by Vifon** [comment]
I've opened a new PR with my proposed solution. Mind that a similar problem occurs when stopping the recording: in case of @cinaeco the `UTIL` layer key will get recorded. It doesn't happen in my case because my stop button is essentially on my default layer.
By the way, thanks for the hotfix for my keymap after your changes, @cinaeco.

**Pull request closed without merging**
