### PR TITLE
New raw_hid_receive_user callback to benefit from RAW HID while still having VIA enabled

### PR DESCRIPTION
**Pull request by Nibelheims**
Hello,
I submit this PR to propose a way for the user to use HID RAW through a new dedicated callback named `raw_hid_receive_user`, to avoid clashing with VIA. It is then possible, for instance, to display host gathered metrics like CPU and RAM usage on an OLED screen while having the VIA feature enabled.

## Description

This is a very small and limited change:
- declaration of the new `bool raw_hid_receive_user(uint8_t *data, uint8_t length);` callback in `/quantum/raw_hid.h`, expected to return `true ` if the received data is to be further processed by `raw_hid_receive`. The user callback gets called first, and if it detects, typically thanks to some magic number or identifier, that it cannot deal with the data, it delegates it down the pipeline (typically to VIA)
- update the `raw_hid_task ` function in `tmk_core/protocol/chibios/usb_main.c`, to call `raw_hid_receive_user`, check its returned value, and call `raw_hid_receive` if necessary.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

NA

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage). Tested with my small and WIP project [gometrics](https://github.com/Nibelheims/gometrics) on a lily58 keyboard

### CODE REVIEW

**Comment by Nibelheims** [comment]
Hello,
I replicated the failing of QMK CI Build locally, and all the errors appear to be due to too large firmware. I have reverted my change and still get the same, for instance, with "yushakobo/ergo68:via".
Could the current contents of the "develop" branch induce those errors?
If I am mistaken, please indicate to me where I am wrong, and I will try to fix it.
Thanks!

**Comment by drashna** [comment]
CI failures are unrelated to this change, so no need to worry about that. 

Also, not sure about this change.  Generally, the biggest issue is with VIA which hijacks the endpoint and assumes nothing else uses it. 

Also, in general, it should follow function -> *_quantum -> *_kb -> *_user flow.   But I'm not really sure that this the direction that we want to head with this.

**Comment by Nibelheims** [comment]
Hi @drashna,
Many thanks for your reply.
You are right, this change is kinda the other way around but seemed the easiest route. Perhaps picking up a more suitable name? Something like `raw_hid_receive_before_via`, or `raw_hid_receive_first` ? I'm not very good at finding names.

**Comment by fauxpark** [comment]
The problem with this change in general, as drashna said, is that VIA pretty much takes over the raw HID interface. As such there is not much that can be done here without giving VIA its own interface separate from the raw HID system. Anything else just introduces more tech debt.

**Comment by Nibelheims** [comment]
OK I understand. I made it work by using a specific header to grab my custom packets, and successfully have used both VIA and my monitoring tool. However, I agree it introduces maintenance difficulties.

**Pull request closed without merging**
