### PR TITLE
Cleanup rules.mk for F303 keyboards

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

The rules.mk setup for STM32F303 is handled in mcu_selection.mk, so we should be able to just set `MCU` for these boards. Not sure if proton_c.mk could be included in this cleanup, but I believe we can also add similar stuff to mcu_selection.mk for the other supported ARM chips.

Additionally, chibios.mk appears to fall back to `drivers/boards/` if no `boards/` directory is found in the keyboard hierarchy. For the Hadron V3, HS60 V2 and NK65, theirs were functionally identical and can be removed.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Travis failure is due to the California, again.

Going to get my ARM toolchain set up to make absolutely sure the hashes don't change.

**Comment by fauxpark** [comment]
With console and command both disabled (probably just command that compiles the build time, now that I think about it):

```
master:
f3c24a2babfb6ea1da6b02f77905805d *clueboard_60_default.bin
ad9882e625d4cbaae73be1a4011ab99e *clueboard_66_hotswap_gen1_default.bin
46838ac355afb49de259eff976e4ddd0 *clueboard_66_rev4_default.bin
b195abf173474e64ddad78a17397bf7f *hadron_ver3_default.bin
be39403cbd44d9e9f96835eae0265342 *handwired_co60_rev6_default.bin
bf620fc0fd2e389bd51fc593559e397c *handwired_co60_rev7_default.bin
fcd9b4e584b965c573a43cf61334b671 *handwired_steamvan_rev1_default.bin
e303bc78cc3be4770e9aefeb282f3cc5 *hs60_v2_default.bin
c19558687885070ac2b6e8697c8ffa93 *nk65_default.bin

stm32f303-rules-cleanup:
f3c24a2babfb6ea1da6b02f77905805d *clueboard_60_default.bin
ad9882e625d4cbaae73be1a4011ab99e *clueboard_66_hotswap_gen1_default.bin
46838ac355afb49de259eff976e4ddd0 *clueboard_66_rev4_default.bin
b195abf173474e64ddad78a17397bf7f *hadron_ver3_default.bin
be39403cbd44d9e9f96835eae0265342 *handwired_co60_rev6_default.bin
bf620fc0fd2e389bd51fc593559e397c *handwired_co60_rev7_default.bin
fcd9b4e584b965c573a43cf61334b671 *handwired_steamvan_rev1_default.bin
e303bc78cc3be4770e9aefeb282f3cc5 *hs60_v2_default.bin
c19558687885070ac2b6e8697c8ffa93 *nk65_default.bin
```

Looks good 👍

**Comment by drashna** [comment]
Nice.   If that's the case, I may see about moving some of the Planck EZ's config into it's folder and out of the default (for sanity's sake).

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
