### PR TITLE
Update lighting effects for xbows ranger keyboard 

### PR DESCRIPTION
**Pull request by XBowsTech**
## Description

Update lighting effects for xbows ranger keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by XBowsTech** [comment]
Hey qmk/qmk_firmware

Thank you for contacting us. This is an automated message to let you know that we have received your message. We will get back to you as soon as possible.

Best,
The x-bows team

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Comment by XBowsTech** [comment]
Hey qmk/qmk_firmware

Thank you for contacting us. This is an automated message to let you know that we have received your message. We will get back to you as soon as possible.

Best,
The x-bows team

**Comment by XBowsTech** [comment]
Hey qmk/qmk_firmware

Thank you for contacting us. This is an automated message to let you know that we have received your message. We will get back to you as soon as possible.

Best,
The x-bows team

**Comment by XBowsTech** [comment]
Hey qmk/qmk_firmware

Thank you for contacting us. This is an automated message to let you know that we have received your message. We will get back to you as soon as possible.

Best,
The x-bows team

**Pull request merged**
