### PR TITLE
Document functions in a table

### PR DESCRIPTION
**Pull request by filterpaper**
## Description

Place functions in an easier-to-read table

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Feature docs (at least the API section) should be structured more like this: https://docs.qmk.fm/#/feature_leader_key

**Comment by filterpaper** [comment]
> Feature docs (at least the API section) should be structured more like this: https://docs.qmk.fm/#/feature_leader_key

In this case, the original format is fine and preferred?

**Comment by fauxpark** [comment]
I've been trying to establish something of a "standard" format for at least the feature and driver docs:
https://docs.qmk.fm/#/feature_leader_key
https://docs.qmk.fm/#/feature_programmable_button
https://docs.qmk.fm/#/feature_send_string
https://docs.qmk.fm/#/feature_hd44780
https://docs.qmk.fm/#/feature_digitizer
https://docs.qmk.fm/#/feature_joystick
https://docs.qmk.fm/#/i2c_driver
https://docs.qmk.fm/#/spi_driver
https://docs.qmk.fm/#/uart_driver

**Comment by filterpaper** [comment]
Thanks for the guidance.

**Pull request closed without merging**
