### PR TITLE
clang-format the future branch via `qmk cformat`

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

[title]

## Types of Changes

- [x] Core
- [x] Enhancement/optimization

## Checklist

- [x] My code follows the code style of this project.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
> If you want consistency with master, then future needs to be rebased to pick up #8063 (this ignores `tmk_core/protocol/usb_hid'`).
> 
> Optionally, `drivers/boards` should be reverted (clang formatting on master was broken when these files were added)

The next `future` rebase will pick up 8063.

Should `drivers/boards/` be added to the ignore list?

**Comment by zvecr** [comment]
If you want this in before rebasing to pick up #8063, then you should revert changes to `tmk_core/protocol/usb_hid`.

> Should drivers/boards/ be added to the ignore list?

maybe, personally I would prefer a different folder structure.

**Comment by noroadsleft** [comment]
> If you want this in before rebasing to pick up #8063, then you should really revert changes to `tmk_core/protocol/usb_hid`.

Debating whether to merge now or wait until after the next rebase (which would be Friday).


> > Should drivers/boards/ be added to the ignore list?
> 
> maybe, personally I would prefer a different folder structure.

If you want to change the folder structure go for it; that work would be over my head anyway.

**Comment by zvecr** [comment]
@tzarc do the board format changes cause any potential issues with ChibiOS stuff?

**Comment by tzarc** [comment]
Shouldn't really... given that all the ChibiOS stuff is already on the branch already it's not like there's a pending merge coming in afterwards.

**Pull request merged**
