### PR TITLE
Initial arm->chibios pass

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Some small steps towards the [documented](https://hackmd.io/9kvL2bT4Q42tPO1UqP0clg) future folder structure.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
LGTM, I'm not sure if stylistically we'd want spaces in between the make variables and `=`, but conceptually looks fine.

**Comment by Syzygies** [comment]
This breaks `make planck/ez:default`, which still looks for target `drivers/arm/i2c_master.c`, now moved to `drivers/chibios/i2c_master.c`.

I'm new around here, and I couldn't figure out how to patch this. `arm` is a pretty common word.

**Comment by fauxpark** [comment]
Seems to compile fine for me on latest master :/

**Comment by Syzygies** [comment]
Huh.  I forked `qmk/master (upstream)`, current as of 10:26am today, reproduced the bug, and used git bisect to identify this commit. Reading this commit, I could see that `arm` was moved to `chibios`, but I couldn't see how `planck/ez` was notified of this move. This painted a consistent picture for me, so I thought it expedient to post the above comment rather than a full bug report. If we're having different experiences, then a full bug report detailing my configuration and evidence would be in order.

Can someone explain how `planck/ez` is supposed to learn of this move? I couldn't figure that out; I was hoping to simply propose a patch, but I failed.

```
  485  git bisect start
  486  git bisect good 2a31fbf9a
  487  git bisect bad 6d1af6384
  489  git bisect good
  491  git bisect bad
  493  git bisect good
  495  git bisect bad
  497  git bisect good
  499  git bisect bad
  506  git bisect reset
```
My experience is that `planck/ez` is not learning of this move:

`make[2]: *** No rule to make target 'drivers/arm/i2c_master.c', needed by '.build/obj_planck_ez_syzygies/i2c_master.o'.  Stop.
`
I'll start again from scratch. I'm new to QMK, but I did spend hours on this.

**Comment by fauxpark** [comment]
As far as I can tell nothing under `keyboards/planck` directly references i2c_master - but the EZ uses one of the ISSI drivers for RGB matrix, so evidently something must have gotten stuck when you updated.

**Comment by Syzygies** [comment]
Thank you.

Sure enough, the following scorched-earth script runs fine as is, or with either checkout uncommented:

```
rm -rf clone
mkdir -p clone
cd clone
git clone https://github.com/qmk/qmk_firmware.git
cd qmk_firmware/
make git-submodule
# git checkout 2a31fbf9a # good
# git checkout 6d1af6384 # bad
git status
make planck/ez:default
```

So I went back to my saved branch where I could reproduce the problem. I reproduced the problem, ran `make clean`, and the problem went away.

There's the obvious conclusion that I'm an idiot for not trying `make clean` earlier. However, after bisecting lead me to this commit, it sure read like a smoking gun. But I have felt for a week now like some kind of hidden state was chasing me around. I wrote it off as functional-programmer-paranoia. We're living in strange times.

A different conclusion is that there's a subtle bug in the makefile dependencies. If so, we'll never find it. I'd be happy to instead force a `make clean` on every upstream commit.

**Pull request merged**
