### PR TITLE
Defer sending keyboard report to host until after matrix loop

### PR DESCRIPTION
**Pull request by hongaaronc**
**This is currently a WIP, and I'm mostly just publishing it here to get some feedback on it.**

## Description

This change defers calling "host_keyboard_send(keyboard_report)" until after the matrix loop.

This enables the ability to send multiple key changes in a single report, which also means that multiple key changes can be detected in a single polling cycle. This essentially allows us report more information in the same amount of time at no additional cost.

Before this change, only one key change (a press, or release) could be sent at a time. This is because "host_keyboard_send(..)" was created as a blocking method so that data cannot be changed mid-transmission to host, and this method was formerly called immediately after any change was made to the keyboard report. Calling this method at this point meant that the remainder of the polling interval would be used to send the report to host.

The impact of this can be very significant in gaming scenarios, when multiple keypresses need to be triggered simultaneously. See issue #4904 for more details.

I tested the change manually on a Fox Leaf 60 and a Romac, and compared directly against the same firmware without the change. I've confirmed in manual testing that this allows multiple simultaneous keypresses, while not seeming to introduce any new issues.

**Manual testing notes:**
- In the config.h, define QMK_KEYS_PER_SCAN to be greater than 1. This will be the number of key presses or releases that can go into a single report.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

Exact changes include:
- In "send_keyboard_report(..)" method, flag the last report's state as dirty instead of immediately sending report to host
- Create a new "send_keyboard_report_immediate(..)" method which is called after the matrix loop, which checks if the last report sent to host is dirty and sends an updated report if so, then sets it to clean

## Issues Fixed or Closed by This PR

* Issue #4904

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by tzarc — CHANGES_REQUESTED** [review]
In general, looks decent enough.
I'd like to get this guarded behind a define though, perhaps something like `#ifdef DEFERRED_KEYBOARD_REPORTS` or something, just so we can ensure we're able to allow for configurability as well as ensuring we have a way to back out to existing functionality. It'd require docs to go with it.

We should probably then see if it's worth applying the same logic to the other reports, I guess?

**Comment by hongaaronc** [comment]
Looks like 9 tests are failing in CI. I just figured out how to run that locally, so I'll have to look into that more. I haven't really used Google's test suite, so it might take a bit.

> In general, looks decent enough.
> I'd like to get this guarded behind a define though, perhaps something like `#ifdef DEFERRED_KEYBOARD_REPORTS` or something, just so we can ensure we're able to allow for configurability as well as ensuring we have a way to back out to existing functionality. It'd require docs to go with it.
> 
> We should probably then see if it's worth applying the same logic to the other reports, I guess?

This all sounds reasonable to me. I can certainly add the define. Not sure of what other reports QMK makes besides keyboard reports, any specific ones I should check out?

**Comment by tzarc** [comment]
The CI tests failing are the unit tests to ensure the keyboard acts correctly -- given you've changed the core logic w.r.t. keyboard reporting, it's unsurprising that they're broken.

Ultimately, if you add the define, these will likely start working again so long as the default for the define is "off".

As for the other reports, I'm not entirely sure -- @fauxpark is likely to know more than I, in that respect.

**Comment by tzarc** [comment]
> Ultimately, if you add the define, these will likely start working again so long as the default for the define is "off".

And for clarity, the CI test failures are for things like macros and the like -- it's understandable that your modifications break those as they'd normally be outputting keycodes sequentially, instead of simultaneously.

**Comment by hongaaronc** [comment]
I added the define.

- I manually tested a Fox Leaf 60 firmware with the define on and firmware with the define off - and haven't noticed any issues on either. Still haven't tested out macros yet.
- All unit tests pass with the define not specified,
- Same 9 unit tests fail with define specified

**Comment by hongaaronc** [comment]
I just manually tested macros - turning on the deferred keyboard report feature breaks them. Will investigate.

**Comment by hongaaronc** [comment]
I fixed the macro support - and got macro related unit tests working as well as testing macros manually on my Leaf 60. When the feature define is included, it is now only failing 5 unit tests.

Here are the changes since last revision:

Rather than modify the functionality of all "send_keyboard_report(..)" calls - the method now sends the keyboard report immediately like before. A new function called "send_keyboard_report_deferred(..)" handles the deferred support if the define is set, and I've replaced former calls to "send_keyboard_report(..)" with the new "send_keyboard_report_deferred(..)" function along the code path for handling keys through the matrix scan (this will not affect other calls, such as how macros are handled).

The only thing I don't like right now about this pull request are the method names. It's hard to come up with names that make sense without renaming existing methods (which are referenced in so many custom keyboard implementations). I tried to avoid renaming the existing ones to reduce the footprint of this pull request - but I think it kind of makes my naming conventions confusing in the end. I'm very open to suggestions regarding this concern.

**Comment by drashna** [comment]
This needs rebasing. 



> When the feature define is included, it is now only failing 5 unit tests:

I'm not thrilled about that, at all.  The tests are there for a reason, and unless there is a VERY good reason, they should not fail, at all.

**Comment by hongaaronc** [comment]
> I'm not thrilled about that, at all. The tests are there for a reason, and unless there is a VERY good reason, they should not fail, at all.

Sorry, I probably wasn't clear by what I meant there. I don't mean to brush this off test failures as "a small price to pay" or anything in that vein - you're absolutely right, and I agree that there is importance in having and using the unit testing, which is why I called them out. I just didn't have the time to address the issues immediately, and wanted to make sure they are called out so this doesn't get shipped before those test failures are addressed.

I was not intending to necessarily ship this change as-is but I wanted some eyes and feedback on it in the current state to help me move it forward, and probably should have tagged this as WIP. Sorry about the misunderstanding - I've just added a note to the first post to clarify. Maybe this isn't the right place for it, or maybe Collaborators was tagged too soon - if it's preferred to use Discord instead for the getting WIP feedback, I can do that - but I figured Github was more suited for reviewing code changes and seemed appropriate. Let me know if I should close this for now and reopen it when it's fixed or move it elsewhere or something.

I can probably have a look at fixing this over the weekend.

**Comment by PickleTicklewithnospace** [comment]
Can confirm this works on the melody96 board. Macros seem to still be sent sequentially with 8ms separating them though (if that's something you're concerned about)

**Comment by hongaaronc** [comment]
The current state of this is that most QMK functionality works with this change, but the change also resurfaces a few bugs like this, and some similar ones:
https://github.com/qmk/qmk_firmware/issues/1708

There was a fix to this issue (which I believe fixes multiple of these bugs/unit tests), but it does not seem to work with my changes: https://github.com/qmk/qmk_firmware/blob/master/tmk_core/common/action.c#L844-L846

I'm going to close this for now - since I don't think I have time to get back to it soon. I may look to reopen or submit a new PR later after the issues are addressed.

**Comment by KarlK90** [comment]
Hi @hongaaronc I had a look at you're changes today, great work so far! 

My daily key map has many tapped modifiers aka. homerow-mods that where non-functional with the changes. This was due to the way they are implemented, the keycode for pressing and releasing are registered the moment the key is physically released inside a time window the "tapping term". Now with the non deferred implementation two independent reports where send. With the deferred implementation an empty report is send because the tapped key is registered and unregistered in the same report time window. To mitigate this issue all tapped unregister key codes are appended to the next report that is send. 

Have a look at this [commit in my personal repository](https://github.com/KarlK90/qmk_firmware/commit/9cf79969e00802fa0fa68137c9626f2cfdd247ee).

Let me know if you are interested in picking up this issue again :-).

**Comment by KarlK90** [comment]
Oh yes, the number of failing unit-tests have increased but I'm confident that they can be fixed.

**Comment by KarlK90** [comment]
Hi @hongaaronc if have openend a [PR](https://github.com/qmk/qmk_firmware/pull/12686) with my changes on top of yours, hope you don't mind picking this up.

**Comment by hongaaronc** [comment]
That's great @KarlK90 ! Those changes make a lot of sense, and seem promising. I haven't had a chance to test them out myself yet, but I'll get around to it eventually and be watching your PR. Let me know if there's anything I could help out on.

**Comment by KarlK90** [comment]
Thank you :slightly_smiling_face:, looking forward to your feedback if this works for you.

**Pull request closed without merging**
