### PR TITLE
Remove unnecessary `rgblight.h` include.

### PR DESCRIPTION
**Pull request by mtei**
## Description

remove `#include "rgblight.h"` when `defined(RGB_MATRIX_ENABLE)` from quantum.h

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by fauxpark — CHANGES_REQUESTED** [review]
Should also be removed from the RGB Matrix VPATH in common_features.mk

**Comment by mtei** [comment]
> Should also be removed from the RGB Matrix VPATH in common_features.mk

```shell
% grep rgblight_list quantum/rgb_matrix*.[ch]
quantum/rgb_matrix.h:#include "rgblight_list.h"
```

**Comment by fauxpark** [comment]
#13371

**Comment by mtei** [comment]
This PR target is 'master'.

**Comment by fauxpark** [comment]
Ah right. So my PR can be reverted once this is merged.

**Review by fauxpark — APPROVED** [review]

**Comment by LechuckThePirate** [comment]
I lost my rgb when I applied this tag. Should I make any modifications to my keymap?? I'm using RGBLIGHTS not RGB MATRIX

```RGBLIGHT_ENABLE     = yes # Enable RGB Lights
VIA_ENABLE          = no # Enable VIA, if you're not gonna use it, set to 'no'
OLED_DRIVER_ENABLE  = yes # Enable OLED screens
LTO_ENABLE          = yes # Makes the firmware smaller, takes more time to compile
EXTRAKEY_ENABLE     = yes # Enables System and Media control keys
SPLIT_KEYBOARD 		= yes # You have a Corne, right?
WPM_ENABLE 			= yes # Enables the WPM (Words per minute) counter in the right OLED screen
TAP_DANCE_ENABLE    = yes```

**Comment by fauxpark** [comment]
If you're using RGBLight then this PR is not relevant.

**Comment by mtei** [comment]
> I lost my rgb when I applied this tag. Should I make any modifications to my keymap?? I'm using RGBLIGHTS not RGB MATRIX

This PR change should not affect keyboards / keymaps with `RGBLIGHT_ENABLE = yes` set.

Are your keyboards and keymaps registered in this repository?
If so, please tell me the keyboard name and keymap name. I will try it.

**Pull request merged**
