### PR TITLE
Translate more documents into Mandarin Chinese

### PR DESCRIPTION
**Pull request by ymzcdg**
## Description
Translate docs into Mandarin Chinese.I hope my work can help my compatriots.
I do this in my time after class , so it won't be fast.
add newbs_getting_started.md (20190426)
add newbs_building_firmware.md and newbs_flashing.md (20190427)

## Types of Changes
add translation:
newbs_getting_started.md
newbs_building_firmware.md
newbs_flashing.md

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mechmerlin** [comment]
Some of these look like they were already fixed in your previous PR. Could you perhaps update your master branch to align with QMK, and then create a new branch off of it and add the new changes there? 

If you keep making changes to your master branch you'll run into some painful git complications.

**Comment by drashna** [comment]
Specifically: 

You've opened this pull request from your fork's `master` branch. While this isn't a major issue now, later changes may result in merge conflicts if you try to file another PR because the commit history will have diverged between your master and QMK's. It is highly recommended for QMK development - regardless of what is being done or where - to keep your master updated, but **NEVER** commit to it. Instead, do all your changes in a branch (branches are basically free in Git) and issue PRs from your branches when you're developing.

There are instructions on how to keep your master updated here:

[**Best Practices: Your fork's master: Update Often, Commit Never**](https://docs.qmk.fm/#/newbs_best_practices?id=your-fork39s-master-update-often-commit-never)

If you need any help with this just ask.

You do not need to close this PR. Further changes should still be pushed to your master branch, until this PR is merged.

**Comment by ymzcdg** [comment]
When I translate the documant named newbs_best_practices.md I found I made a mistake.Sorry.

**Comment by ymzcdg** [comment]
Please merge this,then I will try to create my new branch.

**Pull request closed without merging**
