### PR TITLE
DeltaSplit75 Firmware

### PR DESCRIPTION
**Pull request by xyxjj**
pull request for the firmware for the DeltaSplit75

### CODE REVIEW

**Comment by jackhumbert** [comment]
Awesome! Would you mind moving the hardware files to a different repo, and linking it here? We're trying to avoid the QMK repo from becoming bogged-down with hardware stuff :)

**Comment by jackhumbert** [comment]
@xyxjj we'd be happy to merge this - just pinging you about removing the hardware files!

**Comment by xyxjj** [comment]
@jackhumbert i deleted the case files! forgive me but im not used to github so i had to delete each file one by one

**Comment by jackhumbert** [comment]
Cool! It looks like it's having trouble with the warnings - can you take a look at this when you have the chance? All warnings are treated as errors in the check, which is why it's failing.

```
Making DeltaSplit75/ProtoSplit with keymap Default                                                     [ERRORS]
keyboards/DeltaSplit75/keymaps/Default/keymap.c:21:105: error: macro "KEYMAP" passed 90 arguments, but takes just 88
   KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, MO(1), KC_SPC, KC_RALT, KC_RGUI, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT),
                                                                                                         ^
keyboards/DeltaSplit75/keymaps/Default/keymap.c:15:2: error: 'KEYMAP' undeclared here (not in a function)
  KEYMAP(
  ^
keyboards/DeltaSplit75/keymaps/Default/keymap.c:29:109: error: macro "KEYMAP" passed 90 arguments, but takes just 88
   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
                                                                                                             ^
 | 
 | 
 | 
make[1]: *** [.build/obj_DeltaSplit75_ProtoSplit_Default/keyboards/DeltaSplit75/keymaps/Default/keymap.o] Error 1
Making DeltaSplit75/ProtoSplit with keymap ProtoSplit                                                  [OK]
Making DeltaSplit75/V2 with keymap Default                                                             [OK]
Making DeltaSplit75/V2 with keymap ProtoSplit                                                          [ERRORS]
keyboards/DeltaSplit75/keymaps/ProtoSplit/keymap.c:21:105: error: macro "KEYMAP" requires 90 arguments, but only 88 given
   KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, MO(1), KC_SPC, KC_RALT, KC_RGUI, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT),
                                                                                                         ^
keyboards/DeltaSplit75/keymaps/ProtoSplit/keymap.c:15:2: error: 'KEYMAP' undeclared here (not in a function)
  KEYMAP(
  ^
keyboards/DeltaSplit75/keymaps/ProtoSplit/keymap.c:29:109: error: macro "KEYMAP" requires 90 arguments, but only 88 given
   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
                                                                                                             ^
 | 
 | 
 | 
make[1]: *** [.build/obj_DeltaSplit75_V2_ProtoSplit/keyboards/DeltaSplit75/keymaps/ProtoSplit/keymap.o] Error 1
```

It looks like you need to adjust the KEYMAP definition in your `keyboards/DeltaSplit75/ProtoSplit/ProtoSplit.h`.

We're also trying to standardise the keyboards so that they're all lowercase, and separated by `_` if needed (not sure if Delta Split is two words) - could you make those changes when you have the chance? Thanks!

**Comment by xyxjj** [comment]
the way i have this setup is like this:
I have 2 versions of the pcb, a prototype and a 2nd revision. THe 2nd revision has more keys so i had it made with the keymap: default, while the prototype with less keys is made with the keymap: ProtoSplit. I guess it sort of tried to make everything when in fact the keymaps are for a specific subproject, if that made any sense

**Comment by jackhumbert** [comment]
Cool! It might make sense to have a KEYMAP that leaves a couple spots blank then, to accommodate for your keyboard with more keys. As it is right now, it looks like it's actually erring at the number of arguments.

**Comment by xyxjj** [comment]
yea, because i organised it such that the protosplit subproject was meant to be run with the protosplit keymap which has the correct number of arguments, while the v2 subproject is meant to be run with the default keymap, but i think your method might be easier and more convenient

**Comment by jackhumbert** [comment]
This ended up getting included in #1518 - thanks!

**Pull request closed without merging**
