### PR TITLE
niu_mini uses dfu bootloader rather than the afrdude bootloader

### LINKED ISSUE #5835: Niu Mini uses dfu bootloader, the suggested command is wrong
[Here](https://github.com/qmk/qmk_firmware/tree/master/keyboards/niu_mini) it is suggested to flash the Niu Mini with
  
`make niu_mini:default:avrdude`

but it should say

`make niu_mini:default:dfu`

### PR DESCRIPTION
**Pull request by hadibus**
modified: readme.md

## Description
Small change to the readme. The afrdude bootloader doesn't work for the niu_mini. The dfu bootloader does work for the niu_mini.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

*  Fixes #5835 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes. **Not Applicable**
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Should the rules.mk also be updated from the older `OPT_DEFS += -DBOOTLOADER_SIZE=4096` to `BOOTLOADER = atmel-dfu`?

**Comment by drashna** [comment]
> Should the rules.mk also be updated from the older `OPT_DEFS += -DBOOTLOADER_SIZE=4096` to `BOOTLOADER = atmel-dfu`?

Yes, 100%.   @hadibus if you could update that too?

**Comment by hadibus** [comment]
Yes. I wonder if the comments above that line I changed in rules.mk should be updated as well. I'm new to this project.

**Comment by drashna** [comment]
Nah, they're fine.  

And they're documented, technically: https://docs.qmk.fm/#/config_options?id=avr-mcu-options

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
