### PR TITLE
Add helper macro for generating a transparent VIA layout.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

Got bored of watching @mechmerlin replicate layout macros. :)
Automatically inserts all positions in the electrical matrix with `KC_TRNS`.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Only concern is that entries that were previously `KC_NO` in the resulting array end up being `KC_TRNS`.

**Comment by fauxpark** [comment]
Will this work with CLI/API, `qmk info` etc.?

**Comment by tzarc** [comment]
```c
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /* Base */
    [0] = LAYOUT_ortho_5x4(
        KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
        KC_P7,   KC_P8,   KC_P9,   KC_PPLS,
        KC_P4,   KC_P5,   KC_P6,   KC_PEQL,
        KC_P1,   KC_P2,   KC_P3,   KC_PENT,
        KC_P0,   KC_P0,   KC_PDOT, KC_PENT
    ),
    [1] = LAYOUT_via_transparent(),
    [2] = LAYOUT_via_transparent(),
    [3] = LAYOUT_via_transparent(),
};
```
image

**Comment by fauxpark** [comment]
I'm just thinking further ahead here - how will it work with keymaps in JSON?

**Pull request closed without merging**
