### PR TITLE
Keymap: Miryoku for Gergo

### PR DESCRIPTION
**Pull request by jdayton3**
## Description

Add the Miryoku layout for the Gergo keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by jdayton3** [comment]
@drashna Removed it. Thanks for doing your part to keep the repo squeaky clean!

@manna-harbour Thought you might want to have a chance to look this over too.

**Comment by manna-harbour** [comment]
Thanks for adding gergo to miryoku!

However, there are some issues with this PR:

- The implementation has just changed from including the .c file to building a separate object containing the keymap, so this PR won't be compatible after #9442 is merged.
- All of the miryoku files in QMK are generated from miryoku.org, so new keyboards need to be added there.
- In general, you probably don't want to add new user-named directories `{keyboards/*/keymaps/*/, layouts/community/*/*/,users/*/}` to QMK for someone else's username.
- You don't need IGNORE_MOD_TAP_INTERRUPT in config.h as it's already in the userspace config.h.

But all this is easily taken care of.

I'm happy to add new keyboards and layouts by request, and I have a testing branch so they can be verified as I can't check them myself. I've just added [gergo](https://github.com/manna-harbour/qmk_firmware/tree/miryoku-testing/keyboards/gergo/keymaps/manna-harbour_miryoku).  Please check if ti's ok and I'll make a PR.

If you'd like your own gergo miryoku keymap, you can add that using your own username the same way it's done with [my crkbd keymap](https://github.com/manna-harbour/qmk_firmware/blob/crkbd/keyboards/crkbd/keymaps/manna-harbour/).  You need rules.mk containing only `USER_NAME := manna-harbour_miryoku`, config.h containing only the LAYOUT_miryoku macro, and an empty keymap.c.  You can add extra customisations to keymap.c as usual, and you could add your own keycodes to the unused keys in LAYOUT_miryoku if you have a use for them.

**Comment by jdayton3** [comment]
@manna-harbour Thanks for the feedback! Glad I reached out. I'll change those things.

Regarding the website, how do I use it? When I go to miryoku.org, I see this:

image

I only speak English, and I'm not sure where to go from there.

**Comment by manna-harbour** [comment]
Sorry, that's an unfortunate coincidence! I meant [qmk_firmware/blob/miryoku/users/manna-harbour_miryoku/miryoku.org](https://github.com/manna-harbour/qmk_firmware/blob/miryoku/users/manna-harbour_miryoku/miryoku.org).

I've already [added it](https://github.com/manna-harbour/qmk_firmware/commit/9d57bf9e9185c1989ac40fb4ef7e2825f7ba85a0) to the testing branch, so you only need to test it.

**Comment by jdayton3** [comment]
Great, thanks! I'm busy trying to get GB stuff out for the next few days, but I'll take a look and change things next week!

...Incidentally, if you have any idea why [this keymap](https://github.com/jdayton3/qmk_firmware/tree/for_science/keyboards/for_science) isn't working, I'm all ears 😬😀

**Comment by manna-harbour** [comment]
> Great, thanks! I'm busy trying to get GB stuff out for the next few days, but I'll take a look and change things next week!

No worries.  Good luck with the GB!

> ...Incidentally, if you have any idea why [this keymap](https://github.com/jdayton3/qmk_firmware/tree/for_science/keyboards/for_science) isn't working, I'm all ears

It builds ok.  What's the problem?  Is it just that keymap that has issues or the whole keyboard?

**Comment by manna-harbour** [comment]
@noroadsleft
> The `config.h` and `keymap.c` files need license headers, but that's all IMO.

Actually, this PR can just be closed.  See [this earlier comment](https://github.com/qmk/qmk_firmware/pull/9441#issuecomment-646415361).

**Comment by noroadsleft** [comment]
@manna-harbour,

Thank you for saving me from myself.

Closing per request; the feature is already implemented.

**Pull request closed without merging**
