### PR TITLE
Fix conflicting types for 'tfp_printf'

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Pulling out the discussion within https://github.com/qmk/qmk_firmware/pull/8157#discussion_r378622398 for a longer term fix for #8157.

https://github.com/mpaland/printf ticks the following boxes:
* drop in replacement to existing solution
* non void functions
* binary printing support

seems to work fine with brief testing but it does increase ChibiOS based firmware by 750 bytes.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
The only concern I have is if the MIT license is compatible.

**Comment by Boettner-eric** [comment]
I am having this issue right now on my proton c hardwired build and this branch does fix it

**Comment by drashna** [comment]
@Boettner-eric would you be opposed to approving the PR?  Even if you're not a collaborator, you can do so.  It just won't show it in green.

**Comment by tzarc** [comment]
I personally wouldn't have an issue removing the "breaking_change" label and getting this in to master.
Are there any real reasons to do so, other than the worry of the +750 bytes of flash? Are we close to the limit with any of the ARM builds, even customised keymaps?

**Comment by zvecr** [comment]
As it missed acceptance window for the last breaking change, and adds a new submodule, i figured it would need to go via the next window.

As for the size increase, the merge of nano specs means we would be no worse with this in than we were a few days ago. Personally I think the +750 bytes would be fine, but dont have the metrics to see how it really impacts the end user.

**Comment by tzarc** [comment]
Given that it's a new repo as opposed to a replacement of an existing directory with an equivalent submodule (lufa), I'd be more inclined to say "breaking changes not required". I don't reall mind though, just figure that having this sitting on a branch and waiting for a few months, there's the possibility of divergence for people who try to apply the fix in their own branch to fix their boards.

**Comment by noroadsleft** [comment]
Thanks!

**Comment by fauxpark** [comment]
This should have been merged into future; Configurator is now broken for ARM boards with Console enabled.

**Comment by skullydazed** [comment]
Note: this was manually cherry-picked to `future` and reverted from `master`.

**Pull request merged**
