### PR TITLE
S65x fixes

### PR DESCRIPTION
**Pull request by geofflane**
Post build testing found some problems and fixed. Fix Esc key and left shift in the ANSI layout. Use standard QMK features for RGB and LED control.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Great! Thanks :)

**Comment by bolensmichael** [comment]
@geofflane this breaks Ctrl+Shift+Esc Windows combo, any recommendations on how to keep that working and keep the Shit+Esc working? I was actually working to finalize my layout and was gonna do a pull req for the properly working config, etc but you beat me to it!

**Comment by geofflane** [comment]
@bolensmichael I'm not totally sure, a bunch of the keymaps implement that shift-esc behavior and I blatantly copied from them. :)

```
shift_esc_shift_mask = get_mods()&MODS_CTRL_MASK;
...
if (shift_esc_shift_mask) {
...
```
The above is a bitmask, so I assume you could also detect whether ctrl is pressed as well. Something like: `& ~MOD_BIT(KC_LCTRL)` ?

**Comment by geofflane** [comment]
@bolensmichael Someone literally just added that functionality to the base quantum code today. So I assume it would have the problem you mention, you might want to test it there? You can see it at #1391

**Comment by bolensmichael** [comment]
Oh awesome I hadn't seen that! I am happy to test that out I appreciate you sending the link!

**Pull request merged**
