### PR TITLE
Unicode, Unicodemap and UCIS refactor

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

- Fixed a small bug with test matching due to how `findstring` works (eg. `make test:unicode` builds every test suite starting with `unicode` instead of just the one named `unicode`)
- Fixed typo in legacy keycode
- Moved lots of Unicodemap and UCIS-related code out of `process_keycode` to their own compilation units
- Somewhat reworked and simplified UCIS, now it does not backspace unless it matched a mnemonic, otherwise does nothing
- Added doc comments for nearly everything
- Added a bunch of tests across the whole Unicode feature set
- Rewrote docs page and added API reference

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by thpoll83** [comment]
Hi @drashna 
I did test that branch and on Linux I could not get reliable unicode characters (both uppercase and lowercase). Here a sequence of unicode characters:
`äää00e4 äää00e4 00e4 ääää00e4 00e4 00e4 00e4 00e4 00e4 00e4 00e4 00e4 ä00e4 00df 00df 00df 00f6 00fc 00fc 00fc 00fc 00c4 1e9e 00c4 1e9e 00c4 1e9e 00c4 ẞ00c4 1e9e 00c4 1e9e 00c4 ẞ1e9e 1e9e 00c4 ẞÜ00d6 00dc 00d6 00dc Ö`
Sometimes they are translated, other times not. Can anyone reproduce that?

**Comment by fauxpark** [comment]
Decided to remove the AutoHotkey/US Intl/xkbmap section of the docs, as it's *kinda* out of scope here. I can still see the value in this information though but I don't really know where to put it.

**Comment by vomindoraan** [comment]
This PR appears to have introduced an issue with userspace code due to the newly-added file `unicode.h` being called that. Several userspaces (prior to their removal from the main repo) contained files named `unicode.h`:

```
konstantin@const-debian ~/projects/qmk_firmware (user-keymaps-still-present)
$ find -name unicode.h
./users/drashna/keyrecords/unicode.h
./users/kuchosauronad0/unicode.h
./users/rmeli/keyrecords/unicode.h
./users/yet-another-developer/unicode.h
./users/rverst/unicode.h
./users/ridingqwerty/unicode.h
./users/ericgebhart/extensions/unicode.h
./users/rupa/unicode.h
./quantum/unicode/unicode.h
```

What happens is that `quantum/keyboard.c` (among other files) [tries including `unicode.h`](
https://github.com/qmk/qmk_firmware/blob/master/quantum/keyboard.c#L134-L136), which is intended to be `quantum/unicode/unicode.h`, but it ends up including the userspace file instead due to the include order. This results in the following build error:

```
$ make kbdfans/kbd6x:konstantin
QMK Firmware user-keymaps-still-present
Making kbdfans/kbd6x with keymap konstantin

[...]
Compiling: quantum/keyboard.c                                                                      quantum/keyboard.c: In function ‘quantum_init’:
quantum/keyboard.c:396:5: error: implicit declaration of function ‘unicode_input_mode_init’ [-Werror=implicit-function-declaration]
     unicode_input_mode_init();
     ^
[...]
```

Here's an example from another user's userspace (@ridingqwerty):

```
$ make handwired/minorca:ridingqwerty
QMK Firmware user-keymaps-still-present
Making handwired/minorca with keymap ridingqwerty

[...]
Compiling: users/ridingqwerty/ridingqwerty.c
            users/ridingqwerty/ridingqwerty.c: In function ‘matrix_init_user’:
users/ridingqwerty/ridingqwerty.c:10:5: error: implicit declaration of function ‘set_unicode_input_mode’ [-Werror=implicit-function-declaration]
     set_unicode_input_mode(UNICODE_MODE_LINUX);
     ^
users/ridingqwerty/ridingqwerty.c:10:28: error: ‘UNICODE_MODE_LINUX’ undeclared (first use in this function)
     set_unicode_input_mode(UNICODE_MODE_LINUX);
                            ^
[...]
```

I haven't yet fully ported my userspace to the new external repo structure, so I haven't been able to test if the error still happens when compiling with `user.overlay_dir`, but I suspect it might. If indeed it does, I'll open an issue. For the time being, I'll just rename my files to `unicode_user.{c,h}` as a workaround.

A possible solution is to rename `quantum/unicode/unicode.{c,h}` to `quantum/unicode/unicode_common.{c,h}`. I also feel that name would be more suitable, given the presence of `UNICODE_COMMON`, `UNICODE_COMMON_ENABLE`, `quantum/process_keycode/process_unicode_common.{c,h}` etc.

**Comment by fauxpark** [comment]
`unicode` is far too generic of a name for user code to be using. The correct solution is for the user to rename their files to something else.

**Pull request merged**
