### PR TITLE
Added the keymap I have been using as a daily driver for the last month

### PR DESCRIPTION
**Pull request by era1112**
Adding the keymap I use as a daily driver for a community contribution.

This is being done since it was recommended in the guide at https://github.com/qmk/qmk_firmware/blob/master/docs/getting_started_github.md

## Description

Added a keymap for a preonic rev3_drop, at /keyboards/preonic/keymaps/Era1112

## Types of Changes
This keymap includes, and is a good source of code snippets for:
- doubletap tapdance for caps lock
- rotary encoder
- macro record/playback
- light on/off
- sound on/off
- blink-on-keypress w/ on/off keystroke
- beep-on-keypress w/ on/off keystroke (althought this has runtime stability issues when typing fast, still trying to remediate)

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — CHANGES_REQUESTED** [review]
Please rename the keymap folder to be all lower case.

**Comment by Era1112** [comment]
> Please rename the keymap folder to be all lower case.

Changes made in latest commit (https://github.com/qmk/qmk_firmware/pull/16064/commits/ab258f717ee978a6063ca8b171e56937048c5987)

**Review by drashna — APPROVED** [review]

**Review by noroadsleft — APPROVED** [review]
Looks good to me.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
