### PR TITLE
Add YMD96 Keyboard

### PR DESCRIPTION
**Pull request by sparkyman215**
Uses ps2avrgb base

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! Would you mind updating the readme.md to [this format](https://docs.qmk.fm/documentation_templates.html#keyboard-readmemd-template)?

**Comment by sparkyman215** [comment]
How's it look now?

**Comment by jackhumbert** [comment]
The Keyboard Maintainer, Hardware Supported, and Hardware Availability are needed as well :) any extra info should go after the block linked.  The ps2avrgb's original readme isn't yet compliant with this yet either - please ignore that!

**Comment by sparkyman215** [comment]
Sorry, this is my first pull req :)

**Comment by jackhumbert** [comment]
Great! Thanks :)

**Comment by AnthonyWharton** [comment]
Probably not the most productive comment, but I've just finished building this keyboard literally within the last 30 minutes, and in-between the time of me cloning the `qmk_firmware` repo and starting to read the documentation, I noticed this was merged in!

So because of crazy coincidence have an internet high five for good timing! :+1:

**Comment by sparkyman215** [comment]
Haha no way! I hope you get qmk up and running - if you have any issues feel free to message me :)

**Comment by AnthonyWharton** [comment]
It's been all alright so far, apart from it looks like I might have a dodgy Row 7 (Num Lock, Pad7, Pad4, Pad1, LeftArrow etc).. Anywhere I can message you that isn't here so we don't clutter up this issue? If not I have an attached email address to my github profile - thanks!

**Comment by sparkyman215** [comment]
I'd prefer using discord: sparky#7586

**Pull request merged**
