### PR TITLE
X-Macros for keycode definitions.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

Converts keycode generation to X-Macros. Useful for conversion to text-equivalents.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Random selection of 100 boards show SHA1s match.

**Review by fauxpark — COMMENTED** [review]
`X()` is already used by Unicodemap (for now)... and I feel like this is overcomplicating things a little.

**Comment by zvecr** [comment]
I share similar concerns, could we not just generate a different header from the cli? I guess that would be my preference.

**Comment by fauxpark** [comment]
As of #21092 `X()` is now free to use.

There's also the sendstring keycodes which use an `X_` prefix but it doesn't affect this PR as much, and I'm not sure what to do about those yet - things like `X_LCTL` -> `SS_LCTL` vs the existing `SS_LCTL()`.

**Comment by tzarc** [comment]
No probs, will move further discussion to Discord.

**Pull request closed without merging**
