### PR TITLE
added keymap for Preonic called johns_preonic

### PR DESCRIPTION
**Pull request by JHGarrett**
## Description

I added a new keymap layout for the Preonic keyboard. In the folder johns_preonic there are 4 new files. They include config.h, keymap.c, rules.mk, and a readme detailing the new layers. The code compiles without issue and I am personally using the keymap. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by JHGarrett** [comment]
sorry for the crappy commit messages. I had no intention when I started making this layout to make a pull request. Thanks!

**Comment by drashna** [comment]
There are a lot of changes from other commits here, and this is a mess.

It may be simplest to copy your keymap to a different location, reset your repo, and then copy your files back, and commit them, so you can "start clean".  

None of this requires closing the PR, but the link above may help you out with it.

**Comment by zvecr** [comment]
As a passing comment, on the keymap name "johns_preonic" and the "john" ctrl keymap within the changes of this PR. The keymap being in the preonic directory could be enough context to drop the `_preonic` part. You might also consider using your GitHub username to avoid potential future conflicts, if another John adds a keymap to one of your future keyboard purchases.

**Comment by noroadsleft** [comment]
On :point_up_2: note, I'd highly recommend using `jhgarrett` as your keymap name.

**Pull request closed without merging**
