### PR TITLE
Dilly: Refactor and Configurator support

### PR DESCRIPTION
**Pull request by noroadsleft**
# Refactor

- Matrices
  - `KEYMAP` renamed to `LAYOUT`
  - `KC_KEYMAP` renamed to `LAYOUT_kc`
- Keymaps
  - now use `#include QMK_KEYBOARD_H`
  - default keymap refactored to use `LAYOUT` matrix rather than `LAYOUT_kc`
  - default keymap modified for readability

# Configurator

- added `info.json`

### CODE REVIEW

**Comment by drashna** [comment]
This and the Gherkin should probably be ortho 3x10 layouts.

**Comment by noroadsleft** [comment]
Is the objective with `layouts/default/` and `layouts/community/` to have every keyboard be able to use as many keymaps in the repo as are valid for it? I want to know if I should just make these changes as part of my standard workflow.

**Comment by drashna** [comment]
yes, basically.   Or at least for the ones that are very common.  
`The layouts/ folder contains different physical key layouts that can apply to different keyboards.`

So, if we have several boards that use the same layout... we should support it.

**Comment by drashna** [comment]
And thanks!

**Comment by noroadsleft** [comment]
I'd argue 3x10 ortho isn't very common at this point, but whatever. It's not that much extra work.

**Pull request merged**
