### PR TITLE
SK75

### PR DESCRIPTION
**Pull request by LiuLiuQMK**
Added Three-mode keyboard Womier/SK75.

## Description

Added Womier/SK75 mechanical keyboard
Submit wireless code and keyboard code
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by LiuLiuQMK** [comment]
hello, my wireless code is implemented in the womier/common file, please help me check. If my code does not meet the QMK specification, please give me your opinion, I will deal with it immediately and modify it.

**Comment by waffle87** [comment]
Right now, all you can do is sit and wait. As per the "needs-core-wireless" label that was added, any wireless keyboard PRs are going to be on hold until there is core-wireless support. It is not feasible to maintain multiple keyboard-level wireless implementations.

**Comment by kerlos** [comment]
> Right now, all you can do is sit and wait. As per the "needs-core-wireless" label that was added, any wireless keyboard PRs are going to be on hold until there is core-wireless support. It is not feasible to maintain multiple keyboard-level wireless implementations.

If my keyboard uses the Westberry trimode with the unified wireless source code located in /keyboards/westberry/wireless, would it count as core wireless since multiple keyboards from this vendor can use this code?

here the code from westberry repo
[Westberry core wireless](https://github.com/WestberryTech/qmk_westberry/tree/tri-mode/keyboards/westberry/wireless)

**Comment by tzarc** [comment]
It’s not core, no. There are wireless APIs in the works and trimode keyboards won’t be merged until after they’re adapted to use it. You can do whatever you like with their code, but it won’t be merged into QMK upstream in its current form.

**Comment by LiuLiuQMK** [comment]
Ok, continue to upload the code without wireless function

**Comment by adophoxia** [comment]
> Ok, continue to upload the code without wireless function

That is not going to work out for you because according to the GPL license, all aspects of the source code for the firmware, including the wireless code, must be available. If you were to remove said code, you'd be in violation of that license.

**Comment by LiuLiuQMK** [comment]
You misunderstand my meaning, now the wireless core can not be merged, I will remove the wireless function of my keyboard, only upload the wired version that meets the current requirements, and I will put the wireless version into my personal firmware, because my idea is that I want to do the keyboard can be merged, that's all.

**Comment by tzarc** [comment]
Still won't work.

As per the PR checklist:

---

Wireless-capable boards:
- Given license abuse from vendors, QMK does not accept any vendor PRs for wireless- or Bluetooth-capable keyboards without wireless and/or Bluetooth code
    - Historically, vendors have done this in bad faith in order to attain downstream VIA compatibility with no intention of releasing wireless sources
    - QMK's license, the GPL2+, requires full source disclosure for any distributed binary -- including full sources for any keyboard shipped by vendors containing QMK and/or firmware-side VIA code
    - If a vendor's wireless-capable keyboard PR submission is lacking wireless capability, then the PR will be left on-hold and unmergeable until wireless bindings are provided
    - If a vendor's wireless-capable keyboard is merged into QMK before it's known that the board is wireless, then all existing and future PRs from the same vendor will be put on hold until wireless bindings for the offending keyboard are provided

**Pull request closed without merging**
