### PR TITLE
(Owlet60) Added 60% layouts, fixed JSON file since previous JSON didn't match the Matrix. Added 60% layouts to JSON file

### PR DESCRIPTION
**Pull request by worthlessowl**
## Description

I added 60% layouts to owlet60.h. I also fixed the JSON file. The previous one have the keys all over the place, since i didn't match the order of the keys with my matrix. I also added 60% layout in the configurator JSON file.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
For future reference, we recommend against making changes to your master branch, because of the potential for merge conflicts (artifacts of which I can see in this pull request). It is highly recommended for QMK development - regardless of what is being done or where - to keep your master updated, but **NEVER** commit to it. Instead, do all your changes in a branch (branches are basically free in Git) and issue PRs from your branches when you're developing.

There are instructions on how to keep your master updated here:

[**Best Practices: Your fork's master: Update Often, Commit Never**](https://docs.qmk.fm/#/newbs_best_practices?id=your-fork39s-master-update-often-commit-never)

If you need any help with this just ask.

I'm going to pull down your branch in a moment and I'll see about walking you through cleaning this up. Sit tight.

**Comment by noroadsleft** [comment]
Okay, to get this cleaned up, the first thing we need is to make sure you have a branch that's identical to QMK's current `master` branch. Since you've already made changes to your own master, we want to duplicate the current state of your `master` branch. The best way to do this is to just create a new branch based on the current state. To do this: run `git checkout -b old_master`. Now you have a branch named `old_master` that's the same as your `master` branch, and the current branch is `old_master`.

To easily grab changes from QMK's repository here on GitHub, you want to add QMK's repository as an "upstream" repository. To check your currently configured repositories, run `git remote -v`. This will probably return something similar to:

```sh
$ git remote -v
upstream        https://github.com/worthlessowl/qmk_firmware.git (fetch)
upstream        https://github.com/worthlessowl/qmk_firmware.git (push)
```

To add QMK's repository, run `git remote add QMK https://github.com/qmk/qmk_firmware.git`. This will add QMK's repository under the alias `QMK` (like everything in Git, this is **case-sensitive**).

Now we need to restore your local repository so that it matches QMK's, which takes a couple of steps. First, check out your `master` branch with `git checkout master`. From here we'll then restore the local `master` branch to match the state of QMK's `master` branch. Run, in order:

```sh
git fetch QMK master
git reset --hard QMK/master
```

The first command fetches the references or "refs" that make up the repository and branch. Refs are basically anything related to version tracking in Git. The most common type of ref is the *commit*, but there are also *tags*, *branches*, and *stashes*. Fetching the refs basically tells Git to keep track of all the changes that have been made on QMK's `master` branch.

`git reset --hard` here tells Git "Rewrite my current branch's files so all of them match the state of the `master` branch of the repository `QMK`, discarding any changes I have saved locally." This will erase all the changes you have made to your `master` branch, but your changes aren't gone – they're just in the `old_master` branch now, in case we need them.

At this point, you have two choices: you can attempt to apply the changes you wish to make to your now-synchronized `master` branch. To find your "discarded" commits, run:

```sh
git log --oneline -40 master^..old_master
```

which tells Git "List the last 40 commits that are on the `old_master` branch but *not* on the `master` branch, one line per commit." When you have the commit hashes you want, you can apply them with something like 

```sh
git cherry-pick fc295c1f7
```

If you want to cherry-pick multiple commits, you can include them in the sequence you want, separated by spaces.

Or, you can just start from "scratch" with your normal cycle of editing your files, then running `git add` and `git commit`.

When you get your changes applied to your clean `master` branch, use `git push --force upstream master` to send those changes to your `master` branch on GitHub. `git push --force` is basically the equivalent of `git reset --hard` for your GitHub-hosted fork. Be advised that you should only use the `--force` argument on a branch where you are the only user making changes. It should be safe to use for your fork, but *never* use this with a shared repository.

**Comment by worthlessowl** [comment]
Hi @noroadsleft . Thank you for pointing this mistake out. And thank you for your help guiding me through this. I've followed your instructions, I've made a new branch named old_master, and reset my fork's master to QMK's current state. I still have some things I don't understand though. 

- From what I read from the QMK Best Practices docs, we should keep our fork's master clean. We pull from master often, but don't commit to it at all. When we want to make changes, we create a new branch in our fork, and push all the changes to the branch. We also make new Pull Requests from our branch. Is that correct? Do we need to create a new branch every time we make new changes to our code?

- I still don't understand the `cherry-pick` command you showed me. So we don't actually commit to our master, but we create changes on our branch. Once we're satisfied with our changes, we apply that changes to the clean master with the `cherry-pick command`, and push it to our online fork's master with `git push --force upstream master`. So do we make PR from our master?

- And lastly, my latest commit contains some merge artifacts, so should I go back to the previous commit which didn't contain the artifacts before making a PR?

I'm sorry for this inconvenience. This is the first time I've contributed to a Github project. There are still some confusion I have. Thank you so much for helping me. If there's anything else I need to do, please tell me. I would probably need to close this PR and make a new one with the correct way right?

**Comment by noroadsleft** [comment]
> From what I read from the QMK Best Practices docs, we should keep our fork's master clean. We pull from master often, but don't commit to it at all. When we want to make changes, we create a new branch in our fork, and push all the changes to the branch. We also make new Pull Requests from our branch. Is that correct? Do we need to create a new branch every time we make new changes to our code?

Admittedly, I wrote this from the perspective of changes in different areas of code (something here, something there, something else over there, etc.) because that's my workflow with QMK generally – a lot of similar change sets for different keyboards (I specialize in QMK Configurator implementations). Thank you for pointing out an omission in that guide.

The "new branch for each pull request" probably isn't appropriate for a user who's developing for specific keyboard(s), as you are. A new branch for each change set does make the pull requests easier on our end, because it reduces the "noise." This probably isn't strictly necessary for your use case; I'll need to do some thinking on rewriting that part of the guide.


> I still don't understand the `cherry-pick` command you showed me. So we don't actually commit to our master, but we create changes on our branch. Once we're satisfied with our changes, we apply that changes to the clean master with the `cherry-pick command`, and push it to our online fork's master with `git push --force upstream master`. So do we make PR from our master?

Another failure on my part. `git cherry-pick` is basically "Take the changes from this commit/these commits, and apply them here." Git will edit the files as needed, and automatically commit, using the message you wrote on the original commit (but the cherry-picked commits will have different hashes). Git will notify you if there's a merge conflict.

I told you to cherry-pick to the `master` branch, because it's the one from which you opened this pull request. Once a pull request is opened, you can change the destination branch (I could edit this pull request to put its changes in a different branch on QMK's end, for instance), but you can't change the source branch, which means this pull request only cares about what happens on your `master` branch. Since we do care about these changes, keeping them in the master branch for the purposes of this pull request makes sense. After this PR is merged, you will need to use the `git reset --hard` on your master branch again to resync it. Before doing that though, you can create another new branch (`old_master2` or whatever) if you choose. Once your master is synchronized, you can use the "branch per change set" method, if it suits your workflow. (And if it doesn't, I'll gladly take suggestions of how to edit that recommendation for the guide!)


> And lastly, my latest commit contains some merge artifacts, so should I go back to the previous commit which didn't contain the artifacts before making a PR?

The merge artifacts do need to be cleaned up, because they'll affect what happens if a user attempts to compile your keyboard. It may lead to a situation where *you* can compile it, but no one else can.

I still have your branch pulled down to my computer (as a branch separate from my own `master`). I actually tried to clean it up on my end to walk you through specifically fixing this branch and PR, but I couldn't quite make sense of the merge conflicts, because I actually had two that happened in the same place and were overlapping each other (one merge conflict that contained a second merge conflict), which is a situation I've never encountered before. I likely will take another shot at fixing it on my end so I can instruct you step-by-step how to proceed.


> I'm sorry for this inconvenience. This is the first time I've contributed to a Github project. There are still some confusion I have. Thank you so much for helping me. If there's anything else I need to do, please tell me. I would probably need to close this PR and make a new one with the correct way right?

No need to apologize; everyone is new at some point.

If we can get your master branch cleaned up, you don't need a new PR. I intend to leave this open until either we merge it, or determine we just can't get where we need to go and that you need to start over.

**Comment by noroadsleft** [comment]
Took another look at your changes.

Take a look at this and let me know if it looks good. https://github.com/noroadsleft/qmk_firmware/compare/60cd12f8a4ac82b1dcb2c8ec0f0231c2004507ce...962aa1df653f0499ad7b176cd5f2150ce524c98a

Note that this partially reverses the changes you made to `info.json`. The objects in the `layout` key need to be in the order that `keymap.c` would use, rather than in order of the electrical matrix. Basically, it should match this order:

```
#define LAYOUT_owlet60_split_bsp( \
    k50, k00, k01, k02, k03, k04, k05, k06, k07, k08, k09, k0a, k0b, k0c, k0d, k0e, k0f, \
    k51, k10, k11, k12, k13, k14, k15, k16, k17, k18, k19, k1a, k1b, k1c, k1d,      k1e, \
    k52, k20, k21, k22, k23, k24, k25, k26, k27, k28, k29, k2a, k2b, k2c,           k2d, \
         k30, k31, k32, k33, k34, k35, k36, k37, k38, k39, k3a, k3b, k3c, k3d,      k3e, \
         k40,      k41,      k42, k43, k44,           k45,          k46,  k47,      k48 \
) { \
```

If that looks good, I can walk you through fixing your PR.

**Comment by worthlessowl** [comment]
Hi @noroadsleft , sorry for the slow progress. I had some university coursework that i need to finish first.  Thank you so much for answering all my questions in detail! Your answer clears up all my confusion from earlier. I'll be sure to send you my suggestions if I have one!

About the merge artifacts, drashna showed me how to solve them on my previous PR. I need to `checkout` every keyboards which had merge artifacts in it to qmk/master, and it worked well on my previous PR.

Your changes looks perfect! Just the way I meant it to be. I changed the json file order because on my first PR I had the order just like the one you have right now, but it was messed up when I flashed it to my board, so I thought that it might be linked to the physical matrix of my keyboard. But now that I think about it, it's probably because I put a wrong number to the key_count on my json file.

And, in the confusion of juggling several tasks at once, I managed mess up and make several commits myself when you already tried to help me fix my PR. I'm sorry if that makes things more complicated again. I'll redo the steps you gave me if I need to start from where we left before. 

I tried to fix some stuff, but I think I didn't do it correctly. I finished your guide last time with a clean qmk master on my local machine, but I think I haven't pushed it to my remote repo. So today I made changes to my local clean master, then tried to push it to my remote, but my remote still have changes from my previous commits and was in front of my local repo by several commits, it wasn't affected by the local fetch I did last time. So I pulled from my remote master, and I tried to push again. There was some files that needed to be merged before I could push, but I messed them up and managed to resolve the merge without resolving anything. Now I have a some codes with both incoming and current changes still in it. It was too messy for me so I decided to revert the merge. It all looks fine now, but I have my suspicion that I still have some merge artifacts in my master branch right.

I think I'll stop experimenting for now and follow your guidance until I get a better grasp of what went wrong with my codes.

**Comment by worthlessowl** [comment]
I've tried to fix things again while waiting for the review since I have a bit of free time. I hope everything is fixed now. I don't see any merge artifacts in the "files changed" tab. I assume this is all good?

**Comment by noroadsleft** [comment]
> I've tried to fix things again while waiting for the review since I have a bit of free time. I hope everything is fixed now. I don't see any merge artifacts in the "files changed" tab. I assume this is all good?

Sadly, this isn't really reviewable. You've done a bunch of changes that are "merge this branch into this other branch," and it's messed with the history of the files and your pull request is showing you have edited 290 files, which are all over the repository.

I've attempted to pull only your Owlet60 changes into a clean branch. If [these changes look okay](https://github.com/qmk/qmk_firmware/compare/master...noroadsleft:worthlessowl_owlet60_updates), I'll PR this branch instead and we can close this pull request (but you'll still get your changes in!).

**Comment by worthlessowl** [comment]
> Sadly, this isn't really reviewable. You've done a bunch of changes that are "merge this branch into this other branch," and it's messed with the history of the files and your pull request is showing you have edited 290 files, which are all over the repository.
> 
> I've attempted to pull only your Owlet60 changes into a clean branch. If [these changes look okay](https://github.com/qmk/qmk_firmware/compare/master...noroadsleft:worthlessowl_owlet60_updates), I'll PR this branch instead and we can close this pull request (but you'll still get your changes in!).

Hi @noroadsleft, everything on your clean branch looks good! Thank you so much for helping me out with this. I'm all in with PR-ing your branch.

I'm really sorry about my messy work. I'll do everything slowly and try to follow the guide as closely as I can next time. Do you have any critics or suggestions for me based on my work? Like what I'm supposed to do, what I did wrong this time, or anything else. I've read your review up for my PR above, but maybe there's still some point I can fix. I want to make sure my next PR goes as smoothly as possible. Thank you so much once again for helping me out!

**Comment by noroadsleft** [comment]
Superseded by #7103.

**Comment by noroadsleft** [comment]
> I'm really sorry about my messy work. I'll do everything slowly and try to follow the guide as closely as I can next time. Do you have any critics or suggestions for me based on my work? Like what I'm supposed to do, what I did wrong this time, or anything else. I've read your review up for my PR above, but maybe there's still some point I can fix. I want to make sure my next PR goes as smoothly as possible. Thank you so much once again for helping me out!

Looking through the history of your `master` branch, it seems that you were trying to re-synchronize your branch by pulling QMK's `master` branch into yours after you had already made commits to your `master` branch. When this happens, Git can't apply the original commits, and instead applies *merge commits*, which will have the changes made by the original commits – the ones being `git pull`ed – but with different commit hashes. Because the commit hashes change, your branch (and thus your pull request) has extra commits in it that weren't made by you, and it sends your branch out of sync, even though the contents of the files are the same. I used to run into this when I started with QMK. I started out doing the same thing as you did here – committing to `master` instead of using a branch. I'd make my commit, open a pull request, and then when it got merged, I'd pull QMK's master into my master, but it would leave me in a situation where my master branch would say "This branch is 1 commit ahead of qmk:master" even though there weren't any differences in file contents between the two branches.

The best way I can think to manage something like this in future involves the following:

## 1. Keep your `master` branch updated, but don't commit to it

Detailed in the doc I linked you before: 

- [**Best Practices: Your fork's master: Update Often, Commit Never**](https://docs.qmk.fm/#/newbs_best_practices?id=your-fork39s-master-update-often-commit-never)

## 2. Start your development branches from a current and clean `master` branch

Doing this helps ensure that your starting point is from a working copy of QMK, and that your changes will compile and function as intended.

Along those same lines is:

## 3. Rebase your development branch before opening your pull request

Now, this doesn't always matter. A small change to one file – especially something like documentation – isn't likely to break if QMK's `master` branch updates before your pull request is merged, but if you've made extensive changes and are ready to open a pull request, it's a good idea to rebase your development branch onto a current QMK master and test them to make sure that changes to QMK haven't broken your changes.

I explained `git cherry-pick` before. `git rebase` is basically the inverse of that. Instead of applying changes made elsewhere on top of your current branch and commit, `rebase` takes the changes applied to your current branch and applies them somewhere else. Let me give you an example.

As I write this, the current commit hash of QMK's `master` branch is 97b8ade. But let's say that I had started development on a change, and at that time the commit hash was a41066b. Now my branch and QMK's `master` have diverged – I have changes that aren't in QMK, and QMK has changes I don't have, so the history of the two looks like this:

```
                             noroadsleft:develop
                                      ↓
        G-----H-----I-----J-----K-----L
       /
o-----A-----B-----C-----D-----E-----F
      ↑                             ↑
   a41066b                       97b8ade
                               (qmk:master)
```

From my `develop` branch, I can run `git rebase 97b8ade`, and the history changes from the above, to:

```
                                                           noroadsleft:develop
                                                                    ↓
                                      G'----H'----I'----J'----K'----L'
                                     /
o-----A-----B-----C-----D-----E-----F
      ↑                             ↑
   a41066b                       97b8ade
                               (qmk:master)
```

... so now it's as if I started from QMK's current master, instead of the commit that *was* QMK's `master` at the time. If you run into merge conflicts on this step, it means a file that you've edited on your development branch was edited in the same place in QMK's `master` between when you started your branch and now, and Git can't work out how to apply your changes. If you solve them in this step before opening your pull request, on our end of the PR, it will be like the merge conflict never happened and your history will still be clean.

## 4. Re-synchronize your branches after you have a pull request merged

This is related to Point 2 above. You can re-sync your `master` branch when your PR is merged, but you can *also* re-sync your development branch. Branches in Git are actually just pointers to commits, so QMK's `master` branch at this moment is just a pointer to 97b8ade, the same way `upstream` is a pointer to your fork of QMK here on GitHub. You can have two branches that point to the same commit, so for instance you could have an `owlet60` branch that you use to make changes to your Owlet60 codebase, and then after your changes get merged into QMK, you can re-sync both your `master` and `owlet60` branches to QMK's `master` branch, and then any further changes to the Owlet60 codebase can go on the `owlet60` branch, which you can reuse for your next pull request, because its history is clean.

You don't actually have to re-sync your development branch, and you may decide you don't want to do so. Maybe you want to keep all your development branches so you can see all the individual changes you've made without having to dig through your old pull requests. In that case, you likely will want to make a new development branch `owlet60_2` or something for your next set of changes. It's really all about finding the workflow that you're most comfortable with and that suits your use case the best. That comes with time.

----

As for learning Git, I really quite like the tutorial at https://learngitbranching.js.org/. It's an interactive tutorial that walks you through the concepts that make up Git, and it really helped me when I was starting out.

If you need any more help, feel free to tag me here on GitHub, or if you use Discord, I'm on [QMK Discord](https://discord.gg/Uq7gcHh) with the same username (though my actual Discord username is xxiinophobia#5825).

**Pull request closed without merging**
