### PR TITLE
Add support of DO60

### PR DESCRIPTION
**Pull request by sennin32**
Add DO60 config.
Add testing keymap

### CODE REVIEW

**Comment by sennin32** [comment]
add default keymap for build testing

**Comment by jackhumbert** [comment]
Cool! It looks like you deleted the mechmini readme.md - would you mind restoring that? It looks like you have some empty Icon files as well - I'm not sure what these are, but we try to keep image files out of the repo. If you could make those changes and [update your readme.md to match our template](https://docs.qmk.fm/documentation_templates.html#keyboard-readmemd-template), we'll get things merged!

**Comment by sennin32** [comment]
Thank you!
I found the file is empty.
Might because of some OSx system issue.
I didn't try to add any icon in the folder.
Let me fix things you mentioned!

btw, 
I'm former anrdoid engineer,
Although I don't know much about MCU/C/arduino...etc :(
I'm yet contributing to the community.
But if you guys got any idea relate to android devices.
I'm happy to be part of it!

**Comment by sennin32** [comment]
Oh, 
And I do see mechmini's readme.md.
git shows I changed something in the folder.
But when I cd into it, every thing is there without modify.
Last edit is 10 days ago.

Maybe I make some other errors!?
Have no experience with such big project with so many people.
Not good at some git features T_T

**Comment by sennin32** [comment]
Strange, I checked all record of my branch.
Can not find any record related to delete the readme.
But it does shows this pull will delete it.
Let me try start a new pull.

**Comment by sennin32** [comment]
Let me start a new pull.
Not sure what cause the delete issue in this pull.
I can not find any delete history in my repo.

**Pull request closed without merging**
