### PR TITLE
Add hand swap config matrix for preonic rev 3

### PR DESCRIPTION
**Pull request by martinkauppinen**
## Description
The Swap Hands feature was broken on Preonic rev. 3 due to a change between revisions of the number of matrix rows and columns, leading to build errors if the feature was wanted. This fix adds a check for rev. 3 with the proper matrix.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
I like the update, but I think it may be best to move the hand_swap code from the `preonic.c` to the `rev#.c` files for each board.

@noroadsleft any thoughts?

**Comment by noroadsleft** [comment]
> I like the update, but I think it may be best to move the hand_swap code from the `preonic.c` to the `rev#.c` files for each board.
> 
> @noroadsleft any thoughts?

I agree.

**Comment by drashna** [comment]
Just thinking about it, could handle this the same way that the `music_map` is.  By using `LAYOUT_preonic_grid`, which handles all this mess for you.

**Comment by martinkauppinen** [comment]
> 
> 
> I like the update, but I think it may be best to move the hand_swap code from the `preonic.c` to the `rev#.c` files for each board.

Good call, makes a lot more sense than what I did. I blame being awake and coding at 1am. The code has been moved accordingly.

**Comment by drashna** [comment]
Well, what you did made sense, and it's what was there for the planck and preonic, in the past.   However, it led to complications, so I wanted to avoid that, and keep things consistent with how the layout macros are handled.  That should make things a lot simpler, if there are bug fixes needed.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
