### PR TITLE
Fix Pulse4k info.json LAYOUT name

### PR DESCRIPTION
**Pull request by Maxr1998**
This should fix the configurator support for this macro pad, I think.

### CODE REVIEW

**Comment by noroadsleft** [comment]
Ah, I see; it doesn't compile:

```
Linking: .build/maxr1998_pulse4k_qmk_api_tasks_test_compile.elf                                     [ERRORS]  
 | 
 | .build/obj_maxr1998_pulse4k_qmk_api_tasks_test_compile/keyboards/maxr1998/pulse4k/pulse4k.o: In function `encoder_update_kb':
 | /qmk_compiler/qmk_firmware/keyboards/maxr1998/pulse4k/pulse4k.c:51: undefined reference to `encoder_one_update'
 | /qmk_compiler/qmk_firmware/keyboards/maxr1998/pulse4k/pulse4k.c:59: undefined reference to `encoder_two_update'
 | collect2: error: ld returned 1 exit status
 | 
tmk_core/rules.mk:298: recipe for target '.build/maxr1998_pulse4k_qmk_api_tasks_test_compile.elf' failed
make[1]: *** [.build/maxr1998_pulse4k_qmk_api_tasks_test_compile.elf] Error 1
Makefile:560: recipe for target 'maxr1998/pulse4k:qmk_api_tasks_test_compile' failed
make: *** [maxr1998/pulse4k:qmk_api_tasks_test_compile] Error 1
Make finished with errors
```

You need to refactor the code so that both of these functions exist at the keyboard level, in `pulse4k.c`:

https://github.com/qmk/qmk_firmware/blob/a561443fcacc75ce6b389bd0831af85a2d104f11/keyboards/maxr1998/pulse4k/keymaps/default/keymap.c#L34-L48

The `keymap.c` file that QMK Configurator generates before compiling only contains the keymap data; it doesn't include any other functions or elements:

```c
#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_A, KC_B, KC_C, KC_D, KC_E, KC_F)
};
```

... so logic like this needs to be implemented fully at the keyboard level, instead of in the keymap.

**Comment by Maxr1998** [comment]
Ahhh, thanks for the insight. I will fix the logic errors in this branch as well then.

**Comment by Maxr1998** [comment]
That should be good now.

**Comment by Maxr1998** [comment]
@noroadsleft I think that's fine though, what the encoders do should be part of the keymap configured by the user. Or won't it work in the configurator at all then?

**Comment by noroadsleft** [comment]
Configurator-compiled firmware won't have any encoder functionality, beyond what's written in `encoder_update_kb()`. So just the rgblight events.

**Comment by Maxr1998** [comment]
I see. I will take another look then. Tomorrow, though :sweat_smile:

**Comment by Maxr1998** [comment]
Sorry for taking so long. This should be able to be merged now.

**Comment by noroadsleft** [comment]
Looks good to me.

**Comment by noroadsleft** [comment]
Thanks!

**Comment by noroadsleft** [comment]
image

:+1:

**Comment by Maxr1998** [comment]
Thank you! :tada:

**Pull request merged**
