### PR TITLE
Remap layout to match the actual keys sent from board.

### LINKED ISSUE #3480: Problem with ISO-UK layout on Tada68 and hash/slash keys
The problem I'm having is programming the ISO-UK layout specific keys.

To avoid confusion, let me define names for these two problematic keys:

* The key between the left-shift and Z key; **PipeSlash**
* The key between the @ and enter key; **TildeHash**

image

Out of the factory the board ships almost perfectly, but with both PipeSlash and TildeHash behaving as the TildeHash. Pressing either key would produce a hash.

After finding this repository from Googling around, I flashed the bin to the keyboard using `make tada68:iso-uk:bin`, which fixed the PipeSlash key but then rendered the TildeHash key useless - nothing is received by the computer when pressing TildeHash.

Looking at the code, it seems that **the problem is not the use of `KC_NUHS` constant**, but with the binding itself. If I edit the `keymap.c` file and bind `KC_A` to the TildeHash key, I would expect the key to type an "A", but still nothing happens.

Also, changing the keyboard layout/language in the operating system does not affect anything. If I run a program to monitor key presses, pressing the TildeHash button isn't detected.

Flashing the keyboard with a BIN from [the online Chinese (and ANSII-only) editor](http://123.57.250.164:3000) brings back the original keyboard behaviour with both keys acting as a TildeHash.

I'm going to continue to experiment with changing the keyboard layout, specifically in `tada68.h` as I believe that the issue stems from the use of `k2c` as the incorrect key code, but this is all new to me so any advice would be appreciated.

Thanks,
Greg.

### PR DESCRIPTION
**Pull request by g105b**
This PR fixes #3480

The layout that is supplied on the board from the factory does not differentiate between the `| \` and `~ #` keys. The `tada:iso-uk` layout in this repository kills the `~ #` key completely.

The change in this PR is to "move" the `~ #` key in the keymap file above the enter key, rather than to the left where it is physically located (and where it currently exists in the keymap file).

I would like to learn more about working with QMK Firmware so that I can further tweak the keymap file so that the keymap matches the physical layout of the board... but for now, this gets the keyboard working on all keys as intended.

Thank you for such an amazing open source repository!

### CODE REVIEW

**Comment by drashna** [comment]
@noroadsleft This look okay? 

(and Travis CI error is unrelated, caused by @mtdjr's layout/userspace)

**Comment by mtdjr** [comment]
Crap. Sorry, I’ll fix this today.

**Comment by noroadsleft** [comment]
@drashna @g105b 

If it works as intended and the current master doesn't, then it's an improvement. I'm not crazy about the `KC_NUHS` key being above the Enter key in the keymap rather than beside like it actually is on the board, but there's a way to fix that and still have it work.

@g105b, would you be willing to tell me what output you get if you set your OS input to US English and press the `KC_NUHS` key? Based on your reports, I suspect that the `KC_NUHS` and the ANSI Backslash key `KC_BSLS` are, to the Tada68's controller, identical - two physical switch locations that share one "matrix address". If my theory is correct, you'll get a backslash as the output. Doing the reverse here on my KC60 (in standard ANSI 60% layout), if I switch input to UK English, hitting my backslash key gives me # and ~.

Looking over the Tada68 files, I'm thinking the location in `tada68.h/LAYOUT_iso` that I marked as `k2c` in #3178 is actually electrically `k1d`, and that the `LAYOUT_ansi_split_enter` can't exist in the physical space. The pictures of the PCB on KBDfans seems to confirm this.

The desired solution, assuming all the above is true and accurate, is correcting the electrical matrix in `LAYOUT_iso` so the TildeHash key is on the correct row and column electrically, but assign it "out of sequence" in the keymap as follows:

`tada68.h`: (notice k1d is on home row in the keymap assignment, but on the Tab row electrically)

```c
#define LAYOUT_iso( \
    k00, k01, k02, k03, k04, k05, k06, k07, k08, k09, k0a, k0b, k0c, k0d, k0e, \
    k10, k11, k12, k13, k14, k15, k16, k17, k18, k19, k1a, k1b, k1c,      k1e, \
    k20, k21, k22, k23, k24, k25, k26, k27, k28, k29, k2a, k2b, k1d, k2d, k2e, \
    k30, k31, k32, k33, k34, k35, k36, k37, k38, k39, k3a, k3b, k3c, k3d, k3e, \
    k40, k41, k42,           k45,                k49, k4a, k4b, k4c, k4d, k4e  \
) \
{ \
    {k00, k01, k02, k03, k04, k05, k06, k07, k08, k09, k0a, k0b, k0c, k0d, k0e}, \
    {k10, k11, k12, k13, k14, k15, k16, k17, k18, k19, k1a, k1b, k1c, k1d, k1e}, \
    {k20, k21, k22, k23, k24, k25, k26, k27, k28, k29, k2a, k2b, XXX, k2d, k2e}, \
    {k30, k31, k32, k33, k34, k35, k36, k37, k38, k39, k3a, k3b, k3c, k3d, k3e}, \
    {k40, k41, k42, XXX, XXX, k45, XXX, XXX, XXX, k49, k4a, k4b, k4c, k4d, k4e}  \
}
```

`keymaps/iso-uk/keymap.c`: (`KC_NUHS` physically on home row)

```
  [_BL] = LAYOUT_iso(
    KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_GRV,  \
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC,          KC_DEL,  \
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,  KC_PGUP, \
    KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_PGDN, \
    KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,                             KC_RALT, MO(_FL), KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
  ),

  [_FL] = LAYOUT_iso(
    _______, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_DEL,  KC_INS,  \
    _______, _______, KC_UP,   _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          KC_HOME, \
    _______, KC_LEFT, KC_DOWN, KC_RGHT, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, KC_END,  \
    _______, _______, _______, _______, BL_DEC,  BL_TOGG, BL_INC,  _______, KC_VOLU, KC_VOLD, KC_MUTE, _______, KC_BTN1, KC_MS_U, KC_BTN2, \
    _______, _______, _______,                   _______,                            _______, _______, _______, KC_MS_L, KC_MS_D, KC_MS_R
  ),
```

**Comment by arnaldur** [comment]
Can confirm the solution from @noroadsleft works for my Tada68 iso layout keyboard, the KC_NUSH works now, was dead before.

**Comment by drashna** [comment]
Thanks!

**Comment by noroadsleft** [comment]
@arnaldur @g105b Thanks for the confirmations. Just now seeing this as I'm just getting over having been quite sick (I suspect the flu).

**Pull request merged**
