### PR TITLE
Fixed dead links

### PR DESCRIPTION
**Pull request by Choromanski**
Fixed a bunch of dead links in sub folders docs, layouts, keyboards, and tmk_core.

### CODE REVIEW

**Comment by skullydazed** [comment]
Thanks!

This is very nice! Did you use a tool to check these links? I'd love to learn more about your process if so.

**Comment by Choromanski** [comment]
@skullydazed I used the npm program [markdown-link-check](https://www.npmjs.com/package/markdown-link-check) and the find command to search all the *.md files in my off-line repo. I still have a hand full of links I need to fix that I wasn't able to find  a proper replacement for, such as links to images on the repo before they got removed and links to websites that just don't exist anymore. Do you want me to just delete them if that is the case?

**Comment by skullydazed** [comment]
Yeah, after giving it some thought I think deleting them is probably best in most cases, unless we can find a similar replacement for the link.

**Comment by Choromanski** [comment]
@skullydazed alright cool, just made a pull request removing the dead links

**Pull request merged**
