### PR TITLE
Combo `TAP_CODE_DELAY` and `clear_weak_mods`

### PR DESCRIPTION
**Pull request by sevanteri**
## Description

`TAP_CODE_DELAY`: Some software (e.g. some games) don't like key press and release events too close to each other, so a delay is needed after dumping the key buffer in combo processing.

`clear_weak_mods`: Before, weak mods from combos could leak to the next key press if pressed too fast.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by sevanteri** [comment]
Why does "some software" have to suck so bad... I hate having `TAP_CODE_DELAY` already...

**Review by drashna — APPROVED** [review]

**Comment by sevanteri** [comment]
Needs some work still. If a mod-tap or similar is part of a combo, the delay is applied twice after releasing the key (once in combo processing, once in the ~~tapping monstrosity~~ `process_action`)

**Review by tzarc — APPROVED** [review]

**Comment by drashna** [comment]
> Needs some work still. If a mod-tap or similar is part of a combo, the delay is applied twice after releasing the key (once in combo processing, once in the ~tapping monstrosity~ `process_action`)

Is this ready to go, as is?

**Comment by sevanteri** [comment]
Yeah, should be good to go, haven't had problems with it.

**Review by drashna — APPROVED** [review]

**Pull request merged**
