### PR TITLE
18bluetoothpad add via,use the AdafruitBLE SPI FRIEND

### PR DESCRIPTION
**Pull request by latincompass**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by latincompass** [comment]
> As with #9012 and #9152 you've filed this pull request from your fork's `master` branch. Your master branch has extra changes in which have already been mentioned unnecessary. All `latinpad` changes should be reverted.
> 
> It is highly recommended for QMK development - regardless of what is being done or where - to keep your master updated, but **NEVER** commit to it. Instead, do all your changes in a branch (branches are basically free in Git) and issue PRs from your branches when you're developing.
> 
> There are instructions on how to keep your master updated here:

THNAKS a lot，Sir, i will change the  `latinpad` changes should be reverted.

**Comment by latincompass** [comment]
> As with #9012 and #9152 you've filed this pull request from your fork's `master` branch. Your master branch has extra changes in which have already been mentioned unnecessary. All `latinpad` changes should be reverted.
> 
> It is highly recommended for QMK development - regardless of what is being done or where - to keep your master updated, but **NEVER** commit to it. Instead, do all your changes in a branch (branches are basically free in Git) and issue PRs from your branches when you're developing.
> 
> There are instructions on how to keep your master updated here:
> 
> [**Best Practices: Your fork's master: Update Often, Commit Never**](https://docs.qmk.fm/#/newbs_best_practices?id=your-fork39s-master-update-often-commit-never)

Sir i want call back the latinpad,but i can`t

**Comment by latincompass** [comment]
> To fix the issue @zvecr is flagging, do this:
> 
> ## 1. Check your configured forks
> Your Git installation should know about both this repository and your fork. To check the configured forks, run `git remote -v`, which should return something like this:
> 
> ```shell
> $ git remote -v
> origin  https://github.com/latincompass/qmk_firmware.git (fetch)
> origin  https://github.com/latincompass/qmk_firmware.git (push)
> upstream        https://github.com/qmk/qmk_firmware.git (fetch)
> upstream        https://github.com/qmk/qmk_firmware.git (push)
> ```
> 
> The above means Git uses `upstream` to refer to this repository, and `origin` to refer to your fork.
> 
> ## 2. Retrieve the current state of this repository
> To do this, run:
> 
> ```shell
> git fetch upstream master
> ```
> 
> ## 3. Restore the source branch of this pull request to match that of this repository
> Run:
> 
> ```shell
> git reset --hard FETCH_HEAD
> ```
> 
> In Git, `FETCH_HEAD` means "the state most-recently retrieved by `git fetch`", which in this case is the state of the `master` branch of the qmk/qmk_firmware repository, which was retrieved in Step 2. `git reset --hard` means "rewrite the files on my computer." The above command rewrites the files on your system so they all match the files that are on this repository.
> 
> ## 4. Re-apply the changes intended for this pull request
> Run:
> 
> ```shell
> git cherry-pick b73e6edcd 74424c3ef 923be8d06 64aef1b16 83bbcf0bd e9faf60c0 815e379df 739f67272 9b8c6b27e e7fd92ec0 eacea055d 371b2734d 0042755b0 88544701e 2385dc843 d8182bea5 9e992f8a3 4749c851c
> ```
> 
> `git cherry-pick` takes a series of commit hashes as arguments. The above command means "Take the changes made by these commits, and re-apply them to the current branch."
> 
> ## 5. Update the source branch for this pull request
> Once the above completes, run:
> 
> ```shell
> git push --force-with-lease
> ```
> 
> That should update this pull request with only the changes required for this pull request.

Sir ,my english is so bad,I don't dare to make the above order for fear of ruining the program。

**Comment by noroadsleft** [comment]
> Sir ,my english is so bad,I don't dare to make the above order for fear of ruining the program。

[`Google Translated Chinese`](https://translate.google.com/?hl=en&tab=TT#view=home&op=translate&sl=en&tl=zh-CN&text=Nearly%20everything%20in%20Git%20is%20reversible.%20It's%20almost%20impossible%20to%20break%20something%20permanently.%20But%20fair%20enough.): Git中的几乎所有东西都是可逆的。永久性破坏几乎是不可能的。但是足够公平。

`English`: Nearly everything in Git is reversible. It's almost impossible to break something permanently. But fair enough.

**Comment by latincompass** [comment]
> > Sir ,my english is so bad,I don't dare to make the above order for fear of ruining the program。
> 
> [`Google Translated Chinese`](https://translate.google.com/?hl=en&tab=TT#view=home&op=translate&sl=en&tl=zh-CN&text=Nearly%20everything%20in%20Git%20is%20reversible.%20It's%20almost%20impossible%20to%20break%20something%20permanently.%20But%20fair%20enough.): Git中的几乎所有东西都是可逆的。永久性破坏几乎是不可能的。但是足够公平。
> 
> `English`: Nearly everything in Git is reversible. It's almost impossible to break something permanently. But fair enough.

Thank you sir,i will try it.

**Comment by latincompass** [comment]
按时奥术大师多

**Comment by noroadsleft** [comment]
@latincompass 很抱歉，漫长的等待； 我有大量的待处理评论积压了一段时间。/ Sorry for the long wait; I have had an extensive backlog of reviews to do for a while.

您仍然要添加此内容吗？ / Do you still want this added?

**Pull request closed without merging**
