### PR TITLE
Fixed keymap names of Noah AVR

### PR DESCRIPTION
**Pull request by kb-elmo**
## Description

Fixed the keymap names of the Noah AVR PCB

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by tzarc — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by fauxpark** [comment]
Hm, actually these don't seem to match the default community layouts:

```
error: macro "LAYOUT_64_ansi" requires 67 arguments, but only 64 given
error: macro "LAYOUT_64_iso" requires 68 arguments, but only 65 given
```

**Comment by fauxpark** [comment]
Ah, I see what's happened. The layout macros in noah_avr.h should be the ones getting renamed instead.

**Comment by kb-elmo** [comment]
> Ah, I see what's happened. The layout macros in noah_avr.h should be the ones getting renamed instead.

i had LAYOUT_65_ansi in my original PR but that didn't work either.

**Comment by fauxpark** [comment]
Nope: https://github.com/qmk/qmk_firmware/pull/11563/files#diff-d13bce6be710f240a763af9d1bab86e28b5cf10b8a204fc5b4bcdb2000fa8070R45

**Comment by kb-elmo** [comment]
> 
> 
> Nope: https://github.com/qmk/qmk_firmware/pull/11563/files#diff-d13bce6be710f240a763af9d1bab86e28b5cf10b8a204fc5b4bcdb2000fa8070R45

I did. Drashna requested it to be changed in the PR process.
https://github.com/qmk/qmk_firmware/pull/11563#pullrequestreview-579726387

**Comment by fauxpark** [comment]
In that case, it's not either. Rename them and remove the `LAYOUTS` line from rules.mk instead.

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
