### PR TITLE
doc update zh-cn

### PR DESCRIPTION
**Pull request by ymzcdg**
Timestamp was added at the end of the document, it can help me manage version easier.

## Description

QMK has changed a lot, so has the documents.
Timestamp was added at the end of the document.
It is suggested to add a timestamp to the document to facilitate the translator to manage the version.
武汉加油！
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Could you please change the encoding to UTF-8? It looks like this locally:
image

**Comment by ymzcdg** [comment]
> 
> 
> Could you please change the encoding to UTF-8? It looks like this locally:
> image

sorry,I will check it.

**Comment by ymzcdg** [comment]
notepad++ default to GB2312, already fixed.

**Comment by fauxpark** [comment]
Sorry, there were no changes in that last commit.

**Comment by fauxpark** [comment]
Much better, thanks 👍

**Comment by noroadsleft** [comment]
> notepad++ default to GB2312, already fixed.

Also, I'm a Notepad++ user myself; you can change the default file encoding under Settings / Preferences / New Document / Encoding (in English, anyway :smiley:), if it suits. Encoding of an existing file can be changed in the Encoding menu.

**Comment by ymzcdg** [comment]
> 
> 
> Just a general comment:
> 
> Adding a timestamp as you've done here is fine, but the group that's been doing our Japanese translations has been using the original commit hash to track the source English doc:
> 
>     * https://github.com/qmk/qmk_firmware/blame/387c486e570cc94d6798a8f326dcfe7fdeb7891f/docs/ja/arm_debugging.md#L3-L6
> 
> 
> This has the advantage that it's not specific to a time zone as your method is, in the event someone who perhaps speaks Chinese but doesn't live in China wants to check changes to the English doc that may need updating on the translation.
> 
> Anyway, looks good to me. Thank you for your contributions!

Your method looks very good, but I can't find the way to generate the string of"eae21eed7" with "docs/arm_debugging.md" ,"eae21eed7" is not the commit hash "52c18ef02" and even not md5/sha1 of the document.
I decide to use commit hash and PRid e.g. : arm_debugging.md--52c18ef--7642. I wonder if I can do this.
Thanks for your help.

**Comment by ymzcdg** [comment]
> 
> 
> > notepad++ default to GB2312, already fixed.
> 
> Also, I'm a Notepad++ user myself; you can change the default file encoding under Settings / Preferences / New Document / Encoding (in English, anyway smiley), if it suits. Encoding of an existing file can be changed in the Encoding menu.

Already set but don't work, maybe something wrong with the program. I‘d better use vscode.Thanks.

**Comment by noroadsleft** [comment]
> Your method looks very good, but I can't find the way to generate the string of"eae21eed7" with "docs/arm_debugging.md" ,"eae21eed7" is not the commit hash "52c18ef02" and even not md5/sha1 of the document.

The `eae21eed7` references the commit mash of QMK's `master` branch at the time the file was translated. Specifically, it's referencing:

https://github.com/qmk/qmk_firmware/blob/eae21eed743d8bb9fd961f91d97a92f0f94247fe/docs/arm_debugging.md

The line with `git diff` displays the changes that have been made to the original (English) file since the translated file was created or last updated.

**Comment by ymzcdg** [comment]
> 
> 
> > Your method looks very good, but I can't find the way to generate the string of"eae21eed7" with "docs/arm_debugging.md" ,"eae21eed7" is not the commit hash "52c18ef02" and even not md5/sha1 of the document.
> 
> The `eae21eed7` references the commit mash of QMK's `master` branch at the time the file was translated. Specifically, it's referencing:
> 
> https://github.com/qmk/qmk_firmware/blob/eae21eed743d8bb9fd961f91d97a92f0f94247fe/docs/arm_debugging.md
> 
> The line with `git diff` displays the changes that have been made to the original (English) file since the translated file was created or last updated.

Thanks. I will learn to use Git.

**Pull request merged**
