### PR TITLE
Reduce NIBBLE oled_bongocat keymap size so it compiles

### PR DESCRIPTION
**Pull request by jaygreco**
## Description
Changed WPM counter string builder in order to get the nibble oled_bongocat keymap to compile (thanks to @drashna for the clever optimization).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR
N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Actually, I would recommend reverting this change.  You can save ~1.5K by making a simple change to how the WPM is rendered. 

https://github.com/qmk/qmk_firmware/blob/336c8d3efeaf709f8d80033976141968f478fc59/keyboards/nullbitsco/nibble/keymaps/oled_bongocat/keymap.c#L164-L165

change this to: 
```c
    uint8_t n = get_current_wpm();
    char wpm_counter[4];
    wpm_counter[3] = '\0';
    wpm_counter[2] = '0' + n % 10;
    wpm_counter[1] = '0' + (n /= 10) % 10;
    wpm_counter[0] = '0' + n / 10 ;
    oled_write_P(PSTR("WPM: "), false);
    oled_write(wpm_counter, false);
```

You can remove the stdio.h include at the beginning of the file too.

**Comment by jaygreco** [comment]
Ayoooo, great feedback! Thanks for the heads up. I'll close this PR and revert + resubmit. That's a much better solution.

**Comment by drashna** [comment]
no need to have closed the PR.  Changes to the branch would be reflected. 

And yeah, for such a "simple" change, it's a huge savings!  Been recommending it on any new PRs I've seen since it's such a big change.

**Comment by jaygreco** [comment]
🤦‍♂️ I should stay away from PRs late at night. Thanks! Will update. Appreciate the input and help as always @drashna 👍

**Comment by drashna** [comment]
> 🤦‍♂️ I should stay away from PRs late at night. Thanks! Will update. Appreciate the input and help as always @drashna 👍

I totally understand that feeling.  And welcome!

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
