### PR TITLE
smallkeyboard

### PR DESCRIPTION
**Pull request by zhouqiong19840119**
## Types of Changes

- [x] Core
- [x] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by ridingqwerty — CHANGES_REQUESTED** [review]
Please change all instances of folder name "`small keyboard`" to "`small_keyboard`", or some other schema without a space in the path.  Whitespace in the folder name will cause breakage.

**Review by ridingqwerty — COMMENTED** [review]
In fact, it would be best if all one word "`smallkeyboard`", to match the keyboard `*.{c,h}` files

**Comment by zhouqiong19840119** [comment]
> Please change all instances of folder name "`small keyboard`" to "`small_keyboard`", or some other schema without a space in the path. Whitespace in the folder name will cause breakage.

SIR,Can you help me change the FOLDER NAME to "smallkeyboard",I do not want delete it

**Comment by zhouqiong19840119** [comment]
> Please change all instances of folder name "`small keyboard`" to "`small_keyboard`", or some other schema without a space in the path. Whitespace in the folder name will cause breakage.

SIR,Can you help me change the FOLDER NAME to "smallkeyboard",I do not want delete it

**Pull request closed without merging**
