### PR TITLE
[WIP] Lint documentation during build

### PR DESCRIPTION
**Pull request by zvecr**
## Description

The intention is to provide relevant feedback during the code review process, which should help improve the quality and consistency of the code base.

I have enabled [codacy](codacy.com) for my fork.
https://app.codacy.com/project/zvecr/qmk_firmware/dashboard
The dashboard is feature rich, allowing tracking of improvements to quality, and breakdowns of current issues. The same information is also available to pull requests, that can mark the PR for any negative trending commits. It might take a bit more effort as one of the QMK members will have to set up and configure. I can mess about with settings for my fork, in order to have some recommendations ready if we pull the trigger.

As an alternative solution,  I have added an entry point in travis for performing "static analysis" type actions. So far, the process just performs linting of the repos markdown files. This might require additional logic, potentially filtering to only linting the changed files, as displaying `1435` warnings might overwhelm and mask the new issues.

As always, feedback for the idea is welcome, as well as anything that _could_ push this over the line.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
The current codacy status...
image

**Comment by yanfali** [comment]
@mechmerlin I think we should add this

**Comment by zvecr** [comment]
@yanfali were you referring to codacy or the more custom integration?

Recently i have been setting up and using remark, as its what codacy uses and you can share the conf file, run locally and all that goodness. Either way, markdownlint-cli or remark-cli would need some configuring to the current style (minor things like tab size).

**Comment by zvecr** [comment]
Looking to push a github integration like codacy

**Pull request closed without merging**
