### PR TITLE
add keyboard ilovbee B87

### PR DESCRIPTION
**Pull request by yangzheng20003**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by yangzheng20003** [comment]
This is only a purely wired program.

**Comment by Cipulot** [comment]
> This is only a purely wired program.

No it is not, stop lying about trying to merge boards just for the sake of it, going against the licensing terms.

Comply with the license and don't try to sneak in code like this. https://github.com/qmk/qmk_firmware/issues/24085

For reference, YT video review of this board that clearly states and shows the model board you're trying to merge and can be seen plain as day that it's tri-mode: 

https://www.youtube.com/watch?v=keBXeWYEve8&ab_channel=StudioSC

@tzarc for reading and label application

**Comment by tzarc** [comment]
@cipulot thanks for letting the QMK team know.

I'll discuss within the team but I think we're close to the point where we're going to start banning either individuals, vendors, or specific hardware providers. This is no longer a workable situation.

**Comment by yangzheng20003** [comment]
Oh, this version is only the wired version of the keyboard. As for the three-mode part, we also have an open source wireless part, but it has not been merged into the main branch. We did not request to merge the three-mode of the same model. They have typical differences, such as different PID VID, etc. The keyboard version currently uploaded is also only a limited version

**Comment by tzarc** [comment]
> Oh, this version is only the wired version of the keyboard. As for the three-mode part, we also have an open source wireless part, but it has not been merged into the main branch. We did not request to merge the three-mode of the same model. They have typical differences, such as different PID VID, etc. The keyboard version currently uploaded is also only a limited version

Consider this comment an official request from copyrights holders that you now have 30 days to provide full sources for both the wired and wireless versions of your board, otherwise your license to use QMK will be officially revoked.

**Comment by EBADBEEF** [comment]
Looks like wb32 wireless support is in https://github.com/WestberryTech/qmk_westberry (see [keyboards/westberry/wireless](https://github.com/WestberryTech/qmk_westberry/tree/1ae12a7d6ebc7e18ddc44857803c409efcc55994/keyboards/westberry/wireless)). My guess is the wb32 chip includes a built-in firmware to handle bluetooth/2.4ghz wireless instead of handling the protocol inside of QMK.

There is a PR for this keyboard that appears to include wireless support in https://github.com/WestberryTech/qmk_westberry/pull/64. I'm not trying to comment on the political nature of this issue, just trying to see what is out there.

**Pull request closed without merging**
