### PR TITLE
Set up language fallback for docs, and update translation guidelines

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Without this `fallbackLanguages` array, pages that don't exist in the selected language will 404. All links must also be prefixed with the language code, or it will revert back to English.

Additionally, pointed users towards using the `qmk docs` CLI command, and used fenced code blocks in translating.md, for syntax highlighting.

Also I think the country flags should be the actual emoji characters, instead of eg. `:ja:`, as some of them appear to be unsupported currently.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mtei** [comment]
Some of the section titles (those linked from others) must also be as follows:

```diff
diff --git a/docs/zh-cn/newbs_flashing.md b/docs/zh-cn/newbs_flashing.md
index 05a9eb55e..5f1899c5b 100644
--- a/docs/zh-cn/newbs_flashing.md
+++ b/docs/zh-cn/newbs_flashing.md
@@ -78,5 +78,5 @@
 
-## 使用命令行刷新键盘
+## 使用命令行刷新键盘 :id=flash-your-keyboard-from-the-command-line
 
 首先，您需要知道您的键盘使用的是哪个bootloader。通常是以下四个常见的bootloader。Pro-Micro 和 clones 使用 CATERINA, Teensy 使用 Halfkay, OLKB 键盘使用 QMK-DFU, 其他的atmega32u4芯片使用DFU。
```

I think this description needs to be added to `docs/translating.md`.
(If the English version already contains `:id=xxx`, translators to the new language will be easier to translate.)

**Comment by mtei** [comment]
I have a suggestion.

The following information at the end of `docs/README.md` may help newcomers.

```
?> You can also view this document directly in a repository that has been cloned to your computer. [How to view] (translating.md#previewing-the-translations)
```

**Comment by fauxpark** [comment]
@mtei I moved the entire section to contributing.md, as this information can be used for any kind of docs work, not just translations.

**Comment by mtei** [comment]
@fauxpark, Information on how to preview documents is also useful for users who want to create their own keymaps but do not plan to contribute.
So it would be nice to have a link to the description in README.md or somewhere.

**Comment by fauxpark** [comment]
I'm not quite sure what you mean. This is primarily a dev tool for testing changes to the docs - if you just want to read them you can simply go to the docs site.

**Comment by mtei** [comment]
I want to be able to read the document without being connected to the internet if possible.

**Comment by fauxpark** [comment]
Okay, how's this?

**Comment by mtei** [comment]
Thank you!

**Pull request merged**
