### PR TITLE
Move all KPRepublic keyboards in the same directory

### PR DESCRIPTION
**Pull request by GreatWizard**
This PR is similar to https://github.com/qmk/qmk_firmware/pull/5206 but we don't have to have fun with conflicts and it only moves boards into a subdirectory.

We should open smaller PR, extract from #5206, about the other changes (if they are still relevant) that are not related to the move of boards.

## Description

To reduce clutter in the keyboards/ directory, this PR adds a kprepublic folder to collate all boards under one parent:

- bm16a
- bm16s
- bm43a
- bm60rgb
- cospad
- daisy
- jj4x4
- jj40
- jj50
- staryu
- xd0002
- xd0004
- xd60
- xd68
- xd75
- xd84
- xd87
- xd96

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

close #5206

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by yanfali** [comment]
This one is further along https://github.com/qmk/qmk_firmware/pull/5206

**Comment by yanfali** [comment]
looks like a dupe.

**Comment by GreatWizard** [comment]
Yes it's a part of #5206 up-to-date: only move directories and fix make commands.

**Comment by GreatWizard** [comment]
Yes it's the idea of #5206: only move directories and fix make commands
It think #5206 is too hard to rebase without headache and it's more than 1 year old: there are a lot of new kprepublic boards in qmk and changes that conflict.

**Comment by zvecr** [comment]
#5206 isnt too bad to rebase, has additional review context, plus i am still active on the project. The missing context is that the PR has dropped out of the last 2 merge windows due to internal discussions.

For now im going to close this one as a duplicate.

**Pull request closed without merging**
