### PR TITLE
add hhkb bluetooth functionality (rn42)

### PR DESCRIPTION
**Pull request by Enochen**
pretty much straight from tmk
only some minor changes to make things work

just do 'HHKB_RN42_ENABLE=yes' to enable

### CODE REVIEW

**Comment by drashna** [comment]
Instead of as an option, maybe this should be a revision of the board?

**Comment by Enochen** [comment]
I'm not sure what a revision is in qmk, but I added it as an option because it is just an extra feature you might want to add to your keyboard

**Comment by drashna** [comment]
Revisions are basically like "sub projects".  They're usually used for significant design changes, so that you're not overlapping too much. 

The Lets Split and planck boards are examples of this. 

And giving the amount of changes here, I think that this may be a better idea here.

@jackhumbert opinion?  Or is this fine?

**Comment by Necrosan** [comment]
Any word on this?

**Comment by drashna** [comment]
Well, it doesn't touch any core files, and ... I'm more confident about merging keyboard stuff.

**Comment by drashna** [comment]
Thanks!

**Comment by uuhan** [comment]
It seems the master branch can not be compiled with HHKB_RN42_ENABLE=yes.
#3479

**Pull request merged**
