### PR TITLE
3 speed mousekey movement

### PR DESCRIPTION
**Pull request by JonArintok**
With these modifications to mousekey.c and mousekey.h, the cursor and scrolling will now move at a constant speed. 3 speeds can be precisely defined for both the cursor and the mouse wheel in your keymap's config.h. I also updated the docs accordingly.

### CODE REVIEW

**Comment by Markus00000** [comment]
I suggest making the constant speeds an optional feature. People who have been using acceleration might not be happy when it is removed and their mouse suddenly moves at constant speeds only.

**Comment by JonArintok** [comment]
OK, I'm working on a solution.

**Comment by JonArintok** [comment]
With this, the default behavior will be unchanged, and there should be no performance penalty either way.

**Comment by drashna** [comment]
There is a doc conflict

**Comment by DanielGGordon** [comment]
I personally use and enjoy having acceleration. I would not want constant speed to be default.

**Comment by drashna** [comment]
@DanielGGordon it looks like this PR actually allows for both acceleration, or a set speed.  So you can choose when compiling.

**Pull request merged**
