### PR TITLE
Reverse keymap search order

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

If a keyboard has two keymaps with the same name at multiple levels (eg. `keyboardname` and `keyboardname/rev3` where `rev1` and `rev2` can share a keymap, but `rev3` differs), the makefile logic will pick up the highest-level keymap instead.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
CI failure is expected; the affected boards will need a followup PR to fix the layouts.

**Review by spidey3 — APPROVED** [review]

**Comment by drashna** [comment]
wait, would this prefer the `board/rev3` or `board` keymap?

**Comment by fauxpark** [comment]
The former. Note CI here is passing where dimple rev3 and infinity87 are failing in current develop builder.

**Review by drashna — APPROVED** [review]

**Comment by zvecr** [comment]
Do we want such a logic change to go to `master` rather than `develop`?

**Comment by fauxpark** [comment]
May as well, I'm pretty confident the two boards above are the only ones affected, but just in case...

**Pull request merged**
