### PR TITLE
Add Naiping series keyboard

### PR DESCRIPTION
**Pull request by Weirdo-F**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by Weirdo-F** [comment]
what should i do next？

**Comment by drashna** [comment]
> what should i do next？

Mostly, just wait.  Generally, we want 2 reviews on any given PR.  And we do the reviews in our free time, so it can take a bit before they're done.

**Review by fauxpark — APPROVED** [review]

**Comment by Weirdo-F** [comment]
@drashna Two members have agreed to my modification. Can I merge?

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Comment by drashna** [comment]
> @drashna Two members have agreed to my modification. Can I merge?

Unfortunately, no. Only people with write access can actually merge. So that's a collaborator or director.

That said, it has 2 approvals, so I have merged it

**Pull request merged**
