### PR TITLE
Remove remaining use of terminal keys and related comment labels

### PR DESCRIPTION
**Pull request by kyrias**
## Description

The terminal feature was removed in 8545473307 (Removes terminal from QMK. (#17258), 2022-05-31).  This commit removes the remaining usages of `TERM_{ON,OFF}` and removes the terminal key labels from the keymap comments where the keymap itself had already been updated.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — CHANGES_REQUESTED** [review]
Since this touches user keymaps this will need to go through develop.

**Comment by kyrias** [comment]
Rebased on develop now.  Maybe this is something that should be added to the PR Checklist.  :)

**Comment by drashna** [comment]
This has a merge conflict.

**Comment by kyrias** [comment]
Rebased again.

**Review by fauxpark — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Pull request merged**
