### PR TITLE
Rabbit68: Configurator layout support

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

Makes the keymap resemble the physical hardware in [QMK Configurator](https://config.qmk.fm/#/rabbit/rabbit68/LAYOUT).

## Notes

Tagging @kaiec (Keyboard Maintainer)

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
> Actually seems to have 61 keys, but LGTM

Not sure where you're seeing that.

**Comment by fauxpark** [comment]
Ah, no, you're correct. Configurator isn't updating the key count in the bottom right when you Ctrl+Shift+I :/

**Comment by noroadsleft** [comment]
Ah, yeah. I noticed that too and I just decided to deal with it. I have other methods for checking the key count anyway.

**Comment by drashna** [comment]
> LGTM. Hop to it!

💩

**Comment by yanfali** [comment]
> Ah, no, you're correct. Configurator isn't updating the key count in the bottom right when you Ctrl+Shift+I :/

Yeah this feature is an exception path, it gets the count from the layout macro, which is loaded temporarily into memory for the preview.

**Pull request merged**
