### PR TITLE
Update Preonic's MCU configuration to use the built-ins

### PR DESCRIPTION
**Pull request by jackhumbert**
Should have done this a while ago...

### CODE REVIEW

**Comment by evantravers** [comment]
So far… this works for me. Thanks!

**Comment by drashna** [comment]
Looks like it passes Travis CI, actually.
The branch itself doesn't, but the changes from this branch do.

**Comment by jackhumbert** [comment]
Awesome :) thanks!

**Comment by evantravers** [comment]
👍

**Pull request merged**
