### PR TITLE
handwired/split89 Layout Macro Refactor

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

* rearranges the layout macro and keycodes to resemble the assembled board.
  `KC_Y` is now between `KC_T` and `KC_U`; `KC_H` between `KC_G` and `KC_J`; `KC_N` between `KC_B` and `KC_M`
* updates `split89.h` to use `k<row><column>` notation
* refactors default keymap for readability
* reformats `info.json` for readability/to match layout
  *before* 
  image
  *After*
  image

No logic changes in this PR.

cc @jurassic73 (keyboard maintainer)

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by jurassic73** [comment]
@noroadsleft thanks for your time on this.

**Comment by jurassic73** [comment]
This pull request broke the keyboard layout.

Another user that built my keyboard downloaded firmware and the changes in this pull request broke the mapping.  I just compiled and downloaded the firmware and this mapping is indeed broken.  Can this please be rolled back to remove the changes this pull request implemented?

**Comment by noroadsleft** [comment]
@jurassic73,

Did your user rearrange their keycodes similarly to how the default keymap is edited in this PR? I just rechecked the branch and the default keymap compiles exactly the same before and after these changes – running `shasum handwired_split89_default.hex` from the base commit (`cd50fdf`) and this branch gives me a SHA-1 checksum of `83b86f75b747a7def91d9a28edb0c7e24f3ea4c7`. (Your checksum here may differ if you do the same check, but should be the same before and after.)

**Comment by jurassic73** [comment]
No user keymap rearragment took place by users or myself before or now.  Before your pull request, simply bringing up the split89 layout and compiling produced working firmware.  After your pull request was added, the layout is now broken.

If there is a proper key layout I need to adhere to, I can work towards it but for now could the changes made in your pull request be rolled back as the generated firmware request worked before this, so users can download working firmware by default?  Currently it generates an incorrect firmware file for users.

If you could do this, I could work on installing QMK on my end in a container and try to work this out so it's to  your standards?

**Comment by noroadsleft** [comment]
> Before your pull request, simply bringing up the split89 layout and compiling produced working firmware.

Are you talking about compiling in QMK Configurator here?

**Comment by jurassic73** [comment]
Yes, compiling firmware in the web interface to download.

**Comment by noroadsleft** [comment]
Odd, I can't see any reason why this wouldn't work. I'll go ahead and open a PR to revert these changes.

Perhaps we can connect next week and see about reworking this and/or coordinating on what changes should be made.

**Comment by jurassic73** [comment]
I appreciate your time.  The layout of the wiring and correlating it to the
key layout nearly broke my brain but I 'got it working' however it sounds
like it needs further work.  Thanks for the help on this.

**Pull request merged**
