### PR TITLE
Fixing MIDI for ARM without NKRO enabled

### LINKED ISSUE #9439: #include "qmk_midi.h" always results in compile error[Bug]
##  Describe the Bug

I've spent the past few days working on a keymap for the BDN9 that includes midi functionality on separate layers. Everything works great, but I wanted to include midi sends for the encoders like

```
        if (clockwise) {
            midi_send_cc(&midi_device, 0, 0x14, 1);
        } else {
            midi_send_cc(&midi_device, 0, 0x15, 1);
```

However, in order to do that I need to put #include "qmk_midi.h" within the keymap and no matter what I do it always results in the same error if qmk_midi.h is included. Here's the error

```
tmk_core/protocol/midi/qmk_midi.h:7:36: error: unknown type name 'MIDI_EventPacket_t'
 void              send_midi_packet(MIDI_EventPacket_t* event);
                                    ^~~~~~~~~~~~~~~~~~
tmk_core/protocol/midi/qmk_midi.h:8:36: error: unknown type name 'MIDI_EventPacket_t'
 bool              recv_midi_packet(MIDI_EventPacket_t* const event);

```

I've gotten pretty obsesive about it because I can't for the life of me figure it out. I have midi enabled in the rules and have # define MIDI_ADVANCED in the config. I'd really appreciate if anyone has any suggestion. Thanks

## System Information

 - Keyboard:  
   BDN9 REV 1 (Pro Micro)
 - Operating system:
    Windows 10
 - AVR GCC version: 
   8.3.0
 - ARM GCC version: 
    8.3.1
 - QMK Firmware version:
    0.9.10

### PR DESCRIPTION
**Pull request by AlexOConnorHub**
## Description

MIDI does not work for ARM without NKRO enabled, because it includes this header file. By adding this, the correct header is included regardless of NKRO, while allowing AVR to continue to work.
## Types of Changes
Adding header file.

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* fixes #9439

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by AlexOConnorHub** [comment]
Sorry I do not know what type of change this is.

**Comment by AlexOConnorHub** [comment]
Thanks there Erovia!

**Comment by AlexOConnorHub** [comment]
Is there any reason you left the `__attribute__((weak))` comment @Erovia ?

**Comment by Erovia** [comment]
To signal to the other collaborators that my approval is a "weak" one. (your changes look good to me, but I'm not familiar with the codebase)

Looking back, I probably should have clarified that.

**Comment by AlexOConnorHub** [comment]
Oh, no problem. This is my first pull with QMK, and I just wanted to make sure it didn't mean I needed to change something.

**Comment by AlexOConnorHub** [comment]
Thanks!

**Pull request merged**
