### PR TITLE
Update keymap.c

### PR DESCRIPTION
**Pull request by worldspawn00**
adding V2 layout support

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by worldspawn00** [comment]
checks will fail till all 3 modified files are approved

**Comment by worldspawn00** [comment]
Pull 10312, 10311, 10310

**Review by ridingqwerty — APPROVED** [review]

**Comment by GauthierPLM** [comment]
If you edit multiple files for the same change you should add all of them in one PR so reviewers can easily review them altogether, CI checks properly pass, and when merging your PR, other users can easily see the related commit are linked to each others.

Better: commit all your change together so you have only one commit. If you are not sure how to do this, do not hesitate to ask on Discord or read a little bit about Git. :)

**Review by fauxpark — APPROVED** [review]

**Comment by noroadsleft** [comment]
@GauthierPLM is correct – these three pull requests you've filed comprise one logical change: adding support for a new revision of an existing keyboard. As it's one logical change, it should be one pull request.

Please merge the changes from #10310, #10312 and this pull request into one branch, and open a new pull request.

Something that helped me to understand Git was [Learn Git Branching](https://learngitbranching.js.org/) – it's a browser game that simulates using Git.

If you need any help, find us on the [QMK Discord](https://discord.gg/Uq7gcHh). I'm there as `@noroadsleft` (account is `xxiinophobia#5825`).

**Pull request closed without merging**
