### PR TITLE
Add keymaps for Iris, Let's Split, TADA68, XD75, and handwired dox

### PR DESCRIPTION
**Pull request by mtdjr**

### CODE REVIEW

**Comment by drashna** [comment]
Not sure which is better here, but there is the "faux clicky"/audio clicky subfeature that does something similar to what you're doing with the solenoid code here: https://docs.qmk.fm/#/feature_audio?id=faux-click

(if you want a 90's computer typing vibe, set `AUDIO_CLICKY_FREQ_RANDOMNESS` to `1.0f` and enjoy.

**Comment by drashna** [comment]
lol, well, I'm using the same speaker that the planck uses, and it's fantastic. :)

And thanks!

**Comment by mtdjr** [comment]
This might not be the place for this but since the Travis build failed, I figured I'd ask here. Is there something different about the handwire directory compared to a regular keyboard directory? I had my handwire in the main keyboards directory but moved it to the handwire directory right before my commit and now it fails to compile. Moved it back and it works.

**Comment by drashna** [comment]
yeah, opening an issue would be a good idea.

And no, there shouldn't be a difference.  Though the error that it produces would be a big clue as to what is going on.

**Pull request merged**
