### PR TITLE
Fix held key getting stuck when NKRO is toggled

### PR DESCRIPTION
**Pull request by just-another-jxliu**
## Description

Fixes issue where if a key is held while NKRO mode is toggled, that key will be be continually active as if being held down even if the key is released.

Tested on CTRL, ALT, Rocketeer, and Planck Light.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Weird.

Also, there is `MAGIC_HOST_NKRO` and `MAGIC_UNHOST_NKRO` key codes that this should be added to, I think. 

However, this is called almost immediately after this happens, so I don't think that clearing it here is the right thing to do.  

Worst is that it looks like the logic is due to issues in `host_keyboard_send` in `tmk_core/common/host.c`. 

But thta seems to be only for mods.  Is this affecting mods or is it affecting everything?

**Comment by fauxpark** [comment]
I think something closer to a better solution would be along the lines of removing the `if` and `return` here:

https://github.com/qmk/qmk_firmware/blob/367eac22293ac148e19e545e110d5a591de1eb6e/tmk_core/common/report.c#L246-L256

**Comment by pschmuckal** [comment]
@fauxpark @drashna 

Yes.  I essentially called clear_keyboard() twice because of the the issue in clear_keys_from_report() which only clears one or the other fields depending on keymap_config.nkro.  This was the least risk solution.

Have no issue with fixing it in clear_keys_from_report(), but didn't analyse all possible implications of that change and wasn't confident it couldn't break something else.

Agreed that MAGIC_HOST_NKRO and MAGIC_UNHOST_NKR cases should do the same if we stick to this approach.

It definitely fixes the issue with Drop's keyboards.

**Comment by just-another-jxliu** [comment]
^ the change in this PR is from @pschmuckal . At the time that I created this PR, he didn't have write access to our QMK fork, so I went ahead and created the PR in his place.

**Comment by drashna** [comment]
It looks like there is a merge conflict on this PR, now.

**Comment by rishav142k** [comment]
I didn't quite understood the issue. Could you explain it a bit more?

**Comment by pschmuckal** [comment]
> 
> 
> I didn't quite understood the issue. Could you explain it a bit more?

@rishav142k As mentioned in the description, if you are pressing down keys at the time you make an NKRO switch, those keys will behave as still pressed even if you release them (keys stuck on auto-repeating).

**Comment by fauxpark** [comment]
@pschmuckal @just-another-jxliu still a merge conflict unfortunately, would you mind rebasing?

**Comment by pschmuckal** [comment]
Rebased.  Added buffer clear to MAGIC_HOST_NKRO and MAGIC_UNHOST_NKRO key codes as well.

Should be good to go.

**Comment by PrathamGoyal** [comment]
This issue is still labelled as open issue. Can I take this issue? I think I can help.

**Pull request merged**
