### PR TITLE
Initial draft of VIA QMK underglow integration

### PR DESCRIPTION
**Pull request by fcoury**
## Description

This branch piggybacks on Wilba’s idea of interacting with a keyboard specific API via the HID interface and ports it to a generic APIthat works with a new branch of VIA.

Even though this uses Wilba's implementation as reference, there are no overlaps or parts used from his implementation. The keymap APIs were copied over, at least for the time being.

I intentionally limited the scope of changes to a new keymap for the DZ60, isolating all changes on the `keyboards/dz60/keymaps/via_7u` path.

Ideally, once we validate this implementation, it could be extracted and reused to integrate any keyboards that use QMK underglow with VIA.

Here's a link to VIA's PR that uses this new API implementation:
https://github.com/olivia/via-config/pull/40

And here's an overview of the new VIA UI for this module:

via-qmk-underglow

## Types of changes

- [ ] Core
- [ ] Bugfix
- [x] New Feature
- [ ] Enhancement/Optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fcoury** [comment]
@Wilba6582 please review the changes I made to this PR and let me know if you see any conflicts with things you are working on. Thank you!

**Comment by fcoury** [comment]
Very sad to see all this work go to waste.

**Comment by Wilba6582** [comment]
It won't go to waste, these features will be integrated after the VIA refactor #7268 gets merged.

**Comment by fcoury** [comment]
@Wilba6582 that is great! I would love to get this to all the DZ60 owners, I think it's one of the most popular boards ever. Will keep my eyes peeled for this one.

Thanks!

**Comment by olivia** [comment]
@fcoury @Wilba6582 Now that #7268 is merged, how about reviving this? :)

**Comment by zvecr** [comment]
Implemented with #7911.

**Pull request closed without merging**
