### PR TITLE
Add sn74x165 parallel-in/serial out driver

### PR DESCRIPTION
**Pull request by luantty2**
## Description

Add 74HC165 driver running on SPI.

https://assets.nexperia.com/documents/data-sheet/74HC_HCT165.pdf

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Needs documentation.
Also not a true SPI device as it's not Hi-Z when "chip select" isn't asserted. Should probably make any documentation state as such.

**Comment by luantty2** [comment]
> Needs documentation. Also not a true SPI device as it's not Hi-Z when "chip select" isn't asserted. Should probably make any documentation state as such.

Documentation added.

**Comment by leah-splitkb** [comment]
As another shift register user, I am quite excited about this!

Personally, I think it might be useful to make it a little bit more generic so it can be used for any kind of SPI-attached shift register.

For example, a keyboard I am working on is using the SN74HCS165 with a tri-state buffer and a NOT-gate between `CS` and `SH/LD`, essentially turning it into a "real" SPI device.

Some feedback with this in mind:

- Make it possible to use one pin for both Chip Select and Latch, with configurable polarity.
- Do not make tri-state buffer `OE` or `CLK_INH` mandatory. Technically, neither is required to function, so why make it a requirement.

Also, consider the possibility of not reading the entire chain every time: often-read pins can be placed on the first registers in the chain, with occasionally-read ones on the later registers.

**Comment by sigprof** [comment]
Specifying `SPI_SLAVE_SELECT_PIN` is mandatory due to how the SPI driver in QMK works (at least for ChibiOS it expects `#define SPI_SELECT_MODE SPI_SELECT_MODE_PAD`, and the underlying ChibiOS code for that mode does not support a “no pin” value; in addition, the `spi_master` code uses `NO_PIN` as a special value meaning “SPI is not active”). Therefore even if the CS signal is not really used (because there is only one pseudo-SPI device that does not use CS), you need to allocate an otherwise unused GPIO for that purpose.

Maybe it could be possible to extend the QMK SPI API by supporting `NO_PIN` for CS to handle these special cases; this would require changing `halconf.h` to use `#define SPI_SELECT_MODE SPI_SELECT_MODE_NONE` and handling CS in `spi_master.c`, and also switching the `spi_master.c` code away from using `NO_PIN` for internal purposes.

**Comment by infinityis** [comment]
Recommend removing the SN part number prefix from the docs and defines, since SN prefix is exclusive to Texas Instruments parts and there are plenty of other manufacturers of 74x165

**Comment by fauxpark** [comment]
The functions cannot start with a digit.

**Pull request closed without merging**
