### PR TITLE
adding info.json for funky40

### PR DESCRIPTION
**Pull request by TheFourthCow**
adding info.json for funky40 and fixing some technical difficulties. Thanks noroadsleft!

## Adding info.json for funky40

- [ ] Core
- [X] Bugfix
- [X] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
Thanks!

New Instructions:

1. Hit the `Delete Branch` button on this page.
   Deletes the branch from GitHub.
2. Run `git fetch -p origin`.
   Updates the state of your local repository with the state of your GitHub fork, which in turn tells Git on your computer that this branch was deleted from GitHub.
3. Run `git branch -D funky40_info`.
   Deletes the branch from your computer. If it's the branch you have checked out, run `git checkout master` first.
4. Update your fork and your local repository by running:
   ```
   git checkout master       # changes your branch
   git pull upstream master  # downloads the changes from QMK's repository to your computer
   git push origin master    # uploads the changes on your computer to your fork of QMK Firmware
   ```

Any time you want to make further changes for a pull request, repeat Step 4, then run `git checkout -b <new branch name>` (without the brackets) before making your changes. This will make it easier to keep your QMK fork clean as well as make your pull requests easier to review in future.

Enjoy!

**Comment by TheFourthCow** [comment]
> 
> 
> Thanks!
> 
> New Instructions:
> 
>     1. Hit the `Delete Branch` button on this page.
>        Deletes the branch from GitHub.
> 
>     2. Run `git fetch -p origin`.
>        Updates the state of your local repository with the state of your GitHub fork, which in turn tells Git on your computer that this branch was deleted from GitHub.
> 
>     3. Run `git branch -D funky40_info`.
>        Deletes the branch from your computer. If it's the branch you have checked out, run `git checkout master` first.
> 
>     4. Update your fork and your local repository by running:
>        ```
>        git checkout master       # changes your branch
>        git pull upstream master  # downloads the changes from QMK's repository to your computer
>        git push origin master    # uploads the changes on your computer to your fork of QMK Firmware
>        ```
> 
> 
> Any time you want to make further changes for a pull request, repeat Step 4, then run `git checkout -b <new branch name>` (without the brackets) before making your changes. This will make it easier to keep your QMK fork clean as well as make your pull requests easier to review in future.
> 
> Enjoy!
I followed all the steps, was the info.json file what makes the board compatible with qmk configurator? I dont see the default keymap on that site or is that a different process. Thanks again for all the help!!

**Comment by noroadsleft** [comment]
> I followed all the steps, was the info.json file what makes the board compatible with qmk configurator? I dont see the default keymap on that site or is that a different process. Thanks again for all the help!!

Sorry for the late reply; I've been occupied with other QMK tasks of late.

QMK Configurator's default keymaps live [here](https://github.com/qmk/qmk_configurator/tree/master/public/keymaps) as JSON files. If you give me some time I can put a default on there (there are instructions out there but I need to update them).

**Comment by TheFourthCow** [comment]
Thanks for the reply, I'd love to learn to do it myself and I can try and follow the instructions but if you can do it whenever you have time I'd really appreciate it, thanks!

**Comment by noroadsleft** [comment]
> Thanks for the reply, I'd love to learn to do it myself and I can try and follow the instructions but if you can do it whenever you have time I'd really appreciate it, thanks!

The instructions for creating Configurator default keymaps are here: 

- [How to set the default layouts](https://github.com/qmk/qmk_configurator/issues/618#issuecomment-564955293)

The parts of that post that I need to document/update:

## You can't use `default` as the value for the `keymap` key

The Configurator's API was recently updated, and this is no longer true. Go ahead and use `default` as the value for `keymap`.

## Configurator's UI code only understand one variant of each supported keycode

Also no longer true as of qmk/qmk_configurator#717. Use whichever variant of the supported keycode you like. I personally find the short, seven-characters-or-less variants easier to read, and prefer `_______` to `KC_TRNS` and `XXXXXXX` to `KC_NO`, but it no longer makes any difference to Configurator.

**Pull request merged**
