### PR TITLE
Add leader enter mode.

### PR DESCRIPTION
**Pull request by kdb424**
Continuation of failed PR from before. https://github.com/qmk/qmk_firmware/pull/3744
Git is obviously not my strong suit. I've also added a change that makes this ARM compatible, as negative numbers on arm wrap at least in the case used before.

@drashna @jackhumbert @klardotsh Sorry for the issues on the last one.

### CODE REVIEW

**Comment by kdb424** [comment]
This is is a branch with the wrong name, but the description is correct funny enough. Whoops. Hope your checks go well. I have a Planck and several AVR beards to test changes but this works on all of them without flaws that I could find at the moment.

**Comment by kdb424** [comment]
Botched it again. No leader mode enter for you.

**Comment by drashna** [comment]
Would you mind addid the unicode function as a separate thing? 

Also, I think that unicode common may not be the best place for it, since it looks/sounds like it only really supports the UNICODE_ENABLE option (and looks to be designed to go up to 0xFFFF, and not higher). 

And if that is the case, then it would best belong in https://github.com/qmk/qmk_firmware/blob/master/quantum/process_keycode/process_unicode.c

**Comment by kdb424** [comment]
Makes sense. If someone else wants to push these changes upstream from my branch, they are welcome to. I haven't been able to keep a branch clean for long enough to make it in. I'll comply with the GPL and keep the code in my fork, but alas, can not manage to get it upstream.

**Pull request closed without merging**
