### PR TITLE
optimize source code for size. reduce compiled binary size 292 bytes

### PR DESCRIPTION
**Pull request by bottilabo**
optimize crkbd/ssd1306.c for size. reduce compiled binary size 292 bytes
 

## Description
optimize crkbd/ssd1306.c for size. reduce compiled binary size 292 bytes

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
I don't think that there is much of a point of doing this. Switching to OLED Driver offers more functionality, and I believe is smaller, to boot. 

Ideally, that's what the corne and other boards should be moving to, and what code should be optimized.  

But I'm glad to see the attempt at optimization, here!

**Comment by bottilabo** [comment]
I'm using big Bottilabo layout library, so I'm always suffering from lacking memory. And I've not known about oled driver.c. Next time I'm going to use oled driver. For now, I hope this optimization helps legacy source.

**Comment by bottilabo** [comment]
I made a further optimization and I gave it a try to compare the binary sizes. One is using oled_driver.c and another is my optimized SSD1306.c. Base source code is using oled_driver.c and I ported to SSD1306.c.
The result is using optimized SSD1306.c is smaller than using oled_driver.c 778 bytes.

**Comment by tzarc** [comment]
CI issues look like old keymaps that haven't been updated, default keymap is fine.

**Pull request merged**
