### PR TITLE
[develop] Fix builds broken by #12240

### PR DESCRIPTION
**Pull request by daskygit**
## Description

Add avr/timer_avr.h as an include to the matrix.c files. This is a quick fix and I guess they all could do with reworking properly.
 
I've added the include above "hhkb_avr.h" as it's required in that header.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by shelaf** [comment]
I think this PR should be merged into the master branch.

**Comment by fauxpark** [comment]
`develop` will be merged into `master` at the end of the month anyway: https://docs.qmk.fm/#/breaking_changes?id=when-is-the-next-breaking-change

**Comment by shelaf** [comment]
I understand everything...
I found out that the same fix as #12240 was made in #13675, so I will open another PR that does the same patch.

**Comment by shelaf** [comment]
cf. #14072

**Comment by fauxpark** [comment]
My point was that it may just be worth waiting it out, since the merge date is in just over a week.

**Comment by shelaf** [comment]
Oh sure. I will wait for the merge.

**Pull request merged**
