### PR TITLE
Rename ledmatrix.h to match .c file

### PR DESCRIPTION
**Pull request by fauxpark**
## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Maxr1998** [comment]
Not sure, but could it be that this file was named that way to avoid conflicts with the `led_matrix.h` provided by tmk (`/tmk_core/protocol/arm_atsam/led_matrix.h`)? I see some keyboard specifically importing that one. I think we have to rename ours to `qmk_led_matrix.h` or something like that.

**Comment by fauxpark** [comment]
That would certainly explain the giant errors Travis is giving for the Drop boards... argh. I would rather rename the ATSAM one, TBH. The QMK LED matrix feature is meant to be closely related to the RGB matrix feature, and you can see the similarities between led_matrix.[ch] and rgb_matrix.[ch].

**Comment by Maxr1998** [comment]
That's also certainly be possible, but would also require some changes to the keyboard configs. But nothing a grep & sed couldn't fix ;)

**Comment by skullydazed** [comment]
> I would rather rename the ATSAM one, TBH.

I would too, but it was something I didn't have the cycles for at the time. So I went with `ledmatrix.h` instead for the time being.

**Comment by ridingqwerty** [comment]
> As I wrote above, I think we should first rename the existing `led_matrix.h` in tmk.

I missed the clarifying discussion.  Agree with putting this on hold.

**Comment by fauxpark** [comment]
Taking this off hold, will move to develop for next cycle.

**Review by noroadsleft — APPROVED** [review]

**Pull request merged**
