### PR TITLE
QMK Configurator updates for Atreus62

### PR DESCRIPTION
**Pull request by noroadsleft**
- Add `info.json` file
- Change `<keyboard>.h` to `QMK_KEYBOARD_H`
- Update `KEYMAP` to `LAYOUT` throughout
- Partial coding convention updates

Someday I'll figure out why my previous merged commits are staying glued to my new PRs; it's driving me nuts. My syncing method has gotta be wrong somewhere.

### CODE REVIEW

**Comment by noroadsleft** [comment]
Closing this PR because it's holding up my workflow.

Still working on best practices for keeping my master up-to-date and managing my local files, my github master and my working branch.

**Comment by drashna** [comment]
best bet?  Never use your master.  Keep it up to date, but never use it.  

You want to modify something to send a PR?  make a new branch based on the master, and then issue a PR.  Delete it when done.  Repeat as necessary.  

It's what I do, and it helps a lot.

**Comment by drashna** [comment]
Yup, exactly.

**Comment by noroadsleft** [comment]
> And rebasing rather than merging

Lost me here. When do I rebase? I'm not sure what that command does.

**Pull request closed without merging**
