### PR TITLE
Remove CUSTOM_MATRIX option from diode direction

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Discussion within #5026

There seems to be an existing comment, both within the docs, templates and code base,

```c++
/* COL2ROW, ROW2COL, or CUSTOM_MATRIX */
#define DIODE_DIRECTION CUSTOM_MATRIX
```

However digging into the implementation, it currently does not do much. Currently if you set the documented option (both in the existing template and online docs) `DIODE_DIRECTION = CUSTOM_MATRIX` you end up with a matrix.c being included that will not function at all, and no clean way to implement anything that fixes that.

This PR removes the option, via find replace. In a future PR (or maybe this one if requested), functionality will be added to provide warnings or messages when the above 'broken matrix.c' is encountered.

## Types of changes

- [x] Core
- [x] Bugfix
- [ ] New Feature
- [ ] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* #5026

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
There is a merge conflict. :(

**Comment by zvecr** [comment]
@drashna thanks for the heads up, I will fix the issue ASAP.

The merge conflict has at least flagged with me, that this will need a 2nd pass in the future for any boards added against the previous code base.

**Comment by drashna** [comment]
Well, I'll try to catch the text in future PRs. Can't make any promises though. 

And either still a merge conflict or another has popped up.

**Comment by zvecr** [comment]
@drashna was another commit, i have updated again to reflect the current state of master.

**Comment by zvecr** [comment]
Thanks @drashna, i will schedule a 2nd pass for any that slip through.

**Pull request merged**
