### PR TITLE
rename idobo to idobao/id75, move to vendor folder

### PR DESCRIPTION
**Pull request by peepeetee**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* #15658

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by peepeetee** [comment]
@vinorodrigues let's continue the discussion in #14468 here

Previously: https://github.com/qmk/qmk_firmware/pull/14468#issuecomment-920940474

**Comment by peepeetee** [comment]
The question here is weather
https://drop.com/buy/id75-hot-swappable-ortholinear-keyboard-kit
https://drop.com/buy/xd75-aluminum-mechanical-keyboard
https://idobao.net/collections/60-layout/products/idobao-id75v1-hot-swappable-mechanical-keyboard-kit

Are the same thing. 


On the idobao site, we have this:
image
Which points, well, here. 

In the first drop link, we have this:
https://drop.com/buy/xd75-aluminum-mechanical-keyboard/reviews/2493503?utm_source=linkshare&referer=F9X53K

And the buying link in the readme.md says https://drop.com/buy/id75-hot-swappable-ortholinear-keyboard-kit

Thus I have concluded that these 3 links are the same board, and are made by IDOBAO by merit of the first link

**Comment by vinorodrigues** [comment]
Have a look at the 3 kb's you provided links to above.  Specifically the side profile.  The 2x DROP's are flat ... i.e. top of case and bottom of case are equal in height, where as the Idobao is angled ... i.e. bottom is lower than top.  These boards are not the same.  They may well share the same PCB, but the code on QMK is specifically for the DROP variant (your first link).

Moving this to the Idabao folder will cause confusion with the 330 users out there that will look for it in its original location, or at the very least a Drop vendor folder.

**Comment by sigprof** [comment]
IDOBAO sells the flat variant too, although apparently only on AliExpress:
https://www.aliexpress.com/item/4000378394653.html
I don't really understand what is happening here.

**Comment by peepeetee** [comment]
> Have a look at the 3 kb's you provided links to above. Specifically the side profile. The 2x DROP's are flat ... i.e. top of case and bottom of case are equal in height, where as the Idobao is angled ... i.e. bottom is lower than top. These boards are not the same. They may well share the same PCB, but the code on QMK is specifically for the DROP variant (your first link).
> 
> Moving this to the Idabao folder will cause confusion with the 330 users out there that will look for it in its original location, or at the very least a Drop vendor folder.

image
from the idobao server
We have aliases for keyboard compilation, we'll just alias idobo to idobao/id75

**Comment by vinorodrigues** [comment]
> from the idobao server

good to go then :)

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Pull request merged**
