### PR TITLE
update keyboard soda/mango vid

### PR DESCRIPTION
**Pull request by gezhaoyou**
## Description
update keyboard soda/mango vid, I need this vid.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Cipulot** [comment]
The VID you're trying to get is already in use by Oestling Markiersysteme GmbH.
https://www.the-sz.com/products/usbid/index.php?v=0x1A54&p=&n=

**Review by zvecr — CHANGES_REQUESTED** [review]
[0x1A54](https://the-sz.com/products/usbid/index.php?v=0x1A54&p=&n=) is already allocated so you cant really squat on it.

**Comment by gezhaoyou** [comment]
Ok, I know, this pr close

**Comment by drashna** [comment]
Closing the PR isn't necessary.  However, anything below 0x3500 is generally assigned or actively being assigned.   

Ideally, you want to head to pid.codes and get a PID from them and use their vendor ID, head to the MCU's producer and see if you can do the same there (eg, Microchip for avr controllers), or use a vendor ID that is unused.  The further past 0x4000, the better, as these are less likely to be assigned in the near future.  Eg `0xAA54` would be a good option, as that is probably centuries off, at the current rate of assignment.

**Comment by gezhaoyou** [comment]
What should I do next? Should I reopen this PR?

**Pull request closed without merging**
