### PR TITLE
Make sequencer keycodes static (#11156)

### PR DESCRIPTION
**Pull request by rbelouin**
## Description

This pull request is an attempt to rewrite the `sequencer` feature in a way that makes the QMK framework compatible with VIA (as suggested by @fauxpark in #11156).

Instead of assigning one keycode to each possible resolution, step, and track; it lets the user create a layout where each entry is a `uint32_t` combining a `uint16_t` keycode and a `uint16_t` index. This keeps the keycode enumeration simple and static, while keeping the possibility for end users to declare a rich sequencer layout.

You can see these changes in action on my personal branch: https://github.com/rbelouin/qmk_firmware/blob/rbelouin/keyboards/planck/keymaps/rbelouin/keymap.c#L27-L31

So far, I’ve only created the `sequencer_get_keycodes_48` and `sequencer_get_indices_48` macros to satisfy my needs with my Planck EZ. I’m curious to know your opinion on whether this is the right way to go, and whether I should decline these macros for other keyboards too (and if there’s a way to automate this somehow).

I can probably add some tests to cover the macro, if you believe this is useful.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* #11156

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by fauxpark** [comment]
I don't think this implementation would play well with VIA or the Configurator. I would rather there just be a fixed set of keycodes to control these.

**Comment by zvecr** [comment]
I agree with fauxpark. Plus having to add macros specific to number of keys in core is just messy, and I would argue worse than the current implementation.

**Comment by rbelouin** [comment]
Thanks for your feedback. I agree, the macro is definitely introducing some messiness. I don’t know a lot about macros and was hoping someone would suggest a more generic way to write something equivalent.

My understanding of the issue was that there were too many keycodes allocated to the `sequencer` features; which this PR is trying to solve by using keycodes for sequencer _functions_ only, and encoding indices somewhere else. But it seems that I’m wrong again?

Unless you tweak `SEQUENCER_STEPS`, `SEQUENCER_TRACKS`, or the `sequencer_resolution_t` enumeration locally; the keycode range allocated by the sequencer is static. So in what way is it not compatible with VIA or the Configurator? Does `quantum/quantum_keycodes.h` need to be statically analyzable or something? The cons of having a named keycode for each resolution/step/track is that it will make the file more verbose, more error-prone, and less-easily configurable locally. What are the advantages that I seem to be missing?

**Comment by rbelouin** [comment]
I will close this pull request, and maybe we can keep discussing the problem on the #11156 thread.

**Pull request closed without merging**
