### PR TITLE
add color byte selection for tft screen

### PR DESCRIPTION
**Pull request by jiaxin96**
## Description

Add support for color byte order selection of TFT Display Screen.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
This needs to be done without preprocessor, using runtime configuration.
There's no guarantee that all screens are RGB or BGR on a multi-screen setup.

**Comment by jiaxin96** [comment]
> This needs to be done without preprocessor, using runtime configuration. There's no guarantee that all screens are RGB or BGR on a multi-screen setup.

Should it be placed in the initialization code?

**Comment by tzarc** [comment]
> Should it be placed in the initialization code?

It'd be another parameter to the `qp_make_xxxxxx` functions, stored within the configuration struct, then checked during init etc.

**Comment by jiaxin96** [comment]
> 
But in this case, qp_ tft_ panel_ append_ pixels_rgb565/888 function will be difficult to obtain the byte order parameter.

In fact, I have tested on st7735 and st7789 , which show that both byte orders can work well, so multi-TFT-screens can also unify byte order in one case.

**Comment by tzarc** [comment]
A cleaner solution would be to supply a different vtable with a different conversion function. The resulting code will be smaller.

**Comment by tzarc** [comment]
No indication this is being worked on, have added to my todo list.

**Pull request closed without merging**
