### PR TITLE
[WIP] New DIY keyboard similar to Ergodox Infinity

### PR DESCRIPTION
**Pull request by sballano**
Required firmware changes to make a hand wired keyboard using the Teensy 3.2 controller. The keyboard is very similar to the Ergodox Infinity but with a 3d printed case and without requiring PCB. It uses an OLED screen based on the SSD1306 driver so support for that type of display has been added.

The main part of the changes are on:
https://github.com/sballano/qmk_firmware/tree/master/keyboards/ergodox_expanse
and:
https://github.com/sballano/qmk_firmware/tree/master/drivers/ugfx/gdisp/ssd1306

The code for the display is not written by me, its from:
https://github.com/goeck/SSD1306

The hardware files for the 3D printed case and hand-wiring instructions are located on:
https://github.com/sballano/ergodox_expanse 

As with the Infinity, it uses one controller in each half, so each can be connected to the computer independently or together with a serial connection between them.

### CODE REVIEW

**Comment by drashna** [comment]
Was this ready to be pulled? Eg, are you still working on this?

**Comment by sballano** [comment]
Sorry for the long time without updating. I just have a bug that I can't find, I don't know if I could get help on this or if it would be acceptable to be pulled with this bug. Everything works fine except the gdispGBlitArea function from the ugfx library doesn't work correctly, this makes the logo to not show correctly during power up. After that, the OLED works fine...

**Comment by drashna** [comment]
Not a problem.  I've been going through all of the Issues and PR's to clean stuff up. 
Sounds like it's mostly ready to go (other than the logo issue/bug). 

I'll let jack or skully decide if this should be merged or not, though.

**Comment by drashna** [comment]
Any update on this?

**Comment by sballano** [comment]
No, sorry, I have not been able to work on this lately, maybe is best to close it and I will request again in case I find the issue I had with the display

**Pull request closed without merging**
