### PR TITLE
Generalizing functionality of `ACTION_TAP_DANCE_DUAL_ROLE`

### PR DESCRIPTION
**Pull request by burchill**
Long story short: the old `ACTION_TAP_DANCE_DUAL_ROLE` turns on a layer by using `layer_move`.  I want to use tap dance to toggle layers without turning off other ones. Instead of writing a new `ACTION_TAP_DANCE_TOGGLE_LAYER` with its own version of `qk_tap_dance_dual_role_finished()`, I decided it would be more economical--as well as allowing for greater flexibility in future code--to make it so that multiple variations on `ACTION_TAP_DANCE_DUAL_ROLE` could be written utilizing the same underlying functions.

Instead of writing a new version of something like `qk_tap_dance_toggle_layer_finished()`, I changed the structure of `qk_tap_dance_dual_role_t` to include a function as an additional argument, and changed `qk_tap_dance_dual_role_finished()` so that it would apply that function to the layer.

This also allows future developers to more easily implement things such as creating tap dance functions that will only turn layers *on*, etc.

### CODE REVIEW

**Comment by burchill** [comment]
Potentially this means the

**Comment by burchill** [comment]
Oops, accidentally closed it!

**Comment by jackhumbert** [comment]
@algernon if you have the chance to check this out, I'd be happy to hear your thoughts :)

**Comment by algernon** [comment]
Oooh, this look sweet. Good thinking, good code, and shouldn't break existing user code either.

:+1: :shipit:

**Comment by drashna** [comment]
Looks like there is a merge conflict here, now.

If you could fix that?

**Comment by burchill** [comment]
Ah crap, sorry about that!  Your notification in September must have gotten buried in my inbox! I've been away from the QMK/keyboard world for about a year now though (grad school), so I'm not sure how useful I'd be.

**Comment by drashna** [comment]
One last thing, sorry!

Could `ACTION_TAP_DANCE_TOGGLE_LAYER` be added to the docs for tap dance?

**Comment by drashna** [comment]
Have you had a chance to update this PR?

**Comment by drashna** [comment]
@burchill Could you add documentation for this?

**Comment by drashna** [comment]
Any updates to this?

**Comment by burchill** [comment]
Guys I'm pretty much out the game. This was a very small optimization I made almost two years ago. I no longer remember much about it and I don't really know how documentation is done for this project. 
If you point me to examples of how documentation works in the code (i.e., for similar functions) I can probably whip up something in a similar style if I don't need to build / compile anything new. Otherwise you're probably better off doing it yourselves. Sorry about that!

**Comment by drashna** [comment]
No worries! 

And specifically, the change looks to add support for other layer functions, and specifically "layer_invert" which just toggles the layer (like the "TG" keycode).

**Comment by drashna** [comment]
If you don't mind, I think I may close this, work on it a bit to get it up to stuff, and re-submit it, that way we can get it merged in.

**Comment by drashna** [comment]
I've opened an updated version of this PR, with a fix and documentation, while maintaining credit for the original code change. 

I'm closing this PR, since the other is more up to date.

**Pull request closed without merging**
