### PR TITLE
draytronics/scarlet: fix info.json data

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

Fixing:

image

cc @ghostseven (keyboard maintainer)

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Review by ghostseven — APPROVED** [review]

**Comment by ghostseven** [comment]
Just realised is this a duplicate of my PR for fixing the layout issue? I submitted one about 10 mins before?

**Comment by ghostseven** [comment]
I had assumed this change was in relation to this, but I wonder if it was just dumb luck we both submitted?

**Review by zvecr — APPROVED** [review]

**Comment by ghostseven** [comment]
Ok so both changes this and my pull for the same thing have been approved, so how does that work?

**Comment by noroadsleft** [comment]
> Just realised is this a duplicate of my PR for fixing the layout issue? I submitted one about 10 mins before?
> 
> I had assumed this change was in relation to this, but I wonder if it was just dumb luck we both submitted?

Ha, totally dumb luck. I spent a couple days this week adding default keymaps to Configurator, and the Scarlet was one of the boards that is getting a keymap. I noticed the layout data was wrong, so after I posted the Configurator PR, I started going through the boards that I found needing their Configurator data updated, and this was one of them. I never actually saw your PR until just now.

#10744 was closed for duplicate/conflict – this getting merged would've made that PR unmergeable – but #10747 plays nice with this, so I'll merge that.

**Pull request merged**
