### PR TITLE
Expand count checks in keymap introspection

### PR DESCRIPTION
**Pull request by drashna**
## Description

Checks the count for tap dance to ensure it's not exceeding the max (0xFF), and to provide a more meaningful error when it is misconfigured.

The message is ... meh.  But have verified that it works.

based on master, so can retarget to that, if needed.
## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] Enhancement/optimization

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Should we do the same thing for others like combos and unicode(map)?

**Comment by drashna** [comment]
> Should we do the same thing for others like combos and unicode(map)?

It would probably be a good idea, yeah.

**Comment by drashna** [comment]
Combos and key overrides aren't limited by anything, other than memory usage. And unicode map/ucis look to be the same.  So any limit would be arbirary... and probably would need to cater to AVR.

**Comment by tzarc** [comment]
The likelihood of any of the arrays being `QK_KB` or `0x7E00` in length is extremely unlikely — perhaps a check against that value?

**Comment by drashna** [comment]
Well, AVR isn't a worry for combos as the max array size errors out before the static assert even gets triggered. But not by much (0x7FFF). So using `QK_KB` feels reasonable.

And for the others, checking against `QK_KB` for key overrides feels reasonable, as well.

Both cases, yeah, it should catch the "safe range" stuff.

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Probably low risk to go to `master.

**Pull request merged**
