### PR TITLE
Custom DZ60 Layout

### PR DESCRIPTION
**Pull request by arickho**

### CODE REVIEW

**Comment by arickho** [comment]
Not ready

**Comment by drashna** [comment]
For the layer RGB stuff, you may want to look at this: 
https://docs.qmk.fm/custom_quantum_functions.html#layer-change-code

Also, in https://docs.qmk.fm/feature_rgblight.html, it mentions:
* rgblight_setrgb_at(r,g,b, LED);
* rgblight_sethsv_at(h,s,v, LED); 

Which may be what you want here, too.

**Comment by arickho** [comment]
Amazing! thank you.

**Comment by drashna** [comment]
You're very welcome!

**Pull request closed without merging**
