### PR TITLE
Add function to allow repeated blinking of one layer

### PR DESCRIPTION
**Pull request by matthesinator**
## Description
Added the functions `rgblight_blink_layer_repeat` and `rgblight_blink_layer_repeat_helper`. When `rgblight_blink_layer_repeat` is called, it stores the number of repeats in a counter which is decremented every time a layer is turned on again. `rgblight_blink_layer_repeat_helper` is called after `rgblight_unblink_layers` to check if a lighting layer needs to be enabled again. Both functions call `rgblight_blink_layer` to turn on a layer.

## Types of Changes

- [x] New feature
- [ ] Core
- [ ] Bugfix
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by spidey3 — CHANGES_REQUESTED** [review]
I am uncomfortable with the behavior of `rgblight_blink_layer()` being changed by side effects (global variables not in the argument list).

Please update the implementation so that all of the blink functionality (including the repeat) is located in `rgblight_blink_layer_repeat()`; then `rgblight_blink_layer()` can just be a macro that expands to `rgblight_blink_layer_repeat(layer, duration_ms, 1)`.

**Comment by matthesinator** [comment]
> Please update the implementation so that all of the blink functionality (including the repeat) is located in `rgblight_blink_layer_repeat()`; then `rgblight_blink_layer()` can just be a macro that expands to `rgblight_blink_layer_repeat(layer, duration_ms, 1)`.

Done. I hope this works, considering my C knowledge

**Comment by spidey3** [comment]
One thought - do you really need both `_repeating_layer_mask` and `_blinked_layer_mask`?  I wonder if it could be implemented more simply without the two separate masks. `_times_remaining` could start out as `2 * times`; then even values would mean ON and odd values would mean OFF. I think that would reduce the amount of code needed.

I ask this because adding your code increases the overall firmware size by almost 300 bytes - which is a pretty significant amount for some boards...

**Comment by matthesinator** [comment]
Done. This time I'm not sure if the changes in line 777 are correct, haven't touched that before

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
> spidey3 I did some edits but github still shows "changes requested", how do I change that status?

That's fine.  That doesn't change, until the person requesting changes re-reviews the PR.  It's weird quirk of github.

**Review by spidey3 — APPROVED** [review]
Sorry about the delay reviewing this; I've been offline for a while, but I'm back now!

**Pull request merged**
