### PR TITLE
Update keycodes.md

### PR DESCRIPTION
**Pull request by nblyumberg**
Looks like there were a few typos in the keycodes table with extra _

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
This is intentional, the recommended volume keys are here: https://docs.qmk.fm/#/keycodes_basic?id=media-keys
Because as you can see in the full list, the ones with double underscores do not work on Windows.

**Comment by nblyumberg** [comment]
> This is intentional, the recommended volume keys are here: https://docs.qmk.fm/#/keycodes_basic?id=media-keys
> Because as you can see in the full list, the ones with double underscores do not work on Windows.

I believe the double underscore ones are Mac specific? If so, would it make more sense to make it more obvious like KC_MAC**** or something?

**Comment by fauxpark** [comment]
They work on Linux too. Keycodes `0x7F` to `0x81` here: https://elixir.bootlin.com/linux/v3.4/source/drivers/hid/hid-input.c#L47
are set to `KEY_MUTE`, `KEY_VOLUMEUP` and `KEY_VOLUMEDOWN` here: https://elixir.bootlin.com/linux/v3.4/source/include/linux/input.h#L323

But since they don't work on Windows for whatever reason, we recommend the use of the media key ones. I added the OS support matrix to the keycode list specifically to clear up this confusion.

**Comment by nblyumberg** [comment]
> They work on Linux too. Keycodes `0x7F` to `0x81` here: https://elixir.bootlin.com/linux/v3.4/source/drivers/hid/hid-input.c#L47
> are set to `KEY_MUTE`, `KEY_VOLUMEUP` and `KEY_VOLUMEDOWN` here: https://elixir.bootlin.com/linux/v3.4/source/include/linux/input.h#L323
> 
> But since they don't work on Windows for whatever reason, we recommend the use of the media key ones. I added the OS support matrix to the keycode list specifically to clear up this confusion.

Gotcha, thank you for clarifying that!

**Comment by wcdawn** [comment]
None of these macros seem to be recognized on my Linux installation. I've opened #12210 to try to address this. Is there any additional info you can provide?

**Comment by fauxpark** [comment]
@wcdawn as far as I can tell the Linux kernel maps the volume keycodes on the Keyboard/Keypad page (the ones in the diff here) to the internal Linux volume event codes, same as the ones on the Consumer page (the ones we recommend using instead, because they work on the Big Three):

The event code definitions:
https://github.com/torvalds/linux/blob/b76f733c3ff83089cf1e3f9ae233533649f999b3/include/uapi/linux/input-event-codes.h#L188-L190

Keyboard page mappings (0x7F-0x81):
https://github.com/torvalds/linux/blob/master/drivers/hid/hid-input.c#L35-L36

Consumer page mappings:
https://github.com/torvalds/linux/blob/master/drivers/hid/hid-input.c#L967-L970

So, there should be no difference as far as XF86 is concerned - I can only guess that you don't have `EXTRAKEY_ENABLE = yes` in your rules.mk.

**Comment by wcdawn** [comment]
@fauxpark Thank you so much for taking a look at this! I was able to solve my problem. I did have `EXTRAKEY_ENABLE = yes` in `rules.mk`. I'm not exactly sure what but something in my configuration was "stealing" the keystroke before it could be interpreted by X11. I was able to reset all the defaults. I've documented this in my original issue so hopefully someone else will be able to find this in the future. Thanks again!

**Pull request closed without merging**
