### PR TITLE
Adding my xd60 layout.

### PR DESCRIPTION
**Pull request by JeanOlivier**
The layout I use with my xd60.

I'm not sure how to remove the commit that's only a merge with the main repository from the PR, or if it's even necessary.

Thank you.

**EDIT**: I see that the automated test has failed on cheese's layout because of an option I need in rules.mk, namely `TAP_DANCE_ENABLE = yes`. 

How can I fix it so that this option is only enable for my layout?

Thank you!

### CODE REVIEW

**Comment by drashna** [comment]
You shouldn't edit the `rules.mk` in the keyboard's directory.  Just add one in the keymap folder and it will overwrite the settings.

eg:
https://github.com/qmk/qmk_firmware/blob/master/keyboards/ergodox_ez/keymaps/drashna/rules.mk

**Comment by JeanOlivier** [comment]
It now passes the test. Please tell me if anything further needs to be done.

Thank you.

**Comment by drashna** [comment]
I don't really see a problem. 
Though, it may be best to move the tapping term into a config.h in your keymap (this also overrides values). 
Generally, you never want to modify the main files, if you have other options, because this affects things for all users of that board.  So, whenever possible, ... well, the keymap supports the rules.mk and config.h in a local keymap, and those should be used. 

Eg: 
https://github.com/qmk/qmk_firmware/blob/master/keyboards/ergodox_ez/keymaps/drashna/config.h#L1

As

**Comment by JeanOlivier** [comment]
Thanks for the input. Better practices are better, so I modified my code. 
The only modification to common xd60 files is an aesthetic alignment of a comment in rules.mk.

Thank you very much!

**Comment by jackhumbert** [comment]
Awesome! Thanks :)

**Pull request merged**
