### PR TITLE
Action: Add build workflow

### PR DESCRIPTION
**Pull request by luigi311**
Signed-off-by: Luigi311 <luigi311.lg@gmail.com>

## Description

Adds a build workflow to allow users to build their keyboard firmware on Github action so they do not need to install docker or set up a build environment. The new fetch upstream feature on GitHub web will also allow users to update their firmware once their branch is set up.

Users would navigate to the .github/workflow/build.yml file and replace the matrix with the firmwares they would want to build. In my case I would be building handwired/stream_cheap/2x4:default so my matrix would be 
```
    matrix:
        keyboard:
          - handwired/stream_cheap/2x4
        keymap:
          - default
```

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [X] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by luigi311** [comment]
I am unsure where to place the documentation explaining to users how to utilize this feature.  

It might be best to include the information in the qmk documentation website under the build your first firmware and the development enviornments sections

**Comment by drashna** [comment]
Docs should probably be added to:
https://github.com/qmk/qmk_firmware/blob/master/docs/newbs_getting_started.md

However, the only issue I have with this, is that ... if people want to PR to QMK, this file will be constant modified by everyone that uses.

**Comment by luigi311** [comment]
Thats what i was worried about too. Looking at githubs documentation there doesnt seem to be a way to ignore files from being included in a PR. They talk about deleting a file in a PR here https://github.blog/changelog/2018-07-31-removing-files-from-a-pull-request/ but i do not know if that will try to do a delete for the merge and delete the file on the master branch. 

With that being said i do not really envision this being used all that much by developers submitting PR but it is something that will need to be checked and added to the contribution guide too. I mostly envision this with users that do not want/know how to setup an environment but can follow the guide on changing it to match what they want to build.

**Comment by drashna** [comment]
That would delete the file in the repo, not just from the pull request.  

Sadly, this is one of the areas that gitlab really does have github beat.

**Comment by sigprof** [comment]
There are some ways to modify the behavior of a GitHub workflow without actually modifying its file, but they are not 100% ideal:

1) You can use `on: workflow_dispatch` to run the workflow manually, and add `inputs:` — then you can enter some string arguments before running the workflow. The downside is that the values of those arguments are not remembered by GitHub (only the browser input history could help here), and running the workflow needs multiple clicks; this also does not do anything for automatic builds triggered by pushes.

2) You can abuse secrets to pass some string parameters to the workflow. A major downside is that GitHub then censors the log output by redacting any substrings which match the values of those secrets, and this might make debugging harder.

3) The workflow parameters can be stored in a separate branch. The first job of the workflow could checkout that branch, read the parameter values from there, then output them in the JSON format; then the next job could have something like `matrix: ${{fromJSON(needs.setup.outputs.matrix)}}` to use these values as the matrix config. The workflow file itself still needs to live in the same branch as the code in order to be triggered by a push, but it should never be modified by the user.

**Comment by caksoylar** [comment]
Is there a reason not to use `container: qmkfm/qmk_cli` under `build:`, rather than calling `util/docker_build.sh`? I had rolled my own hacky version by looking at QMK's existing workflows using that; I am curious if I should not be using the container directly.

**Comment by luigi311** [comment]
You can use the container feature of github action but if the configuration for building via the docker image changes for some reason it would need to be updated in both the docker_build.sh and the action with the new steps. Using the bash script also has the benefit of also testing any changes made to the bash script so it would be guaranteed that there are not breaking changes made so people can continue to use it to build locally.

**Comment by luigi311** [comment]
@sigprof 
After thinking about it I think the best way to handle this would instead be to have this live outside of the qmk repo. Create a qmk config build repo that will clone this and then build according to how you wish. I will need to add the ability to overwrite all files based on your config and run any bash scripts as needed. This would allow us to make it so people can just fork that repo and make any changes as needed without worrying about people trying to constantly merge in changes to that action as we can just easily deny them over there.

**Pull request closed without merging**
