### PR TITLE
Allow for overriding clocks on F4xx.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

Allows for overriding clocks for F4xx, if using the blackpill base.
CC @Gondolindrim 

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Gondolindrim** [comment]
Perfect. This has been tested on a Mode SixtyFive M65S PCB and works fine.

**Review by drashna — APPROVED** [review]

**Comment by sigprof** [comment]
Actually it was possible to override `STM32_HSECLK` even without this change, if the override was placed in `board.h`:
```c
#pragma once
#include_next <board.h>
#undef STM32_HSECLK
#define STM32_HSECLK 8000000U
```
What is the place for such overrides in general — a `board.h` overlay like that, or `config.h` (which depends on the fact that `board.h` files from ChibiOS have `#ifndef` checks for these defines)?

And the fact that `config.h` inside the board directory is included after all other `config.h` files was somewhat unexpected — should this ChibiOS-specific behavior be documented in https://github.com/qmk/qmk_firmware/blob/master/docs/hardware_keyboard_guidelines.md#configh ?

**Comment by Gondolindrim** [comment]
> Actually it was possible to override `STM32_HSECLK` even without this change, if the override was placed in `board.h`:
> 
> ```c
> #pragma once
> #include_next <board.h>
> #undef STM32_HSECLK
> #define STM32_HSECLK 8000000U
> ```
> 
> What is the place for such overrides in general — a `board.h` overlay like that, or `config.h` (which depends on the fact that `board.h` files from ChibiOS have `#ifndef` checks for these defines)?
> 
> And the fact that `config.h` inside the board directory is included after all other `config.h` files was somewhat unexpected — should this ChibiOS-specific behavior be documented in https://github.com/qmk/qmk_firmware/blob/master/docs/hardware_keyboard_guidelines.md#configh ?

Unfortunately that is not only it -- the PLL frequency M, N, P and Q multipliers should also be tuned.

**Comment by sigprof** [comment]
> Unfortunately that is not only it -- the PLL frequency M, N, P and Q multipliers should also be tuned.

Yes, but they are defined in `mcuconf.h`, and overriding any defines from there is not a problem. The issue solved by this PR is that someone chose to set `STM32_HSECLK` for blackpill boards in `config.h`, even if the ChibiOS code defines it in `board.h`, and that particular `config.h` gets included after the keyboard level `config.h`, so it was not possible to override that value by adding something to a file with the same name. I just wonder whether putting such overrides in `config.h` is now a preferred way, or it was left just for these boards to avoid breaking some existing code.

**Pull request merged**
