### PR TITLE
Add visualizer support for Infinity60

### PR DESCRIPTION
**Pull request by fredizzimo**
This adds visualizer support for LED backlights on the Infinity60 keyboard. It's still possible to use the old backlight system by specifying `LED_CONTROLLER_ENABLE=yes` instead of `VISUALIZER_ENABLE=yes` and `BACKLIGHT_ENABLE=yes`. The @jpetermans keymap does that, since currently the led controller code has a bit more features, but the other keymaps are using the visualizer.

If you are using the visualizer backlight, then you can control the backlight level with the [Backlight Keycodes](https://docs.qmk.fm/quantum_keycodes.html#backlight). Note that by default the level and state is random since the EEPROM could be initialized with any value, so you need to add those keys to control it.

**Before this is merged, I would like to see both variations tested, because I don't own the keyboard myself.**

Another thing that this pull request does, is adding support for a `build.mk` file in the keyboard or subproject directory. That makefile is run after all options have been parsed, so it's possible to take some actions based on that. In this case, it compiles the led controller files if it's enabled.

### CODE REVIEW

**Comment by jackhumbert** [comment]
@fredizzimo do you know if this has been tested yet? Could we ping anyone to try it?

**Comment by jpetermans** [comment]
I'm up for testing.  I've got a busy few weeks ahead, but I'll start looking through the code @fredizzimo put together to get familiar with it.  Any docs to guide me on how to get started and a list of things to test?

**Comment by drashna** [comment]
This can probably be closed now, since we have the LED Matrix added, which supports the 3731 and 3733 controllers.

**Comment by drashna** [comment]
I don't think that this is needed anymore, as we have the LED Matrix now.... and that doesn't use uGFX. 

https://docs.qmk.fm/#/feature_led_matrix

**Comment by skullydazed** [comment]
I agree with @drashna, at this point we shouldn't be merging any new ugfx boards.

**Pull request closed without merging**
