### PR TITLE
new planck keymap

### PR DESCRIPTION
**Pull request by kritt3r**
Extraneous files deleted and lines changed as requested

### CODE REVIEW

**Comment by drashna** [comment]
Looks like those files are still there, unfortunately.

Also, no need to keep closing and reopening PRs.  If you make changes on the branch in question, it will automatically update the PR. 

Additionally, if you want, I can see about helping fix things up.

**Comment by kritt3r** [comment]
Gotcha.

The files are gone on my repository, so am I not pushing or something correctly?

**Comment by drashna** [comment]
You may not have grabbed the right branch then? 

I can definitely still see them. For instance:  https://github.com/kritt3r/qmk_firmware/blob/master/config.h

**Comment by kritt3r** [comment]
How do i push this then? I believe this is correct.
https://github.com/kritt3r/qmk_firmware/tree/master/keyboards/planck/keymaps/vaire

**Comment by kritt3r** [comment]
nvm i think i fixed it. I didn't realize you were referencing the files in /qmk_firmware

**Comment by drashna** [comment]
Sorry for not being clear! 

Also, it looks like the readme in the root was also modified. That needs to be reverted, too.

**Comment by drashna** [comment]
Awesome, thanks! 

Also, if you need any help with git/github, don't hesitate to ask here or on our gitter.  We are more than happy to help!

**Pull request merged**
