### PR TITLE
Fix `combo_disable`

### PR DESCRIPTION
**Pull request by sevanteri**
## Description

Fixes a couple of issues with `combo_disable` function calls.

The key buffer was not emptied when disabling combos; I had removed the `dump_key_buffer()` call as it could lead to infinite loops. Removing the call it seems wasn't the right move.
Now recursive calls to `dump_key_buffer` start from the next key instead of the key that is "currently being dumped" from the buffer.

Another issues with disabling combos was that any currently active combo wasn't released on key releases.
Now combo key releases are always handled, even if combo processing is disabled.

Easy way to test the current issues:

- create a combo that resolves to `LT(_LAYER, KC_X)`
- When changing to `_LAYER`, call `disable_combo()`

Then just hold the combo for a while to activate the layer. On release the layer stays on.

I've messaged the two I know had issues with this to review this.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
@tzarc Since this is a bug fix, I'd feel better if this made it in on this cycle, rather than q3's.   Thoughts?

**Comment by caksoylar** [comment]
I can confirm that this fixes the issue I described here: https://github.com/qmk/qmk_firmware/pull/8591#issuecomment-885193406. Thanks @sevanteri!

**Comment by tzarc** [comment]
> 
> 
> @tzarc Since this is a bug fix, I'd feel better if this made it in on this cycle, rather than q3's. Thoughts?

This is the q3 cycle :)

**Review by tzarc — APPROVED** [review]

**Comment by trankillity** [comment]
Can also confirm that this fixes the issue described.

**Pull request merged**
