### PR TITLE
introduce new default layout 68_ansi

### PR DESCRIPTION
**Pull request by mechmerlin**
As the title says. This is actually just my previous commit without the top row and a community directory layout. I don't have any 65%s!!!!

### CODE REVIEW

**Comment by drashna** [comment]
Nice :)

**Comment by noroadsleft** [comment]
Crap, I wish I'd seen this earlier. I would have suggested to name it 65_ansi instead, and then 68_ansi could have been Magicforce 68/Varmilo VA68M layout. :frowning:

**Comment by drashna** [comment]
Well, we can still change things later.

**Comment by mechmerlin** [comment]
You're right! Both a 65% and a 68 key have 68 keys lol. But that is more commonly known as a 65%. Swap it over when you have time. Percents vs Keys lol.

**Pull request merged**
