### PR TITLE
Initial Commit of Noxary 268 firmware by Rozakiin

### PR DESCRIPTION
**Pull request by yanfali**
- initial import of files from Rozakiin's repo

This PR imports the Noxary 268 firmware files from @Rozakiin repo [here](https://github.com/Rozakiin/Noxary_Firmware) by his kind [permission](https://github.com/Rozakiin/Noxary_Firmware/issues/1) so that we may start integration with the configurator. TBD create an info.json to go with this keyboard.

### CODE REVIEW

**Comment by yanfali** [comment]
@Rozakiin let me know if you need anything changed. QMK has started to put families of keyboards under their respective vendors. Let me know if Noxary isn't the correct location and I will be happy to change it to whatever you choose. Many thanks.

**Comment by MxBlu** [comment]
I see I'm a bit late, but here's the KLE layout for the 268: https://gist.github.com/MxBlu/c9c76f961a292ec741099d45f29fe376

I am happy to help out if need be.

**Comment by yanfali** [comment]
Oh sweet, thanks. Rozakiin only had an image so I created one from scratch. Thanks for this though, I will verify the info.json.

**Comment by drashna** [comment]
@Rozakiin Did this look good to you?  I'd like to get your approval, before merging it

**Comment by Rozakiin** [comment]
@drashna Yes it all looks good

**Comment by drashna** [comment]
Awesome! Thanks!

**Pull request merged**
