### PR TITLE
Rename debouncing algorithms

### PR DESCRIPTION
**Pull request by purdeaandrei**
## Description

Please see Issue #8763 for the discussion on this topic.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* Issue #8763

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Just a heads up, the eager debouncing algo's are cycle based, not time based, IIRC. 
@alex-ong can confirm/correct.

**Comment by purdeaandrei-movi** [comment]
> Just a heads up, the eager debouncing algo's are cycle based, not time based, IIRC.
> @alex-ong can confirm/correct.

No, all currently implemented algorithms are time based.

Andrei

**Comment by alex-ong** [comment]
Agree with purdeaandrei, they are all Ms based

**Comment by zvecr** [comment]
<https://docs.qmk.fm/#/breaking_changes_instructions>
> Edits to User Keymaps A user may submit their keymap to QMK, then some time later open a pull request with further updates, only to find it can’t be merged because it was edited in the qmk/qmk_firmware repository. As not all users are proficient at using Git or GitHub, the user may find themself unable to fix the issue on their own.

**Comment by drashna** [comment]
> Agree with purdeaandrei, they are all Ms based

I swear there was a conversation where you said it was, but I can't find it... 
And I brought it up because there was a recent change to the ergodox's scan code that made the scans much faster, but much more prone to not catching bounces and basically required doubling the dounce value.

Mostly typing this out to document it, in case I need to reference it. 

Otherwise, looks good.

**Comment by Erovia** [comment]
Currently this is a breaking change. That means the PR should target the `develop` branch instead of `master`.  
Since the change is backward compatible, I think if you'd split the core and keymap stuff into different PRs, the core one could be merged to master and only the keymap one would be considered breaking.

What do you think?

**Comment by purdeaandrei** [comment]
@Erovia 

Agreed, will do so, also I want to do another change to how time/cycles are handled.
I'm reworking the PR, and will add a new PR, so closing this one...

**Comment by purdeaandrei** [comment]
New PR here: https://github.com/qmk/qmk_firmware/pull/9564

**Pull request closed without merging**
