### PR TITLE
Add led/rgb_matrix_none_indicator_kb/user function

### PR DESCRIPTION
**Pull request by lokher**
Add `led_matrix_none_indicators_kb()` and `led_matrix_none_indicators_user()` to led matrix files.
Add `rgb_matrix_none_indicators_kb()` and `rgb_matrix_none_indicators_user()` to rgb matrix files.

With `led_matrix_indicators_kb` / `led_matrix_indicators_advanced_user` and `rgb_matrix_indicators_kb` 
 / `rgb_matrix_indicators_advanced_user`, it is possible to indicate Caps lock state when backlight is on, however it doesn't work when backlight is off.

With these new functions, caps lock indicating state  can be kept upon led/rbg matrix turning off. 
Additionly, when led/rbg matrix is off, with `led_update_kb` or `led_update_user`,  caps lock indicating state  can be toggled with `led_matrix_set_value` or `rgb_matrix_set_color`, followed by `led_matrix_update_pwm_buffers` / `rgb_matrix_update_pwm_buffers`.

Thus caps lock / num lock/ scroll lock indicators work no matter what led/rgb matrix status is except power down.

No sure whether it will work with all type of led drivers, but should work with most.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
A better way to handle this may be to use the "flags" function.  You can prevent rendering of all the LEDs.   And then manually handle caps lock, for instance. 

A number of boards do this, already, such as the massdrop boards, the ZSA boards (ergodox ez, planck ez, and moonlander).  So there are definitely examples that can be used.

**Comment by lokher** [comment]
Actually, what we like to implement is:
1: When led/rgb matrix is enabled,
    a: Caps lock off:  all LEDs are for animations
    b: Caps lock on: all LEDs except the one under caps lock  are for animations, LED under caps lock is set to solid color
2: When led/rgb matrix is disable
    a: Caps lock off:  all LEDs off
    b: Caps lock on: LED under caps lock is set to solid color

I tried checking led/rgb matrix state in loop and turning indicator when disabled, and saw the indicator shortly off when turned off backlight.

**Comment by drashna** [comment]
Yeah, that's what it's doing.  The trick is handling when to render via the rgb_matrix_indicators_* function. 

```c
bool process_record_kb(uint16_t keycode, keyrecord_t *record) {
    if (!process_record_user(keycode, record)) { return false; }
    switch (keycode) {
#ifdef RGB_MATRIX_ENABLE
        case RGB_TOG:
            if (record->event.pressed) {
                switch (rgb_matrix_get_flags()) {
                    case LED_FLAG_ALL: {
                        rgb_matrix_set_flags(LED_FLAG_NONE);
                        rgb_matrix_set_color_all(0, 0, 0);
                    } break;
                    default: {
                        rgb_matrix_set_flags(LED_FLAG_ALL);
                    } break;
                }
                eeconfig_update_kb(keyboard_config.raw);
            }
            return false;
#endif
    }
    return true;
}

__attribute__((weak)) void rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    // RGB_MATRIX_INDICATOR_SET_COLOR(index, red, green, blue);

    if (host_keyboard_led_state().caps_lock) {
        RGB_MATRIX_INDICATOR_SET_COLOR(index, 255, 255, 255);
    } else {
        if (!rgb_matrix_get_flags()) {
           RGB_MATRIX_INDICATOR_SET_COLOR(index, 0, 0, 0);
    }
}

**Comment by lokher** [comment]
> Yeah, that's what it's doing. The trick is handling when to render via the rgb_matrix_indicators_* function.
> 
> ```c
> bool process_record_kb(uint16_t keycode, keyrecord_t *record) {
>     if (!process_record_user(keycode, record)) { return false; }
>     switch (keycode) {
> #ifdef RGB_MATRIX_ENABLE
>         case RGB_TOG:
>             if (record->event.pressed) {
>                 switch (rgb_matrix_get_flags()) {
>                     case LED_FLAG_ALL: {
>                         rgb_matrix_set_flags(LED_FLAG_NONE);
>                         rgb_matrix_set_color_all(0, 0, 0);
>                     } break;
>                     default: {
>                         rgb_matrix_set_flags(LED_FLAG_ALL);
>                     } break;
>                 }
>                 eeconfig_update_kb(keyboard_config.raw);
>             }
>             return false;
> #endif
>     }
>     return true;
> }
> 
> __attribute__((weak)) void rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
>     // RGB_MATRIX_INDICATOR_SET_COLOR(index, red, green, blue);
> 
>     if (host_keyboard_led_state().caps_lock) {
>         RGB_MATRIX_INDICATOR_SET_COLOR(index, 255, 255, 255);
>     } else {
>         if (!rgb_matrix_get_flags()) {
>            RGB_MATRIX_INDICATOR_SET_COLOR(index, 0, 0, 0);
>     }
> }
> ```

I tested it, the backlight animation automaticly turned on after power cycle no matter how the backlight state was. 
I dont think this is better way.

**Comment by drashna** [comment]
> I tested it, the backlight animation automaticly turned on after power cycle no matter how the backlight state was.
> I dont think this is better way

Well... I can verify that this works, provided that EEPROM support is working.   I had to fix the code for the ZSA boards (in their fork) because of changes to the eeprom storage stuff for rgb matrix.  So I'm not sure what it's not working properly for you, but this code does work.

**Comment by drashna** [comment]
I can verify that this works.  Not only did I have to change code for ZSA's fork due to changes in how the eeprom works for rgb matrix, but I have verified this works on one of my boards.

This exact code. 

So unless eeprom storage isn't working or is using transient eeprom, this *should* be working as expected.

**Pull request closed without merging**
