### PR TITLE
initial branch

### PR DESCRIPTION
**Pull request by Waples**
I would like to add my keymap to the Let's Split keymaps.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! Would you mind making the keymap's name lowercase? We try to keep them consistent for case-sensitive systems :)

**Comment by Waples** [comment]
Okay no problem ^^ Will get back to you when I'm done. For some reason I didn't get an email about your comment.. :\

**Comment by Waples** [comment]
@jackhumbert As requested ^^

**Comment by Waples** [comment]
@jackhumbert bump :D

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
