### PR TITLE
Update quantum matrix to support both AVR and Chibios ARM

### PR DESCRIPTION
**Pull request by yiancar**
- Addition of STM32 pin definitions
- Created abstruction layer defines to control GPIO (This is a bit pointless for Chibios as we are creating a PAL ontop of a PAL but it is necessary for uniformity with AVR)
- Modified matrix.c to use the above functions

### CODE REVIEW

**Comment by yiancar** [comment]
This PR is a mix and match of some other code previously found on a variety of places in QMK (usually committed from @jackhumbert)

**Comment by yiancar** [comment]
Travis complains about some size issues which I imagine were there before me:)

**Comment by noroadsleft** [comment]
Yeah, those were like that already. It's unrelated.

**Comment by drashna** [comment]
Unrelated to this PR, but I've fixed the keyboards causing the size errors, and the future checks *should* pass. 

And yeah, we recently changed the "too large" warning to an error.  The side effect to that is that it causes Travis CI to fail.   The upside is that it should be more apparent when this issue comes up, and will stop the build script from flashing (and bricking Pro Micros)

**Comment by yiancar** [comment]
Yep thats great. We should probably contact the people who own those builds to turn off some of there features?

**Comment by jackhumbert** [comment]
Awesome - thanks!

**Pull request merged**
