### PR TITLE
Update Lisa

### PR DESCRIPTION
**Pull request by key10iq**
## Description
My update adds the ability to configure the indicator LEDs function directly from VIA

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Updated keyboard - keyten/lisa 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by waffle87** [comment]
Unfortunately this cannot be accepted, as custom VIA indicator code is not currently not accepted to the qmk_firmware repository due to the maintenance burden it poses.

**Comment by key10iq** [comment]
> Unfortunately this cannot be accepted, as custom VIA indicator code is not currently not accepted to the qmk_firmware repository due to the maintenance burden it poses.

Is this considered a custom indicator code?
https://github.com/key10iq/keyboards/blob/Lisa/v3/keyten/lisa/lisa.json

This is controlled like a regular multilayout

**Comment by zvecr** [comment]
From the PR checklist:
> keyboard updates and refactors (eg. to data driven) must go through develop to reduce master -> develop merge conflicts

And with <https://docs.qmk.fm/ChangeLog/20240526#migration-of-via-keymaps-to-via-team-control>, we would certainly not be accepting any further keyboard level via customisation.

**Comment by key10iq** [comment]
Got it, thanks

**Pull request closed without merging**
