### PR TITLE
S60-X RGB support

### PR DESCRIPTION
**Pull request by Dbroqua**
Hello,

It's for the RGB version of the S60-X. With the actual s60-x firmware my keyboard does not work but with this version (based on qmk.sized.io) it works.

I'm not sure if 2 directories are necessary or if we can merge s60-x and s60-x RGB in one directory (just change rules.mk ?)... But in doubt... 

Regards,
Damien

### CODE REVIEW

**Comment by jackhumbert** [comment]
Yeah, this would be better off as a subproject, or possibly just an always-on unless a keymap specifies that it doesn't need it. Is rules.mk the only difference between the two? You mentioned that the actual s60-x firmware doesn't work - do you mean the factory default, or the s60-x folder in QMK?

**Comment by Dbroqua** [comment]
Yes, only the rules.mk differ.

> You mentioned that the actual s60-x firmware doesn't work - do you mean the factory default, or the s60-x folder in QMK?

First, I try to flash my RGB version with the actual S-60-X revision of the qmk_firwmare and my keyboard does not work.
After few search on google I found a fork of QMK for the RGB revision. After a quick diff only the rules.mk changes. And after flash my keyboard works.

**Comment by jackhumbert** [comment]
If you turn RGB off in your working directory, does everything but the RGB leds work? I'm not sure how that would cause the keyboard to be inoperable :/

**Comment by Dbroqua** [comment]
If I turn RGB to Off in the s60-x-rgb directory: my keyboard works.

My bad: config.h differ, Matrix cols/rows are different in the 2 revisions

**Comment by jackhumbert** [comment]
Ah, gotcha. Yeah, let's make it a subproject then - is that something you think you'd be able to do? The Clueboard, Plancks, and a few others do the same thing if you need a reference!

**Comment by Dbroqua** [comment]
For the planck it's with the subfolder rev3 and rev4 ?

It's yes I will see how to do this ^^

Regards,
Damien

**Comment by Dbroqua** [comment]
Finally I moved RGB directory in sub folder of S60-X and I think all is ok (first time for me :D ).

Regards,
Damien

**Comment by Dbroqua** [comment]
Hello @jackhumbert all is ok?

**Comment by jackhumbert** [comment]
I think so! Thanks :)

**Comment by Dbroqua** [comment]
Ok!

**Pull request merged**
