### PR TITLE
Update snowe's KC_RESET to use QK_BOOT

### PR DESCRIPTION
**Pull request by precondition**
## Description

Update @snowe2010's crkbd keymap to use QK_BOOT instead of RESET.

PS: I'm not sure if editing user keymaps like that is really accepted but this PR is not too different from #18560 so I think it's ok

```diff
commit 19db27a3dbfd91091be06b77bbf5accde380fb31 (HEAD -> update_snowe_s_KC_RESET, origin/update_snowe_s_KC_RESET)
Author: precondition <57645186+precondition@users.noreply.github.com>
Date:   Mon Oct 10 21:12:58 2022 +0200

    Update snowe's KC_RESET to use QK_BOOT

diff --git a/keyboards/crkbd/keymaps/snowe/keycode_aliases.h b/keyboards/crkbd/keymaps/snowe/keycode_aliases.h
index bd70a79aa5..c19fb11d4b 100644
--- a/keyboards/crkbd/keymaps/snowe/keycode_aliases.h
+++ b/keyboards/crkbd/keymaps/snowe/keycode_aliases.h
@@ -42,7 +42,7 @@
 #define COLEMAK KC_COLEMAK
 #define WORKMAN KC_WORKMAN
 
-#define KC_RESET RESET
+#define KC_RESET QK_BOOT
 #define KC_RST KC_RESET
 
 #ifdef SWAP_HANDS_ENABLE
diff --git a/users/snowe/wrappers.h b/users/snowe/wrappers.h
index 9ef7dce607..47fe4a5ace 100644
--- a/users/snowe/wrappers.h
+++ b/users/snowe/wrappers.h
@@ -88,5 +88,5 @@ NOTE: These are all the same length.  If you do a search/replace
 #define _________________ADJUST_L2_________________        MU_TOG , TG(_GAMING), AU_ON,   AU_OFF,  AG_NORM
 #define _________________ADJUST_L3_________________        RGB_RMOD,RGB_HUD,RGB_SAD, RGB_VAD, _______
 #define _________________ADJUST_R1_________________        _______, _______, _______, _______, _______
-#define _________________ADJUST_R2_________________        RESET,   CG_TOGG, _______, _______, _______
+#define _________________ADJUST_R2_________________        KC_RESET,CG_TOGG, _______, _______, _______
 #define _________________ADJUST_R3_________________        _______, KC_MNXT, KC_VOLU, KC_VOLD, KC_MPLY
```
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

*  Compilation errors when compiling crkbd:snowe

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — APPROVED** [review]

**Comment by keyboard-magpie** [comment]
I think this keymap needs overhauling in other areas (OLED code) for it to be contemporary?

**Comment by precondition** [comment]
> I think this keymap needs overhauling in other areas (OLED code) for it to be contemporary?

To be fair, I just wanted to fix only the compilation errors so that the CI run for #15741 doesn't fail due to snowe's keymap. So I didn't look further than the error log to check if other areas of the code could use an overhaul.

**Review by fauxpark — APPROVED** [review]

**Comment by keyboard-magpie** [comment]
> precondition thank you very much! I don't update my code very often so I very much do appreciate any help 😬.
> 
> keyboard-magpie what do I need to fix in the OLED code? A lot of it was very custom and qmk moves very fast and at the rate I update stuff (once a year lol) I get very out of date.

I think it's as simple as adding `#   define OLED_TIMEOUT 30000` to config.h- the issues that get reported on the discord server (your keymap is quite popular!) are that the OLED flickers after initial timeout.

**Comment by snowe2010** [comment]
>I think it's as simple as adding # define OLED_TIMEOUT 30000 to config.h- the issues that get reported on the discord server (your keymap is quite popular!) are that the OLED flickers after initial timeout.

haha is it really? man I thought it wasn't very popular judging by the limited number of responses on my reddit post 😅 . I would have kept expanding it if I knew it was popular! I haven't visited the discord in a long time lol. maybe I should go search my username on there 😫 

I've wondered how to fix that flicker for a long time! I'm glad the fix is so simple! I'll do that right away. Thank you!

**Pull request merged**
