### PR TITLE
Add underglow animation support to rask's UK78

### PR DESCRIPTION
**Pull request by rask**
The UK78 supports underglow animations and this change adds the `RGB_MOD` key to my UK78 layout that allows shuffling between animation modes.

### CODE REVIEW

**Comment by rask** [comment]
Oh god it happened again, all the commits from my topic branch are shown here even though the last two are the actual changes. I need to use some new branching convention on my end.

**Comment by drashna** [comment]
It's not a problem.  Jack or whomever will squash the commits when merging, so it will only show up as a single commit in QMK.

Otherwise, you probably want to rebase, rather than merging. 
Also, once a PR is merged, you'd want to reset and rebase.  

If you like, I have some "scripts"/aliases that automate this process for me.

**Comment by rask** [comment]
@drashna yeah I remember that this happened with my previous PR as well but forgot to do anything about is this time around. Hopefully, I'll remember the next time.

**Comment by jackhumbert** [comment]
Nice - thanks! :)

**Pull request merged**
