### PR TITLE
[Docs] Remove note about feature parity for ARM splits

### PR DESCRIPTION
**Pull request by KarlK90**
## Description

I think this is obsolete by now isn't it? I don't speak japanese maybe @umi-umi can have a look?

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* Many people asking/having doubts about ARM support on splits.

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
No i2c transport, serial bitbang doesnt work well with other features(like rgb). Most common gotchas that still get asked on Discord fairly frequently.

Personally, i think it should stay for the time being.

**Comment by tzarc** [comment]
Perhaps it'd be best if we described exactly that, instead? It's a bit ambiguous as it stands and it's generally being misinterpreted by people in general -- most seem to thing ARM split flat-out isn't possible.

**Comment by KarlK90** [comment]
I would prefer a more detailed explanation as well. The note says for _me at least_ that split keebs and ARM is experimental and should be avoided if one wants something reliable and feature full.

**Comment by zvecr** [comment]
The issue is listing all the nuanced cases where it will and wont work, is rather difficult. Would lead to a wall of text, that will also likely be ignored.

> most seem to think ARM split flat-out isn't possible

While i agree this is a common misconception, i'm not sold that its entirely due to docs. And partially due to it previously being a non starter, coupled with the length of time it was "coming soon".

**Comment by KarlK90** [comment]
I'll close this in favor of the updated sentence in the [docs](https://github.com/qmk/qmk_firmware/pull/11930/commits/af63cb278dde195154982136f42b58a506010b6e#diff-146343c41b58591dbc75c6b43d8b9ea98bd7148691b75c2b91006cb57b0f4525R11) of #11930.

**Pull request closed without merging**
