### PR TITLE
RGBKB Folder

### PR DESCRIPTION
**Pull request by XScorpion2**
## Description

Moved all RGBKB keyboards (Sol, Zen, Zygomorph) to a new RGBKB folder. Also cleaned up the default keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by XScorpion2** [comment]
looks like most of the errors in my pr are from community / layout keymaps

**Comment by XScorpion2** [comment]
Also not sure why my firmware building so large and oversized, locally it is fine.

**Comment by XScorpion2** [comment]
Merge error fixed, compile errors are due to community / layout keymaps that are now included due to the LAYOUT changes. (Also the CI server doesn't like my keymap).

Can this be merged?

**Comment by drashna** [comment]
>Also the CI server doesn't like my keymap

Apparently it has good taste?  :P  
Especially since it doesn't like mine, either. 

Joking aside, it looks good to me

**Pull request merged**
