### PR TITLE
Remove extra holes in Let's Split case

### PR DESCRIPTION
**Pull request by nicinabox**
These holes don't line up with anything. There are no holes in the PCB in this place and removing them matches the STL of the same design.

screen shot 2017-01-26 at 5 24 18 pm

### CODE REVIEW

**Comment by jackhumbert** [comment]
@climbalima are you able to confirm that these don't do anything and are able to be removed?

**Comment by climbalima** [comment]
I put these there for people with the proto pcb that I gave out at the boston meetup. I would like to keep them as there are lots of people with these pcbs.

**Comment by nicinabox** [comment]
Cool, no worries. What do you think about renaming that file with
`_prototype` and include a new one with no holes with a `_v2` suffix?

**Comment by jackhumbert** [comment]
If you only handed it out at the Boston meet-up, `_boston` might work too! Just let us know, @climbalima and I can merge with the changes :)

**Comment by jackhumbert** [comment]
Just gonna close this for now - I'll leave the renaming/organisation of let's split up to @climbalima :)

**Pull request closed without merging**
