### PR TITLE
Added documentation for adding LVGL custom fonts

### PR DESCRIPTION
**Pull request by shawnfelix**
## Description
Added documentation:
Instructions for adding custom fonts with QP LVGL integration

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* N/A - Just some added knowledge in the documentation 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
And @elpekenin, any issues with this?

**Comment by elpekenin** [comment]
Nothing against nor in favour about this, mainly bcs i have never used LVGL. (that also means i dont even know if the funcs/macros used are even correct) 

I guess extra documentation doesnt harm, but on the other hand it makes relevant information harder to find, specially with how bad the search tool sometimes works...

And since this mostly LVGL-specific documentation, we should perhaps just redirect users to their page and not clutter QP's page with it

**Comment by shawnfelix** [comment]
> And since this mostly LVGL-specific documentation, we should perhaps just redirect users to their page and not clutter QP's page with it

@elpekenin  In my project I required a few more steps for adding fonts than what was available from the LVGL docs. I figured that this docs addition would give a useful example for those who go down the LVGL route. Granted, LVGL is probably not frequently used by most.

> I guess extra documentation doesnt harm, but on the other hand it makes relevant information harder to find, specially with how bad the search tool sometimes works...

Agreed. The search tool has been the bane of my existence. and it's something I've been thinking about working on. However, I've been told that there are some core changes that are currently in progress before we address major changes to the docs.

With limited amount QMK+LVGL specific information out there it can be tough for newbies to have success with LVGL. I've been doing some note-taking myself and may publish a personal blog post that we could eventually add to the QMK docs.

**Comment by elpekenin** [comment]
> required a few more steps for adding fonts than what was available from the LVGL docs

Sure, im not saying their docs are perfect (i havent ever looked at them, anyway), my point here is that perhaps the missing documentation is more to do with their own docs, not QMK's. 

As far as i can tell you only really needed the `SRC +=` in the makefile to get the files compiled (??), but that's again not a QP-specific (or even QMK) thing, but just how the build system works... And having that on the QP page, when it is a much broader thing may not be the best idea.

If you really needed something that wasn't on their docs, for example the `LV_FONT_DECLARE` macro... that's definitely on them.

--- 

Also, took a closer look at your changes now, and while i like having a standarized `fonts` folder name, where every potential LVGL-enabled keyboard has their code... It may not be the way to word it, as it makes it look like a requirement.

**Comment by shawnfelix** [comment]
> As far as i can tell you only really needed the `SRC +=` in the makefile to get the files compiled (??), but that's again not a QP-specific (or even QMK) thing, but just how the build system works... And having that on the QP page, when it is a much broader thing may not be the best idea.
> 
> If you really needed something that wasn't on their docs, for example the `LV_FONT_DECLARE` macro... that's definitely on them.

Good point. Step 3 (modifying the LVGL generated C font file) is also specific to QMK but overall not very difficult to figure out. 

_It would be nice_ to have more QMK+LVGL code examples like this PR, but I don't think this addition is the best fit for the QMK docs. QMK+LVGL a niche topic, but still I'm an advocate for more examples/blueprints in the docs

I'll close this and make a blog post elsewhere

Side note: If you're ever interested in QMK+LVGL you can check out my project i've been working on in my fork - develop branch. Building an interactive UI for my keyboard with a whole suite of customizable widgets (macros/games/tools sort of thing) planned out.

**Pull request closed without merging**
