### PR TITLE
JJ40 updates

### PR DESCRIPTION
**Pull request by RandTrawick**
added backlight pin, readme boot default key etc.

### CODE REVIEW

**Comment by jackhumbert** [comment]
[It looks like your build is failing in Travis](https://travis-ci.org/qmk/qmk_firmware/builds/307217074?utm_source=github_status&utm_medium=notification) - does it build locally?

Also, would you mind renaming your keymap? We don't really have an official policy on profanity yet, but we'd like to keep things family-friendly!

**Comment by drashna** [comment]
Looks like it's failing due to this: #2057

**Comment by RandTrawick** [comment]
Sorry about that name, it was from a party we had a while ago and was a bad choice.  
* updated readme and folder names
* set NKRO flag to no, it compiles locally now.
Please review.

**Comment by jackhumbert** [comment]
Cool! It looks like your JJ40.sublime-workspace snuck it - would you mind removing that?

The `info.json` also needs updated for the JJ40 :)

**Comment by RandTrawick** [comment]
updated.  
info.json removed (thought it might help troubleshoot NKRO). I'm new to qmk.

**Comment by jackhumbert** [comment]
Awesome! Thanks :)

**Pull request merged**
