### PR TITLE
Helix keymap rules mk refine

### PR DESCRIPTION
**Pull request by MakotoKurauchi**
refine the redundant code

### CODE REVIEW

**Comment by drashna** [comment]
Wouldn't the keymaps_common.mk stuff work in the rules.mk, so that it's automatically included?

**Comment by mtei** [comment]
The current version `keymaps/*/rules.mk` sets the Makefile variable for customization in the first half.
In the second half of `keymaps/*/rules.mk`, settings such as CFLAGS are set according to the contents of the Makefile variable.

The first half is changed according to the user's own needs of the keymap.
In the second half, the user does not need to change.

In this PR we moved the latter half of `keymaps/*/rules.mk` to `keymaps_common.mk`.
We decided to put `include $(dir $(lastword $(MAKEFILE_LIST)))../../keymaps_common.mk` at the end of keymaps/*/rules.mk.

**Comment by mtei** [comment]
Now I am waiting for #3582 to be merged.
When #3582 is merged, I will change `keymaps_common.mk` as follows.

```
index be54883..19adb1b 100644
--- a/keyboards/helix/rev2/keymaps_common.mk
+++ b/keyboards/helix/rev2/keymaps_common.mk
@@ -62,7 +62,14 @@ ifeq ($(strip $(IOS_DEVICE_ENABLE)), yes)
 endif
 
 ifeq ($(strip $(LED_ANIMATIONS)), yes)
-    OPT_DEFS += -DRGBLIGHT_ANIMATIONS
+    # imitate OPT_DEFS += -DRGBLIGHT_ANIMATIONS
+    # but omit RGB_test and alternating mode for save space
+    OPT_DEFS += -DRGBLIGHT_EFFECT_BREATHING
+    OPT_DEFS += -DRGBLIGHT_EFFECT_RAINBOW_MOOD
+    OPT_DEFS += -DRGBLIGHT_EFFECT_RAINBOW_SWIRL
+    OPT_DEFS += -DRGBLIGHT_EFFECT_SNAKE
+    OPT_DEFS += -DRGBLIGHT_EFFECT_KNIGHT
+    OPT_DEFS += -DRGBLIGHT_EFFECT_CHRISTMAS
+    OPT_DEFS += -DRGBLIGHT_EFFECT_STATIC_GRADIENT
 endif
 
 ifeq ($(strip $(OLED_ENABLE)), yes)
```

**Comment by drashna** [comment]
For the rules, the user's rules.mk will be what is used, over riding the keyboard's settings.

So placing these mk config in the keyboard's rules.mk means that users will still be able to set them, without REQUIRING them to be present in the user's keymap folder.   Which is a MUCH better way to handle the rules.

**Comment by mtei** [comment]
And the user can delete the following line if he wishes.
And he can write everything himself.

```
include $(dir $(lastword $(MAKEFILE_LIST)))../../keymaps_common.mk
```

**Comment by mtei** [comment]
I understand the principles related to rules.mk you are talking about and I keep it. Please let me explain in detail.

The Helix keyboard kit has several hardware options.
 * Users can choose whether the keyboard is 4 or 5 rows.
 * Users can choose whether to use SSD1306 based OLED display or not.
 * Users can choose whether to use rgblight as backlight, underglow or not.

For that reason the setting of rules.mk is a bit more complicated.

So, we prepared a convenient setting to enclose the standard settings.
```
  HELIX_ROWS = 5              # Helix Rows is 4 or 5
  OLED_ENABLE = no            # OLED_ENABLE
  LED_BACK_ENABLE = no        # LED backlight (Enable WS2812 RGB underlight.)
  LED_UNDERGLOW_ENABLE = no   # LED underglow (Enable WS2812 RGB underlight.)
```

These settings are translated into standard settings by code like the following in the second part of rules.mk.

```
  ifneq ($(strip $(HELIX_ROWS)), 4)
    ifneq ($(strip $(HELIX_ROWS)), 5)
      $(error HELIX_ROWS = $(strip $(HELIX_ROWS)) is unexpected value)
    endif
  endif
  OPT_DEFS += -DHELIX_ROWS=$(strip $(HELIX_ROWS))  ## Pass the number of rows to config.h.

  ifeq ($(strip $(LED_BACK_ENABLE)), yes)
    RGBLIGHT_ENABLE = yes                          ## set standard setting
    OPT_DEFS += -DRGBLED_BACK                      ## Pass backlight or underflow to config.h.
    ifeq ($(strip $(LED_UNDERGLOW_ENABLE)), yes)
      $(eval $(call HELIX_CUSTOMISE_MSG))
      $(error LED_BACK_ENABLE and LED_UNDERGLOW_ENABLE both 'yes')
    endif
  else ifeq ($(strip $(LED_UNDERGLOW_ENABLE)), yes)
    RGBLIGHT_ENABLE = yes                          ## set standard setting
  else
    RGBLIGHT_ENABLE = no                           ## set standard setting
  endif
  ifeq ($(strip $(OLED_ENABLE)), yes)
    OPT_DEFS += -DOLED_ENABLE                      ## Whether to use OLED for config.h is passed.
  endif
```

As you can see, these translation codes are always the same thing. Moving these codes to a common file does not disturb the user's choice.

Consolidating the same translated code distributed in each rules.mk into keymaps_common.mk will improve maintainability. This is the purpose of this PR.

**Pull request closed without merging**
