### PR TITLE
translate docs into Mandarin Chinese

### PR DESCRIPTION
**Pull request by ymzcdg**
translate docs into Madarin Chinese

## Description
translate 
---- newbs.md 
----getting_started_github.md
----getting_started_getting_help.md
----contributing.md
----getting_started_introduction.md
into Mandarin Chinese
_summary的第二部分完成，辛苦@mechmerlin大神了！
thanks mechmerlin for give me the time to complete unit two.
@drashna taught me some words，thanks. " raison d'être" turned out to be English, fantastic!

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
@mechmerlin ?

**Comment by yanfali** [comment]
Use an editor that respects editor config settings.

**Comment by drashna** [comment]
Notepad++ supports changing line endings. As does VSCode. 


Additionally, if you're using git from the command line, try running:
```sh
git config --global core.autocrlf false
git config --global core.eol lf
```

This will hopefully make sure that it doesn't use windows line endings (crlf), but use unix style line endings (lf).

Also, "raison d'être" is technically french, but used often in english. ;)

**Comment by ymzcdg** [comment]
There is something wrong with my source file, so my files are in windows format. I fixed it with notepad++.

**Pull request merged**
