### PR TITLE
Fix inverted encoders on BDN9 rev. 2

### PR DESCRIPTION
**Pull request by aidalgol**
## Description

Without ENCODER_DIRECTION_FLIP, the 'clockwise' argument to encoder_update_user() is inverted.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist
- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by aidalgol** [comment]
This appears to have caused build errors around RGB functionality in some keymaps, and I have no idea how.
https://qmk-ci.tzarc.io/cf05d5b93f1d09a1f19fd9748dc4d73483afbe2a:be568177435c94a7c18217c5486e2df1062c3d73

**Comment by tzarc** [comment]
> This appears to have caused build errors around RGB functionality in some keymaps, and I have no idea how.
> https://qmk-ci.tzarc.io/cf05d5b93f1d09a1f19fd9748dc4d73483afbe2a:be568177435c94a7c18217c5486e2df1062c3d73

I’d say it’s more likely that they fail already, without your PR. If they’re the same on `master`, don’t worry about it.

**Comment by tzarc** [comment]
Your PR is the first one that has triggered failures since adding the new CI builder yesterday, sorry about the false positive! I think we might need some tweaks for these scenarios.

**Review by zvecr — CHANGES_REQUESTED** [review]

**Review by drashna — APPROVED** [review]

**Review by keyboard-magpie — APPROVED** [review]

**Comment by nooges** [comment]
I'm going to have to reject this, as it would not match the orientation of the encoders I sell. I have noticed that some encoders have the opposite orientation, and I'm guessing that could be the case here where encoders of the opposite orientation were used.

**Pull request closed without merging**
