### PR TITLE
Fix keyboard matrix scan rate with F072

### PR DESCRIPTION
**Pull request by Xelus22**
## Description

Change matrix io delay to use nops. They have been tested working.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fix 500 scan rate

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
This is "tested it still types" not "validated the gpio is in expected state with an oscilloscope", right?

**Comment by Xelus22** [comment]
This is "tested it types" and I have given it to multiple users and have not had any complaints.

**Review by drashna — APPROVED** [review]

**Comment by zvecr** [comment]
I guess what I'm getting at is, I'm not a massive fan of the change and how it might propagate through the repo. And if changing the base config files for system timer config gives some improvement (but not quite the same) to scan rate as well as general microsecond accuracy, would rather see that. An issue of longer term maintainability.

That aside, the change itself looks fine.

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Maybe throw a comment in `matrix_io_delay()` saying something like
```c
// Tested and verified working on the Xxxx keyboard
```
...just so when the inevitable copypasta occurs we can challenge subsequent PRs as far as validity is concerned. I know for a fact that this is too fast on the Djinn as it runs at 160MHz and electrically things don't "settle" after 3 `nop`s -- others will likely be in the same boat in the future.

The DMA remap is a prime example of @zvecr's reluctance... people put it in without understanding the implications... the I/O delay will cause the same confusion without an explanation as to why it exists.

**Review by drashna — APPROVED** [review]

**Pull request merged**
