### PR TITLE
[Keyboard] Add ISO layout for Durgod K320

### PR DESCRIPTION
**Pull request by nomis**
## Description

Add ISO layout for Durgod K320. This is mostly a copy of the ANSI layout but I've fixed the macro to match where the keys are.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by nomis** [comment]
I've had to add a fix for the media keys because these are wrong in the existing ANSI layout.

**Review by spidey3 — CHANGES_REQUESTED** [review]
Now that #11778 and #11885 have been merged, this PR has merge conflicts.
Can you please rebase, and push again?

**Comment by dkjer** [comment]
I believe #11778 covers these changes, at this point.

**Comment by nomis** [comment]
> I believe #11778 covers these changes, at this point.

That still has the wrong Fn+F3 and Fn+F4 media keys.

**Comment by dkjer** [comment]
> > I believe #11778 covers these changes, at this point.
> 
> That still has the wrong Fn+F3 and Fn+F4 media keys.

Thanks for catching that.  I updated #11978 with a fix for these media keys

**Pull request closed without merging**
