### PR TITLE
Remove custom user code

### PR DESCRIPTION
**Pull request by waffle87**
## Description

Removes `users/*`, `layouts/community/*`, and user/non-default(ish) keymaps in an effort to reduce unmaintained code throughout the repository.

## Types of Changes

- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
We should have a discord command (as well as an FAQ entry) ready to go before this gets merged/hits master.

**Comment by daskygit** [comment]
Are we not keeping vendor keycaps?

**Comment by tzarc** [comment]
> Are we not keeping vendor keycaps?

You probably meant keymaps :P

---

@waffle87 -- after today's board meeting, given the fact that there are a bunch of default-ish or vendor keymaps deleted, we've decided we're going to approach the removal slightly differently.

* We'll produce a full list of keymap names across the entire repository, either by maintaining a GDoc or  a separate branch
* Amongst ourselves determine which keymap names are to be kept
* Create a script that can remove only the listed set of keymaps
* Perform the deletion en-masse

The aim is to still do this for the November 2023 merge date -- further discussion will be on Discord.

**Comment by thomasbaart** [comment]
Hi! I noticed our `debug` keymaps are included in this removal, and I'd like to kindly request to have those exempt, as we refer to them in our build guides and depend on the build process to have them present.

If this is undesirable, please do let me know as well so I can see if we can work around that in a different way. Thank you!

**Comment by mmccoyd** [comment]
Can I vote for keeping the hillside/xx/default_dot_c keymaps, as the hillside's creator? Providing defaults of  .json and .c seemed desirable. If not, I can reexamine having a default.json, given that vial exists.
Thanks!

**Comment by tzarc** [comment]
> Can I vote for keeping the hillside/xx/default_dot_c keymaps, as the hillside's creator? Providing defaults of .json and .c seemed desirable. If not, I can reexamine having a default.json, given that vial exists. Thanks!

Under normal circumstances, people can migrate from json-based to C-based using `qmk json2c`. No generalised documentation exists pointing people at anything like `default_dot_c`, and `qmk new-keymap` will duplicate `default` anyway.

Other than C vs. JSON, is there anything else in particular as to why you're advocating for keeping both?

**Comment by mmccoyd** [comment]
> Other than C vs. JSON, is there anything else in particular as to why you're advocating for keeping both?

Nothing more. Guess I'm not up to date on the conversions. 
Thanks.

**Pull request closed without merging**
