### PR TITLE
<!--- Provide a general summary of your changes in the title above. -->

### PR DESCRIPTION
**Pull request by rpbaptist**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by jackhumbert** [comment]
Hey! It looks like you opened this on qmk:master instead of your fork - I'll go ahead and close it, but let me know if I'm mistaken :)

**Comment by rpbaptist** [comment]
Yeah, sorry about that. I am using `hub` command line tool and GitHub defaults to the original repo.

**Comment by jackhumbert** [comment]
Ah nice! We love `hub` :)

**Comment by drashna** [comment]
Yup, we do.  I know that I use it extensively.

And for `hub pull-request`, you want to add `-b remote:branch` to target a specific repo and branch. 
Also, you can use `-F filename` to specify a template file, too.

**Pull request closed without merging**
