### PR TITLE
handwired/myskeeb Layout Macro Refactor

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

* removes unused positions from the layout macro and keymaps
* physically arranges `info.json` layout data
* adds keyboard image, supported hardware and flashing example to readme

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
Forgot to cc @su8044 (keyboard maintainer)

PR does the layout portion of this:

image

**Comment by su8044** [comment]
Cool, thanks! is there any interaction i should do on my behalf?

**Comment by noroadsleft** [comment]
@su8044 None needed; I'll have a follow-up PR that updates the keymap on QMK Configurator.

**Comment by noroadsleft** [comment]
@su8044 After this gets merged, it will be a good idea to resynchronize your fork of the `qmk_firmware` repo so it matches what will be on QMK's repository.

https://docs.qmk.fm/#/newbs_git_resynchronize_a_branch

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
