### PR TITLE
Add an alternative method for keyboard discovery to speed up build

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Discussed within #6065.

The main take-away is that windows vagrant and macos docker can have poor filesystem performance. This PR attempts to work around that issue by providing a method of keyboard discovery that seems to be faster, up to a factor of 3x.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
I figured it would help get the PR in sooner, as I would have to test it on the platforms for portability.

Would people agree to a 2nd pass for updating the default behaviour, and then much testing?

**Comment by drashna** [comment]
Was this okay, as is?

**Comment by zvecr** [comment]
@drashna Should be fine as is. We can get some confidence with the alt method, and maybe open up another PR to change the default at a later date.

**Comment by drashna** [comment]
Well, unless there is an objection, I think i"m going to merge this, then.

**Pull request merged**
