### PR TITLE
new keymap macro for dm-5x6. (reversed)

### PR DESCRIPTION
**Pull request by ibnuda**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by ibnuda** [comment]
what should I do to help to solve this issue?

**Comment by drashna** [comment]
You may need to run `make git-submodule` and add a new commit.

**Comment by drashna** [comment]
Nope, that didn't do it.  It's been a while since I've done this, so @noroadsleft, comments? 

I think you may need to "cd" into each folder, and reset them to master.  eg:
```sh
cd lib/(name)
git add .
git reset origin/master --hard
```
And then commit and push (and you may need to add `--allow-empty` for th ecommit.

**Comment by ibnuda** [comment]
i am closing this issue and then create another pull request to lessen the headache.

**Pull request closed without merging**
