### PR TITLE
[Bugfix] Delete duplicate readme in unigo66

### PR DESCRIPTION
**Pull request by distransient**
Triggers case sensitivity issues on windows.

## Types of changes
- [x] Bugfix

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
There's actually a commit in #5108 that takes care of the duplicate readme (by removing the file with the uppercase name).

**Comment by drashna** [comment]
And merged.  But thank you for opening this!

**Comment by distransient** [comment]
Resolved before I had a chance to update the PR! Bless. ^^

**Comment by drashna** [comment]
Yup.  Though the author for the unigo66 had a PR open already, and we flagged them there.  Since they were already messing with the files ...

**Pull request closed without merging**
