### PR TITLE
RGB Matrix: Custom effects on a kb/user level

### PR DESCRIPTION
**Pull request by daniel5151**
The current method of creating custom RGB Matrix lighting effects from kb/user is by calling `rgb_matrix_set_color` from methods such as `process_kb/user`, `matrix_scan_kb/user`, or `rgb_matrix_indicators_kb/user`. While this works fine for overriding a few LEDs here-and-there (to indicate caps-lock, or indicating the current layer), it's quite inefficient when overriding all LEDs, since RGB Matrix is still running it's own effects in the background.

This PR introduces a cleaner, more unobtrusive way to extend the RGB Matrix system, adding new effects and having them act just like built in ones (i.e: accessed through RGB_TOG)

## Description

See discussion below and updated docs for usage info.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* #5329 

## Checklist

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
if possible, could you add documentation for this, as well as an example of how to utilize this?

**Comment by daniel5151** [comment]
Due to the in-flux nature of the interface, I was going to write the Docs once the implementation was settled-on.

**Comment by Lenbok** [comment]
I think it would be great if both rgb matrix and rgb underglow had more commonality in terms of how the user specifies which modes they want enabled in their firmware. Underglow is via defines which lets you disable those you aren't interested in but currently has no mechanism to add user modes, so something like this would be useful there.

Does this PR let you disable preexisting modes you don't like? (And ideally reclaim the firmware space)

**Comment by yanfali** [comment]
Not a huge fan of

```c
const uint8_t rgb_matrix_effects_kb_count;
const uint8_t rgb_matrix_effects_user_count;
```

is there some way to look at size of array at compile time and avoid the manual book keeping?

**Comment by daniel5151** [comment]
@Lenbok I agree, but I don't think those changes fall under the scope of this PR.
AFAIK, RGB Matrix already has a way to disable individual effects using defines, see the docs [here](https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-effects). That said, disabling the effect doesn't actually reclaim any firmware space, which is silly, and should be fixed at some point.

@yanfali I agree, it's not great, but unfortunately, the size of arrays can't be easily reconstructed in another compilation unit when using weakly-linked symbols. Some sort of count has to be manually maintained.

One potential alternative to get around this is to introduce a helper macro, something like the following:
```c
#define EXPORT_RGB_MATRIX_EFFECTS_USER(...) \
  const rgb_matrix_effect_f rgb_matrix_effects_user[] = { __VA_ARGS__ }; \
  const uint8_t rgb_matrix_effects_user_count = sizeof(rgb_matrix_effects_user)/sizeof(rgb_matrix_effects_user[0]);
// same thing for KB

// usage (in keymap.c):
static void my_kool_effect(bool init) {}
static void my_kool_effect2(bool init) {}

EXPORT_RGB_MATRIX_EFFECTS_USER(
  my_kool_effect, 
  my_kool_effect2
);
``` 

Thoughts on this Macro based approach?

**Comment by yanfali** [comment]
@daniel5151 if it's less error prone for users I think it's probably worth considering. Managing a count for something that you've already defined just seems like a recipe for people coming to the discord help channel.

**Comment by XScorpion2** [comment]
So I applied this function pointer approach to rgb_matrix ([branch here](https://github.com/XScorpion2/qmk_firmware/pull/new/tech_debt/function_ptr)) as a test and here's my notes 

- Function pointer array & array initialization takes up more firmware space than the switch statement does (~300 bytes, this seems very wrong, but I double checked it...will triple check later).
- It's extremely easy for a user to end up out of bounds, by accessing a null element or out of bounds.
- rgb_matrix_config.mode is allowed, and valid to be out of bounds for certain values, and the matrix code controls eeprom reading of the value. So changing keymap could cause eeprom value to be invalid after flashing.

I wonder if an approach similar to keycodes are handled might not be a safer & smaller solution. ex: `bool process_rgb_effect(uint16_t effectcode)`. I still like the idea of not having a giant switch statement, but not sure the trade offs are worth it.

**Comment by daniel5151** [comment]
- ~300 bytes definitely seems like a lot. It can't imagine what changes could result in such a large codesize increase. We should look into this further at some point.
- OOB issues can be mitigated with the automatic bookkeeping macro (as proposed above), and with some sanity-checks in the rgb_matrix init methods (i.e: when reading from eeprom).

Just to clarify something though, this PR isn't aiming to do a full function-pointer conversion.
So while this exploration is useful, and will certainly help guide how we approach refactoring the system in the future, I'm not sure it's findings are relevant to this PR in particular.

Moreover, I'd just like to stress that this PR doesn't bloat the firmware size, given that it merely adds a couple of hooks, exports a couple of symbols, and tweaks some statements here and there.

**Comment by XScorpion2** [comment]
So I think the PR implementation is great, and want to approve it, but I think it is worth discussing the pros and cons a bit more and the limitations or issues of this approach.

- As for how my conversion test is relevant, it gives a comparison of similar approaches to a known problem: how to pick and call the correct animation function. In this pr case though, if a qmk user had the choice between the two options, function pointers vs switches with the trade offs that switches being smaller firmware size, tiny perf hit, I think it will depend on the board, there are many that are at the wire today for firmware sizes.
- As for OOB, yes it can be mitigated with book keeping, though we really should move certain globals to statics so there is less of an issue in outside manipulation. Mainly I was just bringing this up to ensure this part of the code is reviewed closely.

I'm going to look at the assembly and see what the hell caused that size increase, cause that is just crazy.

**Comment by daniel5151** [comment]
I've gone ahead an added in the helper macros as discussed above, along with some OOB checks that should prevent any nastiness when removing custom effects on boards with EEPROM.
These new helper macros and OOB checks make it a lot harder for users to shoot themselves in the foot, though please double check that I haven't missed any other obvious footguns :)

I've added docs on how to define custom effects, and also updated the PR's description to reflect the new recommended usage. There hasn't been to much pushback on this current design (weakly-linked array+len with bookkeeping macros), so I think we can push forward with it.

**Comment by XScorpion2** [comment]
Will be looking at the size increase a bit more this weekend, but wanted to follow back up before then with a request for a small api change on the function pointer:
```c
typedef bool (*rgb_matrix_effect_f)(bool init, uint8_t iter);
```
This api change is needed to allow for rendering of a single frame over several update ticks. The animation function returns true if it needs to do more work, false if not. iter is a count of how many times it has been called while it still needed more work to be done. This allows us to break up calculating the led data over several ticks instead of all at once potentially causing scanning delays.

**Comment by daniel5151** [comment]
SGTM.

Could you give an example of how this should be used in the custom effect fn + how the the effects should be called from rgb_matrix.c? I'll update the API + docs accordingly.

**Comment by XScorpion2** [comment]
I still need to verify some ideas around this, task to do this weekend, but here's an example:

```c++
bool rgb_matrix_solid_splash(bool init, uint8_t iter) {
  // solid_splash is expensive, we know it ranges from 4ms to 10ms
  // so we want it to iterate 2 to 5 times based on the number of items we are tracking
  // So setup the range we need to operate over
  uint8_t count = 2 + (g_last_hit_tracker.count + 3 - 1) / 3;
  uint8_t led_count = (DRIVER_LED_TOTAL + count - 1) / count;
  uint8_t led_min = led_count * iter;
  uint8_t led_max = led_min + led_count;
  if (led_max > DRIVER_LED_TOTAL)
    led_max = DRIVER_LED_TOTAL;

  for (uint8_t i = led_min; i < led_max; i++) {
    // Do work on this led range
  }
  return led_max < DRIVER_LED_TOTAL;
}
```

The idea is that the animation time slices itself base on it's own knowledge of it's performance characteristics at the time of being called. It will do work each tick until it is complete, and once it is complete, the buffers (rgb_config_t, ticks, etc) that drive the animations will then be updated via a memcpy from an internal double buffer. Most of this loop setup can be extracted out into a utility function with the correct parameters for easier use in custom animations. So that way an animation like solid can just run normally without doing anything special, but the heavier ones can be designed in a way that lets them scale.

**Comment by daniel5151** [comment]
Ah, gotcha.

My one concern would be the feature-creep that this change entails. I don't think this PR should be the one to implement the (what I assume to be) non-trivial logic to support the returned `bool` + `uint8_t iter` parameter (i.e: the double-buffering of environment variables, iteration counting, etc.).

I don't mind changing the fn signature as a future-proofing measure for once your RGB Matrix overhaul PR lands, though I think it might be best to stub-out the extended functionality this modified API suggests, and add a note that the `bool` return value + `uint8_t iter` are ignored/unused at the moment.

Thoughts?

**Comment by XScorpion2** [comment]
Ya, I was thinking the same. Stub it out until a future PR lands with the work. I don't think my matrix refactor will contain this work either as it's already fairly long too. But I do want to use that refactor as a base for this timeslice implementation

**Comment by XScorpion2** [comment]
@daniel5151 Here's the final implementation I ended up with:
https://github.com/qmk/qmk_firmware/pull/5372/commits/52055b9095ff8011c99b4b4fa5d459bbe759fcf3

**Comment by daniel5151** [comment]
@drashna status update on potentially getting this merged?

The interface has been agreed upon and stabilized, and the docs have been updated accordingly :smile:

**Comment by drashna** [comment]
I'm waiting on other people to approve the changes here, actually.

**Comment by XScorpion2** [comment]
@daniel5151 mind updating the API one more time:
```c
typedef struct {
  uint8_t iter;
  uint8_t flags;
  bool init; // debating on if this should be rolled into flags
} effect_params_t;

typedef bool (*rgb_matrix_effect_f)(effect_params_t* params);
```

The idea behind this change is so that, one, we can update animation parameters as needed without changing a bunch of code, and two, the additional flags parameter will go a long ways to allowing different animations running on different sets of LEDs.

For example, using flags I can mask out LEDs to have breathing effect on modifiers, cycle left to right on underglow, and reactive on the remaining easily.

**Comment by daniel5151** [comment]
It sounds like what you really want me to do is wait for the overhaul to land and build on-top of whatever interface stabilizes from it. I can do that, I don't mind.

I'll leave this PR open, but let's not merge anything until #5372 wraps up and we have a concrete idea of how things will work in the future.

**Comment by XScorpion2** [comment]
Either one can land first, and really this is my mistake. I should have gone with the struct parameters approach sooner as it makes things a lot more flexible for future improvements with less code changes.

**Comment by daniel5151** [comment]
No no, that's fine! The best approach only becomes clear after writing and testing code, so it's expected. I suspect that more subtle tweaks will continue to surface, so instead of continuously iterating to match you, I don't mind waiting until things land and stabilize :smile:

**Comment by XScorpion2** [comment]
So went back and looked into function pointer causing firmware size increases. Turns out the problem is with link time optimizations. 
lto turned on: firmware size with function pointers is 646 bytes larger
lto turned off: firmware size with function pointers is 84 bytes smaller
This is the same code changing between using function pointers for effects vs the giant switch statement. So it would appear that lto is not able to handle function pointers all that well at compile time, thus requiring additional information to handle it at link time. Now that I understand why, going to see what I can do to fix that (besides fixing it in the compiler)

**Comment by daniel5151** [comment]
Ah, interesting!

By the way, not sure if you've seen [this](https://github.com/qmk/qmk_firmware/issues/3224#issuecomment-399769416), but LTO causes other issues in QMK too. 
Just something to keep on the radar.

**Comment by XScorpion2** [comment]
Ya, my CTRL has lto turned of because of some issue, I forgot what it was now. my Preonic and SOL both have it turned on with no problems there. Over all though I'm glad it's limited to just lto is not able to decrease the size of that compiled unit.

**Comment by drashna** [comment]
@XScorpion2 probably because the arm gcc 8.x has issues with LTO in general.  

@daniel5151 Macros and functions are deprecated, and shouldn't be used anyways.  So, aside from compiler issues, there aren't really any other issues with LTO. At least on AVR.

**Comment by XScorpion2** [comment]
So one nice thing we can do with the function pointer array that would make it really easy is allow keyboard level and user level include files that just list the functions and we can easily just append them to a single array at compile time:

```c
const static matrix_effect_f effect_list[] = {
  #include "rgb_effect_list.h"
#ifdef RGB_KEYBOARD_EFFECTS
  #include "rgb_effect_list_kb.h"
#endif
#ifdef RGB_USER_EFFECTS
  #include "rgb_effect_list_user.h"
#endif
};
```

and the include file for those would look like this:

```c
    rgb_matrix_none,
    rgb_matrix_solid_color,           // Max 1ms Avg 0ms
#ifndef DISABLE_RGB_MATRIX_ALPHAS_MODS
    rgb_matrix_alphas_mods,           // Max 2ms Avg 1ms
#endif // DISABLE_RGB_MATRIX_ALPHAS_MODS
```

as a shortened example.

**Comment by daniel5151** [comment]
nit, but I wouldn't use the `.h` extension for the effect_list files. Something like `.inc` might be more appropriate.
Other than that though, I think that's a good solution!

**Comment by XScorpion2** [comment]
I'm not going to rework the overhaul pr and update it, but this will be a followup pr.

Another option if LTO proves to be impossible to fix would be to do something similar but inline in the switch statement itself:

```c
  switch (effect) {
    #include "rgb_effect_list.inc"
#ifdef RGB_KEYBOARD_EFFECTS
    #include "rgb_effect_list_kb.inc"
#endif
#ifdef RGB_USER_EFFECTS
    #include "rgb_effect_list_user.inc"
#endif
  }
```

```c
    case RGB_MATRIX_NONE:
      rendering = rgb_matrix_none(&rgb_effect_params);
      break;

    case RGB_MATRIX_SOLID_COLOR:
      rendering = rgb_matrix_solid_color(&rgb_effect_params);           // Max 1ms Avg 0ms
      break;
#ifndef DISABLE_RGB_MATRIX_ALPHAS_MODS
    case RGB_MATRIX_ALPHAS_MODS:
      rendering = rgb_matrix_alphas_mods(&rgb_effect_params);           // Max 2ms Avg 1ms
      break;
#endif // DISABLE_RGB_MATRIX_ALPHAS_MODS
```

which also would require doing an inline include in the effect enum as well:

```c
enum rgb_matrix_effects {
  RGB_MATRIX_NONE = 0,
	RGB_MATRIX_SOLID_COLOR = 1,
#ifndef DISABLE_RGB_MATRIX_ALPHAS_MODS
  RGB_MATRIX_ALPHAS_MODS,
#endif // DISABLE_RGB_MATRIX_ALPHAS_MODS

...

#ifdef RGB_KEYBOARD_EFFECTS
    #include "rgb_effect_enum_kb.inc"
#endif
#ifdef RGB_USER_EFFECTS
    #include "rgb_effect_enum_user.inc"
#endif

  RGB_MATRIX_EFFECT_MAX
};
```

and then I feel that gets a bit messy, though does save a lot on firmware space with LTO.

**Comment by daniel5151** [comment]
Oof, that really makes the `.inc` file nasty...
That said, a couple of helper macros could help to cut down on the boilerplate, so it's not infeasible.

**Comment by XScorpion2** [comment]
ya, I'm going to sit and mull on this a bit more over the weekend. Looked at the assembly dump between the two approaches and the function pointer array just scales so poorly and I've yet to find a gcc attribute or flag or something to improve that. ARM scales worse than AVR oddly enough.

**Comment by XScorpion2** [comment]
So just a quick drunken pass at the idea using macros to help cut down the boilerplate:
https://github.com/XScorpion2/qmk_firmware/commit/030edc0b61228572657d5b64bd38ab9b455fa783

The gist is that a keyboard or user will need to enable custom keyboard or user effects via the `RGB_MATRIX_KEYBOARD` and/or `RGB_MATRIX_USER` define, create 2 files: `rgb_matrix_kb.h` & `rgb_matrix_kb.inc` and/or `rgb_matrix_user.h` & `rgb_matrix_user.inc`. The `.h` file is where they dump in their custom effect function using the format: `static bool rgb_matrix_<name>(effect_params_t* params)` the `.inc` file is where they declare their enums and functions via a single `RGB_EFFECT` macro. At that point they will be able to set their effect using the enum directly as it will be declared as `RGB_MATRIX_<NAME>` or call their function directly via `rgb_matrix_<name>` Example:

```c
static bool rgb_matrix_my_unique_effect1(effect_params_t* params) {
    // todo
}

static bool rgb_matrix_my_unique_effect2(effect_params_t* params) {
    // todo
}
```

```c
RGB_EFFECT(MY_UNIQUE_EFFECT1, my_unique_effect1)
RGB_EFFECT(MY_UNIQUE_EFFECT2, my_unique_effect2)
```

Thoughts?

**Comment by daniel5151** [comment]
Well, it's a lot of rigmarole (having to touch anywhere from 3-5 files), but if function pointers are out of the question, this approach would work. That said, if the bugs are ironed out, my personal preference is still function pointers, since it's a _lot_ simpler to use.

Could you elaborate on how the RGB_EFFECT macro would work? Unless my CPP-fu is failing me, I don't see how a single macro can both declare the enum, and expose the effect.

**Comment by XScorpion2** [comment]
In the example changeset, the define is undefined and redefined right before each type of include usage. This allows it to change how it is imported into the current file. I'm still poking at the function pointer concept as I do like that approach better, but so far it looks like firmware size is the limiting factor as I've yet to find a way to improve that.

**Comment by drashna** [comment]
#5372 has been merged, and has caused conflicts here. 

Could you update this?

**Comment by daniel5151** [comment]
Great to see that the overhaul got merged! How exciting!

I'll try to find some time to update this PR to work with the new system. Hopefully I can get something ergonomic up and running soon enough :)

**Comment by daniel5151** [comment]
I had a change to play around with implementing this approach, and I think I've got something pretty awesome. Using some CPP magic, we can roll the `.h` and `.inc` into a single `.inc` file, with a single NEW_EFFECT macro serving triple-duty in declaring the new effect's enum, switch case, and implementation!

This still requires a user to define RGB_MATRIX_USER (either through Makefiles or config.h, TBD), but that's fine.

Defining new effects is as easy as writing a `rgb_matrix_user.inc` file that look like this:
```c
NEW_EFFECT(my_cool_effect, {
  RGB_MATRIX_USE_LIMITS(led_min, led_max);
  for (uint8_t i = led_min; i < led_max; i++) {
    rgb_matrix_set_color(i, 0xff, 0xff, 0x00);
  }
  return led_max < DRIVER_LED_TOTAL;
})

NEW_EFFECT(my_cool_effect2, {
  RGB_MATRIX_USE_LIMITS(led_min, led_max);
  for (uint8_t i = led_min; i < led_max; i++) {
    rgb_matrix_set_color(i, 0xff, 0x00, 0xff);
  }
  return led_max < DRIVER_LED_TOTAL;
})
```

If the user-facing side looks good, I'll polish up the implementation and push it up :smile:

**Comment by XScorpion2** [comment]
@daniel5151 that looks slick, not completely sure on how you pull that off, but that looks good.

**Comment by drashna** [comment]
And massdrop PR merged, so some more merge conflicts here

**Comment by daniel5151** [comment]
I was thinking about that single-macro approach, and while slick, I thought it was a bit _too_ magical. I've gone ahead and pushed what I think is a good compromise between compactness and readability.

I'll copy-paste the relevant excerpt from the updated docs here:

---


By setting `RGB_MATRIX_CUSTOM_USER` (and/or `RGB_MATRIX_CUSTOM_KB`) in `rule.mk`, new effects can be defined directly from userspace, without having to edit any QMK core files.

To declare new effects, create a new `rgb_matrix_user/kb.inc` that looks something like this:

```C
// !!! DO NOT ADD #pragma once !!! //

// Step 1.
// Declare custom effects using the RGB_MATRIX_EFFECT macro
// (note the lack of semicolon after the macro!)
RGB_MATRIX_EFFECT(my_cool_effect)
RGB_MATRIX_EFFECT(my_cool_effect2)

// Step 2.
// Define effects inside the `RGB_MATRIX_CUSTOM_EFFECT_IMPLS` ifdef block
#ifdef RGB_MATRIX_CUSTOM_EFFECT_IMPLS

// e.g: A simple effect, self-contained within a single method
static bool my_cool_effect(effect_params_t* params) {
  RGB_MATRIX_USE_LIMITS(led_min, led_max);
  for (uint8_t i = led_min; i < led_max; i++) {
    rgb_matrix_set_color(i, 0xff, 0xff, 0x00);
  }
  return led_max < DRIVER_LED_TOTAL;
}

// e.g: A more complex effect, relying on external methods and state, with
// dedicated init and run methods
static uint8_t some_global_state;
static void my_cool_effect2_complex_init(effect_params_t* params) {
  some_global_state = 1;
}
static bool my_cool_effect2_complex_run(effect_params_t* params) {
  RGB_MATRIX_USE_LIMITS(led_min, led_max);
  for (uint8_t i = led_min; i < led_max; i++) {
    rgb_matrix_set_color(i, 0xff, some_global_state++, 0xff);
  }

  return led_max < DRIVER_LED_TOTAL;
}
static bool my_cool_effect2(effect_params_t* params) {
  if (params->init) my_cool_effect2_complex_init(params);
  return my_cool_effect2_complex_run(params);
}

#endif // RGB_MATRIX_CUSTOM_EFFECT_IMPLS
```

**Comment by XScorpion2** [comment]
Looking good!

**Comment by drashna** [comment]
Well, one concern I have: 

To make sure, the `inc` can be "anywhere" that is in the VPATH for QMK?  
Or is there a specific folder that they will need to be in? 

From the documentation, it's not exactly clear (or I am an idiot and completely missed it)

**Comment by daniel5151** [comment]
As long as `#include "rgb_matrix_user.inc"` can be resolved correctly, it will work. So yes, anywhere in the VPATH (though for consistency, kb.inc should go in the keyboard folder, and user.inc should be in the keymap folder.

**Comment by drashna** [comment]
[Keyboard and user modes for RGB Matrix](https://trello.com/c/gqeJyc33/10-keyboard-and-user-modes-for-rgb-matrix)

**Comment by drashna** [comment]
[Keyboard and user modes for RGB Matrix](https://trello.com/c/gqeJyc33/10-keyboard-and-user-modes-for-rgb-matrix)

**Comment by daniel5151** [comment]
Heyo, any updates? 

Also, I think we can remove the needs-docs tag 😄

**Comment by XScorpion2** [comment]
@drashna anything left before merging this pr?

**Comment by daniel5151** [comment]
Awesome! Great work everyone!

Hopefully we'll see some pretty interesting new lighting effects popping up in user-space now 😄

**Pull request merged**
