### PR TITLE
move @kkatano 's keyboards to kkatano user folder

### PR DESCRIPTION
**Pull request by peepeetee**
## Description
Boards moved:
* bakeneko60
* bakeneko65
* bakeneko80
* wallaby
* yurei

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by noroadsleft — CHANGES_REQUESTED** [review]
* `keyboards/kkatano/bakeneko65/rev3/readme.md` doesn't reference the new directory in the `make` instructions.

**Comment by peepeetee** [comment]
> * `keyboards/kkatano/bakeneko65/rev3/readme.md` doesn't reference the new directory in the `make` instructions.

fixed

**Comment by drashna** [comment]
Can you verify that all of the effected keyboards compile properly?  Both the default and via keymaps?

**Comment by peepeetee** [comment]
> Can you verify that all of the effected keyboards compile properly? Both the default and via keymaps?

Just rechecked
image

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
