### PR TITLE
Add ISO backslash key position to facew matrix and keymap files

### PR DESCRIPTION
**Pull request by jbyauk**
## Description

The `LAYOUT_all` macro for the facew keyboard matrix was missing an entry for the ISO backslash key. 
 This key is present on the PCB, so I added it to the macro and updated the keymaps which use it.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

None

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
Tagging @mechmerlin so he's aware of this change to his keymap.

**Comment by mechmerlin** [comment]
This looks good! But since you're adding an extra key, you'll need to put this same change into the corresponding LAYOUT macros in `info.json` in order for the QMK Configurator to correctly generate the visuals.

**Comment by jbyauk** [comment]
I updated `info.json` to include a key at the appropriate position for the layout using macro `LAYOUT_all`.  `LAYOUT_60_ansi` is not affected.  The Travis build error doesn't look to be caused by this change-- it also happens when I run `make facew:mechmerlin` in a clean, up-to-date master branch.

**Comment by drashna** [comment]
Thanks

**Pull request merged**
