### PR TITLE
Update wb32-dfu

### PR DESCRIPTION
**Pull request by wb-Joy**
## Description

Since bootloader.mk adds BOOTLOADER_TYPE but does not add WB32-DFU related to  BOOTLOADER_TYPE, I submit this PR hoping that it can be combined in 2022q1.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by wb-Joy** [comment]
Why can't you merge in 2022q1.

**Comment by fauxpark** [comment]
You missed the cutoff.
https://docs.qmk.fm/#/breaking_changes?id=important-dates

**Comment by wb-Joy** [comment]
All right, I should have noticed this sooner.

**Comment by drashna** [comment]
Also, master is locked today.  So that's a "hard miss".

**Comment by wb-Joy** [comment]
Could this PR be merged as soon as possible? I have a keyboard and need it.

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Pull request merged**
