### PR TITLE
NEW KEYBOARD: 1up60hse

### PR DESCRIPTION
**Pull request by mechmerlin**
1upkeyboards has a new board they would like to get into QMK proper. It has a different switch matrix than the 1up60rgb. From a user perspective, the two major changes are USB C and hotswappable sockets.

### CODE REVIEW

**Comment by drashna** [comment]
Thanks!

**Comment by therg** [comment]
After flashing the 1up60hse the keymap is not being applied properly. I'm wondering if the matrix is defined incorrectly, or perhaps I did something wrong. This is being compiled and flashed on MacOS 10.13.6 with an updated copy of QMK and dependencies installed with `./util/qmk_install.sh`.

Some examples of keys mapped to what they are registering:
```
esc: no response
1: no response
2: no response
3: 3
4: no response
5: no response
6: no response
7: 3
8: no response
9: shift + gui
q: lowering display brightness
w: numpad .
e: 3
r: no response
t: delete
y: no response
u: no response
i: no response
o: no response
p: enter
```

Flashing output:
```
 ~/code/qmk_firmware: make 1upkeyboards/1up60hse:default:dfu
QMK Firmware 0.5.110
Making 1upkeyboards/1up60hse with keymap default and target dfu

avr-gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text	   data	    bss	    dec	    hex	filename
      0	  26184	      0	  26184	   6648	.build/1upkeyboards_1up60hse_default.hex

Compiling: tmk_core/common/command.c                                                                [OK]
Linking: .build/1upkeyboards_1up60hse_default.elf                                                   [OK]
Creating load file for flashing: .build/1upkeyboards_1up60hse_default.hex                           [OK]
Copying 1upkeyboards_1up60hse_default.hex to qmk_firmware folder                                    [OK]
Checking file size of 1upkeyboards_1up60hse_default.hex                                             [OK]
 * File size is fine - 26184/28672 (2488 free)
dfu-programmer: no device present.
Error: Bootloader not found. Trying again in 5s.
dfu-programmer: no device present.
Error: Bootloader not found. Trying again in 5s.
Bootloader Version: 0x00 (0)
Erasing flash...  Success
Checking memory from 0x0 to 0x6FFF...  Empty.
Checking memory from 0x0 to 0x667F...  Empty.
0%                            100%  Programming 0x6680 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
0%                            100%  Reading 0x7000 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
Validating...  Success
0x6680 bytes written into 0x7000 bytes memory (91.52%).
```

**Comment by drashna** [comment]
Does the default keymap from here work: https://qmk.fm/keyboards/

**Comment by therg** [comment]
@drashna thanks, that precompiled hex does work so it must be a local issue during the compilation. I haven't had any issues like this with past boards compiling/flashing via make targets in the QMK repo.

**Comment by drashna** [comment]
what version of avr gcc are you using?  (run `avr-gcc --version` to check).  If it's 8.2, that's a problem. If it's 8.1 ... it may be a problem too.  7 is the best bet to use, honestly.

**Comment by therg** [comment]
`avr-gcc (GCC) 7.3.0`

**Pull request merged**
