### PR TITLE
Update keymap.md to QMK

### PR DESCRIPTION
**Pull request by osamuaoki**
doc/keymap.md is TMK.  I updated it to QMK.

### CODE REVIEW

**Comment by fredizzimo** [comment]
[Here](https://github.com/qmk/qmk_firmware/issues/759) we agreed to move the documentation to the Wiki. So I think the file should be deleted and the information moved to the Wiki instead.

**Comment by osamuaoki** [comment]
I agree.  Wiki contents as submodule at doc and (re)move all existing doc content there seems very good idea.  Data size of keymaps[] and description "Legacy Keymap" really confused me...

**Comment by jackhumbert** [comment]
Thanks for making these changes! I'll go ahead and merge things, and we'll work out the migration to the wiki later :)

**Comment by osamuaoki** [comment]
I worked on wiki a bit.  I see Home.md is becoming too big.  Let me sleep and comeback later to address this.

**Pull request merged**
