### PR TITLE
Add Teensy 3.6 sample / test keyboard

### PR DESCRIPTION
**Pull request by walkerstop**
## Description
Add test keyboard that uses Teensy 3.6 project board

## Types of changes
- [x] Core
- [ ] Bugfix
- [ ] New Feature
- [ ] Enhancement/Optimization
- [x] Keyboard (addition or update)
- [x] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by walkerstop** [comment]
@drashna @jackhumbert @fredizzimo I accidentally closed the original pull request so I had to create a new one after fixing the merge conflicts and removing the unnecessary fatfs documentation, please review

**Comment by mechmerlin** [comment]
Test is failing on the tetris keyboard with "firmware is too large".

**Comment by mechmerlin** [comment]
@walkerstop why do the ChibiOS submodules need to be updated?
Also why is FATFS needed in the sample code?

**Comment by drashna** [comment]
For reference: https://github.com/qmk/qmk_firmware/pull/2881

**Comment by walkerstop** [comment]
@mechmerlin chibios-contrib was pointing to some branch called "k-type-fix" that's a year old and was entirely missing the Teensy 3.6 support for ChibiOS.  In the past @fredizzimo told me the up to date branch qmk used for this submodule is "qmk" and that branch has Teensy 3.6 support.

If qmk for some reason now needs to use that older branch then there's no point to this pull request.  If there's some fix to chibios-contrib needed can't that fix instead be merged to the qmk branch rather than using the ancient branch?

Fatfs I used for sample code to test/demonstrate file IO on Teensy 3.6 since it has working micro SD card support on QMK (one of the differences between teensy 3.6 and older teensy boards)

**Comment by drashna** [comment]
@fredizzimo is it okay to merge this?

**Comment by drashna** [comment]
I think, for now, I'm going to close this.  

We have a big ChibiOS update PR in the works, and this should probably wait on that.

Additional, most of the test boards have been moved to `/keyboards/handwired/onekey/`

**Pull request closed without merging**
