### PR TITLE
gmmk/pro/mike1808 keymap

### PR DESCRIPTION
**Pull request by mike1808**
## Description

Add my keymap for gmmk/pro

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by ach5948** [comment]
The RGB Matrix ledmap is a really cool idea!

**Review by drashna — APPROVED** [review]

**Comment by cj360** [comment]
The Ledmap is awesome though I'm at a loss as to why its setting the rgb to white on function layer when I attempt to copy it.

**Comment by mike1808** [comment]
hey @cj360 can you tell me your content of `rules.mk`?

**Comment by cj360** [comment]
Sure thing [here's a gist](https://gist.github.com/cj360/21f2c211e54eb0961812f49254022304).

**Comment by mike1808** [comment]
@cj360 looks fine. I'm curious, why it can set rgb to white. I don't have any code setting it to white. Can you try to run `qmk clean` before compiling it? Also, maybe you have conflicting RGB code in `rgb_matrix_indicators_advanced_user`

**Review by drashna — APPROVED** [review]

**Comment by ForsakenRei** [comment]
The LED matrix is really a cool idea, which will make customized LEDs for layers way easier.
If I want to use it with my existing `keymap.c`, except the LED layout I need to copy to my `keymap.c` and the `rules.mk` I need change, which files will be essential to have the LED layout functionable?

**Comment by mike1808** [comment]
@ForsakenRei that was my initial implementation, but it was consuming a lot of memory. The current inoleme requires you to define a macro mapping each key to RGB index in g_led_config.

**Comment by ForsakenRei** [comment]
> @ForsakenRei that was my initial implementation, but it was consuming a lot of memory. The current implementation requires you to define a macro mapping each key to RGB index in g_led_config.

I see. Thanks for the tip, I will give it a try.

**Review by tzarc — APPROVED** [review]

**Pull request merged**
