### PR TITLE
add split&matrix encoder support

### PR DESCRIPTION
**Pull request by hsakoh**
Enables flexible wiring of Encoders.

## Description

The following issues are in the current encoder feature.
- The same number of encoders are needed for left and right keyboards (#10096).
- The A/B line of Encoder occupies the pin.
　(It is not impossible to wire A/B line to the matrix, but if you wire to GND, you cannot wire in parallel.)

This solves the two issues above.
Similar to #7209, but #10096 will also be improved.

**I created and tested the circuit diagram on [this gist](https://gist.github.com/hsakoh/ca28268f6d7d3f1d24912176c4515354) on a breadboard.**

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* #10096
* #7209

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

I've only been touching QMK for a week now, I may have a fundamental misunderstanding. 
So please be nice and gentle.

### CODE REVIEW

**Comment by hsakoh** [comment]
The changes in #10259 have also been incorporated into this PullRequest feature

**Comment by hsakoh** [comment]
I'm adding a large ifdef and indenting it.
So when reviewing it, I think it would be easier to see if you add "?w=1" like this.
https://github.com/qmk/qmk_firmware/pull/10517/files?w=1

**Review by Erovia — COMMENTED** [review]
`__attribute__((weak))` :heavy_check_mark: 
I don't have the HW to test this.

This is just nitpicking, but IMHO simply "Basic/Advanced" would be better terms than "Basic/Flexible Support".

**Review by Erovia — APPROVED** [review]

**Comment by hsakoh** [comment]
In JP's Discord, mtei pointed out that "peek_matrix can improve the scan rate",
 so I implemented it.

**Comment by mtei** [comment]
The "#if defined()" in the source makes it hard for me to read, so my first comment will focus on mitigating the readability with a formal change.

The following pattern appears four times. The conditional expression is complex.
```c
#if defined(SPLIT_KEYBOARD) && defined(MATRIX_ENCODER_PINS_ABC) && defined(MATRIX_ENCODER_PINS_ABC_RIGHT)
//split keyboard,both encoder
   :
   :
#elif defined(SPLIT_KEYBOARD) && !defined(MATRIX_ENCODER_PINS_ABC) && defined(MATRIX_ENCODER_PINS_ABC_RIGHT)
//split keyboard,right only encoder
   :
   :
#else
//non split keyboard or left only encoder
   :
   :
#endif
```
I made it a little easier to read. -->  https://github.com/mtei/qmk_firmware/tree/10517_matrix_encoder-patch-1

**Comment by mtei** [comment]
The following three functions are easier to read if you separate the body part of the process as static inline functions.

* `void encoder_update()`
* `void encoder_read_all()`
* `void encoder_init()`

Here is an example of `encoder_read_all()`.
```c
static inline 
void encoder_read_all_common(pin_t *current_rows, pin_t *current_matrix, 
                             uint8_t encoder_count,  encoder_t *current_encoders)
{
    bool       isFirstScan      = true;
    for (int i = 0; i < encoder_count; i++) {
        ////
    }
}

static void encoder_read_all(void) {
#    if defined(split_keyboard_both_encoder)
    if (isLeftHand) {
        encoder_read_all_common(row_pins_left, 
                                (pin_t *)matrix_encoders_pins_left,
                                NUMBER_OF_ENCODERS_LEFT,
                                encoders_left);
    } else {
        encoder_read_all_common(row_pins_right,
                                (pin_t *)matrix_encoders_pins_right,
                                NUMBER_OF_ENCODERS_RIGHT, 
                                encoders_right);
    }
#    elif defined(split_keyboard_right_only_encoder)
    encoder_read_all_common(row_pins_right,
                            (pin_t *)matrix_encoders_pins_right, 
                            NUMBER_OF_ENCODERS_RIGHT,
                             encoders_right);
#    else  // non split keyboard or left only encoder
    encoder_read_all_common(row_pins,
                            (pin_t *)matrix_encoders_pins,
                            NUMBER_OF_ENCODERS,
                            encoders)
#    endif
}
```

**Comment by hsakoh** [comment]
The code has been modified in response to the following review.
https://github.com/qmk/qmk_firmware/pull/10517#issuecomment-705495483
->https://github.com/qmk/qmk_firmware/pull/10517/commits/a1d6f54849bc958c7dc8f580a9f4090836baad8d

https://github.com/qmk/qmk_firmware/pull/10517#issuecomment-705514437
->https://github.com/qmk/qmk_firmware/pull/10517/commits/9a1e16be1f7c4874c3aca2c5f665ea724dc50356

**Comment by hsakoh** [comment]
@russbot 
Thanks for the feedback.

I was able to reproduce the behavior of the comments on the PEC12R.
I think you can reproduce it by stopping the encoder with return stop intentionally.

The A-B phase of the rotary encoder takes four states: (0,0)(1,0)(1,1)(0,1).
This diagram represents the internal circuit of the encoder.

image

With Type A wiring, when one of them is at (1,1), it interferes with the other one's reading.
I don't think this behavior would occur with Type B wiring.
Can you verify this with TypeB wiring?

If the Type B wiring seems to solve the problem, I'll add it to the docs.

**Comment by mtei** [comment]
I'm not sure why a Type-B circuit needs a diode to connect to C.

**Comment by hsakoh** [comment]
Haha, so yeah sure, Type B doesn't need a diode in C.

**Comment by hsakoh** [comment]
Conflict is happening, so I'm going to rebase

**Comment by hsakoh** [comment]
I don't want to have this Pull Request for a long time because conflicts happen occasionally, 
so someone please complete the review and merge.

@Erovia 
Or could you assign another reviewer?

**Comment by mtei** [comment]
I tested by connecting encoders to each side of the split keyboard (Helix keyboard) one by one.

* test 1
  ```c
  // config.h
  #define ENCODERS_PAD_A { B6 }
  #define ENCODERS_PAD_B { B5 }
  ```
  * master
    ok
  * PR 10517
    left(master) ok 
    right(slave) encoder don't work
* test 2
  ```c
  // config.h
  #define ENCODERS_PAD_A { B6 }
  #define ENCODERS_PAD_B { B5 }
  #define ENCODERS_PAD_A_RIGHT { B6 }
  #define ENCODERS_PAD_B_RIGHT { B5 }
  ```
  * master
    ok
  * PR 10517
    left(master) ok  
    right(slave) encoder don't work

**Comment by hsakoh** [comment]
@mtei 
I can't confirm the entire config, so I can't say for sure.
Test 1 should work.
Test 2 should work.
Test 3 is as expected.
Test 3b What does it mean that the Index will be 2 and 3? There's only one encoder, right?
Test 4 is as expected.
Test 5 Show me what kind of build errors you're getting

I don't have a Helix keyboard.
Show me the entire firmware config specifically. 
It's easier to check if there is a branch for each test.

**Comment by hsakoh** [comment]
@mtei 
Fixed an build error in Test5.

**Comment by hsakoh** [comment]
The rebase of qmk/develop has made the Diff difficult to see, so the following URL will make it easier to see.
https://github.com/qmk/qmk_firmware/compare/2d468c45a9ed5094f5a4f3a0313b40fb85576073...hsakoh:develop?w=1

**Comment by hsakoh** [comment]
@mtei 
For Tests 1, 2 and 3b
BASIC (ENCODERS_PAD) behavior is not going to be changed by this pull request.
#10259 may be the cause.

I'd like you to compare the behavior of this PR with qmk/develop(head) instead of comparing it with qmk/master.

**Comment by mtei** [comment]
Updated the comments on the above test results. The transport relationship seems to be suspicious, so I'll check it tonight if possible.
上のテスト結果のコメントを更新しました。 transport 関係があやしそうなので、できれば今夜調べる予定です。


Click here for the tested source. テストしたソースはこちら。

https://github.com/mtei/qmk_firmware/commit/7bd77868e63339012d39ee6d3ec6371a01af23dc in https://github.com/mtei/qmk_firmware/tree/encoder_test_on_b6cac8227_pr_10517

**Comment by mtei** [comment]
I did test1 on the 'a' and 'b' branches below and the encoders on both sides were working.
以下の、'a' と 'b' のブランチで、test1 を行って、両方のサイドのエンコーダは動いていました。

```
* 6a6b22bd3 (HEAD -> b) encoder test code for PR 10517 
* 52f3afaad Per-encoder resolutions (#10259)
| * 1a54eeba1 (a) encoder test code for PR 10517 
|/  
* 187c3cd2d Joystick 16-bit support (#10439)
* 1cedd5e8f Make bootloader_jump weak for ChibiOS. (#10417)
```

**Comment by hsakoh** [comment]
@mtei 
I've reproduced it.
I made a fatal bug last week when I was backporting a fix for another branch.[here](https://github.com/qmk/qmk_firmware/pull/10517/commits/6ed8fbb30b2a0e4e2ca5a098d4d75102fa405cdd#diff-cac35d92f4e205645979d131e3195fa4b4e4823429cdf5443f7026aeaaa72793R18) 

My apologies. Please test it again.

**Comment by mtei** [comment]
This case in the documentation seems to result in a build error.
```c
//To place Encoder on the right side only with a split keyboard.
#define MATRIX_ENCODER_PINS_ABC {}
#define MATRIX_ENCODER_PINS_ABC_RIGHT {{E6,B4,B6}}
```

**Comment by hsakoh** [comment]
A correction to the documentation was missing.
I fixed the documentation.

In this case, "not defining" is correct.

**Comment by mtei** [comment]
The standard `matrix.c` of QMK supports the following three types of keyswitch connections.

* `DIRECT_PINS`
* `DIODE_DIRECTION == COL2ROW` matrix
* `DIODE_DIRECTION == ROW2COL` matrix

Your `quantum/encoder.c` code appears to support only `DIODE_DIRECTION == COL2ROW`.
Thus, on keyboards with `DIRECT_PINS` or `DIODE_DIRECTION == ROW2COL` the `quantum/encoder.c` does not seem to be able to handle the attached encoders in the matrix.

Your current configuration macro looks like this:
```c
#define MATRIX_ENCODER_PINS_ABC { {<A_pin>,<B_pin>,<C_pin>},{...},....}
```

I think it would be better to separate the above into two parts and use the following
```c
#define ENCODERS_PINS_AB { {<A_pin>,<B_pin>},{...},....}
#define ENCODERS_MATRIX_INDEX_AB { {<A_col_index>,<A_row_index>, <B_col_index>,<B_row_index>},{...},....}
```

What do you think?

**Comment by hsakoh** [comment]
@mtei 
>Your quantum/encoder.c code appears to support only DIODE_DIRECTION == COL2ROW.
>Thus, on keyboards with DIRECT_PINS or DIODE_DIRECTION == ROW2COL the quantum/encoder.c 
>does not seem to be able to handle the attached encoders in the matrix.

That's not true.

If A & B are connected to COL and C is connected to ROW, it reads from the key matrix.
But if the Encoder is outside the key matrix, it will manipulate and read directly from the pins.

First class support for reading the key matrix is COL2ROW, but DIRECT_PINS or ROW2COL are supported as well, although at a slightly higher cost of execution.
This keeps the code and configuration simple.

The purpose of this PR is to connect the encoders to the matrix and increase wiring flexibility.
Roughly 90% of the keyboards registered with qmk use COL2ROW and we are not willing to pay additional implementation costs at this time.

After merging this pull request, I will consider implementing your point as an additional feature.

**Comment by mtei** [comment]
Update test result report.
test 1 to 5 is OK.
The result of test 6 is not what I expected.

**Comment by hsakoh** [comment]
@mtei 
Fixed the problem in Test6.

This occurs when only the left hand side is present and there is a right hand side with the same pin.
In the case of right hand side only, the result was correct without transfer, but I fixed the same as a precautionary measure.

**Comment by mtei** [comment]
Update test result report.
test 4 to 6 is OK.

**Comment by hsakoh** [comment]
To restart TravisCI, close and open ,
it because I don't have write permission.

**Comment by hsakoh** [comment]
The review doesn't go forward, so I no longer have the motivation to contribute.
I'll close the pull request and delete the entire repository.
I won't contribute, so don't violate my moral rights regarding this change.

Goodbye qmk.
Good product, but the collaborators are not good.

**Comment by drashna** [comment]
Were sorry to see this. 

For travis CI, we're running into issues with it timing out and errorring out. As long as affected boards aren't erroring from compiling, that's fine.

As for getting it merged, that cannot and will not get merged because you don't have time. We do this in our free time, as well. We don't get paid for this, so it can be hard to get free time to review. Also we have different expertise and different areas of the codebase that they're familiar with.

We are more than willing to work with you, but the process will take time, so it follows the existing coding convention and doesn't break stuff.

We would still like to work with you on this, if you're willing.

**Pull request closed without merging**
