### PR TITLE
Add tkl_ansi_plus_five layout for Phantom

### PR DESCRIPTION
**Pull request by jshuf**
The Phantom can support a variant of the standard TKL ANSI layout that adds five keys between the arrow keys and the 2x3 block above the arrows, resulting in a 5x3 block of keys, and plates are available that support this layout.  Userspace changes that make use of this layout are forthcoming, but I thought it best to do a pull request for these changes separately.

### CODE REVIEW

**Comment by drashna** [comment]
@noroadsleft  This look good to you?

**Comment by noroadsleft** [comment]
@jshuf a suggestion for future reference:

You've filed this PR from your fork's `master` branch. While this isn't a major issue now, subsequent pull requests may be difficult to review or have merge conflicts, because the commit history on your fork will have diverged between your master and QMK's.

It is highly recommended for QMK development - regardless of what is being done or where - to keep your master updated, but **NEVER** commit to it. Instead, do all your changes in a branch and issue PRs from your branches when you're developing.

For example, I keep my keymap in a branch named `keymaps/noroadsleft`, and every now and then I do the following (using Git Bash on Windows 8):

```
git fetch upstream
git checkout master
git pull upstream master
git push origin master
```

This retrieves any recent changes to `qmk_firmware` - nicknamed `upstream` - and syncs them to my fork, which is nicknamed `origin`. Then when I start development on something, I create a new branch for whatever I'm working on with `git checkout -b dev_branch`, which creates a branch `dev_branch` that is based on the current branch, and then checks out the new branch. I'll make all my changes to `dev_branch`, then when they're ready, I'll do a pull request from `noroadsleft:dev_branch` to `qmk:master`.

If you need any help with this in future just let us know.

**Comment by jshuf** [comment]
Thanks for taking the time to give me a clue - and, in particular,
providing the example workflow.  I appreciate it.

Using your workflow, how do you get dev_branch to show up as an option for
the pull request?  Is it just a matter of doing
git push origin dev_branch
?

**Comment by noroadsleft** [comment]
> Using your workflow, how do you get dev_branch to show up as an option for the pull request? Is it just a matter of doing
> git push origin dev_branch
> ?

Exactly. When you're ready, `git push origin dev_branch`, then load the branch in GitHub (`https://github.com/jshuf/qmk_firmware/tree/dev_branch`) and start the pull request from there. That's how I do it, anyway.

**Comment by drashna** [comment]
@noroadsleft For me, that errors out unless you've set an upstream or the branch already exists.  Fortunately, git gives you the actual command that you need, the first time you run it on a new branch. :)

**Comment by drashna** [comment]
Thanks!

**Comment by noroadsleft** [comment]
@drashna True, I forgot about that.

@jshuf To get the `upstream` alias to work, load your Git shell and enter `git remote add upstream https://github.com/qmk/qmk_firmware.git`.

**Comment by jshuf** [comment]
@drashna @noroadsleft Thank you both for taking the time to make sure this is right going forward.  If we ever meet in real life, first round is on me.

**Pull request merged**
