### PR TITLE
Chibios_test/stm32_f072_onekey: Add support for reset to bootloader

### PR DESCRIPTION
**Pull request by TerryMathews**
Chibios_test/stm32_f072_onekey wouldn't reset to bootloader on a
compatible Discovery board because the Chibios library board file was
lacking the __early_init(void) function necessary to read the magic key.
Borrowed code from Clueboard 60, tested working.

This way there will be good example code if anyone else implements an 072 MCU in their project.

### CODE REVIEW

**Comment by yiancar** [comment]
I think cfg/board.chcfg is not needed. Am I right?:)

**Comment by TerryMathews** [comment]
@yiancar I do believe you are correct, compiles with it removed. Can you approve this commit now that I've cleaned it up?

**Comment by TerryMathews** [comment]
@jackhumbert Can you review and approve please?

**Comment by TerryMathews** [comment]
I don't know what the holdup is on this PR, but I have other things to work on. I'm going to have to catch up my repo and start working by 12/27.

I hate to be difficult about it, but it's been two months.

**Comment by drashna** [comment]
Actually, I was just thinking about this the other day. 

Thanks!

**Pull request merged**
