### PR TITLE
Change cKeys Washington keyboard to use atmel-dfu bootloader

### PR DESCRIPTION
**Pull request by Merlin04**
## Description

The cKeys workshop will be using Elite-Cs, not Pro Micros like I originally thought. This changes the bootloader option in rules.mk to `atmel-dfu` so the reset keycode will work.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

None

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
Thanks!

**Comment by CyanGiant** [comment]
Hey Merlin04, apologies for reaching out through this commit comment, I couldn't find other contact info.
Thanks for creating this macropad and for providing this support!  It is really cool!

I am trying to figure out how to support the oled and encoder, and I can't quite get there,  I was wondering if you had a layout / keymap that supports both that I could look at?  
Also, I am creating an acrylic case for this board, I will share the dxf for it as creative commons as well :)

**Comment by noroadsleft** [comment]
@CyanGiant Have you gone through the QMK Docs?

- [OLED Driver - QMK Firmware Docs](https://docs.qmk.fm/#/feature_oled_driver)
- [Encoders - QMK Firmware Docs](https://docs.qmk.fm/#/feature_encoders)

**Comment by Merlin04** [comment]
@CyanGiant The default keymap includes support for the OLED and encoder. Here's the code for support for the encoder:
```c
void encoder_update_user(uint8_t index, bool clockwise) {
    switch (biton32(layer_state)) {
        case _BASE:
            if (clockwise) {
                tap_code(KC_VOLU);
            } else {
                tap_code(KC_VOLD);
            }
            break;
        case _FN:
            if (clockwise) {
                tap_code(KC_MNXT);
            } else {
                tap_code(KC_MPRV);
            }
    }
}
```
And here's the code for the OLED:
```c
void oled_task_user(void) {
  // Host Keyboard Layer Status
  oled_write_P(PSTR("Layer: "), false);
  switch (biton32(layer_state)) {
    case _BASE:
      oled_write_P(PSTR("Default\n"), false);
      break;
    case _FN:
      oled_write_P(PSTR("FN\n"), false);
      break;
    default:
      // Or use the write_ln shortcut over adding '\n' to the end of your string
      oled_write_ln_P(PSTR("Undefined"), false);
  }

  // Host Keyboard LED Status
  uint8_t usb_led = host_keyboard_leds();
  oled_write_P(IS_LED_ON(usb_led, USB_LED_NUM_LOCK) ? PSTR("NUMLCK ") : PSTR("       "), false);
  oled_write_P(IS_LED_ON(usb_led, USB_LED_CAPS_LOCK) ? PSTR("CAPLCK ") : PSTR("       "), false);
  oled_write_P(IS_LED_ON(usb_led, USB_LED_SCROLL_LOCK) ? PSTR("SCRLCK ") : PSTR("       "), false);
}
```

You can contact me on Reddit, my username is /u/keypcb. Let me know if you need any of the design files for the keyboard to make the case.

**Pull request merged**
