### PR TITLE
Various code tidy-ups

### PR DESCRIPTION
**Pull request by jhol**
## Description

This branch contains various tidy-ups:

* Marks all C files as non-executable.
* Removed trailing whitespace at the end of lines
* Replaces all tabs with spaces
* Ensure every source file ends with a newline character

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by jhol** [comment]
What would you like me to do about this?

I think this MR can die - it's the conversions that really matter. Which are as follows:

* Mark all C files as non-executable:  `find -regex ".*\.\(c\|cpp\|cxx\|cc\|h\|\hpp\)" | xargs chmod -x` 
* Removed trailing whitespace at the end of lines: `find -regex ".*\.\(c\|cpp\|cxx\|cc\|h\|\hpp|\py\)" | xargs sed -i 's/[\t ]*$//'`
* Replace all tabs with spaces: `find -regex ".*\.\(c\|cpp\|cxx\|cc\|h\|\hpp|\py\)" | while read i; do expand -t4 $i > /tmp/x; mv /tmp/x $i; done`
* Ensure every source file ends with a newline character: `find -regex ".*\.\(c\|cpp\|cxx\|cc\|h\|\hpp|\py\)" | while read f; do tail -n1 $f | read -r _ || echo >> $f; done`

**Comment by zvecr** [comment]
clang-format handles 2 and 3, and I have already got 1 and 4 covered. So I think it should be safe to close this one.

**Comment by jhol** [comment]
Ok... and what's the time-scale for your tidy-ups being merged? Days? Years?

**Comment by zvecr** [comment]
Not sure, currently checking GitHub actions can cover all our existing use cases before we make the jump. Its likely to be a lot sooner than this one would, due to the files its targeting.

**Pull request closed without merging**
