### PR TITLE
Added support new variant of ST7735 TFT display panels

### PR DESCRIPTION
**Pull request by HorrorTroll**
## Description

Due to problem that ST7735 (80x160) have many variant of different specs. Which is not render correctly on panel using BGR color order and wrong other thing.

Could you please testing your TFT screen and see if there are any issues? @infinityis

## Types of Changes

- [x] Core
- [x] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by infinityis** [comment]
I'll test it as soon as I get a chance, but just from a brief review of the code, it looks like it shouldn't cause any problems (aside from my display will probably need a 180 rotation with how you've shifted the MADCTL around, I'm guessing to match Adafruit rotation indices?)

Looking at the Adafruit ST7735 driver code here https://github.com/adafruit/Adafruit-ST7735-Library/ it's clear that this sort of update to the QP ST7735 driver may be the first of many, since so far there appear to be 10 different ways manufacturers have implemented the ST7735 chip (each colloquially referred to as GREENTAB, BLACKTAB, etc.). Before we get too far down a particular path, it may be worth asking the question of whether we want to continue doing this piecemeal or is it preferable to get ahead of future changes.

Specifically, your code adds the option for BGR vs RGB, and inverted or not inverted. Based on those selections, it also presumes specific offset values (and in fairness, my initial stab at ST7735 driver also presumed specific offset values, plus RGB, and invert settings). Going forward, as new displays are added, should we continue with the approach of adding different options and having folks figure out which options apply to their display, or would it be better to go the Adafruit route (and even using their existing display names) and curate a list of named display configurations to choose from?

I'm not saying we have to implement all the display options at this time, I'm just wondering if the best approach here is to add a bunch of generic configuration options...or adding a list known-viable groups of options (like GREENTAB, etc.).

My personal preference would be to go with the list of known-good option groups like GREENTAB.

Also, I would avoid conditional preprocessor directives in the driver code as well (like `#if ST7735_RGB_PANEL` or `#if ST7735_INVERT_COLOR`. My reasons are:
- If you have multiple displays, the preprocessor directive approach will require them all to have the same configuration
- With so many ST7735 options, it would be very convenient if someday we could enable an autodetect mode that cycles through the settings for each type of ST7735 display for a few seconds at a time, each time attempting to display color text and a white 1px bounding box around the edge of display. The text can tell you which option it is actively displaying, making it trivial to configure QMK (because the configuration option that displayed correctly on the screen will be the one you want to use when compiling code for the keyboard). But....that approach can't be done if preprocessor directives are precluding those options from being compiled into the firmware.

The preprocessor directive you used approach does offer a degree of simplicity in that it allows you directly reach the relevant code from config.h. However, the alternative approach would be to modify `qp_st7735_make_spi_device` to add another argument which specifies the named ST7735 device to use/configure (e.g. GREENTAB).

**Comment by HorrorTroll** [comment]
> I'll test it as soon as I get a chance, but just from a brief review of the code, it looks like it shouldn't cause any problems (aside from my display will probably need a 180 rotation with how you've shifted the MADCTL around, I'm guessing to match Adafruit rotation indices?)

Yes, it was shifted around to match Adafruit rotation indices.

> Looking at the Adafruit ST7735 driver code here https://github.com/adafruit/Adafruit-ST7735-Library/ it's clear that this sort of update to the QP ST7735 driver may be the first of many, since so far there appear to be 10 different ways manufacturers have implemented the ST7735 chip (each colloquially referred to as GREENTAB, BLACKTAB, etc.). Before we get too far down a particular path, it may be worth asking the question of whether we want to continue doing this piecemeal or is it preferable to get ahead of future changes.
> ............

Hmm, you're right. But seriously, I didn't know that there was many different ways manufacturers could be using out there. Meybe I think we could go Adafruit route, since this temporary fix was based on CircuitPython library.

**Comment by elpekenin** [comment]
A potential way to work around the different displays: use the `0x4` command which returns data about the manufacturer/device. Hopefully each of the variants has a *unique* combination (i.e. we dont get the same reading from BGR and RGB screens, hard to test all the different vendors tho...)
In an ideal scenario where such a thing happens, reading the value and adjusting MADCTL accordingly -no user action required-  would be amazing.

There is also `0xB` which returns a bit flagging if RGB/BGR mode is selected (but i guess the issue being tackled is abouthardware decissions, not about toggling this bit)

**Comment by tzarc** [comment]
You should not be using preprocessor directives to override things like RGB/BGR, due to multiple displays and the like.
Add a new API to the driver to allow it to send a command after init to override things like the colorspace.

**Comment by HorrorTroll** [comment]
> You should not be using preprocessor directives to override things like RGB/BGR, due to multiple displays and the like. Add a new API to the driver to allow it to send a command after init to override things like the colorspace. Something like:
> 
> ```c
> void qp_st7735_set_colorspace(bool use_bgr);
> ```

Just noted, I'll take a look after go back on my next vacation. So this PR will be move to draft

**Comment by HorrorTroll** [comment]
If u could think a better solution, u can try to open new PR about it. QP is a bit complex for me, so I thought you could handle it better than me

**Comment by elpekenin** [comment]
The solution i proposed feels more like a monkeypatch than an actual fix, i dont really like it.

Given that + the amount of PR's related with QP i already have open (and a couple more in the works), i will let this be for now. Maybe tzarc comes in with some **proper** way of handling this

**Pull request closed without merging**
