### PR TITLE
Adds config for ALF X2 60% keyboard

### PR DESCRIPTION
**Pull request by fixed**
Originally exported via kbfirmware.com from a JSON that I found on reddit,
PCB is almost the same as DZ60.

### CODE REVIEW

**Comment by mechmerlin** [comment]
The ALF X2 has non-MX style buttons that have been advertised as QMK programmable. Were you able to get those to work with these too?

**Comment by fixed** [comment]
Yeah, as noted in the alf_x2.h file, K404 and K408 are the microswitches at the top of the PCB

**Comment by mechmerlin** [comment]
Sweet! I should learn to read comments!

**Comment by mechmerlin** [comment]
Excellent, much love.

**Comment by drashna** [comment]
One last thing, for the sake of LAYOUTs, could you replace: 
`#include "alf_x2.h""
with: 
`#include QMK_KEYBOARD_H`

In all of the `keymap.c` files for the keyboard?

**Comment by fixed** [comment]
Done!

**Comment by drashna** [comment]
Awesome, looks great!

**Pull request merged**
