### PR TITLE
Let's Split: establish rev2fliphalf subproject

### PR DESCRIPTION
**Pull request by TerryMathews**
Subproject to accomodate second half pad built in opposite orientation
(places TRRS jacks on opposing edges for shorter cable runs)

### CODE REVIEW

**Comment by nicinabox** [comment]
What do you think about making this an alternate keymap method instead? Then this configuration goes right into `keymap.c` and since it'll never change once the board is setup the user won't have to remember the extra-specific subproject config when flashing.

[This would go in `rev2.h`](https://github.com/nicinabox/qmk_firmware/blob/nic/keyboards/lets_split/keymaps/nic/keymap.h) and use it [like this in `keymap.c`](https://github.com/nicinabox/qmk_firmware/blob/nic/keyboards/lets_split/keymaps/nic/keymap.c#L30)

**Comment by TerryMathews** [comment]
I had thought about several different ways to approach this problem.

The only true defining advantage I could come up with this way was that
make will now automatically compile a working default that covers 95% of
the configurations people build. People build these but struggle with
changing and compiling QMK.

I'm certainly not opposed to revamping the way this code works and if
someone wants to make a change please feel free. What we started with
wasn't working and I was tried of having to fix it every time I synced my
QMK tree against Master.

**Comment by fredizzimo** [comment]
@nicinabox, that would tie the specific keyamp to be valid only filpped keyboards. So if someone else want to use the keymap without the flipping, it wouldn't work without modifications

However, it's still possible to provide a keymap default, which will be used if you run make from the keymap directory.

Add a `Makefile` with the following contents to the keyamp directory

```
SUBPROJECT_DEFAULT = rev2filphalf
ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
```

If you then run `make` it will generate the flipped version
`make rev2` will generate the unflipped version
`make rev1` will generate a rev2 flash.

**Comment by nicinabox** [comment]
> So if someone else want to use the keymap without the flipping, it wouldn't work without modifications

Ah good point.

**Comment by jimmyhchan** [comment]
looking at #1052 from wootpatoot aka @climbalima  I suspect trrs cables facing in is the "correct" way to wire this up.

**Comment by TerryMathews** [comment]
One could just as easily say that having them in identical orientations is
the right way, as it allows for tightly fitted cases with surrounds on the
microUSB and the TRRS.

To me, the bottom line is that we should be supporting both build
configurations as they are both valid ways to construct these devices.

**Comment by nicinabox** [comment]
I suspect that more people will be building them with the right side reversed since that's what the build guide does. Maybe this should simply be the default configuration?

**Comment by TerryMathews** [comment]
Again, my $0.02 is that the compiler should be spitting out both. Which one
should be rev2 and which should be rev2fliphalf, matters not to me.

**Comment by Justinicus** [comment]
I built mine with the TRRS jacks together (is that "reversed?"). All the columns on my right side board are backwards, so I definitely support a reversed option instead of remapping everything in a text editor like I've been doing!

**Comment by nicinabox** [comment]
Yeah, the configuration is definitely the way to go here. I'm in favor of having this be the default.

**Comment by TerryMathews** [comment]
OK, so tonight I can update my pull request and flip which matrix is in
rev2 and which is in rev2fliphalf.

**Comment by TerryMathews** [comment]
So this code should now have the rev2 subproject be the mirror image hand layout and rev2fliphalf be identical layout.

**Comment by jackhumbert** [comment]
Great! Thanks :)

**Pull request merged**
