### PR TITLE
Stop sounds when suspended

### LINKED ISSUE #8167: [Bug] Audio playback issue when Audio feature is turned off on startup
## Describe the Bug

If the audio feature was turned off when the board started up, and you turn it on, the next song that it plays will cause it to play a single, continuous tone, rather than a song. 

For testing: 
1. Turn off audio mode
2. unplug and then plug in the keyboard
3. Turn on audio mode
4. turn on music mode
5. press button and get tone

## System Information

 - Keyboard:  Planck EZ, other ARM
   - Revision (if applicable):  
 - Operating system: macOS Mojave (10.14.6)
 - AVR GCC version:  8.3.1

 - ARM GCC version: 8.3.0

 - QMK Firmware version: latest (me lazy, not matter anyway)

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

### PR DESCRIPTION
**Pull request by spidey3**
## Description

The code to stop sounds when suspending was commented out long ago, because it interfered with the startup sound working correctly. The problem was that at the time of `audio_init()` the USB device status might still be in flux, passing through the Suspended state, which would call `stop_all_notes()`.

The solution is to move the playing of the startup song into a routine that is run 300ms after startup, giving enough time for the USB state to settle.

Note: This has been tested thoroughly on AVR. I have provided code for ARM, but it is not as well tested. I understand that the state of audio on ARM is limited to Proton-C; I'd appreciate if someone with that architecture could test this before it is merged.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Fixes issues

Fixes #8167

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
This doesn't work on STM32F303.  Specifically with the moonlander, which uses the same chip as the Proton C.

**Comment by spidey3** [comment]
> This doesn't work on STM32F303. Specifically with the moonlander, which uses the same chip as the Proton C.

Does it just not fix the problem, or does it break other things?

Good news is I have a Proton C on order, expect to have it shortly...

**Comment by drashna** [comment]
It stops the startup sound from playing.

**Comment by spidey3** [comment]
> It stops the startup sound from playing.

 Hmmm...
 I wonder - if you change the 300 to 500 at [quantum.c#L682](https://github.com/qmk/qmk_firmware/blob/81cf21887ca70e648309d3871072aa40b2f63ebd/quantum/quantum.c#L682) does that make it work?

**Comment by tzarc** [comment]
Did some verification:

* PR as-is: Proton-C produces a constant buzz after startup.
* PR, with the change from 300ms to 500ms: no difference
* PR, with change to 5000ms: delay for 5 seconds, then constant buzz
* PR, with change to 5000ms: delay for 15 seconds, then constant buzz
* PR, with merge of `develop` branch: no difference
* Untouched `develop` branch: normal startup "bleep" sound.

**Comment by spidey3** [comment]
@drashna , @tzarc , can you please test again on F303?

I just pushed some code updates that I think solves the problems.

**Review by drashna — APPROVED** [review]
Yup, this works! And fixes the audio init issues on arm, for me.

**Review by fauxpark — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Pull request merged**
