### PR TITLE
Add VIA friendly Mac keymap to lock user screen.

### PR DESCRIPTION
**Pull request by alvinsee**
## Description

Add VIA friendly Mac keymap to lock user screen.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Wilba6582** [comment]
What is the point of adding this keymap to QMK? Since this keymap enables VIA, the only difference to the `via` keymap is the keycode `LGUI(LCTL(KC_Q))` which can be assigned within VIA.

**Comment by alvinsee** [comment]
Yes, the only difference between this keymap is the default keycode mapped. `KC_ENT` -> `LGUI(LCTL(KC_Q)`. 

It could just be my inexperience with using the VIA gui, but I had a difficult time figuring out how to map a combination of keycodes such as this. My initial attempt was to create a single macro with a chord `{KC_LGUI,KC_LCTL,KC_Q}` and bind it to the key. That did not work as I would have expected - the result of it was it being registered as a left shift.

Reflashing the board with this and looking at what the generated user keymapping on VIA showed that the it was binding to a layer with the values `[["C(LWIN(KC_Q))"], ["KC_TRNS"], ["KC_TRNS"], ["KC_TRNS"]]`.

I thought this might be a useful toy example to live alongside with the existing via keymap that only maps to a single keycode. However, if this is a contrived keymap, feel free to decline.

**Comment by noroadsleft** [comment]
Yeah, I'm with @Wilba6582. This strikes me as being something that would be better solved with some additional docs on VIA (on how to use the app, specifically), rather than needing its own keymap.

**Comment by alvinsee** [comment]
Thats fair. Will close this PR then.

**Pull request closed without merging**
