### PR TITLE
Bastard Keyboards: upstream recent changes

### PR DESCRIPTION
**Pull request by 0xcharly**
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by keyboard-magpie — APPROVED** [review]

**Comment by fauxpark** [comment]
`bastardkb/charybdis/3x5/v2/splinky/v2` etc are invalid; QMK only supports up to 5 levels of nesting. This has caused some build failures in CI due to the placement of the pointing device CS pin define:
```
bastardkb/charybdis/3x5/v2/splinky:default
bastardkb/charybdis/3x5/v2/splinky:via
bastardkb/charybdis/3x6/v2/splinky:default
bastardkb/charybdis/3x6/v2/splinky:via
bastardkb/charybdis/4x6/v2/splinky:default
bastardkb/charybdis/4x6/v2/splinky:via
```

**Comment by drashna** [comment]
Also, I missed it but in dilemma.c, line 334, 
```c
void keyboard_pre_init_user(void) {
```
This should be the kb version, and then call the user version.  (appears to be the only place this sort of issue has occurred).

**Comment by 0xcharly** [comment]
> `bastardkb/charybdis/3x5/v2/splinky/v2` etc are invalid; QMK only supports up to 5 levels of nesting. This has caused some build failures in CI due to the placement of the pointing device CS pin define

This seems to be an arbitrary limit, and I can't seem to find any reference to it. It also doesn't match [the output of the CI builder](https://github.com/qmk/qmk_firmware/pull/18903/checks?check_run_id=9494407164) which shows that `bastardkb/charybdis/3x5/v2/splinky/v2:default`, `bastardkb/charybdis/3x5/v2/splinky/v3:default`, and others with similar path built fine, but `bastardkb/charybdis/3x5/v2/splinky:default`, for example, did not.

According to https://github.com/qmk/qmk_firmware/blob/master/lib/python/qmk/keyboard.py#L101-L108, it seems that QMK's CLI is defining a keyboard folder as a folder that contains a `rules.mk` file. This explains the CI behavior above, because `v2/splinky` folders do contain and share a `rules.mk` file that is shared between their children folders `v2/splinky/v2` and `v2/splinky/v3`. The same thing happens for the Scylla, TBK mini, and Skeletyl boards, where the row pin definition changes based on the Splinky's version, so _eg._

```sh
qmk compile -c -j 72 -kb bastardkb/scylla/v2/splinky -km default
```

Compiles, but yields a non-functioning firmware. The issue is actually flagged at compile time by a warning:

```
quantum/matrix.c:53:32: warning: 'row_pins' defined but not used [-Wunused-const-variable=]
   53 | static SPLIT_MUTABLE_ROW pin_t row_pins[ROWS_PER_HAND] = MATRIX_ROW_PINS;
      |                                ^~~~~~~~
```

In light of this, I believe that the appropriate course of action is to use `DEFAULT_FOLDER` in `v2/splinky/rules.mk` to default to building `v2/splinky/v3`. An alternative would be to remove `v2/splinky/rules.mk` and duplicate it into `v2/splinky/v2` and `v2/splinky/v3`, but I'd like to maintain code/config reuse here if possible.

https://github.com/qmk/qmk_firmware/pull/19093 adds the necessary `DEFAULT_FOLDER` declarations, which [seems to satisfy the CI's automatic keyboard folder discovery mechanism](https://github.com/qmk/qmk_firmware/pull/19093/checks?check_run_id=9514728098).

I also verified locally that these targets now build fine and with no warnings:

- `bastardkb/charybdis/3x5/v2/splinky:default`
- `bastardkb/charybdis/3x6/v2/splinky:default`
- `bastardkb/charybdis/4x6/v2/splinky:default`
- `bastardkb/scylla/v2/splinky:default`
- `bastardkb/tbkmini/v2/splinky:default`
- `bastardkb/skeletyl/v2/splinky:default`

**Comment by 0xcharly** [comment]
> Also, I missed it but in dilemma.c, line 334,
> 
> ```c
> void keyboard_pre_init_user(void) {
> ```
> 
> This should be the kb version, and then call the user version. (appears to be the only place this sort of issue has occurred).

Addressed in https://github.com/qmk/qmk_firmware/pull/19091.

**Comment by drashna** [comment]
> This seems to be an arbitrary limit

It is. And the code that arbitrates that is here: 

https://github.com/qmk/qmk_firmware/blob/df5689ed06cc08713f1d097de7436c466f4c0261/builddefs/build_keyboard.mk#L59-L91

**Review by drashna — APPROVED** [review]

**Comment by 0xcharly** [comment]
> > This seems to be an arbitrary limit
> 
> It is. And the code that arbitrates that is here:
> 
> https://github.com/qmk/qmk_firmware/blob/df5689ed06cc08713f1d097de7436c466f4c0261/builddefs/build_keyboard.mk#L59-L91

Thanks, I did miss this! This doesn't seem to be what was causing the CI issues though, since the `bastardkb/charybdis/*/v2/splinky/v3:default` firmwares were building fine?


I happy to add to the madness and submit a PR for `KEYBOARD_FOLDER_PATH_6` if you want, or try to look into a way to support arbitrary depth.

**Comment by fauxpark** [comment]
It would be better to rethink your folder structure, keyboard names with lots of nesting can be confusing to users.

**Comment by fauxpark** [comment]
I made a suggestion here: https://github.com/qmk/qmk_firmware/pull/19088#issuecomment-1315702693

**Comment by 0xcharly** [comment]
I have a follow-up PR to re-work the Splinky versioning (https://github.com/0xcharly/qmk_firmware/pull/2). Let me know if you prefer to keep it as a follow-up, which I'll send as soon as this PR is merged, or if you'd rather merge them both.

**Comment by 0xcharly** [comment]
> [0xcharly](https://github.com/0xcharly) requested review from [drashna](https://github.com/drashna) and [keyboard-magpie](https://github.com/keyboard-magpie) and removed request for [fauxpark](https://github.com/fauxpark), [drashna](https://github.com/drashna) and [keyboard-magpie](https://github.com/keyboard-magpie)

That makes no sense to me, I just clicked to request review icon on Drashna…

**Comment by drashna** [comment]
> > [0xcharly](https://github.com/0xcharly) requested review from [drashna](https://github.com/drashna) and [keyboard-magpie](https://github.com/keyboard-magpie) and removed request for [fauxpark](https://github.com/fauxpark), [drashna](https://github.com/drashna) and [keyboard-magpie](https://github.com/keyboard-magpie)
> 
> That makes no sense to me, I just clicked to request review icon on Drashna…

i ... yeah, wow.  WTF github. It sometimes does some very weird stuff...

**Comment by drashna** [comment]
I think this is one of those weird issues. 

using `bastardkb/charybdis/4x6/v2/splinky/v3` as an example

IIRC, and from what the code appears to read as, it reads for the furthest down (eg v3) and gets each layer higher. However, this means that anything in the 6th from the bottom or further doesn't get processed.   So nothing in bastardkb gets processed (not included in vpath, not included rules/confg, etc.  So anything in that folter is actively ignored, basically.    

Right now, that's not breaking anything, at least from the compiler standpoint.  But any deeper,  and it would ignore the charybdis config and files (including charybdis.c).  

For instance, the `KEYBOARD_bastardkb_charybdis` define is generated, but `KEYBOARD_bastardkb` is not.

**Review by drashna — APPROVED** [review]

**Comment by 0xcharly** [comment]
Thanks! Follow-up PR to address splinky versioning and folder hierarchy issues: https://github.com/qmk/qmk_firmware/pull/19123

**Pull request merged**
