### PR TITLE
Remove FAUXCLICKY feature (depricated)

### PR DESCRIPTION
**Pull request by drashna**
Only 2 boards were using it in the repo, actually. And audio clicky works better, as it supports any board that is supported by the audio feature, rather than just AVR and pin C6. 

## Types of Changes

- [x] Core

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]
👍 👍 👍 
Those empty lines can be removed from the `rules.mk`s though too.

**Comment by drashna** [comment]
Fixed.  A few cases are not, but that's to separate the `LAYOUTS` macro, to keep consistent with the rest of the repo.

**Comment by spidey3** [comment]
`keyboards/handwired/promethium/keymaps/default/keymap.c` and `keyboards/handwired/promethium/keymaps/priyadi/keymap.c` still refer to `FC_TOG`. 
Is that intentional? Should they be changed to CK_TOGG?

**Comment by drashna** [comment]
I think that aliasing them may be a better option, for now, actually.

**Review by tzarc — APPROVED** [review]

**Pull request merged**
