### PR TITLE
Zen refactor and Configurator support

### PR DESCRIPTION
**Pull request by noroadsleft**
- Matrix refactor
  - `KEYMAP` renamed to `LAYOUT`
  - deleted `KC_KEYMAP` macro (it was unused)
- Keymap refactor
  - all keymaps now use `#include QMK_KEYBOARD_H`
  - `KEYMAP` macro rename update
- Configurator support
  - added `info.json` file
- Readme formatting
  - updated to be more consistent with other QMK keyboard readme files.

### CODE REVIEW

**Comment by noroadsleft** [comment]
Ok, the [Travis error](https://travis-ci.org/qmk/qmk_firmware/builds/417110893?utm_source=github_status&utm_medium=notification) is super LOL:

> ERROR: An error occured while trying to fetch your .travis.yml file.
>
> Is GitHub down? Please contact support@travis-ci.com if the error persists.

**Comment by noroadsleft** [comment]
That was actually outside the scope of this PR, which was oriented toward [Configurator support](https://config.qmk.fm/#/zen/rev1/KEYMAP) (and was authored before `split_common` was a thing), but it seems simple enough to do. The problem is I have no way to test split_common changes, as I don't own a Zen (or any split keyboards, for that matter).

**Comment by drashna** [comment]
@Lenbok If you have a Zen and are willing to test the changes and open a PR, then by all means, please!

**Comment by drashna** [comment]
@noroadsleft I don't know what you did, but you broke Travis GOOD.  I've tried restarting the build a few times.

But everything looks good.

**Comment by drashna** [comment]
Dang, missed 333fred's keymap. It errors out since it's using `KEYMAP` and not `LAYOUT`

**Comment by noroadsleft** [comment]
@drashna Did you mean to merge this?

Regarding 333fred's keymap, his keymap is actually newer than the commit this dev branch was originally built from. All the commits were made July 5 and 6. This sat in my fork since, and then I went back and ran `git rebase upstream/master`, but I didn't think to check for new keymaps and I failed to think to run a local compile task.

**Comment by drashna** [comment]
Yes, I did.  Travis just ... didn't want to work for this PR, and everything else looked fine.

**Comment by Lenbok** [comment]
@drashna @noroadsleft Sorry, I assumed that you had a zen so could test the refactoring, which is why I suggested doing the split common migration as well while you were in "testing mode". Unfortunately I don't have a zen (or most of the other split boards) to test with otherwise I would indeed do it myself.

**Pull request merged**
