### PR TITLE
Fix list number

### PR DESCRIPTION
**Pull request by souvlakeeb**

### CODE REVIEW

**Comment by waffle87** [comment]
The [PR template](https://github.com/qmk/qmk_firmware/blob/master/.github/PULL_REQUEST_TEMPLATE.md) exists for a reason. Please use it and fill out when opening PRs.

**Review by waffle87 — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by souvlakeeb** [comment]
It said the template is optional so I left it out. Especially for a small change.

The main reason though is it seems to be geared for code changes with subsequent doc changes, with checkboxes for standalone documentation changes.

**Comment by souvlakeeb** [comment]
What part helps you guys most? Is it cool if I fill out the first type of change only for doc changes?

**Comment by zvecr** [comment]
Read "template is entirely optional" as "replacing it with nothing is generally not accepted".

**Comment by souvlakeeb** [comment]
> Read "template is entirely optional" as "replacing it with nothing is generally not accepted".

Haha, that's a pretty big stretch! Based on this, I would replace with "filling out the entire template is not required".

**Pull request merged**
