### PR TITLE
[Core] Add encoder_set_resolution function

### PR DESCRIPTION
**Pull request by monksoffunk**
## Description
Currently, the resolution of the encoder is set by the ENCODER_RESOLUTION constant, which is fixed at build.
This function allows the user to change the resolution of the encoder by keypress or other means.
Very simple.

```
encoder_set_resolution(uint8_t index, uint8_t resolution);
```
## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
> This function allows the user to change the resolution of the encoder by keypress or other means.

I personally do not see the point in it being dynamic. Its not like a user is going to be swapping out installed encoders frequently. 

What exactly is the use case trying to be solved?

**Comment by monksoffunk** [comment]
@zvecr
Thanks for your comment.
As you can see in the part I added to feature_encoders.md, this is a feature for kits using PCBAs that do not have switches or encoders implemented, but have pre-programmed MCUs already assembled. And we are well aware that there are many such kits these days.
The developers program the firmware before shipping, but they don't know which encoder model the users will use.

So, as you said, users need to build. 
However, many users are not familiar with the development environment, and I am hesitant to force them to build just for an encoder.
With this feature, users can make adjustments by using their keyboards (or even DIP switches).

If this PR is merged, there is no disadvantage, since it can still be set only in ENCODER_RESOLUTION without using this feature.

**Comment by drashna** [comment]
I think the question here is how usable is this really? 

Basically, if you suspect it's going to be an issue, you're going to have to compile it with the option enabled and configured. And because it's not persistent, you'll have to configure it every time the board powers on.   

Additionally, this would only effect the master side on split keyboards.  which would make it's usability severely lacking, as well.  

Additionally, most encoders do use a resolution of 4, which is why it's the default.  And it seems to be a very small selection that use 2 for the resolution.   

So including a volatile setting that will basically require reflashing to make it permanent, and that only works on some hardware...   I don't think that this is worth merging, IMO.

**Comment by monksoffunk** [comment]
@drashna 
Thank you for always taking the time to help me.
You don't need to set it every time you power on.
As I have already written, one way can be set by using DIP switches. The other way is to record the settings in EEPROM. For the latter, I have already implemented and am using it right now.
https://github.com/monksoffunk/qmk_firmware/blob/feature/aleth42_dev/keyboards/aleth42/rev1/rev1.c#L83-L92

As for the resolution of the encoders, the Bourns encoders are 4, while most of recent ALPS models are 2.
https://tech.alpsalpine.com/prod/e/html/encoder/incremental/ec11/ec11n1524402.html

I think splitkb sells this type.
https://docs.splitkb.com/hc/en-us/articles/360011068659-My-encoder-is-skipping-actions-when-turning-it

In fact, in the current QMK, you can find more than 50 config.h files that have 'ENCODER_RESOLUTION 2'. On the other hand, the number of 'ENCODER_RESOLUTION 4' is 119, and I think that 50 against 119 is not a very small number. In addition, there are 14 descriptions of 'ENCODER_RESOLUTION 1'. I don't know what kind of encoder it is for...

For the split type, you can use DIP switches for persistent configuration.
We will need a different PR to fully support the split type. It would be great if you could help.

**Comment by monksoffunk** [comment]
Further findings.
The previously reported number of 'ENCODER_RESOLUTION 4' was too many. However, considering that the default is 4 when ENCODER_RESOLUTION is omitted, we are sure that the majority are 4.

However, I can imagine that among those '4', there are many cases where the keyboard designers don't know what kind of specification the user will install the encoder, so leave it as default.

By the way, I was a little surprised to learn that some keyboards require settings like 1, 3, and 8.

number of 'ENCODER_ENABLE = yes' : 294
#define ENCODER_RESOLUTION 4 : 106
#define ENCODER_RESOLUTION 2 : 51
#define ENCODER_RESOLUTION 3 : 4
#define ENCODER_RESOLUTION 1 : 14

#define ENCODER_RESOLUTIONS {} : 4
-draculad ENCODER_RESOLUTIONS { 4, 4, 4, 1}
-ein_60 ENCODER_RESOLUTIONS { 4, 4 }
-space_space NCODER_RESOLUTIONS { 3, 4 }
-sp_mini ENCODER_RESOLUTIONS { 8, 8 }

**Comment by zvecr** [comment]
Maybe the use case for dip switches is there, but with the push for data driven generally this PR is the wrong direction.

`ENCODER_RESOLUTION` being available to `info.json` and `keymap.json` and eventually exposed to projects such as Configurator seems like a much more maintainable end goal.

The disadvantage is the extra bloat to the number of supported options/combinations. Right now I too dont see enough value to look past this as technical debt.

**Comment by drashna** [comment]
A simple alternative may be to remove the static declaration on the encoder resolution variables

**Pull request closed without merging**
