### PR TITLE
Rgb matrix fixes, I2C library can now retry if it has failed 

### PR DESCRIPTION
**Pull request by yiancar**
- Replaced the original TWIlib by LFKeyboard's modified version
- Allows for an extra argument on TWITransmitData, if blocking is set to 1 function will retry to transmit on failure. Good for noisy boards.

### CODE REVIEW

**Comment by Wilba6582** [comment]
@yiancar and I need to hash out the TWIlib changes, don't commit yet.

**Comment by drashna** [comment]
@yiancar Nice! 

@Wilba6582 Not a problem.  Let us know when this is good to go, and then we'll merge.

**Comment by yiancar** [comment]
@Wilba6582 please give this a go! its the other library as discussed.

@drashna I have not removed TWIlib as some people might like to use it. But if you dont want it I can do so (it is already multiple times in individual keyboard folders)

**Comment by drashna** [comment]
I think that jack would be the better one to comment on the TWIlib stuff, but ... I think that we did want to standardize a lot of that stuff, so we don't have 10 different versions of the code all over the place.

**Comment by Wilba6582** [comment]
@yiancar code looks OK, if it fixes the stability issues you are having with TWIlib then make the change. 

I recommend removing TWIlib then, so future code uses this lib that doesn't require interrupts. IMHO for what we're doing, it's more versatile to use a lib that doesn't use interrupts, this means the routines can be called from an ISR (as long as they don't block indefinitely).

**Comment by Wilba6582** [comment]
@drashna OK to commit

**Comment by drashna** [comment]
Awesome, but I'll let @jackhumbert take a look and commit.

**Comment by jackhumbert** [comment]
Awesome - thanks!

**Pull request merged**
