### PR TITLE
Fixed Python module installation failure on Windows

### PR DESCRIPTION
**Pull request by shelaf**
Depending on the settings in the Windows code page, the installation of some Python modules may fail. Therefore, force the code page to UTF-8.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — COMMENTED** [review]
Could you provide more details on this? How does the code page figure into it?

**Comment by shelaf** [comment]
On Japanese Windows, the dotty_dict python module will fail to install without the PYTHONUTF8 variable. The default system locale for Japanese Windows is SJIS (cp932).
```
Collecting dotty-dict
  Using cached dotty_dict-1.3.0.tar.gz (32 kB)
    ERROR: Command errored out with exit status 1:
     command: C:/msys64/mingw64/bin/python3.exe -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:/Users/shela/AppData/Local/Temp/pip-install-8orid9bf/dotty-dict_d72650ddf926482ca2de14f98eb4cbc4/setup.py'"'"'; __file__='"'"'C:/Users/shela/AppData/Local/Temp/pip-install-8orid9bf/dotty-dict_d72650ddf926482ca2de14f98eb4cbc4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base C:/Users/shela/AppData/Local/Temp/pip-pip-egg-info-5grnb9d1
         cwd: C:/Users/shela/AppData/Local/Temp/pip-install-8orid9bf/dotty-dict_d72650ddf926482ca2de14f98eb4cbc4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:/Users/shela/AppData/Local/Temp/pip-install-8orid9bf/dotty-dict_d72650ddf926482ca2de14f98eb4cbc4/setup.py", line 16, in <module>
        readme = readme_file.read()
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x82 in position 119: illegal multibyte sequence
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a7/da/fc25898c4edb9549b2aac0f7329fec027d654e94d4c4b89849d4c5fff0a4/dotty_dict-1.3.0.tar.gz#sha256=eb0035a3629ecd84397a68f1f42f1e94abd1c34577a19cd3eacad331ee7cbaf0 (from https://pypi.org/simple/dotty-dict/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by skullydazed** [comment]
Apologies for how long it took me to get back to this, initially I had hoped that upstream would release a fixed package but that hasn't materialized. I've published a `qmk-dotty-dict` package that should be installable without this workaround. Can you give #13460 a try?

**Comment by shelaf** [comment]
I tried.

Python [qmk](https://pypi.org/project/qmk/) package requires `dotty_dict`, so [dependency definition](https://github.com/qmk/qmk_cli/blob/60a56b697652b831e25086cbee8a484c28cef5df/setup.py#L48) should be `qmk-dotty-dict`.

**Comment by skullydazed** [comment]
> Python [qmk](https://pypi.org/project/qmk/) package requires `dotty_dict`, so [dependency definition](https://github.com/qmk/qmk_cli/blob/60a56b697652b831e25086cbee8a484c28cef5df/setup.py#L48) should be `qmk-dotty-dict`.

I've released qmk 0.2.0 which changes that dependency. Can you give this another try?

**Comment by shelaf** [comment]
Great!
`qmk` package was successfully installed without the PYTHONUTF8 variable.
As another test, I confirmed that `qmk-dotty-dict` package is automatically installed when I run `qmk compile` command after manually uninstalling `qmk-dotty-dict` package.

**Comment by shelaf** [comment]
This issue was resolved in #13460.

**Pull request closed without merging**
