### PR TITLE
[Keymap] Added layout all ISO to Boardsource The Mark:65

### PR DESCRIPTION
**Pull request by jsanchez0x**
## Description
+ Added new layout for ISO all
* Change layout name "LAYOUT_all" to "LAYOUT_all_ansi"

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Review by zvecr — CHANGES_REQUESTED** [review]
This wont actually do anything, given only `LAYOUT_all` exists in `the_mark.h`. Also, `LAYOUT_all` ideally represents every possible switch location, so the existence of more than 1 all doesn't really make sense.

**Comment by noroadsleft** [comment]
I agree with zvecr; this change doesn't actually achieve anything.

Looks like you're trying to enable support for Split Backspace and Split Spacebar on the regional layouts. That can be done, but this isn't the way.

I'll have to circle back to this.

**Comment by tzarc** [comment]
Removed the tags preventing stalebot from auto-closing this PR.
If it's critical that this gets merged in, I'd suggest following up.

**Comment by noroadsleft** [comment]
The source fork for this PR appears to have been deleted, so I've made what seem to be the intended changes in #16270.

Closing.

**Pull request closed without merging**
