### PR TITLE
Add Blok RP2040 converter

### PR DESCRIPTION
**Pull request by filterpaper**
## Description

Add Promicro to [Blok](https://peg.software/docs/blok) RP2040 converter that uses QMK_PM2040 board.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by keyboard-magpie** [comment]
Hey @filterpaper are you able to link to the blok pinout you have used to sanity check this?

**Review by drashna — COMMENTED** [review]
`__attribute__((weak))` ✅

**Comment by filterpaper** [comment]
Depends on #17595

**Review by zvecr — APPROVED** [review]

**Review by keyboard-magpie — APPROVED** [review]
After I initially struggled to find the pinouts (boardsource need to publish those better) LGTM

**Comment by filterpaper** [comment]
> After I initially struggled to find the pinouts (boardsource need to publish those better) LGTM

Thank you. I agree than the pin out should be shared on the hardware product page, not deep inside the peg software website.

**Pull request merged**
