### PR TITLE
Fix ChibiOS backlight not turning off on suspend

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

This is present in the AVR suspend code, but missing here.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
did we want to import the rest of the code too? Eg, this: 
https://github.com/qmk/qmk_firmware/blob/8937c145140354f656a012ff6d6ec8d0a151ddd7/tmk_core/common/avr/suspend.c#L92-L100

Note, there doesn't seem to be any wake code (as it wouldn't actually be needed).

**Comment by fauxpark** [comment]
@drashna done

**Comment by tzarc** [comment]
LGTM, ship it.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
