### PR TITLE
We have corrected the previous review point, including related files.

### PR DESCRIPTION
**Pull request by marksard**
Hi,

We have corrected the previous review point, including related files.

* Change of how to compile display functions sources
* Add display to LED-parameters function
* Improvement of update timing for OLED display (Need TWI_Init)

Thank you for your helping.

### CODE REVIEW

**Comment by drashna** [comment]
IIRC, this board is based on the Helix keyboard.
And there have been a number of fixes/changes to the helix code that this is based on.  It may be worth checking to see if any of those updates can be ported here, as well.

**Comment by marksard** [comment]
It's based on Helix certainly, but I do not yet know how common the code is. 
So I will check what I can do :)

**Comment by drashna** [comment]
@foostan Does this look okay to you?

**Comment by marksard** [comment]
Hi,
@drashna , what are you asking about @foostan ?

**Comment by foostan** [comment]
OK, I'll check codes today.

**Comment by foostan** [comment]
@marksard Thanks for refactoring keymaps!

@drashna As difference with Helix got bigger, I would like to do some portable updates after merging this PR. What do you think?

**Comment by drashna** [comment]
Well, I think that mtei was looking to convert the helix to the split common code, at least, in part.  And that would help. 

But for the meanwhile, yeah, that sounds good.

**Pull request merged**
