### PR TITLE
Fixup bastardkb charybdis & dilemma

### PR DESCRIPTION
**Pull request by waffle87**
## Description
Don't try to compile `*/v2/splinky` — needs a version specified (v2/v3)

## Types of Changes

- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
I would prefer if the innermost folders were removed instead of skipping one.

**Comment by waffle87** [comment]
The `splinky/v*/` directories? Unsure what the best approach would be given the differences
```diff
diff v2/config.h v3/config.h
22c22
<     { GP28, GP15, GP6, GP7, GP8 }
---
>     { GP28, GP21, GP6, GP7, GP8 }
25,27c25,27
< #define SPI_SCK_PIN GP18
< #define SPI_MOSI_PIN GP19
< #define POINTING_DEVICE_CS_PIN GP14
---
> #define SPI_SCK_PIN GP22
> #define SPI_MOSI_PIN GP23
> #define POINTING_DEVICE_CS_PIN GP16
```

**Comment by fauxpark** [comment]
eg. `bastardkb/charybdis/3x5/v2/splinky_2`/`_3`
There is precedent for this in the Teensy Onekeys:
image

**Comment by waffle87** [comment]
Ah thanks that makes sense.

**Review by fauxpark — APPROVED** [review]

**Comment by fauxpark** [comment]
Merge conflicts.

**Comment by 0xcharly** [comment]
Could we hold these changes for now? 

We already have merge an immediate fix in master, and there's other changes in flight that this PR will conflict with, and make half of this PR obsolete.

I'd rather handle this myself, and for now the CI should not be a problem.

**Pull request closed without merging**
