### PR TITLE
Allow post_config.h to be implemented in userspace

### PR DESCRIPTION
**Pull request by spidey3**
## Description

Allow `post_config.h` to be defined in userspace directories.

At present, we pay attention to it in keyboard and keymap directories, but not in the userspace. 

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by spidey3** [comment]
@skullydazed this is the item we were discussing at https://discord.com/channels/440868230475677696/440868230475677698/798321601858764830

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]
`#pragma weak`

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Conceptual approval, needs some conflict resolution, though.

**Comment by spidey3** [comment]
> Conceptual approval, needs some conflict resolution, though.

Rebased and pushed.

**Comment by tzarc** [comment]
> Rebased and pushed.

Squashed and merged.

:)

**Pull request merged**
