### PR TITLE
Set some default configurations for GMMK Pro

### PR DESCRIPTION
**Pull request by andrebrait**
## Description

Adding a few configurations as defaults for the GMMK Pro which I think make sense either because they're either
1. The defaults on the stock firmware, or
2. Useful for a keyboard focused on enthusiasts and gamers, or
3. The same as the default value on QMK, but I tried to make them explicit here

Maybe it would be up to @glorious-qmk to check if these changes make sense for the GMMK Pro, but I think at least setting `USB_POLLING_INTERVAL_MS` to 1 does.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by andrebrait** [comment]
@drashna I ended up opening this PR against `master` but I guess I should've gone for `develop`? Just asking because I see the other activity for the GMMK Pro is on `develop`

**Comment by drashna** [comment]
This should be okay.  It will get merged into develop, if/when it's merged into master.  And given the type of change, it shouldn't cause any issues.

**Comment by Gigahawk** [comment]
Can confirm this seems to work fine on my board

**Comment by andrebrait** [comment]
@Gigahawk I don't think that's such a niche scenario. I myself switch between machines sometimes, though I have a simple USB switch instead of a full KVM.

Could you maybe comment out some of the options and see if that helps?

**Comment by Gigahawk** [comment]
Looks like removing `FORCE_NKRO` makes the issue go away.
No idea what the problem is, I'm switching between two Windows 10 hosts, one just happens to have really underpowered hardware.

**Comment by andrebrait** [comment]
It's probably more connected to quirks of the USB controller and whatnot, I imagine.

Let's remove it then.

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Comment by andrebrait** [comment]
@Gigahawk sorry for the necro, but I found out that MOUSEKEY causes a lot of issues on this board with KVM switches.
I had to disable it in order to get my keyboard to stop failing when switching between my Mac and my Windows PC (see #15943).

It seems to cause it on many others too, see #15949.

Maybe it's worth trying to see if you can now keep NKRO enabled and also be able to use your KVM.

**Pull request merged**
