### PR TITLE
Nix shell updates (Nixpkgs 2024-02-23, QMK CLI 1.1.5)

### LINKED ISSUE #20704: [Bug] ModuleNotFoundError: No module named 'qmk_cli' inside nix-shell
### Describe the Bug

I made a fresh clone of the repository, ran `nix-shell`, and then `qmk setup`. Instead of the setup command working, I instead got the following error:

```
Ψ Found qmk_firmware at /home/amey/Developer/qmk_firmware.
Traceback (most recent call last):
  File "/nix/store/m59glinmmwjsn191d2l94aiqlc79nvw9-python3.8-qmk-1.1.1/bin/qmk", line 5, in <module>
    from qmk_cli.script_qmk import main
ModuleNotFoundError: No module named 'qmk_cli'
```

### Keyboard Used

Not applicable

### Link to product page (if applicable)

_No response_

### Operating System

Ubuntu 22.04

### qmk doctor Output

```text
[nix-shell:~/Developer/qmk_firmware]$ qmk doctor
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.1
Ψ QMK home: /home/amey/Developer/qmk_firmware
Ψ Detected Linux (Ubuntu 22.04.2 LTS).
⚠ Missing or outdated udev rules for 'atmel-dfu' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'kiibohd' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'stm32-dfu' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'apm32-dfu' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'gd32v-dfu' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'bootloadhid' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'usbasploader' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'usbtinyisp' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'md-boot' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Detected ModemManager without the necessary udev rules. Please either disable it or set the appropriate udev rules if you are using a Pro Micro.
⚠ Missing or outdated udev rules for 'caterina' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'hid-bootloader' boards. Run 'sudo cp /home/amey/Developer/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
Ψ Git branch: master
Ψ Repo version: 0.9.50
⚠ The official repository does not seem to be configured as git remote "upstream".
Ψ CLI installed in virtualenv.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.2.1
Ψ Found avr-gcc version 8.4.0
Ψ Found avrdude version 6.3
Ψ Found dfu-programmer version 0.7.2
Ψ Found dfu-util version 0.10
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2023-01-03 19:29:26 +0000 --  (0062927e3)
Ψ - lib/chibios-contrib: 2023-01-11 16:42:27 +0100 --  (a224be15)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go, but minor problems were found
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

_No response_

### Additional Context

_No response_

### LINKED ISSUE #22348: [Bug] Cannot start nix-shell on macOS
### Describe the Bug

Cloning the repository, then trying to start `nix-shell` results in the following errors:

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'qmk-firmware'
         whose name attribute is located at /Users/emiliazapata/projects/qmk_firmware/shell.nix:69:3

       … while evaluating attribute 'AVR_ASFLAGS' of derivation 'qmk-firmware'

         at /Users/emiliazapata/projects/qmk_firmware/shell.nix:82:3:

           81|   AVR_CFLAGS = lib.optional avr avr_incflags;
           82|   AVR_ASFLAGS = lib.optional avr avr_incflags;
             |   ^
           83|   shellHook = ''

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called without required argument 'lib'

       at /nix/store/gm4rp1786ligd81v2qz420nkrwy0r50k-nixpkgs-src/pkgs/build-support/cc-wrapper/default.nix:8:1:

            7|
            8| { name ? ""
             | ^
            9| , lib
```

### Keyboard Used

_No response_

### Link to product page (if applicable)

_No response_

### Operating System

macOS 14.0

### qmk doctor Output

_No response_

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

_No response_

### Additional Context

nix (Nix) 2.17.0

### PR DESCRIPTION
**Pull request by sigprof**
## Description

Major updates for the Nix shell environment:

  - Nixpkgs updated to the 2024-02-23 snapshot.  This change brings support for the `aarch64-darwin` and `aarch64-linux` hosts, and the AVR toolchain now comes from the official binary cache instead of requiring a time-consuming local build from sources.

  - QMK CLI updated to 1.1.5 (the most recent release at the moment).

  - Other Python modules are updated to their recent versions.

  - Dropped some obsolete build-time dependencies from `util/nix/pyproject.toml` (those dependencies were added there to work around build problems caused by the old Nixpkgs snapshot, and are no longer needed after updating `nixpkgs` and `poetry2nix` to the current versions).

  - Updated `util/nix/sources.nix` from the current Niv version.

  - Fixed the `qmk setup` command failure (#20704); although that command is mostly unneeded with the `nix-shell` workflow, it could still be used to set up the global QMK CLI configuration.

  - Pinned `clang-tools` to major version 11, so that `clang-format` (and therefore `qmk format-c`) would produce the same results as the QMK CI environment (which currently uses Docker images based on Debian bullseye with `clang-format` 11.0).

Toolchain version changes:
  - `avr-binutils`: 2.35.1 → 2.40
  - `avr-gcc`: 8.4.0 → 8.5.0 (still using 8.x versions, because 13.x is not yet avalable for all supported architectures in Nixpkgs)
  - `avr-libc`: 2.0.0 → 2.1.0
  - `gcc-arm-embedded`: 10-2020-q4-major → 12.3.rel1

Version changes for other supporting packages:
  - `avrdude`: 6.3 → 7.3
  - `dfu-util`: 0.10 → 0.11
  - `git`: 2.30.1 → 2.43.0
  - `python3`: 3.8.8 → 3.11.7
  - `teensy-loader-cli`: 2.1.20191110 → 2.2

Version changes for Python modules:
  - `argcomplete`: 2.0.0 → 3.2.2
  - `atomicwrites`: 1.4.1 → none
  - `attrs`: 22.1.0 → 23.2.0
  - `colorama`: 0.4.5 → 0.4.6
  - `editables`: 0.3 → none
  - `flake8`: 5.0.4 → 7.0.0
  - `flit-core`: 3.7.1 → none
  - `hatch-fancy-pypi-readme`: 22.3.0 → none
  - `hatch-vcs`: 0.2.0 → none
  - `hatchling`: 1.8.0 → none
  - `hid`: 1.0.5 → 1.0.6
  - `importlib-resources`: 5.9.0 → none
  - `importlib-metadata`: none → 7.0.1
  - `iniconfig`: 1.1.1 → none
  - `jsonschema`: 4.14.0 → 4.21.1
  - `jsonschema-specifications`: none → 2023.12.1
  - `milc`: 1.6.6 → 1.8.0
  - `nose2`: 0.12.0 → 0.14.1
  - `packaging`: 21.3 → none
  - `pathspec`: 0.9.0 → none
  - `pep8-naming`: 0.13.2 → 0.13.3
  - `pillow`: 9.2.0 → 10.2.0
  - `pkgutil-resolve-name`: 1.3.10 → none
  - `pluggy`: 1.0.0 → none
  - `platformdirs`: none → 4.2.0
  - `poetry-core`: 1.0.8 → none
  - `py`: 1.11.0 → none
  - `pycodestyle`: 2.9.1 → 2.11.1
  - `pyflakes`: 2.5.0 → 3.2.0
  - `pygments`: 2.13.0 → 2.17.2
  - `pyparsing`: 3.0.9 → none
  - `pyrsistent`: 0.18.1 → none
  - `pytest`: 7.1.2 → none
  - `qmk`: 1.1.1 → 1.1.5
  - `setuptools-scm`: 7.0.5 → none
  - `referencing`: none → 0.33.0
  - `rpds-py`: none → 0.18.0
  - `termcolor`: 1.1.0 → 2.4.0
  - `typing-extensions`: 4.3.0 → none
  - `types-colorama`: none → 0.4.15.20240205
  - `yapf`: 0.32.0 → 0.40.2
  - `zipp`: 3.8.1 → 3.17.0

------

The branch was tested on [`x86_64-linux`](https://github.com/sigprof/qmk-nix-support/actions/runs/8031000381/job/21938894649), [`x86_64-darwin`](https://github.com/sigprof/qmk-nix-support/actions/runs/8031000381/job/21938894705) and [`aarch64-darwin`](https://github.com/sigprof/qmk-nix-support/actions/runs/8031012230/job/21938920645); not actually tested on `aarch64-linux` (GitHub still does not provide such runners); also tested locally on `x86_64-linux` (NixOS 23.11).

Cc: @purcell @AstridYu @andresilva @evils

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #20704
* Hopefully fixes #22348 (works on GitHub-provided `macos-14` runners, which have the M1 CPU).

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by synecdokey** [comment]
Ran without a hitch on my M1 machine, thanks for doing this!

**Review by evils — APPROVED** [review]
works for me

changes all look like cleanup to me
but i didn't scrutinize it beyond that

**Review by purcell — APPROVED** [review]
Nice 👍

**Review by tzarc — APPROVED** [review]
Weak approval, going with merge due to SMEs giving thumbs-up.

**Pull request merged**
