### PR TITLE
Check LED flags for Pixel Fractal effect

### LINKED ISSUE #23850: [Bug] rgb matrix effect bug.
### Describe the Bug

https://github.com/qmk/qmk_firmware/blob/master/quantum/rgb_matrix/animations/pixel_fractal_anim.h  

This RGB effect does not limit the NO_LED and will cause access to the wild pointer, which will cause the MCU to malfunction.

### Keyboard Used

_No response_

### Link to product page (if applicable)

_No response_

### Operating System

_No response_

### qmk doctor Output

_No response_

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by filterpaper**
## Description

Refactor effect to account for LED flags

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #23850

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by filterpaper** [comment]
CI build failure due to size will be fixed by #23883

**Review by drashna — APPROVED** [review]
I can't repo the crashing bug, but this does fix the animation respecting flags.

**Comment by filterpaper** [comment]
Thanks @drashna for helping with the test.

**Review by itarze — APPROVED** [review]
Thank you for solving the issue.

**Review by zvecr — APPROVED** [review]

**Pull request merged**
