### PR TITLE
Port DIRECT_PINS from split_common/matrix.c to matrix.c

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Discussion within #5026

split_common already contains a method of mapping pins when diodes are not used, `DIRECT_PINS`. This is currently missing from the non split `matrix.c`.

This PR aligns some of the functionality of `matrix.c` and `split_common/matrix.c` as well as reorders some of the functions to aid diff-ability. Finally i have added docs for the `DIRECT_PINS` option.

As a review hint, it might help to go via the commit history, as the moving of functions was done after the main functionality was added.

## Types of changes

- [x] Core
- [ ] Bugfix
- [ ] New Feature
- [x] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* #5026

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by pelrun** [comment]
> To define a matrix where each pin is tied to ground, instead of using diodes, use `DIRECT_PINS`.

Diodes aren't the defining feature of the wiring system, so it's not really correct to mention them here. Something more like the following would be better:

"To configure a keyboard where each switch is connected to a separate pin and ground instead of sharing row and column pins, use `DIRECT_PINS`."

**Comment by pelrun** [comment]
Other than getting the documentation right, this looks good (although I'm obviously going to say that, having written the original code.)

Thanks for doing this!

**Comment by drashna** [comment]
There are some merge conflicts here.

**Comment by zvecr** [comment]
@drashna thanks for the heads up, I have fixed the merge issue.

**Comment by zvecr** [comment]
Looks like another use case with #5266.

**Comment by zvecr** [comment]
Staryu also requires this change as it defines the matrix as `#define MATRIX_ROW_PINS {  }`

**Pull request merged**
