### PR TITLE
move @latincompass (aka @18438880 , @haierwangwei2005)'s boards to /latincompass

### PR DESCRIPTION
**Pull request by peepeetee**
## Description
At this point in my series of board move PRs, I've started to move boards where I cannot reach the makers beforehand, and have to contact them via the PR itself. 

This PR is made without contacting(or failing at contacting) @latincompass ( @18438880 , @haierwangwei2005 ) first, so it would need them to approve it for it to go in.

As there was no prior communication before this PR, I have to ask a few questions:
* Is the folder name satisfactory?
* Did I leave anything out?
* Did I include anything I shouldn't have included?

One of the reasons I'm electing to do this is to get as many PRs in as possible before the breaking change deadline, please stop me in my tracks if this is inappropriate.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by latincompass** [comment]
Thanks a Lot,Sir,I appreciate your work.

**Comment by latincompass** [comment]
The 18438880 and haierwangwei2005 two  Account is also my Account

**Review by latincompass — APPROVED** [review]
Thank you for your hard work,Sir

**Review by haierwangwei2005 — APPROVED** [review]
Thank you for your hard work,Sir

**Review by 18438880 — APPROVED** [review]
Thank you for your hard work,Sir

**Comment by latincompass** [comment]
Thank you for your hard work,Sir&nbsp; I have Approve it in latincompass 18438880 haierwangwei2005 those 3 Accounts .


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qmk/qmk_firmware"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月25日(星期二) 晚上11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[qmk/qmk_firmware] move @latincompass (aka @18438880 , @haierwangwei2005)'s boards to /latincompass (PR #16039)



 
Description
 
At this point in my series of board move PRs, I've started to move boards where I cannot reach the makers beforehand, and have to contact them via the PR itself.
 
This PR is made without contacting(or failing at contacting) @latincompass ( @18438880 , @haierwangwei2005 ) first, so it would need them to approve it for it to go in.
 
One of the reasons I'm electing to do this is to get as many PRs in as possible before the breaking change deadline, please stop me in my tracks if this is inappropriate.
 
Types of Changes
  
 Core
 
 Bugfix
 
 New feature
 
 Enhancement/optimization
 
 Keyboard (addition or update)
 
 Keymap/layout/userspace (addition or update)
 
 Documentation
  
Issues Fixed or Closed by This PR
  

  
Checklist
  
 My code follows the code style of this project: C, Python
 
 I have read the PR Checklist document and have made the appropriate changes.
 
 My change requires a change to the documentation.
 
 I have updated the documentation accordingly.
 
 I have read the CONTRIBUTING document.
 
 I have added tests to cover my changes.
 
 I have tested the changes and verified that they work and don't break anything (as well as I can manage).
  
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; https://github.com/qmk/qmk_firmware/pull/16039
 
Commit Summary
    
aa068fe  move @latincompass (aka @18438880 , @haierwangwei2005)'s boards to /latincompass
  
File Changes 
 
(65 files)
    
     R     keyboards/latincompass/latin17rgb/config.h     (0)   
   
     R     keyboards/latincompass/latin17rgb/info.json     (0)   
   
     R     keyboards/latincompass/latin17rgb/keymaps/default/keymap.c     (0)   
   
     R     keyboards/latincompass/latin17rgb/keymaps/via/keymap.c     (0)   
   
     R     keyboards/latincompass/latin17rgb/keymaps/via/rules.mk     (0)   
   
     R     keyboards/latincompass/latin17rgb/latin17rgb.c     (0)   
   
     R     keyboards/latincompass/latin17rgb/latin17rgb.h     (0)   
   
     R     keyboards/latincompass/latin17rgb/readme.md     (4)   
   
     R     keyboards/latincompass/latin17rgb/rules.mk     (0)   
   
     R     keyboards/latincompass/latin47ble/config.h     (0)   
   
     R     keyboards/latincompass/latin47ble/info.json     (0)   
   
     R     keyboards/latincompass/latin47ble/keymaps/default/keymap.c     (0)   
   
     R     keyboards/latincompass/latin47ble/keymaps/via/keymap.c     (0)   
   
     R     keyboards/latincompass/latin47ble/keymaps/via/rules.mk     (0)   
   
     R     keyboards/latincompass/latin47ble/latin47ble.c     (0)   
   
     R     keyboards/latincompass/latin47ble/latin47ble.h     (0)   
   
     R     keyboards/latincompass/latin47ble/readme.md     (2)   
   
     R     keyboards/latincompass/latin47ble/rules.mk     (0)   
   
     R     keyboards/latincompass/latin60rgb/config.h     (0)   
   
     R     keyboards/latincompass/latin60rgb/info.json     (0)   
   
     R     keyboards/latincompass/latin60rgb/keymaps/default/keymap.c     (0)   
   
     R     keyboards/latincompass/latin60rgb/keymaps/via/keymap.c     (0)   
   
     R     keyboards/latincompass/latin60rgb/keymaps/via/rules.mk     (0)   
   
     R     keyboards/latincompass/latin60rgb/latin60rgb.c     (0)   
   
     R     keyboards/latincompass/latin60rgb/latin60rgb.h     (0)   
   
     R     keyboards/latincompass/latin60rgb/readme.md     (2)   
   
     R     keyboards/latincompass/latin60rgb/rules.mk     (0)   
   
     R     keyboards/latincompass/latin64ble/config.h     (0)   
   
     R     keyboards/latincompass/latin64ble/info.json     (0)   
   
     R     keyboards/latincompass/latin64ble/keymaps/default/keymap.c     (0)   
   
     R     keyboards/latincompass/latin64ble/keymaps/via/keymap.c     (0)   
   
     R     keyboards/latincompass/latin64ble/keymaps/via/rules.mk     (0)   
   
     R     keyboards/latincompass/latin64ble/latin64ble.c     (0)   
   
     R     keyboards/latincompass/latin64ble/latin64ble.h     (0)   
   
     R     keyboards/latincompass/latin64ble/readme.md     (2)   
   
     R     keyboards/latincompass/latin64ble/rules.mk     (0)   
   
     R     keyboards/latincompass/latin6rgb/config.h     (0)   
   
     R     keyboards/latincompass/latin6rgb/info.json     (0)   
   
     R     keyboards/latincompass/latin6rgb/keymaps/default/keymap.c     (0)   
   
     R     keyboards/latincompass/latin6rgb/keymaps/via/keymap.c     (0)   
   
     R     keyboards/latincompass/latin6rgb/keymaps/via/rules.mk     (0)   
   
     R     keyboards/latincompass/latin6rgb/latin6rgb.c     (0)   
   
     R     keyboards/latincompass/latin6rgb/latin6rgb.h     (0)   
   
     R     keyboards/latincompass/latin6rgb/readme.md     (2)   
   
     R     keyboards/latincompass/latin6rgb/rules.mk     (0)   
   
     R     keyboards/latincompass/latinpad/config.h     (0)   
   
     R     keyboards/latincompass/latinpad/info.json     (0)   
   
     R     keyboards/latincompass/latinpad/keymaps/default/keymap.c     (0)   
   
     R     keyboards/latincompass/latinpad/keymaps/via/keymap.c     (0)   
   
     R     keyboards/latincompass/latinpad/keymaps/via/rules.mk     (0)   
   
     R     keyboards/latincompass/latinpad/latinpad.c     (0)   
   
     R     keyboards/latincompass/latinpad/latinpad.h     (0)   
   
     R     keyboards/latincompass/latinpad/lib/glcdfont.c     (0)   
   
     R     keyboards/latincompass/latinpad/readme.md     (2)   
   
     R     keyboards/latincompass/latinpad/rules.mk     (0)   
   
     R     keyboards/latincompass/latinpadble/config.h     (0)   
   
     R     keyboards/latincompass/latinpadble/info.json     (0)   
   
     R     keyboards/latincompass/latinpadble/keymaps/default/keymap.c     (0)   
   
     R     keyboards/latincompass/latinpadble/keymaps/via/keymap.c     (0)   
   
     R     keyboards/latincompass/latinpadble/keymaps/via/rules.mk     (0)   
   
     R     keyboards/latincompass/latinpadble/latinpadble.c     (0)   
   
     R     keyboards/latincompass/latinpadble/latinpadble.h     (0)   
   
     R     keyboards/latincompass/latinpadble/lib/glcdfont.c     (0)   
   
     R     keyboards/latincompass/latinpadble/readme.md     (2)   
   
     R     keyboards/latincompass/latinpadble/rules.mk     (0)   
  
Patch Links:
    
https://github.com/qmk/qmk_firmware/pull/16039.patch
   
https://github.com/qmk/qmk_firmware/pull/16039.diff
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by drashna** [comment]
Merge conflicts

**Comment by peepeetee** [comment]
> Merge conflicts

resolved

**Review by zvecr — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Pull request merged**
