### PR TITLE
add the ability to change the pwm frequency for the IS31FL3737B

### PR DESCRIPTION
**Pull request by Frooastside**
## Description
I made the same changes to support changing the PWM frequency with the IS31FL3737B and no longer just the IS31FL3733B.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [X] New feature
- [X] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Frooastside** [comment]
I don't really know if this is a core change and instead should be merged into the develop branch, but it is definetly not a breaking change.

**Review by zvecr — APPROVED** [review]

**Comment by zvecr** [comment]
> if this is a core change and instead should target the develop branch

It would be considered `core`, and we generally want those to go via develop. It *could* go directly to master as it should be backwards compatible, though this wouldnt be my preference. I will leave that open to other collabs.

**Review by drashna — APPROVED** [review]
Yeah, I think I would prefer that this go to develop, and through the normal breaking changes cycle. 

Mostly, because it's a slippery slope.   If it's a small change, and we let it through, how big of a change does it have to be?  Etc.  

The policy has been that bugfixes are okay to go to master, directly. Eg, stuff that breaks compiling altogether, or breaks behavior.

**Comment by Frooastside** [comment]
As i said I wasn't sure, now I am. Should I change it to target the develop branch instead?

**Pull request merged**
