### PR TITLE
KBDFans DZ60 Support

### PR DESCRIPTION
**Pull request by yanfali**
Hi,

I'd like to contribute DZ60 support. This is my first PR to qmk_firmware, so please let me know if I've done stuff incorrectly. I've tested this configuration on my board successfully for the last week or so and it seems to work well. All the features of the board appear enabled. Thanks

I'm also happy to squash this down to a single commit before merging.

### CODE REVIEW

**Comment by yanfali** [comment]
Oh, my bad, I see this has already been added. Then I'll close the PR. Is it ok to contribute a keymap?

**Comment by Maartenwut** [comment]
You're encouraged to do so :)

**Comment by jackhumbert** [comment]
Awesome! Please do double-check the current implementation -  I haven't had the chance to actually test it yet :)

**Comment by yanfali** [comment]
Oh, that's a shame. My version was actually tested, but you beat me to the punch :)

**Comment by yanfali** [comment]
I'll test your version right now

**Comment by yanfali** [comment]
hmmm, my shift key is connected to a different pin from yours. Mind if I override your dz.h file?

**Comment by yanfali** [comment]
Ah, OK. I see what I need to do. I'll use a  different define.

**Pull request closed without merging**
