### PR TITLE
ISSI31FL3733 driver 

### PR DESCRIPTION
**Pull request by yiancar**
- Finalized and tested driver.
- Modified i2c_master for arm due to declaration mistake.
- Fixed spaces/tabs in quantum.h file.
- Fixed spaces/tabs in common_features.mk file.
- Removed unnecessary includes from rgb_matrix.c file.
- Added local definitions for MIN and MAX macros in rgb_matrix.c file.
- Adjusted chevron effect.
- Added necessary define (RGB_3733_MATRIX_ENABLE) for makefile.
- Added necessary C define (ISSI3733) to aid with inclusion of the correct header file.
- Added documentation for the new driver.

### CODE REVIEW

**Comment by drashna** [comment]
I know this would be more complicated and make more work for you, but wouldn't it be better to handle the driver like we do for MCU's and the like? 

Eg, use `RGB_MATRIX_DRIVER = 3733` or  `RGB_MATRIX_DRIVER = ISSI31FL3733`, rather than `RGB_3733_MATRIX_ENABLE = yes`.

The advantage of this would be that it would allow for additional of more controllers, in the future with minimal work. 

(I'm mostly thinking out loud here)

**Comment by ishtob** [comment]
wouldn't it make sense here to move the ISSI files to a folder within driver? They offer quite a few chips and may clutter the driver base folder

**Comment by Wilba6582** [comment]
I've talked to @yiancar about this and I think each LED driver (be they ISSI or not) have unique function names such as `IS31FL3731_init()` and their interface have specialization as required (i.e. passed in I2C addresses or not, functions to access specific features of that IC, etc.). Then code such as the RGB matrix driver (i.e. higher level, managing effects, etc.) can conditionally compile where the low-level IC driver functions are called. This results in clearer code. Generalization happens in the calling code, not via multiple low-level IC drivers sharing identical function names - this is TBH a bit of a hacky implementation of polymorphism that doesn't need to be there.

Having just written another ISSI driver for IS31FL3218 which could potentially be used in the RGB matrix, but doesn't fully "fit" the same interface, it makes sense to continue the original way this was done with explicit function names like `IS31FL3218_init()` While it might be a long way off before someone wants to use two different ISSI ICs in an implementation, the fact that the current naming and conditional compilation at the source file level would prevent this, is reason enough to stick to the original function naming and move towards conditional compilation where the IC drivers are used.

**Comment by Wilba6582** [comment]
@yiancar 👍

**Comment by yiancar** [comment]
OK I made all the above changes except the driver subfolder until i get a confirmation on that

**Comment by jackhumbert** [comment]
Yeah, that all sounds good - I think a subfolder in drivers for all the ISSI stuff would make sense.

**Comment by yiancar** [comment]
Sorry everyone found a tiny bug with releasing the special pins. it is now fixed

**Comment by drashna** [comment]
This supports only a single 3733 controller, right?  No dual controllers? 

If so, is there a reason for that?  (I ask, because I'm selfish and want dual 3733's for the Ergodox or similar board, that has 78 keys)

**Comment by yiancar** [comment]
Nop there is no reason (except that I only needed one). You just need to expand the functions as with the 3731. Follow the structure and ull be ok. The only difference is that it is suggested you connect the sync pins and at the init of the first one assign it as master and the second (third etc) as slave. This is a 2 byte flag which can be found on the datasheet:)

**Comment by Wilba6582** [comment]
I was thinking about this the other day when doing the '3736 driver... we could ignore addr2 if it is 0x00

**Comment by jackhumbert** [comment]
Sure! Thanks all!

**Pull request merged**
