### PR TITLE
Remove lock LED example in quantum.c

### PR DESCRIPTION
**Pull request by fauxpark**
## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Someone got to this code first, so the only change now is updating the example.

**Comment by drashna** [comment]
Honestly, I'm not sure if we need that example, at all....   But I'll defer to @jackhumbert or @skullydazed

**Comment by fauxpark** [comment]
Yeah, something like it is already in the docs, so maybe I should just delete it.

**Comment by fauxpark** [comment]
@drashna ping :)

**Pull request merged**
