### PR TITLE
Fixes non-unique vid and pid for sofle_choc 

### PR DESCRIPTION
**Pull request by JellyTitan**
The sofle_choc has [the same VendorID and ProductID as sofle/rev1](https://github.com/the-via/keyboards/pull/2139#discussion_r1477167695). This PR changes the VID/PID for sofle_choc to make them unique. The keyboard creator, Brian Low, [approved the VID/PID update](https://github.com/josefadamcik/SofleKeyboard/issues/194#issuecomment-1943001616). 
I checked for conflicts between the new VID/PID in the latest QMK and didn't find any.

I went with "BL" (Brian Low) for vendor ID & "SC" (Sofle Choc) for ProductID.

@brianlow tagging for visibility.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by brianlow — APPROVED** [review]

**Comment by t-8ch** [comment]
Wouldn't it be better to allocate a pid from https://pid.codes instead as that does not risk conflicts?

**Comment by JellyTitan** [comment]
@t-8ch 

> Wouldn't it be better to allocate a pid from https://pid.codes instead as that does not risk conflicts?

Is there any official QMK guidance on this? 

It looks like many devices in QMK are built/maintained by individuals, and the pid.codes registry seems geared towards organizations. 

If I'm adding VID/PID for other peoples projects, then I'd need to create org profiles for other people - which feels weird?

**Comment by keyboard-magpie** [comment]
https://docs.qmk.fm/#/faq_build?id=usb-vid-and-pid

I don't understand why sofle choc needs a different pair than the original sofle though? They have the same key layout etc.

**Comment by JellyTitan** [comment]
> https://docs.qmk.fm/#/faq_build?id=usb-vid-and-pid
> 
> I don't understand why sofle choc needs a different pair than the original sofle though? They have the same key layout etc.

The Sofle Choc needs a unique pair because it has RGB, and the original Sofle does not.

**Comment by keyboard-magpie** [comment]
There are plenty non-choc sofles with RGB. It would make more sense to me (presuming this is for VIA purposes) to edit the VIA json.

**Comment by JellyTitan** [comment]
> There are plenty non-choc sofles with RGB. It would make more sense to me (presuming this is for VIA purposes) to edit the VIA json.

There is one Sofle RGB already in VIA -but that is the [keyhive variant](https://github.com/the-via/keyboards/tree/master/src/sofle), which has a different pinout, so that VIA config is not compatible with the Sofle Choc.

The keyhive unique pinout variant issue is mentioned [here](https://josefadamcik.github.io/SofleKeyboard/). 

This PR is for VIA purposes. The [VIA PR is blocked by the Sofle Choc having a non-unique PID/VID](https://github.com/the-via/keyboards/pull/2139#discussion_r1477167695). The VIA issue aside, the Sofle Choc should still have a unique PID/VID.

**Comment by JellyTitan** [comment]
@t-8ch 
> Wouldn't it be better to allocate a pid from https://pid.codes instead as that does not risk conflicts?

I followed up on this in the [QMK discord channel](https://discord.com/channels/440868230475677696/1215860348503064616/1215860348503064616). Using pid.codes is not a requirement, and I would feel weird creating profiles for other people, so I will not update this PR to use pid.codes. 

The initial pull request PID/VID remains unchanged.

**Comment by t-8ch** [comment]
@JellyTitan 

> The initial pull request PID/VID remains unchanged.

Ok

**Comment by JellyTitan** [comment]
All issues have been addressed. Waiting for review.

**Comment by JellyTitan** [comment]
@drashna would you be so kind as to review? The PR has been approved by the boards creator, and all other concerns have been addressed. (Plus it's only two lines)!

**Pull request closed without merging**
