### PR TITLE
Only upgrade formulae ~~Remove brew upgrade and prompts the user~~

### LINKED ISSUE #12794: Petition to remove brew upgrade from install script
The line to upgrade brew in the install script for macOS can have unintended consequences for users. In my case it broke some of my installs. I can see that it ignores pinned versions but to be honest, nobody really uses this feature.

If this is not doable - there should be a promt to inform the user that the script will run brew upgrade and the ability to opt out!

The line in question:
[https://github.com/qmk/qmk_firmware/blob/master/util/install/macos.sh#L12](https://github.com/qmk/qmk_firmware/blob/master/util/install/macos.sh#L12)

### PR DESCRIPTION
**Pull request by brorbw**
This will remove the old way of forcefully upgrading peoples systems
without proper notice and consent.

If there are any packages or dependencies that needs upgrading it will
prompt the user and he/she/they/ze can consent to the upgrade or
continue without at own risk.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #12794
## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
I'm opposed to adding a prompt here, as the install process should require as little user interaction as possible.

**Comment by brorbw** [comment]
@fauxpark what would you recommend instead? I'm not married to this solution but just upgrading `brew` with no prompt to opt out is not a good solution. Another solution would be to ONLY upgrade the required dependencies.

**Comment by fauxpark** [comment]
I'm not so sure there is a solution necessary. Could you provide more details on how exactly upgrading Brew breaks stuff for you?

**Comment by drashna** [comment]
I think a better solution may be to include a note in the documentation, that if you do have pinned packages, that you should run the install by hand. Maybe with instructions on how to do so. 

This way, the workflow that we have isn't altered, but does include a path for those with pinned packages.

**Comment by brorbw** [comment]
Looking through the install scripts for other distros I can see that they are far more specific declaring dependencies. 

> more details on how exactly upgrading Brew breaks stuff

I haven't figured out exactly what broke yet but more than once I have had `brew` upgrade and break emacs and most recently it broke my docker setup. Full disclosure I run an AMD hackintosh but that does not diminish the fact that `brew upgrade` left my system in a broken state and I would like full control over a systemwide upgrade. 

Following the logic I don't understand why `pacman -Syu` isn't used in arch.sh?

**Comment by brorbw** [comment]
@fauxpark even using pinned packages they can get upgraded if you install/upgrade a package that depends on it. This means that even using pinned packages this way of installing could still upgrade packages unintentionally.

**Comment by itspngu** [comment]
> I'm opposed to adding a prompt here, as the install process should require as little user interaction as possible.

In that case QMK should default to the containerized setup - that'd also have benefits past this issue.

Messing with a user's system without at least prompting is a no-go. Hiding it in the docs for "simplicity" would also be quite the opposite of a very straightforward 'hey we'll do xyz, okay?' in my opinion.

**Comment by tzarc** [comment]
> I haven't figured out exactly what broke yet but more than once I have had brew upgrade and break emacs and most recently it broke my docker setup

That sounds like an issue with upstream brew, not QMK, to be completely honest.

**Comment by drashna** [comment]
> In that case QMK should default to the containerized setup - that'd also have benefits past this issue.

We do have a docker container set up.  it just lacks integration with `qmk` cli.

https://docs.qmk.fm/#/getting_started_docker

**Comment by brorbw** [comment]
> That sounds like an issue with upstream brew, not QMK, to be completely honest.

Well kinda - I'm running a few taps that are not from upstream and its definitely a `brew` problem that revealed a problem in the way QMK uses `brew`. When I'm upgrading I'm very particular with what I'm upgrading and running dry-runs. 

Maybe I would suggest that `brew install qmk/qmk/qmk` installed the dependencies needed and NOT `qmk setup`

**Comment by skullydazed** [comment]
It's true that we are inconsistent about which platforms we upgrade everything on. We do upgrade on msys2, for example. I think a lot of this is driven by actual problems users have encountered.

If we're going to add a prompt I'd suggest that the better place would be in `util/qmk_install.sh`. Using prompts in msys2 is problematic, it's likely we'll want to special case that out, but otherwise ISTM that most of the arguments being made for homebrew also apply to other OS's.

**Comment by skullydazed** [comment]
> Maybe I would suggest that `brew install qmk/qmk/qmk` installed the dependencies needed and NOT `qmk setup`

This actually does work in most cases, and my intent is that `qmk doctor` pass after running only that command. We try to steer users in that direction, but some users still end up with broken environments and in almost all of those cases a `brew update` fixes it.

**Comment by brorbw** [comment]
> This actually does work in most cases, and my intent is that qmk doctor pass after running only that command.

If this is the case I don't understand why `qmk setup` upgrades `brew`. A different fix would be that `qmk doctor` could fix errors encountered by users. The naming `setup` suggests something different that installing and upgrading dependencies imo

**Comment by fauxpark** [comment]
> Following the logic I don't understand why `pacman -Syu` isn't used in arch.sh?

To clarify this point, I simply missed that during my cleanup. All of the install scripts should be running their respective package managers first.

**Comment by brorbw** [comment]
> To clarify this point, I simply missed that during my cleanup. All of the install scripts should be running their respective package managers first.

That's a terrible idea especially if you insist on using `--nonconfirm`. Why are you so opposed to a prompt or a more narrow dependency update? 

Just updating people's systems is not okay!

**Comment by fauxpark** [comment]
If your system is set up properly, it's not an issue at all, and it spares us having to constantly answer the question of "why didn't QMK install properly?" - it's usually because your packages are ridiculously out of date.

Running your package manager and having something entirely unrelated break is *not* QMK's fault.

**Comment by brorbw** [comment]
@fauxpark I can't for the life of me figure out why I would need a newer version of emacs to use qmk?

**Comment by fauxpark** [comment]
You don't. Emacs, and the fact that it apparently breaks (you still have not said exactly how) when you run `brew upgrade` is not in any way QMK's problem. Please go and file an issue with Homebrew and/or Emacs.

**Comment by brorbw** [comment]
There is literally no reason to run a system wide upgrade of a system to install this package. qmk is already installed using brew (a package manager) why not use the functionality of said manager and declare dependencies. Furthermore its pretty bold to expect that qmk works with all future versions of all packages.

This behavior is either stupid or lazy and I'm hoping for the latter.

**Comment by brorbw** [comment]
> (you still have not said exactly how)

This comment suggest that you do not believe that an update actually breaks my system. So let me tell you how. 

I have no issue upgrading emacs if I do it manually, but it requires that I update dependencies with other package managers than brew, e.g emacs packages from melpa, pip and npm. Especially if you pin a melpa package you would need to update it. Which leaves my setup in a broken state until I go an fix it!

In the case of docker, there are some configuration for running docker on an AMD that are not installed with a brew. This means that I manually have to go fix the setup because the specs changed.

This would not have been a problem if I deliberately updated and installed because I would have set aside time to solve this. 

These are just a few examples of stuff that can break when upgrading - these are not issues with `brew`, `emacs` or `docker` these are problems that happend because of `brew upgrade` which `qmk` did.

**Comment by fauxpark** [comment]
You are correct, there is no real need to run the package manager. But it is highly recommended to do so before setting up QMK. It just makes troubleshooting easier. We could instead politely ask users to make sure they are up to date first, but in our experience they often ignore this advice, or do not even know what a package manager is! Which leads to complaints. So yes, it is easier to do the "lazy" thing and run it for them.

**Comment by brorbw** [comment]
> do not even know what a package manager is
The install script depends on `brew` which requires some knowledge of `brew` I guess. Maybe `upgrade` could be omitted completely and `qmk setup` would install the required deps like in all the other scripts!?

> So yes, it is easier to do the "lazy" thing and run it for them.
Why not also order a pizza for them while they wait using their credit card while you are at it? Remember when windows updated peoples computers to windows 10 without consent or knowledge I'm remember that people _really liked_ that feature.

**Comment by fauxpark** [comment]
You'd be surprised how many people are running Linux on the desktop now that do not have the slightest idea how it works under the hood. Keep in mind we have to support those users, too. Sure, maybe we could have a page in the docs to walk them through updating packages, but that seems a little out of scope, no?

> Remember when windows updated peoples computers to windows 10 without consent or knowledge. I remember that people really liked that feature.

Well, it's a good thing brew can't do anything of the sort... and as for Linux, updating to a new release is generally a separate command (eg. `sudo do-release-upgrade` for Ubuntu).

**Comment by tzarc** [comment]
> The install script depends on `brew` which requires some knowledge of `brew` I guess.

Unfortunately this is a bad guess. The vast majority of QMK's users are unaware of what `brew` actually does, given the bulk of support given out on Discord. In this case QMK's a victim of its own success -- the procedure is simple enough that non-power-users are capable of building and customising their own keyboards.

> Why not also order a pizza for them while they wait using their credit card while you are at it? Remember when windows updated peoples computers to windows 10 without consent or knowledge. I remember that people _really liked_ that feature.

What you're advocating for is the 1% of users who understand the entire problem space, and want things "just so". The other 99% of users are unaffected, and to be quite honest, willingly oblivious of what `qmk setup` of does. QMK's collaborators have limited time for fielding support issues, and running `brew upgrade` is the pragmatic solution.

**Comment by awkannan** [comment]
I understand the need to appeal to end users - but I don't think this is the right way. 
IMO this is really developer unfriendly. It's certainly an edge case, but it could absolutely ruin's someone's day - and I think any project wants to avoid that.

If I were trying to contribute to a project, and it ran a  `brew upgrade` without my knowledge from a setup script, I'd be turned off from contributing. And I'd probably raise a github issue as well. If we can do better, we should, especially if it's not that hard to prevent.

I think a confirmation is way more friendly, and I don't understand why there is so much push back to it. It's very easy for a layman to just hit "yes", and if they aren't sure about what that means or entails, then maybe they can go read a bit more about brew and find out.

If we're worried about CI not being able to run `brew upgrade`, adding flags to the QMK install scripts to auto confirm is a possibility. The default behavior remains developer friendly, and there are ways to enable other use cases.

I can see why @brorbw is upset, and I definitely throw my support behind changing this default behavior.

**Comment by brorbw** [comment]
> many people are running Linux on the desktop now that do not have the slightest idea how it works under the hood.

Honestly most people using linux, myself included can't understand every part of linux it, but a minimum is a package manager or RTFM IMO.

> Sure, maybe we could have a page in the docs to walk them through updating packages, but that seems a little out of scope, no?

You don't think upgrading every package on a system is a little out of scope for a `qmk`?

> Well, it's a good thing brew can't do anything of the sort... and as for Linux, updating to a new release is generally a separate command (eg. sudo do-release-upgrade for Ubuntu).

That is not the case for rolling release systems like arch.

> Unfortunately this is a bad guess. The vast majority of QMK's users are unaware of what brew actually does, given the bulk of support given out on Discord.

Well they have it installed is what I meant - that could be used as an advantage, like using the dependency system of brew.

> What you're advocating for is the 1% of users who understand the entire problem space, and want things "just so". The other 99% of users are unaffected

I would say that's a BS statistic. 

> running brew upgrade is the pragmatic solution.

How is it pragmatic IMO it's lazy development. You could easily mitigate the issue, but there is an unwillingness towards solving this issue.

 ________________
 
 I'm not annoyed by the fact that this issue arose - I'm upset about the resistance towards making qmk a better experience for _super users_ and non super users. 
 
 If people want to flash a keyboard it can easily be done with the online configurator and `qmk` Toolbox. If you have installed this repo you are already in the realm of writing custom firmware and for that scope I would expect people to _AT LEAST_ know how to use a package manager.
 
 I'm all for a better solution than the one proposed in this PR and I'm willing to write another one we just have to agree which is better. Status quo is not a solution IMO - a better solution would be to remove `brew upgrade` from `setup` and declare deps in the recipe - that's literally what package managers are for yet somehow someone reinvented the spoon.

**Comment by brorbw** [comment]
> Comments like this make it harder to take your arguments seriously. Please refrain from personal attacks.

My apologies - I merely meant it as a comment on the install/update strategy and not as a personal attack. I didn't specify that, and to anyone that took offense I'm sorry.

> I understand your frustration but statements like this are confrontational, and that's the tone you've taken from the start. I think it's obscured for you that I'm more on your side than you think.

I think you are right - I had a hard time trying to solve the issue or/and formulate a proper solution to the issue but it felt like running my head against the wall.

I know there isn't a one-size-fits-all in this regard and its very hard to accomplish both usability for non-tech people and more control for people who want that. To paraphrase I fully acknowledge the hard problem that qmk is trying to solve. That said I still don't believe that upgrading all packages on the users system is the proper solution - it might just be an easy one.

> Since homebrew does a brew update when running any other brew command for the first time in a while the version of programs it installs will be the latest available- which may or may not be compatible with the current version of other programs already installed on the user's system. In an ideal world the dependency tree would notice this and update everything required but we don't live in an ideal world, and compiler toolchains can be fickle.

I get that, and if the idea is that you can run `qmk doctor` without errors after `brew install qmk/qmk/qmk` that would mean that everything is setup properly. However the guide states that you need to run `qmk setup` after `brew install`. My expectation was that this would setup either default layout or set some compiler flags or some other form of setup but not that it would upgrade my packages. 

Maybe a rewrite of the install process where you install using `brew` then run `qmk doctor` to verify your install and _IF_ that fails, you can run `qmk setup`. That could maybe even be renamed from `qmk setup` -> `qmk doctor fix`

> Updating your software is important. Really important.

I couldn't agree more

> I would not expect setting up QMK to upgrade all my packages, but as long as it's upfront about what it's doing and gives me a way to cancel I think that's ok. If I don't want to take the risk at that moment I won't.

Hit the nail on the head right there

**Comment by drashna** [comment]
Short term, until we can get a good solution in place...

Would it be worth noting this issue in the documentation, with instructions on how to manually install on/with brew?  And once there is the better solution, remove the text?

**Comment by brorbw** [comment]
@drashna that sounds like a good solution right now

**Comment by brorbw** [comment]
@drashna what was the resolution on this issue/PR. Did the change to documentation happen?

**Comment by drashna** [comment]
I wasn't sure, this stuff is a bit outside of what I do, usually.  

However, I've added "awaiting review" tag, so that it won't get closed, at least.

**Comment by brorbw** [comment]
After some digging I have figured why `brew upgrade` leaves my system in an unusable state and I would like you to reconsider your decision on this matter. Full disclose I use an AMD hackintosh and I _have_ to use docker-machine to build a VM using virtualbox to run docker because there is no support for the AMD version Hyper-V on macOS. I know this is an edge case but hear me out. 

Running `brew upgrade` upgrades both formulaes and casks. Because casks have been migrated into `brew` there is no option to update only formulaes thus I can't opt out. To further make this troublesome `brew` offers no option to pin a cask therefore pinning a package is not an option. This leaves me with a broken system because `brew upgrade` starts to remove the old virtualbox but fails half way through because its running rendering my virtualbox setup unusable. Yes, this can be considered an upstream issue but since there is no real reason to run `brew upgrade`. I would either suggest that the formulae that installs `qmk` _actually_ installs dependencies and that the expected version of said dependencies are pinned in the formulae. This install script should not have anything to do with updating or upgrading brew.
I think that we should use package managers for what they are designed for i.e. managing packages and let the install script initialize the environment.

LMKWYT

**Comment by fauxpark** [comment]
> there is no option to update only formulaes

Does `brew upgrade --formula` not work?

https://docs.brew.sh/Manpage
> `--formula`: Treat all named arguments as formulae. If no named arguments are specified, upgrade only outdated formulae.

That could be a viable solution to this issue.

**Comment by brorbw** [comment]
> Does brew upgrade --formula not work?

I stand corrected. 

> That could be a viable solution to this issue.

I agree. I'm still not a fan of the current solution because of it's misuse of package managers. That said this seems to be the solution with the least implementation.

**Review by drashna — APPROVED** [review]

**Review by skullydazed — APPROVED** [review]

**Comment by chrismanderson** [comment]
What does this PR actually do? Installing `qmk` for the first time broke my developer environment, and it was only after hours of debugging did I realize the cause was that that `qmk` ran a full `brew upgrade`. I found this PR and see that the `--formulae` tag was added to the `brew upgrade` command, but that tag doesn't do anything if not passed in a list of formulas and I don't see a list anywhere in that file.

I know first hand it's a really tough task balancing user finding solutions that makes all users and maintainers/developers happy, but forcibly triggering a `brew upgrade` is really not it. Installing `qmk` and the forced `brew upgrade` broke my development environment, and I have been spending hours trying to undo the damage it caused. I will likely need to restore from a backup - which, is an extreme result from installing keyboard firmware!

In an ideal world, every user would always be able to run `brew upgrade` or really, `upgrade` for any package manager without any repercussions, but any one who has spent even the smallest amount of time developing software learns quickly that, unfortunately, that's not how things operate. It's just turtles all the way down - packages can have strict version requirements, version requirements can be dictated by developer environments, hardware limitations, production limitations, OS limitations, heck, even legal limitations.

Any installation process that requires multiple packages to function should have minimum versions defined for those packages, and prompt the user to upgrade those packages only - and only after user confirmation. It seems like you all went down that path previously in some fashion, but I would encourage you all to try again.

Aside from being more prescriptive around versions in the setup process, at the bare minimum, there absolutely must be either 

1. A confirmation prompt for running `brew upgrade` during setup. I know there was debate in this PR discussion, but that's really not a debatable issue - when triggering a potential mass update to a system, _it needs to be opt-in_, full stop.
2. At a bare minimum, a warning in `brew info qmk` or at the start of setup saying `brew upgrade` will be run, allowing the user to bail out if needed. 

Installing any sort of developer toolchain always has risk to an existing system, but because this was installed via homebrew, I was expecting any risks to be mitigated by the fact that I could just use homebrew to remove it (as I've done many times in the past for 'bad' packages). I was excited to download and start using `qmk` for the first time and I'm disappointed in how that has gone so far.

**Comment by brorbw** [comment]
> I found this PR and see that the --formulae tag was added to the brew upgrade command, but that tag doesn't do anything if not passed in a list of formulas and I don't see a list anywhere in that file.

From `man brew`
> `--formula` Treat all named arguments as formulae. If no named arguments are specified, upgrade only outdated formulae.

We have had the exact same experience, and this PR was originally very different. I still have the old one. It made a dry run on upgrade and printed a list to the user and prompted the user if he/she wanted to continue. There was a _strong_ opposition to the original PR from `qmk` as you might be able to tell from the comments. I still don't agree with this behaviour and the misuse of a packagemanager.

**Comment by fauxpark** [comment]
Unfortunately there is a typo (`--formulae` instead of `--formula`) and this PR as is has no effect.

**Comment by brorbw** [comment]
> Unfortunately there is a typo (`--formulae` instead of `--formula`) and this PR as is has no effect.

Dammit you are right. I'll fix it

**Comment by chrismanderson** [comment]
> > Unfortunately there is a typo (`--formulae` instead of `--formula`) and this PR as is has no effect.
> 
> Dammit you are right. I'll fix it

That's not the issue. If you look at the `man` page for `brew upgrade`, you can see that they are aliases of each other.

```
❯ brew upgrade -h
Usage: brew upgrade [options] [outdated_formula|outdated_cask ...]

Upgrade outdated casks and outdated, unpinned formulae using the same options
they were originally installed with, plus any appended brew formula options. If
cask or formula are specified, upgrade only the given cask or formula
kegs (unless they are pinned; see pin, unpin).

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will then be run for
the upgraded formulae or, every 30 days, for all formulae.

  ....
      --formula, --formulae        Treat all named arguments as formulae. If
                                   no named arguments are specified, upgrade
                                   only outdated formulae.
   ...

```

The issue is that there aren't any arguments passed to the list, so brew still tries to upgrade all outdated packages. I think the intention of this PR was instead of pass in the list of only formula used by QMK, and ignore anything else.

**Comment by brorbw** [comment]
> I think the intention of this PR was instead of pass in the list of only formula used by QMK, and ignore anything else.

No, the original intention of this PR was a solution based on prompting the user to take action but that was shot down. To solve my issue with not upgrading virtual box when I have running VMs this solution was drafted.

**Pull request merged**
