### PR TITLE
Updated ChibiOS-Contrib.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

Updated ChibiOS-Contrib to pick up RP2040 USB support. Ping @hanya for confirmation.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
(Probably going to want a "convert to PR2040" option sometime after this)

**Review by jackhumbert — APPROVED** [review]

**Comment by tzarc** [comment]
For the SparkFun RP2040 ProMicro board? Yeah. On my radar. Got 4 of them handy already.
We'll need a ChibiOS upgrade first, anyway. Unsure we want the 21.6.x ChibiOS with the 20.3.x ChibiOS-Contrib, though.

**Comment by fauxpark** [comment]
This also unblocks #14420, but I guess that's not as fun as the 2040 :P

**Review by fauxpark — APPROVED** [review]

**Comment by hanya** [comment]
Current chibios @ 413e39c does not contain any RP2040 related changes yet.
So we have to update ChibiOS at the same time with the contrib.

I noticed recent ChibiOS migrated ChibiOS/os/common/ports/ARMCMx/* files into own directories.
The PORT_V in chibios.mk have to be updated to match to new directories.

**Comment by hanya** [comment]
I found a bug in the usb driver for RP2040 in the contrib and made PR.

**Comment by KarlK90** [comment]
Updated my RISC-V port for 21.6 as well in https://github.com/ChibiOS/ChibiOS-Contrib/pull/302

**Comment by tzarc** [comment]
Cancelling this for now. Will sort out the upgrade to 21.6.x with the existing in-flight PR for that upgrade.

**Comment by tzarc** [comment]
#14208.

**Pull request closed without merging**
