### PR TITLE
Add tsangan layout and keymap to zeal60 PCB

### PR DESCRIPTION
**Pull request by cdarwin**
This changeset adds a tsangan layout to the zeal60 PCB for the web configurator as well as an equivalent macro for building keymaps for the PCB. Additionally, this adds a default keymap for this layout based on the existing ANSI default. 

Again, I am hoping to provide a sensible default keymap for the provided layout based on what was already here. Oddly, function layer two here appears to be totally transparent… `¯\_(ツ)_/¯ `

It is notable that I don't yet have a zeal60 to test this firmware on. I am ok holding on this until I can test it myself in a couple of days. At that point, I should have another PR to save a keymap for this board based on my own preferences :)

### CODE REVIEW

**Comment by cdarwin** [comment]
Tagging @Wilba6582 because I was seeing some [build failures](https://travis-ci.org/qmk/qmk_firmware/builds/472014965) when I first started working on this similar to what I think you were seeing in #3879

I have removed the offending community layout from the zeal60 make rules as a temporary fix, but I'm sure some others have a better long term suggestion.

Tagging @unxmaal and @skullydazed in case they have some context.

**Comment by mechmerlin** [comment]
is there such a thing as a ANSI or ISO Tsangan?

**Comment by cdarwin** [comment]
I don't see why not? I can't seem to fine a definitive source but my understanding is that `tsangan` as a layout reference is mostly indicator of the bottom row (1.5, 1, 1.5, 7, 1.5, 1, 1.5). I have always seen this paired with a split right space, but I can't say exactly how conventional this is. While I have seen this paired with a split backspace I haven't yet seen it paired with ISO Enter. But there is nothing stopping someone from choosing to do so. I have no problem adding ansi to the name of the layout I have added here.

**Comment by cdarwin** [comment]
@Wilba6582 sure, that's fine with me. I can nuke the dedicated layout in this changeset no problem. I would say that the more pressing issue is the build failures mentioned previously.

**Comment by cdarwin** [comment]
Closing this in favor of #4732

**Pull request closed without merging**
