### PR TITLE
Give a hint to adjust F_CPU in the rules.mk template

### PR DESCRIPTION
**Pull request by steelman**
## Description

By default F_CPU is set to 16000000 which makes all timings (especially USB and UART) twice too slow on 3.3 V/8 MHz Pro Micro boards. As hard as they try hosts are unable to establish communication with such boards and messages like below can be found in the Linux kernel log.

Such hint in the rules.mk may spare novice QMK hackers a day or two of debugging and keep them interested in the project.

```
[2459329.123362] usb 1-1: USB disconnect, device number 125
[2459329.429298] usb 1-1: new full-speed USB device number 126 using xhci_hcd
[2459329.557275] usb 1-1: device descriptor read/64, error -71
[2459329.793224] usb 1-1: device descriptor read/64, error -71
[2459330.029221] usb 1-1: new full-speed USB device number 127 using xhci_hcd
[2459330.161235] usb 1-1: device descriptor read/64, error -71
[2459330.397242] usb 1-1: device descriptor read/64, error -71
[2459330.505304] usb usb1-port1: attempt power cycle
[2459330.917187] usb 1-1: new full-speed USB device number 2 using xhci_hcd
[2459330.917336] usb 1-1: Device not responding to setup address.
[2459331.125341] usb 1-1: Device not responding to setup address.
[2459331.333195] usb 1-1: device not accepting address 2, error -71
[2459331.461230] usb 1-1: new full-speed USB device number 3 using xhci_hcd
[2459331.461394] usb 1-1: Device not responding to setup address.
[2459331.669333] usb 1-1: Device not responding to setup address.
[2459331.877162] usb 1-1: device not accepting address 3, error -71
[2459331.877209] usb usb1-port1: unable to enumerate USB device
```

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Devices with different `F_CPU` values aren't really common enough to warrant this. It used to be in the template, along with a few other options that in practice almost never needed changing, so they were moved to `mcu_selection.mk`.

Instead, `F_CPU` is already documented here: https://docs.qmk.fm/#/hardware_avr?id=mcu-options

**Comment by steelman** [comment]
I may agree 3.3 V boards are less common, I wouldn't say they are rare. For example I bought mine together with some other 3.3 V peripherals (senors) because I didn't want to play with level conversion. Today, I took a board from a drawer and tried to build a simple key pad and flash it with QMK. It didn't work until I tried using the hardware uart driver and found out that while I was setting baud rate to 9600 I had to set my terminal to 4800. I looked at uart_init() and everything became obvious.

You are probably right, rules.mk isn't the best place for such comment. On the other hand there is little no information **why** would anyone would change `F_CPU`. I mean, I knew I've got 3.3 V/8 MHz device, but I (and probably many novice users) wasn't aware I need to adjust `F_CPU`. It just wasn't obvious.

> Instead, `F_CPU` is already documented here: https://docs.qmk.fm/#/hardware_avr?id=mcu-options
 
I read this, but `F_CPU` is just mentioned there rather than documented. Do you think this is a good place to put a note that this setting is crucial for non 16 MHz devices?

**Comment by steelman** [comment]
The document says

> Be very careful if you change any of these settings, you can render your keyboard inoperable.

Such warning makes perfect sens in case one is trying to rebuild firmware for existing hardware. In my case I am building new keyboard and there is no information why and how to adjust each value.

OK, it's quite late. I'll think about it tomorrow.

**Comment by fauxpark** [comment]
Yes, the point I was trying to make is, this is a documentation problem, not a template problem. Just throwing every possible option in there is not a viable solution IMO. Note that `F_CPU` is only relevant for the AVR platform, and although this file is under the `avr` directory, technically this template is used to create keyboard folders which do *not* use AVR MCUs - eventually there will likely be a single unified template for any keyboard, but that's a ways off.

**Comment by zvecr** [comment]
Thank you for your contribution!

This pull request has been automatically closed because it has not had activity in the last 30 days.
Please feel free to give a status update now, ping for review, or re-open when it's ready.

**Pull request closed without merging**
