### PR TITLE
Fix timer_elapsed() overflow issue for STM32F103 and other ChibiOS boards

### PR DESCRIPTION
**Pull request by dworki**
## Description

Space Cadet does not work on STM32F103 (BluePill). Specifically it works a couple of times, then it stops. There may be a deeper problem in timeout computation that I'm not able to fix (being a Java programmer). Basically after a couple of any key presses the timer_elapsed() starts returning large increments (the overflow variable in chibios/timer.c) gets stuck at 65535.

Adding TIMER_DIFF_16() to the comparison in perform_space_cadet() fixed the problem. I'm aware that it is probably not the "right" solution but it works for this case.

It is a simple change but I'm a little worried that I was not able to test the fix on any other architecture.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
The ATSAM and AVR timer.c's both use `TIMER_DIFF_16()` in `timer_elapsed()`. ChibiOS is the odd one out here just doing a simple subtraction.

**Comment by dworki** [comment]
Makes sense! I didn't occur to me to look at other implementations. I'll move the TIMER_DIFF_16() from process_space_cadet() to elapsed() in timer.c
I'm quite new to github, should i open new PR or somehow amend this one?

**Comment by fauxpark** [comment]
Just commit and push to the same branch, and it will show up here :)

**Comment by drashna** [comment]
Been testing on my planck rev6, and on my collide 39 with a proto-proton C, and seems to not cause any issues

**Pull request merged**
