### PR TITLE
Merc updates

### PR DESCRIPTION
**Pull request by kylemccreery**
## Description

New changes to firmware inclusions made it slightly too bulky for this already tight firmware. Changing it to omit mousekeys by default for this keymap to prevent compilation size errors.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Just a heads up, enabling LTO may be a better option than disabling mousekeys.

**Comment by kylemccreery** [comment]
@drashna That's probably fair feedback. I had a reason not to use that option and now I don't quite remember what that was. I do remember that it broke another option that I was trying to utilize, though it might not have been directly in this firmware. 

I don't like doing something just because of a vague memory so I will test the LTO out tonight and make an update if it is working as intended.

**Comment by drashna** [comment]
Also does break action macros and action functions, but these are deprecated anyways, and should be replaced with the process_record_user type stuff anyways.

**Review by fauxpark — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Comment by kylemccreery** [comment]
@drashna I can't find what it was breaking from the firmware that I was playing with, but I am still uneasy. I'm just going to let this one go through and push another one after I dig into it a little more. The Mercutio GB fulfillment orders will be delivered soon and I'd rather just have this small thing working as is and fix it once there is one on the books that works.

**Review by Erovia — APPROVED** [review]

**Pull request merged**
