### PR TITLE
Fix speed issues with RGB Matrix in the DZ60RGB 

### PR DESCRIPTION
**Pull request by moyi4681**
@drashna, thanks a lot:)

### CODE REVIEW

**Comment by Nicell** [comment]
This update has made my DZ60RGB's RGB speed EXTREMELY fast. Is this intended?

**Comment by drashna** [comment]
That depends on what you mean.  But it is meant to fix some of the issues with performance/speed on the board. 

If that's an issue for you, you can add the following to your keymap's `config.h` file:
```c 
#undef RGB_MATRIX_SKIP_FRAMES
```

**Comment by Nicell** [comment]
I mean the RGB animations are extremely fast and look janky (they cycle much much faster - almost annoyingly so). They seemed to look fine before. I wasn't aware of performance issues... Is there anyway to retain the not crazy fast animations and performance, or is this a trade-off?

**Comment by drashna** [comment]
yeah, a number of people have had serious performance issues with their boards. This change helped with it. 

The undef above should revert the change basically

**Comment by moyi4681** [comment]
check this, it will be solved soon I think。
https://github.com/qmk/qmk_firmware/pull/5372

**Comment by moyi4681** [comment]
@Nicell sent u a new firmware, pls check ur email

**Comment by Nicell** [comment]
Thank you. I will give it a try later. New pull request looks promising! Appreciate the responsiveness :)

**Pull request merged**
