### PR TITLE
Add Pendulum layout

### PR DESCRIPTION
**Pull request by hinnebusch**
Layout for Pendulum 30% keyboard.

Front text on layout picture indicates a "hold" command. I.E. Tap period for period, hold period for Ctrl.

### CODE REVIEW

**Comment by jackhumbert** [comment]
It looks like you're missing your `pendulum.c` file (and .h). Does this keyboard have a PCB that's for sale/available? If not, we have a `handwired/` folder for handwired projects :)

**Comment by hinnebusch** [comment]
Sorry, there is! I don't know the source, since I bought it from a dude on the /r/mk discord. I'll find that and get back to you.

**Comment by Dbroqua** [comment]
Hello,

I think you need to:
- rename kb.c/h to pendulum.c/h 
- in pendulum.h replace KB_H to PENDULUM_H
- in keymaps/hineybush/keymap.c replace kh.h to pendulum.h

Regards,
Damien

**Comment by jackhumbert** [comment]
Hey @hinnebusch, I'm gonna close this for now - when you have a chance to make those changes, feel free to open this back up/make a comment, and we'll get it merged :)

**Pull request closed without merging**
