### PR TITLE
Add deterministic audio clicky feature

### PR DESCRIPTION
**Pull request by Corallus-Caninus**
adds the ability for assigning audio clicky beeps to map to keycodes.

## Description

allows users to have deterministic (non-random) clicky sounds assigned per keycode. This is meant to help people learn touch typing and recognize errors and word-sounds for speed typing.
## Types of Changes
additions in docs and process_keycodes.

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR
n/a
* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checnt) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
It feels like there may be some overlap here with the music mode feature.  Though, different implementations to get similar results.

**Comment by drashna** [comment]
Also, while it says everything compiles correctly, the zima calls `clicky_play` from the encoder function and breaks with this change.

**Comment by drashna** [comment]
> Alright let me take another look at this. It's working as my daily driver dactyl_manuform. I'll rebuild and test. Is there any debug info for zima?

https://github.com/qmk/qmk_firmware/blob/42c6920e23d8dace7652155d04310cae60f12e42/keyboards/splitkb/zima/zima.c#L107

Also, my community layout for ortho_4x12 references clicky_play(), as well.  Those would both need to be change.

> Music mode states that it blocks key code signals in favour of just playing audio. I haven't tried music mode so am unaware if there's a way to configure it to match this feature. This and that are otherwise only a few changes away from being consolidated into one feature but it seemed to fit with the clicky key mode given the existing random clicky feature.

By default, it does block the normal keypress, but that can be disabled.
https://docs.qmk.fm/#/feature_audio?id=music-mask

**Comment by Corallus-Caninus** [comment]
Does music mode only produce notes for keycodes below a certain number? Part of this implementation allows for all keycodes to be assigned a beep code that repeats given the shifted bits but are otherwise distributed by the parameters. This helps me when I get lost in layers and needs to produce a sound for all keycodes.

**Comment by drashna** [comment]
> Thanks for the link. Does music mode only produce notes for keycodes below a certain number? Part of this implementation allows for all keycodes to be assigned a beep code that repeats given the shifted bits but are otherwise distributed by the parameters. This helps me when I get lost in layers and needs to produce a sound for all keycodes.

by default, yes, only for a certain set.  However, that can be altered by setting the music mask config:
https://docs.qmk.fm/#/feature_audio?id=music-mask

**Pull request closed without merging**
