### PR TITLE
Handwired tbkmini

### PR DESCRIPTION
**Pull request by cfarvidson**
## Description

This is a handwired version of the original firmware located in `keyboards/bastardkb/tbkmini`.

The main difference from the original firmware are diode direction (this is wired like a dactyl manuform).

Example builds using this firmware:

- <https://carl-fredrik.arvidson.io/posts/tbk-mini>
- <https://carl-fredrik.arvidson.io/posts/another-tbk-mini>

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
If you don't mind me asking, why a different folder for the keyboard? 
You could undef and redefine the hardware configuration in a keymap.

**Comment by cfarvidson** [comment]
> If you don't mind me asking, why a different folder for the keyboard?
> You could undef and redefine the hardware configuration in a keymap.

🤔 I never thought about that to be honest.

Would you prefer that I override `config.h` and `tbkmini.h` in a keymap folder in the original tbkmini firmware instead?

**Comment by drashna** [comment]
It's what I would do, yeah. :)

**Comment by cfarvidson** [comment]
Thank you. I’ll create new PR.

**Pull request closed without merging**
