### PR TITLE
Unify Tap Hold functions and documentation

### PR DESCRIPTION
**Pull request by drashna**
Updates all of the per key functions, and the documentation to go with them. 

Specifically, this means that the keyrecord_t structure has been added to the function call for `get_tapping_term`, mostly. 

Additionally, this moves all of the references in the documentation to the tap_hold.md doc, for easy access. 

This does update a number of user keymaps, and significantly changes a function parameter in core code, so marked as a breaking change. 

## Types of Changes

- [x] Core
- [x] Enhancement/optimization
- [x] Documentation

## Checklist
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
`docs/ChangeLog/20200530/PR8348.md` needs user instructions for fixing broken keymaps/code IMO.

**Comment by drashna** [comment]
> `docs/ChangeLog/20200530/PR8348.md` needs user instructions for fixing broken keymaps/code IMO.

Sounds good to me. 

Something like?
```
Any keymaps that have not been updated (such as those not in the repo), or that are otherwise erroring out on these functions need to be updated to appear like this:
 
bool get_tapping_term(uint16_t keycode, keyrecord_t *record)
bool get_permissive_hold(uint16_t keycode, keyrecord_t *record)
bool get_ignore_mod_tap_interrupt(uint16_t keycode, keyrecord_t *record)
bool get_tapping_force_hold(uint16_t keycode, keyrecord_t *record)
```

**Comment by noroadsleft** [comment]
> Something like?
> 
> ```
> Any keymaps that have not been updated (such as those not in the repo), or that are otherwise erroring out on these functions need to be updated to appear like this:
>  
> uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record)
> bool get_permissive_hold(uint16_t keycode, keyrecord_t *record)
> bool get_ignore_mod_tap_interrupt(uint16_t keycode, keyrecord_t *record)
> bool get_tapping_force_hold(uint16_t keycode, keyrecord_t *record)
> ```

That looks okay to me, but IMO a table that shows both the old and the new syntax would be better.

**Comment by drashna** [comment]
Added. And double checked, only `get_tapping_term` and `get_permissive_hold` need to be updated.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
