### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by iTechsTR**
Fixed a typo.

### CODE REVIEW

**Comment by iTechsTR** [comment]
> Wouldn't the phrase "there are more methods available" be more correct?

Great idea, I am rephrasing the sentence.

**Comment by noroadsleft** [comment]
@iTechsTR, since you're touching the file already, do you mind making a couple more changes? I was proof-reading your changes and found some other issues with the original file.

Line 9 should read:

```
You will need to configure the pins used by your display, and its number of lines and columns in your keyboard's `config.h`.
```

Line 43:

```
To initialize your display, call `lcd_init()` with one of these parameters:
```

Just those couple of things would be a good improvement to this page. Thanks!

**Comment by iTechsTR** [comment]
> Just those couple of things would be a good improvement to this page. Thanks!

Done, you can merge now.

**Comment by noroadsleft** [comment]
Thank you!

**Pull request merged**
