### PR TITLE
Fix playback of long songs

### PR DESCRIPTION
**Pull request by inve1**
## Description
The `play_notes` function takes a `uint16` as the parameter for the length of the song, but the loop playing it uses a `uint8` as a counter, which will overflow on songs longer than 256 notes and loop even when `n_repeat` is `false` (and only play the first 256 notes of the song)

If anyone needs a long song to test this with (I've done this on my preonic rev3) this monstrosity exists https://github.com/inve1/qmk_firmware/blob/mrco/quantum/audio/song_list.h#L507

Anyway.. thanks for the cool firmware

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by inve1** [comment]
are you saying you want me to clean the song up and submit it? :stuck_out_tongue:

**Comment by skullydazed** [comment]
Yes, I'd love to have this song in qmk. :)

**Comment by drashna** [comment]
I concur. :)

**Comment by drashna** [comment]
Well, for now, I think we can merge this.

**Pull request merged**
