### PR TITLE
whale/sk/v3: Configurator fix

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

Fixes the Configurator key assignments and updates the code style for `info.json` files, basically.

*Before screenshot:*
image

cc @ncwhale (keyboard maintainer)

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Comment by ncwhale** [comment]
THX!

**Comment by ncwhale** [comment]
There is one small problem:

Fn & Space Keys are not in the right order, These two big key are space, and F1~F6 / F7~F12 are split in left & right like this:

Splite Keyboard v3 designed layout

**Comment by noroadsleft** [comment]
@ncwhale,

That issue is the reason for this PR. Without this PR, you have to assign the keys as in [the original comment](https://github.com/qmk/qmk_firmware/pull/11490#issue-552188917) to get the correct assignment. With this change, you get:

image

**Pull request merged**
