### PR TITLE
Switching rgb_config_t to use the HSV struct

### PR DESCRIPTION
**Pull request by XScorpion2**
## Description

This update saves another ~190 bytes with LTO enabled.  In addition this was planned with the multiple effects pr in mind making the rebase / transition of that pr easier. 

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Merge conflicts.

**Comment by XScorpion2** [comment]
@drashna not anymore sir

**Comment by XScorpion2** [comment]
CI failure unrelated to my changes. DEBOUNCE strikes once more!

**Comment by XScorpion2** [comment]
Rebased on latest master

**Comment by drashna** [comment]
This has some merge conflicts now

**Comment by XScorpion2** [comment]
rebased on latest master

**Pull request merged**
