### PR TITLE
[Schema] Fix mapping audio pins in data-driven configuration

### PR DESCRIPTION
**Pull request by JunoNgx**
## Description

* In the old fashioned way using preprocessor directives with `config.h`, audio configuration is specified by `AUDIO_PIN <MCU_PIN>` and `AUDIO_PIN_ALT <MCU_PIN>` (fully optional, audio is fully operable with only `AUDIO_PIN`).
* However, in the data-driven configuration approached, the property `audio.pins` is declared as a `mcu_pin_array` in the schema.

I find this a data mismatch, and because of this, it is not possible to correctly configure and enable audio with the data-driven approach for the moment.

Let me know if there is a some abstraction that processes `audio.pins` into `AUDIO_PIN` and `AUDIO_PIN_ALT` I missed out, or if I'm doing this wrong somehow.

I've also checked, and there are very few boards that are currently using audio, and none of them actively uses the data-driven approach, so the amount of breaking here is likely to be small.

## Types of Changes

- [X] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by sigprof** [comment]
There is also this code in `lib/python/qmk/info.py`, which deals with related legacy AVR-only options:
```python
def _extract_audio(info_data, config_c):
    """Populate data about the audio configuration
    """
    audio_pins = []

    for pin in 'B5', 'B6', 'B7', 'C4', 'C5', 'C6':
        if config_c.get(f'{pin}_AUDIO'):
            audio_pins.append(pin)

    if audio_pins:
        info_data['audio'] = {'pins': audio_pins}
```
Looks like this code may just be removed, because the corresponding driver code that handled those options was removed in commit c80e5f9f8868ccaa8cb990be6f4da3f1011c2b78 back in 2021.

As for the `info.json` ⇔ `config.h` mappings, custom mapping code may be added to `lib/python/qmk/cli/generate/config_h.py` and `lib/python/qmk/info.py`, so that the existing defines may still be used with the `audio.pins` array representation in JSON.

BTW, `qmk mass-compile -f 'exists(audio.pins)'` finds some boards, but all of them use the obsolete AVR-only options, and most even have the audio feature disabled (and those that have audio enabled end up having a noop implementation of the `audio_pwm_hardware` driver, because `AUDIO_PIN` is not actually configured):
```
Build delikeeb/vanana/rev1:default                                     [OK]
Build delikeeb/vanana/rev2:default                                     [OK]
Build latincompass/latin6rgb:default                                   [OK]
Build merge/um70:default                                               [OK]
Build nightly_boards/n60_s:default                                     [OK]
```

**Comment by JunoNgx** [comment]
I see. Thanks for the interesting info.

What's the team's take on this then? Would you like me to try poking around at the python level? I guess I should wait for more input?

**Review by drashna — APPROVED** [review]

**Comment by tzarc** [comment]
> I see. Thanks for the interesting info.
> 
> What's the team's take on this then? Would you like me to try poking around at the python level? I guess I should wait for more input?

If you're comfortable it'd be great to go with the "full package" solution, i.e. removing the redundant python code and fixing up board definitions accordingly.

**Comment by JunoNgx** [comment]
Sorry for having taken a while, just got back from a vacation.

Can I have a more specific goal about what I should walk towards? The reason I brought up this PR is how I found the property `audio.pins` was inadequate and didn't do what I needed it to. What do you think should be the ideal output? 

I guess we are keeping `audio.pins` and let it handle both case of one single MCU pin and an array of MCU pins, while also cleaning up the boards that are using this property?

**Pull request closed without merging**
