### PR TITLE
added an ISO split spacebar layout 

### PR DESCRIPTION
**Pull request by mcarni**
modified existing dz60.h and info.json to include the required layout

added iso_split-spacebar folder with keymap and readme files

### CODE REVIEW

**Comment by drashna** [comment]
Unfortunately, there is a merge conflict here. 

You'll need to merge from upstream or rebase from upstream to fix this issue.

**Comment by noroadsleft** [comment]
The detailed instructions of what @drashna said:

## Step 1. Checking your remote repos

Open your Git CLI and run this:

``` sh
git remote -v
```

If you enter that and only get two lines that are both marked `origin`, enter the command below. If you get back two lines both marked `upstream` that point to QMK's fork, go right to Step 2.

``` sh
git remote add upstream https://github.com/qmk/qmk_firmware.git
```

## Step 2: Syncing your master branch

To sync your master branch, run the following commands, in order, one by one:

``` sh
git reset --hard e68c8f2ac6cb2db1192591059c91bc6757ccbe47
git fetch upstream
git pull --ff-only upstream master
```

This updates your master branch so it matches QMK's. At this point, your won't see your changes, but they're not gone; Git knows where they are.

## Step 3: Reapplying your changes

Now, you reapply your changes with the following command:

``` sh
git cherry-pick c4498fc6fa20626d918d30cd70c89627944995b0
```

This command takes a change that was made somewhere else, and applies it to where you currently are in the branch history.

At this point, you'll get an error, because of the merge conflict:

``` sh
error: could not apply c4498fc6f... added an ISO split spacebar layout (modified existing dz60.h and info.json, added iso_split-spacebar folder with keymap and readme)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
```

#### Fixing the merge conflict

Open `dz60.h` in your text editor. Find the line that says

```
<<<<<<< HEAD
```

This line marks the start of the merge conflict. There will be a line later that says

```
>>>>>>> c4498fc6f... added an ISO split spacebar layout (modified existing dz60.h and info.json, added iso_split-spacebar folder with keymap and readme)
```

That's the end. The two sides will be separated by

```
=======
```

Above the line of Equals signs is text from QMK's master branch. Below that line is the text from your commit.

Without deleting or changing the text from QMK's master branch, add the text that was in your original commit. You'll only need the `LAYOUT_60_iso_split` definition. (`LAYOUT_directional_625_space` was deprecated and removed.) Your definition should go between any of the other definitions.

Now, delete the lines with `<<<<<<< HEAD`, `=======`, and `c4498fc6f... added an ISO split spacebar layout ...`, and save the file.

Go back to your Git CLI, and run:

``` sh
git add dz60.h
git commit -m "[your commit message goes here, your can change it if you want]"
git push --force
```

This will overwrite the commit you see here with your fixed changes, and the merge conflict will be gone. GitHub will update this pull request automatically; you don't need to open a new one.

If you need any more help, just reply.

**Comment by drashna** [comment]
Also, GUI editors may help with dealing with merge conflicts.  I personally like VS Code.

**Comment by drashna** [comment]
Travis error is unrelated (due to a missing `#include "quantum.h"` in @TheOneTrueTrench's keymap.h file, that somehow Travis CI and Drashna CI missed)

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
