### PR TITLE
Nordic keymap fixes

### PR DESCRIPTION
**Pull request by oscarcarlsson**
The Nordic keymap was incorrectly labeling the umlaut/tilde/circ key as NO_QUOT (which is mapped to KC_BSLS) and not NO_UMLT (or what have you). I have corrected this, introduced a new keycode NO_UMLT (as in umlaut) and updated depending keycodes in the Nordic layout to reflect this. 

I have also removed a few redudant keycodes in the Swedish and Norwegian layouts and cleaned up some whitespace. Sorry for the last bit but I couldn't stand it.

Any other Nordic users are more than welcome to have a look at the changes. The only breaking issue is that I removed the redundant definition of NO_AA in the Swedish layout as it already existed as NO_AM.

### CODE REVIEW

**Comment by oscarcarlsson** [comment]
Oh I have found this issue as well: https://github.com/qmk/qmk_firmware/issues/513

In case someone from that issue can have a look at this? And also @jackhumbert in case he would like to approve this PR :)

**Comment by jackhumbert** [comment]
Nice - this looks good to me, but I'm curious what @fredizzimo thinks, being more familiar with these languages :)

**Comment by oscarcarlsson** [comment]
Yes, it would be very good if anyone else could have a look at it. :)

**Comment by oscarcarlsson** [comment]
@fredizzimo any updates here? :)

**Comment by tru** [comment]
As a fellow Swede I think I can ack this change. Much needed small cleanup. I am also interested in harmonizing the `KC_` and `NO_` macros since some of them doesn't seem to line up. Like `KC_LT` vs `NO_LESS`.

**Comment by fredizzimo** [comment]
@oscarcarlsson, sorry for the delayed response, I had a huge backlog of QMK issues to go through, so I haven't noticed this.

This changes look ok, but I would prefer my own version, which is more complete https://github.com/fredizzimo/qmk_firmware/blob/fredizzimo_keymap/quantum/keymap_extras/keymap_sv_fi.h. It uses the `sv`prefix, and is based on the normal `KC_` keycodes rather than the imaginary nordic layout (which is close to the Danish layout). It's the full Swedish/Finnish layout with Sami characters. The naming is also consistent with the `KC_` keycodes wherever applicable. 

I can make a pull request for that one tomorrow, along with at least a Norwegian and Danish version. The biggest problem is that it would break some keymaps, unless I use a different names, and leave the original ones intact.

**Comment by drashna** [comment]
There are a number of merge conflict here, and I think that some of this stuff has already been fixed.

Is it okay if we close this?

**Comment by oscarcarlsson** [comment]
Yes, please close this.

**Pull request closed without merging**
