### PR TITLE
Add support for STM32L072 and STM32L073 variants

### PR DESCRIPTION
**Pull request by elagil**
## Description

This adds support for the STM32L072 and STM32L073 chips in various memory configurations.

**Note**: I added granular support for each memory variant, which requires the user to specify their particular variant. For example, simply setting `STM32L072` as the `MCU` will throw an error message, asking to specify the type. Valid types are 

- STM32L072x8 or STM32L073x8
- STM32L072xB or STM32L073xB 
- STM32L072xZ or STM32L073xZ

and are also presented to the user when linking fails.

STM32L072 and STM32L073 chipsets with the same final letter share the same memory layout. Thus, there only exist linker files for STM32L073 chips that shall be used for both.

Finally, the STM32L07x only has 16 bit timers, meaning that the `SYSTICK` timer is set up to be only 16 bit long.

I did not test the changes with hardware yet, but I will soon. Compilation and linking works as expected.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation. In the web document that specifies supported MCUs?
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by KarlK90 — CHANGES_REQUESTED** [review]
Great! 

Please add the supported MCUs to https://github.com/qmk/qmk_firmware/blob/master/docs/compatible_microcontrollers.md and add a onekey keyboard under `keyboards/handwired/onekey` for testing purposes.

**Comment by elagil** [comment]
@KarlK90 I will!

**Comment by KarlK90** [comment]
I'm not familiar with the FLASH peripheral on these chips but if they are close to the F042 ones emulated EEPROM support could be added fairly easy under the `eeprom_stm32*` files.

**Comment by sigprof** [comment]
These chips have real EEPROM, therefore the support for emulated EEPROM is not required.

**Comment by KarlK90** [comment]
> These chips have real EEPROM, therefore the support for emulated EEPROM is not required.

Even better, thanks!

**Comment by KarlK90** [comment]
@elagil you accidentally added ugfx as a submodule under `lib/ugfx`

**Comment by elagil** [comment]
@KarlK90 Looks like it, I updated my fork from a very old state...

**Comment by elagil** [comment]
CI is now clean!

What about the other processors: should we add available memory configuration options for other chips as well? Currently, the default configuration will either

- match the chip (this is good, of course)
- lead to firmware that doesn't fit into the flash memory of a smaller chip
- "waste" space on a larger chip, although most firmwares will not exceed the flash size of smaller chips

**Comment by zvecr** [comment]
> I added granular support for each memory variant

This does not conform to current conventions, and will likely need some general discussion around longer term strategy (eg #8179).

Also this will have to go via develop, per previous additions.

**Comment by elagil** [comment]
That looks like a good place to discuss this topic.

**Comment by tzarc** [comment]
I'd suggest putting this on hold to some degree until discussion occurs on #16534 -- if we go down a specific route it makes little sense making a whole bunch of changes only to find out that it's irrelevant after discussion.

**Comment by elagil** [comment]
I agree, I will make it a draft.

**Comment by patrickhirsh** [comment]
Thanks for this @elagil. I'm using work done in this branch to support a keyboard with a STM32L072KZT6. Sounds like the main blocker is just deciding how to handle supporting different flash memory variants, but let me know if there's any way I can help. I've compiled and linked successfully with this as well and will likely test on hardware this evening.

**Comment by elagil** [comment]
@patrickhirsh Thanks for testing! I would like to point you to this merge request, which is more though out and more likely to be the basis of further development: https://github.com/qmk/qmk_firmware/pull/16536

It will also support your chosen chip, and brings other improvements.

**Comment by patrickhirsh** [comment]
Great! Thanks @elagil. fetching that one now 🙂

**Comment by elagil** [comment]
> Great! Thanks @elagil. fetching that one now 🙂 

If it works (or doesn't) I would be very interested in your feedback. Maybe you find some irregularities.

**Comment by patrickhirsh** [comment]
@elagil I did get a chance to test it last night. Compilation, linking and (seemingly) flashing all went smooth. Oddly, the keyboard with work for ~5 seconds receiving input and registering key events before it'll suddenly halt and disconnect. I have no idea what could be causing this. I am able to reset it, at which point it'll work for another ~5 seconds before the same thing happens. Any ideas?

I noticed this output during flashing after the download completes, right at the end:
`Download done.
    File downloaded successfully
    Transitioning to dfuMANIFEST state
    Non-valid multiplier 'g', interpreted as type identifier instead                                 <<< THIS
*** STM32 DFU device disconnected (WinUSB): STMicroelectronics STM32  BOOTLOADER (0483:DF11:2200)`

Not sure if that could be indicative of a bad flash, but I seem to get it every time after recompiling and flashing. Let me know if you've got any ideas. I have exposed the SWD pins for debugging, so without knowing much about this, My plan is to try to get some kind of logging information that way and figure out what's happening here

**Comment by KarlK90** [comment]
There have been multiple reports of seemingly random lock-ups of keyboards after the update to ChibiOS 21.11.1 on the develop branch. This behaviour you are experiencing could be related. The root cause is yet to be found, but could be related to timer wrapping.

**Comment by elagil** [comment]
> ~5 seconds before the same thing happens. Any ideas?

As @KarlK90 suggested, it sounds a lot like a timer wrapping issue. The systick timer on the STM32L0x chips is only 16 bit long and runs at 10 kHz. Wrapping occurs after ~6.5 seconds. On the other hand, other chips with 32 bit timers will only suffer from any wrapping-induced problems after ~120 hours.

Of course, wrapping of the systick timer should not crash the processor, so there is probably a bug somewhere in firmware. To verify if that it is caused by using the develop branch, please apply this pull request to the current master and test with that.

**Comment by patrickhirsh** [comment]
I tried both of these branches this evening, but unfortunately it seems that neither solves the problem 🙁. Still the same issue. It also seems that my estimation on the time was wrong. I timed how long it takes for the keyboard to disconnect on all 3 versions and they all took almost exactly 20 seconds from boot to disconnect, which makes me think perhaps this isn't related to timer wrapping? (Assuming we would have expected to see a longer time before the disconnect with a lower systick).

Unfortunately I do not have an ST Link or any other development device capable of connecting to my SWD pinout to debug the chip, but I have one on the way with express shipping

**Comment by patrickhirsh** [comment]
Another thought I had is that maybe this could be related to clock drift? The STM32L072xx series boasts USB 2.0 crystal-less, so I've not included an external crystal in my board. [Internal self calibration of 48 MHz RC for USB](https://www.st.com/en/microcontrollers-microprocessors/stm32l072kz.html). Perhaps it's possible it's not defaulting to this clock source, seeing as there are quite a few different clock sources/options. I've got no real idea how to test that or verify the clock is accurate.

**Comment by elagil** [comment]
> Another thought I had is that maybe this could be related to clock drift?

@patrickhirsh I don't think that's the problem. The `mcuconf.h` file that is included in this PR includes `#define STM32_HSI48SEL STM32_HSI48SEL_HSI48`.

This leads to the following setting in ChibiOs, [selecting the correct source](https://github.com/ChibiOS/ChibiOS/blob/09d9092e4e5364bf7eb7f6621157db2fc7f36f81/os/hal/ports/STM32/STM32L0xx/hal_lld.h#L1163) (HSI48):

See the [reference manual](https://www.st.com/resource/en/reference_manual/rm0376-ultralowpower-stm32l0x2-advanced-armbased-32bit-mcus-stmicroelectronics.pdf), section **7.2.4 (HSI48 clock)**:

> The internal 48MHz RC oscillator is mainly dedicated to provide a high precision clock to the
USB peripheral by means of a special Clock Recovery System (CRS) circuitry. The CRS
can use the USB SOF signal, the LSE or an external signal to automatically and quickly
adjust the oscillator frequency on-fly.

**Comment by elagil** [comment]
> Will update here again this weekend
@patrickhirsh

I also did some testing, and can reproduce the problem.

After 10-20 seconds, the PC resets the USB interface, which I can also see in firmware. QMK triggers an event `USB_EVENT_RESET`, after which no further events occur. The keyboard just remains in the idle thread afterwards.

I tested the USB_CDC demo application from ChibiOS as well, which uses exactly the same MCU configuration settings. There, the problem does not occur, so it is definitely an issue in QMK.

Finally, I also ported my keyboard to ZMK, where there are no issues at all - the board just works. Thus, I don't think there is any hardware problem.

The question is, why the PC triggers a reset. Something must cause it, but I don't know how the USB protocol works and how to debug it (yet). In any case, there is no firmware lockup.

**Comment by patrickhirsh** [comment]
@elagil

Interesting! What hardware were you testing with to reproduce the issue? did you manage to get your hands on a STM32L072x/3x ship?

Last night I ran into some trouble getting the ST-LINK to communicate with my MCU via the SWD pinout on my board, but just now finally managed to get it to connect to the target. I'm going to try to get some logging / debug info at runtime using the info you provided earlier (thank you!) to see if I can figure out what in the firmware is causing the `USB_EVENT_RESET` to trigger

**Comment by elagil** [comment]
> Interesting! What hardware were you testing with to reproduce the issue? did you manage to get your hands on a STM32L072x/3x chip?

I use a self-made keyboard, centered around the STM32L072 (available at mouser). I would have used the STM32F042, but it wasn't in stock.

Good luck with debugging! In case you are using VSCode, you can try [this extension](https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug), along with (for example) [OpenOCD (this is for Windows)](https://xpack.github.io/openocd/install/) and gdb.

I use this kind of debug configuration (launch.json):
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Cortex Debug",
            "cwd": "${workspaceRoot}",
            "executable": "./.build/your_build_output.elf",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "openocd",
            "configFiles": ["interface/stlink.cfg", "target/stm32l0.cfg"]
        }
    ]
}
```

**Comment by patrickhirsh** [comment]
Thanks! I was initially trying to use STM32CubeIDE, but I'm having a difficult time setting up the debug configuration. I'll try VSCode with the Cortex-Debug extension + OpenOCD + gdb, since that's what I'd been using as a text editor to modify code anyway. This is my first time programming an ARM MCU and I underestimated the time it'd take to learn the tools 😅.  

Do you compile and flash through VSCode as well? Or do you just use it for debugging and compile/flash with QMK MSYS?

**Comment by elagil** [comment]
> I was initially trying to use STM32CubeIDE, but I'm having a difficult time setting up the debug configuration.

That is also nice, if you like Eclipse ;)

> I underestimated the time it'd take to learn the tools

Yes, it's not that easy, when you have never done it before!

> Do you compile and flash through VSCode as well?

Yes, I do. Usually I build within WSL2 when on Windows (but WSL has very limited hardware access for debugging), but now I just switched to Linux for the whole process. It is much simpler for setting up these toolchains, as most tools are included in the package sources.

**Comment by patrickhirsh** [comment]
Sorry to leave this thread hanging for a while. I've recently had time to dig into this again and finally have a debug environment set up and working with VSCode + Cortex Debug +STLink. I ended up moving to my Linux box as you suggested and that simplified things :)

I'm seeing the same behavior you mentioned in your post above on my hardware as well. It appears that key events are being transmitted properly for the first 10-20 seconds, then I hear a USB device disconnect sound. At this point, I can see that the last received USB event is a USB_RESET_EVENT and the USB event queue remains empty. If I set a breakpoint in the main keyboard loop, I can see that my inputs are still being processed and the firmware doesn't seem to be locked up - as you mentioned as well. 

Of course, I could always bail on QMK for ZMK, but I'd love to get this working. I'm determined to push a little further before calling it quits. It seems like either stepping through USB events on the QMK/ChibiOS side or sniffing USB transmission with Wireshark is the next step in trying to understand what's going on here. I'll share here if I find anything interesting. Just wanted to provide an update in case you or anyone else had made some more progress :)

**Comment by patrickhirsh** [comment]
This is the result of running the dmesg command on my linux machine after connecting the keyboard and waiting ~20 seconds. Seems like the data it's trying to transmit over USB is either mangled or not following protocol as expected:
`[1815423.270232] usb 1-1.3: new full-speed USB device number 102 using xhci_hcd
[1815423.496612] usb 1-1.3: New USB device found, idVendor=feed, idProduct=0000, bcdDevice= 1.00
[1815423.496627] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[1815423.496633] usb 1-1.3: Product: Uniform
[1815423.496637] usb 1-1.3: Manufacturer: Patrick Hirsh
[1815423.505151] input: Patrick Hirsh Uniform as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:FEED:0000.00F9/input/input354
[1815423.570072] hid-generic 0003:FEED:0000.00F9: input,hidraw12: USB HID v1.11 Keyboard [Patrick Hirsh Uniform] on usb-0000:00:14.0-1.3/input0
[1815423.572052] input: Patrick Hirsh Uniform Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.3/1-1.3:1.1/0003:FEED:0000.00FA/input/input355
[1815423.572884] input: Patrick Hirsh Uniform System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.3/1-1.3:1.1/0003:FEED:0000.00FA/input/input356
[1815423.634460] input: Patrick Hirsh Uniform Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.3/1-1.3:1.1/0003:FEED:0000.00FA/input/input357
[1815423.634844] input: Patrick Hirsh Uniform Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.3/1-1.3:1.1/0003:FEED:0000.00FA/input/input358
[1815423.635591] hid-generic 0003:FEED:0000.00FA: input,hidraw13: USB HID v1.11 Mouse [Patrick Hirsh Uniform] on usb-0000:00:14.0-1.3/input1
[1815438.806517] usb 1-1.3: reset full-speed USB device number 102 using xhci_hcd
[1815439.006052] usb 1-1.3: device descriptor read/64, error -32
[1815439.313944] usb 1-1.3: device descriptor read/64, error -32
[1815439.602051] usb 1-1.3: reset full-speed USB device number 102 using xhci_hcd
[1815439.801923] usb 1-1.3: device descriptor read/64, error -32
[1815440.110056] usb 1-1.3: device descriptor read/64, error -32
[1815440.401922] usb 1-1.3: reset full-speed USB device number 102 using xhci_hcd
[1815440.423911] usb 1-1.3: device descriptor read/all, error -32
[1815440.606230] usb 1-1.3: reset full-speed USB device number 102 using xhci_hcd
[1815440.606373] usb 1-1.3: Device not responding to setup address.
[1815440.814174] usb 1-1.3: Device not responding to setup address.
[1815441.022020] usb 1-1.3: device not accepting address 102, error -71
[1815441.022178] usb 1-1.3: USB disconnect, device number 102
[1815441.694023] usb 1-1.3: new full-speed USB device number 103 using xhci_hcd
[1815441.893894] usb 1-1.3: device descriptor read/64, error -32
[1815442.201886] usb 1-1.3: device descriptor read/64, error -32
[1815442.494023] usb 1-1.3: new full-speed USB device number 104 using xhci_hcd
[1815442.694039] usb 1-1.3: device descriptor read/64, error -32
[1815443.001839] usb 1-1.3: device descriptor read/64, error -32
[1815443.110144] usb 1-1-port3: attempt power cycle
[1815443.833809] usb 1-1.3: new full-speed USB device number 105 using xhci_hcd
[1815443.833941] usb 1-1.3: Device not responding to setup address.
[1815444.042156] usb 1-1.3: Device not responding to setup address.
[1815444.249920] usb 1-1.3: device not accepting address 105, error -71
[1815444.433810] usb 1-1.3: new full-speed USB device number 106 using xhci_hcd
[1815444.433978] usb 1-1.3: Device not responding to setup address.
[1815444.642129] usb 1-1.3: Device not responding to setup address.
[1815444.849826] usb 1-1.3: device not accepting address 106, error -71
[1815444.849964] usb 1-1-port3: unable to enumerate USB device`

**Comment by elagil** [comment]
Thanks for the update! That looks like what I could see on my machine as well.

If you need any assistance, please let me know.

**Comment by patrickhirsh** [comment]
After spending a lot of time trying to dig in to understand what was causing this, I eventually just decide to go with a direct implementation (writing the config files myself instead of specifying a board with the info.json file) based on @tzarc's [cyclone keyboard](https://github.com/tzarc/qmk_build/tree/master/tzarc-cyclone), which also uses the STM32L072. This is working perfectly for me, and has been for the last 2 weeks or so. You can find my own implementation [here](https://github.com/patrickhirsh/qmk_firmware/tree/uniform). 

Regretfully, I was unable to find the difference between what I implemented here and what the info.json file was generating in this PR. Perhaps someone with better knowledge of QMK than I can look a little deeper and figure this out.

**Pull request closed without merging**
