### PR TITLE
Add .clang-format file for #4867

### PR DESCRIPTION
**Pull request by pelrun**
## Description

Here's a .clang-format file I've been using which follows the defined code style (such as it is) as closely as I can manage.

## Types of changes
- [ ] Core
- [ ] Bugfix
- [x] New Feature
- [ ] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* #4867 

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by vomindoraan** [comment]
Awesome! I currently have no way of testing this, but thanks for putting in the effort, we definitely need formatting/linting rules.

**Comment by pelrun** [comment]
Bump!

**Comment by drashna** [comment]
I don't want to merge this without some input from @fredizzimo @jackhumbert and/or @skullydazed

**Comment by pelrun** [comment]
If you don't have clang-format set up locally, check out https://zed0.co.uk/clang-format-configurator/, which an interactive configuration tool for it. Set the version dropdown to 6.0.0, Load the file from this PR into it, copy some QMK code into the right hand pane, and see what you think.

**Comment by vomindoraan** [comment]
Was just looking for something like that. Thanks @pelrun, I'll check it out.

**Comment by drashna** [comment]
Hmmm, I noticed one thing that it doesn't reformat correctly.

```c
    if(!process_record_quantum(record))
        return;
```
Was changed to:
```c
  if (!process_record_quantum(record)) return;
```

I'm not sure about the clang settings, so...

**Comment by vomindoraan** [comment]
If I'm not mistaken, that should be changed to `if (!process_record_quantum(record)) { return; }`, correct?

**Comment by pelrun** [comment]
Eliding braces is forbidden!

There's `AllowShortIfStatementsOnASingleLine`, but no matter which way you set it, it'll change some things. We're inconsistent as hell.

**Comment by drashna** [comment]
> If I'm not mistaken, that should be changed to `if (!process_record_quantum(record)) { return; }`, correct?

Yeah, that's what is supposed to happen. 



> Eliding braces is forbidden!

Apparently :D

**Comment by vomindoraan** [comment]
Reading up on it, it looks like Clang-Format was not designed to insert/delete/modify braces (or any other semantic part of code), only whitespace. There's the `AllowShortBlocksOnASingleLine` option, which in conjunction with `AllowShortIfStatementsOnASingleLine` does what we want — but only if the braces are already there.

We can use Clang-Tidy to enforce OTBS and insert braces around all `if`, `for`, etc. statements.

**Comment by pelrun** [comment]
Or we can just let Drashna catch those problems during the PR review process :D

**Comment by vomindoraan** [comment]
It's a superset as in it literally contains Clang-Format (i.e. LibFormat) within itself and, as such, supports all options that Clang-Format supports. In other words, we only need to use Clang-Tidy.

**Comment by pelrun** [comment]
You still need a .clang-format file, because that's where clang-tidy gets it's configuration when it's doing a formatting step. If you want to raise a PR with a .clang-tidy configuration and the build system updated to run it, then feel free, but it doesn't invalidate this one.

**Comment by vomindoraan** [comment]
I'm not saying that this should be invalidated, but rather that only `clang-tidy` should be called in CI :smiley: Whether or not the formatting configuration is inlined in the `.clang-tidy` file with the `FormatStyle: <json>` option, or left in a separate `.clang-format` file with `FormatStyle: file` makes little difference.

In other words, add a `.clang-tidy` file alongside this that covers the linting part (braces etc.) and has the `FormatStyle` option set to `file`. Then add a call to `clang-tidy` to `.travis.yml` and wherever else it's required.

**Comment by vomindoraan** [comment]
I can do that latter part and submit it as a PR to your PR if you want.

**Comment by pelrun** [comment]
Ah, I see the problem. Formatting isn't useful at the CI stage, it's intended to be performed manually before making the commit and raising a PR.

Automatic validation using clang-tidy can be useful addition to CI, but it's pretty much completely independent of this PR.

**Comment by vomindoraan** [comment]
My mistake, I thought we would be enforcing this through CI or shared pre-commit hooks. In that case, the tidying step can be added in a separate PR, along with a section in the docs explaining how to set up local pre-commit hooks to lint and format the code.

**Comment by pelrun** [comment]
One caveat with using this is it will blow up layout definitions.

Need to add `// clang-format: off` just before those to protect them.

**Comment by drashna** [comment]
Is this ready to go, as is?

**Comment by vomindoraan** [comment]
It'd be nice to have this mentioned in `contributing.md`.

**Comment by drashna** [comment]
@pelrun could you add a mention to this in the contributing doc?

**Comment by pelrun** [comment]
Finally got around to updating the docs for this.

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
