### PR TITLE
Fix issues with Python Tests

### PR DESCRIPTION
**Pull request by drashna**
## Description

* Reformat python due to yapf changes
* Fix pytest keymap list test due to moved nui_mini

## Types of Changes

- [x] Core
- [x] Bugfix

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by peepeetee** [comment]
image
What I'm getting at from the name of this test, as well as what other tests below it is doing, is that this test tests for a keyboard that's not in a folder. therefore I believe the way to solve this is to find another keyboard that is unlikely to be moved into a folder(my candidate is crkbd) and substitute that

**Comment by drashna** [comment]
If anything, handwired/onekey would be a better solution, in that case.

**Comment by zvecr** [comment]
> If anything, handwired/onekey would be a better solution, in that case.

that would still fall into the "in a folder category" and be covered by the `test_list_keymaps_vendor_kb` case

**Comment by fauxpark** [comment]
`bfake` perhaps?

**Comment by peepeetee** [comment]
> `bfake` perhaps?

I'm trying to find out exactly which bfake our bfake is, and rename it/put it in a vendor forder accordingly

**Comment by tzarc** [comment]
`contra`? Mainly to go with the mystique of the legendary reddit post.

**Review by fauxpark — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Pull request merged**
