### PR TITLE
Handwired/Dactyl keyboard

### PR DESCRIPTION
**Pull request by ErinCall**
Adds specific support for the [Dactyl keyboard](https://github.com/adereth/dactyl-keyboard/).

It's mostly just a bent Ergodox. A couple of differences do impact the firmware:

* The two innermost columns are removed
  * this also means the topmost, innermost thumb-cluster keys are wired to the outermost columns (0 and B), not the innermost (6 and 7 on the ergodox).
* There are no caps/num/scroll lock LEDs.

This cribs heavily from `keyboards/ergodox_ez`.

### CODE REVIEW

**Comment by joedevivo** [comment]
@ErinCall, the wiring I did runs on the ergodox-ez build without any modification

**Comment by joedevivo** [comment]
the wiring is so compatible, I can use a dactyl for one half and an ergodox-ez for the other, but if memory serves, that means wiring one of the thumb keys to the otherwise unused inner column

**Comment by jackhumbert** [comment]
Awesome :) thanks!

**Comment by ErinCall** [comment]
Oh, I meant to mention--this version only supports column-driven (`COL2ROW`; current flows from row pins to column pins) configuration. I've started now on updating matrix.c to support either direction.

**Pull request merged**
