### PR TITLE
Updated my iris, planck, and xd75 keymaps

### PR DESCRIPTION
**Pull request by DavidRambo**
## Description

Changed keymap code to reflect new default keymap standards for both Planck and XD75.

Added Mac brightness controls to "Symbol" layer in my Planck keymap. Removed moused key from my Planck's rules.mk file.

Added a "Gaming" layer to my XD75 keymap.

Added "#pragma once" to my config.h files in Iris and Planck.

Tweaked syntax of several comment lines (e.g. added spaces after "//", changed "MAC" to "Mac").

Fixed the readme format for my Iris and XD75 keymaps. 

All successfully make and flash to keyboards.

Thanks!

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
If you have `#pragma once`, then you should remove the: 
```c
#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#endif
```

**Comment by DavidRambo** [comment]
Ah, thank you! Will do for Planck and Iris (already removed in XD75 config).

**Comment by drashna** [comment]
Just looking at the files, you should remove:
```c
#include "../../config.h"
#include "config_common.h"
```

The build process handles thes automatically, so they're unneeded, and actually, preprocessed out.

**Comment by DavidRambo** [comment]
Thank you, drashna. I suspected those would be redundant. I haven't been keeping up with the qmk changes these past months.

**Comment by drashna** [comment]
Well, a lot has changed, so that's understandable.   

But it looks good now!

**Pull request merged**
