### PR TITLE
Add option to enable LTO easily 

### PR DESCRIPTION
**Pull request by drashna**
and disable features that cause compilation errors when LTO is enabled. 

Added to `tmk_core/common.mk` rather than `common_features.mk`, since it's not really a feature.

### CODE REVIEW

**Comment by drashna** [comment]
I should probably add docs for this too.... 
That would be a better place for the warnings.

**Comment by mtei** [comment]
Previously, the advice you gave was to add `#define DISABLE_LEADER` to config.h. Is this not necessary now?

https://github.com/qmk/qmk_firmware/pull/3546#issuecomment-409683720

**Comment by drashna** [comment]
> Previously, the advice you gave was to add `#define DISABLE_LEADER` to config.h. Is this not necessary now?

At the time, it was true. However, it's since been moved into it's own "feature" that is off by default, and only enabled if you add `LEADER_ENABLE=yes` to the makefile settings. 

Also, the only reason I have it turning off the macros and functions is that enabling LTO can/will break those features.

**Comment by mtei** [comment]
I see.

FYI, there are also the following ways.

tmk_core/common.mk:
```c
ifeq ($(strip $(LINK_TIME_OPTIMIZATION_ENABLE)), yes)
	    EXTRAFLAGS += -flto
	    POST_CONFIG_H += $(TMK_DIR)/post_config.h
	    TMK_COMMON_DEFS += -DLINK_TIME_OPTIMIZATION_ENABLE
endif
```

tmk_core/post_config.h:
```c
#pragma once
#ifdef LINK_TIME_OPTIMIZATION_ENABLE
  #define NO_ACTION_MACRO
  #define NO_ACTION_FUNCTION
  #ifdef LEADER_ENABLE
    #error  some error message
  #endif
#endif
```

**Comment by drashna** [comment]
@mtei That would definitely work. But there is no reason to disable Leader Keys here, at all.     In fact, I think doing so is a bad idea, actually.     I think that we should use the "lightest touch" here, and not disable anything, unless it's needed (aka it's breaking something).

**Comment by mtei** [comment]
OK, you are right. I do not know the relationship between LTO and LEADER_ENABLE. Just simply, if you need collision detection, just let you know that there is a way.

**Comment by vomindoraan** [comment]
Consider `LTO_ENABLE` instead of `LINK_TIME_OPTIMIZATION_ENABLE`.

**Comment by mtei** [comment]
```
ifeq ($(filter $(LTO_ENABLE) $(LINK_TIME_OPTIMIZATION_ENABLE),yes), yes)
```

**Pull request merged**
