### PR TITLE
clueboard 60 fix col 11 12 mixup

### PR DESCRIPTION
**Pull request by yanfali**
Swaps columns 12 and 11 so they are in the correct positions for the matrix

## Description
This is a bug fix, this has been broken for quite a while.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by yanfali** [comment]
@skullydazed you said you'd check the schematic about 6 months ago iirc, I think it's time we fix this, it's pretty annoying

**Comment by noroadsleft** [comment]
Were you intending to have your keymap changes on this PR?

**Comment by yanfali** [comment]
> Were you intending to have your keymap changes on this PR?

yes. because they were broken from my point of view.

**Comment by yanfali** [comment]
@noroadsleft I will remove that rules.mk change though

**Pull request merged**
