### PR TITLE
Update buzzlighter1 keymap

### PR DESCRIPTION
**Pull request by buzzlighter1**
Cleaned and updated

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by waffle87** [comment]
Could you consolidate all your open PR's into one. No need for individual PR's for each file changed.
(#19760 #19759 #19758)

**Comment by buzzlighter1** [comment]
> Could you consolidate all your open PR's into one. No need for individual PR's for each file changed. (#19760 #19759 #19758)

I would love to, but I need a how-to, and searching for "consolidate opened PR" has no results. Different keyword to look for maybe?

**Comment by waffle87** [comment]
You'd [`git merge`](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) your branches into one (ie. your `patch-1` branch being used for this PR), then close the rest of the open PR's.

**Comment by keyboard-magpie** [comment]
At the moment you have made a different branch for every file change- these should be consolidated to one branch.

Go back to your first patch-1 branch and make the remainder of the desired changes there. Add, commit and push those files using git command line, and then you can perhaps use the github web interface to close/delete the other patch branches and PRs.

**Comment by buzzlighter1** [comment]
Can I do it in the web interface?

**Comment by waffle87** [comment]
No. Tom's suggestion of manually adding your changes to this branch is likely your best bet if you're trying to avoid CLI git.

**Comment by zvecr** [comment]
> https://github.com/buzzlighter1/qmk_firmware/tree/patch-1/keyboards/xiudi/xd75/keymaps/buzzlighter1

Ive done this for you in an effort to move things along.

You should make any further changes to <https://github.com/buzzlighter1/qmk_firmware/tree/patch-1/keyboards/xiudi/xd75/keymaps/buzzlighter1> instead of making new PRs.

**Comment by buzzlighter1** [comment]
Thank you! I was honestly trying to figure it out myself. 
I was pleasantly surprised when I saw editing functions in web interface and how easy it was... but it looks like going through multiple init/add/check/push/pull/commit/etc etc in command line is still necessary.

**Comment by zvecr** [comment]
> in command line is still necessary.

Nope, its not required.
Go to the link i provided as that will put you on the branch for this PR. Navigate to a file you want to edit. Make changes and when prompted make sure you select "commit directly to X branch", for example

image

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
