### PR TITLE
Ergodone - Change VID/PID to official values and enable NKRO by default

### PR DESCRIPTION
**Pull request by yuhe00**
Thanks to @marcostrauss

### CODE REVIEW

**Comment by fredizzimo** [comment]
Do you actually have permission to use those identifiers here? I don't think we can just use manufacurer's identifiers without permission.

**Comment by yuhe00** [comment]
I don't think K.T.E.C will mind, since it's still their product, but you are probably right. Will ask for permission. Closing this for now.

**Comment by marcostrauss** [comment]
@kairyu, @hging, @AdamYoung1234:

Dear [K.T.E.C. members](https://github.com/orgs/ktec-hq/people), [owners](https://github.com/pidcodes/pidcodes.github.com/pull/173) of the respective VID-PID combo, is it okay that your VID-PID combo as well as the one `47EC`, `E60D` is used in this repository?

**Comment by marcostrauss** [comment]
I was told, K.T.E.C. doesn't want the official values to be stored in this repo.

These questions remain:
- Can `47EC`, `E60D` be used as the default, as it contains the company's name?
- Can we put a link to http://pid.codes/1209/2328/ in the code, so that everybody who wants to use the official values, can do it by himself?

**Comment by jackhumbert** [comment]
Putting a link to the official codes should be fine. As for the defaults, it should probably be some not in use by anything else - it doesn't look like `47EC` is currently being used as a vendor ID, but I'd feel better about using our `FEED` as it's a little clearer that it's a bogus one.

**Comment by marcostrauss** [comment]
**Resolved.**

**Pull request closed without merging**
