### PR TITLE
Fix #4635 UCIS "eats" previous emoji.

### LINKED ISSUE #4635: UCIS "eats" previous emoji.
UCIS "eats" previous emoji.

When using UCIS and typing an emoji, if I type another one, then the last one gets "consumed" by the last one.

This can be avoided if I input one space after finishing the unicode. But when I input another one, the space is not there.

**System Information**
 - Keyboard:  Ergodox EZ
   - Revision (if applicable):  Batch 5a
 - Operating System: Manjaro Linux
 - avr-gcc version: 

 - arm gcc version: 8.2.0

 - QMK Firmware version: 8.2.0

 - Any keyboard related software installed? 
   - [ ] Auto Hot Key
   - [ ] Karabiner
   - [x] Other: Plover and Ibus

**Additional context**
I have made a small video

https://youtu.be/UxdapARsLJI

### PR DESCRIPTION
**Pull request by SalchiPapa**
Fixes my previous bug report.

## Description

It also swallows any character not only emojis.
## Types of changes

- [ ] Core
- [x] Bugfix
- [ ] New Feature
- [ ] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* #4635

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by SalchiPapa** [comment]
I have made a video of how it works for me

https://youtu.be/bg9aMissqIM

**Comment by drashna** [comment]
Is this still an issue?

**Comment by SalchiPapa** [comment]
Thank you for asking @drashna!

I am not using UCIS feature anymore :disappointed: I've found that for day to day English/Spanish (áóéúí, ü, ñ) typing using compose is more robust and also now I have triple tap dance for u -> ú  -> ü for example.

Maybe when I need math unicode symbols I will get back to this.

Best regards.

**Comment by AyyKamp** [comment]
Hi, unfortunately this is still an issue.
What happens is that backspace is being sent one too many times so it reverts further back than the original input. 
e.g. 
`abc{UCIS:kiss}` results in `ab😙` using the defaults from [here](https://beta.docs.qmk.fm/features/feature_unicode#ucis)

I can also confirm @SalchiPapa's fix works to resolve this.

**Pull request closed without merging**
