### PR TITLE
Create DZ60_Arrows_625u

### PR DESCRIPTION
**Pull request by mesnik**
I am building a new DZ60 with this keymap configuration https://jimmyb.ninja/post/1518390250 but couldn't find already designed.  This is my first pull request and keyboard configuration.  Hopefully I am doing it right!!!  I am sure someone will let me know.

: )

### CODE REVIEW

**Comment by noroadsleft** [comment]
Hey, I've been working on the still-ongoing addition/cleanup of the keyboard layouts supported by the Configurator.

There's a couple issues here, but I'll drop this line to you to hopefully point you in the right direction moving forward.

Bottom line, you've saved the file itself properly; it's a valid Configurator file. So that's good. Configurator files, however, need to be saved in the keyboard's root folder (in this case, `keyboards/dz60/`) with the filename `info.json`. Documentation regarding the format is [located here](https://docs.qmk.fm/#/hardware_keyboard_guidelines?id=keyboard-metadata), with a few caveats:

- Line 5: The `bootloader` tag is deprecated and not used by the Configurator anymore. The KLE to JSON Converter still generates them though. Not a major issue; it doesn't break anything. The official docs actually had this bit removed a day or two ago. For now I remove these by hand before I commit.
- Line 6: The `width` tag should be `15`, rather than the 15.25 you have. This seems to have been caused by some incorrectly-sized/positioned keys being fed to KLE before the data was fed to the Convertor. The left Shift as shown in the file you've committed is 2.25u, but on your actual keyboard, it's 2.0u. As a result, you have gaps that appear in the layout:  
  
Your layout is actually most similar to the [`LAYOUT_directional`](https://config.qmk.fm/#/dz60/LAYOUT_directional) that is currently present, but without the split Spacebar.
- Line 9: As the proper way to add layouts when there is already a Configurator file present for the keyboard is to edit the existing file in a branch, the layout name - `LAYOUT` in this case - needs to be unique; one cannot have two layouts with the same name, and there is already a `LAYOUT` [in the existing file](https://github.com/qmk/qmk_firmware/blob/692a77c2dd8a369f6ae6efa22270d1bdeb551f0b/keyboards/dz60/info.json#L8).

I'll tag @drashna who is usually the one who reviews/merges pull requests here (as a Collaborator, he has permissions) and ask that he advise you how to proceed.

There's a couple of us working on this "project" and more help is always welcome. Thanks for coming. You can find me on the [QMK Discord](https://discord.gg/hgCgpzx), usually in the #configurator channel.

**Comment by drashna** [comment]
It looks like this is basically just a customized JSON file dumped into the keymap folder.  No keymap or anything else to go with it?

**Comment by mesnik** [comment]
I thought this was the first step to be able to use the QMK Configurator, thus creating the full keymap, no?

**Comment by drashna** [comment]
Yes and no, and sort of on that yes. 

The Configurator uses existing "matrix definitions", and maps them to GUI buttons. 

So, the first thing that you'd need to do, is add a keymap/layout here:
https://github.com/qmk/qmk_firmware/blob/master/keyboards/dz60/dz60.h

This ... is complicated, and not for the faint of heart.  

Once that's added, you'd want to add a matching layout in the main info.json file, here:
https://github.com/qmk/qmk_firmware/blob/master/keyboards/dz60/info.json

If you want .... use the "LAYOUT_all" option in the configurator, and make sure that you ONLY have keys were there are soldered switches, and everything else has "NO" key codes (blank). 
Link that here (or attach the keymap json file), and myself or somebody can see about cleaning this up and adding it.

**Comment by drashna** [comment]
Fixed in #3148

**Pull request closed without merging**
