### PR TITLE
adds DZ60 support

### PR DESCRIPTION
**Pull request by jackhumbert**

### CODE REVIEW

**Comment by Dbroqua** [comment]
How!

Excellent, thank you!

**Comment by jackhumbert** [comment]
:) I haven't been able to test this - just going off of the schematic from kbdfans! If anyone is able to ensure it works, that would be great!

**Comment by Dbroqua** [comment]
I'm waiting for my PCB.

I will try as soon as I receive my PCB (if it's the same PCB as the Tina one: https://kbdfans.myshopify.com/products/tina-keyboard-60?variant=38954516941 ).

**Comment by Maartenwut** [comment]
If everything goes well I will receive mine in a day or two.

**Comment by jackhumbert** [comment]
Yeah, I'm not sure what all keyboards use it, but I'd like to list them all in the readme once confirmed!

**Comment by Maartenwut** [comment]
Works perfectly with my DZ60, thanks!

**Pull request merged**
