### PR TITLE
support for jj4x4 numpad/macropad by Kprepublic

### PR DESCRIPTION
**Pull request by sprayed**
## Description

This adds keyboard support for jj4x4 which is almost exact copy of the jj40 except the keys are arranged differently on the microcontroller lines. Everything is copied from the jj40 keyboard files except the key mapping which I managed to reverse engineer. The jj4x4 PCB is populated identically as the jj40 so I assume everything else is the same, and indeed it seems to flash and work fine.

## Types of changes

- [ ] Core
- [ ] Bugfix
- [ ] New Feature
- [ ] Enhancement/Optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

**i've edited the readme.md to reflect the changes. it is essentially the jj40 documentation, but half the stuff in there i have no idea about so i've left it in there.

### CODE REVIEW

**Comment by sprayed** [comment]
> The custom matrix is because it's an ATMega32a, right?
> 
> If so, you can actually eschew that, as the ATMega32a pins should be supported in the normal matrix.

Honestly, that's beyond my ability and knowledge. That part is copied over from the jj40 keyboard. I think the custom matrix is for controlling the rgb backlight? There's an "Atmel200 tiny85" on the pcb that is connected to the rgb backlights. I have no idea what the custom matrix does.

**Comment by pelrun** [comment]
Looks like another ps2avrgb board.

You can remove matrix.c and CUSTOM_MATRIX = yes from your rules.mk, and delete matrix.c entirely. Then add the following to your config.h:

```
#define MATRIX_ROW_PINS { B0, B1, B2, B3, B4, B5 }
#define MATRIX_COL_PINS { A0, A1, A2, A3, A4, A5 }
```

**Comment by sprayed** [comment]
Thanks! The custom matrix has been removed. I've also been able to simplify the matrix mapping further by defining exactly the pins that are used in the right order.

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
