### PR TITLE
add support for Orthodox keyboard

### PR DESCRIPTION
**Pull request by utrrrongeeb**
This branch adds support for the upcoming Orthodox keyboard from /u/Deductivemonkee, and has been successfully tested on the prototype boards.

Due to the nine-column layout, the interconnect protocols from the lets_split had to be adjusted. This will be an ongoing process; the current implementation is functional, but inelegant and inflexible.

Please excuse the ragged commit history on this branch – there were ill-advised merges from master into the feature branch, which were undone by cherry-picking into a clean branch.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! Is it only using I2C, and not serial? (the guide suggests this, but I'm not sure) 

We're gonna be doing a bit of reorganisation with the readme files soon - you might consider [making a page at qmk.fm for this](https://docs.qmk.fm/adding_a_keyboard_to_qmk.html#imagehardware-files), where things can be a bit more verbose, and have images/hardware files :)

**Comment by utrrrongeeb** [comment]
It can use either; both work. Both could use a bit of cleanup, code-wise, due to unexpected difficulties encountered in adding the ninth column, but i2c was worse (hence the workaround-like current solution for it). I'm hoping to clean it up once I have a better test setup.

The readme image is hotlinked from imgur, and I'd noted the existence/purpose of qmk/qmk.fm. I'll be glad when something's there for this. As for verbosity, much of that is carried over from lets_split; once there's a better idea of what the sparse readme format is (and a little more time), it can certainly be pared down. I believe there's a rewrite in the works of the Flashing section, new content, but that wasn't ready tonight.

**Comment by jackhumbert** [comment]
Ah, gotcha. Yeah, we'll be moving the I2C and serial to the core here pretty soon, and we'll help get things organised with that :)

Yeah, that's looking good! [This is what we're hoping the readmes will look like in future](https://github.com/qmk/qmk_firmware/issues/1362#issuecomment-310859229), but we'll be happy to help change things over/clean things up down the road!

Thanks!

**Comment by utrrrongeeb** [comment]
Thank you. I'd definitely like to follow that interconnects-to-core process, and see how that gets resolved.

**Pull request merged**
