### PR TITLE
Added Test_board

### PR DESCRIPTION
**Pull request by 0CODERKID**
## Types of Changes

- [x] Core
- [x] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by waffle87** [comment]
Did you intend to open this pull request?

**Comment by 0CODERKID** [comment]
@waffle87  yea?

**Comment by 0CODERKID** [comment]
is there an issue?

**Comment by waffle87** [comment]
Most of the code here does not conform to current QMK practices and is missing multiple things (ie. you did not follow the [PR Checklist](https://docs.qmk.fm/pr_checklist), despite checking the box that you did).

Additionally, pretty much everything about this keyboard and its code indicates that this is a "test"/incomplete/etc. and not really something that warrants being added. At least judging from [0CODERKID/hackpad](https://github.com/0CODERKID/hackpad).

Has this code actually been tested on hardware?

**Pull request closed without merging**
