### PR TITLE
Keycapsss Kimiko rev1: Configurator bugfix

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

I don't think it's supposed to look like [this](https://user-images.githubusercontent.com/18669334/108877291-f0886b00-75b3-11eb-984f-462b061b499d.png).

cc @BenRoe (keyboard maintainer)

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by BenRoe** [comment]
@noroadsleft many thanks for that you found it and already fixed it.

**Comment by noroadsleft** [comment]
@BenRoe,

Since you're here, here's an "after" image:

image

**Comment by BenRoe** [comment]
How do you get the image with the fixed positions?

**Comment by noroadsleft** [comment]
> Looks good. Only the angle of the MO and 1.5 keys are not correct.

This is a limitation of QMK Configurator – its UI code doesn't support key rotation at all.

> How do you get the image with the fixed positions?

As I am the de-facto maintainer of QMK Configurator, I have a workflow where I can do some testing of changes before they get deployed to the live site.

In short:

1. Deploy the Configurator locally (it becomes accessible through `http://localhost` in the browser).
2. Modify the `info.json` and save it.
3. Generate a `keymap.json` for the desired board for Configurator import, and save it as `"qmk_configurator/public/keymaps/p/Preview info.json_default.json"`.
4. Preview in the `localhost` deployment using `Ctrl+Shift+I` (this shortcut works on the live site too, for the record).
5. Click the `Load Default` button.

This shows you how the keys will be assigned if the `info.json` file is committed to the repo in its current state. You can't compile it, because there's no keyboard source assigned in Preview Mode, but at this point you've likely already made sure Configurator can compile the board anyway. Any board without a default keymap in Configurator either hasn't had a keymap added yet, or can't be compiled in a way that yields largely similar behaviour to compiling from the `qmk_firmware` source (certain features are incompatible with Configurator builds – Tap Dance and Unicode Map, off the top of my head, for example).

**Review by fauxpark — APPROVED** [review]

**Review by drashna — APPROVED** [review]

**Pull request merged**
