### PR TITLE
Added upcoming Midway60 Keyboard

### PR DESCRIPTION
**Pull request by mrnoisytiger**
## Description
Added upcoming Midway60 Keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
It looks like you have changes to some of the submodules.  Please revert these changes. 
You should be able to run `make git-submodule` and add a new commit.

**Comment by mrnoisytiger** [comment]
@drashna Submodules should be reverted

**Comment by mrnoisytiger** [comment]
Any chance I could get review on this? Submodules should be fixed.

**Comment by mrnoisytiger** [comment]
@drashna  Could I get the dependency tag removed on this guy? Thanks!

**Comment by drashna** [comment]
The dependency tag is there, because there is a change to the submodules.  Once that's resolved, it should be automatically removed.  

That said it looks like the submodules weren't fixed properly.  Try: 
```
make git-submodule
git commit --allow-empty -m "Fix submodules"
git push
```

This should (hopefully) fix the issue.

**Comment by mrnoisytiger** [comment]
> The dependency tag is there, because there is a change to the submodules. Once that's resolved, it should be automatically removed.
> 
> That said it looks like the submodules weren't fixed properly. Try:
> 
> ```
> make git-submodule
> git commit --allow-empty -m "Fix submodules"
> git push
> ```
> 
> This should (hopefully) fix the issue.

Steps done! Hopefully this should resolve it...

**Comment by mrnoisytiger** [comment]
Closing and deleting to destroy broken branch. Will re-create pull request.

**Pull request closed without merging**
