### PR TITLE
Remove ps2avrGB since its a hangover from the keyboards/winkeyless refactor

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Removes error within the output of http://compile.qmk.fm/v1/keyboards/error_log.

Given the `ps2avrGB` folder is partially a bmini, and that exists within` winkeyless/bmini`, the folder is now redundant.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mechmerlin** [comment]
what? This is the progenitor of all BMC boards ported into QMK. How dare you! Would you throw out your grandpa?  

jk jk. I'm all for it.

**Comment by noroadsleft** [comment]
Is the information there relevant for keeping around as docs or reference? It's been ages since I was in that folder.

**Comment by mechmerlin** [comment]
> Is the information there relevant for keeping around as docs or reference? It's been ages since I was in that folder.

It's not, all information in there is actually old and has been better wordsmithed in the corresponding BMC ports.

**Comment by zvecr** [comment]
I also have #5587 in progress which should hopefully improve on the information that was previously.

**Comment by noroadsleft** [comment]
@mechmerlin in that case:

**Pull request merged**
