### PR TITLE
rgblight_modes.h sample implementation for #5367

### PR DESCRIPTION
**Pull request by mtei**
@GrayHatter, Is this kind of change you want to do with #5367 ?

### CODE REVIEW

**Comment by drashna** [comment]
To be honest, I'd personally like to see something more like: 
https://github.com/qmk/qmk_firmware/blob/master/quantum/rgb_matrix.h#L71-L127

**Comment by mtei** [comment]
Certainly the definition of  `enum rgb_matrix_effects {};` is simpler and easier to understand than the definition of `enum RGBLIGHT_EFFECT_MODE {};`. 

I wish that someone can fix `enum RGBLIGHT_EFFECT_MODE {};` well like `enum rgb_matrix_effects {};`.

**Comment by drashna** [comment]
I might see about trying to do this, since I'm looking at improving rgb matrix and rgb light, and bringing them more on line with each other, since I am using both on one of my keyboards, now.

**Comment by mtei** [comment]
However, the DISABLE_RGB_MATRIX_XXXX macro is not good. Should have been the ENABLE_RGB_MATRIX_XXXX macro. That's because when someone adds a new mode, a lot of keyboard firmware gets undesirably large.

**Comment by drashna** [comment]
I do agree.  It would be better to explicitly enable.   

Honestly, I want to do a lot of changes to both features, to make them more in line with each other.   It's a matter of time/motivation for me.

**Comment by mtei** [comment]
However, it should be pointed out that including `rgblight_modes.h` multiple times also has a maintenance advantage.

It makes it easy to add helper tables.

I reduced the firmware size by adding `static uint8_t mode_base_table []` in PR #5020. Take a look at the code below.

https://github.com/mtei/qmk_firmware/blob/a2e5e9b97882c8e5f31016bd404b4af5686752f7/quantum/rgblight.c#L55-L74

https://github.com/mtei/qmk_firmware/blob/a2e5e9b97882c8e5f31016bd404b4af5686752f7/quantum/rgblight.c#L543-L545

https://github.com/mtei/qmk_firmware/blob/a2e5e9b97882c8e5f31016bd404b4af5686752f7/quantum/rgblight.c#L812

https://github.com/mtei/qmk_firmware/blob/a2e5e9b97882c8e5f31016bd404b4af5686752f7/quantum/rgblight.c#L818-L824

**Comment by mtei** [comment]
This change is closed because it is included in #5020.

**Pull request closed without merging**
