### PR TITLE
Initialize Layer State on startup

### PR DESCRIPTION
**Pull request by drashna**
Right now, on startup, the default layer state gets called and set, triggering the callback functions for the default layer state. However, the normal layer state never actually gets initialized.  It's set to 0 directly, by default, but the callback functions are never actually called.  This creates some inconsistency in the behavior for end users.  This adds a simple "clear" that triggers the callback on startup.  This should produce more consistent behavior between the two functions and layer masks.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
hmm, only issue is that the mock test now fails.  

Probably why this wasn't implemented before. 
Unfortunately, I'm not sure how to fix the test. :(

**Comment by fauxpark** [comment]
Haven't we run into this before?

**Comment by drashna** [comment]
Yes. Specifically with re-initing on eeprom reset, IIRC. But it was failing at a different point. 

Honestly, I suspect that the testing could use some TLC.

**Comment by kitlaan** [comment]
While I'm not sure what the intent of the gunit tests are... This causes them to go away with your original change:
```
diff --git a/tests/test_common/test_fixture.cpp b/tests/test_common/test_fixture.cpp
index 8caf1fca4..926b31512 100644
--- a/tests/test_common/test_fixture.cpp
+++ b/tests/test_common/test_fixture.cpp
@@ -22,7 +22,8 @@ using testing::Return;
 
 void TestFixture::SetUpTestCase() {
     TestDriver driver;
-    EXPECT_CALL(driver, send_keyboard_mock(_));
+    // Once for initial initialization, and again for bootmagic init
+    EXPECT_CALL(driver, send_keyboard_mock(_)).Times(2);
     keyboard_init();
 }
 
@@ -32,6 +33,7 @@ TestFixture::TestFixture() {}
 
 TestFixture::~TestFixture() {
     TestDriver driver;
+    EXPECT_CALL(driver, send_keyboard_mock(_)).Times(1);
     layer_clear();
     clear_all_keys();
     // Run for a while to make sure all keys are completely released
~
```

**Comment by spidey3** [comment]
Just curious, shouldn't this also be done even if bootmagic or magic are not configured (e.g. if using bootmagic lite)?

**Comment by drashna** [comment]
> Just curious, shouldn't this also be done even if bootmagic or magic are not configured (e.g. if using bootmagic lite)?

Nope.

If bootmagic is set to: 
* `full`/`yes`: bootmagic.c is included
* `lite`:  magic.c is included
* `no`/not set: magic.c is included

So there is no circumstance at which one or the other isn't included. 

The logic for this is here:
https://github.com/qmk/qmk_firmware/blob/dc6fe85b87a62ddba13b501a8d81bea9d5ff563b/tmk_core/common.mk#L29-L49

**Comment by spidey3** [comment]
> So there is no circumstance at which one or the other isn't included.

I stand corrected! 
Hadn't noticed that `magic.c` would be included in all circumstances.

**Comment by drashna** [comment]
No worries!  There are a lot of things that are hidden and obfuscated, if you haven't dug deep into the bowels of the code.   That's part of why I posted the code reference, since learning more == good. :)

**Comment by tzarc** [comment]
Retargeted `develop` due to core changes.
Are we waiting on anything else other than another review?

**Comment by drashna** [comment]
> Are we waiting on anything else other than another review?

Nope. Should be ready to merge.

**Pull request merged**
