### PR TITLE
Add better documentation for handling custom keycodes for keyboards

### PR DESCRIPTION
**Pull request by drashna**

### CODE REVIEW

**Comment by drashna** [comment]
Travis error is due to layout/userspace issue, not related to the v60_type_r board itself (default keymap compiles file)

**Comment by skullydazed** [comment]
I think we want to talk about this change more. I'm pretty loathe to migrate to a new name for `SAFE_RANGE` in the keymap. As we briefly discussed on discord I think having `SAFE_RANGE` maintain its current usage and creating something like `SAFE_RANGE_KB` is better.

**Comment by drashna** [comment]
For something like `SAFE_RANGE_KB`, we'd have to define that range, wouldn't we.   And that means that there is a limited number of keycodes that a keyboard could use.  

Unless we can do something like: 
```c 
#ifndef KB_KEYCODE_RANGE
#define KB_KEYCODE_RANGE 0
#endif 

enum {
  ...
  SAFE_RANGE_KB,
  SAFE_RANGE = SAFE_RANGE_KB + KB_KEYCODE_RANGE,
};
```

**Comment by Wilba6582** [comment]
What if the current enum value `SAFE_RANGE` is changed to something slightly different e.g. `SAFE_RANGE_QUANTUM` and then `#define SAFE_RANGE SAFE_RANGE_QUANTUM` immediately after the enum.

At the keyboard level, custom keycode enum can be:

```
enum {
    KC_FOO = SAFE_RANGE,
    KC_BAR,
    KC_BAZ,
    SAFE_RANGE_USER
};
#undef SAFE_RANGE
#define SAFE_RANGE SAFE_RANGE_USER
```

Then at the keymap (user) level, custom keycode enum can be similar:

```
enum {
    KC_BING = SAFE_RANGE,
    KC_BONG,
    KC_BANG
};
```

**Comment by drashna** [comment]
Closing this. 

If we do implement something like this, implementing it at the core level would be best.

**Pull request closed without merging**
