### PR TITLE
Gc9107 driver

### PR DESCRIPTION
**Pull request by fpb**
## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by elpekenin** [comment]
Changes to `lib/` need to be reverted

Also, seems like the opcodes (at least partially) match with `gc9a01`. So, should perhaps merge them into a common folder (`gc9xxx`?) and avoid some duplication, similar to what `st77xx` or `ili9xxx` already do

**Comment by fpb** [comment]
> Changes to `lib/` need to be reverted
> 
> Also, seems like the opcodes (at least partially) match with `gc9a01`. So, should perhaps merge them into a common folder (`gc9xxx`?) and avoid some duplication, similar to what `st77xx` or `ili9xxx` already do

Had that in mind but I don't have a gc9a01 to test. I am sure that a lot of init code in the gc9a01 can be removed too.

**Comment by elpekenin** [comment]
I dont mean the init code, which should be left as is.

I mean the header file with the opcodes, which could be merged with yours.

Again, you can take a look at st77xx or ili9xxx for some reference

**Comment by fpb** [comment]
> I dont mean the init code, which should be left as is.
> 
> I mean the header file with the opcodes, which could be merged with yours.
> 
> Again, you can take a look at st77xx or ili9xxx for some reference

Ok. Do you see any problem changing the opcode names too? 

I think their names should follow as much as possible the terms used in the data sheets. But that will require some retouching in the current gc9a01 implementation file. Also, I prefer the init code to be as much descriptive as possible instead of using (unknown commands or magic parameter values).

I will try to find some cheap gc9a01 lcd to make some tests and see what can be cleaned there too. But that will probably take around 2 weeks before it arrives.

**Comment by elpekenin** [comment]
> Do you see any problem

Im not a maintainer, just another user, so my opinion is not too relevant :P

---

That said, given that a second device on the family is being added, i think renaming from `<device>_<command>` to `<family>_<command>` is not only a good idea, but also a desirable change. Of course, there might be some commands that are specific to a specific device in the series and would need a dedicated file for those.

As per the renaming of the `<command>` part, i dont think it is too critical. The little amount of people that will get down into  this code will most likely know what they are doing and the mismatch wouldn't cause an issue... Anyway, if the command has the exact same name on all datasheets but another name is used on QMK, sounds like a good change too.

On the testing aspect, if you are careful with the renaming, you shouldn't break stuff (and other people who already have the hardware can test too). However, im not the one doing the PR or spending money on a device, so that's up to you :)

**Comment by fpb** [comment]
Created a new PR with a structure inspired by ST77XX family of drivers.

**Comment by elpekenin** [comment]
Next time just edit the existing PR.

**Comment by fpb** [comment]
> Next time just edit the existing PR.

Let's just say I wasn't too confident on my git skills [:(]

**Pull request closed without merging**
