### PR TITLE
Added support for LED backlight, XD60v2's RGB underglow LED

### PR DESCRIPTION
**Pull request by stanleylai**
- Updated to include support for XD60v2 PCB's soldered on RGB underglow LEDs.
- LED backlight support added
- Cleaned up and fixed GPIO comments and assignments in xd60.h

Known Issue:
- Can't get variable brightness for LED backlight. Limitation of XD60? ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by jackhumbert** [comment]
Awesome! Do you know of the differences between the two versions? Would it make sense to have the revisions be subprojects?

**Comment by backstabbd88** [comment]
@stanleylai , is XD60v2 the version with the  black pcb?

**Comment by stanleylai** [comment]
@jackhumbert It seems to be exactly the same as v1, as far as I can tell. The only addition is soldered on RGB underglow LEDs, which I have added support for. So I just updated the previous v1 project to v2. So far everything seems to be backward compatible :)

@backstabbd88 it should say XD60v2 on the top of the PCB, and they have now included soldered on RGB underglow LEDs. Both are black PCBs.

**Comment by jackhumbert** [comment]
Cool! Would you mind adding a note about the versions to the readme? :)

**Comment by backstabbd88** [comment]
@backstabbd88 ok i'm gonna check mine when i get home, i've been using the code from gh60/robomaxtron for rgb underglow and i can't make some of the light mode work, only breathing mode with 1 color at a time.

Can't wait to try your code @stanleylai. Thanks!

**Comment by stanleylai** [comment]
@jackhumbert readme updated :)

**Comment by jackhumbert** [comment]
Awesome :) if you get the chance, would you mind checking out #1090? I think that'll work for this pin. You'll need to increase the number of backlight levels in your config.h though.

**Comment by stanleylai** [comment]
BL_STEP now works as intended, but only when BACKLIGHT_LEVELS is >6. Below that, the brightness difference for each step is tiny, and there isn't a LED off state. BL_TOGG doesn't work regardless of the BACKLIGHT_LEVELS value.

**Comment by jackhumbert** [comment]
Ah, cool! Thanks for testing :)

**Comment by tobsn** [comment]
@stanleylai I just flashed with the default layout and the RGB lights are just red - how do you control it? I couldn't see anything in the keymap :/

**Comment by stanleylai** [comment]
@tobsn I have it setup on my personal keymap here: https://github.com/qmk/qmk_firmware/blob/master/keyboards/xd60/keymaps/stanleylai/keymap.c

**Pull request merged**
