### PR TITLE
Katamari song

### PR DESCRIPTION
**Pull request by pvinis**
## Description

Added a new song from katamari

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [X] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Sorry to leave you in limbo. 

RIght now, as is, we don't have any plans on merging this.  That is because it is a copyright concern. 

However, leaving this open for the future, if/when we implement a good way to include songs that doesn't leave QMK in a precarious state.

**Comment by pvinis** [comment]
oooh ok. that makes sense. I can close this and maybe make an issue instead?

**Comment by drashna** [comment]
That's your call.   Either should be fine, but an issue may be cleaner, for now.

**Comment by drashna** [comment]
I know that @skullydazed wanted to implement a method to import music without having it stored in the repo.  However, it's not implemented yet.

And for the same of cleaning up PRs, I think opening an issue about this would be a better idea now.

So, for now, I'm closing this PR.

**Pull request closed without merging**
