### PR TITLE
Helix rev1 Configurator-oriented updates

### PR DESCRIPTION
**Pull request by noroadsleft**
The goal of this PR is to remove the `helix` option from the Configurator, while having the `helix/rev1` and `helix/rev2` options remain.

## Caveat:

This PR will make it so that a revision folder **must** be specified in the `make` command.

```
make helix:default           # This doesn't work
make helix/rev2:default      # This does work
make helix/rev1:default      # This works too
```

### CODE REVIEW

**Comment by drashna** [comment]
I'm not sure that removing the "helix" option is the correct thing to do here, since it will break `make helix` for anyone compiling from source.

I think that getting the configurator to ignore it, rather than removing it is better.

(also, thinking of other boards too)

**Comment by skullydazed** [comment]
I think we need to have a larger discussion about `DEFAULT_FOLDER` and when it should be used. It's not clear to me why we want to have `make helix:default` work but not have helix as a target in configurator.

**Comment by noroadsleft** [comment]
@skullydazed 

Go on Discord and search for `from: mechmerlin#2999 "folder names"`; that'll take you to the start of a conversation between @mechmerlin and @yanfali. (You and I both chime in later on.) qmk/qmk_configurator#175 is part of the context for this.

The TLDR is that Merlin discovered a user who was trying to flash a JC65 (Rama M65-A) from the Configurator. There's two versions of that PCB, [one that runs QMK natively](https://github.com/qmk/qmk_firmware/tree/master/keyboards/jc65/v32u4) and [the other runs that runs ps2avrGB](https://github.com/qmk/qmk_firmware/tree/master/keyboards/jc65/v32a). Configurator reads the `DEFAULT_FOLDER` rule and treats `helix` as `helix/rev2`, but doesn't expose this behavior to the user. So the `helix` and `helix/rev2` options are identical, but this can lead to issues like the case of the JC65 user, who ended up with a hex file for the v32u4 version, but had a v32a PCB.

Perhaps there's a better solution for this business, but I agree the conversation needs to be had. Maybe the Configurator should just ignore `DEFAULT_FOLDER` rules instead?

**Comment by noroadsleft** [comment]
"Fixed" in qmk/qmk_configurator#198.

Further discussions are still needed on this issue though.

**Pull request closed without merging**
