### PR TITLE
 dactyl_manuform 5x7 aka Ergodox added

### PR DESCRIPTION
**Pull request by zwnk**

### CODE REVIEW

**Comment by zwnk** [comment]
the fw was tested on a 5x7.

**Comment by drashna** [comment]
Could you remove the ZIP file?

**Comment by zwnk** [comment]
done. sorry did'nt realize that.

**Comment by zwnk** [comment]
Hi drahna. anything else missing?

**Comment by drashna** [comment]
Only my notice. Sorry! 

And thanks!

**Pull request merged**
