### PR TITLE
[Keyboard] Fix compiler errors for Kingly Key boards

### PR DESCRIPTION
**Pull request by drashna**
## Description

Tapping term was referenced, but not defined by default.  

## Types of Changes

- [x] Bugfix
- [x] Keyboard (addition or update)

## Issues Fixed or Closed by This PR

* Travis CI 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — CHANGES_REQUESTED** [review]
`get_tapping_term` is also wrong, so i would personally do something like....

```diff
diff --git a/keyboards/kingly_keys/ave/ortho/keymaps/default/keymap.c b/keyboards/kingly_keys/ave/ortho/keymaps/default/keymap.c
index 4e195d43b..8411e8fe6 100644
--- a/keyboards/kingly_keys/ave/ortho/keymaps/default/keymap.c
+++ b/keyboards/kingly_keys/ave/ortho/keymaps/default/keymap.c
@@ -16,6 +16,7 @@
  */ 
 
 #include QMK_KEYBOARD_H
+#include "action_tapping.h"
 
 enum avenue_layers {
   _QWERTY,
@@ -185,7 +186,7 @@ const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
 
 
 // Per-Key Tapping Term Definitions:
-uint16_t get_tapping_term(uint16_t keycode) {
+uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record){
   switch (keycode) {
     case TD(TD_DBQT):
       return 235;
```

**Comment by drashna** [comment]
> ```diff
> +#include "action_tapping.h"
> ```

If anything, that should probably be added further up the chain, or as a prototype somewhere, that way, this doesn't happen in the future.  but that would be a different PR.

**Comment by zvecr** [comment]
The idea in the short term is, adding `action_tapping.h` removes the need to duplicate the default at the keymap level. Not that I imagine we would change it any time soon, but you would end up with a mixture if someone didnt then refactor all keymaps at the same time.

**Comment by fauxpark** [comment]
https://github.com/qmk/qmk_firmware/pull/10042#issuecomment-727178746

**Comment by drashna** [comment]
For now, this should be fine.  But I already have #11127, which addresses this long term. I can include this change in that, instead.

**Comment by zvecr** [comment]
Still not a fan of the following block being added to the keymap
```c
#ifndef TAPPING_TERM
#    define TAPPING_TERM 200
#endif
```

Would rather push forward with #11127 if thats going to be a sticking point.

**Review by skullydazed — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Pull request merged**
