### PR TITLE
add RGBLIGHT_EFFECT_BREATHE_TABLE macro, If defined, use fixed breath table instead of exp() and sin()

### PR DESCRIPTION
**Pull request by mtei**
## Description

The RGBLIGHT_EFFECT_BREATHE_TABLE macro has been added to reduce the firmware size when using rgblight's breathing effect.

Example:

```
% make crkbd:default
......
Linking: .build/crkbd_rev1_default.elf
Creating load file for flashing: .build/crkbd_rev1_default.hex
Copying crkbd_rev1_default.hex to qmk_firmware folder
Checking file size of crkbd_rev1_default.hex
 * The firmware size is fine - 28388/28672 (284 bytes free)
```

```
% git diff
diff --git a/keyboards/crkbd/rev1/config.h b/keyboards/crkbd/rev1/config.h
index 55bf5930f..c4f29da6e 100644
--- a/keyboards/crkbd/rev1/config.h
+++ b/keyboards/crkbd/rev1/config.h
@@ -54,6 +54,8 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #define RGB_DI_PIN D3
 
 #define RGBLED_NUM 12    // Number of LEDs
+// reduce firmware size when using RGBLIGHT_EFFECT_BREATHING
+#define RGBLIGHT_EFFECT_BREATHE_TABLE
 
 /*
  * Feature disable options

% make crkbd:default
..........
Creating load file for flashing: .build/crkbd_rev1_default.hex 
Copying crkbd_rev1_default.hex to qmk_firmware folder 
Checking file size of crkbd_rev1_default.hex 
 * The firmware size is fine - 26702/28672 (1970 bytes free)
```

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by vomindoraan** [comment]
I think either the word `BREATHE` or `BREATHING` should be used instead of `BREATH` (as in “breath table”).

**Comment by mtei** [comment]
Thank you for pointing out the word mistakes.

**Comment by XScorpion2** [comment]
Silly thought, but why don't we make the table method the default? It's faster to lookup vs calculate, and it is smaller firmware size at the cost of a slight bit of smoothness? How big of a visual change is it? Only concern would be ARM support, but I think we have defines for PROGMEM and pgm_read_byte.

**Comment by mtei** [comment]
I couldn't decide which would be better. So I chose to maintain the status quo.

If the object to be floating-point calculation is only `rgblight.o`, the use of the table will reduce the firmware size. But if not, rgblight.o himself grows. In such cases might exceed the limit of the size of the firmware. I could not ignore the possibility.

**Comment by XScorpion2** [comment]
Mmm, very solid point as always. Though that does bring up that the code base should probably be reviewed for float / double math and replaced where approerate.

**Comment by mtei** [comment]
#5484 was better than this, so it closed.

**Pull request closed without merging**
