### PR TITLE
Tranlsated README.md into russian language

### PR DESCRIPTION
**Pull request by greggubarev**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
@StrikerRUS @nabokovas You guys mind looking this over for me?

**Comment by StrikerRUS** [comment]
@greggubarev Hi! I'm sorry, but it seems that you translated README which had been already translated in #6967 by me. I remember, QMK-team created #6924 to track the translation progress and avoid duplicated  work. You may want to get familiar with it.

@noroadsleft That's what about I was sayin in https://github.com/qmk/qmk_firmware/pull/6967#issuecomment-539261763
> to prevent from different contributors commit the same folder creation and introduce conflicts.

I'll try to commit the translation of two files that I promised in a few hours.

**Comment by noroadsleft** [comment]
@StrikerRUS,

> That's what about I was sayin in [#6967 (comment)](https://github.com/qmk/qmk_firmware/pull/6967#issuecomment-539261763)
> 
> > to prevent from different contributors commit the same folder creation and introduce conflicts.

Good point. We are internally evaluating our procedures here, and have already identified a few areas in which to improve should we do another Hacktoberfest event in the future.

Perhaps if he's willing, you could team up with @greggubarev and maybe work out which areas of the docs you each will do, so there's no overlap?

At this moment I'm more inclined to go with your PR as it's more complete, but I can't speak to the translation accuracy or quality of either pull request, because I don't know Russian.

**Comment by greggubarev** [comment]
@noroadsleft @StrikerRUS - I am ready to translate those documents that have not yet been translated, can I find out - which ones can I start working on?

**Comment by StrikerRUS** [comment]
@greggubarev I guess any which are untouched by other Russian-translation PRs. There are a lot docs there. But it's better to wait for an answer from QMK collaborators, I think.

**Comment by noroadsleft** [comment]
@greggubarev You could start on the pages under the QMK Basics section of the Docs. Not `docs/ru-ru/README.md`; that's on the other Russian translation PR, but:

- QMK Introduction
- QMK CLI
- QMK CLI Config
- Contributing to QMK
- How to Use Github
- Getting Help

... all could use translations.

**Comment by greggubarev** [comment]
> @greggubarev You could start on the pages under the QMK Basics section of the Docs. Not `docs/ru-ru/README.md`; that's on the other Russian translation PR, but:
> 
> * QMK Introduction
> * QMK CLI
> * QMK CLI Config
> * Contributing to QMK
> * How to Use Github
> * Getting Help
> 
> ... all could use translations.

ok, confirmed

**Comment by noroadsleft** [comment]
@greggubarev Any progress to report?

**Comment by greggubarev** [comment]
> @greggubarev Any progress to report?

@noroadsleft yes, with other PR`s. I think, we need to close this one

**Pull request closed without merging**
