### PR TITLE
Move GMMK Pro to allow for multiple revisions

### PR DESCRIPTION
**Pull request by GloriousThrall**
## Description

We have added GMMK PRO WestBerry G7 MCU QMK compatibility and updated the file structure to meet QMK Repo standards. Also, we have added GMMK V2 QMK compatibility which will also use the WestBerry G7 MCU.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — CHANGES_REQUESTED** [review]
A lot to unpack so will stick to the high level issues:
* 200+ files is too many for a single PR
  * Each keyboard add should be its own
* Moving of `keyboards/gmmk/pro` will have to go via `breaking changes`
  * this will unnecessarily stall the merge of the other added keyboards (another reason to break up to smaller PRs)
* duplication of core `spi_master` and `flash_spi` logic is unlikely to be ever accepted 
  * those added to `keyboards/gmmk/gmmk2/external_flash` just fragment the code base and are contributing in the opposite direction to that of QMK
* `keyboards/gmmk/gmmk2/gmmk2.h` is also conceptually wrong when keyboards have difficult physical layouts
* various outstanding issues from PR checklist

**Comment by tzarc** [comment]
Deferring to Q3 merge cycle -- unaddressed concerns.

**Comment by wb-Joy** [comment]
What are concerns to resolve?

**Comment by tzarc** [comment]
> What are concerns to resolve?

https://github.com/qmk/qmk_firmware/pull/16423#pullrequestreview-889217153

**Comment by tzarc** [comment]
>     * 200+ files is too many for a single PR
>       
>       * Each keyboard add should be its own

This counts for rev1 and rev2. Separate PRs.

>     * Moving of `keyboards/gmmk/pro` will have to go via `breaking changes`
>       
>       * this will unnecessarily stall the merge of the other added keyboards (another reason to break up to smaller PRs)

This is a QMK policy and has been in place for at least two years. Moving keyboards or keymaps introduces disruption to users who expect their boards/keymaps to exist where they last left it.

Keyboard moves need to be modified in the [keyboard aliases](https://github.com/qmk/qmk_firmware/blob/develop/data/mappings/keyboard_aliases.json) file, too. This PR cannot proceed until that is completed.

>     * duplication of core `spi_master` and `flash_spi` logic is unlikely to be ever accepted
>       
>       * those added to `keyboards/gmmk/gmmk2/external_flash` just fragment the code base and are contributing in the opposite direction to that of QMK

These files should be removed -- both Glorious and Keychron seem to want to go in a different direction to QMK -- duplication of code with minor tweaks, making it even harder for maintenance.

#16996 works towards a solution for the wear leveling abstraction, but that won't be ready for this breaking changes cycle anyway. Suggest reverting to use transient EEPROM in the short term, EEPROM-on-external-flash will be coming next cycle.

>     * `keyboards/gmmk/gmmk2/gmmk2.h` is also conceptually wrong when keyboards have difficult physical layouts
>       
>       * note that `keyboards/xiudi/xiudi.h` does not exist for the `xd84` and `xd96`

Not sure why the file even exists in the first place. Can you give some guidance here?

**Comment by tzarc** [comment]
For clarity, best to repurpose this PR to move rev1.
In theory this PR has already missed the cutoff for the Q2 breaking changes merge window, but we're willing to process the move anyway.

**Comment by wb-Joy** [comment]
> For clarity, best to repurpose this PR to move rev1. In theory this PR has already missed the cutoff for the Q2 breaking changes merge window, but we're willing to process the move anyway.

Ok, I'll take care of it.

**Comment by wb-Joy** [comment]
please, review.

**Comment by tzarc** [comment]
> please, review.

`keyboards/gmmk/pro/rev1/keymaps/moults31/keymap.c` should probably be under `ansi`, too.

**Comment by tzarc** [comment]
`keyboards/gmmk/pro/rev1/ansi/keymaps/keymaps/moults31/keymap.c` now has `keymaps` twice.

**Review by tzarc — APPROVED** [review]

**Comment by Amathadius** [comment]
Why did you do that? It broke everything. I can't update my keyboard anymore. I have to redo everything to make it work until it breaks again, right?

**Pull request merged**
