### PR TITLE
[Docs]Retranslate newbs section to Simplified Chinese, part of #14924 

### PR DESCRIPTION
**Pull request by peepeetee**
## Description

Part of my partitioning of #14924 to make it multiple small PRs

Files included here (the list is files translated in #14924):
- [x] * Tutorial
  - [x] * [Introduction](newbs.md)
  - [x] * [Setup](newbs_getting_started.md)
  - [x] * [Building Your First Firmware](newbs_building_firmware.md)
  - [x] * [Flashing Firmware](newbs_flashing.md)
  - [x] * [Getting Help/Support](support.md)
  - [x] * [Other Resources](newbs_learn_more_resources.md)
  - [x] * [Syllabus](syllabus.md)

- [ ] * FAQs
  - [ ] * [General FAQ](faq_general.md)
  - [ ] * [Build/Compile QMK](faq_build.md)
  - [ ] * [Troubleshooting QMK](faq_misc.md)
  - [ ] * [Debugging QMK](faq_debug.md)
  - [ ] * [Keymap FAQ](faq_keymap.md)
  - [ ] * [Glossary](reference_glossary.md)

- [ ] * Configurator
  - [ ] * [Overview](newbs_building_firmware_configurator.md)
  - [ ] * [Step by Step](configurator_step_by_step.md)
  - [ ] * [Troubleshooting](configurator_troubleshooting.md)
  - [ ] * [Architecture](configurator_architecture.md)
 - [ ] * QMK API
    - [ ] * [Overview](api_overview.md)
    - [ ] * [API Documentation](api_docs.md)
    - [ ] * [Keyboard Support](reference_configurator_support.md)
    - [ ] * [Adding Default Keymaps](configurator_default_keymaps.md)

- [ ] * CLI
    - [ ] * [Overview](cli.md)
    - [ ] * [Configuration](cli_configuration.md)
    - [ ] * [Commands](cli_commands.md)
    - [ ] * [Tab Completion](cli_tab_complete.md)

- [ ] * Using QMK
  - [ ] * Guides
    - [ ] * [Customizing Functionality](custom_quantum_functions.md)
    - [ ] * [Driver Installation with Zadig](driver_installation_zadig.md)
    - [ ] * [Easy Maker for One Offs](easy_maker.md)
    - [ ] * [Keymap Overview](keymap.md)
    - [ ] * Development Environments
      - [ ] * [Docker Guide](getting_started_docker.md)
      - [ ] * [Vagrant Guide](getting_started_vagrant.md)
    - [ ] * Flashing
      - [ ] * [Flashing](flashing.md)
      - [ ] * [Flashing ATmega32A (ps2avrgb)](flashing_bootloadhid.md)
 

  - [ ] * Advanced Keycodes
    - [ ] * [Grave Escape](feature_grave_esc.md)
    - [ ] * [Mod-Tap](mod_tap.md)
    - [ ] * [Space Cadet Shift](feature_space_cadet.md)

  - [ ] * QMK Reference
    - [ ] * [Contributing to QMK](contributing.md)
    - [ ] * [Translating the QMK Docs](translating.md)

I've removed zh-cn/newbs_best_practices.md, see #7231

This kinda depends on #15447 and #15445 to make sense
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* #15443

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by peepeetee** [comment]
#15443

**Comment by peepeetee** [comment]
duplicate work, #14924

**Comment by peepeetee** [comment]
I checked out newbs_* from #14924 to make it go in faster, as a small PR is easier to review

**Review by LitoMore — APPROVED** [review]

**Comment by peepeetee** [comment]
Needs some help with reviewing @mechmerlin @renmu123 @ymzcdg @ShiftyBlock @idiotstone @jeromeli002

**Pull request closed without merging**
