### PR TITLE
Add Tetris keyboard to QMK

### PR DESCRIPTION
**Pull request by YCF**
TetrisPhoto

A compact 40% (12x4) ortholinear keyboard (Planck Mit layout) with per switch RGB and encoder.
Also the default powerful keymap.c may help other people to make theirs keyboard more powerful .

### CODE REVIEW

**Comment by YCF** [comment]
The Travis CI build have a  WARNING:
`Checking file size of tetris_default.hex                                                            [WARNINGS]`
` * Your file is too big! 30466/28672`

but,Here is the real size at my pc:
` * File size is fine - 28548/28672`

It's OK!

**Comment by YCF** [comment]
@drashna the `#define NO_MUSIC_MODE` is the one  what I need,thank you very much.

**Comment by drashna** [comment]
Yeah, I need it too.  Heck, I'm the one that added it. :)

**Comment by drashna** [comment]
Yeah, it compiles smaller than Travis indicates... which is odd.  But then again, not unheard of.

It may be worth checking out my userspace config.h file, as I've disabled a bunch of stuff to reduce firmware size.

**Pull request merged**
