### PR TITLE
[Core][Bugfix] Joystick: Ignore axis-related code when axes count=0

### PR DESCRIPTION
**Pull request by amrsoll**
The analog joystick feature does not compile accross all platforms (see https://github.com/qmk/qmk_firmware/pull/4226#pullrequestreview-460275628)

All joystick related code is put between `#if JOYSTICK_AXES_COUNT > 0`

This also reduces the size of the compiled code when you only want to use joystick buttons.

### How to reproduce bug:

1. `qmk new-keyboard`
2. select the MCU `GD32VF103` (other options don't matter)
3. `rules.mk` Add `JOYSTICK_ENABLE = yes`
4. `config.h` : Add
    ```c
    #define JOYSTICK_BUTTON_COUNT 1
    #define JOYSTICK_AXES_COUNT 0
    ```
5. (optional) Change a key to `JS_BUTTON0` in keymap
6. run `qmk compile` against new keyboard

Errors will show related to the ADC.

### Disclaimer

1. I do not have the proper HW to debug on all keyboards, but it does work from the RP2040 branch which has a similar problem
   TBH, I'm mostly submitting this PR because it allows me to :see_no_evil: on the bug I described in  https://github.com/qmk/qmk_firmware/pull/14877#issuecomment-1114032488
2. I guess `ifeq ($(shell expr $(JOYSTICK_AXES_COUNT) \> 0), 1)` ain't so pretty,
   but it didn't work with `#ifneq ($(JOYSTICK_AXES_COUNT), 0)` ??
3. I have not been able to test if it actually broke the joystick (axis) feature, but I really can't see how it would.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
The `savePinState`/`restorePinState` logic is due to be removed, which would supersede this fix.

**Comment by amrsoll** [comment]
I am looking forward to that! The logic in the joystick parts are a bit confusing to me. Where is the

**Comment by amrsoll** [comment]
Do you mean it won't work in `common_features.mk` ?

**Comment by fauxpark** [comment]
`JOYSTICK_AXES_COUNT` is a C preprocessor define, not a makefile variable, so it will not be visible at that level.

**Comment by amrsoll** [comment]
Then I guess it ain't possible to make that work unless we start defining the number of axis in `rules.mk` .. Is that advisable?

**Comment by fauxpark** [comment]
The change doesn't really make much sense anyway as you can configure axes to not read from the ADC with `JOYSTICK_AXIS_VIRTUAL`.

**Comment by zvecr** [comment]
> Is that advisable

Nope, should remain config.h only at the moment.

As I mention, the code causing this issue is going shortly so I dont think we need to go forward with the proposed changes right now.

**Comment by amrsoll** [comment]
> having a count of 0 is not a good metric for whether or not to compile the ADC code.

It is only avoiding compilation of ADC code for the joystick, as the joystick only uses it for reading analog axes. Doesn't prohibit other features from using the ADC.

> As I mention, https://github.com/qmk/qmk_firmware/commit/9a86f5c52281c928c6d590c689f032d0feef876c the code causing this issue is going shortly so I dont think we need to go forward with the proposed changes right now.

Which branch is it part of? GitHub isn't tracking it anymore (rebased) and I can't find it through search

---

Perhaps the joystick buttons should be removed in favour of using programmable buttons? I am trying to use both, but they step on each others toes when trying to use with a flight simulator :roll_eyes:

**Comment by amrsoll** [comment]
Closing as recommended.

**Comment by amrsoll** [comment]
> you can configure axes to not read from the ADC

@fauxpark True, but it still tries to compile it, which can break, unless you explicit that the driver is `digital`, which is a workaround and shouldn't be considered solid because it requires to understand the mechanisms behind.

This PR was aimed at people trying to make a keymap using joystick buttons but no axis, which is indeed particular.

**Pull request closed without merging**
