### PR TITLE
Apollo PCBs EEPROM driver update

### PR DESCRIPTION
**Pull request by Gondolindrim**
## Description

Updates the EEPROM driver for the Apollo PCBs for legacy wear-leveling.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
These should all be default already?

**Comment by tzarc** [comment]
See https://github.com/qmk/qmk_firmware/blob/f21443d6a2be8e2068164f0f3646a175ffed2df4/builddefs/mcu_selection.mk#L371-L373

**Comment by Gondolindrim** [comment]
> These should all be default already?

These changes were not at master; firmware does not compile without those specific lines.

**Comment by Gondolindrim** [comment]
> See
> 
> https://github.com/qmk/qmk_firmware/blob/f21443d6a2be8e2068164f0f3646a175ffed2df4/builddefs/mcu_selection.mk#L371-L373

Interestingly, when I compile without these lines I get errors

**Comment by tzarc** [comment]
You'd have to update your repo -- the code I linked was from current master.

**Comment by Gondolindrim** [comment]
> You'd have to update your repo -- the code I linked was from current master.

Yep, that did it. No need for this PR then, I am closing it

**Pull request closed without merging**
