### PR TITLE
[Split] Ensure SOFT_SERIAL_PIN is defined if USE_I2C isn't defined

### PR DESCRIPTION
**Pull request by drashna**
## Description

If a serial pin isn't defined, and i2c isn't enabled, it gives some esoteric errors. 

This makes sure it errors out in a more obvious way.

## Types of Changes

- [x] Core
- [x] Bugfix

## Issues Fixed or Closed by This PR

* Troubleshooting on discord

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
  - `qmk multibuild -f SPLIT_KEYBOARD=yes` came back with no errors

### CODE REVIEW

**Review by tzarc — APPROVED** [review]
Needs a format, but logic seems fine.

**Comment by mtei** [comment]
I think it is appropriate to do this check in `quantum/split_common/post_config.h`.

```diff
diff --git a/quantum/split_common/post_config.h b/quantum/split_common/post_config.h
index 8f79beb6ed..310a1fc30f 100644
--- a/quantum/split_common/post_config.h
+++ b/quantum/split_common/post_config.h
@@ -8,3 +8,6 @@
 #        define F_SCL 100000UL // SCL frequency
 #    endif
 #endif
+#if !defined(USE_I2C) && !defined(SOFT_SERIAL_PIN)
+#   error USE_I2C or SOFT_SERIAL_PIN are required
+#endif
```

**Comment by drashna** [comment]
> I think it is appropriate to do this check in `quantum/split_common/post_config.h`.

Honestly, I'm not really a fan of that, as that will error out everywhere, basically, since it's a config.h file.  And if you're using the -j switch, you'll see the error repeated a bunch of times

My main concern here is erroring out with a meaningful message, rather than erroring out during linking.  

Though, I'm not sure which option is best, here.

**Comment by mtei** [comment]
> My main concern here is erroring out with a meaningful message, rather than erroring out during linking.

I got it.

Here, there is an implicit assumption that `platforms/avr/drivers/serial.c` is used only with split keyboards.
That's true, but I think it's desirable to show it explicitly.
    
```c
#    if defined(SPLIT_KEYBOARD) && !defined(USE_I2C)
#        error Split keyboards require either SOFT_SERIAL_PIN or USE_I2C　but has not been defined.
#    endif
```

**Comment by drashna** [comment]
That can be done, but it should probably be done to all of the serial implementations for split serial, which is out of scope for this PR (and  is something that should target develop, specifically).

**Pull request merged**
