### PR TITLE
Add support for STM32L432, STM32L442.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

Adds support for STM32L432, STM32L442. Also adds a working `handwired/onekey/nucleo_l432` test board, confirmed with hardware.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — APPROVED** [review]

**Comment by vinorodrigues** [comment]
hey @tzarc - i ran into issues.  quite bad ones:  i've reported in on #16031 - but going forth i have no means to help here, as the one and only q1 i have is now departed the electrosphere. :( 

thanks for trying though ... your lack of arrogance is impressive to me ... more ppl. should be like you in helping outside their own interests.  know you are appreciated.

**Comment by lokher** [comment]
This a bug in upstream chibios of STM32L432, gpio PH3 can not function as GPIO due to missing `RCC_AHB2ENR_GPIOHEN` in stm32_registry.h. The chibios forum is unaccessable now , I can't submit the bug.

**Comment by vinorodrigues** [comment]
Possibly related to #14280 ?

**Comment by lokher** [comment]
> Possibly related to #14280 ?

Absolutely same issue. I submitted a bug report to chibios forum, hope it will be fixed asap.

**Pull request merged**
