### PR TITLE
Support renaming of user RGB matrix custom include file

### PR DESCRIPTION
**Pull request by filterpaper**
## Description

As titled, allow users to change the name and location of `rgb_matrix_user.inc`.

## Types of Changes

- [x] Core
- [x] New feature
- [x] Enhancement/optimization
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Honestly, I'm not really sure how useful this is, since the compiler looks at the virtual paths, so as long as the rule is enabled, and the file is named correctly, it should pick up the file automatically.

**Comment by filterpaper** [comment]
> Honestly, I'm not really sure how useful this is, since the compiler looks at the virtual paths, so as long as the rule is enabled, and the file is named correctly, it should pick up the file automatically.

It is meant to support management of a large userspace or keymap folder, where functional files are placed in subdirectories, like `#define RGB_MATRIX_CUSTOM_USER_INC "rgb/rgb_matrix_user.inc"`

**Comment by drashna** [comment]
> > Honestly, I'm not really sure how useful this is, since the compiler looks at the virtual paths, so as long as the rule is enabled, and the file is named correctly, it should pick up the file automatically.
> 
> It is meant to support management of a large userspace or keymap folder, where functional files are placed in subdirectories, like `#define RGB_MATRIX_CUSTOM_USER_INC "rgb/rgb_matrix_user.inc"`

Alternatively, you could add `VPATH += $(USER_PATH)/rgb` to your rules, and accomplish that as well.

**Comment by filterpaper** [comment]
`VPATH` works for as well. I'll close this PR if it adds unnecessary complexity to an eccentric use-case.

**Comment by drashna** [comment]
> `VPATH` works for as well. I'll close this PR if it adds unnecessary complexity to an eccentric use-case.

I'd say let others weigh in on this, first.

**Comment by zvecr** [comment]
+1 to keeping the filename the same, it gives something consistent to search the repo for.

**Pull request closed without merging**
