### PR TITLE
Adds .qmk file type as a target for QMK Toolbox

### PR DESCRIPTION
**Pull request by jackhumbert**
Building with the `qmk` target (i.e. `make planck:default:qmk`) will generate a .qmk file that contains the .hex (named firmware.hex), along with all the contents of the keymap/*keymap* folder, for reading by the firmware flasher.

---

This is now for the Toolbox, not the flasher :)

### CODE REVIEW

**Comment by NoahAndrews** [comment]
Can we agree not to merge this until we have a version of the flasher that makes use of it? That will also give us an opportunity to make sure the info file contains all of the information we want to use in the flasher.

**Comment by jackhumbert** [comment]
Sure! :)

**Comment by NoahAndrews** [comment]
Idk if you've already thought of this, but the format should include the flash capacity of the MCU, so that we can alert the user beforehand if the file is too big to flash successfully.

**Comment by jackhumbert** [comment]
I think I messaged you about this, but for posterity, we talked about the app handling that side of things, right?

**Comment by NoahAndrews** [comment]
Yep, that's right.

**Comment by jackhumbert** [comment]
We make use of this in the Toolbox, and `info.json` will be the info file for keyboards, so I'm comfortable merging this now.

**Pull request merged**
