### PR TITLE
Update feature_advanced_keycodes.md

### PR DESCRIPTION
**Pull request by kdb424**
Probably a better way to word it, but I've solved this issue on reddit several times, had to solve this for friends, ect. It's something worth being in the docs as it's a common issue, and not always intuitive. I have offered this change as I was told by several people "It was never mentioned in the docs".

### CODE REVIEW

**Comment by kdb424** [comment]
I'd also like to note that this is stated in the advanced section, but isn't something that is super clear, and most people assume that switching layers is not an advanced thing, and is likely to get skipped over, especially when not stated so clearly. If nothing else, I'd like to see more clarity to reduce the time spent on debugging layout issues, which is the whole point of docs.

**Comment by fauxpark** [comment]
The description for `MO()` in the full keycode list (`keycodes.md`) does note that the key on the destination layer must be transparent, however it is kind of tucked away, and is only partly true - all the keys at the same spot _on every layer up to and including_ the destination layer must be transparent. Could be a source of confusion for people doing `MO(2)` from layer 0, but I suspect most fill their empty keycode slots with transparent anyway (I don't).

**Comment by kdb424** [comment]
I would agree that some people do, but this is a common problem on reddit still and one that I and friends had when getting into this. While I agree that we shouldn't need to do this, that's what docs are for. Making it clear how to use the software, and preventing us from taking our time to fix their issues if it could have been fixed by reading the docs quickly. If this was a more advanced feature, I'd probably just have left it alone, but switching layers is something most users do, and therefor it comes up often.

**Comment by fauxpark** [comment]
No, I was agreeing with you, but pointing out that just placing `KC_TRNS` at the same spot on the destination layer is only half the story. For example, in a keymap with three layers, the key needs to be transparent on both layer 1 and 2 so it falls through back to the `MO(2)` on layer 0. I was just saying that I fill my empty slots on higher layers with `KC_NO` to prevent alpha keys etc. leaking into my function layer, instead of `KC_TRNS` which I think is probably the norm and often has the side effect of avoiding that particular issue.

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
