### PR TITLE
Adding few Korean translated files

### PR DESCRIPTION
**Pull request by SeungheonOh**
Korean Translation

## Description

Just adding few Korean translated files, planning to translate more documentations to korean

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My change requires a change to the documentation.
- [ ] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
I think these should be under the subfolder `ko` or `ko-kr`, if we're using ISO 639-1 `kr` is not Korean: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by drashna** [comment]
@jackhumbert

**Comment by SeungheonOh** [comment]
> I think these should be under the subfolder `ko` or `ko-kr`, if we're using ISO 639-1 `kr` is not Korean: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

Gotcha, I'll fix it this afternoon!

**Comment by SeungheonOh** [comment]
Directory name have been updated. As well as full translation of 'getting_started_build_tools.md'

**Comment by SeungheonOh** [comment]
getting_started_getting_help.md and getting_started_github.md have also translated
: )

**Comment by tzarc** [comment]
Two approvals, assuming this is all good.

**Pull request merged**
