### PR TITLE
Port SPLIT_USB_DETECT to helix/rev2

### PR DESCRIPTION
**Pull request by stormbard**
## Description

This PR adds SPLIT_USB_DETECT support for those users having issues with Elite-C V3s.
Copied from PR https://github.com/qmk/qmk_firmware/pull/7195

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Tagging @mtei @MakotoKurauchi
While there are long term plans to move to split_common, any issues with this change? I will really help with some of the reported issues we are seeing!

**Comment by mtei** [comment]
Currently, I am suggesting MakotoKurauch to change Helix to use oled_driver.c instead of ssd1306.h.  At the same time, I am preparing for the transition to split_common.  
https://github.com/MakotoKurauchi/qmk_firmware/pull/24

This PR may conflict with the above changes. So please don't do this PR yet.

**Comment by mtei** [comment]
This PR adds `bool is_keyboard_master(void)` to `keyboards/helix/rev2/split_util.c`.
Doing so will cause problems with the operation of RGB light. The right half rgb light mode will not be changed.

**Comment by zvecr** [comment]
@mtei There are users currently suffering issues so I would rather push for this to go in.

split_common generally needs extra work to make it compatible, such as syncing matrix state. This will take extra time to review and merge.

As for adding `is_keyboard_master`, that wont break anything within rgblight as its not like we can check if the symbol is defined.

**Comment by mtei** [comment]
> As for adding `is_keyboard_master`, that wont break anything within rgblight (its not like we are in a language where we can check if the symbol is defined).

Now I did the following:

```
git fetch qmk pull/7385/head:x
git checkout x
make helix/rev2/back:five_rows:avrdude-loop
```

And I tried RGB_TOG key, RGB_MOD key.
The master side worked correctly.
On the slave side, the LED cannot be turned on/off. mode does not change.

**Comment by zvecr** [comment]
Is it this block that is in play then?
https://github.com/qmk/qmk_firmware/blob/46d0fe44f357f0435d3335cbe5e361324d4236f6/tmk_core/common/keyboard.c#L288-L316

Where the default implementation of is_master currently always returns true.

**Comment by zvecr** [comment]
@stormbard can you copy in the latest updated found within #7404, this *should* fix keycode processing and potentially unblock this PR.

**Comment by stormbard** [comment]
@zvecr I can push the changes but in my testing locally on my helix the right hand LEDs do not toggle off when the toggle key is pressed. Doesn't matter which one is master in this case.

I'm also still seeing some intermittent issues with the halves communicating. I'm not sure if this is due to a firmware or hardware issue though and will take suggestions for debugging.

**Comment by zvecr** [comment]
It sounds like a hardware issue, though I don't have anything on hand to verify that is the case.

Does reverting the suggestions within #7404 make it work again?

**Comment by stormbard** [comment]
Didn't work before or after the changes in #7404.

**Comment by stormbard** [comment]
After some further testing I believe this change is good. I'm able to get the backlighting to work on both halves as I'd expect.

**Comment by mtei** [comment]
Since the 'xulkal' keymap was not working, So I made a patch.
https://github.com/mtei/qmk_firmware/commit/61350f4ec4d780454a1fb1ab9ed8faabee5c79f0
Would you like try it?

**Comment by zvecr** [comment]
> the 'xulkal' keymap was not working.

Can you elaborate further on what the issue is please. The keymap compiles fine, and that suggestion is rather involved to see what the actual problem issue is.

**Comment by XScorpion2** [comment]
You can probably ignore, 'xulkal', helix keymap, I haven't used that board in a while, and usually have a quick turn around on fixing my own keymaps. Though I always do appreciate a heads up when one of my keymaps break.

**Comment by zvecr** [comment]
@mtei I don't see any of those changes being a hard requirement for this PR:

1. removing `has_usb` potentially breaks backwards compatibility
2. moving `is_master` just adds code churn, and these short term fixes tend to aim for minimal change
3. adding `is_keyboard_master` goes back to #7404 where it will break previous assumptions, though as per that PR, its only an issue if included in `tmk_core/common/keyboard.c` which the proposed rev2.h currently isn't unless a user adds in within their keymaps config.h path
4 serial.c and its compilation in this PR remains unchanged so should be considered out of scope
5. xulkal keymaps implementation of `is_keyboard_master` should remains unchanged as the underpinning `is_master` bool it depends on has the same behaviour as before

Though if you do want to propose some of those changes, feel free to raise a separate PR.

**Comment by mtei** [comment]
> 3. adding `is_keyboard_master` goes back to #7404 where it will break previous assumptions, though as per that PR, its only an issue if included in `tmk_core/common/keyboard.c` which the proposed rev2.h currently isn't unless a user adds in within their keymaps config.h path
>    4 serial.c and its compilation in this PR remains unchanged so should be considered out of scope

I'm not good at English. This sentence was too long for me to understand. So I can't comment, sorry.

However, I have confirmed that my patch has been tested and works correctly with all keymaps. Don't forget it.

> 4. xulkal keymaps implementation of `is_keyboard_master` should remain unchanged as the underpinning `is_master` bool it depends on has the same behaviour as before

'helix:xulkal' has problems similar to those solved by #7404. Currently, 'helix:xulkal' can be compiled but is not working properly. If you want 'helix:xulkal' to work correctly, you need to fix it.

I checked the operation before and after applying my patch. It has been confirmed that it will not work properly before the patch is applied. It has been confirmed that it works correctly after applying the patch.

However, the 'helix:xulkal' problem is certainly outside the scope of this PR.
I will open a new PR after this PR has been merged.

**Comment by mtei** [comment]
Of course I don't care if my patch was not included in this PR.  Either way, I approve this PR. However, my patch above will be needed for backward compatibility when Helix changes to use split_common in the future.

> 1. removing `has_usb` potentially breaks backwards compatibility
> 2. moving `is_master` just adds code churn, and these short term fixes tend to aim for minimal change

'is_master' and 'has_usb()' must not be removed for backward compatibility. You say my patch breaks backward compatibility, which is a misunderstanding. My patch keeps backward compatibility better than the current code of this PR.

The current code for this PR causes problems when changing Helix to use split_common. My patch avoids that problem.

**Comment by zvecr** [comment]
> My patch keeps backward compatibility better than the current code of this PR
That is a bit of an abstract statement, can you provide an example where this PR breaks backwards compatibility?

**Comment by mtei** [comment]
To reiterate what I already wrote above, in this PR's current code, 'is_master' is in 'helix/rev2/matrix.c' and 'has_usb()' is in 'helix/It is in rev2/split_util.c'.
If Helix uses split_common, the two files will not be linked.

**Comment by zvecr** [comment]
But thats not a backwards compatibility issue.

As there are none being raised, im going to merge this as is.

**Comment by zvecr** [comment]
Cheers for your work @stormbard!

**Pull request merged**
