### PR TITLE
Remove MATRIX_IS_ON macro

### PR DESCRIPTION
**Pull request by xyzz**
this macro is both incorrect and excessive given that macro_is_on()
exists

## Description

The macro is incorrect as it uses && while it should be using &. It is not used by any code.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by tzarc — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]
This can go straight into master and the alt and ctrl `matrix.h`s can be deleted, otherwise ✔️

**Comment by tzarc** [comment]
Good point, rebasing on master will clear it up. It'll auto-merge to develop afterwards. Swapped the target branch.

**Review by tzarc — CHANGES_REQUESTED** [review]
Just holding on the rebase, so nobody else merges.

**Review by fauxpark — CHANGES_REQUESTED** [review]
Massdrop matrix.h's can be completely removed.

**Review by fauxpark — APPROVED** [review]

**Review by zvecr — APPROVED** [review]

**Comment by zvecr** [comment]
Thanks!

**Pull request merged**
