### PR TITLE
ChibiOS upgrade: configuration file migrator

### PR DESCRIPTION
**Pull request by tzarc**
## Description

To facilitate the migration to newer versions of ChibiOS, we need to migrate to a "minimal" configuration file format, specifically to make the keyboards immune to version upgrades of the base ChibiOS.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Something funky when trying to build the `hadron/ver3`:
```sh
qmk chibios-confmigrate -i keyboards/hadron/ver3/chconf.h -r platforms/chibios/GENERIC_STM32_F303XC/configs/chconf.h -o
qmk chibios-confmigrate -i keyboards/hadron/ver3/halconf.h -r platforms/chibios/GENERIC_STM32_F303XC/configs/halconf.h -o
qmk chibios-confmigrate -i keyboards/hadron/ver3/mcuconf.h -r platforms/chibios/GENERIC_STM32_F303XC/configs/mcuconf.h -o
make hadron/ver3:default
```

**Comment by tzarc** [comment]
Subtle issue with `halconf.h`:
https://github.com/qmk/qmk_firmware/blob/develop/platforms/chibios/GENERIC_STM32_F303XC/configs/halconf.h#L34

Needs to be modified in the following way to get the include paths to consider the keyboard directory:
```diff
--- a/platforms/chibios/GENERIC_STM32_F303XC/configs/halconf.h
+++ b/platforms/chibios/GENERIC_STM32_F303XC/configs/halconf.h
@@ -31,7 +31,7 @@
 #define _CHIBIOS_HAL_CONF_
 #define _CHIBIOS_HAL_CONF_VER_7_0_

-#include "mcuconf.h"
+#include <mcuconf.h>

 /**
  * @brief   Enables the PAL subsystem.
```

**Comment by tzarc** [comment]
Part of #8976.

**Review by fauxpark — APPROVED** [review]

**Comment by tzarc** [comment]
So far, this has been working fine, in that it's been able to run through the entirety of #10418 without issue.

**Pull request merged**
