### PR TITLE
Adjustments to Gust Rev1.2

### PR DESCRIPTION
**Pull request by eithanshavit**
## Description

Adding another row to Gust Rev1.2. This is backwards compatible for previous revisions.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by eithanshavit** [comment]
Looking for some eyes on this please. 🙏

**Review by fauxpark — APPROVED** [review]

**Comment by drashna** [comment]
Since this is changing the keyboard config, significantly, it should probably target develop.

**Comment by eithanshavit** [comment]
@drashna, would you please explain what you mean by target develop?

**Comment by drashna** [comment]
Eg, the PR should target the `develop` branch, rather than `master`.  This can be done by clicking on the "Edit" next to the title, and then there should be a dropdown under the title to change the branch.

**Comment by eithanshavit** [comment]
@drashna, I'm not sure this is the intention here. Even though there are changes to the keyboard config, non of these changes are breaking, and no negative impact will be on any user current or previous. This is because all of these changes are fully backward compatible with previous revisions.

**Comment by eithanshavit** [comment]
Hi @drashna, wondering if you have more thoughts on my previous text. This change I'm suggesting here is suitable for all current users of this board, and many are waiting for this to merge so they can fully customize their keys. Thoughts?

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
