### PR TITLE
Add Guix manifest

### PR DESCRIPTION
**Pull request by ekaitz-zarraga**
Add guix manifest to make guix environments like `guix environment --manifest=guix-manifest.scm`

- It's not configurable at the moment.
- AVR-Toolchain is 4.9 version because 5.5 package is broken, see [help-guix mailing list](https://lists.gnu.org/archive/html/help-guix/2020-02/msg00195.html)

### CODE REVIEW

**Comment by drashna** [comment]
Doesn't have the 5.4 or 6.3 package available?

**Comment by ekaitz-zarraga** [comment]
A search returns only those (see below)
We can fix the package description of the 5.5 and make it available but it's not ready yet.

``` bash 
$ guix package --search=avr-toolchain

name: avr-toolchain
version: 5.5.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: avr-binutils@2.32 avr-gcc@5.5.0 avr-libc@2.0.0 avrdude@6.3
location: gnu/packages/avr.scm:121:4
homepage: https://www.nongnu.org/avr-libc/
license: GPL 3+
synopsis: Complete GCC tool chain for AVR microcontroller development  
description: This package provides a complete GCC tool chain for AVR
+ microcontroller development.  This includes the GCC AVR cross compiler
+ and avrdude for firmware flashing.  The supported programming languages
+ are C and C++.
relevance: 20

name: avr-toolchain
version: 4.9.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: avr-binutils@2.32 avr-gcc@4.9.4 avr-libc@2.0.0 avrdude@6.3
location: gnu/packages/avr.scm:121:4
homepage: https://www.nongnu.org/avr-libc/
license: GPL 3+
synopsis: Complete GCC tool chain for AVR microcontroller development  
description: This package provides a complete GCC tool chain for AVR
+ microcontroller development.  This includes the GCC AVR cross compiler
+ and avrdude for firmware flashing.  The supported programming languages
+ are C and C++.
relevance: 20
```

**Comment by drashna** [comment]
My concern here is that the 4.9 version is very old, and may be too old.  And I'm not even sure about the 5.4 version.

**Comment by ekaitz-zarraga** [comment]
We are currently working on a fix for 5.5 and working on an update of the avr-toolchain. You can see the discussion here:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=39794

I hope we'll have a patch in the next weeks at least for 5.5. There's already a patch that fixes the issue, so we'll push it as soon as we can.

**Comment by Erovia** [comment]
@ekaitz-zarraga I'm not familiar with Guix, is there any reason the latest 8.x version cannot be built/packaged for it?

**Comment by ekaitz-zarraga** [comment]
> @ekaitz-zarraga I'm not familiar with Guix, is there any reason the latest 8.x version cannot be built/packaged for it?

Just bad packaging on Guix's side. This patch is supposed to solve it, but it's not merged yet.
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=39918

**Comment by bricewge** [comment]
On master `docs/getting_started_build_tools.md` has been deleted in https://github.com/qmk/qmk_firmware/pull/8252. The documentation should probably go elsewhere or https://github.com/qmk/qmk_firmware/commit/d1c18086d23c1f510ee434e1aa12b203f36e4794 should be partially reverted before merging this pull request.

**Comment by bricewge** [comment]
@ekaitz-zarraga Could you remove `arm-none-eabi-toolchain` since [it conflict](https://issues.guix.info/issue/39794#8) with `avr-toolchain`? You can also drop the version specification for `avr-toolchain`, [5.5 is working](https://issues.guix.info/issue/24416#6) correctly now and adding `python` silence the warning “Python 3 is not installed. [...]”.

With these modifications I was able to successfully build `helix/rev2` as well as `40percentclub/luddite`.

**Comment by ekaitz-zarraga** [comment]
@bricewge Did what you proposed but arm toolchain is supposed to be used by other parts of the project so the manifest proposed here is only going to be unusable for some keyboards (I think).

**Comment by bricewge** [comment]
Thanks @ekaitz-zarraga that was quick! BTW it's `python` instead of `python3`.

Do you have any example of such a keyboard?

**Comment by ekaitz-zarraga** [comment]
@bricewge done.

I don't have any in mind but if that's part of the projects requirements it should be for a reason. :)

**Comment by fauxpark** [comment]
We use the ARM toolchain to build firmware for STM32 microcontrollers (and some NXP chips used by the ARM Teensys, and the ATSAMD51J18A that the Massdrop boards have) using ChibiOS' HAL. If there is a conflict between it and the AVR toolchain that will need to be fixed upstream.

**Pull request closed without merging**
