### PR TITLE
Support IS31FL3741 and IS31FL3741A.

### LINKED ISSUE #6101: add support for IS31FL3741
## Feature Request Type

- [ ] Core functionality
- [x] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

QMK uses the RGB matrix and supports IS31FL3731, 3733, 3736, and 3737.

But those four ICs support less than 100 keys of RGB.

The IS31FL3741 from the same company supports 117 RGB LEDs.

This means that you can add RGB to a single IC on a 104- to 108-key keyboard

Can you add support for IS31FL3741?

I usually use a full size keyboard.

Using multiple ICs complicates the design.

### PR DESCRIPTION
**Pull request by melgeek001365**
## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Closes #6101

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Please do not close this PR, you are making it more difficult to review.

You may be asked to make changes, which you can do either by accepting the suggestions a reviewer may make, or by committing and pushing to the `melgeek` branch. There is no need to close and reopen it every time.

**Comment by melgeek001365** [comment]
> Please do not close this PR, you are making it more difficult to review.
> 
> You may be asked to make changes, which you can do either by accepting the suggestions a reviewer may make, or by committing and pushing to the `melgeek` branch - the PR will be updated here with the additional commits. There is no need to close and reopen it every time.

BTW, I have two commits with the melgeek branch. but it will be merge one PR with two commits automatically. how can I handle it ?

**Comment by fauxpark** [comment]
You will need to create a separate branch and PR for the keyboard addition.

**Comment by melgeek001365** [comment]
> You will need to create a separate branch and PR for the keyboard addition.

OK. Thank you very much! I will do it.

**Comment by fauxpark** [comment]
Don't branch off of the `melgeek` branch, go back to `master` and create the branch from there:
```
master
     |---> melgeek
     \---> z70ultra
```
For example.

**Comment by melgeek001365** [comment]
> Don't branch off of the `melgeek` branch, go back to `master` and create the branch from there:
> 
> ```
> master
>      |---> melgeek
>      \---> z70ultra
> ```
> 
> For example.

Done. Thank you! but I think the Travis CI will be failed.

**Comment by rea104** [comment]
Hello, IS31Fl3741 has an Open/Short detection functionality. Has anyone tried it?

**Comment by elfmimi** [comment]
@rea104 it is okay to start a new issue if it is a technically reasonable one like this. so please don't post it randomly.

**Comment by myst729** [comment]
@melgeek001365 I have read your Z70Ultra firmware, and I noticed that [you defined 1 driver and 2 driver addresses](https://github.com/melgeek001365/qmk_firmware/blob/master/keyboards/melgeek/z70ultra/config.h#L48-L49) (same value) for **compliancy reasons**, which is not explained anywhere else. And what addresses are available (since each driver is a little different from others)?

I'm trying to drive an [Adafruit IS31FL3741 breakout board](https://www.adafruit.com/product/5201) (open sourced [here](https://github.com/adafruit/Adafruit-IS31FL3741-PCB)) with a Pro Micro via I2C, but with no luck. Could you add a doc section in [RGB Matrix Lighting](https://docs.qmk.fm/#/feature_rgb_matrix) page?

**Pull request merged**
