### PR TITLE
CLI: Parse USB device version BCD

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

`DEVICE_VER` is a BCD value in the format `MMmr`. This enhances the mapping between `info.json` and `config.h` from a simple 4 digit hex number to a version string.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
There are a handful of boards with `DEVICE_VER` digits > 9, these throw up a warning in `qmk info`:
```
⚠ 40percentclub/25: DEVICE_VER->usb.device_ver: invalid literal for int() with base 10: '0F'
```
```
40percentclub/25
40percentclub/5x5
40percentclub/6lit
40percentclub/foobar
40percentclub/half_n_half
boston_meetup/2019
coarse/ixora
coarse/vinta
handwired/qc60
lets_split_eh
ramonimbao/squishytkl
spacetime
```

**Comment by fauxpark** [comment]
Last failing test is expected, due to the boards listed above which have invalid digits.

**Review by tzarc — APPROVED** [review]
If we can fix up the conflicts, this can go in.

**Review by drashna — APPROVED** [review]

**Comment by Sasasu** [comment]
Hi here, 

I think the hardware revision is different from the software version.
hardware revision usually means different hardware with different functions, eg: rev-A uses a knob to adjust volume, rev-B uses a photoresistor to adjust RGB brightness. they are different functions but share the same ADC resource, which does not mean rev-B is better than rev-A.

and, alphabet is often used just so as not to mislead people, BCD version in hexadecimal is also very strange.
```c
major = int(info_data['usb']['device_ver'][2:4])
minor = int(info_data['usb']['device_ver'][4])
revision = int(info_data['usb']['device_ver'][5])
```

**Comment by fauxpark** [comment]
I'm not sure what you mean. You can see here, and in the actual USB spec, that this value is indeed BCD and should be treated as such: https://www.beyondlogic.org/usbnutshell/usb5.shtml#DeviceDescriptors

Therefore, digits greater than 9 are not allowed.

**Pull request merged**
