### PR TITLE
Brightness up/down

### PR DESCRIPTION
**Pull request by grota**
Hi there guys!
I was just wondering if you were willing to accept this contribution.
I'm using it on my fork and even if I found out the numeric values on a MS webpage they work also on linux (I don't know about Mac OS though)

### CODE REVIEW

**Comment by Wilba6582** [comment]
Since these were added to the end of that keycode range, it won't affect dynamic keymaps 👌

**Comment by grota** [comment]
I fixed the `#define IS_CONSUMER(code)        (KC_MUTE      <= (code) && (code) <= KC_BRID)` but it still does not work

**Comment by drashna** [comment]
Did you add the keycode to: https://github.com/qmk/qmk_firmware/blob/39bd760faf2666e91d6dc5b199f02fa3206c6acd/tmk_core/common/report.h#L171

**Comment by grota** [comment]
yeah, that's in the PR, I also figured out that I needed to fix the IS_CONSUMER define as per my commend above (not yet in the PR) but oddly enough it still doesn't work (xev does not show anything).
KC_BRIGHTNESS_DOWN should have the 0xBE value in the enum (so it should be ok).
I'm lost for now. Since the custom keycodes work even by calling
```
      if (record->event.pressed) {
        register_code(KC_BRIU);
      }
      else {
        unregister_code(KC_BRIU);
      }
```
I think it's something in the core that is not liking it...

**Comment by fauxpark** [comment]
You also need to change the `KC_MEDIA_REWIND` in [keymap_common.c](https://github.com/qmk/qmk_firmware/blob/master/quantum/keymap_common.c#L67) 👍

**Comment by grota** [comment]
damn it! :smile:  that was it! I should have been able to realize it, thanks though! I force-pushed it. I'll go ahead and update the docs too.

**Comment by drashna** [comment]
Travis CI errors are unrelated (size issues due to feature creep)

**Comment by grota** [comment]
docs added, for me it's good

**Comment by fauxpark** [comment]
Could you also add which OSes these keycodes work on to the docs? I can test macOS later today if you need.

**Comment by grota** [comment]
I'm going to sleep now, I'll do it tomorrow, but I tested windows and Linux.
Thanks for testing osx.
Btw, I stumbled on those 2 magic numbers on that Microsoft page i linked in the PR, just out of curiosity, is there a comprehensive list of those numbers accross OSes?
I kinda expected to find it for Linux but I got nothing.

**Comment by fauxpark** [comment]
[This page](https://www.usb.org/hid) lists all of the usages that the USB-IF recognises (the brightness controls are part of [review request 41](https://www.usb.org/sites/default/files/hutrr41_0.pdf)), but as far as OS support I'm not aware of anything like that. At least for Linux, if you were so inclined you can always dive into the code :P

**Comment by fauxpark** [comment]
Okay, I can confirm it works on High Sierra and Mojave, so I'd say that's a yes for macOS.

**Comment by drashna** [comment]
@ezuk I always check the travis log for why the failures occur. 

This one is due to feature creep, as a couple of vusb boards are over size by about 10 bytes.  I have a PR that disables mouse keys to help prevent this for a while, by disabling mousekeys. 

https://github.com/qmk/qmk_firmware/pull/4502

@fauxpark awesome, thanks for testing that!

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
