### PR TITLE
Move CORTEX_ENABLE_WFI_IDLE=TRUE to rules.mk files

### PR DESCRIPTION
**Pull request by tzarc**
## Description

The ChibiOS upgrade branch utilises scripts provided in their repo for updating the respective conf.h files.
It seems as if there's been a fair bit of copy/paste going on with respect to configurations, and the flag `CORTEX_ENABLE_WFI_IDLE=TRUE` has been replicated in a lot of places.
Unfortunately executing the upgrade scripts nukes this definition in the conf files. After discussion on Discord with @zvecr it seemed like splitting this out into rules.mk would make the upgrade review process smoother.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
New conflicts fixed up.

**Comment by tzarc** [comment]
@adrientetar @TerryMathews @awkannan @Codetector1374 @belak @coarse

Apologies for the pings, just looking for confirmation that you all have no objections to these changes.
It's preparation for the ChibiOS upgrade, and should have no discernible effect to your boards.

**Comment by TerryMathews** [comment]
No objection here.

**Comment by Codetector1374** [comment]
Looks good to me

**Comment by coarse** [comment]
LGTM! :+1:

**Comment by awkannan** [comment]
Looks good to me!

**Pull request merged**
