### PR TITLE
Add model01 keymap. Change kinesis keymap.

### PR DESCRIPTION
**Pull request by tw1t611**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
Travis CI errors are unrelated to these changes.

**Comment by tw1t611** [comment]
It seems like the CI failed to docs generation.
I did no changes to the firmware itself.
Is it possible to merge anyway?

**Comment by noroadsleft** [comment]
Yes, it's possible; I was just hoping someone else would chime in as to why Travis decided to check the whole repository on this PR when it only has two keymaps.

Looking into this, it seems it's because your source branch isn't in sync with qmk:master. This is the "This branch is 1 commit ahead, 73 commits behind qmk:master." message that [appears on your branch](https://github.com/tw1t611/qmk_firmware/tree/add-model01-tw1t611), and so Travis is seeing changes to a lot more files than you have actually changed (about 650).

I thought it might have been a CI glitch, but it seems to be more of a case of unusual integration.

Tested the changes on a rebased branch and everything looks good.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
