### PR TITLE
Lets split readme eeprom master hand fixes

### PR DESCRIPTION
**Pull request by jimmyhchan**
Please see the 3 individual commits. 

Fix EEPROM values
* update the EEP files to show up at addr 0x0a (decimal 10).  if you compare split_util.h with the original project by ahtn, the address we look for isLeftHand config went from addr 7 to addr 10   (decimal). The EEP files were not updated.
* do not default EE_HANDS for the serial keymap
    EE_HANDS should not be enabled by default since it's more confusing for most users
* rewrite the readme to explain EE_HANDS better and what happens by defualt with hasUsb
* rewrite the readme to be QMK specific take out references that would require the Makefile of the original ahtn repo. 
* renamed I2C_MASTER_RIGHT to MASTER_RIGHT since this'll work for serial as well. kept the check in place for backwards compatibility

### CODE REVIEW

**Comment by nicinabox** [comment]
This is fantastic! Great catch on the EEP files.

**Comment by TerryMathews** [comment]
Glad you got this sorted. I tried to follow the code and figure out why the serial EEPROM files weren't doing anything and finally threw my hands up in frustration.

**Comment by nicinabox** [comment]
Flashed mine with this branch and everything went great 👍

**Comment by nicinabox** [comment]
@jimmyhchan would you mind updating the readme to include the changes from #1036 and #1053?

**Comment by jimmyhchan** [comment]
I'll get to it tonight.

**Comment by jimmyhchan** [comment]
got my code rebased. Should be ready to merge.  Here's the readme updated too in case anyone wants to proof-read / suggest edits.
https://github.com/jimmyhchan/qmk_firmware/blob/fixSplit/keyboards/lets_split/readme.md

**Comment by jackhumbert** [comment]
Great - thanks! :)

**Comment by TerryMathews** [comment]
Is setting rev2 as SUBPROJECT_DEFAULT really desirable?

**Pull request merged**
