### PR TITLE
Prevent clang-format messing up placeholder tokens within keyboard templates

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

This should hopefully prevent clang-format messing up the placeholder tokens...

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Yeah... actually it will happily format .template files, it is apparently smart enough to recognise C code in there.

Possibly adding `--exclude='*.template'` to the grep in travis_compiled_push.sh would help.

**Comment by noroadsleft** [comment]
@skullydazed please advise.

**Comment by fauxpark** [comment]
Maybe it would be easier to just move the template dir out of quantum and into util?

**Comment by skullydazed** [comment]
I think we'd be better off to switch to `qmk cformat` which handles these details for us. It already limits formatted files to .c, h, and .cpp.

**Comment by fauxpark** [comment]
This should be a much simpler change now. Undid the .template file extension - I *think* all that's needed is to `grep -v 'quantum/template'` in travis_compiled_push.sh.

**Pull request merged**
