### PR TITLE
Enable de-ghosting for RGB/LED matrix on all ISSI LED drivers

### PR DESCRIPTION
**Pull request by donicrosby**
Take two of #14281 

## Description
Currently RGB/LED matrixes for the various ISSI ICs have ghosting issues with the LEDs. Any LEDs used as indicators or just plain off in the matrix glow faintly which isn't ideal. I have added a option to be set in a keyboards config.h that allows for makers and users to enable the de-ghosting functions of the ICs for all of the drivers on the board so that this ghosting is eliminated.

I have set the default value to allow for ghosting (0 ohm resistor/de-ghosting settings off) so as to stay backwards compatible and not cause power issues with older boards.

The datasheet recommends enabling the highest resistor possible during the blanking time so there shouldn't be any dimming with the LEDs when they are on. If you want me to set that as the default (would make sense that you wouldn't want ghosting on the matrix) I can do that as well.

## Types of Changes

- [x] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
No support for the 3731?  (I'm pretty sure the answer is no).

Also, the 3218?

**Comment by donicrosby** [comment]
Not that I can tell from looking at the datasheets. I didn't see any mention of de-ghosting built into the array.

**Comment by sigprof** [comment]
Actually the [application note for 3731](https://www.lumissil.com/assets/pdf/core/IS31FL3731_AN.pdf) mentions “0xC2 Ghost Image Prevention Register” in section Q20; for some reason the [3731 datasheet](https://www.lumissil.com/assets/pdf/core/IS31FL3731_DS.pdf) does not describe that register.

And 3218 should not need any de-ghosting, because it does not use a LED matrix — it has a dedicated output for each LED.

**Comment by donicrosby** [comment]
Why the hell is that not in the datasheet....

Thanks for the heads up @sigprof, I'll add that in!

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Conflicts need to be resolved, other than that looks fine.

**Pull request merged**
