### PR TITLE
add SPLIT_HAND_PIN_WITH_PULLUP into quantum/split_common/split_util.c

### PR DESCRIPTION
**Pull request by mtei**
## Description
Added SPLIT_HAND_PIN_WITH_PULLUP similar to SPLIT_HAND_PIN.

With SPLIT_HAND_PIN_WITH_PULLUP, the left half does not need to connect the pin to Vcc.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by pelrun** [comment]
This is *really* messy. Just use setPinInputHigh permanently.

If a specific keyboard needs anything weird like a high-Z here, then they can easily override is_keyboard_left. It's marked weak precisely for this reason.

**Comment by mtei** [comment]
> Just use setPinInputHigh permanently.


I do not want to adversely affect the behavior of existing keyboards. So I avoided changing the existing implementation to setPinInputHigh ().

**Comment by zvecr** [comment]
@mtei Would there be an adverse effect, the `readPin` would still read non zero for existing users of `SPLIT_HAND_PIN`?

**Comment by pelrun** [comment]
It can't affect them adversely - the only case which is a problem is one that already isn't supported by the existing code. Keyboards using split pin have to already tie each side to a rail, or take advantage of the previous bug (if it actually resulted in the pullup being enabled) and only tie down the low side.

If there actually are any keyboards that for some weird reason only used a very high value resistor to pull down the low side, then adding yet another config option to handle it is still the wrong way to go about it. The code is already broken for that case *now*, and they should be overriding the function to handle it properly.

**Comment by zvecr** [comment]
I guess my question could be rephrased to "Are there any known boards that will break, if we just swap SPLIT_HAND_PIN to use setPinInputHigh"?

**Comment by mtei** [comment]
In other words, I did not want to change the compilation results of the existing keyboard.

I do not know if the existing keyboard was working correctly or accidentally.
And when I change the source I don't know if something will happen. So I did not want to change the compilation results.

**Comment by zvecr** [comment]
`SPLIT_HAND_PIN` usage in the repo is limited to:
- keebio split boards
- suihankey
- otaku_split
- lets_split_eh

ai03/orbit uses a fork of split common so i have left it out

**Comment by pelrun** [comment]
> I do not know if the existing keyboard was working correctly or accidentally.

That's not a good justification for this sort of design decision.

And as I've already mentioned, the only keyboards which would be broken after changing to `setPinInputHigh` are ones which *already* do not work. Not "only work accidentally", but cannot possibly be working at all. Any that currently "only work accidentally" (if they even exist) are in the group which will be permanently fixed by that change.

**Comment by mtei** [comment]
I think it is safe to go through the following steps.

 * Step 1 Add SPLIT_HAND_PIN_WITH_PULLUP to split_common / split_util.c.
 * Step 2 Try each keyboard user switching to using SPLIT_HAND_PIN_WITH_PULLUP for testing.
 * Step 3 If it is confirmed that SPLIT_HAND_PIN_WITH_PULLUP works for all keyboards, abolish the previous implementation of SPLIT_HAND_PIN and switch to setPinInputHight ().

**Comment by pelrun** [comment]
Except how do you get "each keyboard user" to do that test?

All that will happen is that SPLIT_HAND_PIN_WITH_PULLUP will get stuck in the code and it'll have to be maintained indefinitely.

**Comment by mtei** [comment]
> All that will happen is that SPLIT_HAND_PIN_WITH_PULLUP will get stuck in the code and it'll have to be maintained indefinitely.

Is that really so? Incredible. Even if that happens, I do not think that it is a big problem in this case.

**Comment by zvecr** [comment]
Personally, I would rather just go with the override in <keyboard>.c instead of a convoluted deprecation procedure.

**Comment by mtei** [comment]
Everyone agrees that the current setPinInput (SPLIT_HAND_PIN) is not good, right?

**Comment by nooges** [comment]
Yeah, I tie the read pin to either VCC or GND, and never leave it floating.

**Comment by drashna** [comment]
There are some merge conflicts here.   

However, did we want to close this in favor of previous mentioned solutions?

**Comment by mtei** [comment]
I thought again, but again I disagree with pelrun's opinion of using 'setPinInputHight()' in the SPLIT_HAND_PIN implementation.

I think the choice between using 'setPinInputHigh()' or using 'setPinInput()' should follow the hardware design. However, it is also true that SPLIT_HAND_PIN_WITH_PULLUP is not necessary for now.

So I close this PR.

**Pull request closed without merging**
