### PR TITLE
Updated Info.json for keyboard

### PR DESCRIPTION
**Pull request by WestMProducts**
## Description

Updated info.json to more accurately reflect layout.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — CHANGES_REQUESTED** [review]
Produces the following in lint

```c
Layout Layout_Alice:
                     ┌──┐┌──┐┌──┐┌──┐
                     │k1││k1││k2││k2│
   ┌──┐┌──┐┌──┐┌──┐  └──┘└──┘└──┘└──┘                ┌──┐┌──┐┌──────┐
   │k0││k0││k0││k0│┌──┐┌──┐┌──┐┌──┐                  │k0││k0││k06   │
   └──┘└──┘└──┘└──┘│k2││k2││k2││k2│                  └──┘└──┘└──────┘
  ┌──┐┌────┐┌──┐   └┌──┐┌──┐┌──┐┌──┐                ┌──┐┌──┐┌──┐┌────┐
  │k0││k09 ││k0│    │k2││k2││k2││k2│                │k0││k0││k0││k0d │
  └──┘└────┘└──┘    └──┘└──┘└──┘└──┘                └──┘└──┘└──┘└────┘
 ┌──┐ ┌─────┐┌──┐     ┌──┐┌──┐┌──┐┌──┐                ┌──┐┌──┐┌───────┐
 │k0│ │k10  ││k1│     │k2││k2││k2││k2│                │k1││k1││k14    │
 └──┘ └─────┘└──┘     └──┘└──┘└──┘┌──┐┌──┐┌──┐┌──┐    └──┘└──┘└───────┘
     ┌───────┐┌──┐         ┌──────│k3││k3││k3││k3│   ┌──┐┌──┐┌─────┐┌──┐
     │k15    ││k1│   ┌────┐│k31   └──┘└──┘└──┘└──┘   │k1││k1││k1a  ││k1│
     └───────┘└──┘   │k33 │└─────┌──┐┌──┐┌──┐┌──┐    └──┘└──┘└─────┘└──┘
     ┌────┐          └────┘      │k3││k3││k3││k3│               ┌────┐
     │k1c │                      └──┘└──┘└──┘└──┘               │k1d │
     └────┘                      ┌──┐┌──┐┌──┐┌──┐               └────┘
                                 │k3││k3││k3││k4│
                                 └──┘└──┘└──┘└──┘
                               ┌──┐┌──┐┌──┐┌──┐
                               │k4││k4││k4││k4│
                               └──┘└──┘└──┘└──┘
                               ┌─────────┐ ┌────┐
                               │k4b      │ │k4f │
                               └─────────┘ └────┘
                               ```

**Comment by WestMProducts** [comment]
Ahhh, apologies. Was doing this late at night, and I must have copied the incorrect one I was playing around with in.

**Comment by WestMProducts** [comment]
@zvecr Fixed! I somehow forgot to add in ("layout": [)... I should probably stop doing things late at night. Thanks for the catch!

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
