### PR TITLE
Implemented RGBLIGHT_TIMEOUT functionality similar to other timeout features

### PR DESCRIPTION
**Pull request by aashreys**
## Description

Added the ability to define a timeout value for rgblight. Internally it reuses the existing wakeup/suspend functionality but now adds a timer check which runs in QMK's core task loop. If the timer expires then rgblight is suspended and it is woken up on the next keypress, encoder update or wake up call from the connected computer. 

Also updated the rgblight documentation to reflect the new configuration variable introduced in this PR.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR
This PR will address all issues requesting similar features like this one - https://github.com/qmk/qmk_firmware/issues/12920

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by aashreys** [comment]
Hey folks lemme know if I need to make any changes to this PR to get it merged. The feature is very simple and meshes will with the current implementation of rgblight.c. Thanks!

**Comment by zvecr** [comment]
In its current form, this PR cannot be accepted due to the submodule changes in `lib`, most likely from before the previous develop cycle merged.

**Comment by drashna** [comment]
Specifically, this probably needs to be rebased.  

Also, this would need to target the develop branch.

**Comment by aashreys** [comment]
Got it. Lemme see if I can rebase it with the dev branch. Thanks for the quick response.

**Comment by aashreys** [comment]
I've created a new PR (https://github.com/qmk/qmk_firmware/pull/14310) which fixes the issues mentioned in this one. I'm closing this PR now.

**Pull request closed without merging**
