### PR TITLE
Add more "decent" text editors

### PR DESCRIPTION
**Pull request by mvaneijgen**
I'm a web designer and know there are several "decent" code editors out there, but I would figure not everyone into keyboards is, so I found Sublime text a bit of a hard sell for someone who just need to manipulate some text files. VS Code or Atom would b a much better suit for them instead of dropping $80 on a "decent" text editor.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
You don't *need* to buy a Sublime Text license, it will just nag you every 50 or so saves (and honestly, it is not that annoying). So the "(paid)" part is not quite true.

**Comment by mechmerlin** [comment]
lol! I'm sure someone will come along after this fix and say, "hey there are other decent text editors out there", and put in a couple more!

**Comment by mvaneijgen** [comment]
Thats fair, in my eye Sublime is expensive, but the infinite trial is not something I knew. 

@mechmerlin true, but VS Code is also mentioned in the newbs [getting started guide](https://docs.qmk.fm/#/newbs_getting_started), so it's a little inconsistent.

**Comment by mechmerlin** [comment]
> Thats fair, in my eye Sublime is expensive, but the infinite trial is not something I knew.
> 
> @mechmerlin true, but VS Code is also mentioned in the newbs [getting started guide](https://docs.qmk.fm/#/newbs_getting_started), so it's a little inconsistent.

Ahh ok, consistency is a much better argument!

**Pull request merged**
