### PR TITLE
Cirque Pinnacle usability updates

### PR DESCRIPTION
**Pull request by dkao**
## Description

Some basic usability updates for the Cirque Pinnacle circle trackpad.

- Software data ready check for when data ready pin is not available (e.g. `SPLIT_POINTING_ENABLE`)
- Set ADC attenuation according to overlay, and calibrate on initialization
- Preprocessor directives to opt out of tap and smoothing

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by dkao** [comment]
This got labeled as core. Should pointer related PRs target `develop` instead of `master`?

**Comment by Kriechi** [comment]
@dkao great to see other people improving the pinnacle trackpads!
I already sent https://github.com/qmk/qmk_firmware/pull/17091 with already takes care of the software data ready check and a few other minor improvements and lots of code comments that we discussed on Discord with other Cirque trackpad users. How about combining our forces?

Is the smoothing actually applicable in absolute mode? Reading the docs, I think it only applies to relative mode?

**Comment by dkao** [comment]
@Kriechi Uh oh!
Yes, definitely makes sense to coordinate our efforts. The actual changes I wanted to push are inertial cursor and circular scrolling which are after these commits, not included here because I thought those would be more contentious.
I feel a pretty big difference with smoothing disabled in absolute mode. By the way, which document are you referring to? I only saw a mention of the smoothing disable bit in the “using a stylus” app note and decided to try it out, thinking I’m somehow missing a lot of information.

**Comment by Kriechi** [comment]
@dkao luckily, I referenced all docs in my PR so in the future others can discover it more easily:
https://github.com/qmk/qmk_firmware/pull/17091/files#diff-23e6ffbdd473057b633a13eb63cf8bec7e6e99578268a3713d991974af92e9a5R4
specifically:  IC-DS-150408 Pinnacle Specification (though other docs also have additional details), for FeedConfig1, Bit2:
> The Filter disable bit controls whether the filtering algorithm is applied to generated data. By default the hardware filters are enabled. Cirque does not recommend disabling hardware filtering.

How about we base our PRs on top of each other? The SoftwareData Ready is already covered in mine, and the Hardware Data Ready would be something new in yours - although I'm not sure if it brings any benefit? Pinnacle at most gives new data every 10ms, so interrupt-driven would just add more complexity and requires an extra (useless?) pin... happy to hear about your real-life experience if you are using it?

About calibration, I don't think we need to explicitly call this:
> Pinnacle automatically executes compensation/calibration when powered on and when triggered by specific events.

Looking forward to your circular scrolling! That sounds super interesting!

**Comment by dkao** [comment]
@Kriechi So there's a filtering disable bit in FeedConfig1 and a separate smoothing disable bit in FeedConfig3, bit 1. Filtering disable likely refers to filters on the capacitive image itself before coordinates are computed, and smoothing disable refers to a smoothing filter applied to the computed coordinates.

>  The SoftwareData Ready is already covered in mine, and the Hardware Data Ready would be something new in yours - although I'm not sure if it brings any benefit? Pinnacle at most gives new data every 10ms, so interrupt-driven would just add more complexity and requires an extra (useless?) pin

Hardware data ready pin is already handled in QMK by https://github.com/qmk/qmk_firmware/blob/94755308e0db92bf98d2a32c0717e4a76be7ef6a/quantum/pointing_device.c#L239-L244 There isn't really a need to check hardware data ready pin **and** the data ready bits in status register.
I think it's better for the caller to check for data readiness as needed, rather than have `cirque_pinnacle_read_data()` send fake reports potentially throwing off caller logic (such as the tap code checking `touchData.touchDown`).

> About calibration, I don't think we need to explicitly call this: 
>> Pinnacle automatically executes compensation/calibration when powered on and when triggered by specific events.

We do if changing ADC attenuation, the controller doesn't automatically recalibrate.
If you're lucky, controller figures out it has a bad baseline after a few touches and recovers by triggering a recalibration on its own. If you're not lucky the trackpad remains unusable.

Let's work on your PR first, I'll rebase my stuff on top of that.

**Pull request closed without merging**
