### PR TITLE
bastardkb: fix info.json changes that got reverted during the last merge from `master` to `develop`

### PR DESCRIPTION
**Pull request by 0xcharly**
Fix forward changes that were reverted during the last merge.

cc @drashna 

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by fauxpark** [comment]
Are you sure that this works? I've been deliberately avoiding keyboards split into revisions for #17782 etc. because there is an issue with the order in which the CLI merges info.json's together.

**Comment by 0xcharly** [comment]
This seem to work for all these boards and configuration without any issue (all keyboards under `bastardkb`, including the Charybdis that is already using this setup with multiple level of `info.json`, eg. https://github.com/qmk/qmk_firmware/blob/develop/keyboards/bastardkb/charybdis/3x5/v2/elitec/info.json).

If this is not the intended use, I revert those changes and update all the `info.json` files under `bastardkb`.

**Comment by fauxpark** [comment]
I think it should be fine if each key is only specified once - for example if an info.json under `rev1` "overrides" the manufacturer string in the top-level info.json, the latter is used instead, though it should be the other way around. But I have not really looked into this yet, so I've just been putting it off in these PRs. If the generated config.h has the right values, no problem.

**Comment by 0xcharly** [comment]
You're correct, values cannot be overridden, only combined. The resulting `config.h` looks correct to me, and all configurations build correctly with these changes.

**Review by keyboard-magpie — APPROVED** [review]

**Pull request merged**
