### PR TITLE
Update led_update_kb example

### PR DESCRIPTION
**Pull request by yanfali**
Provide a more succinct and less verbose example for a custom LED function.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by noroadsleft** [comment]
Related question: does this or a similar method work if the board uses Input/Output to toggle the LED instead of High/Low? And if not, can we make it do that?

**Comment by fauxpark** [comment]
I kept these as discrete if statements because I figured it would be more understandable for newbs, but if you're going to change them to `writePin()` I guess a small bit of explanation as to what's going on here would be helpful. Especially with the `!` inverting the logic as this is not always the case; it depends whether the LED is between the pin and VCC or GND.

@noroadsleft I think (haven't tested...I should buy some breadboards tbh) that high/low will work for all cases, as we just need current flow. If both sides of the LED are at VCC or GND, it won't light up. When it's pointing from VCC to GND, it will light up. Whether the pin is input or output probably has no effect electrically.

**Comment by yanfali** [comment]
> I kept these as discrete if statements because I figured it would be more understandable for newbs, but if you're going to change them to `writePin()` I guess a small bit of explanation as to what's going on here would be helpful. Especially with the `!` inverting the logic as this is not always the case; it depends whether the LED is between the pin and VCC or GND.
> 
> @noroadsleft I think (haven't tested...I should buy some breadboards tbh) that high/low will work for all cases, as we just need current flow. If both sides of the LED are at VCC or GND, it won't light up. When it's pointing from VCC to GND, it will light up. Whether the pin is input or output probably has no effect electrically, it's simply the fact that putting the pin into Hi-Z state basically disconnects one end of the circuit.

I've updated the comment in the code example to reflect this information. Thanks!

**Comment by esinlayo** [comment]
Thanks for this example. I had to set the pin as an output using SetPinOutput in my init to get it to work though.

**Pull request merged**
