### PR TITLE
Modified URLs to point to new locations

### LINKED ISSUE #3684: Atreus documentation links broken
A similar issue was fixed for the Ergodox (#1594), but Atreus also has some dead links. I found some related pages, but no exact match, so I'll refrain from making a PR without knowing the intended page.

> See [build environment setup](https://docs.qmk.fm/build_environment_setup.html) then the [make instructions](https://docs.qmk.fm/make_instructions.html) for more information.

### PR DESCRIPTION
**Pull request by germ**
Fixes for https://github.com/qmk/qmk_firmware/issues/3684

## Description
Pointed at new doc location

## Types of changes
- [ ] Core
- [ ] Bugfix
- [ ] New Feature
- [ ] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by this PR
Closes #3684

### CODE REVIEW

**Comment by drashna** [comment]
Well, .... I hate to be "that guy", but we've been using: 
```markdown
See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

Ideally, we should use that for the rest, for the conformity and sanity's sake.

**Comment by germ** [comment]
Ah, I just ripped a few regex through the layouts to do it quickly. Short of editing a 100 or so files manually. Seems that most of these are outdated anyway :(

Want me to get on changing those or just keep it as is?

**Comment by noroadsleft** [comment]
I say update the Docs links now and we can worry about matching the template later.

**Comment by germ** [comment]
Sounds good to me, wasn't looking forward to updating all that :P

**Pull request merged**
