### PR TITLE
update quantum/template/avr/config.h

### PR DESCRIPTION
**Pull request by mtei**
## Description

Modify the template of config.h according to drashna's recommendation. And I think the RGBLIGHT_ANIMATIONS is only for backwards compatibility. I think its use should be deprecated. So I removed it.

see https://github.com/qmk/qmk_firmware/pull/8670#discussion_r403683217

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Has there been discussion to deprecation of `RGBLIGHT_ANIMATIONS`? Given it also functions as "give me all available animations", i'm not sure its `only for backwards compatibility`.

**Comment by mtei** [comment]
> The LTO block should also use proper formatting.

I didn't change it to avoid conflicting with #8663.

**Comment by mtei** [comment]
> Has there been discussion to deprecation of `RGBLIGHT_ANIMATIONS`?

I wanted to discuss that here, so I made this change.

When I made rgblight.c configurable (#3582), RGBLIGHT_ANIMATIONS was referenced in several source files under `quantum/` and `tmk_core/`, so I didn't remove it for fear of negative consequences.

Later, due to refactoring by you and others, RGBLIGHT_ANIMATIONS is no longer referenced under `quantum/` and `tmk_core/`.

Currently, RGBLIGHT_ANIMATIONS is only there to ensure backward compatibility for keymap users. Of course, this compatibility should be maintained in the future.

But with the new keyboard, I think it's better not to use RGBLIGHT_ANIMATIONS, but to choose the effect you want to use explicitly. So I propose to remove it from the template.

If, after discussion, we come to the conclusion that we want to keep RGBLIGHT_ANIMATIONS, I will add it again to the template.

**Comment by mtei** [comment]
> Given it also functions as "give me all available animations", i'm not sure its `only for backwards compatibility`.

If someone adds a new effect to rgblight.c in the future, it will automatically increase the firmware size of the keyboard using RGBLIGHT_ANIMATIONS.

Is this an acceptable thing to do?
Is adding a new effect a breaking change?

So, I don't think RGBLIGHT_ANIMATIONS should be used on new keyboards. And when you add a new effect, you shouldn't include it in RGBLIGHT_ANIMATIONS.

**Comment by zvecr** [comment]
So I agree we have space limitations on AVR boards, and that factors partially into the decision.

However for end users, having `RGB_MOD` cycle through everything we have is far more useful that having to enable each one, potentially in turn, to see which one you like. I would say disabling other features like console is a worthwhile trade off to the increase in firmware space due to animations.

**Comment by mtei** [comment]
This PR template has all RGBlight effects enabled. It's easy for users to see which one they like. I think the reasons you gave are irrelevant to the question of whether or not to leave RGBLIGHT_ANIMATIONS in the template.

And with RGBLIGHT_ANIMATIONS, you'll be affected when RGBlight effects are added in the future, as mentioned above. When a user brings qmk_fiermware up to date, it may fail to compile due to an unexpected increase in firmware size. Therefore, it is better not to use RGBLIGHT_ANIMATIONS on new keyboards to avoid that risk.

**Comment by fauxpark** [comment]
Looks like the "backward compatibility" notice was added in #7773?

**Comment by mtei** [comment]
> Looks like the "backward compatibility" notice was added in #7773?

Which notice are you referring to?

**Comment by fauxpark** [comment]
Ah, never mind, it came from rgblight_reconfig.h in 3582.

**Pull request closed without merging**
