### PR TITLE
add stock layout for xd75

### PR DESCRIPTION
**Pull request by WunderWaffla**
This adds default layout for XD75RE keyboard.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Does the XD75 actually come with a default keymap? Is this preferred over the current one?

**Comment by WunderWaffla** [comment]
This layout is preinstalled on xd75. At least on xd75re from KPrepublic Store page, which is the only seller. Official documentation also contains link to this layout on keyboard-layout-editor.
http://www.keyboard-layout-editor.com/#/gists/ac341208e023e4a4d982bccf711ae38f
I think this stock layout is a good place to start creating a custom one.

**Comment by jackhumbert** [comment]
Cool - I wouldn't mind having this be the `default` keymap then, if @BenKesselring doesn't mind!

**Comment by BenKesselring** [comment]
I'm good with it! I just copied the Atomic layout because it was simpler than copying Kai's layout from TMK.

**Comment by jackhumbert** [comment]
Cool! @WunderWaffla if you wanna just replace the `default` keymap instead of naming it `stock`, we'll get this merged :)

**Comment by WunderWaffla** [comment]
@jackhumbert nice. I'll make a new commit with "default" keymap name when I get home.

**Comment by WunderWaffla** [comment]
@jackhumbert layout has been renamed.
'default' is now 'atomic_style'
'stock' is now 'default'.

CI was failed because of this:
```
Connecting to www.atmel.com (www.atmel.com)|209.133.57.121|:80... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
2017-10-06 22:10:39 ERROR 504: Gateway Time-out.

```
I don't think this is because of my commits. How can I restart CI process?

**Comment by jackhumbert** [comment]
It looks like we got past the time-out, but now it's erroring because of some remaining files in the `stock` folder - I think it'll build correctly if you remove them!

**Comment by WunderWaffla** [comment]
@jackhumbert I cleaned up a little bit. Now it's ready to merge

**Comment by jackhumbert** [comment]
Perfect - thanks :)

**Pull request merged**
