### PR TITLE
Allow 30us matrix delay to be keyboard/user overridable 

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Hitting some limits when testing the arm uart serial code, this allows the delay while waiting for IO to settle to be configurable.

Ive tested as low as 5us with success.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by alex-ong** [comment]
Nice feature, it will speed up scan rate significantly. It might be a better idea to set how many nops, rather than how many microseconds? I think looking up our set of devices (atmega32u4, cortex armv3 etc etc) to see if pin settling time is defined in microseconds vs nops might be desirable.

Finally, since i believe this figure is inherently tied to which microprocessor we are using, it could be defined by default per microprocessor and then this override could still be used (still up for discussion on whether it be defined in nops or microseconds).

**Comment by zvecr** [comment]
I would rather avoid nops where possible, as some STM32 boards require the wait for yielding (so that the USB thread gets runtime).

An alternative implementation is in 18c948ae8911205d413dc39adade6bd74376bb1e, where it would allow the replacement of the delay logic at the expense of a function call.

**Comment by alex-ong** [comment]
What about an "inline" function call? I remember that it isn't exactly guaranteed  because it's  just a suggestion to the compiler...

**Comment by zvecr** [comment]
inline cant be weak, so thats a non starter, it would have to be a define which you redef.

**Comment by alex-ong** [comment]
Right, going from 30us to 1us will make the biggest difference. Qmk is always going to be battle between open apis and power users who want specific functionality at no additional cost to Rom size / speed. 

I think an overrideable function is better than just using pure us and is the most flexible option.

**Comment by alex-ong** [comment]
I'll have a look at speed testing this vs my scanning code, and ideally bringing back xealous-brown to a simpler default implementation :D

**Pull request merged**
