### PR TITLE
Remove redefinition of `_______` in documentation example

### PR DESCRIPTION
**Pull request by AnthonyWharton**
After [being caught out](https://github.com/qmk/qmk_firmware/pull/3908#discussion_r217840949) I thought it might be useful to edit the keymaps documentation to remove the redefinition of the alias of `KC_TRNS`; `_______` in the Definitions section of "Anatomy of a keymap.c".

I've put a suggested rewording for the following paragraph to remove the mention of this, and looked through and not spotted any other mentions of this. That being said, I am newer to this project, so if there are any other suggested updates/rewording suggestions then please feel free to comment.

I've also spotted that there are notes about the included `_______` definition above (and below) in the documentation file so did not add any other note to the section in which it was removed.

### CODE REVIEW

**Comment by AnthonyWharton** [comment]
@drashna / @noroadsleft If you feel the comments [here](https://github.com/qmk/qmk_firmware/pull/3908#discussion_r217891097) are worth making more explicit in the keymaps documentation then let me know what to add and I could do that for you in this PR if you'd like!

**Comment by mechmerlin** [comment]
Could you explain why this is being taken out? Using _______ is actually a frequent occurrence.

**Comment by AnthonyWharton** [comment]
As far as I was aware it is included by default now, as you do not need to include it. I may be mistaken though, in which case I'll promptly close the PR!

**Comment by mechmerlin** [comment]
Yes it has, I just thought it was a good idea to put it there as additional info. Perhaps you could leave it commented out explaining that its included by default. It helps explain what the underscores are in the keymap.

**Comment by AnthonyWharton** [comment]
Sure ok, afraid I won't be able to do that until tonight/tomorrow.

The reason I never included a comment there is due to this being mentioned several other times in this file, such as on Line 75, and Line 154 (I couldn't seem to link to lines in markdown files in github sorry!). These locations seem slightly more relevant to mentioning about this alias in my opinion?

I'll get the change in by tomorrow unless I hear from you otherwise! :smiley:

**Comment by noroadsleft** [comment]
@mechmerlin Never occurred to me that these lines could just be commented out. :man_facepalming:

**Comment by drashna** [comment]
Maybe we should use this: 

```c
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 *  You can use _______ in place for KC_TRNS (transparent)   *
 * Or you can use XXXXXXX for KC_NO (NOOP)                   *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
```

**Comment by AnthonyWharton** [comment]
Whoops, it appears in a moment of git madness that I missed a commit before that one and thus the commit message isn't the best. Apologies.

I've added @drashna's suggestion along with a brief explanation as a note below.

Another thing I experienced in the past is the [the following include macro](https://github.com/qmk/qmk_firmware/pull/3908#discussion_r217777295) - `#include QMK_KEYBOARD_H`.

Should this be added in this pull request, and if so is the explanation of what it does in the link sufficient to take as a base to what the documentation should be? Thanks.

**Comment by drashna** [comment]
Actually, yes please.  

And I don't think that an explanation is really needed here.  It's part of the community layouts feature, though. 
https://docs.qmk.fm/#/feature_layouts?id=tips-for-making-layouts-keyboard-agnostic

**Comment by AnthonyWharton** [comment]
Sorted, if you're happy without a reference to that link then I think providing that you are happy, this is good to go :tada:

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
