### PR TITLE
Move keyboard USB IDs and strings to data driven: D

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Previous PR #17789 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by KarlK90 — APPROVED** [review]
LGTM!

**Comment by drashna** [comment]
should probably target develop.  Have already ran into merge conflicts, with the B PR due to changes to the boardsource boards.

**Comment by fauxpark** [comment]
I don't recall getting an email that the develop merge failed? Unless you mean merge conflicts with other PRs, in which case they would need to be resolved. These aren't core changes.

**Comment by fauxpark** [comment]
Lint errors are unrelated.

**Comment by drashna** [comment]
> I don't recall getting an email that the develop merge failed? Unless you mean merge conflicts with other PRs, in which case they would need to be resolved. These aren't core changes.

It definitely failed the merge. Not sure why it failed to send a notification.

https://github.com/qmk/qmk_firmware/actions/runs/2733376752

I'm not sure if any others will have issues, though.

**Review by drashna — APPROVED** [review]

**Pull request merged**
