### PR TITLE
Updating old Mad Noodle Keypads, and added support for all Mad Noodle keypads, past and future (upcoming keypad launch)

### PR DESCRIPTION
**Pull request by jessel92**
Updating old Mad Noodle Keypads, and added support for all Mad Noodle keypads, past and future (upcoming keypad launch).

## Description

Hey there!

I'm a small keypad manufacturer (one-man operation), The Mad Noodle. I actually only did a QMK pull request for my first gen of keypads, so this is adding everything I've produced so far. Also tried to clean things up to make things a little easier for my customers.

I've updated older keypads and added all of the keypads I've sold/manufactured up to this point. Plus one new keypad that has yet to launch but hopefully will be ready to go by the end of the month. 

I believe I followed all the pull request etiquette to the best of my ability. But please let me know if I did anything incorrectly.

Thanks in advance!

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

*  Updated older keypads to new JSON format
*  Add multiple newer keypads

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by jessel92** [comment]
ALSO! Forgot to add this! 
I know this is a lot of changes so I'm super sorry. 
But please note that files for ncc1701, noodlepad/v1, and v2 are almost identical except for minor pin definitions and the readme.md.

If this is too much for a single pull request, I can split this up. But I've been using this FW for 4ish years and extensively tested it on my end. So ideally, it should be easy on your end hopefully lol. but I barely know what I'm talking about when it comes to git, so I could be totally wrong hahaha.

**Comment by sigprof** [comment]
Sorry, but this PR does not comply with several important items of the [PR Checklist](https://docs.qmk.fm/#/pr_checklist):

> multiple keyboards at the same time is not acceptable

You need to split this to separate PRs for each keyboard, not lumped in like this.

> keyboard moves within the repository must go through the develop branch instead of master, so as to ensure compatibility for users

Apparently you are trying to move `themadnoodle/noodlepad` to `themadnoodle/noodlepad/v1`; this rename needs to go through the `develop` branch (and the addition of `themadnoodle/noodlepad/micro` and `themadnoodle/noodlepad/v2` too, as they depend on the rename).

There are also some more problems:

- Your PR includes changes to some files which should not be touched, like `.vscode/settings.json`.
- Some `config.h` settings, like `RGBLIGHT_DEFAULT_SPD`, now have `info.json` equivalents which should be used instead.
- `ENCODER_MAP_ENABLE = yes` at the keyboard level `rules.mk` is not allowed — this option can be set only in the keymap (so a bunch of your `default` keymaps would need `rules.mk` with that setting, and most of `rules.mk` at the keyboard level should become just `# This file intentionally left blank`, as the other settings in there should be moved to `info.json`).

**Comment by jessel92** [comment]
Hey ok i understand. 
But im a little confused on some aspects:
* How do I add encoder_map_enabled at the keymap level? I was just following the docs and there's is nothing about it. Are you saying add a separate rule.mk in the individual default keymaps folders? (similar to the via keymap? Do i still need the RGBLIGHT_ENABLE = yes as well?
* Same with the RGB settings in JSON. How would I write that? 

Any guidance would be greatly appreciated!

**Comment by jessel92** [comment]
Also should I wait for the v1 PR to the Dev branch to go through before I make PRs for the other Noodlepads?

**Pull request closed without merging**
