### PR TITLE
Fix pin numbers for Fractal keyboard

### PR DESCRIPTION
**Pull request by Merlin04**

### CODE REVIEW

**Comment by drashna** [comment]
Looks like this code is already merged in, actually.  

Also pin numbers look the same.

**Comment by noroadsleft** [comment]
6b69163 and 66a0aaf are new commits. The first three are in already though.

**Comment by Merlin04** [comment]
I didn't mean to add 6b69163, only the change to the pin numbers.

**Comment by drashna** [comment]
That commit is fine, actually.  

And I do see now that the pin definitions are different. 

If you wanted to resolve the merge conflict?

**Comment by Merlin04** [comment]
I've resolved the merge conflict.

**Comment by drashna** [comment]
Awesome!  

And Travis CI error isn't related to your code, but seems to be an issue with @Xyverz's community layout.

**Pull request merged**
