### PR TITLE
 Fix Clueboard hotswap gen1 not compiling when LED Matrix is disabled

### PR DESCRIPTION
**Pull request by vomindoraan**
## Description

Clueboard 66 hotswap gen1 doesn't compile if `LED_MATRIX_ENABLE` is set to `no`. This is because of an unconditional `#include "is31fl3731-simple.h"` directive in a source file. That header isn't present if LED Matrix is disabled, so the build fails. This PR fixes that by moving the include into a `#ifdef LED_MATRIX_ENABLE` block.

Tagging @skullydazed for review.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by vomindoraan** [comment]
CI seems to be failing because it's trying to build `keyboards/clueboard/66_hotswap/keymaps/json` as a keymap, but it only contains a `keymap.json` file. I will move this file to `keyboards/clueboard/66_hotswap/keymaps/default`.

**Comment by skullydazed** [comment]
We support json keymaps now, that should compile.

**Comment by vomindoraan** [comment]
Ah, I wasn't aware of that. I will revert the last commit. In that case, the build issue is outside of the scope of this PR.

**Comment by skullydazed** [comment]
Thanks!

**Pull request merged**
