### PR TITLE
Plaid - Add compatibility for LAYOUTS = planck_mit planck_grid

### PR DESCRIPTION
**Pull request by zvecr**
## Description

Spotted within the output of http://compile.qmk.fm/v1/keyboards/error_log.

Plaid defines `LAYOUTS = planck_mit planck_grid` however the LAYOUT macros are defined as `plaid_mit` and `plaid_grid`.

This PR allows the default community layout ` make plaid:default_planck_mit` to be built and also removes planck_grid as ortho_4x12 supersedes it. I have kept the existing macro and defined an alias, just incase any keymaps already exist. If required i can change the logic so the layouts are planck and the alias is plaid.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by zvecr** [comment]
Failures are due to ortho_4x12 community layouts

@Xyverz 
  - Plaid is currently not configured for RGB underglow

bakingpy @nooges 
  - Plaid does not support backlight
  - rules.mk logic would be need to be extended to exclude the board

**Comment by noroadsleft** [comment]
The ideal way to fix the API error is to remove `planck_grid` as an option from https://github.com/qmk/qmk_firmware/blob/3761c28bf9a0d8c117b124c8d1a958e033b1e99f/keyboards/plaid/rules.mk#L100

The community has settled on `ortho_4x12` for that purpose. Only Planck-specific keymaps should be using `LAYOUT_planck_grid`.

**Comment by zvecr** [comment]
@noroadsleft Less build targets is always better (i.e. for build speed and maintainability) but while that fixes the planck_grid issue, it does not address the planck_mit one.

**Comment by noroadsleft** [comment]
I failed to discuss that aspect of the issue. Your solution for the `planck_mit` layout is the correct course of action.

**Comment by zvecr** [comment]
Planck still defines `keyboards/planck/rules.mk:LAYOUTS = ortho_4x12 planck_mit planck_grid`, and is the only board to do so. I presume this should also be removed now?

**Comment by noroadsleft** [comment]
> Planck still defines `keyboards/planck/rules.mk:LAYOUTS = ortho_4x12 planck_mit planck_grid`, and is the only board to do so. I presume this should also be removed now?

It should.

**Comment by zvecr** [comment]
Anything i can do to push this over the finish line?

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
