### PR TITLE
NIU keyboard default layout

### PR DESCRIPTION
**Pull request by kubek2k**
the layout that comes straight from the store (and this probably should be the basis for further keymaps development).

### CODE REVIEW

**Comment by jackhumbert** [comment]
Awesome! Would you mind updating the `readme.md` (note the case) to match the other projects? The `config.h` should really have unique identifiers as well - thanks!

**Comment by kubek2k** [comment]
@jackhumbert done!

**Comment by jackhumbert** [comment]
Cool! Can you update the readme to follow [this format as well](https://github.com/qmk/qmk_firmware/issues/1588)? Thanks!

**Comment by jackhumbert** [comment]
#1847 adds this!

**Comment by kubek2k** [comment]
ah - I am so sloppy - thanks @krusli !

**Pull request closed without merging**
