### PR TITLE
Putting all IBM Model M projects under one folder #12370

### PR DESCRIPTION
**Pull request by nuess0r**
As discussed in #12370:
The maintainers of several Model M replacement
controller projects agreed to cosolidate them
under one common folder.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* #12370

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by drashna — APPROVED** [review]

**Comment by nuess0r** [comment]
any news on this pull request? 
Seems that none of the Model M developers has a need to comment here or a wish to change something.

**Comment by drashna** [comment]
Looks like you have a merge conflict that needs to be resolved, at the very least.

**Comment by nuess0r** [comment]
Merge conflict solved

**Comment by drashna** [comment]
It looks like you may need to rebase to properly fix this.

**Comment by drashna** [comment]
it looks like you merged, rather than rebased.  Unfortunately that leaves it in the same position.  

If you want, I should be able to see about helping out with this.

**Comment by nuess0r** [comment]
I did try to rebase but seems that long ago I did a merge by mistake. I'm new to rebase, never needed that at work.
I didn't knew how to fix it in this branch so I created a new branch and cherry-picked what was correct: #14996 

So I close this one.

**Pull request closed without merging**
