### PR TITLE
Variable tapping terms

### PR DESCRIPTION
**Pull request by nikchi**
Referenced to #1320 

Implemented for new advanced tap dance macro.
`ACTION_TAP_DANCE_FN_ADVANCED_TIME`

### CODE REVIEW

**Comment by ezuk** [comment]
Would be cool if this came with a little readme.md explaining what the change feels like to a user, which we could then pull into the docs repo. Just a little usage example and what it feels like in practice.

**Comment by nikchi** [comment]
I'll try to get one in later tonight or tomorrow, any particular formatting?

**Comment by ezuk** [comment]
no, format isn't a big deal at all -- just basically would like to convey what this change feels like in practice, the rationale behind it (what is it good for) and how to use it with an example or two. This would then go into the main docs for the project.

**Comment by nikchi** [comment]
I put the readme as a file named variableTapDance.md in my keymap folder (not sure where else to put it). Trying to figure out what type of example to show, as this is just an extension of an existing feature.

**Comment by ezuk** [comment]
That's a good writeup IMO. The only point I would clarify is that the spacing between each beat remains the same (right?). It's just that you can change that interval per combo? Like, does it change (short-long-long-short, Morse-style) on a single combo, or does it just give you more/less room in that one combo?

Just for context, your writeup will go as a new section here: https://docs.qmk.fm/Tap-Dance.html

**Comment by nikchi** [comment]
Just the latter. As I understand it, tap dance is 

> tap, then wait TAPPING_TERM to see if another tap occurs, then do something or repeat.

This new macro would allow specific actions to override the TAPPING_TERM with its own.

I'll update the .md to have this clarification

**Comment by ezuk** [comment]
Love it! 👍

**Comment by fredizzimo** [comment]
@jackhumbert, Can you re-trigger Travis. It failed to contact the Atmel servers in order to download the avr toolchain.

BTW, I wonder how they like that we download it every time a build is triggered...

**Comment by jackhumbert** [comment]
This was failing because of something else - @nikchi, you may need to pull the latest changes for Travis to clear this!

**Comment by nikchi** [comment]
@jackhumbert 
Pulled the latest changes into my fork, and repushed. It looks like travis passed.

**Comment by jackhumbert** [comment]
Perfect - thanks!

**Pull request merged**
