### PR TITLE
making it work on freebsd with bash not in /bin/bash

### PR DESCRIPTION
**Pull request by kubatyszko**
Tiny fix that makes the install script work on freebsd with bash not in /bin/bash

## Description

Modify path in some shell scripts from  #!/bin/bash  to #!/usr/bin/env bash

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ X ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ x] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — COMMENTED** [review]
Good catch!
I think this could probably be done to all of the scripts.

**Comment by kubatyszko** [comment]
modified other scripts and pushed

**Review by fauxpark — APPROVED** [review]

**Comment by kubatyszko** [comment]
messed up some commits, resubmitting as another PR.

**Comment by kubatyszko** [comment]
@fauxpark resubmitted as PR #13422

**Pull request closed without merging**
