### PR TITLE
Overhaul the QMK documentation

### PR DESCRIPTION
**Pull request by skullydazed**
Lots of improvements to the QMK documentation:

* Reorganize the sidebar
* New theme
* Dark mode support using `prefers-color-scheme: dark`
* Table of Contents
* Rename the Newbs Guide to Tutorial
* Promote the use of the CLI in the Tutorial
* Overhaul the handwire guide
* Bring in the API documentation
* Add Copy button to code boxes
* Update the configurator video

[Screenshot of new theme, homepage, and sidebar](https://i.imgur.com/o6mX3i1.png).

## Types of Changes

- [x] Enhancement/optimization
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by mtei** [comment]
I have one request.

Some links in documents refer directly to sections of other documents.

**newbs_git_resynchronize_a_branch.md:**
```md
Now your GitHub fork, your local files, and QMK's repository are all the same.
From here you can make further needed changes 
([use a branch!](newbs_git_using_your_master_branch.md#making-changes)) and post them as normal.
```

**newbs_git_using_your_master_branch.md:**
```md
## Making Changes

To make changes, create a new branch by entering:
```

Translators into other languages do not want to change the link information, so they need to do the following:

**ja/newbs_git_resynchronize_a_branch.md:**
```md
これで、あなたの GitHub フォーク、あなたのローカルファイル、および QMK のリポジトリはすべて同じになりました。
ここから、[ブランチを使って](ja/newbs_git_using_your_master_branch.md#making-changes)さらに必要な変更を加え、通常どおりそれらを投稿できます。
```

**ja/newbs_git_using_your_master_branch.md:**
```md
## 変更を行なう :id=making-changes

変更するには、以下を入力して新しいブランチを作成します:
```

If the original (English) document looks like this, it will help all translators.

**newbs_git_using_your_master_branch.md:**
```md
## Making Changes :id=making-changes

To make changes, create a new branch by entering:
```

**Comment by shelaf** [comment]
If you overhaul the document, there are suggestions.
Would you please move all English documents to under the en folder?
The main reason is that it is difficult to check if the translated document is older than the original. This check can be simplified by introducing translation support tools such as [Transifex](https://www.transifex.com/) and linking to Github, but these support tools assume that the original text is in a specific language code folder.

Currently, in Japanese translated documents, the commit hash at the time of translation is included in the document (see https://github.com/qmk/qmk_firmware/commit/da1a527c90b1adab02b2dfbe6f9da40c4d8e069e#diff-b3e744151f02a5bd4939286ba46df368R4), and the change history can be obtained by executing command such as `grep --no-filename "^[ ]*git diff" docs/ja/*.md | sh | grep '^--- a/'`. However, such a maintenance method is very difficult.
And then, I would also be very happy if QMK could prepare a translation support tool officially :)

**Comment by skullydazed** [comment]
@mtei Good idea, I've just pushed a commit with that change.

@shelaf This seems like a good idea. We can make this change but it should probably be done separately from this PR. I don't think we will be able to use Transifex as that that tool is rather expensive, but we are supportive of setting up an open source or free alternative. The best way to push that forward is to open an issue and suggest some possible tools we can implement. Hopefully community discussion can provide a clear direction from there.

**Comment by shelaf** [comment]
OK. I don't do much research on these support tools, so I need to make sure we can do what we want.
In addition, the comment system of these tools is often poor than Github, so I think it is necessary to evaluate usability, too.
I don't have time to do this research right now, so it will be a while away.

**Comment by skullydazed** [comment]
Apparently I can't approve my own PR, but the changes that @noroadsleft has made LGTM.

**Comment by bricewge** [comment]
@skullydazed What was you reasoning behind d1c18086d? The commit is titled “wip” and delete `docs/getting_started_build_tools.md` which contains documentation about how to build QMK with Nix which, information which isn't present anywhere else in the repo. Further more there are still links, dead links, to this file in the current master.

Can this commit be reverted or where should the unique information that was present in `docs/getting_started_build_tools.md` should go now?

**Comment by skullydazed** [comment]
@bricewge I removed that page because in general that information is contained in https://docs.qmk.fm/#/newbs_getting_started and part of my goal here was to reduce duplication.

At the time I didn't realize that was the only place the Nix commands were documented. Reviewing that now it looks like that doesn't follow the correct pattern anyway. We handle all package installation through `util/qmk_install.sh` (and associated OS specific scripts), and it appears that no one has done that work for Nix yet.

**Comment by sigprof** [comment]
Looks like this PR removed the documentation for `PERMISSIVE_HOLD_PER_KEY` (added in #7994).

**Pull request merged**
