### PR TITLE
Implement option to define mod mask to trigger alt repeat key

### PR DESCRIPTION
**Pull request by KohlJary**
Added define for ALT_REPEAT_MASK, as a mod bit mask value such as MOD_BIT(KC_RSFT) that when active will cause QK_REP to send the alternate repeat key instead of the standard repeat key.

First PR so let me know what I can do to tidy things up. Looked at writing unit tests for the function but I am a bit lost on how to set up tests with and without a particular define present. Unsure if the addition is large enough to merit adding to the documentation regarding it as well, but if it is I'd be happy to write something up for the docs.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] ? My change requires a change to the documentation.
- [ ] ? I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by precondition** [comment]
>  Unsure if the addition is large enough to merit adding to the documentation regarding it as well, but if it is I'd be happy to write something up for the docs.

This is a feature targeted towards end-users so you should document it. If no one knows about it, no one will use it.

**Comment by KohlJary** [comment]
Sure, I'll get those up for this later on today

**Comment by getreuer** [comment]
@KohlJary  Thanks for the cool addition and making your first PR! 

> Unsure if the addition is large enough to merit adding to the documentation regarding it as well, but if it is I'd be happy to write something up for the docs.
 
Yes, mention this in the QMK documentation so that people know about it. How to do that:

1. Edit [docs/feature_repeat_key.md](https://github.com/getreuer/qmk_firmware/blob/c90b28559f634dc4e13b533a47b0b43b579e0e3a/docs/feature_repeat_key.md). 
2. Use `qmk docs` locally to preview the updated documentation.

> Looked at writing unit tests for the function but I am a bit lost on how to set up tests with and without a particular define present. 

Regarding unit testing, yes, compile-time options are a complication. The solution is to make a separate test target in which `ALT_REPEAT_MASK` is defined. See how the existing tests under [tests/repeat_key](tests/repeat_key) have three targets so far for different compile-time settings, and follow that structure to add another such target for `ALT_REPEAT_MASK`. The test itself is written using the [GoogleTest](https://google.github.io/googletest/) framework. Take a look at some existing tests, like [tests/repeat_key/test_repeat_key.cpp](https://github.com/getreuer/qmk_firmware/blob/c90b28559f634dc4e13b533a47b0b43b579e0e3a/tests/repeat_key/test_repeat_key.cpp), for examples of how GoogleTest is used in QMK to simulate and test key events.

I suggest to do something like this:

1. Create a copy of `tests/repeat_key/alt_repeat_key` called `tests/repeat_key/alt_repeat_mask` as a starting point.
4. Within that new folder, edit the config.h file to define `ALT_REPEAT_MASK`.
5. Rename the test file to "test_alt_repeat_mask.cpp", and replace the test code to exercise the mask option.
6. Run the test with `make test:alt_repeat_mask`.

**Comment by drashna** [comment]
To pile on...

Documenting options is always a good idea. 
And adding more tests boosts confidence in the code changes, both current and future.

**Pull request closed without merging**
