### PR TITLE
Changes to own keymap

### PR DESCRIPTION
**Pull request by Maartenwut**

### CODE REVIEW

**Comment by fredizzimo** [comment]
I think that you should include the changes to `tada68.c`, that were discussed in https://github.com/qmk/qmk_firmware/issues/1501. Otherwise your keymap won't work for other people trying it out.

**Comment by Maartenwut** [comment]
Oh, I thought I had included them.

**Comment by Maartenwut** [comment]
This may be merged.

**Comment by jackhumbert** [comment]
Cool :) thanks!

**Pull request merged**
