### PR TITLE
Fix avrdude USB port scanning

### PR DESCRIPTION
**Pull request by nooges**

### CODE REVIEW

**Comment by drashna** [comment]
This looks to be almost identical to #2301 
And neither work for me.

**Comment by nooges** [comment]
@drashna This is just extracting the port detection part off of that PR for improving things on Linux and Mac, issues with Windows will still remain.

**Comment by jackhumbert** [comment]
Ah, sounds good - thanks!

**Comment by drashna** [comment]
Okay, thanks. 

Hopefully the windows issues can get fixed in the near future then!

**Pull request merged**
