### PR TITLE
Added personal keymap in Kinesis matching username; updated old readme.md

### PR DESCRIPTION
**Pull request by tuesdayjohn**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

### CODE REVIEW

**Comment by noroadsleft** [comment]
This a general comment of "Hey, here's something that might be more efficient.":

I glanced at your Gaming Layers and I have a similar thing going on in [my keymap](https://github.com/qmk/qmk_firmware/blob/eb756916c2b1d3b03b1aa26b8bb02e91ce849089/keyboards/kc60/keymaps/noroadsleft/keymap.c#L311-L341). It looks like both of your Gaming layers (Colemak and QWERTY versions) overwrite the same positions, and to the same keycodes.

You could actually combine both layers into a generalized "Gaming" layer, fully transparent (`_______`/`KC_TRNS`) except for the positions you want to overwrite, and then enable it with a toggle `TG(_GAMING)`, and it'll work with either Colemak or QWERTY, so your layer stack looks like:

- Enabled base layer (Colemak or QWERTY)
- Enabled Gaming layer

Keys that are assigned on the Gaming layer would activate as assigned when pressed, and transparent keys on the Gaming layer would fall through to whichever base layer you have active, and run those assignments.

**Comment by tuesdayjohn** [comment]
That’s actually not a bad idea.  I’ll try making the toggle layer layer.

**Comment by tuesdayjohn** [comment]
Tried out the toggle layer method and it's working.

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
