### PR TITLE
add option to let ctrl override shift/gui for the GRAVE_ESC.

### PR DESCRIPTION
**Pull request by BalzGuenat**
This makes the ctrl+shift+esc shortcut to task manager on windows work.
currently, this is OFF by default but I could see it becoming ON by default, since ctrl+~ and ctrl+` aren't used much, afaik.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! Would you mind throwing a line in the documentation about this as well?

**Comment by jackhumbert** [comment]
Sorry, I meant [in the docs](https://github.com/qmk/qmk_firmware/blob/0787d70e55a668244445d9328f3cda2303cc6877/docs/faq_keymap.md#esc-and--on-a-key) :D

**Comment by BalzGuenat** [comment]
done. also put it into the template.

**Comment by jackhumbert** [comment]
Perfect - thanks!

**Pull request merged**
