### PR TITLE
Remove unused fn_actions[] and action_function()

### PR DESCRIPTION
**Pull request by fauxpark**
## Description
#4820, part 2.

I did a repo-wide search for `fn_actions`, ignoring anything that isn't a keymap, then went into each result and looked for the regex `F[UN\(]` (function keycodes appear as `F(n)`, `FUNC(n)`, `KC_FNn`, or `FN_n` in the case of layouts that prepend `KC_`). Any entries in `fn_actions` that weren't referenced were removed.

Next up I will be switching `ACTION_LAYER_MOMENTARY()`, `ACTION_LAYER_TAP_KEY()` and `ACTION_LAYER_TAP_TOGGLE()` to `MO()`, `LT()` and `TT()` respectively.

## Types of changes

- [ ] Core
- [ ] Bugfix
- [ ] New Feature
- [ ] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* None

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
For now, at least, I think it would be best if these changes were only made to the default layouts.

**Comment by fauxpark** [comment]
That would be a grand total of 10 keymaps affected.

**Comment by fauxpark** [comment]
@drashna what should I do with this? Roll it back to just default keymaps?

I'd really like to be rid of this "feature" that duplicates a whole bunch of others :)

**Comment by drashna** [comment]
Yeah, for now.

**Comment by fauxpark** [comment]
I've limited the scope of this PR to just the affected default keymaps, plus the following:

```
keyboards/cu75/keymaps/iso/keymap.c
keyboards/ergodox_ez/keymaps/testing/keymap.c
keyboards/katana60/keymaps/colemak/keymap.c
keyboards/lfkeyboards/lfk87/keymaps/iso/keymap.c
keyboards/lfkeyboards/smk65/keymaps/iso/keymap.c
layouts/community/ergodox/erez_experimental/keymap.c
layouts/community/ergodox/reset_eeprom/keymap.c
layouts/community/ergodox/robot_test_layout/keymap.c
```

**Pull request merged**
