### PR TITLE
gboards/gergoplex: move `COMBO_ENABLE` to keymap level

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

image

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Unrelated to changes, but CLI lint check is failing with:
```
☒ gboards/gergoplex: MATRIX_COLS is inconsistent with the size of MATRIX_COL_PINS: 5 != 4
☒ gboards/gergoplex: MATRIX_ROWS is inconsistent with the size of MATRIX_ROW_PINS: 4 != 10
```

@germ any idea why this is?

**Review by zvecr — COMMENTED** [review]
Seems a bunch of the non default keymaps fail
```
Making gboards/gergoplex with keymap colemak-dhm                                                       [ERRORS]
☒ gboards/gergoplex: MATRIX_COLS is inconsistent with the size of MATRIX_COL_PINS: 5 != 4
☒ gboards/gergoplex: MATRIX_ROWS is inconsistent with the size of MATRIX_ROW_PINS: 4 != 10
In file included from keyboards/gboards/gergoplex/keymaps/colemak-dhm/keymap.c:7:
keyboards/gboards/g/keymap_combo.h:4:84: error: 'COMBO_END' undeclared here (not in a function); did you mean 'COMBO_LEN'?
    4 | #define K_DATA(name, key, ...) const uint16_t PROGMEM cmb_##name[] = {__VA_ARGS__, COMBO_END};
```

**Comment by fauxpark** [comment]
CC @GeorgePetri @tgrosinger

**Comment by GeorgePetri** [comment]
My keymap always had those MATRIX_{COLS, ROWS} warnings, I think it also happens on the default keymap. I'd love to know how to make them disappear.

**Comment by fauxpark** [comment]
@pirj I just noticed you were actually the submitter of this board, not germ (#13027). Could you shed some light on why there is a mismatch between matrix rows/cols count and pins?

Also, if you have the time, it would be nice to migrate to the core MCP23018 driver, now that we have one: https://github.com/qmk/qmk_firmware/blob/master/drivers/gpio/mcp23018.h

**Comment by pirj** [comment]
The original code was written by @germ in #8928, I've just slightly adjusted it.

As far as I remember, rows and columns are mixed up, and should be the other way around.
This can be spotted in [the layout](https://github.com/qmk/qmk_firmware/pull/13027/files#diff-b9234d71088b6b82b5052b051d7da31e984f19b0a4811af728be0d08b39f62c4R39), and a couple of places in the code ([1](https://github.com/qmk/qmk_firmware/pull/13027/files#diff-ddfe308f65cce9dd95ba8517a11a469a462f891b35a830c47b86885749a2cda6R54), [2](https://github.com/qmk/qmk_firmware/pull/13027/files#diff-ddfe308f65cce9dd95ba8517a11a469a462f891b35a830c47b86885749a2cda6R238)):
```
static const pin_t row_pins[MATRIX_COLS] = MATRIX_ROW_PINS;
```
```
setPinOutput(col_pins[row - MATRIX_ROWS_PER_SIDE]);
```

I didn't dare to make a pivot.

> the core MCP23018 driver

Fantastic! That would potentially allow making it purely declarative.
Unfortunately, I don't presently have capacity for such an effort.

**Review by tzarc — APPROVED** [review]

**Review by zvecr — APPROVED** [review]

**Pull request merged**
