### PR TITLE
Fix RGB_TOG cycle for Massdrop CTRL default keymap

### PR DESCRIPTION
**Pull request by doughsay**
## Description

This includes the modifier keys in "keys only" mode of the RGB matrix, bringing the keymap
closer to how the off-the-shelf firmware behaves.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by doughsay** [comment]
I didn't include the same update to the ALT keymap, because I don't own an ALT to test it with, but this is a relatively simple change that it might be worth doing anyway?

**Comment by mechmerlin** [comment]
The stock firmware uses a different RGB lighting mechanism. I don't even think their configurator points to the qmk_firmware (will need to be confirmed). The default_md keymap located at https://github.com/qmk/qmk_firmware/tree/master/keyboards/massdrop/ctrl/keymaps/default_md should be what comes by default on the board when shipped. 

I don't see a particular need/reason to make the QMK default "similar" to the stock firmware when it is actually already available.

**Comment by doughsay** [comment]
You're right of course that there's no real reason to make the new RGB matrix powered keymap similar to the stock one, but I find it not very useful to have a lighting mode that only highlights the keys and not the modifiers. (Not only that, but on this keyboard F5-F8 are considered modifiers for the purpose of backlighting because those keycaps are the same color plastic as the modifiers, making it awkward when you're in "keys only mode" to have F1-F4 and F9-F12 lit up, but F5-F8 not...). I guess that's just my opinion though; but I was using the fact that that's the way the stock firmware works as an argument that maybe it's not an unpopular opinion.

**Comment by mechmerlin** [comment]
I'm just trying to avoid changing default too often. Let's say you change default. 2 weeks later, someone comes by and find that default doesn't make sense for them, and then changes it again. 1 month later someone else comes by and finds that the original default makes more sense etc etc. 

I believe @XScorpion2 was the last to edit this keymap and may have more insights or stronger arguments for or against changing default. 

My opinion though is that if default doesn't work for you, maybe you can just commit a keymap that works for you under keymaps/doughsay.

**Comment by doughsay** [comment]
Yeah, makes perfect sense. I'm not married to this change, just thought to propose it.  @XScorpion2 does appear to the person who originally added the mode cycle code, so I would like to here from them if this change makes sense.  If not, let's just close it and I'll keep my modifications separate.

**Comment by doughsay** [comment]
@XScorpion2 thanks; I've applied the same fix to the ALT default keymaps, but as I said earlier I can't verify them myself. That being said, I can't imagine there's anything that could go wrong, it's a really small change. I've verified that all modified keymaps compile.

**Comment by doughsay** [comment]
ah shoot... travis is failing now because it's testing the compilation of one of the old broken ctrl keymaps.  Why did my first commit not run that test?  The `responsive_pattern` is a known broken keymap, so it shouldn't be in the tests anyway, right?

**Comment by drashna** [comment]
@doughsay that's fine.  As long as the default keymaps compil, that's the most important part. 

@patrickmt any issues with this?

**Comment by patrickmt** [comment]
CTRL looks good but the ALT seems to be missing what keys are considered as modifiers, since only caps lock is highlighted.

**Comment by drashna** [comment]
Ah, okay.  I think that's a bit out of the scope of this PR, but should be fixed, as well.

**Comment by doughsay** [comment]
@drashna sorry for the long silence on this.  I still would like the fix added for the CTRL keymap if possible.  Can I just remove the changes to ALT and call this done?

**Comment by drashna** [comment]
Yeah, that should be good

**Comment by doughsay** [comment]
@drashna rebased and dropped the ALT changes.  Should be good to go now.  Thanks!

**Comment by drashna** [comment]
Thanks!

**Pull request merged**
