### PR TITLE
Port SPLIT_USB_DETECT to crkbd

### PR DESCRIPTION
**Pull request by zvecr**
## Description

While there are plans to move to split_common, that has complications as that currently has behaviour changes.

This PR adds `SPLIT_USB_DETECT` support for those users having issues with Elite-C V3s.

Tagging @foostan as maintainer.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
@foostan any objections to this change?

**Comment by foostan** [comment]
No problem. Thanks 👍

**Comment by zvecr** [comment]
Thanks everyone!

**Comment by prog13** [comment]
Hello everyone, bug report here.

This commit breaks RGB_MATRIX feature for me. 

The slave half starts with the default mode (defined with RGB_MATRIX_STARTUP_MODE) and ignores any of RGB_* codes (RGB_MOD, RGB_TOG, etc).

I use EE_HANDS option and DFU bootloader. Tried to set master and slave halves explicitly, no luck. After dropping this particular commit, everything works as expected.

**Pull request merged**
