### PR TITLE
Add handwired keyboard

### PR DESCRIPTION
**Pull request by samux6146**
i have buld my mechaniacal 3d printed keyboard handwiered with 44 alps switches an made it compatible with qmk and via

https://github.com/samux6146/croxsplit44

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — CHANGES_REQUESTED** [review]
Needs to be moved to the [handwired](https://github.com/qmk/qmk_firmware/blob/master/data/templates/avr/readme.md) folder, and a [readme](https://github.com/qmk/qmk_firmware/blob/master/data/templates/avr/readme.md) added.

**Comment by samux6146** [comment]
i have made the changes.

**Review by samux6146 — COMMENTED** [review]
added

**Review by drashna — APPROVED** [review]

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
