### PR TITLE
ADPenrose Obi Layout Macro Conversion and Addition

### PR DESCRIPTION
**Pull request by noroadsleft**
## Description

- converts `LAYOUT_all` to data-driven
- adds a layout macro for 6.25u Spacebar with reference keymap

cc @ADPenrose (keyboard maintainer)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by ADPenrose** [comment]
Loved the matrix diagram! Also, did you move the matrix data to the info.json file manually?

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
> Loved the matrix diagram! Is it there only for reference or does it have a function in QMK?
> 
> Also, did you move the matrix data to the info.json file manually?

Pretty sure it's from `qmk info` (with `-m`), but manually edited.

**Comment by noroadsleft** [comment]
> Loved the matrix diagram! Is it there only for reference or does it have a function in QMK?

It's only for reference. I'm doing a whole series of similar PRs, and it's basically impossible to tell at the beginning what layout options are supported. Some may only support two layouts like this one (split or 6.25u Spacebar); others may support dozens or even hundreds. That being the case, I thought it wise to leave some trace of what's supported on a board, even if I don't implement every option.

> Also, did you move the matrix data to the info.json file manually?

`qmk generate-info-json` takes care of this. I instruct that command to output the generated data to a new file (`-o dd.json`, specifically), which I then edit - partially with a Python script and partially by hand - before copying the relevant data back to `info.json`, deleting the data from the relevant `<keyboard>.c` and `<keyboard>.h` files - or the files themselves if I can - at the same time.

**Comment by ADPenrose** [comment]
Thank y'all for the info! <3

**Comment by ADPenrose** [comment]
@noroadsleft Quick question: are you using some kind of script to generate the matrix_diagram.md file? I wanna implement it on my future designs, but I wanna know if I can save myself some struggle hahaha.

**Pull request merged**
