### PR TITLE
Add support for STM32WB

### PR DESCRIPTION
**Pull request by JackyJia73**
## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* Add support for STM32WB

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
At this stage we're not including support for new MCUs unless there's a corresponding keyboard for them. All of these items can be specified in `rules.mk` directly inside a keyboard definition -- it'll be up to the QMK team to determine if/when we should be breaking it out and making a common definition.

**Comment by tzarc** [comment]
See #23392 as an example of in-keyboard definition.

**Comment by JackyJia73** [comment]
@tzarc How about update a working kb the same time? Thanks

**Comment by tzarc** [comment]
> @tzarc How about update a working kb the same time? Thanks

That’s fine, so long as the definitions for the MCU still reside in the keyboard. QMK maintainers will choose when to support it in core definitions.

**Pull request closed without merging**
