### PR TITLE
Fix functions when `NO_ACTION_TAPPING` is defined

### LINKED ISSUE #5735: NO_ACTION_TAPPING disables layers
I was just playing around for fun, because I'm probably going to use taps at one point. But defining NO_ACTION_TAPPING disables the layer switching. Even with MO

### PR DESCRIPTION
**Pull request by drashna**
## Description

Changes so that when `NO_ACTION_TAPPING` is defined, that layer function act as expected.  Eg, that MO and TG still work. 

* LT's work as just their keycode
* MT's work as their keycode (but can be switched to mods)
* One Shot Layers work as MO
* One Shot Mdds work as their mod
* TT works as TG (but can be switched to MO
* Tap Dance works (with a fix), considering disabling outright as it is heavily "tapping" dependant
* File formatted

## Types of Changes
- [x] Core
- [x] Bugfix
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #5735

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tzarc** [comment]
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

**Comment by bcat** [comment]
Oooh, it looks like this may be the solution to my perennial Crkbd firmware size issues. :) When I went to rebase my local keymap branch so I could send a PR, I realized I was over size with avr-gcc 5.4.0. Downloading an 8.5.0 toolchain brought me under size, but just barely (even with everything I could find that I didn't want disabled [in rules.mk](https://github.com/bcat/qmk_firmware/blob/f38debd67780571331dc274891d1a15797b6f590/users/bcat/rules.mk#L42-L68) and [config.h](https://github.com/bcat/qmk_firmware/blob/f38debd67780571331dc274891d1a15797b6f590/users/bcat/config.h#L99-L103):

```
Checking file size of crkbd_rev1_bcat_split_3x6_3.hex                                               [WARNINGS]

 * The firmware size is approaching the maximum - 28570/28672 (99%, 102 bytes free)
```

With this PR and `NO_ACTION_TAPPING` enabled, I have a ton more bytes for OLED and RGB fun:

```
Checking file size of crkbd_rev1_bcat_split_3x6_3.hex                                               [OK]
 * The firmware size is fine - 26818/28672 (93%, 1854 bytes free)
```

I can give this PR a try on my keyboards this week if more testing is helpful

**Comment by rileyjshaw** [comment]
Thank you for fixing this. I just applied some of the changes locally and saw a huge size reduction, similar to what @bcat reported.

What’s the status on landing this to `master`? Any way we can pitch in?

**Comment by rileyjshaw** [comment]
Yay! Thanks for giving this an update @drashna. Excited for it to land 🥳🎈

**Comment by drashna** [comment]
> Yay! Thanks for giving this an update drashna. Excited for it to land 🥳🎈

Sorry, I meant to get back to this sooner.  On the plus side, I've learned a lot since.  MT and others now work when tapping is disabled.  Though, a lot more preprocessor stuff...


Need to add a bunch of tests to ensure that the behavior is correct *and* that it's not accidentally broken, later on.

**Comment by rileyjshaw** [comment]
Epic, thanks @drashna!

**Review by tzarc — APPROVED** [review]

**Comment by rileyjshaw** [comment]
Epic!!!!!! Congrats on landing this and a huge thank you to @drashna!

**Pull request merged**
