### PR TITLE
Rename Talljoe's common layout variable so it doesn't collide with some keyboards.

### PR DESCRIPTION
**Pull request by drashna**

### CODE REVIEW

**Comment by mechmerlin** [comment]
THANK YOU

**Comment by drashna** [comment]
This is pulled from @Talljoe fork, and he linked it in another PR.  So .... should be good to go.

Also, this is why I picked `_wrapper` for mine.  I ran into this issue locally, actually. Well, between this and the "pretty" layouts for the ergodox...

**Comment by drashna** [comment]
Referenced in #2804, specifically.

**Comment by drashna** [comment]
Talljoe opened PR with this commit, and more.  Best to use his

**Pull request closed without merging**
