### PR TITLE
Update Invalid JSON Array

### PR DESCRIPTION
**Pull request by AlexOConnorHub**
## Description

`encoder` => `rotary` array example did not have a comma between the two JSON objects within the array.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
Superseded by #21324

**Comment by AlexOConnorHub** [comment]
I Subscribed to the rework PR. I don't know if GH will close this when yours is merged, so I'll plan to mark this as closed once yours goes through. I like the work you put into the rework, the documentation seems much more complete!

**Review by drashna — APPROVED** [review]

**Comment by AlexOConnorHub** [comment]
The superseding PR is now closed. The fact that this PR does not appear to have a conflict,  and from what I just checked the live docs site, it appears that this JSON is still invalid.

**Comment by fauxpark** [comment]
My PR went to develop, this one is targeted at master. There is no conflict now but develop will be merged into master in the next few days.

**Comment by AlexOConnorHub** [comment]
Lol, I just didn't notice what branch you were going to :rofl:

I just looked at the new encoder section, and there isn't any JSON examples, so I will close this, as I do not see a bad example. (Side note, thanks for documenting the `info.json` file! It looks great, and now I have one place to go to for information on the keys.)

**Pull request closed without merging**
