### PR TITLE
Small documentation and keymap tweaks for my minivan layout

### PR DESCRIPTION
**Pull request by jetpacktuxedo**

### CODE REVIEW

**Comment by jetpacktuxedo** [comment]
That Makefile isn't in my branch that is being merged... I don't really understand where that is coming from 🤔

**Comment by jackhumbert** [comment]
I can see it [here](https://github.com/jetpacktuxedo/qmk_firmware/blob/tv44/keyboards/tv44/keymaps/jetpacktuxedo/Makefile) :/

**Comment by jetpacktuxedo** [comment]
Hmmm... I'll investigate and fix that tomorrow.

**Comment by jetpacktuxedo** [comment]
Got it, thanks Jack!

**Comment by jackhumbert** [comment]
Awesome :) thanks!

**Pull request merged**
