### PR TITLE
Add pretty layout to all ergodox clones

### PR DESCRIPTION
**Pull request by drashna**
Adds my pretty pretty layouts to the Ergodox Infinity and Ergodone keyboards.  
(this was because my layout will cause these boards to fail, and tripped up Travis at least once) 

Unfortunately, I don't have either board, so I'm unable to test this out, to verify that it's correct.  
It ... should be, as I made sure I got the matrix right. But I'd rather they be tested first.

### CODE REVIEW

**Comment by Xyverz** [comment]
Will this require us to rewrite our keymaps?

**Comment by drashna** [comment]
>Will this require us to rewrite our keymaps?
Hell no.  It adds a new keymap/layout to the existing (like how the planck has the grid and 2U/mit layouts), so you have a choice. 

The existing keymaps will continue to work as is (with no modifications).  But if you want to use the new "pretty" keymap layout, then yes, you'd need to rewrite it. Which is mostly just copy and pasting sections so each row is all one line. 

https://github.com/qmk/qmk_firmware/blob/master/layouts/community/ergodox/drashna/keymap.c#L55-L67
https://github.com/drashna/qmk_firmware/blob/4ce34deea20b7271ebba86d0c9e3d616663922e5/keyboards/ergodox_infinity/ergodox_infinity.h#L121-L131


And really just need somebody on an ergodone to test this out now.

**Comment by drashna** [comment]
In fact, it only took about 5 minutes to do this: 
```c
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[_DV] = LAYOUT_ergodox_pretty(
        // left hand
        KC_EQL,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_ESC,         KC_ESC,  KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_SLSH,
        KC_TAB,  KC_QUOT, KC_COMM, KC_DOT,  KC_P,    KC_Y,    XXXXXXX,        XXXXXXX, KC_F,    KC_G,    KC_C,    KC_R,    KC_L,    KC_BSLS,
        KC_CAPS, KC_A,    KC_O,    KC_E,    KC_U,    KC_I,                             KC_D,    KC_H,    KC_T,    KC_N,    KC_S,    KC_MINS,
        KC_LSFT, KC_SCLN, KC_Q,    KC_J,    KC_K,    KC_X,    MO(_MD),        MO(_KP), KC_B,    KC_M,    KC_W,    KC_V,    KC_Z,    KC_RSFT,
        KC_LGUI, KC_GRV,  KC_INS,  KC_LEFT, KC_RGHT,                                            KC_UP,   KC_DOWN, KC_LBRC, KC_RBRC, KC_RGUI,
                                            KC_LCTL, KC_LALT,                          KC_RALT, KC_RCTL,
                                                     KC_HOME,                          KC_PGUP,
                                   KC_BSPC, KC_DEL,  KC_END,                           KC_PGDN, KC_ENT,  KC_SPC
  ),
[_QW] = LAYOUT_ergodox_pretty(
        // left hand
        KC_EQL,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_LEFT,        KC_ESC,  KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,
        KC_DELT, KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    XXXXXXX,        XXXXXXX, KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSLS,
        KC_BSPC, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                             KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    MO(_MD),        MO(_KP), KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,
        KC_LGUI, KC_GRV,  KC_INS,  KC_LEFT, KC_RGHT,                                            KC_UP,   KC_DOWN, KC_LBRC, KC_RBRC, KC_RGUI,
                                            KC_LCTL, KC_LALT,                          KC_LALT, KC_LCTL,
                                                     KC_HOME,                          KC_PGUP,
                                   KC_BSPC, KC_DEL,  KC_END,                           KC_PGDN, KC_ENT, KC_SPC
  ),
[_CM] = LAYOUT_ergodox_pretty(
        // left hand
        KC_EQL,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_LEFT,        KC_ESC,  KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,
        KC_DELT, KC_Q,    KC_W,    KC_F,    KC_P,    KC_G,    XXXXXXX,        XXXXXXX, KC_J,    KC_L,    KC_U,    KC_Y,    KC_SCLN, KC_BSLS,
        KC_BSPC, KC_A,    KC_R,    KC_S,    KC_T,    KC_D,                             KC_H,    KC_N,    KC_E,    KC_I,    KC_O,    KC_QUOT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    MO(_MD),        MO(_KP), KC_K,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,
        KC_LGUI, KC_GRV,  KC_INS,  KC_LEFT, KC_RGHT,                                            KC_UP,   KC_DOWN, KC_LBRC, KC_RBRC, KC_RGUI,
                                            KC_LCTL, KC_LALT,                          KC_LALT, KC_LCTL,
                                                     KC_HOME,                          KC_PGUP,
                                   KC_BSPC, KC_DEL,  KC_END,                           KC_PGDN, KC_ENT, KC_SPC
  ),
[_MD] = LAYOUT_ergodox_pretty(
        // left hand
        RESET,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F11,         KC_F12,  KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  _______,
        _______, _______, KC_PSCR, KC_SLCK, KC_PAUS, _______, _______,        _______, _______, KC_MUTE, KC_VOLD, KC_VOLU, _______, _______,
        _______, _______, _______, _______, _______, _______,                          KC_MSTP, KC_MPRV, KC_MPLY, KC_MNXT, KC_MSEL, _______,
        _______, _______, DVORAK,  QWERTY,  COLEMAK, _______, _______,        _______, _______, _______, _______, _______, _______, _______,
        _______, _______, _______, _______, _______,                                            _______, _______, _______, _______, _______,
                                            _______, _______,                          _______, _______,
                                                     _______,                          _______,
                                   _______, _______, _______,                          _______, _______, _______
  ),
[_KP] = LAYOUT_ergodox_pretty(
        // left hand
        KC_PWR,  _______, _______, _______, _______, _______, _______,        _______, _______, KC_NLCK, KC_PEQL, KC_PSLS, KC_PAST, _______,
        KC_SLEP, _______, _______, _______, _______, _______, _______,        _______, _______, KC_P7,   KC_P8,   KC_P9,   KC_PMNS, _______,
        KC_WAKE, _______, _______, _______, _______, _______,                          _______, KC_P4,   KC_P5,   KC_P6,   KC_PPLS, _______,
        _______, _______, _______, _______, _______, _______, _______,        _______, _______, KC_P1,   KC_P2,   KC_P3,   KC_PENT, _______,
        _______, _______, _______, _______, _______,                                            KC_P0,   _______, KC_PDOT, KC_PENT, _______,
                                            _______, _______,                 _______, _______,
                                                     _______,                 _______,
                                   _______, _______, _______,                 _______, _______, _______
  ),

};
```

**Comment by mechmerlin** [comment]
Think you could fix these errors as well? 
```
"Error: ergodox_ez: KEYMAP_PRETTY_80: Number of elements in info.json does not match! info.json:82 != KEYMAP_PRETTY_80:80", 
"Error: ergodox_ez: KEYMAP_80: Number of elements in info.json does not match! info.json:82 != KEYMAP_80:80", 
"Error: ergodox_ez: LAYOUT_ergodox_pretty: Number of elements in info.json does not match! info.json:78 != LAYOUT_ergodox_pretty:76", 
"Error: ergodox_ez: LAYOUT_ergodox: Number of elements in info.json does not match! info.json:78 != LAYOUT_ergodox:76", 
```

These are from the QMK API Error Log
https://docs.api.qmk.fm/error-log

**Comment by drashna** [comment]
I'm looking at the json file, and I don't see the issue. In fact, I see where the issue is, but .... not how it's happening. 

Specifically, it looks like the top row has 8 buttons. But even in the info file, there is only 14 (7 per side) keys on y:0. 

So .... I have NO idea how this is happening.

**Comment by drashna** [comment]
@jackhumbert This should be good/safe to merge.   

It's been tested on both an ergodox EZ and an Ergodox Infinity, and both work.  The Ergodone hasn't been tested yet, but since it doesn't override anything, it should be safe until somebody can test it out.

**Comment by jackhumbert** [comment]
Perfect - thanks folks!

**Pull request merged**
